### PR TITLE
Proposal for IP infrastructure on Substrate: InvArch

### PR DESCRIPTION
**Pull request by Invarchitect**
### Project Abstract

> InvArch is a next-generation blockchain for intellectual property tokenization, development, & networking.
Under this grant, the [InvArch Pallet Library](https://github.com/InvArch/InvArch-Pallet-Library) would be delivered and would provide an intellectual property tokenization and utility infrastructure for the Substrate ecosystem.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [X] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `InvArch.md`) and updated.
- [X] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [X] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [X] The software delivered for this grant will be released under an open-source license specified in the application.
- [X] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Comment by Invarchitect** [comment]
I apologize for the delay.

We've come to the realization that what we require is our chain with a custom runtime and pallets. We would like to develop and deploy these pallets for the Web3 community to also utilize and build on top of, as well as so that we can integrate them into our own chain's runtime.

> Overall, personally I'm not fully convinced of the idea behind IPTs/DEV itself, but I would still be willing to support the project for the tech of extending RMRK & linking it to smart contracts.

The focus of InvArch is to provide an IP blockchain infrastructure for Substrate and Substrate developers, and then to extend the utility of this infrastructure through a series of application deployments and runtime upgrades. Unfortunately, our primary focus isn't to extend the RMRK standard or link them to smart contracts. Our focus is much more significant for the Substrate ecosystem.

I understand that you're uncertain about the premises behind InvArch; however, I ask that you support us as we explore and test this new technology. If our assumptions are wrong, then it wouldn't be without effort on our end. If our assumptions are correct, then we have the potential to fundamentally decentralize and disrupt many industries and aspects of innovation that presently exist, and provide an entirely new digital asset for developers in the substrate ecosystem.

**Comment by Invarchitect** [comment]
To explain the change in approach:

We realize that **one day** it may be possible to build an MVP of the InvArch networking platform by building on top of pre-existing projects; however, we would be heavily reliant on the development progress and focuses of those projects. 

Building a custom chain using substrate and writing our own custom pallets doesn't just help allow us to design an optimal runtime for our chain's specific use cases, it allows us to more easily integrate and expand these technologies throughout the Substrate ecosystem.

**Review by mmagician — APPROVED** [review]
Sounds like a plan. Good luck with the project!

**Comment by Invarchitect** [comment]
Thank you so much for your review! I promise that given this opportunity, we will dedicate our all to delivering on our milestones and helping to bolster the Substrate ecosystem!

I noticed that the PR says 5 approving reviews are required, are these different from the 3 approvals needed per the Level 2 application status?

Again, thank you so much for your time @mmagician!

**Review by mmagician — DISMISSED** [review]
This is just a github feature - once it reaches 3 approvals it will be merged.

**Comment by semuelle** [comment]
Hi @Invarchitect, couple of questions:

- What does `Pallet_dev` provide that `Pallet_dao` doesn't? The description of a DEV sounds like a DAO owning one or more `IPSet`s to me.
- How are files attached to a token?
- `recieve rewards for when their work is viewed by other users` -- I couldn't find this aspect described anywhere, could you expand what that would look like?
- Could you describe where you see InvArch compared to the current, legal handling of IP and rights management? Is it expected to establish copyright, legally?

**Review by semuelle — CHANGES_REQUESTED** [review]
Hi @Invarchitect, couple of questions:

- What does `Pallet_dev` provide that `Pallet_dao` doesn't? The description of a DEV sounds like a DAO owning one or more `IPSet`s to me.
- How are files attached to a token?
- `recieve rewards for when their work is viewed by other users` -- I couldn't find this aspect described anywhere, could you expand what that would look like?
- Could you describe where you see InvArch compared to the current, legal handling of IP and rights management? Is it expected to establish copyright, legally?

**Comment by Invarchitect** [comment]
Hi @semuelle! Thank you for taking the time to look over our proposal. I've updated our proposal to directly address your questions, but will overview briefly below:

> What does Pallet_dev provide that Pallet_dao doesn't? The description of a DEV sounds like a DAO owning one or more IPSets to me.

`Pallet_dev` serves to initialize and structure the required/requested roles a project needs and their IP Ownership allocations, sets its milestones/deliverables, copyright terms, if any, and decides its application process. A DEV can also be imagined as a digital representation of a real-world development project.

`Pallet_dao` will solely be focused on proving the governance logic in our runtime. We would prefer to keep these separate, as we would like to explore expanding the `Pallet_dao` to include multi-layer governance capabilities in the future.

> How are files attached to a token?

IPFS or Interplanetary File System allows data and IP contents to be securely stored off-chain and given a CID, or content identifier, that serves as a unique hash and is used to mint IP Tokens. The InvArch protocol will include the [`ipfs_api`](https://docs.rs/ipfs-api/0.11.0/ipfs_api/) crate to help achiave this.

>"receive rewards for when their work is viewed by other users" -- I couldn't find this aspect described anywhere, could you expand what that would look like? That's something we wish to explore in the future, possibly under a separate grant. I didn't intend to have that there when I committed. It's been removed. 

>Could you describe where you see InvArch compared to the current, legal handling of IP and rights management? Is it expected to establish copyright, legally?

It can only establish "legal" copyright where NFTs are recognized as such; however, it serves as a very powerful tool in those instances. Regarding registering copyright, we would like to explore streamlining this process between users and centralized entities (legal institutions) in the future. Our focus now is developing the underlying architecture required to build these features.

**Review by semuelle — APPROVED** [review]
Thanks for the quick reply.

**Review by mmagician — APPROVED** [review]

**Review by Noc2 — APPROVED** [review]

**Comment by alxs** [comment]
@Invarchitect any updates on the second milestone?

**Comment by alxs** [comment]
@Invarchitect @SHA888 do you still intend to finish the grant? If you can't submit the second milestone within the next 2-3 weeks, could you please submit an amendment to adjust its duration?

**Comment by alxs** [comment]
@Invarchitect @SHA888 note that if we don't hear from you within the next two weeks, we'll assume you're no longer interested and terminate the grant.

**Comment by Invarchitect** [comment]
@alxs I'm really sorry for the delay. We've had a lot of needed improvements & changes take place around the project over the course of the last several months, some of them being expansive. We're not looking to implement the DEV protocol; rather, focusing on 1: IP file composability, pegged assets & sub-assets, licensing, & cross-chain authentication (XCA).

I believe it's best if we submit an amendment and just focus on providing a more composable IP Pallet package, we'll be providing the latter tech, but through milestones in a builders program. I will have the amendment ready by this Wednesday if that's acceptable?

**Comment by alxs** [comment]
@Invarchitect sounds good! We'll gladly review the amendment.

**Comment by alxs** [comment]
@Invarchitect friendly reminder.

**Comment by semuelle** [comment]
@Invarchitect @SHA888 If we don't hear back from you or receive an amendment until next week, we'll assume you are no longer interested in pursuing it and will cancel the grant. You are free to reapply anytime.

**Comment by Invarchitect** [comment]
@semuelle, we're finished development on the work under the grant (considering our changes, as well). 

I apologize for not pushing an amendment sooner. I promise to have updated by the weekend & ready for your review coming into next week. We're excited for your review!

**Comment by Invarchitect** [comment]
Hey @semuelle, I just submitted [PR #950](https://github.com/w3f/Grants-Program/pull/950) as mentioned above. 
If I filled out anything incorrectly or against the standard procedures, please let me know & I'll get on top of it ASAP.

**Comment by alxs** [comment]
@XCAstronaut a reminder to submit the next milestone, seeing as the amendment was accepted 2 weeks ago and assuming your intention was to submit immediately.

**Comment by XCAstronaut** [comment]
@alxs, we are internally reviewing the code for the INV4-Git middleware now to make sure everything is in perfect order.

I will be traveling in about 12 hours, but I should hopefully be submitting our completed proposal within the next 24 hours.

**Comment by alxs** [comment]
Hey @XCAstronaut, thanks for the update. Feel free to submit when you're ready. It's great to hear you want to deliver a mature product.

**Pull request merged**
