### PR TITLE
societal application update

### PR DESCRIPTION
**Pull request by gfox1**
Societal Web3 Grant

This PR is an update to Societal Web 3 Grant [Application](https://github.com/w3f/Grants-Program/blob/master/applications/Societal.md) and https://github.com/w3f/Grants-Program/pull/952.

#### Project Abstract

> Please replace these instructions with a brief description of your project summarizing key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by gfox1** [comment]
Hi @Noc2 and @alxs, this PR is an update to my previous [PR](https://github.com/w3f/Grants-Program/pull/1246), that I closed by accident while syncing my fork. Hopefully the edits in this PR are easier to read. Apologies for the confusion.


Below I will include some information from the previous PR and answer your questions. 

Hi there, this PR is an update to Societal original application.

I would like to switch out two milestones for a new one - DAO Factory Pallet. Milestones 2 & 3 will come in the future, but to get to that point we have to build out our DAO Factory pallet. Therefore, I was hoping that I would be able to modify the grant to have our DAO Factory pallet as our main submission?

The DAO Factory Pallet would allow you to do the following:

Create a DAO

Create a token for your DAO - Currently using the assets pallet to do this

Setup a treasury for your DAO - Currently using the treasury pallet

Select a governance system for your DAO - Implementing Governance V1 to be used for DAOs

Please let me know if this is a suitable modification. We will have the DAO Factory pallet ready in 2 weeks to submit.

**Comment by gfox1** [comment]
@Noc2 I will answer your previous question below. 

`Thanks for the update. It’s usually easier if you change the original application rather than replacing it entirely. This way it’s more difficult to see the changes. Could you still sign the latest version of the terms and conditions? Regarding the amendment: It looks like you replaced Cross-Chain Smart Contract Execution via an Approved Governance Proposal as well as the “SaaS Pricing Model Pallet” with only one pallet. What is the reason for this? Could potentially integrate the cross-chain part again or reduce the price?`

I have made this new PR with a synced node, so you should be able to see the changes more clearly. Yes, I am replacing the Cross-Chain Smart Contract Execution via an Approved Governance Proposal as well as the SaaS Pricing Model Pallet. The reason for this is change is that for me to get to the stage of developing those two items, I have to build out the DAO Factory pallet first. So I would like to submit our development of our DAO Factory pallet, which we are using as our MVP. This show our ability to develop substrate pallets and give us additional resource to develop the other items. 

In regards to price, I have lowered the total cost of the grant to 30k USD.

**Comment by gfox1** [comment]
@alxs I will answer your [question](https://github.com/w3f/Grants-Program/pull/1246#issuecomment-1300384911) here. 

> @gfox1 you might need to sync your fork. Also note that according to the current [levels](https://github.com/w3f/Grants-Program#level_slider-levels), your grant would need 5 approvals, so it would also make sense to reduce the price in this regard.

Thanks for pointing out the sync to my fork. I have now synced the fork. In regards to the current grant levels, I have lowered the grant to 30k USD to be within level 2.

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I'm happy to mark it as ready for review and go ahead with it.

**Review by keeganquigley — APPROVED** [review]

**Pull request merged**
