### PR TITLE
submit Move pallet RFP Phase 1

### PR DESCRIPTION
**Pull request by Nikhil-Desai-Talentica**
#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [] **Level 2**:  Up to $30,000, 3 approvals
- [] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by semuelle** [comment]
Thanks for the application, @Nikhil-Desai-Talentica, and sorry for the long wait. I will look into it as soon as possible.

**Review by Noc2 — CHANGES_REQUESTED** [review]
@Nikhil-Desai-Talentica Could you create two separate PRs for the new application and the amendment of the old one?

**Review by semuelle — CHANGES_REQUESTED** [review]
Hey @Nikhil-Desai-Talentica. I think the Pontem Move VM is already fully `no-std` compatible: 
- https://github.com/pontem-network/sp-move-vm/commits/90491b8ca453472b01f3c0f0a54381a57a3ac1ea
- https://github.com/pontem-network/sp-move-vm/blob/b1645fdab76beff58b849ac8581226a0eccc927d/README.md#differences. 

I think we can jump to Phase 2. :)

**Comment by semuelle** [comment]
I am closing this PR due to inactivity. Please let me know if you plan to continue working on the application so I can reopen the PR.

**Pull request closed without merging**
