### PR TITLE
Protico: Web3-Powered Community Success for Web2 brands

### PR DESCRIPTION
**Pull request by howieyoung**
#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) or BTC address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by howieyoung** [comment]
I have read and hereby sign the Contributor License Agreement.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Could you add more technical details to the specification of the milestone tables? For example, are you going to use ink! smart contracts? What exactly are you planning to implement for the Auto-Reward System? How do you prevent Sybil attacks, etc.?

**Comment by howieyoung** [comment]
> Thanks for the application. Could you add more technical details to the specification of the milestone tables? For example, are you going to use ink! smart contracts? What exactly are you planning to implement for the Auto-Reward System? How do you prevent Sybil attacks, etc.?

Thank you for the questions @Noc2 
Considering the capacity that our team has, we will build the smart contracts with Solidity first cause it's something we are familiar with the most. But we are open to build it with ink! if we can go with the a higher grant level at 3 to get more FTE.

The auto-reward system will be used with our Web3 Lobby regarding users' engagement onto brands' websites and apps.
Flow: Brands implement Web3 Lobby onto their products > Users engage in the lobbies > Brands reward users regarding their engagement through our auto-reward system.

The sybil attacks issue is important but it would be handled case by case according to the brands' goals and the rewards they set cause the rewards would be not real money but things like memberships or coupons that brands want to issue as more as possible.
But we do will give them options to set rules about how they want the auto-reward system to work for them. This will be widely different from each cases so that we didn't list it in the milestone tables. Hopefully that makes sense to you.

**Comment by dsm-w3f** [comment]
@howieyoung thank you for the grant application. If you want to discuss this application in private, you can select the option "I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: @_______:matrix.org (change the homeserver if you use a different one)" in the PR, and provide a matrix handle, in this way, we can create a channel to discuss this properly. I noticed that you made this same application in private, we can discuss it by e-mail as well. Let us know what is your preference for communication about this grant proposal.

**Review by dsm-w3f — CHANGES_REQUESTED** [review]
Changes requested by e-mail.

**Comment by keeganquigley** [comment]
pinging @howieyoung are you still planning to make the requested changes?

**Pull request closed without merging**
