### PR TITLE
Create Decentralized and Trustworthy AI enabled by Polkadot.md

### PR DESCRIPTION
**Pull request by JelYin**
Create a new grant application

#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
> Enabling Decentralized and Trustworthy AI Services on Blockchain
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by dsm-w3f — CHANGES_REQUESTED** [review]
Thank you for the application. I notice that the deliverables in the milestones are not compliant with our [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md). Could you please adjust to include the mandatory ones and also the specific ones for developing the proposed software? You can take a look at other applications to see examples of how to describe the milestone deliverables. 

Regarding the content of the application, could you please add more technical details on how you intend to achieve the aims of the proposal? How do you plan to develop the properties proposed in the application using substrate and Polkadot technologies? In special, the ones listed below: 
* Protecting the privacy of personal data used for AI
* Tracing the source and usage of data
* Self-verify the correctness and compliance of their computation results
* zero-knowledge proofs (this one is actually needed?)

**Comment by JelYin** [comment]
Dear @dsm-w3f:
Hello! Thanks for your golden critiques and feedback. We have revised and resubmitted our milestones according to the template. As for more technical details:
 
> * Protecting the privacy of personal data used for AI

We will encrypt the data used for AI via [homomorphic encryption](https://en.wikipedia.org/wiki/Homomorphic_encryption) so for users they can protect their data privacy while using and contributing to AI. For AI developers and service providers, they can train, improve and run AI smoothly with privacy-preserving data.

> * Tracing the source and usage of data

The data here refers to the online usage and activities of users that can be tracked on chain like transactions, states, and accounts. After encrypted, users' data will be stored on [decentralized storage](https://wiki.polkadot.network/docs/build-storage) and traced on blockchain. In this way, their integrity, validity, and legality can be verified to be used for AI.

> * Self-verify the correctness and compliance of their computation results

As the execution of AI will be done off chain, we will use zero knowledge proofs like [ZK-SNARK](https://medium.com/@danieldkang/trustless-verification-of-machine-learning-6f648fd8ba88) to verify the correctness of computation in a simple, fast, and privacy-preserving way. Specifically, given the encrypted data and AI model as inputs, we can simply check the proofs to validate the computation results as outputs without performing the computation by ourselves again.  

> * zero-knowledge proofs (this one is actually needed?)

As mentioned above, we will apply zero-knowledge proofs to provide reliable, verifiable, and privacy-preserving AI. With zero-knowledge proofs, in AI training and modeling, we can improve AI and verify the improvement is valid with encrypted data given by users. In AI execution and computation, we can verify the computation results of AI performed by a third-party is correct easily.


This is the research proposal for our development plan above. The general solution will be like this but the details haven't been all found and determined yet. Given the grant we can do further research and start the actual development, and at that time we can figure out more detailed and practical issues, and address them to finish our project! Thanks a lot!

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Regarding the milestone delivery tables, could you be more specific? For example, what exactly are "core functionalities and features"? Also, we usually ask teams to provide some initial designs or mock-ups for UI-focused deliverables.

**Comment by JelYin** [comment]
Dear @Noc2:
Hello!

Thanks for your review and critiques! We plan to design and develop the following core functionalities and features in our project:

**1. Decentralized AI training via privacy-preserving contributor data:** Everyone can contribute their data to AI modeling and training. We will protect data security and privacy, verify data integrity and validity, and have a token model to give contributors corresponding returns as incentives. 

**2. Decentralized AI improvement and public auditing:** Everyone can upgrade and improve AI algorithms to optimize their performance, and they will be rewarded according to their their contributions. Everyone can also help correct any bias, discrimination, and mistakes within AI and reach consensus on essential settings and parameters involving public interests to make AI ethical, constitutional and justicial.

**3. Trustworthy verification of AI execution results via ZKML:** As the intelligence of AI can approach even exceed human beings, people are hard to validate the outputs of AI by themselves. With ZKML people can verify the computation results of AI quickly to ensure their correctness and authenticity as expected. With blockchain, everyone can self-verify those AI providing public services and involving public benefits to ensure they are fully reliable and trustworthy.

We plan to design and develop front-end user interfaces in our deliverables so everyone can use our project easily. They will be made during our development in the fist milestone together when we develop our system in the back end. Only when we determine and start our system development can we build the front-end for our client on top of that.

Any other questions feel free to ask us and we will answer in time. Thanks a lot!

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the reply here. But you need to update the application itself and the technical details described in the milestone tables.

**Comment by JelYin** [comment]
Dear @Noc2:
Hello!

Sure thanks to your golden feedback, we have revise our **Project Component part** to include the core functionalities and features of our project, and revise **Milestones part** to have more specific timeline.

Thanks a lot for your kindly help and hope can get your endoresment!

Kindly Regards,
Jel Yin

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. But it's still not clear to me what these substrate modules and ink! smart contract will provide exactly. For example, what exactly do you need to implement for "Public AI improvement, auditing, and consensus"? Additionally, why do you develop ink! smart contracts as well as substrate modules and how will you split the functionality between them?

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update here. However, the specifications of the milestones are still missing a lot of details. For example: what does "We will deliver a set of ink! smart contracts as the source code for testing our project" mean? Or what does "A substrate will be used to encrypt data for protecting data privacy." mean? At the current stage, I personally won't approve the application, but I will mark it as ready for review and share it with the rest of the team. Maybe others have a different opinion here.

**Review by dsm-w3f — COMMENTED** [review]
I agree with @Noc2. Although there is high-level information about the scope of the grant proposal, it lacks technical details that specify how the scope will be developed. Without that, it is not possible to evaluate the feasibility of the development. For this reason, I won't approve it.

**Comment by JelYin** [comment]
Dear @Noc2 and @dsm-w3f:
Hello!

Thanks for your critiques and feedback! Yes as we are a team of PhDs and researchers on blockchain and AI, we intend to do it as a research project first, and we really need your support to do so. Also although the intersection of blockchain + AI is promising, it's still in the early stage and a lot of systematic and scientific research and design work need to be done before moving into actual development and deployment, so it's unpractical to give specific technical details and deliverables at this time without your endorsement of our research and design work. Therefore we can revise our proposal and apply for your research grant instead if it works for you, and your assistance is really crucial and needed! Thanks a lot!

**Comment by dsm-w3f** [comment]
@JelYin thanks for the answer. Feel free to apply for a research grant. Probably a research grant is more suitable for the stage that you currently are in your project. Please notice that the [research application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template-research.md) is different from the one used in development applications. As the technical details cannot be provided and you want to apply for a research grant, my suggestion is to close this application. We can only support one grant per team at a certain moment at time.

**Comment by semuelle** [comment]
pinging @JelYin

**Pull request closed without merging**
