### PR TITLE
propose research on smartcontract automation protocol

### PR DESCRIPTION
**Pull request by Nikhil-Desai-Talentica**
#### smartcontract automation protocol
Smartcontract Automation Protocol enables Polkadot developers to schedule calls to their smartcontracts that will be honored by decentralized infrastructure.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) or BTC address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. I have one initial question: How is this project specifically beneficial for the Polkadot ecosystem? At the moment, it seems rather generic and theoretically could also be funded by any other foundation in the space. For example, are you planning to focus on ink! or any other Polkadot native technology or architecture?

**Comment by Nikhil-Desai-Talentica** [comment]
Hi David,
Yes, we intend to design and implement it by keeping in mind the Polkadot ecosystem. This has been mentioned in passing in the application. I did create a vague, unstable flow involving Ink! smartcontracts but held off on including them in here for two reasons,
1. It is unstable and our high-level design may diverge considerably from it. So all it could do was create confusion.
2. While it is definitely easier to implement this idea in Ink!, especially because our target entities are smartcontracts and the interplay between them will be much easier, we have not completely ruled out Pallets yet.

Thanks for showing interest in our proposal and we welcome your questions. Have a great day!

**Review by dsm-w3f — CHANGES_REQUESTED** [review]
@Nikhil-Desai-Talentica thank you for the grant application. If you are applying for a research grant please use our [research grant template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template-research.md). Furthermore, I think we do have one specific network that deals with automation in the Polkadot ecosystem (https://oak.tech/). How does your research relate to this network, and what is the intention to produce after this grant? Would be something similar to OAK?

**Comment by keeganquigley** [comment]
pinging @Nikhil-Desai-Talentica

**Comment by semuelle** [comment]
I am going to close this application due to inactivity. Please let me know if you would like to continue working on it, @Nikhil-Desai-Talentica, and I'll reopen.

**Pull request closed without merging**
