### PR TITLE
zkWasm Rollup: Rollup Transfer Transactions based on Wasm

### PR DESCRIPTION
**Pull request by ashWhiteHat**
#### Project Abstract

We are going to implement rollup transfer transactions technology by `zkWasm`. This has both side of [zk rollup](https://github.com/barryWhiteHat/roll_up) and [zk-evm](https://github.com/privacy-scaling-explorations/zkevm-circuits). `zkWasm Rollup` generates proof for `VM` so it's similar to `zkEvm` and aggregate transfer transactions so it's similar to `zk rollup`. There are two main benefit. One is that we can use `zkWasm` for general purpose unlike `zk rollup`. Another is that we can use simple rollup scheme unlike existing rollup technology. This can expand the possibility of Substrate because of supporting Wasm rollup and implementing L2 scheme as built-in of mainchain.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (aUSD/USDT) address for the payment of the milestones is provided in the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [x] I am okay anywhere we talk but if it's complicated or it takes time, feel free to ping me on telegram(@ashWhiteHat) and element(@ashwhitehat:matrix.org).

### CODE REVIEW

**Review by Noc2 — APPROVED** [review]
Thanks for the application. This looks really good. I'm personally happy to go ahead with it, but let me share it with @mmagician for additional feedback before I share it with the rest of the team.

**Review by takahser — APPROVED** [review]
Happy to approve as well, LGTM. 👍

**Comment by keeganquigley** [comment]
Thanks @ashWhiteHat looks really good, but are you able to specify which type of license it will fall under? Currently, your application displays the template text listing all four.

**Comment by ashWhiteHat** [comment]
Hi @takahser @keeganquigley 
Thank you for the review.
I specified the license according to your review.

I would appreciate it if you could confirm.
Thank you!

**Review by takahser — APPROVED** [review]

**Comment by mmagician** [comment]
1. Do you have any refernce implementation for these specific optimizations for JubJub? Could you commit to creating a PR with your new changes to [zkcrypto](https://github.com/zkcrypto/jubjub) upstream?
2. `circuit implementation [...] We are going to implement zero knowledge circuit which supports combination of plookup and recursive proof. This circuit allows us to implement the circuit for zkwasm.` I'm not sure what that means, and what is this `zkwasm` that you keep mentioning? If you are planning to support [every single wasm instruction](https://pengowray.github.io/wasm-ops/) in a circuit, that sounds like a lot of work. Also Milestones 2.3 & 3.1 seem to be the same in essence.
3. `proof verification implementation [...] This is implemented on on-chain.` - how is this realized on-chain?
4. Why sapling and not halo2? I don't know about frontends for building sapling circuits, but the halo2 APIs seem to be quite popular among circuit builders, and it supports lookup tables, custom gates and recursion out-of-the-box.

**Comment by ashWhiteHat** [comment]
Hi @mmagician 
Long time no see and thank you for the review!
> Do you have any refernce implementation for these specific optimizations for JubJub?

This is totally original optimization so there is no reference.
You can imagine part of these by [this](https://github.com/zero-network/zero/pull/60/files) changes.

In above changes, I implemented Naf representation and it's binary representation with sign.
Comparing with [`zkcrypto/jubjub` representation](https://github.com/zkcrypto/jubjub/blob/main/src/lib.rs#L283), Naf representation can reduce hamming weight to $\frac{n}{6}$ where n is bits number of field and also clean the zero [here](https://github.com/zero-network/zero/pull/60/files#diff-42968ca17fb4c150ad3280e899e0917997489b7c14606e100ec0cfd9778f7e5cR81).
Eventually, this reduces $\frac{n}{6}$ times elliptic curve addition and sum of $\frac{n}{2}$ geometric series curve doubling.
I benched it and ensured that it worked: https://github.com/zero-network/zero/issues/44#issuecomment-1399381991

We can reduce elliptic curve addition by extending the window size so the elliptic curve doubling is more important and that's why we would like to introduce `Jacobian coordinates`.

About wNaf and pippenger, I am going to introduce quadruple and the fourth power for elliptic curve and field for each. About field square, we can rollup the limbs arithmetic as [doubling](https://github.com/zero-network/zero/blob/master/primitive/crypto/src/arithmetic/limbs/bits_256/normal.rs#L74). To implement fourth power, it can just perform as bitshift 4 as the same with square and skip one time montgomery reduction.

> Could you commit to creating a PR with your new changes to [zkcrypto](https://github.com/zkcrypto/jubjub) upstream?

I would be happy to contribute but previous time I created PR to zcash team, it took for a month to be merged. I think the optimization is not high priority for them and that's why we implemented crypto libraries from scratch. If we depend on external team library, it would be hard to immediately apply optimization and keep dealine.

> If you are planning to support [every single wasm instruction](https://pengowray.github.io/wasm-ops/) in a circuit, that sounds like a lot of work

I totally agree about this that's why in this milestone, we are focus on the wasm opcodes related to transfer. And actually, the wasm instruction circuits are not so difficult to implement. I implemented zkevm `MLOAD`, `MSTORE` and `MSTORE8`, `MSIZE` by one day. I think lookup table combination and consistency check are hardest parts. The transfer only uses account key value storage so we can reduce so much workload. We would like to finally support all operation but in this milestone, we would like to implement basic cryptographic primitive and structure.

> Also Milestones 2.3 & 3.1 seem to be the same in essence.

In Milestones 2.3, we implement plookup and recursive proof and in Milestones 3.1, we implement circuit for opcodes, lookup  table for state db and circuit combining together.
Milestone 2 is for plonk implementation and Milestone 3 is for zkwasm circuits.

> proof verification implementation [...] This is implemented on on-chain. - how is this realized on-chain?

We support the transfer zkwasm so firstly, we compile circuit and generate verification key. Secondly, we hardcode it on chain. In previous our grant [zero-network confidential transfer](https://github.com/zero-network/zero/tree/master/pallets/confidential_transfer) did the same thing so I would like you to check.

> Why sapling and not halo2?

The reason why we implement part of sapling is to delegate the proof generation and related to digital signature arithmetic. I think these are totally different.

> the halo2 APIs seem to be quite popular among circuit builders, and it supports lookup tables, custom gates and recursion out-of-the-box.

Making halo2 compatible with substrate takes so much time because it's complicated more than `dusk-plonk`. I already made plonk library compatible three times. First time is [zk rollup](https://github.com/zero-network/Grants-Program/blob/zkwasm-rollups-transfer/applications/zk-rollups.md), second time is [zk-plonk](https://github.com/zero-network/Grants-Program/blob/zkwasm-rollups-transfer/applications/zk-plonk.md) and third time is [zero-network](https://github.com/zero-network/Grants-Program/blob/zkwasm-rollups-transfer/applications/zero-network.md). When we try to use plonk on Substrate, we need to rewrite almost every parts of plonk, jubjub, bls12-381 and polynomial, field and so on. I think to use halo2 is not feasible option and I already implemented [dusk-plonk](https://github.com/zero-network/dusk-plonk) with parity compatible library in previous milestone. We would like to use it.

And we would like to follow hermez zkevm strategy to prove the VM. It joins the lookup tables. It's hard for halo2. If we use halo2, we need to check consistency by sharing column and somehow combine these together. I would like to know if you have any idea.

Sorry for long text.
I would appreciate it if you could confirm.
Thank you!

**Review by Noc2 — APPROVED** [review]
I'm still happy to go ahead with it.

**Review by randombishop — APPROVED** [review]
LG

**Review by dsm-w3f — APPROVED** [review]

**Comment by keeganquigley** [comment]
Hi @ashWhiteHat how is Milestone 1 coming along?

**Comment by ashWhiteHat** [comment]
Hi @keeganquigley 
Thank you for the notification!

We completed half part of Milestone 1 and 2.
https://github.com/KogarashiNetwork/jubjub
https://github.com/KogarashiNetwork/dusk-plonk

First milestone will be delivered the end of next month.

**Comment by keeganquigley** [comment]
thanks @ashWhiteHat for the update, much appreciated. Since the delivery date is a couple of months away, could you file a PR to amend the timeline? That way you can change the subsequent milestone dates as well to take the pressure off. Thanks!

**Comment by ashWhiteHat** [comment]
Hi @keeganquigley 
I created PR for amendment.
https://github.com/w3f/Grants-Program/pull/1788

Sorry for the inconvenience.
I would appreciate it if you could confirm.
Thank you.

**Comment by keeganquigley** [comment]
Hi @ashWhiteHat how is M3 coming along?

**Comment by ashWhiteHat** [comment]
Hi @keeganquigley 
It was removed as I explained as follows.
https://github.com/w3f/Grants-Program/pull/1788#issuecomment-2197001087

I would appreciate it if you could confirm.
Thank you!

**Comment by keeganquigley** [comment]
Thanks @ashWhiteHat no problem, I will fix it in our records. Thanks!

**Pull request merged**
