### PR TITLE
Solidity SCALE Codec Implementation

### PR DESCRIPTION
**Pull request by Doordashcon**
#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (aUSD/USDT) address for the payment of the milestones is provided in the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks for the application @Doordashcon generally we don't support Solidity development because we aren't experts when it comes to Solidity libraries and contracts. I appreciate that this library might be needed by the community, but in my opinion our focus should be on WASM and not EVM architecture. Moonbeam (or other parachains that support EVM) on the other hand, might want this; you can find their grants program [here](https://moonbeam.foundation/grants/). 

So I personally won't approve it at this stage but I will mark it as ready for review and share it internally with the committee.

**Comment by randombishop** [comment]
Hi @Doordashcon !
Thank you for submitting this application. Can you please provide a couple of examples of how your library consumers would need to use SCALE encoding in solidity context?
More generally, what motivated you to build this library?

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. I have one initial question, how would your solution be different from existing solutions? See for example
- https://github.com/darwinia-network/darwinia-messages-sol/blob/master/contracts/utils/contracts/ScaleCodec.sol 
- https://github.com/Snowfork/snowbridge/blob/main/core/packages/contracts/contracts/ScaleCodec.sol

**Comment by Doordashcon** [comment]
Hello @Noc2 these implementations lack support for enum{option/result}

**Comment by Doordashcon** [comment]
Hello @randombishop  in the context of verifying state proofs from parachains on the EVM, a more robust version of the SCALE Codec is required, to that end we present the solidity trie verifier [here](https://github.com/w3f/Grants-Program/pull/1486)

**Review by Noc2 — CHANGES_REQUESTED** [review]
In this case, could reuse their code? 30k for enum{option/result} sounds a little bit expensive to me. Also, something to be aware of, we usually only support one project per team initially. So my recommendation would be to close one of the applications or combine them.

**Comment by Doordashcon** [comment]
After further analysis we've discovered these scale implementations lack the ability to decode `Vec<u8>`  into `Vec<Vec<u8>>`, when a storage proof is retrieved from a parachain node, it is provided as  `Vec<Vec<u8>>`, but when this proof is sent across the wire ideally it needs to be encoded into a `Vec<u8>` to make it more compact.

We will includes these additional features in the [trie verifier](https://github.com/w3f/Grants-Program/pull/1486) as a separate milestone.

**Pull request closed without merging**
