### PR TITLE
NFT infrastructure | by walt.id

### PR DESCRIPTION
**Pull request by philpotisk**
#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [x] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@pp21:matrix.org`

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the application. Could you add the level to the overview section at the beginning of the application, see https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md Also could you update the overview section under the development roadmap and remove the none bold text? Finally, it’s not fully clear from the application what kind of NFTs you will support in our ecosystem, e.g. pallet implementation or ink smart contracts. Could you clarify this and add more technical details to the deliveries?

**Comment by philpotisk** [comment]
Hi @Noc2 thanks for your feedback. I updated the application accordingly.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. Could you add the programming language to the specification of the deliveries? Furthermore, we would probably prefer to have a pallet-based implementation (https://github.com/paritytech/substrate/tree/master/frame/uniques, https://github.com/rmrk-team/rmrk-substrate/tree/main/pallets/rmrk-core) or an ink-based implementation (https://github.com/paritytech/ink/tree/master/examples/erc721), over the evm support. So it would be nice if you would definitely work on this, instead of having it optional (“will look into NFT specific solutions like Uniques”). It doesn't need to work with a live parachain.

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I’m happy to go ahead with it and I will share the application with the rest of the team.

**Review by alxs — APPROVED** [review]
LGTM!

**Review by keeganquigley — APPROVED** [review]
LGTM

**Comment by keeganquigley** [comment]
Hi @philpotisk any updates on how milestone 1 is coming along?

**Comment by philpotisk** [comment]
> Hi @philpotisk any updates on how milestone 1 is coming along?

Hi @keeganquigley we have completed this milestone (which is actually the whole project). Please review our PR here https://github.com/w3f/Grant-Milestone-Delivery/pull/837 
Thanks for you feedback in advance!
Phil

**Pull request merged**
