### PR TITLE
Grant application for Lastic - A UI interaction for the coretime chain

### PR DESCRIPTION
**Pull request by poppyseedDev**
#### Project Abstract

Lastic aims to create a blockspace marketplace on the Polkadot network, aiming to democratize access to Polkadot blockspace with a focus on streamlining the purchase and sale of 'Coretime'. The platform's vision is to standardize blockspace pricing and introduce tailored payment solutions, potentially branching into subscription and futures-based offerings.

Limited to the functionality of the Coretime chain not being on testnet yet, this proposal accentuates the development of a dedicated **user interface (UI) for the Coretime Parachain** exposing limited interactivity, coupled with a static mockup for the chain.

As the project progresses, Lastic envisions broadening its capacities, encompassing functionalities such as core fragmentation and integrating secondary market transactions.

This application is not a follow-up to a previous grant.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) or BTC address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@aurora721:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by phillux** [comment]
I have read and hereby sign the Contributor License Agreement.

**Comment by semuelle** [comment]
Thanks for the application, @poppyseedDev and @phillux. You provided a Matrix handle in the PR but didn't check the corresponding item. Would you like the discussion to be private?

**Review by Noc2 — CHANGES_REQUESTED** [review]
Just some very quick initial feedback: We don't pay teams in DOTs. See  https://grants.web3.foundation/docs/Process/how-to-apply regarding your options.

**Comment by phillux** [comment]
> Thanks for the application, @poppyseedDev and @phillux. You provided a Matrix handle in the PR but didn't check the corresponding item. Would you like the discussion to be private?

We're ok with the discussion being public.

**Comment by phillux** [comment]
> Just some very quick initial feedback: We don't pay teams in DOTs. See https://grants.web3.foundation/docs/Process/how-to-apply regarding your options.

Updated the application to request BTC instead of DOT

**Review by semuelle — APPROVED** [review]
Hey @poppyseedDev and @phillux. Thanks again for the application. You have clearly put a lot of time and thought into the proposal. I am happy to approve it and share with the rest of the committee.

**Review by keeganquigley — APPROVED** [review]
Thanks @phillux this looks really good. During Sub0 I was intrigued by the notion of having a secondary market for blockspace. Glad to see you are one step ahead, happy to approve also.

**Review by Noc2 — APPROVED** [review]
Given it's a level 1 grant, it's already approved, but I'm happy to approve it as well and merge it.

**Pull request merged**
