### PR TITLE
DOTLY: Revolutionizing Polkadot Account Statistics

### PR DESCRIPTION
**Pull request by justmert**
#### Project Abstract

DOTLY is an innovative platform that transforms Polkadot account statistics into an insightful and entertaining experience.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [X] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [X] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [X] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [X] The software delivered for this grant will be released under an open-source license specified in the application.
- [X] The initial PR contains only one commit (squash and force-push if needed).
- [X] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by keeganquigley — CHANGES_REQUESTED** [review]
Thanks for the application @justmert a couple of initial questions/comments:

- This is a unique approach, and the gaming element could help onboard new Polkadot users. Can you elaborate more on what **Score** and **Level** pertain to and how they are calculated?
- Are there plans to build tools to monitor XCM transfers? For example, this is Subscan's [XCM Dashboard](https://polkadot.subscan.io/xcm_dashboard).
- I see cross-chain functionalities under future plans, and this is important since a lot of activity takes place on parachains. Would you eventually aim to compete with sites such as [Sub.ID](https://sub.id/) which displays a cross-chain balance?
- Personally I think that it's a bit expensive, especially for the dashboard-focused milestone 2.
- The mandatory deliverables 0a. - 0e. are meant to be included in both milestones. Could you please add these to M2? The article is only mandatory for the last milestone.

**Comment by keeganquigley** [comment]
Thanks for the updates @justmert, it's looking better now. The only thing missing is _0e. Article_ for milestone 2, which isn't a huge deal, but personally I think a quick blog article is rather important for this project in order to promote it and start getting users interested in the features it offers.

That being said, I will go ahead and mark the application as ready for review so other committee members can leave questions and/or comments.

**Review by keeganquigley — APPROVED** [review]
Thanks @justmert for the updates, I'm happy to see the XCM functionalities being included in the grant, and I agree that it warrants a higher price. I'm happy to go ahead with it.

**Review by Noc2 — APPROVED** [review]
I'm happy to support it as well. Btw. regarding [Polkaflow](https://polkaflow.xyz/projects) are you aware of https://wiki.polkadot.network/docs/build-open-source

**Review by semuelle — CHANGES_REQUESTED** [review]
Thanks for the application, @justmert. 

- Do I understand correctly that I can paste anyone's account into the search bar and get these statistics on them? Or does it require siging a message?
- I noticed that you added Google Analytics to the Polkaflow frontend. Could you share some user numbers?
- Have you applied or are you planning to apply for any other grants with this?
- What are your long-term plans with Dotly? How are you planning to fund maintenance and development after the grant?

**Review by semuelle — COMMENTED** [review]
Thanks for the updates and sorry for the late reply, @justmert. My conclusion is that this project, or at least parts of it, would be a better fit for a wallet, where this information might be used for analysis and accumulated across accounts and is only accessible for the owner. I am also not too keen on the gamification idea. 

I will ping the rest of the committee again, they might be of another opinion.

**Comment by semuelle** [comment]
Since this application hasn't garnered any approvals in five weeks, I am closing it. Thank you for putting in the effort, @justmert, and engaging with us. I hope you'll find a way of making this project a reality. Feel free to apply again in the future.

**Comment by takahser** [comment]
@justmert thanks for reaching out to me here. I've actually skimmed the application and was hesitant to give my approval, but didn't find the time to state my opinion here. Hence, I'm going to do this now.

Unfortunately, I won't approve it neither due to the following reasons:
- personally I don't see much value in that application on itself
- if it was embedded into a wallet, it might be more useful
- similar to what was already stated in the conversation above, I'm not convinced of the gamification aspects of your proposal

Nevertheless, I wish you all the best for the future of this project and I hope you'll prove me wrong. 👍😃

**Comment by Noc2** [comment]
Just clarify here: None of the other committee members were willing to proceed with the application. Therefore @semuelle closed it. If you want to change the application, I can either reopen it, or you can simply create a new PR. That said, after the internal discussion and taking a closer look at your previous projects (which don't seem to be maintained), I would also be interested to learn more about your long-term plans for this or your next project and who you mean by **We**. Especially since no one ever seems to have contributed to your projects other than yourself. Additionally, are the future plans regarding your previous project still relevant: https://github.com/w3f/Grants-Program/blob/master/applications/polkaflow.md#future-plans?

**Comment by Noc2** [comment]
@justmert, thanks for the quick reply here. As promised, I reopened it, and sorry for the confusion.

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I will share it again with the rest of the team.

**Review by keeganquigley — APPROVED** [review]
Hi @justmert thanks for making the changes and reducing the scope/price. I'm willing to give you a chance for this price, and looking forward to seeing what you come up with.

**Pull request merged**
