### PR TITLE
SubVT Telegram Bot Grant Proposal

### PR DESCRIPTION
**Pull request by kukabi**
### Project Abstract

SubVT Telegram Bot is an upgrade for the existing Helikon [Polkadot/Kusama 1KV Telegram Bot](https://github.com/helikon-labs/polkadot-kusama-1kv-telegram-bot) to support all validators on Kusama and Polkadot with increased functionality and performance. The 1KV Bot currently serves 61% of all valid nodes on the Kusama 1KV and 69% on the Polkadot 1KV.

This upgrade consists of migrating the bot to use the [backend services](https://github.com/helikon-labs/subvt-backend) and storage of SubVT (Substrate Validator Toolkit), which is an under-development native mobile application project for iOS and Android phones, tablets and wearables, [supported by](https://kusama.polkassembly.io/treasury/99) the Kusama Treasury.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Review by mmagician — APPROVED** [review]
Awesome! Looking forward to using the bot 🎉

**Comment by kukabi** [comment]
Thanks a lot @mmagician 🙂  Looking forward to get it running!

**Review by BenWhiteJam — APPROVED** [review]

**Comment by kukabi** [comment]
Hi @semuelle, I have finished the development, am doing the final tests and making the production deployment. Release date is next week Thursday, 19th of May, going to announce it in the Matrix channels.

It ended up being a rewrite from scratch in Rust, and it’s an overdelivery by far, hence the delay, very sorry for it still. I’m going to post a PR that reflects the changes.

**Comment by kukabi** [comment]
New [PR](https://github.com/w3f/Grants-Program/pull/936) created with the dev update. @mmagician @semuelle

**Pull request merged**
