### PR TITLE
Grant Application: PolkaSignIn

### PR DESCRIPTION
**Pull request by hanwencheng**
### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Review by Noc2 — APPROVED** [review]
Looks good to me and I will share it with the rest of the team. Feel free to also integrate the psp process https://github.com/w3f/PSPs at some point.

**Comment by takahser** [comment]
Hi @hanwencheng
There doesn't seem to have been any activity on this recently. What's the current state here? Is there any way we can support you?

**Comment by hanwencheng** [comment]
Thanks for asking @takahser , After submitting the proposal, the project is paused for 1 and a half months. Now we are onboarding a new engineer to work on the topic.

**Comment by takahser** [comment]
Thanks for the update @hanwencheng 
Can you give me an estimate on when you plan to deliver?

**Comment by hanwencheng** [comment]
it is already started, I am pretty confident that we can deliver in one month.

**Comment by takahser** [comment]
Sounds good. Looking forward to it! @hanwencheng

**Comment by hanwencheng** [comment]
@takahser  The authorization library is complete in the [repo](https://github.com/litentry/PolkaSignIn), now we are under internal test, and are integrating the data part(OIDC). There are several issues related to the future of the project, feel free to join the discussion.

**Comment by takahser** [comment]
@hanwencheng happy to see you're making progress! Can you provide me with a rough estimate on when you'll have the issues resolved i.e. when you'll be able to deliver milestone 1?

**Comment by hanwencheng** [comment]
The issues are not related to the milestone, there is only the data part remaining unresolved, rough estimate of the data part is by the end of this week.

**Comment by takahser** [comment]
@hanwencheng that sounds good to me, thanks for the update

**Comment by hanwencheng** [comment]
We have finished the tasks up to `1c`.

Also, we created a demo for `1d`, it would be good that web3 foundation could make some introduction to other platforms, so that we could integrate the PolkaSignIn with some real use cases, for example: [Crowdcast](https://www.crowdcast.io/).

out

**Comment by Noc2** [comment]
> We have finished the tasks up to `1c`.
> 
> Also, we created a demo for `1d`, it would be good that web3 foundation could make some introduction to other platforms, so that we could integrate the PolkaSignIn with some real use cases, for example: [Crowdcast](https://www.crowdcast.io/).
> 
> out

That’s great. Not sure if we have someone in contact with crowdcast, but I will try to see what I can do and share it also with the ecosystem development team.

**Comment by semuelle** [comment]
Hey @hanwencheng. I see there is plenty of activity on the litentry repositories. Can you give an estimate of when you might be submitting your milestone?

**Comment by hanwencheng** [comment]
We haven't find a partner to use the login solution yet, this would be the final step.

**Comment by alxs** [comment]
Hey @hanwencheng, are you still interested in this? If you still want to deliver and haven't found a partner yet, could you please submit an [amendment](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval) as Sebastian mentioned and update the deliverables, as well as the timeline?

**Comment by alxs** [comment]
@hanwencheng friendly reminder. Note that if we don't hear from you within the next two weeks, we'll assume you're no longer interested and terminate the grant.

**Pull request merged**
