### PR TITLE
Submit application of project Libra

### PR DESCRIPTION
**Pull request by psyduckio**
### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. The naming of your project might lead to some confusion, since facebook's project diem was previously named libra. But that’s something, which isn’t relevant for this application. Just so that you are aware of it, since it might also lead to legal problems. So if I understand your application correctly, you basically want to integrate an on-chain escrow system. Are you aware of the [Currencies Module](https://github.com/AcalaNetwork/Acala/tree/master/modules/currencies) and the [Identity Module](https://github.com/paritytech/substrate/tree/master/frame/identity)? How are your solutions different?  Also could you update the following: "We will create a Substrate module that will... (Please list the functionality that will be implemented for the first milestone)"

**Comment by psyduckio** [comment]
> The naming of your project might lead to some confusion, since facebook's project diem was previously named libra. But that’s something, which isn’t relevant for this application. Just so that you are aware of it, since it might also lead to legal problems.

Thanks for reminding us about Facebook's project Diem and the potential legal issue.
Libra is a common English word, and we shouldn't have any issue with trademark infringement.
Libra was the unit of measure in Ancient Rome. It is Latin for scales as well. We loved the name as we found it. Somehow it fits our vision for the project perfectly.
Your concern about it may lead to confusion is a valid point. Indeed, we need to state it clearly when we do branding.

> So if I understand your application correctly, you basically want to integrate an on-chain escrow system.

In short, yes. The opportunity we're seeing is it lacks a complete blockchain-based eCommerce solution that enables these things:
Buyer can cancel their purchase and also get protected from fraud.
Merchant can cancel/refund.
We see a future where blockchain-based eCommerce becomes mainstream; the needs and use-case are different from what we have recently. That's why we are bringing payment and escrow into a more straightforward protocol.
The other key thing is the SDK, where people can start accepting crypto payments in just seven lines of code (similar to Stripe).

>  Are you aware of the Currencies Module and the Identity Module? How are your solutions different? Also could you update the following: "We will create a Substrate module that will... (Please list the functionality that will be implemented for the first milestone)"

Yes, we saw the modules during our research phase. We intend to extend the [orml currencies](https://github.com/open-web3-stack/open-runtime-module-library/tree/master/currencies) to fit with the protocol requirements and also easy to manage assets in the protocol.
And we think that is the same with the modules you mentioned.
For the identity module, we want to add a customized module that can include the roles e.g. resolvers, merchants, ... and credibility of an identity.
It will be helpful for the future development plan where we can warn the users of the high risks payments.
We've also updated the application.
Thank you so much!

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. Could you add more details regarding the differences between the existing modules and your modules (identity, currency)?

**Comment by psyduckio** [comment]
Sorry for being unclear. Here are the differences between the existing modules.

**Currencies pallet**
- We plan to add the currencies registry which allows creating currencies by bonding some native tokens.

**Identity pallet**
- We will make it more specific on the business logic of the chain which is just people adding specific fields, not generic like the existing module.
- We will add the identity credibility which stores the history of identity such as transactions made, disputes rate, wrong dispute decisions, ... This will enable users can evaluate the risks before making a payment.
- We will add the domain verify which allows an identity can verify that they own the domain. We think it will be helpful to prevent identity impersonation.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks. But could you add this information also to the grant application, since this is basically our contract?

**Comment by psyduckio** [comment]
I already updated the application which includes the detail of the identity pallet and currency pallet. Can you please review the application? Thank you so much!

**Review by Noc2 — APPROVED** [review]
Thanks again for the update. I’m happy to go ahead with the application and I will share it with the rest of the team.

**Review by BenWhiteJam — APPROVED** [review]

**Review by gautamdhameja — APPROVED** [review]

**Comment by psyduckio** [comment]
Hi @Noc2, 
Because the application has been approved in the holidays of our team, it will be delayed about 2 weeks to be delivered. Do we need to amend our application to correct the timeline or just need to let you know and keep it as it is?

**Comment by semuelle** [comment]
> it will be delayed about 2 weeks to be delivered. Do we need to amend our application to correct the timeline 

Hi @psyduckio. We are usually quite liberal with timelines. Unless the project is delayed by two months or more, there is no imminent need to amend the contract.

**Comment by psyduckio** [comment]
Thank you for your response @semuelle 🙏

**Comment by alxs** [comment]
Hey @psyduckio, any updates on the third milestone? Unless you plan to submit soon, could you please submit an [amendment](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval) with an updated timeline?

**Comment by psyduckio** [comment]
Hi @alxs, we are in the final steps to submit the third milestone. It seems our team underestimated milestone 3, but it is fine now. We will submit it this week or next week. Thank you for reminding me.

**Pull request merged**
