### PR TITLE
New funding flowchart

### PR DESCRIPTION
**Pull request by PieWol**
An updated funding flowchart inspired by [Shawn Tabrizi](https://forum.polkadot.network/t/is-the-treasury-polkadots-biggest-vc/9015)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
What do you mean by immediate public value?

**Comment by PieWol** [comment]
> What do you mean by immediate public value?

By that I mean anything which results in an immediate benefit for the Polkadot ecosystem. I‘d say this is what it boils down to when the treasury and their voters have to evaluate what they are funding. 

The term is taken from this [forum post](https://forum.polkadot.network/t/is-the-treasury-polkadots-biggest-vc/9015) by Shawn Tabrizi.

**Review by Noc2 — CHANGES_REQUESTED** [review]
It's too unspecific. At least, this would not help me understand, if I should apply for a grant or apply via the treasury.

**Comment by PieWol** [comment]
postponed

**Pull request closed without merging**
