### PR TITLE
Update openbrush-follow-up-2.md

### PR DESCRIPTION
**Pull request by coreggon11**
#### Project Abstract

This is an update of an already [accepted grant](https://github.com/w3f/Grants-Program/blob/master/applications/openbrush-follow-up-2.md).

We want to do some additions, however, I have noticed that after [this PR](https://github.com/w3f/Grants-Program/commit/57ef638f2bb331c24c569bff02f04c2b3e89bfb0) the changes we previously made to the grant application and which were accepted in [this PR](https://github.com/w3f/Grants-Program/pull/1237) were discarded, so I am adding these changes as well as one new change regarding ink! 4.0. As we are updating OpenBrush to use ink! 4.0, and the storage was reworked in ink! 4.0, we will need to do many changes in OpenBrush and it may increase the original delivery time and cost, and we want to have it covered in this grant. We also had some team adjustments, they are addressed in this PR.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [X] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [X] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [X] A BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (aUSD/USDT) address for the payment of the milestones is provided in the application.
- [X] The software delivered for this grant will be released under an open-source license specified in the application.
- [X] The initial PR contains only one commit (squash and force-push if needed).
- [X] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
I’m very sorry for the issue with the [website integration PR]( https://github.com/w3f/Grants-Program/commit/57ef638f2bb331c24c569bff02f04c2b3e89bfb0). Something like this shouldn’t happen, and it’s a very good thing that we have the version history. But given that your PR changes more than the original PR, we need to review it again. I’m personally happy to go ahead with it.  Could you sign the latest version of the CLA?

**Comment by coreggon11** [comment]
Hi @Noc2 and thank you for response. I have signed it.

**Review by Noc2 — APPROVED** [review]
Thanks. I'm happy to go ahead with it and share it with the rest of the team.

**Review by keeganquigley — DISMISSED** [review]

**Review by alxs — APPROVED** [review]

**Comment by alxs** [comment]
@coreggon11 note that we [no longer pay](https://github.com/w3f/Grants-Program#pencil-process) in USDT on Ethereum. Could you provide a Kusama or Polkadot address if you still want to be paid in USDT? The same goes for the [other](https://github.com/w3f/Grants-Program/pull/1367) [two](https://github.com/w3f/Grants-Program/pull/1368) amendments. Feel free to have a look at the current list of [payment currencies](https://github.com/w3f/Grants-Program#pencil-process).

**Review by alxs — APPROVED** [review]

**Review by Noc2 — APPROVED** [review]

**Comment by coreggon11** [comment]
@alxs thanks for the reply, and sorry for waiting, we needed to discuss this. I see you already approved the changes, but for others, I changed the payment method to DAI (and the same for other PRs)

**Review by keeganquigley — APPROVED** [review]

**Review by dsm-w3f — APPROVED** [review]

**Comment by FLebed** [comment]
Hello guys, a pleasure to meet you. I’m Fedor, Head of Operations at Brushfam. @TtomaS7 resigned from her position in 727 ventures, so the grants she initiated will be transferred to me.


[OpenBrush](https://github.com/727-Ventures/Grants-Program/blob/master/applications/openbrush-follow-up-2.md)


[Typechain](https://github.com/727-Ventures/Grants-Program/blob/master/applications/typechain-polkadot-follow-up.md)


[Sol2ink](https://github.com/727-Ventures/Grants-Program/blob/master/applications/sol2ink-follow-up.md)


Toma, please confirm this)

**Comment by TtomaS7** [comment]
I confirm it!

**Review by SBalaguer — APPROVED** [review]

**Pull request merged**
