### PR TITLE
Add PHP RPC Lib Follow up

### PR DESCRIPTION
**Pull request by gmajor-encrypt**
#### Project Abstract

> PHP-RPC-Lib smart contract extension
>
> follow up https://github.com/w3f/Grants-Program/pull/622

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (aUSD/USDT) address for the payment of the milestones is provided in the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by randombishop** [comment]
Thank you for submitting this application. 
One question from my end: how does your project differ from https://github.com/nitor-infotech-oss/parity-substrate-interface?
Thank you!

**Comment by gmajor-encrypt** [comment]
@randombishop Thank you for reply, [parity-substrate-interface](https://github.com/nitor-infotech-oss/parity-substrate-interface) simply wraps the rpc and does not parse the return value. In addition, there is no support for wsam contract

https://github.com/gmajor-encrypt/php-substrate-api is more like a PHP version of [polkadot.js](https://github.com/polkadot-js/api) package. He has a more comprehensive Data query and codec and transaction sending

**Comment by randombishop** [comment]
@gmajor-encrypt Thanks for the clarification.

**Review by randombishop — APPROVED** [review]

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Could you add a few more technical details to the specification of the milestones (e.g., PHP as the programming language, linking to the repo, etc.)? These are basically the requirements of our contracts, which should be as detailed as possible. Apart from this, an example or article might be useful as additional delivery.

**Comment by gmajor-encrypt** [comment]
@Noc2 Hey, I have modified my project details, if there are still deficiencies, please tell me

**Review by Noc2 — APPROVED** [review]

**Review by randombishop — APPROVED** [review]

**Pull request merged**
