### PR TITLE
DevPool by Ubiquity

### PR DESCRIPTION
**Pull request by pavlovcik**
#### Project Abstract

DevPool is a crypto-native platform that organically sits on top of GitHub to optimally match developers with open tasks and get paid in crypto while automating management for distributed organizations and repository maintainers.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by keeganquigley — CHANGES_REQUESTED** [review]
Thanks for the application @pavlovcik a couple of initial comments/questions:

- Regarding the milestones, the mandatory deliverables look good (0a. - 0d.) but delivery table descriptions 1 - 6 seem to still be the template boilerplate text. Can you replace this with the concrete technical deliverables that you would produce? 
- We only fund software that doesn't exist yet, and it seems that some of the [DevPool](https://dao.ubq.fi/the-devpool) tools have already been built, such as [ubiquibot](https://github.com/ubiquity/ubiquibot). Can you specify in the application what you would be building as part of the grant? The more technical details the better.
- For any front-end focused milestones, we typically ask for mockups to be presented in the application.
- Please also note that we typically only fund ink! smart contracts, as we aren't Solidity experts.

**Comment by pavlovcik** [comment]
>  fund ink! smart contracts

What is "fund ink!"?

I understand that these submissions are expected to be delivered in a single commit. It makes more sense to me that we append changes to this same pull request, possibly while leaving it as a draft pull request, and to keep the context of the conversation. 

Otherwise, please confirm if you want me to close this pull request, and open another when we complete our changes.

**Comment by keeganquigley** [comment]
Thanks @pavlovcik yep no worries, you can make the changes on the current PR, no need to open a new one. We will squash the commits anyway.

**Comment by Noc2** [comment]
I wanted to let you know that I'm closing this because of inactivity. Let me know if I should reopen it.

**Pull request closed without merging**
