### PR TITLE
RainbowDAO Protocol ink!  Phase 1.md

### PR DESCRIPTION
**Pull request by RainbowcityKun**
### Project Abstract

RainbowDAO Protocol ink! is a series of smart contracts based on DAO infrastructure authorized and developed by the Rainbowcity Foundation. On the foundation of substrate development ecology, it focuses on the creation of web3 basic kits. These smart contracts are all created by the Ink! Framework. Anyone can create and manage their own DAO through RainbowDAO protocol. RainbowDAO protocol can build not only independent DAOs, but also parent DAOs, child DAOs and alliance DAOs. What's more, it can create management departments within DAOs to achieve multi-level management.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Comment by semuelle** [comment]
Thank you for the delivery, @RainbowcityKun. We will look into it as soon as possible.

**Comment by RainbowcityKun** [comment]
> Thank you for the delivery, @RainbowcityKun. We will look into it as soon as possible.

Thank you for the hard work of your web3 team. At present, our team has fully started the development of the protocol.

**Comment by RainbowcityKun** [comment]
> Thank you for the delivery, @RainbowcityKun. We will look into it as soon as possible.

Hello，semuelle，how was your investigation of our proposal? What content needs to be optimized or modified here? Thank you for your hard work.

**Comment by semuelle** [comment]
I had a quick look at your application, and so far it looks good. I'm afraid it will still take some time before we can provide proper feedback, though. Most of the team is currently out of office. Please ping us again if you don't hear from us next week.

**Comment by RainbowcityKun** [comment]
> I had a quick look at your application, and so far it looks good. I'm afraid it will still take some time before we can provide proper feedback, though. Most of the team is currently out of office. Please ping us again if you don't hear from us next week.

ok, thank you very much for your feedback, and I will wait patiently. At present, our team has fully started the development of the protocol, and we will make certain additions and adjustments based on your team's feedback in the future.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Looks interesting. A few comments: Something in general to be aware of, is that we expect assets, like erc20 to live inside the [assets pallet](https://github.com/paritytech/substrate/tree/master/frame/assets) and for multisig most people will probably use the multisig pallet. So, not sure if you need to develop these as ink! smart contracts. Otherwise, I would be interested to hear if you are also thinking about something like a court, similar to the aragon court: https://anj.aragon.org/#/dashboard.

**Comment by RainbowcityKun** [comment]
> Thanks for the application. Looks interesting. A few comments: Something in general to be aware of, is that we expect assets, like erc20 to live inside the [assets pallet](https://github.com/paritytech/substrate/tree/master/frame/assets) and for multisig most people will probably use the multisig pallet. So, not sure if you need to develop these as ink! smart contracts. Otherwise, I would be interested to hear if you are also thinking about something like a court, similar to the aragon court: https://anj.aragon.org/#/dashboard.



Hello, Noc2, thank you very much for your feedback. Now let me answer your questions:

1.First of all, there are two main reasons why we need to establish an ink contract for the erc20 factory.

The first point, we know that on the public welfare parachain Statemint, anyone can creat their own erc20 tokens through the assets pallet module. They are the underlying assets of the blockchain, not contract-based assets. However, the assets pallet module itself is very powerful, and there are many different options for token management. The operation complexity is relatively high, and certain basic technologies are required. At the same time, the transfer of tokens also requires cross-chain management, and relatively professional management knowledge is required to manage the issuance and destruction of tokens. This is more suitable for some large-scale project parties or project teams with technical foundations.

But our erc20 factory contract positioning here is different. Issuing erc20 contract tokens here does not require any technical foundation. Anyone can issue an erc20 token through a few basic settings, and there is no complicated management authority and is very suitable for ordinary people who do not understand any technology. At the same time, the issued tokens are a fixed number, and there is no need to issue or destroy them, and token management is very simple. This token factory is directly bound to the DAO organization it generates, and can generate corresponding governance DAOs simultaneously.

Anyone can create a DAO through the RainbowDAO protocol. It may be a large DAO, or it may be a small DAO of dozens of people. To create a very small DAO, there is no need to cross-chain the assets pallet module to create erc20 tokens. The erc20 factory contract is enough.

Therefore, the erc20 factory belongs to the basic configuration of a DAO tool product. Similar to Aragon, they also have a matching token factory module when they establish a DAO organization.

https://client.aragon.org/#/


The second point ,it is that we will add some parameters to the erc20 factory contract to record the token circulation information in the block. This helps us to use some of the advanced features of the RainbowDAO protocol. For example, in our voting weight design, there will be different voting rights calculation methods, such as one person one vote, one token one vote, or quadratic voting. At this time, we need to call this parameter to calculate the voting weight. This logic comes from compound's governance logic. However, there is no similar function in the standard assets pallet module, and we cannot ask the parachain governance party to increase the corresponding function. Therefore, an erc20 factory contract is still very necessary.



2.Secondly, regarding the issue of multisig pallet, we also have multiple considerations on this point.

The first point is that the multisig contract is one of the core functions of RainbowDAO protocol and represents our overall governance thought. First of all, through the RainbowDAO protocol, anyone can create an independent DAO organization. This DAO organization is managed by the corresponding governance DAO. However, the governance by all token holders will result in low work efficiency and execution power. Therefore, we have specially created the function of DAO department management. Any DAO organization can create multiple different departments, different departments bear different division of labor, and have a certain amount of special use of funds. Here, department management is no longer managed by the entire token holders, but by different multisig management committees. This is the further decentralization of the DAO's power. The multisig contract is used to manage the departments within the DAO, which improves the efficiency and execution of the DAO's organizational management.

Therefore, the multisig contract is one of the core functions of the RainbowDAO protocol and is essential. The RainbowDAO protocol will be deployed on different parachains in the form of smart contracts in the future to serve various types of DAO organizations on these parachains. However, there may be some parachains that do not carry multisig pallets or carry The multisig pallet cannot meet the needs of our DAO governance. Therefore, our protocol itself must have a multisig contract, so that anyone can quickly and easily deploy multisig contracts and exercise the management authority of the department.


The second point, we have also carefully studied the multisig pallet function provided by polkadot official team. There is still a certain difference between the multisig pallet here and the multisig requirement of our protocol itself. The official multisig pallet pays more attention to the management of multisig funds, and cannot be used for mutual calling of multisig management permissions. In addition, the official multisig pallet function can only be used to establish multisig  accounts between accounts that you own, and cannot use non-self-owned accounts to establish multisig accounts.

With our multisig smart contract, you can choose any wallet address or contract address as one of the multisig signers, and the function is more flexible. At the same time, the multisig contract function we designed not only manages funds, but more importantly, manages various permissions in the governance process. It can also participate in voting for various proposals through multisig signatures, and the functions are more open and combinable.

The vision of the RainboDAO protocol we designed is to realize the function of organizing Lego. Different modules can be combined, disassembled, and called each other, which can truly achieve unlimited upgrades and evolve into a vitality  protocol. The reason why we choose ink contract to build the core function of the protocol is that we value the composability and mutual calling between smart contracts.

At the same time, the multisig smart contract function we designed here is inspired by the Ethereum ecosystem's gnosis-safe, https://gnosis-safe.io/,

gnosis-safe is regarded as one of the most famous asset management protocols in the Ethereum ecosystem. Our product logic is similar to it, and has been optimized and improved on the basis of its existing functions. The multisig smart contract we designed can not only exist as a management contract of the DAO organization, and play a role in the form of a plug-in, it can also become an independent asset management protocol that functions independently of the DAO organization.

In the future, we will participate in the parachain campaign and will build a parachain with the DAO organization as the core. We will choose to design some basic low-level logic into pallet functions, and some application logic into contract functions. When we did not have our own independent parachain, we designed all the logic into an ink smart contract, so that our protocol can be deployed on any parachain without worrying about whether their underlying pallets are suitable for our protocol.


3.Regarding the function of court, https://anj.aragon.org/#/dashboard

This is also a function we have been focusing on. In the overall RainbowDAO protocol we designed, we designed a total of 12 major modules and 60 independent small systems, which will all exist in the form of plug-ins. Among them, the 12th module already contains the court system. In terms of, we also focused on the court function of aragon, and will improve it on the basis of its existing functions.

However, the function of the court was not included in our first proposal. Our first proposal is based on the RainbowDAO protocol basic framework and DAO factory. First, we realize the creation and management of a DAO organization. We will put the function of court in the second proposal. At that time, the function of court will exist in the form of plug-ins. Any DAO organization or community member can resolve disputes in the governance process through court. We will further study the specific product details and functional logic. At that time, we will elaborate on the idea of our court module in our second grant proposal.


The above is a response to some of your questions. Thank you again for your team's hard work.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the detailed reply. I have one last question, before I share it with the rest of the team. Would you also be willing to integrate some of the UI into the deliverables? I’m mostly asking because it seems that you are already working on this.

**Comment by RainbowcityKun** [comment]
> Thanks for the detailed reply. I have one last question, before I share it with the rest of the team. Would you also be willing to integrate some of the UI into the deliverables? I’m mostly asking because it seems that you are already working on this anyway.

You are welcome, I am very happy to work with you. We don't just take it as the task of the grant, but really hope to make it a great project. In these two milestones, we will integrate the UI into the deliverables. As you said, our UI is already under design and will be delivered together with the smart contract.

**Comment by RainbowcityKun** [comment]
> Great! Could you integrate this into the deliverables of the milestones and update the PR?

Thanks! I just added the UI to the deliverables and updated the PR.

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I will share the application with the rest of the team.

**Comment by RainbowcityKun** [comment]
> Thanks for the update. I will share the application with the rest of the team.

OK, thank you very much! Our team is already working hard to develop the protocol, and we will definitely create a great project!

**Review by semuelle — COMMENTED** [review]
Hi @RainbowcityKun, thanks for the thorough application. A couple of minor questions:

- In the protocol diagram, the factory contract is connected to the protocol, RBD token and governor. Does that mean that my DAO would be subject to, for example, fees that the RBD token holders agree on?
- What purpose does the membership management contract serve? Usually, in DAOs, token holders are the members. How does one become a member? What identity information do you plan on storing? What recommendations do you plan on implementing?
- You mention the ability to upgrade the protocol. Will the smart contracts be upgradable, i.e. can I swap my treasury management contract after deployment?
- You mention composability. Does that mean that I can deploy a DAO without a governance token, infrastructure contract and proposal management contract, if I wanted to?

**Comment by RainbowcityKun** [comment]
Hi, @semuelle, thank you for your wonderful questions, each question is very representative and constructive::

 * In the protocol diagram, the factory contract is connected to the protocol, RBD token and governor. Does that mean that my DAO would be subject to, for example, fees that the RBD token holders agree on?


First of all, the DAO I established here is not controlled by the holders of RBD, it is controlled by the holders of our own governance token.

Our protocol is mainly divided into two layers, one is the basic protocol layer, which is controlled by the governance DAO of RBD through voting. This basic protocol layer belongs to the overall infrastructure of the RainbowDAO protocol and consists of six parts.The first is the rainbow core contract, the second is the membership management contract, the third is the revenue management contract, the fourth is the web3 suite tool contract, the fifth is the DCV controller contract, and the sixth is the DAO factory contract. 

The DAO factory contract also belongs to the second layer of the RainbowDAO protocol, which is mainly used to control and manage the DAO created by the protocol. 

RBD holders can control the parameters of these six modules through the RBD governance DAO, such as changing the protocol revenue parameters, adding various DCV controllers, adding or deleting protocol plug-ins, and so on.

But RBD holders cannot control the independent DAO created by the DAO factory. Each independent DAO establishes its own governance DAO by binding its own governance token, and finally realizes the governance and upgrade through its own governance DAO.


 * What purpose does the membership management contract serve? Usually, in DAOs, token holders are the members. How does one become a member? What identity information do you plan on storing? What recommendations do you plan on implementing?


In our protocol design, the membership management contract belongs to the basic protocol layer of the RainbowDAO protocol, and we will build an independent identity ID system. It exists independently of each DAO, but each DAO member can use this identity system. Anyone can become a member through the registration function, regardless of whether he is a member of the DAO.

At the beginning, we mainly store two types of information, one is the basic information of members, such as user name, avatar, personal introduction, twitter and other basic information; the second is to store the member recommendation information of the entire protocol.This recommendation system belongs to the plug-in of the entire protocol, and each independent DAO can freely choose whether to use this recommendation system. If it chooses to use this recommendation system, it can also customize the level of recommendation and the ratio of rewards. All can be set flexibly.

In the future, as the protocol continues to upgrade, we will integrate more functions, such as RainbowDAO employee recruitment system, RainbowDAO work reporting system, daily, weekly or monthly reports, and RainbowDAO reputation system and credit system. These systems will be integrated into the RainbowDAO overall protocol in the form of plug-ins in the future. At present, we can only provide the basic framework, and cannot provide detailed information about each function. This needs to be improved step by step as the protocol continues to develop.


 * You mention the ability to upgrade the protocol. Will the smart contracts be upgradable, i.e. can I swap my treasury management contract after deployment?


Here, our protocol upgrade capability is mainly controlled by the governance DAO of RBD holders, which controls the parameters of each basic protocol layer, and achieves protocol upgrades through the modification of this parameters. At the same time, the governance DAO of RBD holders can also control the routing contract in the Rainbowcore contract. The routing contract can change the contract addresses of some corresponding contracts, so as to replace the deployed contracts and achieve the upgrade of the protocol.

The treasury management contract you mentioned belongs to the created independent DAO treasury management contract. It is not controlled by the holders of the RBD. It is controlled by the governance DAO created by the governance tokens bound to it. When the DAO is deployed, it cannot directly change its treasury contract address, but it can create a new departmental treasury by establishing a new department, and it can transfer funds through voting.


 * You mention composability. Does that mean that I can deploy a DAO without a governance token, infrastructure contract and proposal management contract, if I wanted to?


Yes, it is absolutely possible. All of our functional modules exist in the form of plug-ins. When I deploy a DAO, I can freely choose each functional module according to my actual needs. I can build a very complex DAO that can accommodate tens of thousands of people, and I can also build a very simple DAO with only a few dozen people. We hope to finally realize the vision of DAO Lego, which can be combined freely or disassembled freely. Everything is based on the actual needs of each DAO, so that we can truly realize the diversified needs of DAO. Any type of DAO can be customized to suit their actual needs through our protocol.

**Review by semuelle — APPROVED** [review]
Thanks for the thorough response, @RainbowcityKun. From your description the recommendation system sounds more like an _endorsement_ or *com*mendation system. Is that what you mean? It certainly makes more sense than what I had in mind. Anyway, I'm happy to proceed.

**Comment by RainbowcityKun** [comment]
> Thanks for the thorough response, @RainbowcityKun. From your description the recommendation system sounds more like an _endorsement_ or _com_mendation system. Is that what you mean? It certainly makes more sense than what I had in mind. Anyway, I'm happy to proceed.

Hi, @semuelle, thank you very much for your patience. Sorry, English is not my native language, so it is not very accurate in terms of using words. In the future, I will try to use more precise words to express my meaning.

Here, the recommendation system is not an endorsement or commendation system. It is an invitation system. The invitation relationship is constructed by generating an invitation code, and then a certain bonus distribution is obtained. This is a basic function.

In future versions, we will build a recruitment system, work reporting system, credit system, reputation system and medal system on the basis of this membership, each of which will be an independent system and be installed on the basic protocol in the form of a plug-in unit. This will involve more complex personnel management. In this way, we can provide more diversified tools for DAO management and governance to adapt to the needs of different DAOs. These are future development plans and are not in this version.

**Comment by semuelle** [comment]
Thanks for the clarification, @RainbowcityKun. I think your application is easy to understand. We just get applications involving recommender systems ("if you like X, you might like Y") occasionally, so it's good to have this clarified.

**Comment by RainbowcityKun** [comment]
> Thanks for the clarification, @RainbowcityKun. I think your application is easy to understand. We just get applications involving recommender systems ("if you like X, you might like Y") occasionally, so it's good to have this clarified.

Yes, thank you for your recognition. In the description of future product functions and logic, we will also be as accurate as possible.

**Review by BenWhiteJam — APPROVED** [review]

**Pull request merged**
