### PR TITLE
Crowdloans-FET Application

### PR DESCRIPTION
**Pull request by brymut**
#### Project Abstract

The CrowdloanFET project is a free and opensource white-label solution for Polkadot projects to showcase the Crowdloan to prospective and current project supporters and community members.

Built using Nextjs, Tailwind and Polkadot.js, projects can easily configure/modify and deploy a frontend for their crowdloan campaign, either on their own infrastructure that supports node or on affordable/free platforms like Vercel.

**This application is response to the [Crowdloan Front End Template RFP](https://github.com/w3f/Grants-Program/blob/master/rfps/open/crowdloan_front_end_template.md)**

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — APPROVED** [review]
Thanks for the application. I’m happy to support it and share it with the rest of the team.

**Review by takahser — CHANGES_REQUESTED** [review]
@brymut I'm generally willing to support this.
However, I've noticed that the mandatory deliverable _0d. | Docker_ is currently missing, see also in our [template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#milestone-1-example--basic-functionality):

> ❗ The default deliverables 0a-0d below are mandatory for all milestones

Feel free to add it.

**Comment by brymut** [comment]
Hi again @Noc2 / @takahser , thanks for the feedback, I have now included docker into the milestone. Could you please have another look?

**Review by Noc2 — APPROVED** [review]

**Review by takahser — APPROVED** [review]

**Comment by randombishop** [comment]
Hey @brymut!

Nabil here from the web3 foundation grants team.

I will be making a presentation about the w3f grants program at DOT Safari in Kenya; and I am curious to hear from your experience with us as an african grantee.

My questions are: 
* How was your experience with our grants program?
* Do you have thoughts on how we could reach out for african talent, encourage them to build on the Polkadot ecosystem, and help them benefit from our program? 
* Please share social media links as well, would love to learn more and follow! 

Also curious to hear about your current progress on your first milestone and if you'll be present at DOT Safari, it would be great to meet there...

One more detail: I tried to reach out using the email provided in the grant application but I got back an address not found. Could you please make a PR to update your contact info.

Thank you and hope to hear back from you soon!

**Comment by keeganquigley** [comment]
Hi @brymut have you been making any progress on milestone 1? As it is a few months overdue now.

**Comment by keeganquigley** [comment]
@brymut are you able to give us an update?

**Comment by keeganquigley** [comment]
Hi @brymut please note that if we don't hear back from you after 2 weeks, the committee will likely file a PR to cancel the grant due to inactivity. Thanks for your work so far and please let us know if you are still working on it.

**Pull request merged**
