### PR TITLE
GenesisDAO

### PR DESCRIPTION
**Pull request by deep-ink-ventures**
#### Project Abstract

Genesis DAO is a platform as a service for DAOs. The platform lives on a polkadot parachain and utilizes Cross Consensus Messages (XCM) as a first-class citizen of its infrastructure.

It allows teleporting of DAO tokens to other chains to be native parts of the protocol while voting, treasury and other DAO infrastructure is living natively on Genesis DAO. Genesis DAO manages the ramifications of DAO on its robust platform – the DAO token itself becomes a lego block that can live on every chain of choice.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (aUSD/USDT) address for the payment of the milestones is provided in the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. I have just a few follow-up questions: 

- Regarding the “Substrate module: pallet_dao_core”, did you take a look at other dao modules here: https://wiki.polkadot.network/docs/build-open-source and how is your solution different from the existing ones? 
- Regarding “Frontend Infrastructure”, would you support all functionality of the initial dao pallet? Do you have any mock-up or something similar that you can already share? 
- Could you add maybe Benchmarking as a deliverable to the pallets? 
- You currently list the exact same deliverables under milestone 2 and 3. For example: “We will fork the pallet_asset and customize it for DAO optimization needs, most prominently with checkpoint functionality.” Could you update this?

**Comment by deep-ink-ventures** [comment]
Thanks for this.

> Regarding the “Substrate module: pallet_dao_core”, did you take a look at other dao modules here: https://wiki.polkadot.network/docs/build-open-source and how is your solution different from the existing ones?

THe core pallet is used to orchestrate the interaction between all other pallets. It's therefore the only one that is not loosly coupled in the sense that it can be reused standalone: It has dependencies on our `dao_asset` pallet and is as well the configuration layer for the other pallets (such as hookpoints). We therefore don't use existing pallets for this.

> Regarding “Frontend Infrastructure”, would you support all functionality of the initial dao pallet? Do you have any mock-up or something similar that you can already share?

Yes, we want to have initial support for creating daos, issuing a token, creating proposals and voting. We do not have yet mockups.

> Could you add maybe Benchmarking as a deliverable to the pallets?

Yes, I added it in milestone 3.

> You currently list the exact same deliverables under milestone 2 and 3. For example: “We will fork the pallet_asset and customize it for DAO optimization needs, most prominently with checkpoint functionality."

That slipped through :-) - fixed.

**Review by Noc2 — DISMISSED** [review]
Thanks for the update. Given that the goal here is to create a common good solution and based on the good impression I got of your team, I’m generally happy to go ahead with it and share it with the rest of the team. But you still might define the scope of the milestones a little bit better. For example, what does “lifecycle” mean/contain? The milestones (=requirements of the contract) are currently relatively loosely defined for a 100k grant, which might raise some concerns.

**Review by gautamdhameja — APPROVED** [review]

**Review by BenWhiteJam — DISMISSED** [review]

**Review by SBalaguer — DISMISSED** [review]
I'm looking forward to approving this! A couple of things that I'd like to point out that will be relevant for this grant:
- Remote Locking on [XCM v3](https://github.com/paritytech/polkadot/pull/4097). This will serve for voting purposes.
- Discussions about unlocking chains remotely from a DAO chain. Particularly on the [last barcamp](https://forum.polkadot.network/t/polkadot-summit-barcamp-workshop-summaries-and-action-ownership/1466) there's a [next step](https://polkadot-summit.notion.site/Polkadot-Summit-Outcomes-Tracker-aba3d9019f5945a8bea2fea8858c9649) on how to improve the unlocking of a parachain. This will most probably be for a second iteration of the project, but it's good to have it in mind.

**Review by dsm-w3f — CHANGES_REQUESTED** [review]
@deep-ink-ventures thank you for your application. Reading the application, I missed some information that is in our [template for grants application](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md), such as Team Members (is only you?), Team's experience, Linkedin Profiles, and Code repositories. Could you please add them to your application? 

Regarding the tests in the deliverables, we usually ask for integration/system tests, not only unit tests. Could you please explain which approach will be held to validate the integrated (all parts) system in each milestone? Do you plan to have automated e2e tests or a detailed manual test plan for us to reproduce the validation of the system? Could you please add the selected approach and the related artifacts in the test deliverable of the milestones?

In the parachain setup deliverable (1), it says: "AWS-based staging environment". This would be nice for the production environment, however, for testing, we usually expect a docker-compose file that spins up all services needed for testing. Could you please add this to your deliverables?

We already supported some DAO's related tools, such as [daos](https://github.com/w3f/Grants-Program/pull/1050) (a library to create DAOs that is the base for DICO and KICO parachains) and [MangoBox](https://github.com/w3f/Grants-Program/pull/976) (a fundraising platform that is similar to a well-known one https://juicebox.money/ used to fund DAOs). Could you please compare your grant proposal with those projects? What are the differences? Could you have some benefit of using the DAOs library in your proposal or MangoBox for fundraising the DAOs? Which parts of the "dao lifecycle" and "lifecycle of a proposal" are already covered by these projects? Which parts are not covered? Is it possible to reuse them? Please detail the features planned to be included in these lifecycles during your comparison.

**Comment by deep-ink-ventures** [comment]
Commit: https://github.com/deep-ink-ventures/Grants-Program/commit/fdc70dde2557e1569985214de933f94aaaebc6ac

> Do you plan to have automated e2e tests or a detailed manual test plan for us to reproduce the validation of the system? Could you please add the selected approach and the related artifacts in the test deliverable of the milestones?

Behind unit tests (`cargo test` in the pallets …), we do have a Quality Engineer testing the system and setting up manual test cases on top of the UX. Those manual test cases can evolve into system integration tests over time and we plan to do them simultaneously. I therefore added a manual testing guide and a functional test suite to the deliverables.

> In the parachain setup deliverable (1), it says: "AWS-based staging environment". This would be nice for the production environment, however, for testing, we usually expect a docker-compose file that spins up all services needed for testing. Could you please add this to your deliverables?

This makes sense. I swap AWS environments for a docker compose setup with a focus of getting up and running locally fast.

> We already supported some DAO's related tools [...]

We are positioning GenesisDAO as an infrastructure chain that aims to streamline composability and interchain communication and that acts as a baseline to build on top. We want to set this up as a common good parachain that supports dao building for third parties. The aim for this is to have a standard across chains that can act as primitive for critical components such as chain recovery or cross chain voting mechanisms. 

As such, promising projects such as Societal or MangoBox are complementary projects to our approach. GenesisDAO supports the basic building blocks of a DAO - create, token issuance and basic voting and focusses from there on to provide ecosystem integrations where features like treasury management or fundraising can be build on top by projects like societal and MangoBox. Another way of saying this is that GenesisDAO is the Statemint equivalent for DAOs - the basic infrastructure with strong hook points and integration offerings.

As for the mentioned library, we will monitor its usage and applications for us closely as it gets closer to production readiness.

**Review by Noc2 — APPROVED** [review]
I'm still happy to go ahead with it.

**Review by SBalaguer — APPROVED** [review]

**Review by dsm-w3f — APPROVED** [review]
Thank you for the improvements. My requests were answered either in the application document or in a private discussion.

**Review by keeganquigley — APPROVED** [review]

**Pull request merged**
