### PR TITLE
Added ink-boxes application

### PR DESCRIPTION
**Pull request by nerdsince98**
#### Project Abstract

> Ink boxes are a collection of helpful Ink smart contract boilerplates along with it's frontend. It will already have polkadot.js library using which frontend can talk with the smart contract deployed. Got inspired by truffle boxes on how easily one can spin up the boilerplate code in no time.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. One quick comment the link: https://gitlab.com/nerdsince98 doesn't seem to work. Could you update this?

**Comment by nerdsince98** [comment]
Hey @Noc2. I tried opening my GitLab profile in incognito mode, but it is not opening, asking me to sign in. I have moved that repo to GitHub: https://github.com/nerdsince98/ink-boxes. Please check. Also, I will keep on adding more boxes.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the quick reply. I have two additional questions: 

- Do you have any mock-up or design or reference regarding the website you have in mind? 
- The total costs of the first milestone seem relatively high compared to the second milestone. Could you potentially reduce the cost of the first milestone and increase the costs of the second milestone? Especially since I think the project is only useful with a nice website.

**Comment by nerdsince98** [comment]
Hey @Noc2. Thanks for your reply.

I have reduced the cost from the first milestone and increased it in the later one.

This is the website I will be taking inspiration from: https://trufflesuite.com/boxes/

**Review by keeganquigley — APPROVED** [review]

**Comment by nerdsince98** [comment]
Hey @Noc2 I have submitted the first milestone and raised invoice for the same. Request you to check the code repository: https://github.com/nerdsince98/ink-boxes 
 Thankyou

**Comment by avirajkhare00** [comment]
Hey @0xCaso. I will rework the website to make it more pretty. Eventually, I will go through the evaluation notes and make them perfect.

**Pull request merged**
