### PR TITLE
Cross-Consensus Messaging Software Development Kit

### PR DESCRIPTION
**Pull request by 0xslipk**
### Project Abstract

XCM SDK is a tool that provides an interface to send XCM messages for Substrate based blockchains. This library is written in Typescript so it can be imported in a whole new set of applications or dApps that use Javascript/Typescript engines such as Node. 

The idea of this project is to have fast way to send XCM messages between the relay chain and the parachains without having to use Rust-written tools or other platforms/applications. 

This project is focused on the Polkadot ecosystem but it can be used in any other Substrate-based blockchain that uses the XCM pallet.

### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Just for reference
https://github.com/w3f/Grants-Program/pull/1052 We usually ask teams to first finish their initial grant, at least their initial evaluation. So I put this on hold for now. See  https://github.com/w3f/Grant-Milestone-Delivery/pull/570  
Regarding the application, it looks really good. It might make sense to link to the specific types that you would support as part of milestone 1.  And do you think it would make sense to add a simple CLI tool as part of the deliveries to make it easier for others to use this tool

**Comment by 0xslipk** [comment]
> Thanks for the application. Just for reference #1052 We usually ask teams to first finish their initial grant, at least their initial evaluation. So I put this on hold for now. See [w3f/Grant-Milestone-Delivery#570](https://github.com/w3f/Grant-Milestone-Delivery/pull/570) Regarding the application, it looks really good. It might make sense to link to the specific types that you would support as part of milestone 1. And do you think it would make sense to add a simple CLI tool as part of the deliveries to make it easier for others to use this tool

Hi @Noc2, thanks for taking the time to review our proposal. We were waiting to merge https://github.com/w3f/Grant-Milestone-Delivery/pull/570, before summiting this one, but we also want some feedback in avance for this proposal. We truly sorry for sending this before complete the initial evaluation for https://github.com/w3f/Grants-Program/pull/1052

We are gonna add the specific types that we would support as part of milestone 1.

What do you mean with CLI tool? Adding something like [commander](https://www.npmjs.com/package/commander) to execute commands to get the xcm messages?.

Thanks,

**Comment by 0xslipk** [comment]
Hi @Noc2,

We added our [research document](https://github.com/blockcoders/xcm-grant-research) with the types we are gonna support and CLI tool as part of Milestone 2.

**Review by Noc2 — APPROVED** [review]
Thanks a lot for the update. Since your first milestone is accepted, I’m happy to go ahead with this grant and mark it as ready for review.

**Review by gautamdhameja — APPROVED** [review]

**Review by takahser — APPROVED** [review]

**Pull request merged**
