### PR TITLE
application-BikaToken.md

### PR DESCRIPTION
**Pull request by JhonnyAllen79**
### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Comment by JhonnyAllen79** [comment]
I build and develop Dapps, the project will contribute to polka dots and substrates.  the project requires development funding from W3F.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. However, you shouldn’t move the application template itself and rename it. Instead you should create a copy of the application file and update this accordingly. Also your application is currently still missing details. For example your second milestone has no deliveries at the moment. Could you please update this?

**Comment by JhonnyAllen79** [comment]
Thank you for your feedback, I will try to fix his mistake.

Pada tanggal Jum, 21 Jan 2022 14.59, github-actions[bot] <
***@***.***> menulis:

**Comment by JhonnyAllen79** [comment]
Hi sir, Do i have to delete the grant application and create a new one
create a new file and copy the template.

Regards
Bika Token/StarX

Pada tanggal Jum, 21 Jan 2022 15.14, Arki Ark star ***@***.***>
menulis:

**Comment by JhonnyAllen79** [comment]
Hi W3F, I've fixed the error and I've given detailed project information clearly, I hope this can help my project get development funding.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. However, you are still deleting the application-template as part of your PR and the application itself contains almost no details. Could you please update this? For example feel free to rename “Substrate module: X”, etc. and to specify all the deliverables for your milestones. These are basically the requirements of our contract. “we will create Dapps and decentralized applications for the development of new innovations in polkadot Blockchain Dapps.” for example is completely unspecific. What kind of dapp are you going to create? Etc. Let me know if you have any questions.

**Comment by JhonnyAllen79** [comment]
Thank you @Noc2 for replying to my message. I will try to fix it and
provide detail info.




Regards
Bika Token/Bika StarX

Pada tanggal Sen, 24 Jan 2022 14.38, David Hawig ***@***.***>
menulis:

**Comment by JhonnyAllen79** [comment]
Hi @Noc2, I've fixed and updated to increase enough detail to verify, I
hope this helps the process for validation and to speed up project
development with grant funds. If there is anything else to ask please reply.




Regards
Bika Token/Bika StarX

Pada tanggal Rab, 26 Jan 2022 11.04, Arki Ark star ***@***.***>
menulis:

**Comment by StefansArya** [comment]
Hi @JhonnyAllen79, does the team member was from Indonesian?

Because on the application you're mentioned that `team members have 3 years experience in Crypto and Blockchain project development`, can you kindly share some preview or link to your last project you have worked on that was already 3 or 2 years old?

https://github.com/w3f/Grants-Program/blob/a6b801e358252667a0209a0b33e61c0a8109a88f/applications/application-BikaToken.md#L93-L95

**Comment by JhonnyAllen79** [comment]
Hi @StefansArya, yes we have members from Singapore and Indonesia, I have a project in Crypto in 2019 but my project is the same as now experiencing a kris fund for project development, I can't share anything about my experience because the company didn't develop because I wasn't experienced before and did not have enough funds for development, so the project Bika requested a grant from Polkadot for project development so that it could advance from previous experiences.
Thank you for your reply I'm waiting to hear if the Bika project can get a grant?
If you have more questions, please reply to this message for discussion.

**Comment by JhonnyAllen79** [comment]
how @Noc2, when can Bika Project get grant funding, I will work on the development of Dapps for polkadot, I hope the W3F team give a prompt confirmation of our grant application, I thank w3f for the development on web3.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Sorry for the late reply. I was ooo last week. However, your pull request still deletes our application-template.md. Could you please change this or close the current PR and create a new one? Furthermore the application itself is still mostly based on the application template. We need you to update the application in order to even consider it. For example, we can not sign an example milestone 2 worth 4000 USD without any details! Please update the application otherwise I will close the PR.

**Comment by JhonnyAllen79** [comment]
Thanks @noc for the reply, for this it is better to close the PR. And I'll
give you a new PR.


Regards
Bika Token/Bika StarX



Pada tanggal Sen, 31 Jan 2022 14.42, David Hawig ***@***.***>
menulis:

**Comment by Noc2** [comment]
Got it. I will close the PR in this case.

**Pull request closed without merging**
