### PR TITLE
Distributed Cryptography for Polkadot Wallets application

### PR DESCRIPTION
**Pull request by janbormet**
#### Project Abstract

This project aims to combine BIP-32 compatible hierarchical deterministic wallets with distributed (threshold) cryptography into a novel wallet scheme that brings advanced security and usability to the Polkadot ecosystem. This application covers cryptographic research on threshold cryptography and crypto wallets, while a follow up application will target an implementation of our proposed cryptographic protocols.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by nikw3f — CHANGES_REQUESTED** [review]
Can you please provide the info on deliverables. Are your delivering whole wallet or just libraries. Will this wallet be a browser extension or native or mobile?

**Comment by janbormet** [comment]
This application covers basic research into a novel cryptographic wallet protocol. While we will consider "implementability" and provide important considerations for implementation in our deliverables (see Milestone 4), there will be no implementation as part of this specific application (as mentioned at the beginning of the Project Details section). The milestones provided and the respective deliverables reflect this fact. Once we successfully finish this project, we plan to implement our result through a follow up grant application. The circumstances of this follow up implementation (library vs. application, desktop/browser/mobile, programming language) will be specified within the follow up application as they may depend on the nature of the results and learnings from the research project. If some of the deliverables listed in the application remain unclear, it would be great if you can tell us so that we can clarify them.

**Review by keeganquigley — CHANGES_REQUESTED** [review]
Thanks for the application @janbormet we have a separate [template for research grants](https://github.com/w3f/Grants-Program/blob/8504089cd7ec531282ca8251303f50bf1d687784/applications/application-template-research.md), in which 0a. - 0d. are mandatory deliverables. Can you update to include these and specify which license type you would be using for the publication(s)?

I'll also ping my colleague @burdges in case he is available to take a look since you mentioned talking to him.

**Comment by janbormet** [comment]
Thank you @keeganquigley! We have carefully adjusted the Development Roadmap section to the requirements of the research template. I have amended the commit and force pushed so that there is still only one commit.

**Review by Noc2 — APPROVED** [review]
Sorry for the delay here. I'm personally happy to go ahead with it. But I will also ping @burdges again since he might be interested in the project.

**Comment by sebastianfaust** [comment]
> Sorry for the delay here. I'm personally happy to go ahead with it. But I will also ping @burdges again since he might be interested in the project.

Thanks a lot! You may also include Handan Kilinc Alper. We were also talking to her several times.

**Comment by Noc2** [comment]
> Thanks a lot! You may also include Handan Kilinc Alper. We were also talking to her several times.

Thanks. I pinged her as well

**Review by nikw3f — DISMISSED** [review]

**Review by keeganquigley — DISMISSED** [review]
Thanks for making the changes @janbormet I'm happy to go ahead with it as well.

**Review by laboon — DISMISSED** [review]

**Review by semuelle — APPROVED** [review]
Happy to support this. I would just like to suggest maintaining a (high-level) log for those deliverables that might not result in its own section/chapter in the article that you can share with us when delivering the milestone, because the specification of some of the deliverables is somewhat vague ("we will investigate..."). That makes it easier for us to evaluate.

**Review by semuelle — APPROVED** [review]

**Review by nikw3f — APPROVED** [review]

**Review by takahser — APPROVED** [review]

**Comment by sebastianfaust** [comment]
Hi all,

Thanks a lot for accepting the grant. As we have an important deadline in mid October, would it be OK if we start the project by end of October?

Best,
Sebastian

**Comment by keeganquigley** [comment]
Hi @janbormet how is milestone 2 coming along, are you still working on it?

**Comment by keeganquigley** [comment]
pinging @janbormet

**Comment by janbormet** [comment]
Hi Keegan,


Thank you for reaching out and sorry for the late reply due to the holiday season!


Yes, we are still working on the grant. While working on the next milestones, we discovered a promising research direction that is of independent interest. In a nutshell, we are currently designing a novel scheme for a Threshold Exponent VRF (TEVRF), which may allow us to derive keys from hardened nodes in Threshold BIP32 wallets in a non-interactive manner. Hence, over the last months we focused more on this topic and how TEVRFs can be helpful to BIP32 Threshold Schnorr wallets.


We are currently working on a submission to Financial Crypto 25 (expected deadline is in September / October). We plan to publish these results on ePrint after the submission process is finished and also submit the results as part of some of the next milestones.


On top of that, we also will finish our work on threshold BIP32 Schnorr wallets for the Polkadot ecosystem. Our next step is putting together the security model and protocol pseudocode.

Following the review of Jeff Burdges, we propose that we just write the final result and make a new milestone submission whenever the items covered in a milestone are present in the draft. This will also save us time and the final result will be the same. We hope this is fine with you.


We apologize for any inconvenience, but as already pointed out in our grant proposal, our goals are rather basic research and hence having a perfectly fitting milestone list does not make much sense to us. It is quite common to have side tracks that lead to interesting results, so hopefully in the end everyone will benefit from it.

**Comment by keeganquigley** [comment]
Hi @janbormet just checking in :) Any updates you can provide on the ePrint situation?

**Comment by janbormet** [comment]
Hey @keeganquigley ,
in the process of preparing the FC submission we came across this paper https://link.springer.com/chapter/10.1007/978-3-031-68394-7_10 on "Round-Optimal, Fully Secure Distributed Key Generation" by Jonathan Katz.
It presents a similar construction to ours, but in the context of DKG, and we were not able to adjust our work in time for the FC submission.
We want to delay eprint publication or submission to another conference until we are able find more novel contribution.

Nevertheless, our work on Threshold Exponent VRF is in a good state and we are glad to share the results and the writeup through a normal milestone submission, which we plan to submit as a PR by end of next week.
In this submission we will also outline our suggestions on how to proceed with the project, as discussed previously in this thread.

**Comment by keeganquigley** [comment]
Sounds good @janbormet thanks for the update!

**Comment by keeganquigley** [comment]
Hi @janbormet do you still plan to submit a PR soon? Or should we perhaps put it on hold for now?

**Comment by janbormet** [comment]
Hi, we submitted a week ago :)
You can find it here:
https://github.com/w3f/Grant-Milestone-Delivery/pull/1225

**Comment by keeganquigley** [comment]
Thanks @janbormet my apologies, was going through the sheet and didn't see the delivery.

**Comment by keeganquigley** [comment]
Hi @janbormet how are milestone 4 + 5 coming along? Can you provide an update?

**Comment by janbormet** [comment]
Hey @keeganquigley,
we are planning to upload the whitepaper by 10 th of May!

**Comment by keeganquigley** [comment]
Thanks for the update @janbormet much appreciated. Are you also still planning to submit the security analysis for M4? Thanks and have a great weekend.

**Comment by keeganquigley** [comment]
pinging @janbormet

**Comment by sebastianfaust** [comment]
Hey @keeganquigley,
@janbormet is currently on holidays. We already included a comprehensive security analysis of TEVrfs in the previous milestone. We will also establish the security of the overall wallet (the still missing part) in the upcoming milestone, making use of our results from the TEVrf anslysis. This will complete the entire scope of the project and can then be used as a reference to implement an efficient distributed/threshold wallet over Polkadot.

**Comment by keeganquigley** [comment]
Thanks @sebastianfaust sounds good. I was just looking for a more general update on the status of M4, so thank you and have a great weekend!

**Comment by janbormet** [comment]
Hi @keeganquigley 
we submitted the final milestone earlier this week. Looking forward to the reviews :)

**Comment by janbormet** [comment]
Hey, can we get an update on how the final review is going?
Best,
Jan

**Comment by semuelle** [comment]
Sorry for the delay, @janbormet. I was just talking to the research team. We hope to have some feedback in the next couple of days.

**Pull request merged**
