### PR TITLE
Create Zebraswap.md

### PR DESCRIPTION
**Pull request by DIMOCODE**
#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. However, level 1 grants are up to 10k and definitely not 1,3 million. Also the total costs are different from the sum of the costs of the milestones. For a project this size, we would need to have a lot more technical details. What kind of bridges do you want to develop? Do you already have a specification? Why is your solution better than existing ones, etc.

**Comment by DIMOCODE** [comment]
> Thanks for the application. However, level 1 grants are up to 10k and definitely not 1,3 million. Also the total costs are different from the sum of the costs of the milestones. For a project this size, we would need to have a lot more technical details. What kind of bridges do you want to develop? Do you already have a specification? Why is your solution better than existing ones, etc.

Hello there, thank you for your quick revert, apologies for the confusion there, we were asked to apply for the grants (by Mr. Robin) level by level in order to gain trust and redeem ourselves ,have made changes to the application to reflect the same . Please do let us know what more info is required.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update and the huge price reduction. But it still would be nice to have better defined milestone tables. For example “Developing the collateralized interoperable bridges and infrastructure design: The System infra will be built and ready to enable cross chains and multi-chain liquidity pools”, could mean that you create a bridge between any kind of blockchains completely unrelated to our ecosystem. So could you add a little bit more technical details (also things like programming language/framework)? Alternatively for 10k you could also simply focus on things that you need to develop and that doesn’t already exist in our ecosystem and describe it in detail.

**Comment by DIMOCODE** [comment]
> Thanks for the update and the huge price reduction. But it still would be nice to have better-defined milestone tables. For example “Developing the collateralized interoperable bridges and infrastructure design: The System infra will be built and ready to enable cross chains and multi-chain liquidity pools”, could mean that you create a bridge between any blockchains completely unrelated to our ecosystem. So could you add a little bit more technical details (also things like programming language/framework)? Alternatively for 10k, you could also simply focus on things that you need to develop and that don’t already exist in our ecosystem and describe it in detail.

Thanks for your guidance on updating the grant application. Have re-shuffled some info and added a more in-depth point of focus on the missing links that currently are not present in the ecosystem. Along with editing the milestones and adding in technical languages etc. Please do let us know if you have any feedback on the same. Thanks again!

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the update. I have a couple of follow-up questions/comments

- We usually don’t support the development of solidity smart contracts via our grants program, since we are no experts when it comes to solidity and what was already developed, etc. You could either focus on ink! smart contracts instead or apply for a grant from an ethereum focused parachain, like https://moonbeam.foundation/grants/ 
- What is the advantage of your solution compared to https://github.com/interlay (BTC) and https://github.com/Snowfork/snowbridge (Binance smart chain)?  
- Also “Using solidity for smart contracts for the Dapp as well as bridges” is still not really specific.

**Comment by DIMOCODE** [comment]
Hey NOC, apologies for the confusion there, have delved more in depth:. 

> * We usually don’t support the development of solidity smart contracts via our grants program, since we are no experts when it comes to solidity and what was already developed, etc. You could either focus on ink! smart contracts instead or apply for a grant from an ethereum focused parachain, like https://moonbeam.foundation/grants/

> **regd the Smart contracts ( there would be two sets, an EVM compatible tab and a native Polkadot smart contract, for the native Polkadot one we will be using !ink, and for the EVM compatible version embedded in the DApp itself we will be using solidity for those set of contracts** 

> * What is the advantage of your solution compared to https://github.com/interlay (BTC) and https://github.com/Snowfork/snowbridge (Binance smart chain)?
> **Both are great bridges! however, we aim to have more of these similar bridges with different crypto and NFT assets flowing from them. The infrastructure is a bit different for the bridges which is one of the biggest differences since we will be implementing bridges that are operated by a group of permissionless, decentralised bridge nodes that a re-elected every single month. These nodes collectively use a combination of Secure Multipart Computation (sMPC) and Shamir’s Secret Sharing (SSS) to collectively generate signatures to secure crosschain assets. This approach is far more secure than the multisig approach used by many other cross-chain bridges. Additionally, this approach ensures that no single node or entity ever has access to a user’s assets **
> * Also “Using solidity for smart contracts for the Dapp as well as bridges” is still not really specific.
again apologies for the vagueness and confusion, have made some more changes hope this makes things clearer.

Looking forward to your valuable feedback.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. Could you potentially integrate the Secure Multipart Computation (sMPC) and Shamir’s Secret Sharing (SSS) part into the deliverables and maybe add a little bit more details regarding this? So your bridge would be actually more similar to this: https://github.com/ChainSafe/ChainBridge, with the advantage that you don't rely only on a multi-sig solution. Also please remove any tokens from the deliverables, like “DOT<>BSC”, we mostly focus on the open source software with this grants program and don’t care about the actual deployment.

**Review by Micassa93 — APPROVED** [review]
💯

**Comment by DIMOCODE** [comment]
> Thanks for the update. Could you potentially integrate the Secure Multipart Computation (sMPC) and Shamir’s Secret Sharing (SSS) part into the deliverables and maybe add a little bit more details regarding this? So your bridge would be actually more similar to this: https://github.com/ChainSafe/ChainBridge, with the advantage that you don't rely only on a multi-sig solution. Also please remove any tokens from the deliverables, like “DOT<>BSC”, we mostly focus on the open source software with this grants program and don’t care about the actual deployment.

Hello there, thanks again for the suggestions, I have updated the above-mentioned suggestions! Can't wait to start building on polka!!

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. I still would like to have more information about sMPC and SSS. How exactly are you going to implement this? Could you provide more technical information? In the meantime, I will mark the application as ready for review so that others can also look at it.

**Comment by alxs** [comment]
@DIMOCODE since your proposal has now been in the review state for over 2 weeks without any approvals or comments from other members of the committee, I'll go ahead and close it. This application may not have succeeded in swaying the committee, but don't be discouraged—check out other [sources of funding](https://github.com/w3f/Grants-Program#rocket-alternative-funding-sources) in the ecosystem, or otherwise you're always welcome to apply again with another project.

**Pull request closed without merging**
