### PR TITLE
Create AgriDot.md

### PR DESCRIPTION
**Pull request by kacena123**
#### Project Abstract

AgriDot is an innovative agricultural application designed specifically for farmers and beekeepers. It leverages Polkadot's NFT technology to improve agricultural management, raise farmer awareness, and promote community collaboration.

The proposal introduces a solution for integrating an agricultural use case into Polkadot, addressing an existing gap by bringing new niche use cases and a specialized user base to the platform. It allows farmers to outsource valuable information about their fields, track nearby pests, and learn new practices and tips through guides.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (Polkadot AssetHub (DOT, USDC & USDT) address in the application and bank details via email, if applicable).
- [x] I understand that an agreed upon percentage of each milestone will be paid in vested DOT, to the Polkadot address listed in the application.
- [x] I am aware that, in order to receive a grant, I (and the entity I represent) have to successfully complete a KYC/KYB check.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by kacena123** [comment]
I have read and hereby sign the Contributor License Agreement.

**Review by keeganquigley — CHANGES_REQUESTED** [review]
Thanks for the application @kacena123 could you please provide a bit more info on how we will be able to test these components and evaluate them upon milestone delivery? For example, do you plan to integrate any unit tests and e2e tests, and if so can you include this in the language?

**Comment by kacena123** [comment]
Hello @keeganquigley , 
Thank you for your evaluation, as mentioned in milestone delivery 0.c - "We will provide **unit tests** for core application functionality. Guide on how to launch these tests will be mentioned in the README.md."

So, as mentioned all core functionality will be covered by comprehensive **unit tests**, which will be easily launchable by one command mentioned in README.md. 

All functionality will also be testable by running the solution locally. 

If you have any other questions, feel free to ask.

Best regards, 
Katarina

**Comment by keeganquigley** [comment]
Thanks for the changes @kacena123 I will mark the application as ready for review so the rest of the committee can comment.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. I'm generally happy to support it. But could you add more details to the specification of each milestone? For example, what exactly are the technical functions regarding "Fields as NFTs (Private)"? Is this only implemented in the app or also on-chain in a pallet, etc.?

**Comment by kacena123** [comment]
Hello @Noc2 ,
Thank you for your feedback, I have added the required technical details that I felt could be more specific. 

Hope, the milestones are defined better now.
If you have any other questions, feel free to ask.

Best regards,
Katarina

**Review by Noc2 — CHANGES_REQUESTED** [review]
Which NFT pallet are you going to use?

**Comment by kacena123** [comment]
@Noc2 ,

As stated in the proposal - a pallet called [NFTs](https://wiki.polkadot.network/docs/learn-nft-pallets#nfts-pallet). 

During our research, we discovered, that there is also a pallet called Uniques, but this pallet is deprecated.

I have updated the proposal to display the choice of the pallet better.

If you have any other questions, feel free to ask.

Best regards,
Katarina

**Review by keeganquigley — APPROVED** [review]
Thanks for the changes @kacena123 I'm willing to give it a shot.

**Comment by keeganquigley** [comment]
In the meantime, we perform [KYC verification](https://in.sumsub.com/idensic/l/#/uni_mjcB05gJZfh8dbr7) for all grantees. Could you fill out the information there please?

**Comment by kacena123** [comment]
@keeganquigley ,

Thank you for the approval!

I have just filled out the KYC form. 

Best regards,
Katarina

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I'm happy to go ahead with it.

**Pull request merged**
