### PR TITLE
Crossbow Grant

### PR DESCRIPTION
**Pull request by enfipy**
### Crossbow Grant

A goal of the `crossbow` (formerly `creator`) project is to provide a complete infrastructure for game development in rust. In addition, the project simplifies the creation and packaging of crates for Android, iOS, and other platforms. Finally, we want to make most of our tools - engine agnostic to help rust game developers integrate them into their games, engines, and crates.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Comment by enfipy** [comment]
This is a draft pull request because it adds the `maintenance` grants folder and needs revision on the grant application file format. Any suggestions are highly appreciated!

@alxs As we discussed in element.io - creating this draft pull request for its further enhancement. Also, I couldn't find any information about adding bank account numbers inside the grant application or only invoices after each deliverable?

**Comment by semuelle** [comment]
Hi @enfipy. Alex is out of office. Apparently, you have already discussed this with him privately, but I'll still try to answer this.

> This is a draft pull request because it adds the `maintenance` grants folder and needs revision on the grant application file format. Any suggestions are highly appreciated!

I think it would make sense to put the template into a separate PR, because it might require some discussion, and it's not directly related to your grant. 

> I couldn't find any information about adding bank account numbers inside the grant application or only invoices after each deliverable?

You should fill out [this form](https://docs.google.com/forms/d/e/1FAIpQLSfMfjiRmDQDRk-4OhNASM6BAKii7rz_B1jWtbCPkUh6N7M2ww/viewform). You will have to provide the same information as in your .md document, but it will allow you to provide fiat payment information privately. You can refer to this PR where the form asks for a Google doc and a pull request.

**Comment by enfipy** [comment]
@semuelle Thank you for your quick response! Created new PR with application template and filled the form as you recommended.

Also, we will highly appreciate any feedback on our grant application.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Sorry for the late reply here and thanks for creating the template as well as the first maintenance grant application. We had also to discuss internally a little bit what qualifies for maintenance grants and what is still a regular grant. Regarding maintenance grants, I think a project needs to be at least ready (see https://youtu.be/fsKyQ5Fgcpk?t=388) ~ core features are complete (obviously subjective). Based on this, I personally would say that this grant looks to me more like a regular grant. You have a lot of features you still want to implement and your project still seems to be in a rather early stage (most issues are created by you https://github.com/dodorare/crossbow). Therefore, I would recommend changing the application to a regular grant application, but also feel free to disagree ;-)

**Comment by enfipy** [comment]
Hi all! I just updated the grant application and will appreciate any feedback! @Noc2, is there something else we should change?

**Comment by semuelle** [comment]
Thanks for the update, @enfipy. We will look into it, it might take a bit though as most of the team is out of office this week.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. Could you add the deliverables 0a-0d of the template to your application? These are mandatory for all milestones, and deliverable 0e at least for the last one.

**Comment by enfipy** [comment]
Hey @Noc2. I just updated the application and added the mandatory deliverables that you mentioned. Also, we think deliverable 0e (article) - will be super cool to make after Milestone 3 as we will show the main functionality with plugins and some Android API (with how to add it to your game).

Also, we added to this project our rust game developer that has experience (and contributions) in Amethyst and Macroquad. So we hope to finish all milestones on time.

Feel free to give other feedback or changes :)

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. Just one minor thing: Could you add 0a to 0d also to milestone 2 and 3?

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I will share it with the rest of the team.

**Review by alxs — APPROVED** [review]

**Review by semuelle — APPROVED** [review]

**Comment by alxs** [comment]
@enfipy by the way, is Substrate integration still a part of Crossbow? A quick search in the repository doesn't return anything, and it'd seem that it was removed from the project since the first grant as Creator. The main reason we were willing to support this grant was that we believed it would make it easier to develop mobile games that integrated with Substrate - could you add it to the feature set again, or is it indeed still there and I'm just missing it?

**Comment by enfipy** [comment]
@alxs Yes, sure! I think we just need to clarify things in documentation specifically for Substrate developers. We just moved some things out because wanted to make better templating in crossbundle.

**Comment by semuelle** [comment]
Hey @enfipy. Just checking in here. Are you still working on Milestone 2? According to my calculations it was scheduled for March.

**Comment by enfipy** [comment]
Hey, @semuelle! Yes, absolutely. Sorry for this huge delay! As always, estimates on the plugins were highly optimistic, and we are just finishing it. We already made 90% of Milestone 2, but we really want to finish everything to present it to you! So we will try to deliver Milestone 2 in a week from now. Is it okay? Sorry again for the delay! 🙏

**Comment by semuelle** [comment]
Thanks for the update, @enfipy. No worries about the delay. Don't rush things on the last meters. We just like to keep tabs on teams to see if we can help. Looking forward to your delivery.

**Comment by enfipy** [comment]
Hello @semuelle.

Finally, we finished Milestone 2 and will be happy to be reviewed. Here's the link to [Milestone Delivery Pull Request](https://github.com/w3f/Grant-Milestone-Delivery/pull/499).

If you encounter any issues - please let me know. ✨

**Comment by enfipy** [comment]
Hello everyone!

We finished Milestone 3 and will be happy to be reviewed. Here's the link to it: https://github.com/w3f/Grant-Milestone-Delivery/pull/550.

If you encounter any issues or questions - please let us know! 🙂

**Comment by alxs** [comment]
Hi @enfipy! Thanks a lot for the delivery. That sounds like a good option to me too - I'll leave the information in the delivery PR so nobody misses it.

**Pull request merged**
