### PR TITLE
Re-open ISO-8583 RFP grant

### PR DESCRIPTION
**Pull request by dastansam**
### Description

I lost access to my email that receives GitHub notifications and thus wasn't able to reply to @keeganquigley comments on time. Just found out that the grant was [terminated](https://github.com/w3f/Grants-Program/pull/2177) because I was on the verge of submitting milestone delivery.

To back up my claims, here are the PRs with active commit history in the relevant repos I was working on:

https://github.com/subclone/iso8583-chain/pull/1
https://github.com/subclone/payment-processor/pull/5

Once re-opened, I will submit the remaining milestone delivery as soon as possible. And in the future, I will make sure to respond W3F comments on time.

Thanks for your understanding

cc @Noc2

### CODE REVIEW

**Review by Noc2 — APPROVED** [review]
Thanks a lot for creating the PR. I'm happy to approve it.

**Comment by Noc2** [comment]
For reference, here is the original application: https://github.com/w3f/Grants-Program/pull/1809

**Review by semuelle — APPROVED** [review]

**Review by keeganquigley — APPROVED** [review]

**Comment by keeganquigley** [comment]
Thanks for the notice @dastansam once this is merged I will update the status. In the meantime you can go ahead and submit the delivery when its ready.

**Comment by dastansam** [comment]
> Thanks for the notice @dastansam once this is merged I will update the status. In the meantime you can go ahead and submit the delivery when its ready.

thanks for understanding, really appreciate it!
Sure, I will polish the deliverables and start preparing them for the delivery.

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/polkadot-iso-20022-integration/8483/1

**Comment by Eldo420** [comment]
Certainly! Let's delve deeper into the solution, expanding on each section to provide a more comprehensive view of the ISO-8583 toolkit. This includes detailed module design, potential challenges, and additional considerations for production readiness.

### 1. Detailed Project Overview
The primary objective is to create an ISO-8583 toolkit/library that can be integrated into existing financial systems seamlessly. The toolkit should cater to the needs of various financial institutions by being easily configurable and extensible.

1. **Cross-Version Support**: 
   - **ISO-8583:1987**: Basic fields and early transaction types.
   - **ISO-8583:1993**: Enhancements like field lengths and added data elements.
   - **ISO-8583:2003**: Further additions including more transaction types and field definitions.

### 2. In-Depth Functional Requirements

#### a. Message Parsing and Building
- **Parser**:
  - Capable of interpreting raw byte streams into structured data formats.
  - Should cater to various field lengths and encoding types.
- **Builder**:
  - Construct messages from scratch, ensuring all mandatory fields are present.
  - Methods to add, modify, and delete fields.

#### b. Field Definitions
- **Standard Fields**: Implement all standard fields as per the ISO-8583 specification.
- **Custom Fields**: Provide mechanisms for users to define and handle proprietary fields.

#### c. Validation
- **Standard Validation**: Ensure that messages adhere to ISO-8583 standard rules.
- **Custom Validation**: Allow users to implement specific validation rules.

#### d. Encoding/Decoding
- **Data Encoding Formats**: Support various encodings such as ASCII, EBCDIC, BCD, binary.
- **Multibyte Encodings**: Handle different byte encodings transparently.

#### e. Logging and Debugging
- **Logging**: Implement robust logging mechanisms using libraries like `logging` in Python for detailed inspection.
- **Debugging Tools**: Provide tools for visualizing and analyzing ISO-8583 messages.

### 3. Comprehensive Technical Approach

#### a. Language Choice: Python
- **Python Advantages**:
  - Readability and ease of use.
  - Robust libraries for encoding, decoding, and network communication.

#### b. Library Design
- **Core Module**: 
  - `IsoMessage`: Class to represent an ISO-8583 message. Responsible for setting/getting fields, packing, and unpacking messages.
- **Field Module**: 
  - `IsoField`: Class representing individual ISO-8583 fields. Handles encoding and decoding of specific field types.
- **Validation Module**: 
  - `IsoValidator`: Class to validate ISO-8583 messages against standard and custom rules.
- **Utilities Module**: 
  - Encoding, decoding helpers, and logging functionalities.

### 4. Example Implementation Expanded

```python
from iso8583 import Iso8583, IsoField, IsoValidator  # hypothetical library

class IsoMessage:
    def __init__(self, version):
        self.version = version
        self.fields = {}

    def set_mti(self, mti):
        self.mti = mti

    def get_mti(self):
        return self.mti

    def set_field(self, field_id, value):
        self.fields[field_id] = IsoField(field_id, value)

    def get_field(self, field_id):
        return self.fields[field_id].value if field_id in self.fields else None

    def pack(self):
        # Packing logic, handling fields and encoding based on ISO-8583 standards
        packed_message = b''
        # compose mti, bitmap and field data
        return packed_message

    def unpack(self, iso_message):
        # Unpacking logic to parse raw message into fields
        pass

    def validate(self):
        validator = IsoValidator(self)
        return validator.validate()

class IsoField:
    def __init__(self, field_id, value):
        self.field_id = field_id
        self.value = value

class IsoValidator:
    def __init__(self, iso_message):
        self.iso_message = iso_message

    def validate(self):
        errors = []
        # Validate MTI
        if len(self.iso_message.get_mti()) != 4:
            errors.append("Invalid MTI length")
        # Additional field validations
        for field_id, field in self.iso_message.fields.items():
            if not self._validate_field(field):
                errors.append(f"Field {field_id} validation failed")
        return len(errors) == 0, errors

    def _validate_field(self, field):
        # Validate individual field based on its type and value
        return True

# Example usage
msg = IsoMessage(version='1987')
msg.set_mti('0200')
msg.set_field(2, "4000001234567899")  # PAN
msg.set_field(4, "000000010000")      # Transaction Amount
iso_message = msg.pack()
print(f"Packed ISO8583 Message: {iso_message.hex()}")
received_msg = IsoMessage(version='1987')
received_msg.unpack(iso_message)
mti = received_msg.get_mti()
amount = received_msg.get_field(4)
print(f"MTI: {mti}")
print(f"Transaction Amount: {amount}")
valid, errors = received_msg.validate()
if valid:
    print("Message is valid")
else:
    print(f"Message validation failed: {errors}")
```

### 5. Detailed Documentation

#### a. User Guide
- **Installation**:
  ```sh
  pip install iso8583lib
  ```
- **Usage Examples**: Complete examples covering typical use cases.
- **Configuration**: Details on configuring the toolkit for different versions and custom fields.
- **Best Practices**: Guidelines on integration and performance optimization.

#### b. API Reference
- Detailed descriptions of each class, method, and function.
- Examples illustrating each API’s usage.

#### c. Contributions Guide
- **Coding Standards**: PEP 8 (for Python) or equivalent for better code quality.
- **Branching and Workflow**: Guidelines on using Git, including branching strategies, pull requests, and code reviews.
- **Issue Tracking**: Best practices for reporting and resolving issues.

### 6. Robust Testing

#### a. Unit Tests
- Write tests for each module and function using a testing framework like `unittest` or `pytest`.
- Ensure edge cases and error scenarios are covered.

#### b. Integration Tests
- Simulate end-to-end scenarios using real financial transaction flows.
- Ensure messages can be parsed and constructed correctly.

#### c. Compliance Tests
- Implement tests to verify compliance with different versions of the ISO-8583 standard.
- Include regression tests to ensure new changes do not break existing functionality.

### 7. Comprehensive Project Management

#### a. Version Control
- **Git**: Use Git for code versioning.
- **Branch Management**: Implement a consistent branching strategy such as Git Flow.

#### b. Continuous Integration
- **CI/CD Pipelines**: Set up pipelines using tools like GitHub Actions, Travis CI, or CircleCI.
- Automate testing and deployment processes to ensure quality and reduce manual effort.

#### c. Issue Tracking
- **Tooling**: Use tools like Jira, GitHub Issues, or Trello for tracking development progress and bugs.
- **Scrum/Kanban**: Employ agile methodologies like Scrum or Kanban for iterative development and better team collaboration.

### 8. Submission and Follow-up
As part of the Web3 Foundation (W3F) Grants Program:

1. **GitHub Repository**:
   - Create a public repository with proper setup and access instructions.
   - Document all necessary details for evaluation and future development.

2. **Contact Information**:
   - **Matrix Username for Discussion**: -
   - **Email**: ferbianoerduado@gmail.com

This comprehensive approach ensures a robust, flexible, and compliant toolkit for ISO-8583, facilitating seamless integration into financial systems while allowing for customization and extensibility.

**Pull request merged**
