### PR TITLE
Application for polkadot-validator-setup repo maintenance

### PR DESCRIPTION
**Pull request by roberts-ivanovs**
#### Project Abstract

> The Polkadot validator setup repository is a vital resource for users to establish and operate Polkadot validator nodes. It enhances the ecosystem by increasing accessibility, bolstering security, and improving stability. Our team will address [the RFP's ](https://github.com/w3f/Grants-Program/blob/6e2e98e0f0f3ad7e10521c6269b1f4471c848ff8/docs/RFPs/Open/validator-setup-maintenance.md)concerns by fixing issues, updating documentation and dependencies, expanding Terraform backends and cloud provider support, and investigating pass-phrased SSH key deployment. We will also identify potential areas for future maintenance or enhancements.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. I have one initial question: Are you aware of https://github.com/polkachu/polkadot-validator? I think it does a lot of the things that we intended to do with the RFP, and we probably should have updated the RFP by now.

**Comment by roberts-ivanovs** [comment]
@Noc2 
> I have one initial question: Are you aware of https://github.com/polkachu/polkadot-validator?

Yes, we are aware of it. Would you prefer that we take the direction of polkachu's repository and incorporate the same functionality that they offer? I think we could use it as a solid base and direction pointer on where to take the current repository, by providing simple commands and an easy and straightforward way to start up a local validator. My proposal would be that such functionality could be added in the second milestone. 
Is there anything specific that you would like to see?

**Comment by darentuzi** [comment]
Hello @semuelle thank you for the question. My name is Daren, I am the Ceo of Eiger so I can give you more information.
[Eiger](https://eiger.co/) and [Equilibrium](https://equilibrium.co/) are sister companies in the same group, so you might not see some contributors employed on LinkedIn in Eiger but rest assured its the same people, just different brand. For example:

1.  in [SnarkOS](https://github.com/AleoHQ/snarkOS): [ljedrz](https://github.com/ljedrz) and [niklaslong](https://github.com/niklaslong) are our guys
2. in [OrbidDB](https://github.com/orbitdb/orbit-db): [aphelionz](https://github.com/aphelionz)
3. in [RustIPFS](https://github.com/rs-ipfs/rust-ipfs): [koivunej](https://github.com/koivunej) [ljedrz](https://github.com/ljedrz) [niklaslong](https://github.com/niklaslong) [aphelionz](https://github.com/aphelionz)
4. In [Interledger](https://github.com/interledger/interledger-rs):  [koivunej](https://github.com/koivunej) [ljedrz](https://github.com/ljedrz) [Mirko-von-Leipzig](https://github.com/Mirko-von-Leipzig) [aphelionz](https://github.com/aphelionz) [pradovic](https://github.com/pradovic) [KristianWahlroos](https://github.com/KristianWahlroos)
5. and all of [Ziggurat](https://github.com/runziggurat) is done by Eq and Eiger enginners

**Review by Noc2 — CHANGES_REQUESTED** [review]
Sorry for the delay here. My comment about Polkachu’s work was mostly regarding what you think would be the benefits for us to support an additional similar solution by your team. To be honest, here, I currently have two concerns: on the one hand, your monthly rate is relatively high. On the other hand, your primary motivation would be a maintenance agreement, whereas validator companies have a self-interest in maintaining these solutions in the long run. Potentially we can come up with other projects that might be in higher demand and a better fit for your team.

**Comment by Noc2** [comment]
Thanks for the quick reply. I just got in touch with you on telegram and will close the application for now. We can reopen it later if we decided that this is the best way forward.

**Pull request closed without merging**
