### PR TITLE
Maki application

### PR DESCRIPTION
**Pull request by CrommVardek**
#### Project Abstract

This application is a response from the [anti-collusion infrastructure RFP](https://github.com/w3f/Grants-Program/blob/master/rfps/open/anti-collusion_infrastructure.md)

Maki aims to be a simple MACI implementation for the Polkadot eco-system, similar to the existing one on Ethereum ([MACI](https://github.com/privacy-scaling-explorations/maci))

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by alxs** [comment]
Thanks for applying again @CrommVardek! Are you aware of [this](https://github.com/w3f/Grants-Program/pull/232) previous application for this RFP? The team didn't go ahead with the project in the end, but you might want to have a look at their [proposal](https://github.com/pajicf/Open-Grants-Program/blob/18acf2960a3b7c5a4692186b9725a05347d69047/applications/pallet_maci.md#project-details). In particular, they list a more [detailed interface](https://github.com/pajicf/Open-Grants-Program/blob/18acf2960a3b7c5a4692186b9725a05347d69047/applications/pallet_maci.md#technology-stack). How would this functionality be provided in your case? Feel free to add details to your application.

Also could you just clarify in the deliverables which language you'll use for each of them? I.e. TS for the prover vs ink! for the verifier etc.

**Comment by CrommVardek** [comment]
Hi @alxs , thanks for your comment.

I wasn't aware of that application for the same RFP, I'll read their proposal and the detailed interface (which is indeed more detailled than mine). 

I'll add more details in the Project Details section and clarify the languages used in the deliverables.

**Comment by CrommVardek** [comment]
Hi @alxs , just for information, I'll complete my application by the end of this week. Sorry for the idle time on this.

**Comment by alxs** [comment]
Sounds good, no worries and thanks for the update.

**Comment by CrommVardek** [comment]
Hi @alxs , I've added details of the interface and interactions of Maki. 
Just to add, the main difference between the pallet_maci and maki is reusability, with the latter, for each new vote round, a new contract must be deployed. Old one cannot be reused. 
This is a choice, to facilitate maintainability of Maki's usage I think it's better - when a new version of Maki is released - to just use the latest one rather than having the dilemma to choose between continue using an old one or deploy a new one.

**Comment by alxs** [comment]
Thanks a lot for the additional details - looks really good to me, I'm happy to approve it and I will share it with the rest of the committee.

**Review by alxs — APPROVED** [review]

**Review by takahser — APPROVED** [review]

**Review by Noc2 — APPROVED** [review]

**Comment by CrommVardek** [comment]
Thanks for trusting me again :)

**Comment by CrommVardek** [comment]
Hello, 

I'm just writting this comment to say that I'm still working on the 1st milestone, slower than I wish. But the project is not dead. 

However at this pace, I don't expect to be able to deliver the 1st milestone before the start of the next year. Just so you know. 

Best,

**Comment by semuelle** [comment]
Thanks for the update. Feel free to submit an amendment with updated timeline to take the pressure off, or if you think it might take longer than that.

**Comment by keeganquigley** [comment]
Hi @CrommVardek just checking in. If you still think there will be significant delays I would recommend filing [an amendment](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval) to update the timeline. Thanks!

**Comment by keeganquigley** [comment]
Hi @CrommVardek just checking to see if you can give us an update on M1, as I believe we are approaching on 6 months. Thanks!

**Comment by CrommVardek** [comment]
Hi @keeganquigley , sure, the M1 is almost done, there is still the doc that needs to be completed and the step 4 that has to be finalized as well. I cannot give you a strict deadline for me to finish the M1, but soon :)

**Comment by keeganquigley** [comment]
Thanks for the update @CrommVardek if you think it might take longer than 2 weeks please submit an amendment to extend the timeline.

**Comment by CrommVardek** [comment]
Sorry for the late reply, rather than just adding a month, I added 3 months on the the application for the first milestone in PR #1717

**Comment by keeganquigley** [comment]
Hi @CrommVardek how is the first milestone coming along?

**Comment by CrommVardek** [comment]
Hi @keeganquigley , it was terminated : https://github.com/w3f/Grants-Program/pull/1830

**Pull request merged**
