### PR TITLE
ChainViz v1 application

### PR DESCRIPTION
**Pull request by kukabi**
#### Project Abstract

ChainViz Alpha ([alpha.chainviz.app](https://alpha.chainviz.app/)) is an [open-source](https://github.com/helikon-labs/chainviz) real-time 3D visualization of the Kusama relay chain validators and block production process.

This application is to fund the building of the first major version of ChainViz, with Polkadot support, new features and redesign.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by alxs** [comment]
@kukabi this is cool! However note that we focus on funding development work that may be useful to others in the ecosystem, i.e. we don't fund things like UI/UX or audio design. Have you considered applying for [treasury](https://github.com/w3f/Grants-Program#treasury) funding instead? They don't have the same constraints and I think your project would be a much better fit for it. Let me know if you want to be put in touch with someone who can walk you through the process.

**Comment by muddlebee** [comment]
> we don't fund things like UI/UX or audio design.

I went through the application. It is more of development work only. Afaik Chainviz uses webgl for 3D rendering and new app mentioned ChainSynth also requires some engineering to produce the  **Audio Development** work. 

I was just curios. If anyone plans to propose along these lines? Design + Development? doesn't it qualify for the grants? because design research is also a part of development pipeline. We have many good projects like talisman, subscan which is user friendly because of focused design efforts.

**Comment by dkrvchnk** [comment]
Hi, @alxs @muddlebee! It's a pleasure to meet you. I am ChainViz project manager 🙂

Thank you very much for your feedback! As @kukabi pointed out, this project is mainly focused on the development part, and the design is something that will not only allow it to look fantastic but will actually be the key supportive element in creating a highly user-friendly solution.

@alxs, thanks a lot for mentioning the usefulness of the project. Here I would like to point out that this is exactly why it is not just a development work but design + development. We aim to provide a solution that will be very easy to comprehend, intuitive and highly accessible, ensuring a rise in utility and user engagement. ChainViz is already welcomed and used by the community, who raised a set of current UI/UX issues, which we will fix, add more necessary features and create an incredibly convenient and useful tool for the ecosystem with the help of a professional design team. In addition, as @muddlebee absolutely rightfully pointed out, design research is, indeed, a very important part of development: all great development projects out there always start with the design first.

**Comment by kukabi** [comment]
Thanks a lot @alxs, this clarified a lot. We're very happy that the application is finding some use in the W3F offices:) We'll have an internal discussion and update here later today.

**Comment by kukabi** [comment]
@alxs we had an internal call, and decided to exclude the design budget (-8K USD) and update the development plan so that we have full-stack feature implementation output for each milestone. Audio-related content will also be removed from milestone output. We're going to discuss and update the application today and fix the PR commit tomorrow.

And just a side note for:

> ..."Backend Services", which it sounds like you've already implemented?

Most of the services are implemented already as part of the [SubVT Backend](https://github.com/helikon-labs/subvt-backend), but we need one extra websockets service, the Block Details Service to push the extrinsics and event data for each new block to the client. This service is going to be utilized in both displaying block content and visualizing cross-chain messages (`XcmPallet` extrinsics and events). We're also going to need a new simple REST endpoint to fetch parachain list and details, though this one is negligible work compared to the websockets service.

**Comment by alxs** [comment]
@kukabi sounds good, thanks for the update! I recommend you add the details regarding the backend and any additional technical details to the application.

**Comment by kukabi** [comment]
Hi @alxs, application has been updated with the changes I mentioned yesterday. Please let us know any further issues, thanks!

**Review by keeganquigley — APPROVED** [review]
LGTM

**Review by Noc2 — APPROVED** [review]

**Comment by kukabi** [comment]
Hi @keeganquigley, it's going good however behind the initial schedule. Planning to deliver milestones 1 and 2 together in June.

**Comment by keeganquigley** [comment]
Hi @kukabi are you able to provide an update on the milestones?

**Comment by kukabi** [comment]
Hi @keeganquigley, submission & release is scheduled for the 18th of July '23. Thanks for your patience!

**Comment by kukabi** [comment]
Hi again @keeganquigley, just a notice that we have to reschedule the release again to the 1st of August '23.

We have completed the UI/UX design, development and testing of the new backend services for block details (includes XCM messages) for both Kusama and Polkadot, and most of the UI development.

Apologies for the delay and thanks for your patience.

**Comment by keeganquigley** [comment]
Thanks for the update @kukabi sounds good; if it is going to be more than 2 weeks consider filing an amendment PR. Thanks!

**Comment by kukabi** [comment]
@keeganquigley Thanks:) We're nearly there, should be live in a couple of days, will update here, then I'll prepare the submission.

**Comment by kukabi** [comment]
@keeganquigley I'd like to share some latest screenshots.

Main screen (Kusama:)
Screenshot 2023-08-11 at 14 06 54

Validator hover:
Screenshot 2023-08-11 at 14 07 20

An expanded block:
Screenshot 2023-08-11 at 14 07 35

BridgeHub validators on Polkodot:
Screenshot 2023-08-11 at 14 08 44

We have completed most of the interaction and animations, and the majority of the overall work. Outstanding work:
- XCM details display.
- Associate blocks with their authors with an animation.
- Separate block events and extrinsics panel.
- Validator list & filter.

I think we're going to be able to deliver the complete package only next week.

There's a change to the initial development plan. We're now using a combination of the Polkaholic API and the Polkadot JS API for block and XCM details. It is serving the purpose perfectly, so there was no need to develop the extra block details service.

@keeganquigley Do you think we should submit an amendment? Or should we include it all in our submission?

**Comment by Noc2** [comment]
Looks great. Feel free to also submit an amendment, just to be on the safe side.

**Comment by keeganquigley** [comment]
Thanks for the screenshots @kukabi they look nice! I agree with @Noc2 that for development changes an amendment should be submitted. It should be relatively easy to get it approved. Thanks!

**Comment by kukabi** [comment]
@Noc2 @keeganquigley thanks a lot, I'm going to submit the amendment on Sunday, and hopefully we'll submit the delivery next week.

**Comment by kukabi** [comment]
Posted the amendment @ #1906.

**Comment by kukabi** [comment]
Hi, just wanted to post the update that we've completed the development. We're working on improving the testing and preparing the submission material. I'm hoping to submit it in the week. Thanks for your patience. Attaching some screenshots.

s000

s001

s002

s003

s004

**Comment by semuelle** [comment]
Looks great, @kukabi. Thanks for the update. Looking forward to your delivery.

**Comment by kukabi** [comment]
Just submitted the delivery: https://github.com/w3f/Grant-Milestone-Delivery/pull/1005

Thanks a lot for your patience. Application is live at [chainviz.app](https://chainviz.app), source code [here](https://github.com/helikon-labs/chainviz), and the delivery document has the rest of the material.

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/decentralized-voices-program-kutsal-kukabi-helikon/6106/1

**Pull request merged**
