### PR TITLE
Ocelloids Monitoring SDK grant application

### PR DESCRIPTION
**Pull request by mfornos**
#### Project Abstract

Ocelloids is an open-source software development kit for building monitoring applications for Substrate-based networks. 

Three primary features are planned to be delivered as part of the grant:

1. Multi-chain support: configurable multi-chain wrapper for Polkadot.js Promise and Rx APIs to simplify setup for multi-chain monitoring.
2. Core Components: a set of reactive operators for sourcing core Substrate data, such as events and extrinsics, and reactive controls for filtering and transformation over it. The core components will encapsulate common patterns like call batching and multi-signature calls.
3. Domain logic for ink! smart contracts monitoring.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. This a quick reminder to sign our terms and conditions. Could you add a little bit more information regarding the example application (e.g. will it be a UI, what kind of programming language are you going to use, etc.) and, in general, your long-term goal with this project?

**Comment by mfornos** [comment]
I have signed the CLA, but seems that is not being updated.

If it needs to be signed by all the committers, I am afraid that we should re-submit the application because I have lost the mobile phone with the 2FA app for the `frozen.pomelo` account :cry: (and don't have any backup recovery methods for that account)

Otherwise, we are happy to update this one with details regarding the example application and the long term goals of the project.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. The payment address still needs to be added. Also, are you aware of [Sub-Api](https://github.com/kodadot/packages/tree/main/sub-api)?

**Comment by mfornos** [comment]
> Thanks for the update. The payment address still needs to be added. Also, are you aware of [Sub-Api](https://github.com/kodadot/packages/tree/main/sub-api)?

Updated payment details.

We checked out Sub-Api and considered it for our first feature of multi-chain support. However, the project only exposes the Promise APIs and not the underlying reactive APIs of Polkadot.js. Since the main focus of our SDK is on reactive streams, Sub-Api is not suitable for our needs. (+ we prefer a fluent interface to access the API instances)

**Comment by mfornos** [comment]
Hi @Noc2,

In terms of pricing, the rate of this application is already 20% lower relative to the previous grants we have worked on. e.g. [Epirus Substrate P2](https://github.com/w3f/Grants-Program/blob/master/applications/epirus_substrate_phase_2.md)

We are confident in a high-quality delivery of the proposed features, which are not trivial and require a great deal of API design and domain knowledge. We set an unbuffered estimation, so the implementation could take more effort than estimated.

Since we believe the project has high potential and is very promising for the ecosystem, we are willing to lower the price to 28k.

Please, let us know if this works for you so we can update the document.

**Comment by mfornos** [comment]
Hi @Noc2 
We are thinking on replacing the "domain logic for staking and nomination pools" (delivery item 2) by "domain logic for ink! contracts monitoring" and the example command line app (delivery item 3) accordingly. Currently there are no tools for ink! contract monitoring and it will be a necessity for the ecosystem.

Would you be happy to support this rather than the "staking and nomination" logic?

**Review by semuelle — CHANGES_REQUESTED** [review]
Hi @mfornos. Thanks for the application. 

- Would you mind sharing what your roles were at Web3 Labs?
- When you say your "long-term vision is to offer an end-to-end solution accessible as a web application", do you mean you are planning to offer it as a service?

Regarding your comment: while we have signed ink! monitoring related grants in the past, I think that'd be a better first deliverable than the staking one.

**Comment by mfornos** [comment]
Happy to hear from you @semuelle 

To answer your questions:

> Would you mind sharing what your roles were at Web3 Labs?

We were providing software development services to Web3 Labs as freelance contractors.

During our time there, we started the Epirus Substrate project which involved:
-   Writing the grant application documents, including the UI mock-ups and the software architecture.
-  Defining the features and UI/UX.
-  Designing and implementing the systems, web applications and tools.
-  Preparing the grant deliveries, including deploying, running and operating the services and writing the technical documentation.

In addition, I was also in charge of evolving and operating the close-sourced hosted Ethereum explorer.
We ended our contracts in March and have handed over both projects to a new team.

> When you say your "long-term vision is to offer an end-to-end solution accessible as a web application", do you mean you are planning to offer it as a service?

Yes, we intend to build a full-fledged monitoring service for the Substrate ecosystem on top of the proposed SDK. During our exploration phase, we realised that a good foundation of sourcing and filtering data from Substrate networks is not trivial and a good solution is currently lacking in the ecosystem. Hence, we want to build the base as an open-source SDK so that other teams can benefit from the technology.

I hope this answers your questions :)

We will update the application document to replace the staking feature with ink! contract monitoring.

**Comment by mfornos** [comment]
We've updated the application document with the ink! smart contracts monitoring and adjusted the time estimation to 2 months.

If everything sounds good to you, shall we move forward?

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks again for the update. I have one last question: Would you still be willing to reduce the price to 28k?

**Comment by mfornos** [comment]
Sure @Noc2 we updated the price :)

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I'm happy to go ahead with it and I will share it again with the rest of the team.

**Comment by keeganquigley** [comment]
Thanks for making the changes and reducing the price @mfornos I'm happy to also go forward with it.

**Review by keeganquigley — APPROVED** [review]

**Comment by keeganquigley** [comment]
Hi @mfornos thanks for your patience during the review process. I will ping the committee again and ask them to take a look.

**Review by semuelle — APPROVED** [review]
Sorry for the late reply, @mfornos. Happy to proceed.

**Pull request merged**
