### PR TITLE
Create dauth_network.md

### PR DESCRIPTION
**Pull request by yyd106**
#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [x] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@deanyyd:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by semuelle — APPROVED** [review]

**Review by randombishop — APPROVED** [review]
LG

**Review by keeganquigley — APPROVED** [review]
LGTM

**Review by Noc2 — APPROVED** [review]

**Comment by keeganquigley** [comment]
Hi @yyd106 how is milestone 1 coming along?

**Comment by yyd106** [comment]
> Hi @yyd106 how is milestone 1 coming along?

Hi @keeganquigley , We will need another week, but we will deliver both milestones at once. This is because we found a close correlation between the two milestones, and the project team needs to use the DAuth SDK. So we decide to deliver a finalized version. Is that work?

**Comment by keeganquigley** [comment]
Thanks for the update @yyd106 yep that works.

**Comment by keeganquigley** [comment]
Hi @yyd106 any news on the delivery?

**Comment by yyd106** [comment]
> > Hi @yyd106 how is milestone 1 coming along?
> 
> Hi @keeganquigley , We will need another week, but we will deliver both milestones at once. This is because we found a close correlation between the two milestones, and the project team needs to use the DAuth SDK. So we decide to deliver a finalized version. Is that work?

Yes, we are work on the integration by Linea last few weeks. We provide attestation service for their Proof of Humanity and got 400K users authentication on our platform. Will finalize and submit the deliverables and docs this week.

**Comment by keeganquigley** [comment]
Thanks for the updates @yyd106 are you still planning to submit the delivery this week?

**Comment by yyd106** [comment]
Yes @keeganquigley

**Comment by yyd106** [comment]
Hi @keeganquigley , The deliverables PR is submitted: https://github.com/w3f/Grant-Milestone-Delivery/pull/1105

**Comment by keeganquigley** [comment]
Hi @yyd106 how is milestone 2 coming along?

**Comment by keeganquigley** [comment]
pinging @yyd106

**Comment by semuelle** [comment]
pinging @scott0927

**Comment by keeganquigley** [comment]
Hi @yyd106 please let us know if you are still working on this grant. Otherwise we will cancel it in a few weeks due to inactivity. Thank you.

**Comment by Metizen** [comment]
Hi @keeganquigley , I think dauth network has delivered all the milestones? Is there anything we have missing?

**Comment by keeganquigley** [comment]
Hi @Metizen @yyd106 ah I see that our records didn't properly update due to both milestones being delivered at the same time. Thanks, please disregard. My apologies for the false alarm. Will fix this on our end.

**Pull request merged**
