### PR TITLE
Updating timeline

### PR DESCRIPTION
**Pull request by mblinder**
#228

### CODE REVIEW

**Comment by semuelle** [comment]
Hi Mark, thanks for the update. Correct me if I'm wrong, but this should only update the timeline of your existing grant, right? 

If so, could you create a PR with the changes from a more recent fork? That way, the diff will immediately show the changes made to the file.

**Comment by mblinder** [comment]
Hi Sebastian,
I’ll take a look - apologies. I updated the team list, timeline and the FTE. But left the pricing and all the description. 
Are those the other changes you’re seeing?
Marc

**Comment by Noc2** [comment]
Currently the PR will add a completely new file and probably result in a merge conflict.

**Comment by mblinder** [comment]
Just did it again - was that right?

**Comment by semuelle** [comment]
Yes, thanks. Closing this one in favor of #587.

**Pull request closed without merging**
