### PR TITLE
submit application: polket_toearnfun

### PR DESCRIPTION
**Pull request by zhiquan911**
#### Project Abstract

**ToEarnFun** is a **fit to earn** Web3 smart fitness application. Compared with other **x-to-earn** applications that only have **SocialFi** and **GameFi** elements, it can be connected with real smart fitness equipment. It relies on the encryption technology of the hardware chip to ensure that the sweat is paid fairly. The entry-level users of **ToEarnFun** do not need to purchase cryptocurrencies, but only need to purchase smart fitness equipment adapted to the application, and they can **fit to earn** immediately, greatly reducing the difficulty for ordinary users to enter the web3 world.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by takahser** [comment]
@zhiquan911 thanks for the submission of your grant application! We currently have a rather large backlog to tackle, so it might take a bit longer than usual until we can give you feedback. Nevertheless, we're going to take a look at it as soon as we can.

**Comment by zhiquan911** [comment]
> @zhiquan911 thanks for the submission of your grant application! We currently have a rather large backlog to tackle, so it might take a bit longer than usual until we can give you feedback. Nevertheless, we're going to take a look at it as soon as we can.

all

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. This looks like a very interesting project. I have one initial question: Are you going to open source the entire project or do you plan to keep some parts closed sourced? Because currently, your organization contains very little code: https://github.com/polketio In general, it’s not mandatory for you to open source everything, but at least the open source parts released as part of this grant should be somehow useful for others. For example, will the entire flutter app be released under the GPL-3.0 license?

**Comment by zhiquan911** [comment]
> Thanks for the application. This looks like a very interesting project. I have one initial question: Are you going to open source the entire project or do you plan to keep some parts closed sourced? Because currently, your organization contains very little code: https://github.com/polketio In general, it’s not mandatory for you to open source everything, but at least the open source parts released as part of this grant should be somehow useful for others. For example, will the entire flutter app be released under the GPL-3.0 license?

Yes, when the milestones in the grant are completed, we will open source the entire project.
Our projects are open source based on GPL-3.0 license.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Could you maybe add this to the application and do you already have some additional code that you could make open source and share?

**Comment by zhiquan911** [comment]
> 
The application is updated!
I have open sourced the Substrate node project I am currently developing.
https://github.com/polketio/polket-node

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I’m happy to go ahead with it and will share it with the rest of the team.

**Review by takahser — APPROVED** [review]

**Review by gautamdhameja — APPROVED** [review]

**Comment by zhiquan911** [comment]
Thanks to the web3 foundation for the grants support. We are excited to make our own contribution to the polkadot ecosystem.

**Pull request merged**
