### PR TITLE
Add proposal: Perun App Channels

### PR DESCRIPTION
**Pull request by matthiasgeihs**
### Project Abstract

This proposal is a follow-up to the [Perun Payment Channels Pallet](https://github.com/w3f/Grants-Program/blob/master/applications/perun_channels.md) and its [integration with the Perun SDK](https://github.com/w3f/Grants-Program/blob/master/applications/perun_channels-integration.md). With these two completed grant projects, Perun payment channels are available to the Polkadot ecosystem.

We now propose to extend the feature set of Perun Channels on Polkadot by enabling so-called *app channels*. App channels allow to program arbitrary transaction logic into the channel and thereby enable scalable off-chain transactions for more complex use cases. This grant has been written in collaboration with the game developer studio [Ajuna Network](https://ajuna.io) who is interested in using app channels for realizing latency-sensitive game logic in their Polkadot-based gaming platform.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Review by Noc2 — APPROVED** [review]
Thanks a lot for the application. I think in general, given that we worked together already with everyone behind this application, we can already mark it as ready for review and I’m personally happy to support it in any case. In the meantime, I will ask Kuba to organise a pitch call.

**Review by gautamdhameja — APPROVED** [review]

**Review by laboon — APPROVED** [review]

**Review by takahser — APPROVED** [review]
@matthiasgeihs thanks again for the presentation, I'm happy to proceed with this. Looking forward to the 1st delivery. 👍

**Review by cruikshankss — APPROVED** [review]
I am very interested in seeing the results and different benefits of TEE/state channels in a gaming use-case. Thank you for the application!

**Comment by matthiasgeihs** [comment]
Thanks a lot for the quick response as always. Looking forward to start the work :)

**Pull request merged**
