### PR TITLE
PolkaAirdrops

### PR DESCRIPTION
**Pull request by jcsancho**
#### Project Abstract

PolkaAirdrops is an AI-powered airdrop automation platform tailored for crypto projects in the Polkadot ecosystem.
Our project is addressing two critical areas in the Polkadot ecosystem which are Marketing and BizDev through its innovative use of AI in marketing and community engagement. PolkaAirdrops represents a significant step forward in the intersection of AI and blockchain technology elevating Polkadot projects' visibility on a global scale.

PolkaAirdrops key features: 

- AI-Driven NFT Creation: PolkaAirdrops allows to design and minting of unique NFTs automatically using the power of generative AI. We are using Generative Pre-trained Transformers (GPTs) for advanced natural language processing to automate the process of creation and management of NFT airdrops.

- AI-Driven NFT Reward Distribution: We are using GPT technology to intelligently and automatically identify and reward positive social media engagements. We are utilizing EVM-compatible Moonbeam smart contracts to ensure seamless, secure, and cross-chain airdrop distributions.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [ x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [ x] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) address in the application).
- [x ] I am aware that, in order to receive a grant, I (and the entity I represent) have to successfully complete a KYC/KYB check.
- [ x] The software delivered for this grant will be released under an open-source license specified in the application.
- [ x] The initial PR contains only one commit (squash and force-push if needed).
- [x ] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [x] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@jcsancho:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by jcsancho** [comment]
Grants Terms and Conditions
===========================

Updated February 2023

* * * * *

By participating you acknowledge and accept the​ terms and conditions​ of the Web 3.0 Foundation for the grant application (the "Terms and Conditions").

* * * * *

These Terms and Conditions are entered into by and between the Web 3.0 Technologies Foundation, Baarerstrasse 14, 6300 Zug, Switzerland (CHE-332.596.347) (henceforth "Web 3.0" or "We") and you as an applicant for the technical grant for software development, research and/or the production of software documentation and technical education material as specified in Guidelines for technical grant of Web 3.0 Technologies Foundation (henceforth "User" or "You") (each also a "Party" and together the "Parties"). Please read these Terms and Conditions carefully. By signing off the terms and conditions via the CLA assistant, You confirm that You have read these Terms and Conditions and that You agree to be bound by them.

We reserve the right to change, modify, add or remove portions of these Terms and Conditions from time to time. If this occurs, We will notify You in adequate form on such updates.

## 1.  Introduction

We are the Web3 Foundation and nurture and steward technologies and applications in the fields of decentralized web software protocols, particularly those which utilize modern cryptographic methods to safeguard decentralization, to the benefit and for the stability of the Web3 ecosystem. We have developed a network protocol which purports to operate as an umbrella network for independent blockchain offerings and shared data or tokens across different blockchains. Parallelizable blockchains (so called "parachains") can be connected within Our network with a so called "relay chain" which provides security to the "parachains" and relays messages between them.

## 2.  Defined Terms

The terms defined in this section whenever used in these Terms and Conditions shall have the respective meanings indicated below, both in singular and plural:

"Affiliate" has the meaning with respect to any person, any other person directly or indirectly controlling, controlled by or under common control with such person;  

"Change of control" means any change in Your ownership or control or of a legal entity directly or indirectly owning or controlling You, whether by merger, consolidation, reorganization, take-over, change in the ownership of the share capital or otherwise;

"Development Work"  means any and all development activities related to the Software and undertaken by You. For the avoidance of doubt, any development activities undertaken before the Effective Date in relation to the Software are deemed to constitute Development Work and to form part of the deliverables to be provided by You and be subject to the terms of these Terms and Conditions;

"Effective Date"  means the date on which the application is accepted by the Grants Committee via the application review process defined below (the date of the merged commit of the application, which can be found under <https://github.com/w3f/Grants-Program/pulls>);

"Grant" means the financial support granted by Web 3.0. to You (i) for the development of the Software in accordance with the Specifications; and (ii) the grant of license rights on the Intellectual Property Rights, according to the terms of these Terms and Conditions. The Parties agree that Grants are unrelated to the actual development costs and the commercial value of the Software;

"Intellectual Property Rights" means any (i) patents, designs, copyright and related rights, database rights, trademarks, trade names (whether registered or unregistered), and the related rights to apply for registration thereof; (ii) applications, extensions and renewals in relation to any of these rights; (iii) know-how and confidential information; and (iv) all other rights of a similar nature and/or having an equivalent effect anywhere in the world;

"Milestones" mean any and all of the milestones specified in the final version of the application under Development Roadmap and  approved by the Grants Committee in accordance with the Procedure as well as placed in the applications folder of the W3F Grants Program Repository at <https://github.com/w3f/Grants-Program/tree/master/applications>;

"Polkadot" means a scalable heterogeneous multi-chain framework developed by, or the development of which has been procured by Web 3.0. that has the features described in the white paper ("Polkadot: Vision For A Heterogeneous Multi-Chain Framework -- Draft 1") or as otherwise determined by Web 3.0. in its sole discretion from time to time) and utilizes DOTs as the blockchain token native to its operation and/or functioning;

"Procedure" means the procedure in connection with the Web 3.0 Foundation Grants Program, as established in Section 4 below;

"Software" means the deliverables created by You during the development activities performed according to these Terms and Conditions in their final and working version, and that are to be provided to the Foundation in accordance with the Specifications, Milestones and Time Schedule;

"Specifications" mean the reasonably detailed technical and/or other requirements describing the features and functionality of the Software, as specified in the final version of the application approved by the Grants Committee in accordance with the Procedure and placed in the applications folder of the W3F Grants Program Repository at <https://github.com/w3f/Grants-Program/tree/master/applications>.

"Terms and Conditions" means this terms and conditions together with any documents referred to in it;

"Time Schedule" means the time schedule specified in the final version of the application approved by the Grants Committee in accordance with the Procedure and placed in the applications folder of the W3F Grants Program Repository at <https://github.com/w3f/Grants-Program/tree/master/applications>.

## 3.  Eligibility

If You are submitting an application for a Grant, You represent and warrant that:

- each of the following statements is true and accurate and all of the information You provided was and shall remain true and complete;
- If You are registering on behalf of a legal entity, such legal entity is duly organized and validly existing under the applicable laws of the jurisdiction of its organization and you are duly authorized by such legal entity to act on its behalf;
- You are of legal age to form a binding contract (at least 18 years old in most jurisdictions);
- You have the right, full power and authority to enter into these Terms and Conditions, to exercise your rights and perform your obligations under these Terms and Conditions and in doing so will not violate any other agreement to which You are a Party nor any laws;
- these Terms and Conditions constitutes a legal, valid and binding obligation on You which are enforceable against You in accordance with their terms;
- no consent, authorisation, licence or approval of or notice to any governmental authority nor your shareholders, partners, members, other record or beneficial owners or other any relevant person (as applicable) is required to authorise the execution, delivery, validity, enforceability or admissibility in evidence of the performance by You of your obligations under these Terms and Conditions;
- You are not a citizen of, or resident in or located in, or incorporated or otherwise :
    1. listed on any of the following lists (each a Sanctions List): the Consolidated United Nations Security Council Sanctions List; the Specially Designated Nationals and Blocked Persons List or the Sectoral Sanctions Identification List maintained by the US Office of Foreign Assets Control (OFAC); the Consolidated List of Persons, Groups and Entities subject to EU Financial Sanctions; the Consolidated List of Financial Sanctions Targets or List of persons subject to restrictive measures in view of Russia's actions destabilising the situation in Ukraine, maintained by the UK Treasury; the Overall List of Sanctioned Individuals, Entities and Organizations maintained by the Swiss State Secretariat for Economic Affairs (SECO); 'Ordinance lists of the Swiss Federal Council'; or any similar list maintained by, or public announcement of sanctions made by, any other Sanctions Authority (as defined below);
    2. owned or controlled by, or acting on behalf of or for the benefit of, any person on a Sanctions List;
    3. located in, resident in or incorporated under the laws of (as applicable) Syria, Iran, Cuba, Crimea or North Korea, or any other country or territory which, after the Effective Date, becomes the target of such comprehensive, country-wide or territory-wide Sanctions (as defined below) as currently apply to the aforementioned territories; or
    4. the target of any sanctions laws, regulations, embargoes or restrictive measures (Sanctions), as amended from time to time, administered, enacted or enforced by: the United Nations, the United States, the European Union or any Member State thereof, the United Kingdom, Switzerland or the respective Governmental Authorities and agencies of any of the foregoing responsible for administering, enacting or enforcing Sanctions, including without limitation, OFAC, the US Department of State, the United Kingdom Treasury or the SECO (Sanctions Authority).

- You will comply with any laws applicable to Your software (built based upon the Polkadot network) and not engage in any illegal activities. In particular, You will not use the Polkadot network to facilitate infringement of any third party intellectual property rights or data privacy rights.

You shall indemnify and hold harmless Web 3.0 from any third party claims (including reasonable attorney's costs) raised against Web 3.0 based on an alleged infringement of the above representations and warranties.

## 4.  Procedure

To apply for the Web 3.0 Foundation Grants Program, your application shall fulfill the following criteria:

- it shall be a research or software-based project, which contributes to the advancement of the Polkadot ecosystem;
- the Software shall be released under the Apache license version 2.0.;
- You must accept payment in USDT or USDC on Polkadot AssetHub or fiat;
- You will need to submit the application and deliver the milestones according to the process specified below;

The grants process consists of five parts, each of them described in more detail below:

**(i)  Grant application process:**

To apply for a grant of the Web 3.0  Foundation Grants Program, You shall comply with the procedures established in the README.md file under <https://github.com/w3f/Grants-Program> as well as the process defined inside this document.

To apply for a grant of the Web3 Foundation Grants Program, the grantee needs to fork (= create a copy on GitHub of) the Grants-Program GitHub repository. In the newly created fork (=copy on GitHub), the grantee has to create a copy of the application-template.md. The copied application-template.md needs to be renamed as "project_name.md". "Project_name" needs to be replaced with the name of the project application. Additionally, the grantee has to fill out all mandatory parts of the application-template.md presented in bold letters. Once the grantees have completed the application, they need to create a new pull request (= in this case, a mechanism to submit the changes of the fork to the original Grants-Program GitHub repository) by clicking on the "create new pull request" button shown inside the fork of the W3F Grants-Program GitHub repository. After this, the grantee needs to sign off the terms and conditions presented via the CLA assistant.

**(ii)  Application review process:**

The Web 3.0 grants committee, which is specified on the [Grants-Program GitHub repository](https://github.com/w3f/Grants-Program)(the "Grants Committee"), can issue comments and request changes on the grant application pull request (the submission of the grant application on GitHub).  As soon enough members of the Grants Committee approve the pull request, the terms and conditions are signed off and all requested changes are addressed, the application is officially accepted. The application is now a part of the [W3F Grants-Program GitHub repository](https://github.com/w3f/Grants-Program). The time point of the acceptance by the Grants Committee is hereby stored on GitHub and counts as the official beginning of the grant. The original submission is stored with a unique commit hash (identifier) and can not be altered by any party. The final version approved by the Grants Committee of the Specifications, the Time Schedule and Milestones will be placed  in the applications folder of the W3F Grants Program Repository at <https://github.com/w3f/Grants-Program/tree/master/applications> via the merge function of GitHub.

**(iii)  Milestone delivery process:**

To submit one of the possible multiple milestones specified in the application, You shall fork the [Grant Milestone Delivery GitHub repository](https://github.com/w3f/Grant-Milestone-Delivery) with the same Github account, used to submit the initial application. In the newly created fork, You shall create a copy of the [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md). Such [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) needs to be renamed as "project_name_milestone_number.md". "Project_name" needs to be replaced with the name of the project application and milestone number with the number of the delivered milestone. Additionally, You shall fill out all mandatory parts of the [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) as well as the invoice form linked inside the [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md). Once You have completed the milestone delivery document, You shall create a new pull request by clicking on the "create new pull request" button shown inside their fork of the [Grant Milestone Delivery GitHub repository](https://github.com/w3f/Grant-Milestone-Delivery).

**(iv)  Milestone review process:**

The Grants Evaluators, who are specified on the [Grants-Program GitHub repository](https://github.com/w3f/Grants-Program), can issue comments and request changes on the milestone delivery pull request.

a)  Purpose and object of the milestone review process

The purpose of the milestone review process is to examine whether the  Milestones and/or Software meets the requirements agreed in the Specifications. The milestone review process shall take place following the submission of each milestone as specified in the time schedule.

The test criteria that must be met in order for the Milestones and/or Software to be considered as acceptable by Web 3.0 are determined in the Specifications.

The milestone review process shall be deemed to have been successfully completed if no significant defects are found in any of the Milestones and/or Development Work. Insignificant defects shall not prevent acceptance by Web 3.0.

b)  Acceptance Procedure

If any of the Milestones and/or the Software does not meet the test, review or inspection criteria, Web 3.0 shall grant You a period of 14 days to rectify the defects and any deviations from the Specifications found and objected to during the milestone review process. Rectification shall be free of charge for Web 3.0.

If You are unable to remedy the defects within this additional period, You shall be considered to be in default, without any additional notice by Web 3.0.

In the event of default, Web 3.0 may either, at its discretion:

- insist on the rectification of the milestones and/or the Software;
- delegate the completion of the Software to a third party at your expenses;
- reduce payment of the Grant because of the reduced value of the Software; or
- refuse payment of the Grant in full (for the avoidance of doubt, this may require You to refund all milestone and advance payments made under these Terms and Conditions).

As soon as one evaluator approves the pull request, the delivery is officially accepted. The delivery is now a part of the [Grant Milestone Delivery GitHub repository](https://github.com/w3f/Grant-Milestone-Delivery). The time point of the acceptance by the evaluator is hereby stored on GitHub. The original submission is stored with a unique commit hash (identifier) and can not be altered by any party.

**(v)  Payment process:**

The Operations Team specified in the [Grants-Program GitHub repository](https://github.com/w3f/Grants-Program), gets notified once the above-specified delivery was accepted. As soon as any feedback is provided by the evaluators, this feedback first needs to be resolved. After this, the Operations Team makes the payment to the bank account or Polkadot AssetHub (for USDT and USDC) address specified in the initial application.

## 5.  Scope of these Terms and Conditions

The subject matter of these Terms and Conditions is (i) the development of the Software by You in accordance with the Specifications, Milestones and Time Schedule, as well as any related activities (including any development activities undertaken before the Effective Date in relation to the Software) (collectively referred to as "Development Work") in accordance with the terms of these Terms and Conditions.

In performing your obligations under these Terms and Conditions, You shall:

1. use reasonable skill and care;
2. comply with any date or time specified according to the Time Schedule;
3. perform your obligations in accordance with good industry practice, being practices in relation to the development of software and related deliverables the same as or similar to the Software that are usually followed by other suppliers in the same industry, including adherence to industry codes of practice and industry standards in relation to such products and services;
4. perform your obligations in accordance with all laws and codes of conducts applicable;
5. ensure that your development team consists of a sufficient number of appropriately skilled and experienced individuals
6. develop the Software as an open source software under the Apache license version 2.0.

Unless expressly agreed otherwise in writing by the Foundation, the Grantee shall not subcontract, even partially, the development of the project/deliverable to any third party.  If the project/deliverable, in whole or in part, is subcontracted to a third party without the consent of the Foundation, the Foundation is entitled to immediately terminate the Grant Agreement and to recover the grant amount already disbursed.

The Parties acknowledge and agree that the requirements set out in the Milestones may only be varied or amended by submitting another pull request and the following reevaluation by the committee under the same conditions as the initial application review process specified above.

## 6.  Obligations of User

1. You shall deliver the Software, as well as all related deliverables, including but not limited to the source code, to Web 3.0 free of defects, fully compliant with the Specifications and in accordance with the Time Schedule.

2. Web 3.0 shall be in the position to further developing, re-engineering and using the delivered Software without any technical or other limitations.

3. You shall bear all costs and expenses incurred in connection with the Development Work.

4. You shall remain positive towards the Foundation, the Foundation representatives and its goals, plans and projects. You shall advocate for the Foundation's projects' and sub-projects' aims during the term of the Agreement.

5. You shall, at all times during the term of the Agreement refrain from making, causing to be made, publishing, ratifying, endorsing, re-publishing or promulgating any and all disparaging remarks or derogatory, false, negative, critical, vilifying or otherwise detrimental statements or comments, whether implied or expressed, made in any format to any party or entity with respect to the Foundation, its officers, directors, employees, council members, advisors or otherwise affiliated individuals, entities and projects, including, but not limited to negative statements pertaining to:
    1. any management style, methods of doing business, quality of products and services, the business affairs, operation, financial condition and standing in the community; and
    2. any treatment of its officers, directors, employees, council members, advisors or otherwise affiliated individuals and any circumstances surrounding any such employment and/or separation of employment from the Foundation or advisory relationships.


6. You agree to forbear from making any public or non-confidential statement with respect to any claim or complaint against the Foundation without having obtained the Foundation’s prior written consent.

7. You agree that during the term of this agreement together with the Schedules (or any of each SOW), including extensions or modifications thereto, and for a period of nine (9) months thereafter, neither Grantee nor the Foundation will recruit, directly or indirectly hire, solicit or employ, engage as an independent contractor, any employee or independent contractor of either party, or any employee or independent contractor of any of the other subcontractors, who are involved in the development, use, or provision of the Services, without the prior written approval of the party whose employee or independent contractor is being considered for employment or engagement as an independent contractor, except as otherwise required by law. If one of the parties breaches this section, this party shall pay forty thousand dollars ($40,000.00) for each person hired as liquidated damages. The parties agree that quantifying losses arising from breach of this section is inherently difficult and stipulate that the agreed upon sum is not a penalty, but rather a reasonable measure of damages, based upon the parties’ experience in the software development industry and given the nature of the losses that may result from such breach.

## 7.  Terms of Grant Giving

Web 3.0. shall grant You, as compensation for the delivery of the Software and the related deliverables and the grant of license rights on the Intellectual Property Rights to the Web 3.0., a Grant as indicated in the application placed in the applications folder of the W3F Grants Program Repository at <https://github.com/w3f/Grants-Program/tree/master/applications>.

The Parties agree that the Grant is a lump-sum payment and that no additional compensation is due for the actual development costs incurred.

The Grant is paid as milestone payments for the accomplishment of the Milestones during several phases of the Development Work as indicated in the main readme file on Github (<https://github.com/w3f/Grants-Program>).

You shall not be entitled to an increase in compensation, even if you have had more work or greater expenses than anticipated. An increase in compensation is also excluded if extraordinary circumstances which could not have been foreseen prevent the completion of the Software or make it excessively difficult.

Except as specifically provided otherwise, the Grant shall be due and payable on or before thirty (30) calendar days after receiving an invoice from You and upon acceptance by the Web 3.0. of the Software and/or Milestones.

The Parties acknowledge and agree that the Web 3.0. shall be entitled to make Milestones payments. The Parties acknowledge and agree that any partial or advanced payments by the Web 3.0. or any third party shall be set off against the total amount of the Grant.

## 8.  Taxes and other duties

You are solely responsible for determining what, if any, taxes or other duties apply to Your Grant. It is also Your responsibility to withhold, collect, report, and remit the correct taxes to the appropriate tax authorities, according to the legislation in force. Web 3.0 is not responsible and shall be in no way held liable for withholding, collecting, reporting, and remitting and taxes arising from, or in connection to Your Grant.

## 9.  Warranties and Liabilities

You hereby warrant that:

(a)  You are the owner of all Intellectual Property Rights, title and interest in and to the Software and the related deliverables, free and clear of all liens and encumbrances;

(b)  You have the exclusive and unlimited right and authority to use and dispose of the Software and the related deliverables by granting to Web 3.0. license rights according to these Terms and Conditions and such use and right to dispose did not and will not conflict with, infringe upon or violate any copyright or any other proprietary right of any other person;

(c)  there are no licenses or rights current in effect in favor of any third party to use the Software and the related deliverables which would impair the rights granted to Web 3.0. as provided for under these Terms and Conditions; and

(d) You have disclosed all previous involvement of any team member in the Web 3.0 grant process, including, but not limited to: Closed, Rejected, Accepted, Delivered and Pending grant applications.

(e)  there is no pending or threatened claim, action, suit, investigation or proceeding of any kind challenging, alleging or asserting that the Software and the related deliverables were improperly or invalidly granted or are otherwise not protected as Intellectual Property Rights.

You further warrant that the Software and the related deliverables:

(a)  are free of defects in materials and workmanship;  

(b)  fully conform the Specifications and perform the functions and criteria as described in the Specifications; and

(c)  are sufficient and fit for the intended use as described in the Specifications.

Your liability for a single loss event shall be limited to the aggregate total of all sums paid by Web 3.0. to You under these Terms and Conditions. Nevertheless, You shall not be held liable for indirect, special, punitive, exemplary, incidental or consequential damages or losses arising out of these Terms and Conditions.

Furthermore, You shall hold Web 3.0. as well as its sublicensees harmless against any and all liability and damages for the infringement of Intellectual Property Rights of third parties, insofar as the infringement of such third party rights was caused by the intended use of the Software according to the Specifications. Web 3.0. shall immediately inform You in writing of any third party claims asserted and authorize You to conduct the defense, including the conclusion of a settlement, entirely at its own costs. In this respect, You shall use best efforts to provide Web 3.0. with the right to continue, or let continuing, using the Software or replace or modify the Software without deterioration or limitations of the functions and criteria agreed in the Specifications and without any additional costs. Should none of these measures be possible, Web 3.0. shall be entitled to withdraw from these Terms and Conditions and request the reimbursement of the Grant.

If You or Web 3.0. delegates the performance of an obligation or the exercise of a right under these Terms and Conditions to an associate, they are liable to the other Party for any loss or damage the associate causes intentionally or negligently in carrying out such tasks.

## 10.  Term and Termination

These Terms and Conditions (i) comes into force on the Effective Date (notwithstanding that these Terms and Conditions shall apply to Development Work carried out prior to the Effective Date); and (ii) shall remain in force (unless terminated earlier in accordance with its terms) until the acceptance of the Software by Web 3.0. and full payment of the Grant.

Termination with immediate effect will occur if the terms of the Terms and Conditions agreement is violated, as follows:

1. if a deadline according to the Time Schedule is not met;
2. if it results from Your behavior that such a deadline will not be met;
3. if You become bankrupt, insolvent, wound-up or dissolved or otherwise loses its legal personality as a validly standing entity;
4. if there is a Change in Control and Web 3.0. has not given his prior written consent to such Change in control; and/or
5. in the event You do not comply with Section 6.1, 6.4, 6.5, 6.6 and/or causes, in any way and at Web 3.0.'s discretion, any damage to Web 3.0. or Polkadot's image or reputation.

Furthermore, termination can happen for any reason at the discretion of the Web 3.0 Technologies Foundation.

## 11.  Notices

We may provide any notice to You under these terms and conditions by posting a notice on our Website, adding a comment to the initial pull request of your application on GitHub or sending an email to the email address associated with Your access account to the network. Notices We provide by posting on the Website will be effective upon posting. You will be deemed to have received any email sent to the email address then associated with Your account when We have sent the email (or the next regular working day thereafter), whether or not You actually receive or read the email. It is Your responsibility to keep Your email address current.

To give Us notice under these terms and conditions, You must contact us by email to [grants@web3.foundation]. We may update this email address for notices to us by posting a notice on Our Website. Notices to us will be effective one business day after they are sent.

All communications and notices to be made or given pursuant to these terms and conditions must be in English language.

## 12.  Miscellaneous

The Parties are independent contractors. These Terms and Conditions are an agreement at arms' length between the Parties and do not constitute a partnership, association or joint venture under any applicable law. Consequently, the provisions of these Terms and Conditions shall not, under any circumstances, be interpreted as creating any such relationship between the Parties. Neither Party may bind the other in any manner whatsoever or in favour of anyone whomsoever.

The failure of any of the Parties to avail itself or to enforce any of the provisions of these Terms and Conditions or any rights with respect thereto shall in no way be considered to be a waiver of such provisions or rights, or in any way to affect the validity of these Terms and Conditions. No waiver shall be effective unless expressly made in writing and signed by an authorized representative of the waiving Party.

If any provision of these Terms and Conditions is held to be void, invalid or inoperative, the remaining provisions of these Terms and Conditions shall not be affected and shall continue to be in effect, and the invalid provision shall be deemed modified to the least degree necessary to remedy such invalidity.

These Terms and Conditions or individual rights and obligations arising from it may only be assigned or transferred to third parties with the prior written consent of the other Party, save that Web 3.0 may freely assign any of its Intellectual Property Rights and any rights or obligations pursuant to these Terms and Conditions to any of its Affiliates.

These Terms and Conditions and any documents referred to in it shall constitute the entire agreement between the Parties in relation to the subject matter hereof, and shall supersede all previous agreements, arrangements and understandings between the Parties with respect hereto.

The headings used herein are inserted only as a matter of convenience and for reference only. They shall not affect the construction or interpretation of these Terms and Conditions.

## 13. Referral Program

If you were referred to the Web 3.0 Foundation Grants Program by a person who is either a Polkadot Ambassador or, in any case, a person considered by Web 3.0 as being active in the Polkadot Ecosystem (a “Valid Referee”), upon signature of this Terms and Conditions you could indicate to Web 3.0 the name of this Valid Referee, provided that he/she gave you his/her consent to share his/her identity with Web 3.0.  Web 3.0, as part of its grant referral program, will grant to the Valid Referee a referral bonus of the amount at that time allocated as bonus under such program.
For the avoidance of any doubt, Web 3.0 reserves the right to decide - at its complete discretion - if an individual is (and/or continues to be) a Valid Referee, and only in this case the referee will be entitled to receive the referral bonus.


## 14.  Applicable Law and Jurisdiction

These Terms and Conditions shall be governed by and construed in accordance with the substantive laws of Switzerland without any reference to its conflict of law provisions. The provisions of the United Nation Convention on contracts for the International Sale of Goods (CISG) shall not apply.

Any disputes arising out of or in connection with these terms and conditions and contracts entered into thereunder shall be submitted to the sole and exclusive jurisdiction of the courts of the city of Zug.

## 15.  Polkadot Network

If You are using Polkadot network for the purpose of the software development, research and/or the production of software documentation and technical education material You agree to be bound by specific term as follows:

You are free to use the software to gain access to and use the Polkadot network and to build your own network(s) and have your network interact with other networks which are also part of the Polkadot network.

HOWEVER, YOU SHALL AT ALL TIMES NOTE THAT NO PARTY (NEITHER WE OR YOU), INCLUDING BUT NOT LIMITED TO ANY PARTY INVOLVED IN, OR HAVING CONTRIBUTED TO THE DEVELOPMENT OF, THE POLKADOT  NETWORK AND ANY OF THE AFFILIATES, DIRECTORS, EMPLOYEES, CONTRACTORS, SERVICE PROVIDERS OR AGENTS OF SUCH PARTIES (THE "PARTIES INVOLVED") OWNS OR CONTROL THE POLKADOT NETWORK OR ANY ACCESSORY, UPGRADE, RELATED SOFTWARE OR ANY OTHER MODIFICATION TO IT (INCLUDING, BUT NOT LIMITED TO, POLKADOT NETWORK USER INTERFACE) AND YOU ARE SOLELY AND IN FULL RESPONSIBLE FOR YOUR USE OF EACH AND ANY OF THEM. THERE IS NO CENTRAL OVERSIGHT OVER THE POLKADOT NETWORK. IT IS BUILT BY THE PARTICIPANTS AND PARTICIPANTS OF THEIR NETWORKS THEMSELVES. FOR THE AVOIDANCE OF DOUBT, WEB 3.0 ASSUMES NO RESPONSIBILITY OR LIABILITY FOR (1) AVAILABILITY AND OPERABILITY OF THE POLKADOT  NETWORK AND ITS UNDERLYING SOFTWARE, (2) INTEROPERABILITY OF YOUR NETWORK WITH OTHER THIRD PARTY NETWORKS (THIS LARGELY DEPENDS ON EXTERNAL FACTORS BEYOND OF WEB 3.0'S REASONABLE CONTROL SUCH AS, IN PARTICULAR THE INFRASTRUCTURE AND OPERABILITY OF THIRD PARTY NETWORKS AND THEIR INTERNET-CONNECTIVITY MEASURES) OR (3) SUITABILITY OF THE POLKADOT NETWORK FOR YOUR OWN BUSINESS PURPOSES. YOU ARE USING THE POLKADOT NETWORK FOR YOUR OWN BUSINESS PURPOSES AT YOUR SOLE AND OWN RISK.

### Acknowledgement and assumption of risks

You shall at all times acknowledge and agree that certain risks exist in relation to using the Polkadot network. You fully acknowledge and agree that:

- No Party, including but not limited to the Parties involved, ​owns or controls the Polkadot network. It is built by the end users themselves.
- No Party, including but not limited to the Parties involved, has any authority to approve, prevent, restrict or anyhow exercise control over any interaction that occurs through the Polkadot network. You and end users are free to build their own network and network-based applications and provide them to customers under their own terms and conditions, provided that such applications should also run and be offered in a decentralized manner (as e.g. distributed ledger technology or often referred to as "blockchain" or any future adaptations of such technologies) without central oversight.
- You shall not have any expectations over the performance, suitability for business or interoperability of the Polkadot network for Your own business purposes.
- Polkadot network source code has not passed a third party security audit and can be potentially unstable and could cause unexpected effects and system failures. You are aware of this risk and must address it within Your own privacy compliance model when establishing technical and organizational measures on data security for Your end customers.
- By using the Polkadot network You covenant, represent, and warrant that Your use of the  network complies with Your jurisdiction of residence and You are fully able and legally competent to use the Polkadot network.
- In the event Your use of the Polkadot network does not comply with the applicable law of Your jurisdiction of residence, You shall be fully liable for any consequences incurred thereof and fully acknowledge and agree that ​We ​shall not be held liable for Your use of the Polkadot network
- There is a risk that advances in cryptography or technical advances (such as the development of quantum computers) could present risks to blockchain-based applications and cryptocurrencies, Ethereum or tokens which could result in the theft or loss of such elements.
- The  network (as well as any network You build based upon it) is susceptible to mining attacks (including but not limited to double-spend attacks, majority mining power attacks, "selfish-mining" attacks and race condition attacks. Despite the efforts of Web 3.0, the risk of known or novel mining attacks exists.
- There are risks associated with using the  network, such as e.g. failure of hardware, software and Internet connections. You acknowledge that Web 3.0 shall not be responsible for any communication failures, disruptions, errors, distortions or delays You may experience when using the  network.
- network source code is provided on an "AS IS" basis, without warranties and conditions of any kind, either express or implied, including, without limitation, any warranties or conditions of title, merchantability, fitness for a particular purpose, and non-infringement, unless otherwise required by mandatory applicable law.
- The entire risk as to the quality and performance of using the  network is borne by You.
- You are solely responsible for determining the appropriateness of using or redistributing the  network source code and/or any Derivative Work and assume any risks associated with Your exercise of permission granted under this License.
- You are solely responsible to regularly check for any modifications and updates to the  network source code published at <https://github.com/paritytech/polkadot/>

### Intellectual property

As regards the  network and its underlying technology, Web 3.0 is offering You the right to use it open-source based and Web 3.0 does not retain any proprietary intellectual property rights therein (see the GPL-License Version 3 available under <https://www.gnu.org/licenses/gpl-3.0.en.html>​).

However, Web 3.0 retains all rights, title and interest in any intellectual property rights relating to its business (such as e.g. trademarks or logos on its Website or copyrights/know-how in other business offerings not related to the  network).

### Privacy

To the extent that You will gain access to and collect and process personally identifiable data through the  network (or any own network built based upon it) and maybe even store it outside of these networks (i.e. "off-chain"). In this context, You represent and warrant to be compliant with the applicable data protection laws, in particular, to collect personal data lawfully, in good faith, and to retain and process such data proportionately only for the purposes of processing made evident at the time of collection and that such data will be secured with adequate technical and organizational measures against unauthorized use and to comply with third party data processing principles and not transfer such data into countries with a non-adequate data protection standard compared to Yours without adequate contractual safeguards.

### Limitation of liability

In no event and under no legal theory shall Web. 3.0 be liable to You for damages, including any direct, indirect, special, general, incidental or consequential damages of any character arising as a result of this License or out of the use or inability to use the  network (including, but not limited to, loss of data or data being rendered inaccurate or losses sustained by You or third parties or a failure of the network to operate with any other programs, loss of goodwill, work stoppage, business interruption, computer failure or malfunction or any and all other commercial damages or losses), even if a contributor has been advised of the possibility of such damages. Web 3.0 does not control, take responsibility for, or assume liability for the data in any way processed and stored by You or any third party using the  network and for any damage or loss incurred thereto. You shall solely be liable for the appropriateness, lawfulness, and accurateness of the data in any way processed by You using the network (and or if using such data outside of the network i.e. "off-chain".

### Indemnification

The Grantee shall indemnify, defend, and hold the Foundation and its officers, agents, employees, and affiliates harmless from and against all claims, causes of action, damages, fines, third-party claims, penalties, losses, expenses, costs (including reasonable attorney’s fees), and liabilities the Foundation incurs which relate to or arise out of any breach of this Agreement by Grantee or of any express or implied representation or warranty by Grantee, or any negligent or willful acts or omissions of Grantee or its Personnel.

**Comment by jcsancho** [comment]
recheck

**Comment by jcsancho** [comment]
I have read and hereby sign the Contributor License Agreement.

**Comment by jcsancho** [comment]
recheck

**Comment by jcsancho** [comment]
recheck

**Comment by jcsancho** [comment]
recheck

**Review by semuelle — CHANGES_REQUESTED** [review]
responded in channel

**Comment by semuelle** [comment]
Closing due to inactivity.

**Pull request closed without merging**
