### PR TITLE
Add setheum-launchpad-crowdsales-pallet

### PR DESCRIPTION
**Pull request by JBA-Khalifa**
Add setheum-launchpad-crowdsales-pallet 

### Project Abstract

> The Launchpad Crowdsales pallet provides crowdsales capabilities on a launchpad for teams/individuals to launch their tokens and run a public token sale campaign on substrate.
>
> How the protocol works:
> Screenshot from 2022-01-23 13-31-41

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the new application. For reference, I will add here a link to your [previous delivery](https://github.com/w3f/Grant-Milestone-Delivery/pull/101). One concerns with your previous deliveries was that you used Acala’s code, specifically the [currencies module](https://github.com/open-web3-stack/open-runtime-module-library/blob/master/currencies/src/lib.rs) without any [reference](https://github.com/Setheum-Labs/stp258-currencies/blob/master/src/lib.rs). To me it looks like you still haven’t added any reference to their implementation. This is something that we usually don’t take lightly. Could you comment on this?  Also it looks like your pallet is already [implemented](https://github.com/Setheum-Labs/launchpad-crowdsales). What are you planning on doing as part of the grant?

**Comment by JBA-Khalifa** [comment]
> Thanks for the new application. For reference, I will add here a link to your [previous delivery](https://github.com/w3f/Grant-Milestone-Delivery/pull/101). One concern with your previous deliveries was that you used Acala’s code, specifically the [currencies module](https://github.com/open-web3-stack/open-runtime-module-library/blob/master/currencies/src/lib.rs) without any [reference](https://github.com/Setheum-Labs/stp258-currencies/blob/master/src/lib.rs). To me it looks like you still haven’t added any reference to your implementation. This is something that we usually don’t take lightly. Could you comment on this? Also it looks like your pallet is already [implemented](https://github.com/Setheum-Labs/launchpad-crowdsales). What are you planning on doing as part of the new grant?

Thank you for the feedback. Regarding the reference to Acala's code on my previous deliverable, the code was deprecated, but not deleted. I can add the reference to the repo now if it is okay. Once again I apologise for that, it was an honest mistake.

**Comment by JBA-Khalifa** [comment]
Oh yes, the pallet was implemented for the grant. I thought it was possible to do that in contrast to my previous proposal where design was altered multiple times and it took too long. I didn't want to mess things up. I hope it can be accepted

**Comment by JBA-Khalifa** [comment]
How about adding the `LaunchPool` support and implementing the `launchpool_module` and extending the design like this: 
Screenshot from 2022-02-16 18-47-10
 
Some of the functionalities include:
```
fn make_bootstrap(); //  to bootstrap a successful campaign token on the Setheum DEX (integrating with the DEX);
fn add_liquidity(); // to add Launchpool Liquidity
fn remove_liquidity(); // to remove launchpool liquidity
fn add_vesting_schedule(); // to set DEX LP Tokens into vesting
fn claim_vested_lp_tokens(); // to claim vested DEX LP Tokens
```

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update and explanation. It will be up to the committee to consider this, once the application is ready for review. In the meantime, feel free to add the launch pool module. Alternatively you could also integrate a simple UI for your module as additional work as part of the grant. Could you also add benchmarks/benchmarking to your deliverables?

**Comment by JBA-Khalifa** [comment]
> Thanks for the update and explanation. It will be up to the committee to consider this, once the application is ready for review. In the meantime, feel free to add the launch pool module. Alternatively you could also integrate a simple UI for your module as additional work as part of the grant. Could you also add benchmarks/benchmarking to your deliverables?

Sure, thank you very mmuch. I will add the simple UI and benchmarking to the pallet

**Comment by JBA-Khalifa** [comment]
@Noc2 Could you please reffer me to some documents, tutorials, seminars and/or fundamental implementations of a bridge-parachain that connects to both polkadot and a standalone substrate chain?

**Comment by Noc2** [comment]
> @Noc2 Could you please reffer me to some documents, tutorials, seminars and/or fundamental implementations of a bridge-parachain that connects to both polkadot and a standalone substrate chain? Anything safe for production? I am looking into [bridges-common](https://github.com/paritytech/parity-bridges-common)

Hi. That’s the correct repo. I believe you can also find some videos on youtube, e.g. https://www.youtube.com/watch?v=1lutDZKbT2Q and you might also want to take a look at: https://github.com/paritytech/polkadot/tree/bridges-xcm-on-rococo-wococo and generally the work by https://github.com/svyatonik

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks just a few more questions from my side. Regarding the UI, will this be based on a substrate front-end template or are you planning to use something else for it? And do you still plan on adding the launch pool module? And finally would you be willing to reduce the price a little bit more?

**Comment by JBA-Khalifa** [comment]
> Thanks just a few more questions from my side. Regarding the UI, will this be based on a substrate front-end template or are you planning to use something else for it? And do you still plan on adding the launch pool module? And finally would you be willing to reduce the price a little bit more?

Thank you for the info @Noc2. No, the UI will be made from scratch using reactJS and a custom client API using Polkadot.JS and the custom JSON types (I could also add that to the deliverables).

And regarding the LaunchPool, I thought of adding it to a future milestone as I'm not satisfied with the design yet (especially where I mentioned 2 types of LP tokens, needs a different data structure - maybe using a `StorageDoubleMap` for the LPs, and more).  So, alternatively, I'll add the `UI` and the `client-api`, full-stack sounds very interesting to me.

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I’m happy to go ahead with it and give you another chance. I will also share the application with the rest of the team.

**Comment by JBA-Khalifa** [comment]
> Thanks for the update. I’m happy to go ahead with it and give you another chance. I will also share the application with the rest of the team.

I am most grateful, thank you David. I won't let you down!

**Review by takahser — CHANGES_REQUESTED** [review]
Hi @JBA-Khalifa 

Thanks for continuously being interested in the Web3 Foundation Grants program and submitting another application!
The idea of a Substrate-based crowdfunding platform sounds definitively exciting to me. 👍 

I have 2 questions:

- Are you aware that there already is a [Crowdfunding pallet](https://github.com/ImbueNetwork/imbue/blob/main/pallets/proposals/src/lib.rs), developed by a different team? I think their functionality covers a good part of what you're planning to implement (feel free to correct me if I'm mistaken). Is there any particular reason to implement a new pallet, duplicating said functionality?

- I saw you added a comment containing the [updated diagram](https://github.com/w3f/Grants-Program/pull/823#issuecomment-1041391162). For the sake of completeness, could you add it to the application as well?

**Comment by JBA-Khalifa** [comment]
Thank you @takahser for the questions. Pertaining the first question, No, I was not aware of the Crowdfunding pallet you mentioned, not until now. There are similarities I see in functionalities as they are all meant for crowdfunding as well as differences. My reason to implement a different pallet begins with "I didn't know about the one you reffered to", then I cannot use it in our protocol because based on what I see it is staged with milestones (more like the W3F Grants) and votes. The launchpad-crowdsales module lets me provide a straight-forward campaign with a single round. Otherwise, I don't sincerely see any highly differential reason concerning the implementation of this specific launchpad-crowddsales pallet.

For the second question, and thank you for asking, for the sake of completeness, I have not completed the design of the Launchpool as I am still pondering on how efficiently to fund a bootstrap and what datastructure best suits the shares/rights of the pool funders/holders. If I just automatically extract funds from the pool to bootstrap a launchpad, how do I determine the amount needed for that and who decides on the amount, and what will be the minimum or maximum, and how do we reconcile with the project's launchpool allocations and pricing for bootstrapping, all while avoiding interest-like LP incentives. For that I know it will be easy to solve if I look into some launchpad designs or DAO's. This is one of the reasons why I prefer to keep the Launchpool out of the question. Any implementation I'll do now will be impractical.

**Comment by JBA-Khalifa** [comment]
> @JBA-Khalifa thanks for your answers.
> 
> > I have not completed the design of the Launchpool
> 
> I see, so the design outlined in your [comment](https://github.com/w3f/Grants-Program/pull/823#issuecomment-1041391162) is not final, yet? Would you mind finalizing your concept and [updating the application](https://github.com/w3f/Grants-Program/blob/a32f60dcaf6eb9171ddcbdb8a32d10ba33c4f432/README.md?plain=1#L158) accordingly? Otherwise, it will be difficult for us to decide whether your delivery is complete, once you'll deliver. Just FYI, if at some point later during development you realize that the previously assumed concept could be improved or is not implementable you can always [amend](https://github.com/w3f/Grants-Program/blob/a32f60dcaf6eb9171ddcbdb8a32d10ba33c4f432/README.md?plain=1#L168) your application.

Okay, thank you @takahser

**Comment by JBA-Khalifa** [comment]
> See my previous comment. arrow_up

It seems to me that my first proposal is now complete, the deliverables are complete. If you check through our chats with @Noc2 you'll agree too @takahser

**Review by takahser — CHANGES_REQUESTED** [review]
@JBA-Khalifa as far as I can tell you still didn't update your application. Please do so accordingly, see my [comment](https://github.com/w3f/Grants-Program/pull/823#issuecomment-1055595347).

**Comment by semuelle** [comment]
@takahser, I believe what @JBA-Khalifa is saying is that the Launchpool design is not finalised and thus will not be part of this proposal. Since the launchpad pallet seems at least partially implemented, as [David pointed out](https://github.com/w3f/Grants-Program/pull/823#pullrequestreview-881342899), it now becomes a question of whether we retroactively fund its development. 

@JBA-Khalifa, my question would be whether the pallet will have, other than the ORML pallet mentioned in your application, any Setheum-specific dependencies. Also, is the work in the `launchpad-crowdsales` repo based on the `simple-crowdfund` pallet from the Substrate Developer Hub, or based on any other previous work?

**Review by semuelle — CHANGES_REQUESTED** [review]
@takahser, I believe what @JBA-Khalifa is saying is that the Launchpool design is not finalised and thus will not be part of this proposal. Since the launchpad pallet seems at least partially implemented, as [David pointed out](https://github.com/w3f/Grants-Program/pull/823#pullrequestreview-881342899), it now becomes a question of whether we retroactively fund its development. 

@JBA-Khalifa, my question would be whether the pallet will have, other than the ORML pallet mentioned in your application, any Setheum-specific dependencies. Also, is the work in the `launchpad-crowdsales` repo based on the `simple-crowdfund` pallet from the Substrate Developer Hub, or based on any other previous work?

**Comment by JBA-Khalifa** [comment]
> 

Thank you @semuelle, the `launchpad-crowdsales` repo has no Setheum-specific dependencies so far and is not based on the `simple-crowdsales` pallet and, it is just my code. Am Sorry for the late reply

**Review by semuelle — APPROVED** [review]
Thanks for the clarification. Happy to proceed.

**Comment by JBA-Khalifa** [comment]
Thank you all

**Pull request merged**
