### PR TITLE
Create Unite DAO.md

### PR DESCRIPTION
**Pull request by art0eth**
### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the interest in our grant program. But we require teams to use our application template, see https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md Specificly the milestone part is important, since it basically list the requirements of our contracts: https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#milestone-1-example--implement-substrate-modules Could you take a look at it and update the application accordingly?

**Comment by art0eth** [comment]
Hi, thank you, I just need to update the Milestone section right? Thank you.

**Comment by semuelle** [comment]
Hi @art0eth. The list of milestones and deliverables is perhaps the most important bit of an application. However, since anything that is outside this repository could at any point be removed or altered, we prefer anything that might be relevant for the verification and evaluation of your grant work to be part of this document. That doesn't mean you need to put your whole roadmap document into this one, but perhaps you could summarize the video with a few bullet points.

**Comment by art0eth** [comment]
Hi @semuelle and thank you, will fix this ASAP.

**Comment by semuelle** [comment]
Thanks for the update, @art0eth. Someone will review it in the coming days. 

I just checked briefly and noticed that the total (50k) and the individual milestone amounts (4 x 43k) don't match. These numbers should be what you are requesting for this grant, not what the actual cost is. Feel free to put the actual cost below the milestone or under Additional Information.

**Comment by art0eth** [comment]
Hi @semuelle, roger, will fix this ASAP. Thank you!

**Comment by art0eth** [comment]
Hi again @semuelle, I just updated the amounts. Thank you.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. However, deliverables 0a-0d of the application [template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) are mandatory for all milestones, and deliverable 0e at least for the last one. Also we usually don’t support research, deployment, developing ideas, token sales, legal research etc., especially when you plan to raise funds in different ways yourself. We mostly focus on concrete open source technical development in these cases. Basically the parts of the project that are potentially useful for others in our ecosystem and that could be leveraged by someone else for their own project.

**Pull request closed without merging**
