### PR TITLE
Add IPFS Utilities application

### PR DESCRIPTION
**Pull request by dobschal**
#### Project Abstract

This application is about the utilities of Substrate within IPFS.
The existing `offchain::ipfs` will be extended and adjusted to have a proper handling of IPFS CIDs and a redirect feature to retrieve files from IPFS.

This is a follow up to an already closed application PR: https://github.com/w3f/Grants-Program/pull/1127

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [X] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — APPROVED** [review]
Thanks for the updated grant application. I’m still willing to go ahead with it and will share it again with the rest of the committee.

**Review by gautamdhameja — APPROVED** [review]

**Comment by SBalaguer** [comment]
Hi @dobschal thanks for the updated proposal! It does look very interesting to me.

Would it be possible for you though to briefly explain how this proposal is improving current implementations like [`place_storage_order`](https://github.com/crustio/crust/blob/febe7477ca2f38f90af48dca0699b9942ccddf1b/cstrml/market/src/lib.rs#L459) from Crust?

**Comment by semuelle** [comment]
Hi @dobschal. Thank you for the application. Are you building this out of an in-house need? Since we now have multiple unmaintained forks of offchain_ipfs, it would be good to know that it won't be dropped again right away.

**Comment by semuelle** [comment]
ping @dobschal

**Comment by bbros-dev** [comment]
@Noc2 this also seems to be relevant prior art/grant:

- https://github.com/w3f/Grants-Program/pull/657

**Comment by bbros-dev** [comment]
lacked points to post this here: https://substrate.stackexchange.com/questions/5406/storing-data-offchain-to-ipfs-pallet-vs-chain-extension

# Subtrate runtime with native IPFS support

Objective:

> [including the Rust implementation IPFS in the native Substrate runtime](https://rs-ipfs.github.io/offchain-ipfs-manual/introduction.html)

Benefit: 

An example ...
> [pallet, which is essentially a Rust module that complies with the requirements to be included within a substrate runtime.](https://rs-ipfs.github.io/offchain-ipfs-manual/template-pallet.html)

## Status: 19 Oct 2022

- 8 Jul 2021: Web3 Foundation Grants Program awards [JuniDB grant](https://github.com/w3f/Grants-Program/pull/466#issuecomment-876207748)
- 1 Nov 2021: offchain_ipfs project can't handle the JuniDB contribution ([PR to rs-ipfs:offchain_ipfs from JuniDB team](https://github.com/rs-ipfs/substrate/pull/5#issuecomment-956168803))
- 3 Nov 2021: Web3 Foundation Grants Program awards [Iris grant](https://github.com/w3f/Grants-Program/pull/657#issuecomment-957547602)
- 1 Dec 2021: Open [APAC submission (Part One): Add IPFS into the substrate runtime and use frame v3 to build pallets which interact with it!](https://github.com/WunderbarNetwork/substrate/pull/8)
- 9 Dec 2021: Open [APAC submission (Part two) Example of creating a pallet which is using IPFS-core to talk to an IPFS ocw](https://github.com/WunderbarNetwork/substrate/pull/10)
- 6 Dec 2021: [offchain-ipfs manual](https://rs-ipfs.github.io/offchain-ipfs-manual) and the accompanying [rs-ipfs/substrate]() fork halts: "" 
  - offchain-ipfs manual [discussion](https://github.com/rs-ipfs/offchain-ipfs-manual/issues/22)
- 30 Apr 2021: Iris grant [completes](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/iris_3_cruikshankss.md)
- 27 July 2022: [WunderbarNetwork/substrate](https://github.com/WunderbarNetwork/substrate)
    - Polkadot APAC hackathon submission: [Implementation of IPFS in Substrate Runtime! (Frame V3)](https://github.com/WunderbarNetwork/substrate/tree/ipfs-ocw-v0.9.26#-implementation-of-ipfs-in-substrate-runtime-frame-v3-)
- 4 Oct 2022: [JuniDB Milestone 1 update](https://github.com/w3f/Grant-Milestone-Delivery/pull/254#issuecomment-1266778855)
- 19 Oct 2022: An open Web3 Foundation Grants Program application for [Add IPFS Utilities](https://github.com/w3f/Grants-Program/pull/1187)

Activity in last 30 days:

- [rs-ipfs/rust-ipfs](https://github.com/rs-ipfs/rust-ipfs)
- [JuniDB Milestone 1 update](https://github.com/w3f/Grant-Milestone-Delivery/pull/254#issuecomment-1266778855)

### Status Summary

- Upstream changes to Substrate are required (things have been tried).
- [Upstream is not resistant](https://github.com/rs-ipfs/offchain-ipfs-manual/issues/22#issuecomment-877354507)
- Upstream changes won't be easy/quick
- Web3 Foundation have made two grants related/using IPFS, but not focused on getting IPFS in the native Substrate runtime
- The Iris grant project completed
- The upstream review stalled due to lack of resources

### Status Conclusion

Until this resolves, hovever that is, you'll need to use a substrate fork closest to your use case:

- [uggugteam/substrate](https://github.com/uddugteam/substrate/tree/offchain_ipfs)
- [iridium-labs/substrate](https://github.com/iridium-labs/substrate/tree/offchain_ipfs_v3)
- [WunderbarNetwork/substrate](https://github.com/WunderbarNetwork/substrate/tree/ipfs-ocw-v0.9.26#-implementation-of-ipfs-in-substrate-runtime-frame-v3-)

**Comment by bbros-dev** [comment]
Hmmmm.... rs-ipfs is in a state of flux, possibly being [archived](https://github.com/rs-ipfs/rust-ipfs/pull/512), with [iroh](https://github.com/n0-computer/iroh) being a new candidate. Performance is [impressive (presentation)](https://www.youtube.com/watch?v=qPBR2K2X6cs&t=161s) but it is early days.

Substrate forking seems unavoidable for the foreseeable future, say 12+ months

**Comment by dobschal** [comment]
> Hi @dobschal. Thank you for the application. Are you building this out of an in-house need? Since we now have multiple unmaintained forks of offchain_ipfs, it would be good to know that it won't be dropped again right away.
Hey @semuelle 
We faced this problem in our [NiftyMarket](https://www.niftymarket.com) project. We created a workaround but with this grant we want to solve it also for others. Once this implementation is available we plan to integrate this in our [NiftyMarket](https://www.niftymarket.com) blockchain implementation. Updates on this pallet during our development would be then contributed back to the community.

**Review by takahser — CHANGES_REQUESTED** [review]
This looks interesting and could be useful to the community. However, I do think that the price is currently too high with 16.5k/month/FTE. In your [past grant](https://github.com/w3f/Grants-Program/pull/877/files#diff-e490796b2a04757fdcc035e55e01f78c6d7afadd2782b142d67664be9c048e62R122-R123) the rate was a bit more than 1/3 of that price: 5.5k/month/FTE. The other teams that worked on ipfs-related grants that you quoted also demanded much less for similar scopes.

**Review by semuelle — APPROVED** [review]
Thanks. Happy to proceed.

**Comment by alxs** [comment]
@bbros-dev thanks for the in-depth summary. Regarding the wiki, feel free to open an issue in its [repo](https://github.com/w3f/polkadot-wiki/issues).

@dobschal thank you for the updated application. I agree with @takahser regarding the rate, would be great if you could address this. But more importantly, as @bbros-dev pointed out, `rust-upfs` has now been [archived](https://github.com/rs-ipfs/rust-ipfs/pull/512), so it probably doesn't make a lot of sense to build a new integration with Substrate on top of it. Even with [`iroh`](https://github.com/n0-computer/iroh) being in its early days, I'd be more willing to support a project based on it. Such a project may be likely to break, but given the current state of things, relying on `rust-ipfs` would make it _certain_ to break. Curious to hear your thoughts.

**Review by alxs — CHANGES_REQUESTED** [review]
@bbros-dev thanks for the in-depth summary. Regarding the wiki, feel free to open an issue in its [repo](https://github.com/w3f/polkadot-wiki/issues).

@dobschal thank you for the updated application. I agree with @takahser regarding the rate, would be great if you could address this. But more importantly, as @bbros-dev pointed out, `rust-upfs` has now been [archived](https://github.com/rs-ipfs/rust-ipfs/pull/512), so it probably doesn't make a lot of sense to build a new integration with Substrate on top of it. Even with [`iroh`](https://github.com/n0-computer/iroh) being in its early days, I'd be more willing to support a project based on it. Such a project may be likely to break, but given the current state of things, relying on `rust-ipfs` would make it _certain_ to break. Curious to hear your thoughts.

**Review by takahser — CHANGES_REQUESTED** [review]
I still think it's too expensive, as [already indicated](https://github.com/w3f/Grants-Program/pull/1187#pullrequestreview-1153174326) and I haven't heard any feedback on that yet.

**Comment by dobschal** [comment]
Hey, thanks for the feedback. 

As there are too many unsolved doubts we are considering other options.

Thanks!

**Comment by dobschal** [comment]
We would like to reopen this grant. There was a misunderstanding on our side and we would be very happy to continue with this grant. If you have any questions, please feel free to ask.

**Comment by Noc2** [comment]
I shared your application again with the team.

**Review by keeganquigley — APPROVED** [review]

**Comment by dobschal** [comment]
Thanks for the approvals 🥳 Will check the next steps and are super happy to jump on that!

**Comment by dominikdem** [comment]
Hello W3F Team; we started the implementation phase.

**Comment by keeganquigley** [comment]
Thanks @dominikdem how is M1 coming along?

**Comment by dominikdem** [comment]
Hi @keeganquigley, thanks for reaching out. After some challenges, we have made good progress and are about to finish M1 by the end of next week.

**Comment by dobschal** [comment]
Hey 👋
we created the PR for the milestone 1 delivery. 
https://github.com/w3f/Grant-Milestone-Delivery/pull/743

**Comment by keeganquigley** [comment]
@dobschal awesome thanks for the submission! Someone will look at it shortly.

**Pull request merged**
