### PR TITLE
Milestone delivery amendment, remove CLI from deliverables

### PR DESCRIPTION
**Pull request by drewstone**
Amendment for delivery

### Project Abstract
Amending the extended mixer since all deliverables except CLI are ready. The CLI would take additional time and this has taken far longer than 1 month to complete. We would consider building out a CLI but don't want to waste time spent delivering this larger than expected deliverable.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Comment by drewstone** [comment]
@alxs we are amending the CLI component of this project. It would take us too much additional time that I don't want to include here and waste for delivering this large milestone. Getting all the other components has taken our team longer than expected and we'd need more resources to prioritize it.

**Comment by alxs** [comment]
@drewstone usually, we expect teams to reduce the cost of a milestone when a non-trivial deliverable is removed. Would you say that in this case, the other deliverables took more effort than expected and the price is still fair?

**Comment by drewstone** [comment]
Yes I would still consider it fair. The other deliverables took considerably more effort than expected.

**Comment by alxs** [comment]
@drewstone could you expand a little? I hadn't seen your edit, to be honest I think it would be better if you reduced the price a little especially since you mention that the deliverable isn't trivial, as otherwise this would set a tricky precedent.

**Comment by drewstone** [comment]
The deliverable that is removed is straightforward to implement. It is just a CLI. One main issue why it takes a long time is that subxt has never had stability. If we were to extend our CLI it has the potential to cascade into another month or two or work making sure things can work. 

We've built an SDK that makes it possible to build a CLI in typescript using our WASM bindings to the rust side. This would still take additional time.

To be honest, this deliverable took many months and many updates to a lot of rust software from the previous milestone. I don't think it's fair to reduce the cost as it cost us more in fact in raw resources ($). If you think otherwise I'll leave it to your discretion.

**Review by alxs — APPROVED** [review]
Fair enough, thanks for the added info. I'm happy to approve the amendment and will share it with the rest of the team.

**Review by Noc2 — APPROVED** [review]

**Review by mmagician — APPROVED** [review]

**Pull request merged**
