### PR TITLE
CosmWasmVM

### PR DESCRIPTION
**Pull request by Martin-Kiss**
#### Project Abstract

Composable Finance focuses on trustless, cross-chain communications between Polkadot and other ecosystems. We are developing the first CosmWasm VM implementation in Substrate for the Polkadot and Kusama ecosystems.

In this case, a CosmWasm VM is a supplementary component to onboarding a new developer community and a widely adopted smart contract framework.
Our target audience consists of parachain builders, and dApps in the Dotsama ecosystem that want to leverage a WASM based smart contracting framework.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [X] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [X] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [X] A BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (aUSD/USDT) address for the payment of the milestones is provided in the application.
- [X] The software delivered for this grant will be released under an open-source license specified in the application.
- [X] The initial PR contains only one commit (squash and force-push if needed).
- [X] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the application. In general, this looks really interesting. I would like to understand better what functionality will be supported after you submit your first milestone. Will I be able to deploy a cosmwasm smart contract on this (see https://docs.cosmwasm.com/docs/1.0/smart-contracts/contract-semantics) on your pallet?

**Comment by KaiserKarel** [comment]
> Thanks a lot for the application. In general, this looks really interesting. I would like to understand better what functionality will be supported after you submit your first milestone. Will I be able to deploy a cosmwasm smart contract on this (see https://docs.cosmwasm.com/docs/1.0/smart-contracts/contract-semantics) on your pallet?

First milestone is basically functional parity with Cosmwasm according to the official spec, and usable for developers and other parachains, however with poor DX from a contract authors perspective. (No React contract bindings and other goodies).

**Review by Noc2 — CHANGES_REQUESTED** [review]
@KaiserKarel Thanks for the super quick reply. Could you try to integrate this into the milestone 1 table, which basically shows the requirements of the contract, and we will use it to evaluate the delivery? It would be nice actually to deploy such a smart contract as part of milestone 1 for testing, or is there a potential test tool or something similar that we can use to evaluate the functional parity with Cosmwasm?

**Comment by KaiserKarel** [comment]
> @KaiserKarel Thanks for the super quick reply. Sounds very good. Could you try to integrate this into the milestone 1 table, which basically shows the requirements of the contract, and we will use it to evaluate the delivery? It would be nice actually to deploy such a smart contract as part of milestone 1 for testing, or is there a potential test tool or something similar that we can use to evaluate the functional parity with Cosmwasm?

Yeah I'll edit the milestone. The deliverable showcase will be:

A local network setup running a substrate chain with the pallet and a contract showing the functionality described in the milestones, so that it can be inspected and called through Polkadotjs.org.

**Comment by Noc2** [comment]
Great. Let me know once you have updated it.

**Comment by Martin-Kiss** [comment]
Applied the suggestion from @Noc2 as requested by @KaiserKarel

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I'm happy to go ahead with it and share it with the rest of the team.

**Review by gautamdhameja — APPROVED** [review]

**Review by randombishop — APPROVED** [review]
Looks good!

**Comment by semuelle** [comment]
Hi @Martin-Kiss & @KaiserKarel, would you mind sharing an update on the project?

**Comment by keeganquigley** [comment]
pinging @Martin-Kiss

**Comment by KaiserKarel** [comment]
@Martin-Kiss and I have left Composable, as have other principal engineers. I suggest contacting the current CEO. 

The original authors of the CosmwasmVM are no longer employed there, so I am unsure if the current status.

**Comment by semuelle** [comment]
Thanks for the info, @KaiserKarel.

Pinging @hussein-aitlahcen, @dzmitry-lahoda and @mina86 then. Do you know what the status of the project and the first milestone is?

**Comment by dzmitry-lahoda** [comment]
pinged Jafar from Composable. he works on proposals

**Comment by JafarAz** [comment]
Hello @semuelle @keeganquigley, just a quick update on our development progress. 

**For milestone 1:** 

- 0b, 0c, 1a and 1c (except anything leftover from 1b) are complete. We are currently working on completing the XCM integration and verification through Fuzzing & Kani and Benchmarking for 1b. Once those are complete, I will submit milestone 1. 

- You can find docs to interact with the pallet as mentioned in [0b here](https://docs.composable.finance/developer-guides/cosmwasm-cli). 

- The core functionality of the cosmwasm-vm can be seen on [this page](https://picasso-rococo.subscan.io/extrinsic?address=&module=cosmwasm&call=all&result=all&signedChecked=signed%20only&startDate=&endDate=&startBlock=&timeType=date&version=10029&endBlock=) which shows CosmWasm contracts successfully uploading, instantiating and executing on Picasso Rococo. 

- Furthermore, we already have existing Cosmos projects testing their contracts to deploy on our VM as [we announced](https://twitter.com/Picasso_Network/status/1662130360916881409?s=20) the release of CosmWasm on Picasso Rococo and have sparked a lot of interest in bringing CosmWasm-based projects to Kusama.

**For milestone 2:**

- Every single item required to submit milestone 2 is complete (0a-0d and 1 is partially complete) except for querying contracts’ state in the Development section.

**Comment by dzmitry-lahoda** [comment]
> XCM integration, .., allow calling extrinsics,

I have forked and made no_std support for more CW code (+2 repos with relevant prs and updates to 2 previous forks) to make CW contracts no_std enabled, to allow use of no_std wasm SP crates with CW crates in same contract, and updated CW+wasmi to latest version.  So it it just enables possible XCM/extrinsics integration, but not does it per ce. 

CW things to have no_std with 2.0 in September 2023.

**Comment by semuelle** [comment]
Thanks for the update, @JafarAz & @dzmitry-lahoda. Happy to hear things are progressing. Can you please review the timeline you have provided in the application and, if there is much further delay, please submit an amendment?

**Comment by keeganquigley** [comment]
@JafarAz @dzmitry-lahoda are you able to provide an update?

**Comment by dzmitry-lahoda** [comment]
There are 2 project are built on top of CW in Picasso, one is pure on chain defi protocol, other I am on is multichain swap.

We use this

https://github.com/ComposableFi/composable/blob/main/docs/docs/products/cosmwasm/deploy-and-run-cosmwasm-contracts-with-pdjs.md <- this is how it works with PD.js app.

https://github.com/ComposableFi/composable/tree/main/code/parachain/frame/cosmwasm/cli This is how it works via Cosmos like CLI.

We wrap pallets into precompiles which look like contracts (pallet id -> account = contract address). Example of usage 145 

We done https://github.com/ComposableFi/composable/blob/main/rfcs/0015-one-signature-multihop-transfer-solution-ibc-xcm.md IBC XCM multi chain transfers, and doing IBC XCM swaps (here will use XCM precompiles).

**Comment by keeganquigley** [comment]
Thanks @dzmitry-lahoda for the development update. Does this mean you plan to submit a delivery within the next couple weeks? If it's any longer than that I would agree with @semuelle that an amendment would be needed. Thanks!

**Comment by JafarAz** [comment]
@keeganquigley sure we can amend the duration on the proposal.

**Comment by keeganquigley** [comment]
@JafarAz thanks much appreciated! Yep, feel free to change the timeline on the original proposal and create a pull request. The PR will need 3 approvals, but this should happen rather quickly, and will take the pressure off.

**Comment by keeganquigley** [comment]
Hi @JafarAz do you still plan to submit an amendment?

**Comment by JafarAz** [comment]
Hi @keeganquigley apologies for the delay. Will get to it this week

**Comment by dzmitry-lahoda** [comment]
Here is overview of Milestone 1 delivery https://github.com/ComposableFi/composable/blob/main/docs/docs/internal/cosmwasm.md .

**Comment by semuelle** [comment]
Hey @dzmitry-lahoda, we are still waiting to hear back from @JafarAz on the contract amendment linked above. Can you look into it?

**Comment by keeganquigley** [comment]
Hi @Martin-Kiss for the sake of transparency, would you possibly be able to confirm [these comments](https://github.com/w3f/Grant-Milestone-Delivery/pull/999#issuecomment-1718061416) regarding change in personnel? Thanks.

**Comment by dzmitry-lahoda** [comment]
Martin is also not with us for last half year.

**Pull request merged**
