### PR TITLE
Qubit NFTs Tickets

### PR DESCRIPTION
**Pull request by linafx**
### Project Abstract

Qubit is a Multi-chain NFT ticketing marketplace build on Polkadot, which is a way to disrupt the traditional model. A game theory system applied to NFT ticketing maintains its equilibrium.

[Qubit NFTs Tickets.md](https://github.com/w3f/Grants-Program/files/7521467/Qubit.NFTs.Tickets.md)

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `Qubit NFTs Tickets.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [ ] The software delivered for this grant will be released under an open-source license specified in the application.
- [ ] The initial PR contains only one commit (squash and force-push if needed).
- [ ] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Comment by semuelle** [comment]
Hi Lina, thank you for your application. We will look into it as soon as possible. In the meantime, could you review the roadmap section? 

- Some of the deliverables don't have numbers and/or names. 
- Usually, we ask for a list of deliverables for each milestone, so if you could organise your deliverables under the milestones, that'd be helpful. 
- The total FTEs don't match the FTEs in the milestones
- The specifications of the deliverables are confusing and too short. For example, I don't understand what `Generate a Polkadot/Kusama. Migrate the current.` is supposed to mean. Ideally, it'd be something verifiable, like a list of implemented functions and a description of their functionality.

**Comment by alxs** [comment]
@linafx are you still interested in this? Note that we usually close applications after two weeks of inactivity.

**Comment by linafx** [comment]
Hi there!

I'm really sorry, I will be upload the update today.  We were a bit busy
this week, but we are still really interested in being a part of the
program.

Again, excuse me for the delay

**Comment by linafx** [comment]
Hi there!
Thanks for waiting, we've actually had a lot of work and some changes and
we want to strive to do things right and be part of the W3 Foundation. With
that said, I would like to know how to load the suggested update, as a
commit?

I will be attentive to your answer.

Lina

**Comment by semuelle** [comment]
Hi @linafx, if you commit to the branch you have opened the pull request from, the pull request should update automatically.

**Comment by linafx** [comment]
Will do, thanks!

**Comment by semuelle** [comment]
Hi @linafx, I cannot find any new commits on your repo. Are you still planning on the application?

**Comment by alxs** [comment]
Closing due to inactivity. Feel free to apply again if you're still interested.

**Pull request closed without merging**
