### PR TITLE
add sub nft marketplace

### PR DESCRIPTION
**Pull request by rust-0x0**
#### Project Abstract
Sub NFT marketplace is heavily inspired by Artion implementation [artion](https://github.com/Fantom-foundation/Artion-Contracts.git)
The NFT marketplace is a market where people can sell NFTs — [ERC 721](https://eips.ethereum.org/EIPS/eip-721) or [ERC 1155](https://eips.ethereum.org/EIPS/eip-1155) tokens — at a fixed price ( what we'll refer to as a "Direct listing"), or auction them (what we'll refer to as an "Auction listing").

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [x] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@rust.0x0:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by takahser** [comment]
@rust-0x0 thanks for your delivery! We currently have a rather large backlog to tackle with, so it might take a bit longer than usual until your delivery is evaluated. Nevertheless, we're going to take a look at it as soon as we can.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application and sorry for the late reply. I’m interested in supporting this application. The main concern I have is that your previous delivery had a lot of [issues](https://github.com/w3f/Grant-Milestone-Delivery/pull/500). So how do you plan to improve this? I will also ping @takahser again here since he previously evaluated your delivery.

**Comment by rust-0x0** [comment]
Thanks for your review.
first of all，sorry to take  your lots of review time previously.
Before submitting the milestone delivery,I will spend more time to test by myself, increase  more test cases, improve test coverage, reduce issues.Improving the quality of PR every time.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the quick response. However, we discovered that you reused most of the application text without proper attribution: https://cryptobriefing.com/top-five-nft-marketplace-alternatives-opensea/ This is something that we take very seriously and therefore will close your application. Nevertheless, thank you for your interest in our grants program, and let us know in case you disagree with the decision.

**Pull request closed without merging**
