### PR TITLE
Update citadel.md

### PR DESCRIPTION
**Pull request by citadeldao**
#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [ ] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] The initial PR contains only one commit (squash and force-push if needed).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for creating the amendment. However, your grant was already successfully delivered and accepted a while ago (even though not everything was open source as promised in the contract, which was a mistake on our side with the evaluation): https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/citadel-one_1_cruikshankss.md Why do you want to suddenly increase the total costs as well as update the application? Usually, once a grant is completed we no longer change it. If you want to work on additional projects, feel free to apply for a new grant. I’m therefore closing the PR for now. Let me know if you have any questions or disagree with this.

**Comment by Noc2** [comment]
I believe, in this case, it was a misunderstanding. I’m sorry for this. I think there is no need for you to update the application at this stage (open the PR again) since you successfully delivered the milestone. Let me know if you need anything else. Also, something to be aware of, Ashley who evaluated your milestone no longer works for us.

**Comment by citadeldao** [comment]
Okay, thanks for the clear explanation.  We are interested in the period for which you plan to allocate assets for the first milestone.  If it has already been, I would like to inform you that we have not received them yet.

**Comment by Noc2** [comment]
@citadeldao Sorry for the delay and thanks for chasing us. However, it looks like your invoice is denominated in BTC. Could you send us one in USD and we use the exchange rate on the day of the payment? (see https://github.com/w3f/Grants-Program/blob/master/applications/citadel.md, Total Costs: $22200)

**Comment by citadeldao** [comment]
Hi, thanks for the answer. This is our payment address:
USDC ERC20 
0x0834bBD1c425C4610e4b1Dc1145636c9E3B64dE0

Also, should we change it in our milestone or it's enough to write it here?

**Comment by citadeldao** [comment]
@Noc2 We've updated our payment address. Here is our new PR: https://github.com/w3f/Grants-Program/pull/1216
Thanks

**Pull request closed without merging**
