### PR TITLE
Ink Smart Contract Wizard

### PR DESCRIPTION
**Pull request by amankumar1008**
#### Project Abstract

> Ink Contracts Wizard is an UI based smart contract generation tool. It will scaffold Smart Contracts based on the options selected by the user. User can also download the contracts if required.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — APPROVED** [review]
Thanks for the application. I'm happy to mark it as ready for review and share it with the rest of the team.

**Comment by amankumar1008** [comment]
Thanks a lot for your review and marking it approved.

**Review by takahser — APPROVED** [review]

**Comment by avirajkhare00** [comment]
Hey @Noc2. I recently came across this: https://openbrush.io/.

They already have a smart contract generator, just as same as OpenZepplin Wizard.
Should I terminate this grant since a tool like this already exists?

**Comment by Noc2** [comment]
In general, we are interested in supporting multiple solutions. But if you prefer to work on something else instead, we can also terminate it. Whatever you prefer.

**Comment by avirajkhare00** [comment]
Hey @Noc2. I want to pivot a bit here instead of selecting options and generating smart contracts in the WebApp. I want to do the same in the CLI. I would raise PR for the same.

Here are the ideas I wish to work on: https://docs.google.com/document/d/10zN5rIYJObSDTwnirfUxIgAyxLxDpIPnkOgd59Y9oNs/edit?usp=sharing

How should I go about it? I am a bit confused here. If you can look at the doc, it would be great.

**Comment by Noc2** [comment]
Feel free to create a PR to amend this contract/file.

**Pull request merged**
