### PR TITLE
create InitialWorld.md

### PR DESCRIPTION
**Pull request by LeonardoTZ**
### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Comment by semuelle** [comment]
Thank you for your application, @LeonardoTZ. We will look into it as soon as possible.

In the meantime, could you share some public repositories or other proof showing your team's/team members' open source development and maintenance experience? Also, could you share the project's current [development status](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#development-status-open_book)?

**Comment by LeonardoTZ** [comment]
Thank you for replay, @semuelle. here are two members of our project and their github page, [RomiJones](https://github.com/RomiJones), [zhangwei](https://github.com/d5c5ceb0), you will see some open source dev experience. And this is the GitHub page of our project, [InitialWorldTeam](https://github.com/InitialWorldTeam).we just started our project and you can see some repos are being in development process.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. However, it seems to be pretty focused on RMRK. The web3 grants program needs to be as objective as possible when it comes to different parachain projects. Also we are no expert when it comes to RMRK and the technology. I therefore recommend closing the application and trying to reach out to the RMRK team and see if they potentially are willing to support this. Otherwise, I would recommend changing the application, and for example to focus on the [Uniques Module](https://github.com/paritytech/substrate/tree/master/frame/uniques).

**Comment by Noc2** [comment]
I’m closing the application for now due to inactivity. Let me know if I should reopen it.

**Comment by LeonardoTZ** [comment]
ok, we are trying to adjust the grant application we submitted.

David Hawig ***@***.***> 于2021年12月27日周一 18:07写道：

**Pull request closed without merging**
