### PR TITLE
zkwasm rollup amend timeline

### PR DESCRIPTION
**Pull request by ashWhiteHat**
As I commented, I would like to amend timeline.
https://github.com/w3f/Grants-Program/pull/1487#issuecomment-1572935659

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks @ashWhiteHat much appreciated. I see that you added a table with the new timelines, however could you incorporate these new durations into the milestones as well? Since the contract started on Feb. 17th 2023, technically the overall estimated duration would be closer to 11 months now. I will make the suggested changes below in order for you to easily change them. Thanks!

**Comment by ashWhiteHat** [comment]
Hi @keeganquigley 
Thank you for the comment!
That makes sense to me.
I changed our PR accordingly.

I would appreciate it if you could confirm.
Thank you!

**Review by keeganquigley — APPROVED** [review]
Thanks @ashWhiteHat looks good, I will ping the rest of the committee.

**Review by Noc2 — APPROVED** [review]

**Review by semuelle — APPROVED** [review]

**Review by takahser — APPROVED** [review]

**Review by SBalaguer — APPROVED** [review]

**Comment by ashWhiteHat** [comment]
Hi there
Regarding Milestone 1, it passed test now so we are going to describe tutorial and get thing done by this week.
https://github.com/KogarashiNetwork/Kogarashi/pull/91/files#diff-569c4866ec743e47bcc4258ec42720e55d00c382c8bc859b2916a4fe4f2ae030R10

**Comment by keeganquigley** [comment]
Hi @ashWhiteHat how is M3 coming along? Checking in since it was due around 6 months ago I believe.

**Comment by ashWhiteHat** [comment]
Hi @keeganquigley 
Thank you for the message.

For instance, this grant was amended and completed.

Following PR changed to the latest status.
https://github.com/w3f/Grants-Program/pull/2077

Summary of Above PR
zkwasm rollup was proposed as scaling solution by zero knowledge proof
however, introduction of core time and considering number of network validators, zero knowledge proof overhead costs more
so working on functionality by zero knowledge proof instead scaling solution

It was completed as follows.
https://github.com/w3f/Grant-Milestone-Delivery/pull/1092

Please ping me whenever you have questions.
Thank you!

**Comment by keeganquigley** [comment]
Thanks @ashWhiteHat much appreciated. I did see the amendment but hadn't noticed that M3 + M4 were removed completely. I will adjust our records, thanks!

**Pull request merged**
