### PR TITLE
Meta Defender Proposal

### PR DESCRIPTION
**Pull request by 327istesting**
### Project Abstract

Meta Defender is a leading provider of DeFi insurance, which provides a transparent, trustworthy, and convenient decentralized mechanism without intermediaries in insurance trading. Inspired by AMM pool, Meta Defender also has a pool in insurance trading. Also, the fee of insurance is driven by the market. Like most of the DeFi protocols, we run it a DAO system, which means, the whitelist of covered protocols(such as DeFi protocols or public chain security) is decided by all the token hodlers.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying?

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] I have read and understood the [FAQs](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md), [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md) and [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).
- [ ] I prefer the discussion of this application to be in a private Element/Matrix channel. My username is: ``@_______``

### How Did You Hear About our grants program?

- [ ] Social Media
- [x] Hackathon
- [ ] Personal Recommendation
- [ ] Substrate Builders Program
- [ ] Investor/VC
- [ ] Online Search
- [ ] Other: _______

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Looks really interesting. However, this application seems to focus mostly on Acala/Karura, I therefore suggest to apply here: https://acala.network/ecosystem-program Especially, since we usually don’t support solidity smart contracts and mostly focus on ink! and substrate. Let me know, in case you want to develop an ink! version or pallet instead.

**Comment by 327istesting** [comment]
> Thanks for the application. Looks really interesting. However, this application seems to focus mostly on Acala/Karura, I therefore suggest to apply here: https://acala.network/ecosystem-program Especially, since we usually don’t support solidity smart contracts and mostly focus on ink! and substrate. Let me know, in case you want to develop an ink! version or pallet instead.

@Noc2 Hi David, thanks for your prompt reply. After discussing with our team, we would like to change this proposal to mainly focus on the development of an ink! smart contract and to target the Polkadot ecosystem as a whole. I will update the application and let you know.

**Comment by 327istesting** [comment]
Hi @Noc2 , the revised version has been submitted. Thanks.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the update and sorry for the late response. I’m generally happy to go ahead with it, but could specify the deliverables of the milestone a little bit more detailed? For example, are you planning to implement “Buy Cover” and “Underwriting” as part of an ink! smart contract? Feel free to mention this as part of the specification. Also feel free to remove the part regarding the deployment on a parachain completely from the deliveries. The source code and a local testnet is fine for us and the deployment on a parachain might depend on other things that are out of your hands.

**Comment by 327istesting** [comment]
Hey @Noc2, sorry for the delay, I have updated the proposal accordingly, please let me know if any question.

**Review by Noc2 — APPROVED** [review]

**Comment by Noc2** [comment]
Thanks for the update. I’m happy to go ahead with it and will share it with the rest of the team.

**Review by gautamdhameja — APPROVED** [review]

**Comment by alxs** [comment]
Hey @327istesting, any updates on the first milestone? Unless you plan to deliver soon, could you please submit an [amendment](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval) with an updated timeline?

**Comment by keeganquigley** [comment]
Hi @327istesting any chance you can give us an update on the progress of M1?

**Comment by 327istesting** [comment]
Hey Keegan,

We managed to complete ink-contract and it looks good from contract-UI, however we stuck at ink-e2e testing. We encountered some issues and asked in stack exchange as well as directly to some devs in ink! developer team but unfortunately, we haven't received any reply. We still don't know whether it's because ink-e2e doesn't provide full support or we didn't deal with it in the right way. We are continuing working on it, otherwise I think we could provide a doc listing the steps of waterfall testing.

Also, we would like to move the second part of the first milestone (Manual of interaction between ink! and front-end) to second milestone because of the issue<https://github.com/polkadot-js/apps/issues/8500> which is related to Weights V2 support<https://github.com/polkadot-js/apps/issues/8364> in polkadot.js. It seems that it cannot be resolved in the near future, so we couldn't finish that part in the first milestone.

I will open a PR to reflect above issues after discussing with my team members. Cheers.
[https://opengraph.githubassets.com/9c21729a2225f509b2d05bdd89074dd6304c4a20d7179e92702ac81621b12bce/polkadot-js/apps/issues/8364]<https://github.com/polkadot-js/apps/issues/8364>
Contracts: Weights V2 support · Issue #8364 · polkadot-js/apps<https://github.com/polkadot-js/apps/issues/8364>
Deploying and calling contracts should support passing prrof_size for weights V2, currently it only supplies the legacy 1 dimensional execution_time part of the weight.
github.com

[https://opengraph.githubassets.com/8801b3b85194ced7c5ec59bbd1fedb95497c0302bc59dc278c06dbc623cb36b5/polkadot-js/apps/issues/8500]<https://github.com/polkadot-js/apps/issues/8500>
Deploy a contract with ink! 4.0.0-beta always return { Err: { Module: { index: 7 error: 0x02000000 } } } · Issue #8500 · polkadot-js/apps · GitHub<https://github.com/polkadot-js/apps/issues/8500>
The text was updated successfully, but these errors were encountered:
github.com


________________________________

**Comment by 327istesting** [comment]
Hey @keeganquigley,

We managed to complete ink-contract and it looks good from contract-UI, however we stuck at ink-e2e testing. We encountered some issues and asked in stack exchange as well as directly to some devs in ink! developer team but unfortunately, we haven't received any reply. We still don't know whether it's because ink-e2e doesn't provide full support or we didn't deal with it in the right way. We are continuing working on it, otherwise I think we could provide a doc listing the steps of waterfall testing.

Also, we would like to move the second part of the first milestone (Manual of interaction between ink! and front-end) to second milestone because of the [issue](https://github.com/polkadot-js/apps/issues/8500) which is related to [Weights V2 support](https://github.com/polkadot-js/apps/issues/8364) in polkadot.js. It seems that it cannot be resolved in the near future, so we couldn't finish that part in the first milestone.

I will open a PR to reflect above issues after discussing with my team members. Cheers.

**Comment by 327istesting** [comment]
Hi @keeganquigley , the ink4 framework itself is unstable right now and we encountered some problems which seems cannot be fixed soon. The team is also committed to other jobs and won't have time to work on it in the near future, so we would like to terminate this one.

**Comment by Noc2** [comment]
@327istesting Thanks for the update. I just created the PR to terminate the grant: https://github.com/w3f/Grants-Program/pull/1639. Feel free to reapply once you have the time to work on this.

**Pull request merged**
