### PR TITLE
Update subauction.md

### PR DESCRIPTION
**Pull request by green-jay**
The project needs to change the lead (and possibly add some additional members) in order to move things forward.

### CODE REVIEW

**Comment by green-jay** [comment]
Hello, can you please add other members @pmensik and @repetny as reviewers? Thank you

**Comment by alxs** [comment]
Hey @green-jay, I don't think we can do that, or at least I can't. It should be fine if they could just leave a quick comment here. Do you also want to update the team members given your comment?

**Comment by green-jay** [comment]
Ok, I will let the guys know. I don't have new people on board yet but I will do my best to get some more manpower so this doesn't take too long to complete :)

**Comment by pmensik** [comment]
Yeah, I am ok this :-)

**Comment by repetny** [comment]
All fine with this!

**Review by mmagician — APPROVED** [review]

**Review by alxs — APPROVED** [review]
Perfect :)

**Review by pmensik — APPROVED** [review]

**Review by semuelle — APPROVED** [review]

**Comment by alxs** [comment]
Update to #351

**Pull request merged**
