### PR TITLE
Proposal: Green Lemon🍋 Phase 2 

### PR DESCRIPTION
**Pull request by wuyahuang**
#### Project Abstract

[Proposal: Green Lemon Protocol🍋 - An anonymous NFT solution](https://github.com/w3f/Grants-Program/pull/1096)

Many of today’s blockchains, including Bitcoin and Ethereum, are open and public ledgers in the sense that there are no restrictions on participation and all transaction details are visible on the blockchain. In a public ledger, the transaction entities are only identified by their blockchain addresses, which are derived from the corresponding public keys. Public ledgers are generally considered to be “pseudo-anonymous”, which means that an address is linked to one person, but that person is unknown to the public. However, by analyzing the transaction graph and combining it with other information, it is possible to reveal the true real-world identity behind a blockchain address, as shown by recent research. 

The Green Lemon Protocol is an anonymous NFT platform based on zero-knowledge proof and dual-key stealth address protocol. Anyone can deploy their anonymous NFT smart contract and integrate it with our relayer service. Or use our template NFT contract as well.

Quick facts:

* Send anonymous transactions based on zero-knowledge proof
* Encrypt the asset owner based on the dual-key stealth address protocol

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by dsm-w3f — COMMENTED** [review]
@wuyahuang thank you for your application. Due to recent problems with mixers, I have some concerns about the usage of the project for money laundering and other illegal activities. In face of that, how this project could allow privacy in transactions and also prevent illegal activities to be performed on that? Any KYC or AML is planned or developed in the project?

**Comment by wuyahuang** [comment]
Hi, @dsm-w3f Thank you for the quick reply.

The anonymous transaction is `pseudo-anonymous` after any KYC or AML is implemented.

Our original vision is to create an anonymous NFT solution, but after some brainstorming, we think a layer 2 platform focused on the anonymous transaction will bring more possibility to the Polkadot community.

I think your point makes sense, We decided not to open the `anonymous` feature to any other third party until we find out a good solution to prevent money laundering and other illegal activities.

We are going to stick to our original path which is the `anonymous NFT` solution. The proposal is also updated. I have removed milestone 1 `anonymous ERC20`, and added another milestone `Mini Polkadot wallet (Google Chrome Extention)`. 
For now, both milestone 1 and milestone 2 are tools for the Polkadot developers.

Thanks. 🤝

**Comment by wuyahuang** [comment]
Hi, @Noc2 I accidentally removed @keeganquigley from the reviewer list. Could you add him back?😂 Sorry for that.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Closing, for now, see the email. I'm happy to reopen it in case anything changes.

**Pull request closed without merging**
