### PR TITLE
Iris Amendment

### PR DESCRIPTION
**Pull request by driemworks**
There was a lot of learning done as part of milestone two and as I was preparing the grant milestone submission document I realized that the work done deviated quite a bit from the original terms. I also stated in milestone two that we would setup a light client which requires a relay chain, but milestone 3 is where the relay chain setup tasks are specified.

The major difference is that rather than implementing a naive centralized encryption mechanism (which would have been unusable in a production scenario and would be thrown away eventually) I went ahead and used proxy reencryption instead. I also changed the scope of some of future milestones, as Tom won't be working with us on those.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

https://github.com/w3f/Grants-Program/pull/958

### CODE REVIEW

**Review by alxs — APPROVED** [review]
Thanks @driemworks. LGTM.

**Review by Noc2 — APPROVED** [review]

**Review by keeganquigley — APPROVED** [review]

**Review by dsm-w3f — APPROVED** [review]

**Review by SBalaguer — APPROVED** [review]

**Comment by driemworks** [comment]
Just sending an update: I took a little hiatus on this as I was attending the polkadot blockchain academy. As classes have concluded, I'll be returning to work on this.

**Comment by keeganquigley** [comment]
@driemworks thanks for the update, we appreciate it!

**Comment by keeganquigley** [comment]
Hi @driemworks how is milestone 3 coming along?

**Comment by keeganquigley** [comment]
@driemworks friendly ping.

**Comment by driemworks** [comment]
Hey @keeganquigley apologies for the slow reply. For several reasons, I think it's best if this grant is terminated. Can you help me with that process? Also, is there any type of post-mortem/retrospective that we can do/share with w3f?

**Comment by Noc2** [comment]
Thanks for the reply. I will open a PR to terminate it. Feel free to share more information with us via email: grants@web3.foundation

**Pull request merged**
