### PR TITLE
Lastic coretime price simulation

### PR DESCRIPTION
**Pull request by poppyseedDev**
#### Project Abstract

This grant is a continuation of development of the Lastic project (see [PR](https://github.com/w3f/Grants-Program/pull/2008)). We want to continue our journey with the **Coretime Sale Price Calculator**, building on our successful initial grant that focused on UI development for the Coretime Parachain. This tool is set provide the Polkadot community with a better understanding of how Coretime pricing will be implemented. 

Our tool aims to provide blockspace pricing analysis, offering real-time, interactive simulations of Coretime pricing. Aimed at enhancing understanding and identifying potential vulnerabilities in the `broker pallet`, our tool features a user-friendly interface with sliders and graph visualizations, showcased in our [working prototype](https://lastic.streamlit.app/).

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — APPROVED** [review]
Thanks for the application. Given that this is a very small additional grant, I'm happy to support it and mark it as ready for review. But I generally recommend looking for other funding sources besides the grants program.

**Review by takahser — APPROVED** [review]
@poppyseedDev this looks interesting to me, approving this!

Zooming out, I have one question regarding your future roadmap though: Are you still planning to implement a secondary marketplace for blockspace?
On another note, given the [positive community feedback](https://forum.polkadot.network/t/seeking-community-insight-on-coretime-price-simulation-model/4527) I also believe that this is a good time to start exploring alternative funding sources, such as treasury funding, our recently launched [decentralized futures program](https://futures.web3.foundation/) or other funding sources.

**Comment by poppyseedDev** [comment]
> @poppyseedDev this looks interesting to me, approving this!
> 
> Zooming out, I have one question regarding your future roadmap though: Are you still planning to implement a secondary marketplace for blockspace? On another note, given the [positive community feedback](https://forum.polkadot.network/t/seeking-community-insight-on-coretime-price-simulation-model/4527) I also believe that this is a good time to start exploring alternative funding sources, such as treasury funding, our recently launched [decentralized futures program](https://futures.web3.foundation/) or other funding sources.

Thank you for your approval and advice, we will be applying for those.

Of course we will be continuing with our are efforts 😄. Regarding the immediate future, however, we want to apply for a L2 grant to enhance our platform by indexing the coretime chain plus adding interactive and visual elements. What are your thoughts on that?

**Comment by takahser** [comment]
@poppyseedDev what do you mean here; Adding some visualisations and diagrams?

> enhance our platform by indexing the coretime chain plus adding interactive and visual elements. What are your thoughts on that?

**Comment by poppyseedDev** [comment]
> @poppyseedDev what do you mean here; Adding some visualisations and diagrams?
> 
> > enhance our platform by indexing the coretime chain plus adding interactive and visual elements. What are your thoughts on that?

Charts based on the data from the coretime chain.

**Pull request merged**
