### PR TITLE
RFP: Designing Upchain - a framework for securing Substrate runtime upgrades and Substrate network upgrades (#1309

### PR DESCRIPTION
**Pull request by taqtiqa-mark**
# Request for Proposals

## Abstract

The Upchain Specification, a framework for securing Substrate runtime upgrades and Substrate network upgrades, by extending The Update Framework and modeled on Uptane (The Update Framework Specification extended for automobiles)

## Background

* [How to recover a parachain](<https://forum.polkadot.network/t/how-to-recover-a-parachain/673>)
* [Polkadot Summit: Barcamp (30 Nov, 1 Dec) topic Parachain Emergency Recovery](https://forum.polkadot.network/t/polkadot-summit-barcamp-submit-agenda-topics-30-nov-1-dec/669/8)

## Checklist

- [x] I have checked the [open](https://github.com/w3f/General-Grants-Program/tree/master/rfps) and [implemented](https://github.com/w3f/General-Grants-Program/tree/master/rfps/implemented) RFPs to make sure this is not a duplicate.
- [x] I have read and followed the [RFP Suggestion instructions](https://github.com/w3f/General-Grants-Program#mailbox_with_mail-request-for-proposals-rfp-suggestions).

### CODE REVIEW

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/robust-chain-upgrades-impossible-or-uptane-for-substrate-parachains/1267/4

**Review by Noc2 — COMMENTED** [review]
Thanks for creating the PR. Let me share it with others also to get additional feedback. But in general, I think it’s a good idea to work on such a framework or even just guidelines.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Sorry, for the delay here. My colleague is currently ooo, but he already shared some feedback with me regarding it. That I would like to share with you as well:

> “ I had a look at it. A well-motivated proposal that tries to address a genuine problem for parachain teams. But I have a few ideas on how to improve it. I feel the RFP should be clearer on how the Upchain spec/standardization serves its utility in solving the issue of discrepancies in runtime code of parachain and relay chain during updates. 
> Main points:

- > clarify the stage at which this spec should be used and who is the target audience, upfront.
- > Is the scope of UpChain limited to creating a spec which aims at mitigating/ avoiding such discrepancies, or does it also include guidelines to triage and recover after the issue occurred.
- > I assume its scope includes providing recommendations and changes at the protocol level. If yes, does it also include analysis of performance overheads (e.g., overheads on the blockspace) caused. This may entail involving teams at parity/w3f.
- > what would be the approach to evaluate the deliverables. It is an extremely subjective task but nevertheless some qualitative metrics would be nice.
- > Not sure why Uptane (ECU update framework for automotives) is chosen as the template to begin with and contrast upchain. The settings are very different: ECU updates fall clearly within client-server model where centrally managed updates are pushed to clients.
- > check if there are synergies with Zombienet, which plans to have runtime update testing.”

But to also point this out here. We are already extremely happy that you created the RFP, and you don't need to answer all of these questions. We will continue to work on it in any case.

**Comment by taqtiqa-mark** [comment]
Will address the feedback shortly.

**Comment by taqtiqa-mark** [comment]
Hi @Noc2 I've addressed the feedback as best I can.

**Review by Noc2 — DISMISSED** [review]
Thanks for the update. I'm happy to already approve it. We might have additional questions in the future or further improve it.

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/how-to-recover-a-parachain/673/26

**Comment by bkchr** [comment]
I skimmed/read the document. First, I'm not familiar with the process here, so sorry if I'm saying something wrong. However, I don't get what you are trying to propose here? There is this framework and you want to integrate it into Substrate, but how? This document doesn't contain any explanation about at least some abstract explanation on what this framework should do and how it would work for blockchains. 

I think this should be the minimum requirement before accepting this? IDK.

**Comment by taqtiqa-mark** [comment]
> I don't get what you are trying to propose here?

Apologies for the confusion. I have reworked the content to be clearer.

> There is this framework and you want to integrate it into Substrate, but how?
 
I've clarified this way:

> This RFP seeks W3F Grant applications addressing/proposing how TUF can be integrated into Substrate.

Regarding:

> This document doesn't contain any explanation about at least some abstract explanation on what this framework should do

The TUF specification itself contains this information.
Finally:

> ... how it would work for blockchains

This RFP calls for W3F grant applications that address exactly that question:

> ... by extending The Update Framework and modeled on Uptane (The Update Framework Specification extended for automobiles)

Do these address your objections?

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/the-evolution-of-polkadots-political-economy/1480/2

**Comment by bkchr** [comment]
@taqtiqa-mark I still don't see any clarifications. You are still talking about some upgrade framework that is build for client/server infrastructure and should prevent clients ending in some unrecoverable state. While I don't say that this isn't working or similar, I don't see any connection to what we have here. We don't have any client/server infrastructure. We don't have any central authority that pushes an upgrade or can revert an upgrade. In case of Substrate all nodes upgrade at the same time by importing the block that enacts the new runtime upgrade. The problem is that you can not just revert this process, because if anyone could just revert the upgrade you would have huge problems. Everyone could easily revert any runtime upgrade and preventing any kind of progress in your chain logic. You would need some way to proof to the runtime that an upgrade was broken to revert it. I had written up a way for standalone chains here:https://github.com/paritytech/substrate/issues/7558

However, this would also not help you if a bug appears X hours after the upgrade.

For parachains it gets more complicated, because the relay chain is only interested in valid state transitions and it needs to ensure these. If your valid state transition is to apply a faulty runtime upgrade, the relay chain doesn't care. Now you could build in some kind of protocol to revert a runtime upgrade (which would again only work directly after it happened and not x hours later). However the most importing part would be to have a way to proof that the runtime upgrade was faulty. How would you do this? You can not trust collators, because they are only there for liveness and not security. Security is provided by the relay chain. I could continue on this for quite some time, but we all discussed this already in Lisbon and in the linked forum thread. We can add some recovery process into the validation wasm blob (which I also already mentioned in the thread and in Lisbon). However the main problem would still be on how to authorize this recovery process. We would then move this process off to the parachain itself, but I would assume that most of them would disable it as this is otherwise some big security risk. (in general this entire, who should approve this recovery process, is mainly some philosophical problem.)

I think we need to improve testing, so that these kind of issues are not happening and when they are happening it only happens very very rarely. 

If you have solutions to these problems, I'm happy to listen to them. We have this entire thread in the forum that would be happy about any kind of proposal on how to improve the process.

**Comment by taqtiqa-mark** [comment]
I think we have different scopes in mind. It seems to me that you desire a general solution ("this would also not help you if a bug appears X hours after the upgrade"). I'd settle for a narrower scope. How narrow? As narrow as required to have a revertible upgrade. I agree that protocol changes are likely required - just what those changes are will depend on the approach taken.  Yes you will need an origin/source for an upgrade - not concerned if you call it a server or something else, e.g. introduce a category of transaction with the required attributes, etc.

Solving the problem for a narrow/well-defined/constrained use case should shed light on other more general cases.

**Review by keeganquigley — DISMISSED** [review]
Hi @taqtiqa-mark thanks a bunch for creating this RFP. Seeing as all the comments have been addressed, I'm happy to go ahead and approve this as well since we need more RFPs! I'll also ping @bhargavbh one more time to see if he has any additional input.

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/design-a-friendly-easy-updatable-iterable-system/1674/6

**Review by Noc2 — DISMISSED** [review]
Sorry for the delay here. I am still okay with merging it and seeing what kind of application we get (if any).

**Review by semuelle — CHANGES_REQUESTED** [review]
Hey @taqtiqa-mark. Thanks for writing this up. I'm happy to approve it. However, it seems when you addressed Bhargav's feedback, you did so [on a different branch](https://github.com/taqtiqa-mark/Grants-Program/commits/designing-upchain) than the one you submitted this PR from. If you could merge that branch into your master branch, the changes should show up here.

**Comment by semuelle** [comment]
pinging @taqtiqa-mark.

**Comment by taqtiqa-mark** [comment]
Apologies, RL interrupted. I'll get to it this week.

**Comment by taqtiqa-mark** [comment]
> However, it seems when you addressed Bhargav's feedback, you did so [on a different branch](https://github.com/taqtiqa-mark/Grants-Program/commits/designing-upchain) than the one you submitted this PR from.

Apologies for the oversight. This is now corrected.

**Review by Noc2 — APPROVED** [review]

**Review by keeganquigley — APPROVED** [review]

**Review by semuelle — APPROVED** [review]

**Pull request merged**
