### PR TITLE
Hex 

### PR DESCRIPTION
**Pull request by rust-0x0**
### Project Abstract

Hex is  heavily inspired by Five Degrees protocol implementation [5degrees](https://github.com/5DegreesProtocol/5degrees-protocol.git)
Five Degrees propose a simple entity data ownership protocol and use the protocol to capitalize these core data. To make the protocol simple enough, permission-less, and composable, we choose to build the protocol under the existing ERC-1155 standard. Compatible with the ERC-1155 standard, meaning it will be easily implanted into any protocol or business of Web3 that supports ERC-1155. The NFT generated in the protocol can be traded in any NFT market, also any smart contract that requires user relationships can track this data on chain. Any application that supports ERC-1155, can easily integrate this protocol.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying?

- [x ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [ x] I have read and understood the [FAQs](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md), [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md) and [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md).
- [x ] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [ x] I have read and acknowledge the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [ x] The software delivered for this grant will be released under an open-source license specified in the application.
- [ x] The initial PR contains only one commit (squash and force-push if needed).
- [ x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).
- [x ] I prefer the discussion of this application to be in a private Element/Matrix channel. My username is: ``@rust.0x0:matrix.org``

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] Hackathon
- [x] Personal Recommendation
- [ ] Substrate Builders Program
- [ ] Investor/VC
- [ ] Online Search
- [ ] Other: _______

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. I have only one question: What kind of front-end are you planning to develop (react, vue, based on the substrate template, etc.) and do you already have some initial designs? Usually we ask teams to provide some mockups/designs, but I believe for 5k it’s not necessary.

**Comment by rust-0x0** [comment]
> Thanks for the comment. The front-end   based  on substrate-front-end-template.
Add front-end screenshot picture.Reduce costs.

**Review by Noc2 — APPROVED** [review]
Thanks for the quick response. I’m generally willing to go ahead with it, but you are now also changing the applications/RainbowDAO Protocol ink!  Phase 1.md as part of your PR. Could you update this, so that you only add your application?

**Review by Noc2 — CHANGES_REQUESTED** [review]
(sorry, I requested changes, see above)

**Pull request closed without merging**
