### PR TITLE
IDE issue resolution grant application

### PR DESCRIPTION
**Pull request by lawmeskiviahs**
#### Project Abstract
This is a response to the open RFP: https://github.com/w3f/Grants-Program/blob/master/docs/RFPs/Open/IDE_for_ink_Smart_Contracts.md
This application is to resolve issues and add additional features to the ink! playground developed by paritytech.
And also a follow up to: https://github.com/w3f/Grants-Program/pull/1712

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [ ] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by semuelle** [comment]
Thanks for the update, @lawmeskiviahs. We will look into it as soon as possible.

Could you update the PR with the contents of our [pull request template](https://github.com/w3f/Grants-Program/blob/master/.github/pull_request_template.md)? That will make things a bit easier on our end.

**Comment by lawmeskiviahs** [comment]
Thankyou for the reply, @semuelle The update has been done. Kindly look into it.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the updated application, and I will mark it as ready for review. However, as you have clearly seen, we got another application from another team in the meantime: https://github.com/w3f/Grants-Program/pull/1731 Given that your application copies a lot of the other application, I personally would prefer the "original" application, but others might have a different opinion so I will share it with the rest of the team.

**Comment by lawmeskiviahs** [comment]
Thanks for the review @Noc2. We had put in a proposal earlier #1712. The current application is just an update of the previous one with the requested changes. Kindly take this into account.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update here and all the effort you put into this. However, the grants committee decided to go ahead with the other application: https://github.com/w3f/Grants-Program/pull/1731. I'm therefore closing this one. However, I strongly encourage you to apply for another project. For example, we are generally interested in supporting the development of all kinds of ink! related tools. Let me know if you have any questions.

**Pull request closed without merging**
