### PR TITLE
Polkadart proposal

### PR DESCRIPTION
**Pull request by Lohann**
### Project Abstract

> Polkadart is a Dart library that provides a clean wrapper around all the methods exposed by a Polkadot/Substrate network client and defines all the types exposed by a node. It's an equivalent to [polkadot-api](https://github.com/polkadot-js/api) written in Dart language.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying?

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [X] I have read and understood the [FAQs](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md), [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md) and [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md).
- [X] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [X] I have read and acknowledge the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [X] The software delivered for this grant will be released under an open-source license specified in the application.
- [X] The initial PR contains only one commit (squash and force-push if needed).
- [X] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).
- [X] I prefer the discussion of this application to be in a private Element/Matrix channel. My username is: ``@lohann:matrix.org``

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] Hackathon
- [X] Personal Recommendation
- [ ] Substrate Builders Program
- [ ] Investor/VC
- [ ] Online Search
- [ ] Other: _______

### CODE REVIEW

**Comment by semuelle** [comment]
Discussion [here](https://matrix.to/#/!qjwxboLtPfrOWGrgfN:web3.foundation?via=web3.foundation).

**Review by Noc2 — CHANGES_REQUESTED** [review]
Just a reminder here to sign the CLA Bot, which means our terms and conditions. For everything else I will join the private channel.

**Review by cruikshankss — APPROVED** [review]
I'm extremely excited about this. I think it has the potential to bring lots of high quality front-end devs to the substrate ecosystem, and I see you have a huge incentive to maintain the api given your Rankanizer project. I'm a huge fan of Flutter although I haven't used it personally. From what I know, it seems to be the leading cross-platform app framework (preferred over React Native (I don't think Facebook even uses React Native much, if at all, despite developing it)). Also Flutter seems to be a great framework to aid with building components and layout that meet many of the ideals of a Progressive Web App (PWA), which is admittedly very difficult to achieve, especially for single-person and small front-end developer teams. I will share this with the grants committee!

**Comment by cruikshankss** [comment]
Please note: the discussion was formerly private (so see Element for chat history) but I've just removed the `private discussion` label per request of the team to bring the discussion to the public forum. Cheers!

**Comment by alxs** [comment]
Hey @leonardocustodio @Lohann, are you aware of https://github.com/Pocket4D/Polkadot-Dart? It seems to be unmaintained, but you may be able to reuse a lot of code from there.

**Review by gautamdhameja — APPROVED** [review]

**Comment by cruikshankss** [comment]
> Hey @leonardocustodio @Lohann, are you aware of https://github.com/Pocket4D/Polkadot-Dart? It seems to be unmaintained, but you may be able to reuse a lot of code from there.

Hey @alxs, thanks for mentioning. The Polkadart team already mentioned in their application (Ecosystem Fit section) essentially what you've said that it's unmaintained but they're aware of it. :)

**Comment by leonardocustodio** [comment]
Hello @alxs ,
We are not planning to use any of their code. Even if we did I don't think that would be a simple and cheap task. There are multiple reasons for that, here is their repo: https://github.com/Pocket4D/Polkadot-Dart 

1. They only finished milestone 1, most of the work is on milestone 2 not 1.
2. The project was made using flutter 1.x, we are currently on version 3.x. On flutter 1.x not even null safety was supported.
3. At the time that made the project we had metadata v12 that needs typegen/interface files. Today substrate uses metadata v14 with auto-generated types by parsing the metadata itself and not the type/interface files. And that is a good amount of work.
5. They use dynamic generated libs, we will try to avoid this because that requires rust and compiling for each platform and generates way extra work for developers that do not have much experience.

**Review by alxs — APPROVED** [review]
Thanks for the details. Makes sense and in that case, I'm happy to support your application.

**Review by Noc2 — APPROVED** [review]
I'm happy to support it as well.

**Review by takahser — APPROVED** [review]
This would be very useful to the ever-growing Flutter community. I'm happy to approve as well. 👍

**Comment by keeganquigley** [comment]
Hi @leonardocustodio @Lohann how is milestone 2 coming along?

**Comment by leonardocustodio** [comment]
Hey @keeganquigley, it is almost over. I know we are a little bit behind the schedule for this milestone, but there is only a single topic missing right now, all the rest is done. I believe if not next week at most in the other we will be submitting the delivery.

**Comment by Lohann** [comment]
@keeganquigley sorry for the delay, the milestone 2 has been delivered here:
https://github.com/w3f/Grant-Milestone-Delivery/pull/799

**Comment by keeganquigley** [comment]
@Lohann are you still making good progress on M3?

**Comment by leonardocustodio** [comment]
Hello @keeganquigley , we are very late for M3 unfortunately. But we won't give up ;)

**Comment by keeganquigley** [comment]
Thanks for the update @Lohann it's generally not an issue to be behind, we just ask that you submit an [amendment](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval) to extend the timeline if it will be significantly delayed. Thanks!

**Comment by keeganquigley** [comment]
pinging @leonardocustodio @Lohann

**Comment by keeganquigley** [comment]
Hi @Lohann I see the amendment PR was rejected due to inactivity. Let us know if we should re-open it. Otherwise we will likely cancel the grant in the coming days.

**Comment by leonardocustodio** [comment]
Hello @keeganquigley, I can't talk for Lohann but I can take over the project if you guys agree with. Though I would remove the sr25519 part for now as I would not be able to complete that anytime soon. And obviously with that make a few adjustments in the amendment.

**Comment by keeganquigley** [comment]
Thanks @leonardocustodio does this mean you will file an amendment PR yourself to mark this change and extend the timeline? That should work if @Lohann can confirm the change.

**Comment by leonardocustodio** [comment]
Yes, if everybody agrees obviously.

**Comment by Lohann** [comment]
@keeganquigley 
Hello, I apologize to everyone, unfortunately I haven't been able to dedicate as much time as I would like on this last milestone. We had 5 engineers working on this project, but implementing Signed Extrinsics requires a deep understanding of Substrate codebase and Rust, while working on it I even found a [bug on keyring/substrate substrate-bip39](https://github.com/paritytech/substrate/issues/14631), and currently only @leonardocustodio and I have the necessary knowledge and experience to implement this last milestone, which slowdown the development a bit.

I confirm @leonardocustodio as the new owner of Polkadart and this Grant, he is actively using polkadart in production and have the necessary knowledge to complete this last milestone, which is by far the most complex one. Besides that I'll continue as a contributor.

**Comment by keeganquigley** [comment]
Thanks for the update @Lohann sounds good. @leonardocustodio feel free to amend the original application to create an amendment PR. Feel free to ping me when I should take a look!

**Pull request merged**
