### PR TITLE
Anti-Collusion Infrastructure Application

### PR DESCRIPTION
**Pull request by StringNick**
#### Project Abstract

Anti-Collusion infrastructure with online voting example

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the application. But we would need to have more details and not just: "potentially via Minimum Anti-Collusion Infrastructure (MACI)," which could theoretically mean anything. What exactly are you planning to implement? Could you add as many technical details as possible to the milestone specification?

**Comment by StringNick** [comment]
@Noc2 hi, yeah i didn't write, because I don't know is it last version of algorithm. But if in a few words:

We have a trusted account that, for example, creates a poll, and alongside this, we have users. These users submit their encrypted votes in transactions. These transactions can be either valid or invalid, as it's necessary to render any attempts at bribery ineffective. The trusted account then computes all the submitted votes in batches and updates the poll's state. The computed results remain undisclosed. Instead, the trusted account provides a zk-SNARK hash of the computation. This approach enables everyone to verify that the trustee accurately calculated each vote. Consequently, the trustee cannot censor votes or commit fraud.

**Comment by StringNick** [comment]
I have read and hereby sign the Contributor License Agreement.

**Review by semuelle — CHANGES_REQUESTED** [review]
Thanks for the updates, @StringNick. I will have a closer look next week. In the meantime, could you please provide a registered address? If you prefer not to publish it, feel free to send it via [email](mailto:grants@web3.foundation).

**Review by semuelle — CHANGES_REQUESTED** [review]
Hi @StringNick. Thanks for the updates. However, many of the issues raised above are still not addressed. We would like to see some discussion of where this project fits in in the ecosystem (potential use cases, similar projects), what work has been done in this direction (either by you or others, in this ecosystem or others) and a more detailed description of the architecture. For example, you casually mention zk snarks. How are they integrated and where?

**Comment by semuelle** [comment]
pinging @StringNick

**Comment by semuelle** [comment]
Please let me know when we should have another look at the proposal, @StringNick.

**Comment by StringNick** [comment]
Sorry I was sick, now I am okay.
I add some updates about snark, I put a link of proposal by noc2 in rfp.

**Review by semuelle — CHANGES_REQUESTED** [review]
Sorry for the late reply, @StringNick. I just had another look at the application, and it still not in a shape that allows a proper review. Please have a look at the previous comments and update the document accordingly. Otherwise, I will close this application at the end of the week.

**Comment by StringNick** [comment]
> Thanks for the updates, @StringNick. Do you or anyone on your team have experience with Rust and Substrate? I couldn't find any Rust-based projects in any of the repos. 
i have rust experience(3 years), right now i have only one public pallet for another team, that i developed: https://github.com/Belsoft-rs/diffychat-pallet.
> Also, what do you mean by entering the ecosystem "as part of the Substrate Developer"?
i started making some pet projects based on substrate from 2020, also ink smart contracts but more of them private (freelance) projects for customers.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the application and all the effort you put into this. However, the grants committee decided today not to go ahead with your application. Part of the reason we decided against it is that, ideally, someone should implement it who will also use and maintain it. Another reason is that we weren't fully convinced by the application itself. Independent of it, we wish you all the best, and let us know if you have any questions.

**Pull request closed without merging**
