### PR TITLE
Kuma Wallet - Phase 2

### PR DESCRIPTION
**Pull request by 0xslipk**
#### Project Abstract

This is a follow-up grant for the previous successfully delivered [Cross-chain Wallet - XCW grant](https://github.com/w3f/Grants-Program/blob/master/applications/cross-chain-wallet.md) under [W3F's General Grants Program](https://github.com/w3f/General-Grants-Program/).

Kuma Wallet is a cross-chain wallet designed to revolutionize the way users interact with EVM and WASM blockchain networks. Built with user-friendliness and security in mind, Kuma Wallet aims to streamline cross-chain asset management and provide a unified, intuitive interface for asset transfers, dApp interactions, and much more.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) or BTC address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by 0xslipk** [comment]
I have read and hereby sign the Contributor License Agreement.

**Review by keeganquigley — CHANGES_REQUESTED** [review]
Hi @0xslipk nice to see you again. I am a fan of Kuma wallet and it's a very well-built product, but in my opinion I'd suggest going for treasury funding at this point since we already bootstrapped the initial phases. Especially with M2 & M3 because Transak is not open-source afaik, and this would ideally create a revenue source for you via fees, as well as the fees that go to Transak for each tx. So I'm not sure we'd be willing to fund this. Also, the integration with HydraDX might be a better fit for their [grants program](https://docs.hydradx.io/spending_fw/).

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the application. I agree with @keeganquigley here. Also, regarding HydraDX. Our grants program needs to be as objective as possible.

**Comment by 0xslipk** [comment]
I complely understand. Thank you for the feedback. We are gonna ask HydraDX team about.

**Pull request closed without merging**
