### PR TITLE
Add NFT Explorer

### PR DESCRIPTION
**Pull request by wuminzhe**
# Grant Application

## Abstract

UniArts NFT Explorer wants to be the best place to analyze, track and discover NFTs.

UniArts NFT Explorer hopes to create a unified NFT dedicated explorer for the Polkadot / Kusama ecology. It can be used to discover and view the NFTs of parachains. 

## Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] The total funding amount of the project is below USD $30k for first-time grant applications and $100k for follow-up ones.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

### CODE REVIEW

**Comment by Noc2** [comment]
Sorry for the late response here. In general, I think we are interested in an NFT Explorer. However, your current deliverables look like you want to create a NFT explorer for ethereum and doesn’t seem to be focused on our ecosystem, which is a key requirement of our grants program. I’m pretty sure there are existing explorers for this, which you might be able to reuse. Also we usually don’t fund initial research into our ecosystem via grants (regarding: “ how to monitor the events of evm under Substrate”), since this isn’t something necessarily useful for others. 
If you want to create an NFT explorer focused on substrate, you might want to take a look at the existing indexing and block explorer solutions: https://github.com/w3f/Grants-Program/blob/master/docs/polkadot_stack.md.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Sorry for the late response here. In general, I think we are interested in an NFT Explorer. However, your current deliverables look like you want to create a NFT explorer for ethereum and doesn’t seem to be focused on our ecosystem, which is a key requirement of our grants program. I’m pretty sure there are existing explorers for this, which you might be able to reuse. Also we usually don’t fund initial research into our ecosystem via grants (regarding: “ how to monitor the events of evm under Substrate”), since this isn’t something necessarily useful for others. 
If you want to create an NFT explorer focused on substrate, you might want to take a look at the existing indexing and block explorer solutions: https://github.com/w3f/Grants-Program/blob/master/docs/polkadot_stack.md.

**Comment by semuelle** [comment]
Hi @wuminzhe, thank you for your application. 

What are the `certain addresses and topics` you are planning to query? This seems at odds with what you are saying in the beginning that you `do not require submission or application by NFT creators`

**Comment by wuminzhe** [comment]
> Sorry for the late response here. In general, I think we are interested in an NFT Explorer. However, your current deliverables look like you want to create a NFT explorer for ethereum and doesn’t seem to be focused on our ecosystem, which is a key requirement of our grants program. I’m pretty sure there are existing explorers for this, which you might be able to reuse. Also we usually don’t fund initial research into our ecosystem via grants (regarding: “ how to monitor the events of evm under Substrate”), since this isn’t something necessarily useful for others.
> If you want to create an NFT explorer focused on substrate, you might want to take a look at the existing indexing and block explorer solutions: https://github.com/w3f/Grants-Program/blob/master/docs/polkadot_stack.md.

Thanks for the reply, Here is my opinion:
1. I don't see an explorer in the Polkadot ecosystem that is suitable for NFT, the current explorers are all block explorers. If there is something I don't know, please tell me. 
2. It's not for ethereum, but for evm compatibility substrate blockchains. because the most widely used VMs in the Polkadot ecosystem now are evm-compatible VMs. I think there will be a lot of evm-based NFTs soon. We will support wasm and statemine in the future.
3. About "how to monitor the events of evm under Substrate"
    I think technically we already know how to do that.
    But evm generates both substrate events and evm events, which are tracked differently. And, evm itself is changing rapidly. So, We need to take a different approach depending on the different chains. So this feature is not something to study, but to follow the individual projects that use evm.

**Comment by wuminzhe** [comment]
> Hi @wuminzhe, thank you for your application.
> 
> What are the `certain addresses and topics` you are planning to query? This seems at odds with what you are saying in the beginning that you `do not require submission or application by NFT creators`

`certain addresses and topics`. It is just a lib or a framework to track `certain addresses and topics`.  But the addresses and topics are from auto-discovery.

But we may need a blacklist to block some bad NFTs.

**Comment by Noc2** [comment]
1. See [NFT Explorer for Kusama & Polkadot](https://github.com/kodadot/nft-gallery). But I was referring to the fact that the existing explorer can be changed to also monitor for example substrate NFT related events (given that they already monitor every event, see https://polkascan.io/kusama/event and once an nft pallet is integrated), so you could reuse the backend for this and mostly focus on the frontend.  
2. Could you describe the difference between an ethereum focused block explorer and an evm focused block explorer for NFTs? I was under the impression that moonbeam implementation let’s you reuse the existing evm stack, but I might be wrong for this specific use case. 
3. In general it would be nice to have more technical details as part of the application.

**Comment by wuminzhe** [comment]
> 1. See [NFT Explorer for Kusama & Polkadot](https://github.com/kodadot/nft-gallery). But I was referring to the fact that the existing explorer can be changed to also monitor for example substrate NFT related events (given that they already monitor every event, see https://polkascan.io/kusama/event and once an nft pallet is integrated), so you could reuse the backend for this and mostly focus on the frontend.
> 2. Could you describe the difference between an ethereum focused block explorer and an evm focused block explorer for NFTs? I was under the impression that moonbeam implementation let’s you reuse the existing evm stack, but I might be wrong for this specific use case.
> 3. In general it would be nice to have more technical details as part of the application.

1. I listed the kodadot nft gallery in the similar projects section. It is just for rmrk nfts. It's a part of the RMRK. Our final goal is to build an all-in-one explorer for Polkadot & Kusama ecosystem with some data statistics for users to easily discover NFTs. This goal is too big for now. I just want to say that our direction is different from kodadot nft gallery.

Other existing explorers like opensea are NFTs markets than explorers. They are not permissionless. And they are not for Polkadot ecosystem.

2. An ethereum focused block explorer and an evm focused block explorer for NFTs are similar now. But I think They will be a lot different in the future. Because each project has the ability to modify its own evm pallet.

3. For evm, we use the filter to get the target logs. `eth_newFilter` and `eth_getLogs` are the rpc methods we use. I created a small lib to track logs: https://github.com/wuminzhe/evm-log-tracker

    For substrate events, we get the events block by block. similar to https://github.com/darwinia-network/bridger/blob/master/task/task-darwinia-ethereum/src/service/darwinia

I would like to say that for this project, the technology is not difficult, what matters is the direction, and there is not an NFT explorer with the same direction in the Polkadot ecosystem. It is also difficult for the ethereum NFT explorers to cover the chains in the Polkadot ecosystem.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the quick response. But could you please update the specification in the application itself. These are basically the requirements of the contract. Also keep in mind that in the future a lot of things can change, but we can only cover things as part of the grant that reflect the current status quo. For example if we sign the grant for evm support, you will be able to deliver the grant based on the current evm implementation and not potential future versions, which might be different. Also you milestone 2 currently only covers the deployment as key deliverable (at least how it’s currently phrased), that’s something we don’t cover why grants. We only support the development of open source code that can be used by others in our ecosystem.

**Comment by wuminzhe** [comment]
> Thanks for the quick response. But could you please update the specification in the application itself. These are basically the requirements of the contract. Also keep in mind that in the future a lot of things can change, but we can only cover things as part of the grant that reflect the current status quo. For example if we sign the grant for evm support, you will be able to deliver the grant based on the current evm implementation and not potential future versions, which might be different. Also you milestone 2 currently only covers the deployment as key deliverable (at least how it’s currently phrased), that’s something we don’t cover with grants. We only support the development of open source code that can be used by others in our ecosystem.


Thank you for your reply. I need your help to figure out what needs to be updated.

1. I will add the difference between this project and Kodadot NFT gallery.
2. I will change the milestone 2's deliverables.

Is there something I'm missing? Are the boundaries of this grant not clear enough?

**Comment by Noc2** [comment]
Sounds good. Just two add two things:
- Regarding “Workers for chain“, rather focus on the technical deliverable than having something deployed for different chains. 
- Maybe integrate some explanation why you are not using an ethereum focused block explorer for NFTs, but rather develop your own solution for the evm.

**Comment by wuminzhe** [comment]
@Noc2 I understand what you mean now. Thank you.

**Comment by alxs** [comment]
Linking to your previous application for reference: https://github.com/w3f/Grants-Program/pull/368

**Comment by wuminzhe** [comment]
@Noc2 I have updated the content. Please review again. Thank you.

1. Uniscan is a newly created team for the NFT explorer. I joined to develop this.
2. Because the evm integration of Uniarts is still in progress, so I removed it from the application.
3. I change the milestone 1&2's deliverables.
4. I add the difference between this project and Kodadot NFT gallery.
5. I add the `Why evm?` section.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. Looks more or less good to me. But I have a few additional comments: Could you integrate the notion documents into the application? Otherwise you could theoretically update the content of the links and therefore the deliveries without our approval. Also just for clarification: Could you add the programming language to the specification of the deliverables (e.g. lib)? And it might make sense to replace Moonbean and Darwinia with more general terms (substrate and evm), since we don’t want to support a specific chain via our grants program.

**Comment by wuminzhe** [comment]
@Noc2 Updated

**Review by Noc2 — APPROVED** [review]
Looks good to me, I will share it with the rest of the team.

**Comment by semuelle** [comment]
Hi @wuminzhe, thanks for the application. Everything makes sense, I'm just wondering if it'll be possible to buy the listed NFTs through the explorer? In other words, is it generally possible to discover if they are listed on a marketplace (through contract events or centralised market APIs) and are you planning to integrate links to these marketplaces?

**Comment by wuminzhe** [comment]
Hi @semuelle
We will consider adding the marketplace link in the future. We don't plan to add buying and selling functions ourselves.

**Review by semuelle — APPROVED** [review]

**Review by Lederstrumpf — APPROVED** [review]

**Comment by alxs** [comment]
Congratulations and welcome to the Web3 Foundation Grants Program! Please refer to our [Milestone Delivery repository](https://github.com/w3f/Grant-Milestone-Delivery/) for instructions on how to submit milestones and invoices, our [FAQ](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md) for frequently asked questions and the [support section of our README](https://github.com/w3f/Grants-Program/blob/master/README.md#support) for more ways to find answers to your questions.

Before you start, take a moment to read through our [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md) for all communications related to the grant or make them known to the right person in your organisation. In particular, please <b>don't announce the grant publicly before at least the first milestone of your project has been approved.</b> At that point or shortly before, you can get in touch with us at grantsPR@web3.foundation and we'll be happy to collaborate on an announcement about the work you’re doing.

Lastly, please remember to let us know in case you run into any delays or deviate from the deliverables in your application. You can either leave a comment here or directly request to amend your application via PR. We wish you luck with your project! :rocket:

**Pull request merged**
