### PR TITLE
quantum lock lvl 1 grant proposal

### PR DESCRIPTION
**Pull request by bqpquantum**
The application for lvl 1 grant proposal.

### Project Abstract

We are developing an enhancement to the blockchain consensus protocol to enable it to run on a quantum computer. The core development is the Quantum Lock which enables the proof-of-quantum-work. Our Quantum Lock uses quantum computation with marginal energy cost that is only a fraction of its classical counter-part. The most significant benefit is the potential to drastically diminish the energy consumption involved in a classical proof-of-work computation, while the consensus protocol scales with emergence of the quantum computing power. The first application of the Quantum Lock is the QBITCOIN.  

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [x ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x ] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x ] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x ] The software delivered for this grant will be released under an open-source license specified in the application.
- [x ] The initial PR contains only one commit (squash and force-push if needed).
- [ x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] Hackathon
- [ x] Personal Recommendation
- [ ] Substrate Builders Program
- [ ] Investor/VC
- [ ] Online Search 
- [ ] Other: _______

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Sounds like an interesting project and I’m generally happy to give it a try. But I have a few quick questions (and sorry in case I missed something because I haven’t looked into detail into the process): 

- How computation intensive is calculating the forrelation function on-chain? Doesn’t it make more sense to do this off chain via offchain worker? It might make sense to take a look at Phragmén and how it’s implemented. 
- How does it drastically diminish the energy consumption involved in a classical proof-of-work computation? Wouldn’t you still compete like in classic proof-of-work and therefore the more the better? 
- Also you might want to take a look at this: https://docs.substrate.io/how-to-guides/v3/consensus/pow/ and for example https://github.com/kulupu/kulupu, which you can find here: https://github.com/w3f/Grants-Program/blob/master/docs/polkadot_stack.md#heavy_check_mark-consensus

**Comment by bqpquantum** [comment]
> Sounds like an interesting project and I’m generally happy to give it a try. But I have a few quick questions (and sorry in case I missed something because I haven’t looked into detail into the process):
> 
> * How computation intensive is calculating the forrelation function on-chain? Doesn’t it make more sense to do this off chain via offchain worker? It might make sense to take a look at Phragmén and how it’s implemented.

This is an idea which we are contemplating. We do internally work with this as a proof of quantum authority (node has ability to perform quantum work). We aim to explore this in later stage, once we have proof of quantum work up and running (that is more vanilla concept). It will be certainly useful when thinking about quantum smart contracts and calculation of useful quantum tasks.

> * How does it drastically diminish the energy consumption involved in a classical proof-of-work computation? Wouldn’t you still compete like in classic proof-of-work and therefore the more the better?

Quantum computing is per se energy more efficient and energy consumption does not scale in the same way for classical computing. By some estimation, the reduction in energy consumption as result of processing data with quantum computing can be a factor of 10^-2 to 10^-3, which is huge.  It is indeed true, that proof of work will always be on “more the better“ and thus there will be demand for more work; however, we are proposing technology, which will work on different scale compared to current levels. There will be competition in improving the ability to do quantum computing between the nodes but such competition cannot be trivially won by more brute force energy consumption. 

Bit of a hope here is that such competition enabled by our protocol can promote genial technological progress in quantum error correction, quantum circuit optimization and distributed quantum computation, which would in turn bring substantial positive impact in various domains. On the contrary, traditional PoW in many sense, unfortunately, has zeroed in on a pattern of destructive competition.

> * Also you might want to take a look at this: https://docs.substrate.io/how-to-guides/v3/consensus/pow/ and for example https://github.com/kulupu/kulupu, which you can find here: https://github.com/w3f/Grants-Program/blob/master/docs/polkadot_stack.md#heavy_check_mark-consensus

Thanks for links!

**Review by Noc2 — APPROVED** [review]
Thanks for the detailed reply. Makes sense. I’m happy to go ahead with this and will share it with the rest of the team.

**Review by takahser — APPROVED** [review]
I have just one question: Since you're using quantum algorithms, will they be able to run on traditional hardware as well?
But anyways, I'm happy to go approve it as well, sounds like a revolutionary consensus algorithm.

**Comment by alxs** [comment]
Hey @bqpquantum, are you still interested in this? Note that if we don't hear from you within the next two weeks, we will assume you're no longer interested and terminate the grant.

**Pull request merged**
