### PR TITLE
Create DataBlock.md

### PR DESCRIPTION
**Pull request by diposs**
#### Project Abstract

> A searchable database that provides a record of precedence, cross-chain analysis, proof of history, context, security, and ownership of NFTs across multiple parachains in the Polkadot ecosystem and other Blockchains. The tracker will collect data like NFT creation, past ownership history, metadata. The data will be made accessible via [polybase](polybase.xyz) and Datablock own SDK.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [x] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@diposs:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by diposs** [comment]
Polybase.xyz is a very versatile web3 database system. In my view it is more like a backend as services. I could have applied a general database like mongodb but I wanted a service in the web3 space that checks all the boxes. "Data model definition" uses polybase polylang to write out the schemas. All schemas are public so access to how the database is written and how it handles data is all public. Yes, the data stored could be made private like every other web2 database but, it isn't beneficial to have it private. I want an information repo that can be challenged for data inconsistencies or any mistakes. 
The reason for involving lots of chains if for cross-chain analysis. Nft minted on one  chain by a certain person or persons should be known by everyone. If such nft data is minted elsewhere the data act as proof of history, precedence and security. If the chains allowed are only polkadot and it substrates, it still permits fraud in the system since most users would be oblivious  to its existence elsewhere.
This modeling style and inclusion of other chains outside the polkadot ecosystem provides security for both the popular and unpopular NFT project, be it media or document. 

Thank you.

**Comment by diposs** [comment]
Modified the chains to just include polkadot and Ethereum.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the quick reply. I would still recommend to define the actual deliveries more concrete (e.g. what kind of NFT standards will you support) and how it's useful compared to existing solutions. The fact that you will use polybase alone isn't very concrete. Also for this grant, feel free to remove ETH as well. We are looking for projects that are beneficial for the Polkadot/Kusama/Substrate ecosystem as part of this grants program.

**Comment by diposs** [comment]
@Noc2  Modifications have been made. The project would be focused on just Polkadot and its parachains. I would also provide a Graphql Schema

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. I will mark the applications as ready for review. However, I personally won't accept it since I don't see a lot of value in it compared to the existing solutions. But the rest of the team might have a different opinion.

**Comment by keeganquigley** [comment]
Thanks for the application @diposs a couple of questions/comments:

- Is this application in response to your own needs as a user that were not being met? Have you done any temperature checks in the community to see if this is needed and researched the other NFT projects [here](https://wiki.polkadot.network/docs/build-open-source)?
- Is the Vercel app currently supposed to do anything? I can see the search bar but can't get it to index anything.
- Your application states that EVM compatibility will be completed "later on", but the delivery tables states that the scanner module will work with "EVM-compatible NFTs". This seems contradictory to me, can you explain which is the case?
- How do you plan to fund upkeeping the app and integrating XCM v4 when it is released?

Thanks!

**Comment by diposs** [comment]
- Is this application in response to your own needs as a user that were not being met? Have you done any temperature checks in the community to see if this is needed and researched the other NFT projects [here](https://wiki.polkadot.network/docs/build-open-source)?
- Yes. Temperature checks, No! ondora.xyz and nftscans.com are similar projects but not the same as mine
- Is the Vercel app currently supposed to do anything? I can see the search bar but can't get it to index anything.
- it isn't yet connected to output the data from my polybase collection but if you wish for the explore version 
[https://explorer.testnet.polybase.xyz/collections/pk%2F0x89de820323237a0e6cab8c5f29dfbf2f026f8c1da20c01f5b06b31877252a9d0f493bf95b625b667b1bdb3fb1593553bda1f056220cb2aa0e680316dba8b9a2c%2Fsh!%2FIndexBlock](https://explorer.testnet.polybase.xyz/collections/pk%2F0x89de820323237a0e6cab8c5f29dfbf2f026f8c1da20c01f5b06b31877252a9d0f493bf95b625b667b1bdb3fb1593553bda1f056220cb2aa0e680316dba8b9a2c%2Fsh!%2FIndexBlock)
- Your application states that EVM compatibility will be completed "later on", but the delivery tables states that the scanner module will work with "EVM-compatible NFTs". This seems contradictory to me, can you explain which is the case?
- later on, Yes. it doesn't stop the project from indexing data of EVM- Compatible NFTs. 
- How do you plan to fund upkeeping the app and integrating XCM v4 when it is released?
- I do not wish to respond.


my opinion 

> Every Blockchain grant tends to be just a little selfish. 
> Just fix my Blockchain or limit the scope. 
> Being honest I rather work on multiple Blockchains than just one. 
> I have been advised to remove other chains from my application. 

This entire process put I and my project at the mercy of Polkadot. from agreeing to fully opensource to polkadot being the sole judge of an acceptable job welldone or not to funds only being paid after job completion. Nothing before completion. 
 All this policies aren't a turn off to me but if the line of questioning is this considering how lopsided the agreement is for a level1 project, Please close if you feel having an entire overview of the entire blockchain to provide enhance security by informing the community of fraud committed on other chains due to the value extracted on other chains isn't Value enough? 
 I am contended with having this proposal closed. 
 Thank you

**Pull request closed without merging**
