### PR TITLE
Calamar application

### PR DESCRIPTION
**Pull request by uiii**
#### Project Abstract

Calamar is a block explorer for Polkadot and Kusama relay chains and their parachains, that uses Subsquid API for data fetching.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [X] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [X] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [X] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [X] The software delivered for this grant will be released under an open-source license specified in the application.
- [X] The initial PR contains only one commit (squash and force-push if needed).
- [X] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. This looks really interesting. The links don’t seem to be working. For example, if I click on account detail overview or cross-chain transfers. Also, could you try to be more specific with your deliveries, for example, what does “...” exactly mean, what is the meaning of “improve” or does “fix things” include more than the search. What kind of  ​​cross-chain information will you share? etc. Additionally, the integration into Polkadot.js apps is probably not up to you. So I would simply say something like creating a PR for this or something similar.

**Comment by uiii** [comment]
@Noc2 Hi, thanks for the reply. 
- These two links works for me, they are only for skipping to the section in the Project details. Are there other links which don't work?
- As for deliveries, I will rewrite it more specifically.
- And with Polkadot.js integration, yes you are right I meant a PR.

**Comment by uiii** [comment]
@Noc2 I've updated the application

**Review by Noc2 — APPROVED** [review]

**Comment by Noc2** [comment]
Thanks for the update. I’m happy to support it and I will share it with the rest of the team.

**Review by alxs — APPROVED** [review]
LGTM! This looks fantastic. For the XCM features, perhaps you want to have a look at the discussion [here](https://github.com/w3f/Grants-Program/pull/1039).

**Review by gautamdhameja — APPROVED** [review]

**Comment by uiii** [comment]
Hi guys, I'd like to inform you that, unfortunately, we will have a delay in our milestone delivery. We need few more weeks to finish. We don't work on Calamar full-time and several issues/tasks occured which are not part of the grant but need to be done. I hope this is ok.

**Comment by alxs** [comment]
No worries and thanks for letting us know. If it takes longer than a few more weeks (let's say, end of the month), could you please submit an [amendment](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval) with an updated timeline? You can also always do the same if you want to modify the scope of the grant.

**Comment by keeganquigley** [comment]
Hi @uiii how is milestone 2 coming along?

**Comment by uiii** [comment]
Hello @keeganquigley, I was about to write here. We are working on it and it will be finished soon. There are delays because, among other things, we need to wait for some data resources from Subquid.

**Comment by uiii** [comment]
Hello, I just want to let you know we are finishing the milestone, but still waiting for some last resources to be provided by Subsquid, we are dependend on them in this. Sorry for the delay.

**Comment by keeganquigley** [comment]
Hi @uiii just a friendly ping. If you think it will take a significant amount of time, consider submitting an amendment PR to extend the timeline. Thanks!

**Comment by uiii** [comment]
Hi @keeganquigley. Understand, we have almost all finished, only few relatively small features are missing. So I'm thinking about submitting the delivery either way and moving them to the next milestone, is this ok?

**Comment by Noc2** [comment]
Hi. This generally depends on the grants committee and the exact deliveries that are missing, etc.. Feel free to create a PR to amend your original grant agreement. As long as it's reasonable we usually merge these rather quickly.

**Comment by uiii** [comment]
Hello guys, we finally finished it and submitted the delivery PR: https://github.com/w3f/Grant-Milestone-Delivery/pull/867

**Comment by keeganquigley** [comment]
Hi @uiii how is Milestone 3 coming along?

**Comment by uiii** [comment]
Hello @keeganquigley, the current miletone is little bit on hold, there's not much done yet. I should have updated the application. In an upcomming week or two I will know if I we start working on the milestone now or later. I'll update the application whenever I know, is it ok?

**Comment by keeganquigley** [comment]
thanks @uiii does this mean you are planning to submit an amendment?

**Comment by uiii** [comment]
Hey @keeganquigley, well the original plan is still valid, we just would like to extend it with something more to use the grant fully but haven't figured it out yet. So we stick to the original plan for now and might submit the amendment later.

**Comment by keeganquigley** [comment]
Hi @uiii since it has been a month please go ahead and submit the amendment if you want to extend the timeline. Thanks!

**Comment by uiii** [comment]
Hey @keeganquigley I'd like to but not sure yet how. We are working on the universal search now, it is fine. But the XCM part is uncertain because this week Subsquid inform us about their changes of plans in developing of the backend infrastructure we are using. We were counting on them that XCM will be ready soon but it won't happen soon. We are in contact with them but we need some more time to figure out what next.

**Comment by uiii** [comment]
Hi @keeganquigley I've amended the application: https://github.com/w3f/Grants-Program/pull/2055

**Comment by keeganquigley** [comment]
Hi @uiii are you able to provide an update on M3?

**Comment by uiii** [comment]
Hi @keeganquigley, yes. We are finishing and I'll be sending the delivery during next week.

**Pull request merged**
