### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by DappGuy**
### Project Abstract

Diora Network is a public EVM-compatible parachain for the Dotsama ecosystem. We are hoping to realize 2000+ TPS utilizing advanced PoSM with Double Validation & Randomization for security guarantees.

Diora Network proposes the Proof of Stake Masternode (PoSM) consensus, which is a PoS based blockchain protocol with a fair voting mechanism & rigorous security guarantees.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying?

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [X] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] I have read and understood the [FAQs](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md), [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md) and [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).
- [ ] I prefer the discussion of this application to be in a private Element/Matrix channel. My username is: ``@_______``

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] Hackathon
- [ ] Personal Recommendation
- [ ] Substrate Builders Program
- [ ] Investor/VC
- [x] Online Search
- [ ] Other: _______

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Could you make sure that all milestones have the default deliverables 0a-0d of the [template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md). These are usually mandatory.  Also feel free to add the programming languages to the deliverables and remove the deployment focused deliverables, like “Kusama Parachain Testnet” or “Crowdloan Prep”. We usually focus on the technical open source deliverables that could also be useful for other projects in our ecosystem and reused for other purposes.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. However, the default deliverables of the template seem to be still missing (see above). For example it’s usually mandatory to specify the licence of the deliverable.

**Comment by semuelle** [comment]
ping @DappGuy

**Comment by Noc2** [comment]
I’m closing this PR due to inactivity. Let me know if I should reopen it.

**Pull request closed without merging**
