### PR TITLE
SubFlow: Web3 microblogging Smart Service

### PR DESCRIPTION
**Pull request by deus4**
#### Project Abstract

SubFlow aims to develop a decentralised social media platform that empowers users with control over their data and interactions.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit.
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).
- [x] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@antsu:matrix.org`

### CODE REVIEW

**Comment by keeganquigley** [comment]
Left a comment in the private chat room.

**Comment by keeganquigley** [comment]
Left a comment in private channel.

**Review by Noc2 — CHANGES_REQUESTED** [review]
I left a comment in the private channel.

**Review by takahser — CHANGES_REQUESTED** [review]
@deus4 I left a comment as well.

**Review by semuelle — CHANGES_REQUESTED** [review]
Left a comment in the chatroom.

**Comment by takahser** [comment]
@deus4 unfortunately, the committee has decided against the approval of this approval. The reasons thereof have been shared confidentially. Thank you for your understanding, and we hope this decision doesn't deter your passion and determination for the success of your project. Also, you're welcome to apply for another grant at our program in the future!

**Pull request closed without merging**
