### PR TITLE
Create HorizonFinance.md

### PR DESCRIPTION
**Pull request by Saumay-Agrawal**
#### Project Abstract

Horizon Finance aims to make XCM transfers more user friendly for DotSama users.  We want to make the experience of doing XCM transfers as smooth as swapping tokens on Uniswap.

We will do this by building a good user experience for all things surrounding an XCM transfer like wallet selection, network/parachain selection, amount inputs etc. This is covered more in-depth under the project details section.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) address in the application).
- [x] I am aware that, in order to receive a grant, I (and the entity I represent) have to successfully complete a KYC/KYB check.
- [ ] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by Saumay-Agrawal** [comment]
I have read and hereby sign the Contributor License Agreement.

**Review by keeganquigley — CHANGES_REQUESTED** [review]
Thanks for the application @Saumay-Agrawal a couple of initial comments:

- Since you already have a prototype and are looking to form a self-sustaining company, I wonder if the new Polkadot [decentralization fund](https://futures.web3.foundation/) would be a better fit for the project. 
- Also because we don't cover getting code ready for production, so M2 is essentially out of scope, as we wouldn't pay for beta testing, CI/CD, customer feedback, etc. Whereas the DF fund can cover this.
- As well as the fact that it would mainly be a finance product.
- For M1, we don't cover design and typically ask for rough mockups to be included upfront.
- In case you haven't heard of [ParaSpell](https://github.com/w3f/Grants-Program/pull/1118), their [XCM-SDK](https://github.com/paraspell/xcm-sdk) and [XCM-API](https://github.com/paraspell/xcm-api) might be of great use for this project.

**Comment by Saumay-Agrawal** [comment]
Hey @keeganquigley, thanks a lot for the feedback & sharing these resources. I'll look into these, discuss the feedback with my team and get back to you soon. 

> As well as the fact that it would mainly be a finance product.

Also, can you please elaborate more on this?

**Comment by keeganquigley** [comment]
Thanks @Saumay-Agrawal sounds good. To answer your question, recently the grants program has shifted its focus a bit to focus on core tech that directly benefits the ecosystem. So it's not that we don't fund DeFi projects outright, but the W3F grants program focuses on early-stage PoCs, and it would have to directly benefit the community somehow to make sense for us to fund the full platform. Also, DeFi projects typically release a token or have other means of collecting revenue, making it possibly not a great fit for the program (see our guidlines on [token sales](https://github.com/w3f/Grants-Program?tab=readme-ov-file#wave-introduction)). 

Essentially, the committee likes to see deliverables that contain re-usable components/resources that others can utilize, rather than deliverables that are really only useful for your product.

**Review by takahser — CHANGES_REQUESTED** [review]
@Saumay-Agrawal as pointed out by @keeganquigley this project seems to be quite similar to [ParaSpell](https://paraspell.github.io/docs/) so I'd be curious to learn how your project is different from theirs.

**Comment by dudo50** [comment]
@keeganquigley , thanks for mentioning our products, we value this a lot. @Saumay-Agrawal , if you feel interested in implementing any of our tools feel free to contact us. We can assist your team free of charge.

With kind regards,
Team ParaSpell.

**Comment by Saumay-Agrawal** [comment]
Hi @takahser! - ParaSpell is a low level developer tooling to make XCM transactions easier, while we're building a user facing product. We can use it as a single interface for interacting with the asset transfer API & the XCM pallet instead of integrating them separately. 

About the price, yes on a surface level $30k just for building a UI might seem expensive. But we're aiming to build a good user experience, and there's a difference. 

There are many intricacies associated with a single XCM transfer that require a lot of thinking from a product design perspective and a good amount of collaboration between the designers & the developers. 

The entire user flow of making an XCM transfer includes many user decisions like:
- Selecting a wallet, and then selecting the account to make the transfer from
- Selecting a network (polkadot or kusama)
- Selecting a destination parachain
- Selecting a destination address (could be a substrate address or a native parachain address)
- Selecting the asset to be transferred and it's amount

All of these steps are intertwined, and would need dynamic UI components that would change basis each user decision to give the user realtime feedback. Beyond these, we will also give heads up about things that will lead to a failed transaction in order to prevent them. Each of these UI elements would need lower level technical integrations to be able to work properly. 

We will also be giving an ability to view all previous XCM transfers done by the user within the app itself. This would also need us to setup appropriate backend infra & integrate it with the relevant UI components. 

So if one would consider the amount of efforts and collaboration needed between the product & tech talent, the price would seem justified.

Happy to discuss this further & address any more concerns you have around this!

**Comment by Saumay-Agrawal** [comment]
Hi @dudo50 - thanks for letting us know. We're looking into ParaSpell and we'll reach out soon! :)

**Comment by Saumay-Agrawal** [comment]
Hi @keeganquigley! -  A short update from our end. As you mentioned, Decentralised Futures Fund is a better fit for our project and we're going ahead for it. Thanks again for helping me with all the details & the feedback. 🙏

**Comment by semuelle** [comment]
Thanks for the update, @Saumay-Agrawal. In that case, I am going to close this PR for now. We can reopen it later if needed.

**Pull request closed without merging**
