### PR TITLE
Create Apenotic-DID-Wallet.md

### PR DESCRIPTION
**Pull request by phemestre**
Web3 Foundation Grant Application for Apenotic DID Wallet

#### Project Abstract

The Apenotic DID Wallet is a user-centric decentralized identity (DID) solution designed to provide users with complete control over their digital identities and blockchain assets. Apenotic empowers users to grant selective access to their blockchain information while safeguarding their wallet address, enhancing privacy, and ensuring data security. Our platform offers a unified and interconnected experience for managing digital assets across multiple blockchain networks. With a focus on interoperability and self-sovereign identity, Apenotic is at the forefront of revolutionizing digital identity management in the Web3 era.

#### Grant Level

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The application template has been copied and aptly renamed (`apenotic_did_wallet.md`).
- [x] I have read the application guidelines.
- [x] Payment details have been provided (USDC address: [USDC_Wallet_Address] in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit.
- [x] The grant will only be announced once the first milestone has been accepted.
- [x] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@phemestre:matrix.org`.

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
(Changes requested via the private channel on elements)

**Review by semuelle — CHANGES_REQUESTED** [review]
I left some questions in the private chat.

**Review by semuelle — CHANGES_REQUESTED** [review]
Left some questions in the chat.

**Review by semuelle — CHANGES_REQUESTED** [review]
Sorry for the long wait, @phemestre. I added more comments in the chat.

**Review by takahser — CHANGES_REQUESTED** [review]
@phemestre I added a comment in the private chat as well.

**Pull request closed without merging**
