### PR TITLE
Widelens

### PR DESCRIPTION
**Pull request by josephriosIO**
### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application and the interest in our grants program. However, our grants program focuses on funding software development and research efforts related to [Polkadot, Kusama, Substrate and ink!](https://github.com/w3f/Grants-Program#wave-introduction). Your application seems to focus on Ethereum instead. Let me know if you want to focus on our tech stack instead or I misunderstood something, otherwise I’m going to close the application.

**Comment by josephriosIO** [comment]
> Thanks for the application and the interest in our grants program. However, our grants program focuses on funding software development and research efforts related to [Polkadot, Kusama, Substrate and ink!](https://github.com/w3f/Grants-Program#wave-introduction). Your application seems to focus on Ethereum instead. Let me know if you want to focus on our tech stack instead or I misunderstood something, otherwise I’m going to close the application.

I'd be interested in offering abilities to see chains such as polkadot, I can see there is a use case for multichain NFT transaction social media app.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Sounds good. In this case, could you update the application and integrate the use of either ink! Smart contract or substrate pallets. Also we don’t pay out teams in ETH and deliverables 0a-0d of our template are mandatory for all milestones, see https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md Alternatively let me know, if I should close the application and we can reopen it once you are ready.

**Comment by josephriosIO** [comment]
> Sounds good. In this case, could you update the application and integrate the use of either ink! Smart contract or substrate pallets. Also we don’t pay out teams in ETH and deliverables 0a-0d of our template are mandatory for all milestones, see https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md Alternatively let me know, if I should close the application and we can reopen it once you are ready.

Pushed the changes! Let me know what else is needed.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. However, you application still seems to be focused on Ethereum, e.g. (etherscan). We only support software development and research efforts related to [Polkadot, Kusama, Substrate and ink!.](https://github.com/w3f/Grants-Program#wave-introduction).

**Pull request closed without merging**
