### PR TITLE
Xcavate Milestone 2 W3F Grant Application

### PR DESCRIPTION
**Pull request by xcavate2022**
#### Project Abstract

> Real world real estate has traditionally been only available to a small number of people due to the incredibly complex nature of the asset. It is currently not possible to invest directly from a real estate developer without "trusted" third party intermediaries like banks, solicitors, estate agents and investment funds.
> Our goal is to create a community-controlled protocol, which empowers global communities to directly fund and invest in real estate developments that span across; residential, commercial and community non-for-profit projects. By leveraging sovereign digital identity and real estate asset specific verifiable credentials, this will create a less trust more transparency environment, removing many barriers to entry for the average person.
>
> This is a follow-up to a previous grant, https://github.com/w3f/Grants-Program/pull/1649

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) or BTC address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by meanking — APPROVED** [review]
I reviewed and resolved the conflicts.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the PR, but it looks like you want to apply for a follow-up grant and not amend the current agreement. Could add a new application/file to the repo, rather than changing the existing agreement?

**Comment by xcavate2022** [comment]
Apologies - yes we are applying for a follow up grant… I’ll create a new application now

**Comment by xcavate2022** [comment]
Incorrect PR... new application created for milestone 2

**Pull request closed without merging**
