### PR TITLE
Submit application of Primis

### PR DESCRIPTION
**Pull request by Andy-Meta**
### Project Abstract

Primis redefines the Web3 Desktop world. 
In here, a basic Web3 explorer will be provided. Primis integrates all Dapps in the Web3 world and interacts Dapps with blockchains through a simple operation interface. 

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying?

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] I have read and understood the [FAQs](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md), [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md) and [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).
- [ ] I prefer the discussion of this application to be in a private Element/Matrix channel. My username is: ``@Andy-Meta``

### How Did You Hear About our grants program?

- [x] Social Media
- [ ] Hackathon
- [ ] Personal Recommendation
- [ ] Substrate Builders Program
- [ ] Investor/VC
- [ ] Online Search
- [ ] Other: _______

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. But it’s currently missing a lot of technical details. For example, are you leveraging ink! or substrate for your project? What exactly are the unique features of your “web3 desktop”? What doesn’t exist already in the ecosystem, etc.? Also 
deliverables 0a-0d of the template are mandatory for all milestones.

**Comment by cruikshankss** [comment]
Hi @Andy-Meta, I'm pretty new at reviewing incoming applications and I accidentally overlooked that you checked off "private discussion". I'm working on setting that up ASAP. Sorry for my mistake.

**Comment by Andy-Meta** [comment]
> Thanks for the application. But it’s currently missing a lot of technical details. For example, are you leveraging ink! or substrate for your project? What exactly are the unique features of your “web3 desktop”? What doesn’t exist already in the ecosystem, etc.? Also deliverables 0a-0d of the template are mandatory for all milestones.



> Hi @Andy-Meta, I'm pretty new at reviewing incoming applications and I accidentally overlooked that you checked off "private discussion". I'm working on setting that up ASAP. Sorry for my mistake.
That's ok, you can re-open it, and we can keep communicating publicly.

**Comment by Noc2** [comment]
Thanks for the reply. However, we are looking for a lot more technical information and concrete technical details when it comes to the application. For example, what actually is the supported functionality of your Primis wallet, which programming languages are you going to use, which networks are you going to support etc. Also according to the slides it looks like you don’t plan to use our tech stack or develop anything related to our ecosystem. So, I’m closing the application for now. Let me know if I should reopen it.

**Comment by Andy-Meta** [comment]
> 

ok, we will update what you mentioned.

**Comment by Andy-Meta** [comment]
> Thanks for the reply. However, we are looking for a lot more technical information and concrete technical details when it comes to the application. For example, what actually is the supported functionality of your Primis wallet, which programming languages are you going to use, which networks are you going to support etc. Also according to the slides it looks like you don’t plan to use our tech stack or develop anything related to our ecosystem. So, I’m closing the application for now. Let me know if I should reopen it.

ok, we will update what you mentioned.

**Comment by Andy-Meta** [comment]
@Noc2 @cruikshankss Hi, we have updated our application contents after some discussion and come up with customized solutions for Polkadot Eco. Of course, we have added the technical details you mentioned. You can check this [updated MD file.](https://github.com/Andy-Meta/Grants-Program/blob/master/applications/Primis.md) If you need any other requirements to re-open this pull request, please let us know when you are available, thanks.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. But your milestones are still very abstract and don’t have a lot of details. Additionally, as I said before, deliverables 0a-0d of the template are mandatory for all milestones (see https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#milestone-1-example--implement-substrate-modules).

**Comment by Andy-Meta** [comment]
> Thanks for the update. But your milestones are still very abstract and don’t have a lot of details. Additionally, as I said before, deliverables 0a-0d of the template are mandatory for all milestones

@Noc2 Got it, we will update the details of the milestones asap, including the deliverables 0a-0d. Appreciate your quick reply!

**Comment by Andy-Meta** [comment]
> Thanks for the update. But your milestones are still very abstract and don’t have a lot of details. Additionally, as I said before, deliverables 0a-0d of the template are mandatory for all milestones (see https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#milestone-1-example--implement-substrate-modules).

@Noc2 hi, we updated the MD file about the details of Milestones (https://github.com/Andy-Meta/Grants-Program/blob/master/applications/Primis.md) and attached some Primis Desktop interface preview.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. A reminder that you still need to sign our Terms and Conditions (see CLA bot above). Apart from this, my recommendation would be to initially apply only for the first milestone for 10k. This would mean you only need 2 approvals and I personally would be willing to go ahead with it (first milestone for 10k). Additionally it gives you the opportunity to deliver the electro app and show the rest of the committee that it’s useful. After this you could apply for a follow-up grant. What do you think?

**Comment by Andy-Meta** [comment]
> Thanks for the update. A reminder that you still need to sign our Terms and Conditions (see CLA bot above). Apart from this, my recommendation would be to initially apply only for the first milestone for 10k. This would mean you only need 2 approvals and I personally would be willing to go ahead with it (first milestone for 10k). Additionally it gives you the opportunity to deliver the electro app and show the rest of the committee that it’s useful. After this you could apply for a follow-up grant. What do you think?

@Noc2 Thanks, Primis Team is willing to adopt your suggestion about Milestone 1 for 10k. I have updated the cost of Milestone 1 in the MD file to 10k. Primis Team also appreciates the opportunities to present to the committee and have Follow-up Grant. Let's get started, anything that we should do in the following steps, plz let us know.

**Review by Noc2 — CHANGES_REQUESTED** [review]
That’s great to hear. Could you update the application accordingly? (Update the total costs to 10k, update the level at the beginning and remove milestone 2, 3 and 4)  Thanks!

**Comment by Andy-Meta** [comment]
> That’s great to hear. Could you update the application accordingly? (Update the total costs to 10k, update the level at the beginning and remove milestone 2, 3 and 4) Thanks!

@Noc2 Hi, Noc2, I already updated the total cost, level and removed milestone 2, 3 and 4.

**Review by Noc2 — APPROVED** [review]
Perfect. Thanks a lot. I’m happy to go ahead with it.

**Review by gautamdhameja — APPROVED** [review]

**Comment by Andy-Meta** [comment]
> Congratulations and welcome to the Web3 Foundation Grants Program! Please refer to our [Milestone Delivery repository](https://github.com/w3f/Grant-Milestone-Delivery/) for instructions on how to submit milestones and invoices, our [FAQ](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md) for frequently asked questions and the [support section of our README](https://github.com/w3f/Grants-Program/blob/master/README.md#support) for more ways to find answers to your questions. Before you start, take a moment to read through our [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md) for all communications related to the grant or make them known to the right person in your organisation. In particular, please don't announce the grant publicly before at least the first milestone of your project has been approved. At that point or shortly before, you can get in touch with us at [grantsPR@web3.foundation](mailto:grantsPR@web3.foundation) and we'll be happy to collaborate on an announcement about the work you’re doing. Lastly, please remember to let us know in case you run into any delays or deviate from the deliverables in your application. You can either leave a comment here or directly request to amend your application via PR. We wish you luck with your project! 🚀

@Noc2 @gautamdhameja Appreciate your guys' interest and trust in Primis, we will try our best to complete Milestone 1 on time.

**Pull request merged**
