### PR TITLE
Add rlink.md

### PR DESCRIPTION
**Pull request by Rlinkwork**
### Project Abstract
Rlink is the world's first oracle that completely realizes decentralized recommendation relationship and rebate. Rlink want to realized the whole process of recording the reference relationship on the smart contract and making chain rebates according to the reference relationship. 

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Could you clarify the programming language as part of the specification of the deliverables? Something you should be aware of, is that we usually don’t fund the development of solidity smart contracts. The reason is that we are no experts when it comes to solidity and it’s very difficult to judge what is new and what does already exist at this point. Also could you specify the different (substrate?) modules more concretely? On your website you even link to an audit report. Do you already have code or a specification for the modules which you could share?

**Comment by Rlinkwork** [comment]
Thanks for your reply. Actually, we have realized the basic function of decentralized recommendation relationship and rebate by solidity. we use solidity firstly because we want to know whether we can realize those functions technically, EVM is more convenient. As we said from this proposal, we will build a parallel chain for the Polkadot ecosystem. This is the link of some source code for solidity: https://github.com/Rlinkwork/rlink
we also can convert to another programming language if your fund need. We will be very pleased to listen to you if you have other comments or something confused about Rlink

**Comment by Rlinkwork** [comment]
> Thanks for the application. Could you clarify the programming language as part of the specification of the deliverables? Something you should be aware of, is that we usually don’t fund the development of solidity smart contracts. The reason is that we are no experts when it comes to solidity and it’s very difficult to judge what is new and what does already exist at this point. Also could you specify the different (substrate?) modules more concretely? On your website you even link to an audit report. Do you already have code or a specification for the modules which you could share?

**Comment by Rlinkwork** [comment]
> Thanks for the application. Could you clarify the programming language as part of the specification of the deliverables? Something you should be aware of, is that we usually don’t fund the development of solidity smart contracts. The reason is that we are no experts when it comes to solidity and it’s very difficult to judge what is new and what does already exist at this point. Also could you specify the different (substrate?) modules more concretely? On your website you even link to an audit report. Do you already have code or a specification for the modules which you could share?

Thanks for your reply. Actually, we have realized the basic function of decentralized recommendation relationship and rebate by solidity. we use solidity firstly because we want to know whether we can realize those functions technically, EVM is more convenient. As we said from this proposal, we will build a parallel chain for the Polkadot ecosystem. This is the link of some source code for solidity: https://github.com/Rlinkwork/rlink
we also can convert to another programming language if your fund need. We will be very pleased to listen to you if you have other comments or something confused about Rlink

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the reply. In this case I recommend either using ink! Smart contract or pallets for your application. Maybe the following the post helps you to decide which one you want to use:  https://stackoverflow.com/questions/56040779/when-should-i-build-a-substrate-runtime-module-versus-a-substrate-smart-contract Do you already have any solitidy contracts regarding the deliveries you describe as part of the grant? For example regarding Address relation or Distribute. In this case, could you link to the solidity version. In any case, could you update the application accordingly?

**Comment by Rlinkwork** [comment]
> Thanks for the reply. In this case I recommend either using ink! Smart contract or pallets for your application. Maybe the following the post helps you to decide which one you want to use: https://stackoverflow.com/questions/56040779/when-should-i-build-a-substrate-runtime-module-versus-a-substrate-smart-contract Do you already have any solitidy contracts regarding the deliveries you describe as part of the grant? For example regarding Address relation or Distribute. In this case, could you link to the solidity version. In any case, could you update the application accordingly?

Thanks for your reply and your advice. We will consider your recommendations carefully. This is the link of some source code for solidity: https://github.com/Rlinkwork/rlink, you also can try the demo dapp of Rlink: main.rlink.link

**Comment by mmagician** [comment]
Closing due to inactivity. Feel free to re-open the application with a more complete proposal.

**Comment by Rlinkwork** [comment]
Hello web3 team， We were waitng for your checking codes and we do not know what we need to do.We are sorry to find this issue now. Please keep touch our team  again and reopen this proposal.
@alxs @mmagician @Noc2

**Pull request closed without merging**
