### PR TITLE
add universaldot application

### PR DESCRIPTION
**Pull request by JosephKnecht-lab**
### Project Abstract

A freelancing decentralized application (dApp) that allows individuals to create/complete tasks and organize themselves by creating geographically distributed organizations. 

The creation of Bitcoin allowed for easy exchange of digital tokens of value. Currently, value is created in the real world and exchanged in the digital world. Our dApp allows for digital creation of value in addition to digital exchange of value.

This dApp will be developed using Substrate. New pallets will create the business logic layer which will allow users to directly interact with each other using tasks. 

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Comment by semuelle** [comment]
Hi Joseph, thank you for your application! We will look into it as soon as possible.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application and sorry for the late reply here. Did you consider using ink! Smart contracts for the project instead of pallets? Also did you consider using the [identity pallet](https://github.com/paritytech/substrate/tree/master/frame/identity) for profiles, the [bounties pallet](https://github.com/paritytech/substrate/tree/master/frame/bounties) for tasks and potential leveraging some of the exiting work regarding daos, see https://github.com/w3f/Grants-Program/blob/master/docs/polkadot_stack.md? How is your solution different from these existing solutions?

**Comment by JosephKnecht-lab** [comment]
Hi David. Thanks for your response. 

Initially, we considered creating ink smart contracts, but the business logic we intend to implement within the pallets is more appropriate to be implemented on the protocol level. Also, since this dApp is intended to be a large-scale implementation, it needs to be implemented on a separate blockchain that eventually may become a Polkadot parachain. 

The pallets you have mentioned have been useful. Here are the main differences that we foresee:
- The substrate Identity pallet relies on third-party registers to validate one's identity. In our Profile Pallet implementation, identifying is self-sovereign. Also, our Profile Pallet must have custom metadata attached to each AccountID (such as reputation points, interests, etc). This profile metadata will be currently added to Blockchain storage, but eventually might be hashed and stored in IPFS.
- The Substrate Bounties pallet requires permission from the council, curator as intermediaries. Our implementation will offer a direct exchange of value between producer and consumer. This implies that anyone who has a Profile can create tasks and complete them. The fee for task creation will be used as a financial incentive not to spam the network, but other than that we allow free exchange of value/information.
- DAO’s in the first initial implementation will be formed around a common vision. DAO’s create a bundle of related tasks that help fulfill the larger vision. In the later iteration of the project (beyond the scope of the current grant) we intend to implement a Deep Learning Layer that Automates most of the repetitive organizational work. In other words, Organisations must eventually become autonomous. 

Additionally, our dApp will abstract out all or most blockchain-specific knowledge. We consider that most current dApps have low adoption due to the large technical knowledge regular users must have before interacting with these dApps. Our front-end implementation intends to simplify the interaction so that users that have zero knowledge of blockchain can interact with our application.

Let me know if you have further questions.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the detailed reply and sorry for the late reply. Could you try to integrate this also into the application? How does your reputation system work? This seems to be an important component of your system. And would you also be willing to add weights for all three pallets as milestone 1? (for example delivery: Weight estimation: provide reasonable weight estimations, e.g., using benchmarking.) Regarding milestone 2, could you potentially reduce the price a little bit, since this delivery will be less useful for other teams in our ecosystem.

**Comment by JosephKnecht-lab** [comment]
Hi David.. thanks for your feedback.

 Regarding the reputation system, each profile will have reputation points which are awarded for completing tasks. The initial reputation will rely on a linear model where users are rewarded reputation points for completing tasks successfully and slashed reputation points for undertaking tasks without completing them. Also, users will be awarded reputation points for creation DAO’s which have large user participation as well. As I mentioned, the initial implementation will use linear functions for increasing/decreasing reputation points. Reputation points unlike utility tokens are non-transferable, and belong to each Profile as long as the Profile exists. 

We will include benchmarking in the delivery for the first milestone. We are currently adding 10_000 weight to each extrinsic + additional weight based on the number of read/writes inside the extrinsic function. I don’t see an issue doing proper benchmarking for the delivery of the pallets in the first milestone. I will update the application Readme to reflect this. 

I will reduce the second milestone cost in the application by 2,000 USD. These costs will be incurred by the UniversalDot foundation. 

Let me know if there are further questions.

**Comment by JosephKnecht-lab** [comment]
Thanks David. 

As we develop more and more functionality, there might be a need to extract some of the common functionality into separate pallets that can be reused within the main pallets. For example, currently, we manage permissions in each pallet separately but if we can loosely couple that functionality, we can create a new Permission pallet that can be used for Profiles, Tasks, or DAO's. Permission Pallet will then become a supporting pallet.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks again for the quick reply. To be honest, I still think that your application is a little bit expensive given the usefulness and scope. That’s why I haven’t approved it yet. Would it be possible to reduce the price to 35k?

**Comment by JosephKnecht-lab** [comment]
Hi David,

I reduced the price to 35k. Also, the number of FTE's is reduced to 2,5 for the second milestone. We will try to improve the User Experience with the knowledge already available within the team and won't be hiring an external UI expert.

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I’m happy to go ahead with it.

**Review by semuelle — COMMENTED** [review]
I'm generally happy to support this. Just a few minor questions:

- Can you explain what you mean by "Transfer of intellectual property through task creation/completion"?
- What are the permissions mentioned in the use case diagram?
- Have you thought about how disputes would be settled on your platform?
- There are not `edit_task` or `remove_task` functions, is that on purpose? 
- How is the UI going to simplify interaction with the blockchain ("Our front-end implementation intends to simplify the interaction so that users that have zero knowledge of blockchain can interact with our application.")? They still need a wallet and sign transactions, right?

> The substrate Identity pallet relies on third-party registers to validate one's identity.

I just want to point out that you could still retrieve identity information on the UI level from chains using the identity pallet.

**Comment by JosephKnecht-lab** [comment]
Hi Sebastian,

Below you can find the answers to your questions…

* Can you explain what you mean by "Transfer of intellectual property through task creation/completion"?
    * Suppose I want someone to write a personalised poem for me. I will create a task with my requirements and budget. Some poet will write my poem and will receive the budgeted amount. With that transfer he has transferred his intellectual property(the poem) to me and I will have the rights to use it. Of course, there might be some cases in which the intellectual property of a task might stay with the creator, but those can be negotiated between the people who create and complete tasks.
* What are the permissions mentioned in the use case diagram?
    * We foresee that most of the functionality for profile, tasks and DAO’s has to do with who has permissions to do what. Instead of placing that functionality inside each pallet, we wanted to abstract it out and create separate pallet that only deals with permissions. We would like to consult with some developers from the builders program if this is a good design decision. 
* Have you thought about how disputes would be settled on your platform?
    * This is a great question. In the first milestone, disputes are expected to be settled between people who create and complete tasks. On a protocol level, when someone creates a tasks, we will reserve his funds so the funds become unspendable until the task has been completed. Upon completion, the reserved funds are transferred to the person who completed the tasks. In this manner both the task creation and task volunteer are incentivised to resolve internal disagreements. On a protocol level, we increase reputation to profiles that acted with integrity, meaning successfully create and complete tasks. 
    * In a future iteration of this project, we foresee that some disputes cannot be resolved internally and would require a third party to adjudicate disputes. Then we will design a proper way to handle disputes. For example, we can select a user at random to review and resolve the dispute for a small fee.  
* There are not edit_task or remove_task functions, is that on purpose?
    * We read that the Milestone description is a binding agreement for delivery, so we included the minimal functions that we will deliver. We already include more functionality in the task pallet, which you can review here: https://github.com/UniversalDot/pallets/blob/master/task/src/lib.rs 
* How is the UI going to simplify interaction with the blockchain ("Our front-end implementation intends to simplify the interaction so that users that have zero knowledge of blockchain can interact with our application.")? They still need a wallet and sign transactions, right?
    * Yes, they would still need a wallet and sign transaction. We intend this application to be used by large non-technical audience, so we intend to make the UI as simple as possible. Our current mockup is in indication of how the UI could look like: https://github.com/UniversalDot/documents/blob/master/designs/documents/UniversalDot%20Prototype.pdf 

Let me know if you have any further questions.

**Review by semuelle — APPROVED** [review]
Thanks for the reply. I'm a bit worried a dispute and reputation system that doesn't reflect the complexities that can arise will frustrate users, so I'd focus on doing that well and possibly, at least partially, on-chain so anyone can verify. But a simplified first version as part of this grant makes sense.

**Review by BenWhiteJam — APPROVED** [review]
Interesting to see, I would also highly recommend, or at least consider the potential use of an identity specific chain/service integration long-term. I see it might be a blocker mid-term, but it should be at least possible.

**Pull request merged**
