### PR TITLE
Nft 2.0 (PSP) Grant Application

### PR DESCRIPTION
**Pull request by 0xMarkian**
#### Project Abstract

In the current landscape majority of projects use Erc721, which we believe is largely outdated and limited. While some of developers already see NFT as something more than an image, an image is still the root property of Erc721. For proper DApp development, and each project introduces new primitives and features. It makes interoperability between different NFT projects more complicated.

Our goal is to define and implement an extensible NFT standard(PSP), which will unify and standardize all NFT use cases defining their own new extensions for specific use cases.
The standard takes into account features already invented by different projects. The standard will gather them together, make them more generic, and treat them as extensions of the NFT. It will also have its own features to support cross-chain compatibility, provide API for extension management, and define rules for future additions to the standard.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (aUSD/USDT) address for the payment of the milestones is provided in the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@0xmarkian:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by avirajkhare00** [comment]
Hey @0xMarkian, I was onto something like this: https://github.com/w3f/Grants-Program/pull/1192

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the new application, and sorry for the delay because of Christmas. I will mark the application already as ready for review to also get additional feedback from others. But I personally won’t approve it yet, mainly because I think you should first focus on some of the other five [outstanding grants](https://github.com/w3f/Grants-Program/blob/master/applications/index.md). We usually ask teams to finish one grant before we sign another one, and already made quite a few exceptions in your case. Also, something I would like to point out here, which caused a little bit of confusion in the past, is that ultimately a standard on a decentralized blockchain is defined on the chain by adoption and usage and not via the PSP process, which is currently barely used. 
Finally, I have a question are you aware of the [NFTs 2.0](https://github.com/paritytech/substrate/pull/12765) initiative by Parity and how does this compare to your solution?

**Comment by 0xMarkian** [comment]
Hey @Noc2! thanks a lot for replying during the holiday season. Appreciate that!

I am of a different opinion about PSP being barely used. Out PSPs for fungible and non-fungible are widely used across different projects and L1s. Astar, AlephZero, (any ink! parachain practically), Subwallet, etc. I think we have around 30-40projects & 100-200 active ink! developers and everyone is using PSP22 and PSP34. Openbrush is used in every serious ink! project and it uses them under the hood. I believe Polkadot ecosystem needs standards, as they are required for everyone to agree on the same interface. As without standard every project will develop its own way as we see right now is happening. There is no good reason for everyone to use RMRK standard since it's their proprietary, not community standard. So I agree with 100% that standards should be defined in a decentralized manner however it seems to me we don't have an efficient way to do it on-chain as of right now. Perhaps we should implement it. In the meantime, I think PSPs can serve their purpose and gain popularity as we have seen was the case with ERCs. 

Also, thanks for the link to Parity's solution, I will see if our team has seen and taken it into account in this proposal.

**Comment by Noc2** [comment]
Thanks for the reply. Just to clarify: I didn’t want to say that the PSP process isn’t useful, I just wanted to point out that the process at the moment doesn’t automatically result in a standard that needs to be used by everyone. Often only a single team contributes to a specific PSP at the moment. If, for some reason, the community decides to use another implementation instead, this would become the de facto standard, not the PSP.

**Comment by 0xMarkian** [comment]
yes, that's totally clear and it makes sense. We expect nothing else and understand the importance of adoption. We are planning to have an implementation of it done in Openbrush which will ensure the popularity of this PSP in the smart contracts world. We also plan to involve other teams that are already in the NFT field in the table of discussion. I believe there are many stakeholders and would be beneficial for everyone to agree on a common standard which is the purpose of PSP. 
as for your other comment - we should finish typechain grant soon, I hope delivery will be accepted this week, also Openbrush and sol2ink grants are to be finished in this month. And we already have work in progress for the NFT 2.0. So would be really glad to move the application process forward if possible. Thanks!

**Comment by 0xMarkian** [comment]
sure, I am okay with what makes sense for you. But I think we have only 3 outstanding grants, not five :)

**Review by takahser — CHANGES_REQUESTED** [review]
@0xMarkian thanks, in general I'm all for creating an NFT standard that combines features that are already used by other implementations with new, potentially useful functionality.
However, I have a couple of points to make and questions to ask.

1. From reading your application it doesn't become clear, what these features would be. Example:

    > We will create a new PSP for NFT 2.0 and optimize it to reflect possible requested changes and improvements.

    It would be nice if you could enhance your proposal with additional details, so the vision for this grant becomes clearer.
2. Also, I think @Noc2's [question](https://github.com/w3f/Grants-Program/pull/1390#pullrequestreview-1230113565) regarding Parity's [Nft 2.0](https://github.com/paritytech/substrate/pull/12765) and its relation to this grant wasn't answered. Since this is a quite elementary question, I'd suggest you even add it to your proposal, so it becomes clear to any future reader that you're aware of it and how you're planning to complement it.
3. Furthermore, I agree with @Noc2 on the fact that you currently have a lot of outstanding grants and it might be difficult to reach enough approvals for that reason.
4. In deliverable 2 you say:
    > We will implement the NFT 2.0 standard once the PSP is accepted as part of Openbrush.

    Does this mean that the standard is aimed at ink! smart contracts? Or could they be used outside the contracts pallet on a parachain level?
5. Finally, I have a specific question: Are you planning to support ERC-1155-type that supports semi-fungible tokens?

**Comment by 0xMarkian** [comment]
Hey @takahser 
thanks a lot for a thorough review. And let me get back to you with answers soon!

**Comment by Noc2** [comment]
I'm closing this due to inactivity for now. Let me know once I should reopen it. In general, it might make sense to also apply for treasury funding with these initiatives since this is something that the treasury should support.

**Pull request closed without merging**
