### PR TITLE
Swanky suite grant proposal

### PR DESCRIPTION
**Pull request by hoonsubin**
### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

The Swany Suite is an all-in-one WASM smart contract development environment that aims to unify and streamline the Parity WASM smart contract development within the Polkadot ecosystem. With this tool, we aim to create the best WASM developer experience that can compete with the developer environment from Ethereum, Near, and Cosmos.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying?

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] I have read and understood the [FAQs](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md), [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md) and [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md).
- [ ] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).
- [ ] I prefer the discussion of this application to be in a private Element/Matrix channel. My username is: ``@hoonsubin``

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] Hackathon
- [x] Personal Recommendation
- [ ] Substrate Builders Program
- [ ] Investor/VC
- [ ] Online Search
- [ ] Other: _______

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. I have a few initial comments/questions: 

- I guess the main discussion point of this application will be that we usually don’t give grants to teams that have done a successful token sale for the purpose of the grants, see our [guidelines](https://github.com/w3f/Grants-Program#guidelines)  “We do not award grants for projects that have been the object of a successful token sale.”, with Astar being focused on smart contracts and having their own [Builders Program](https://github.com/AstarNetwork/builders-program). Maybe we can discuss this during a call. Feel free to reach out to grants@web3.foundation My first response would be that some kind of co-funding would make more sense here. Maybe even together with another parachain.  
- Apart from this, the sections at the beginning of the application still seems to be missing some information or seems to have information that can be removed, like “Payment Address: TODO - BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) payment address. Please also specify the currency. (e.g. 0x8920... (DAI))”. Could you clean this up? 
- And deliverables 0a-0d of the [template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) are mandatory for all milestones, and deliverable 0e at least for the last one.

**Comment by hoonsubin** [comment]
> Thanks for the application. I have a few initial comments/questions:
> 
> * I guess the main discussion point of this application will be that we usually don’t give grants to teams that have done a successful token sale for the purpose of the grants, see our [guidelines](https://github.com/w3f/Grants-Program#guidelines)  “We do not award grants for projects that have been the object of a successful token sale.”, with Astar being focused on smart contracts and having their own [Builders Program](https://github.com/AstarNetwork/builders-program). Maybe we can discuss this during a call. Feel free to reach out to [grants@web3.foundation](mailto:grants@web3.foundation) My first response would be that some kind of co-funding would make more sense here. Maybe even together with another parachain.
> * Apart from this, the sections at the beginning of the application still seems to be missing some information or seems to have information that can be removed, like “Payment Address: TODO - BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) payment address. Please also specify the currency. (e.g. 0x8920... (DAI))”. Could you clean this up?
> * And deliverables 0a-0d of the [template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) are mandatory for all milestones, and deliverable 0e at least for the last one.

Thank you for your comment.

For points 2 and 3, it seems like it got slipped after several editing by multiple people 😅 I will fix it in a couple of days.

For point 1, I wasn't aware of that condition. Nevertheless, we want this project to be spread throughout the Dotsama ecosystem, and we've talked with Phala for supporting us too on Swanky. In that regard, I love the idea of onboarding other parachain projects to Swanky. Having said that, the exact method for kickstarting the project (either co-funding or through a grant) is something I will have to discuss with our team and Supercolony.
I'll get back to you on this point later!

**Comment by SotaWatanabe** [comment]
Hello, @hoonsubin @cruikshankss Thank you for the information above, and appreciate your follow-up. Based on the information, I have some questions and comments. Regarding point 1, to be clear, we have never raised funds **for the purpose of the grants**. In addition to that, some successful projects that raised funds like [Moonbeam got funded by Web3 Foundation in June](https://moonbeam.network/announcements/web3-foundation-grant-for-custom-parachain-staking-pallet/). If the above sentence is true, how could you explain this?

Lastly, this is a joint proposal between Supercolony and Astar. If the foundation does not award grants for projects that have been the object of a successful token sale, this problem will be solved if we submit this proposal under Supercolony's name logically speaking.

**Comment by Noc2** [comment]
@SotaWatanabe Thanks for the reply. You are right, moonbeam/purestake (2 grants) and especially Astar/Stake technologies (7 grants) received grants from us in the past, see https://github.com/w3f/Grants-Program/blob/master/docs/accepted_grant_applications.md. Nevertheless, the general guideline is correct: “We do not award grants for projects that have been the object of a successful token sale.” as you can see in our [readme](https://github.com/w3f/Grants-Program/blob/master/README.md). However, this guideline is obviously highly subjective and ultimately depends on the opinion of the grants committee members and the web3 foundation council. For example: What exactly was covered by the tokensale and should be funded by the team? I still suggest discussing this during a call, since I believe that this would be a controversial topic for this grant. 

Btw. If only Supercolony applies for the grant, only they are allowed to work on it, since subcontracting without our approval is against our Terms and Conditions.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Followed-up via email

**Comment by hoonsubin** [comment]
Closing this grant as we are planning on moving to on-chain funding mechanisms (based on our email discussion)

**Pull request closed without merging**
