### PR TITLE
Polkadot light client

### PR DESCRIPTION
**Pull request by vbar**
#### Project Abstract

This is a post-milestone update of https://github.com/w3f/Grants-Program/pull/968 .

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the PR. Could you change the original file so that it is easier to see the changes that you made?

**Comment by vbar** [comment]
> Thanks a lot for the PR. Could you change the original file so that it is easier to see the changes that you made?

Actually I did - on the EQ side there's just a small commit, but the PR created a whole new file... Maybe I should have forked a later version of https://github.com/w3f/Grants-Program ?

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the quick reply. Potentially it’s related to the recent updates to our repo because of the website/docusaurus version that we want to integrate. If it’s not too much work, could you potentially fork the latest version and create another PR?

**Comment by vbar** [comment]
> could you potentially fork the latest version and create another PR?

OK, closing this one.

**Pull request closed without merging**
