### PR TITLE
pallet-drand-client application

### PR DESCRIPTION
**Pull request by random-ham**
#### Project Abstract

Current sources of verifiable randomness in Substrate are limited, and developers need to rely on deriving randomness themselves, or by taking it from BABE. Both of these sources contain randomness that is always derived from information *within* the network. Another approach is to take randomness from an external source, if that source can be proven to be secure. One such source could be a trusted [drand](https://drand.love/about/) (decentralised randomness beacon), which allows the participants "to produce collective, publicly verifiable, unbiased, unpredictable random values at fixed intervals". This is what is being used by the [League of entropy](https://en.wikipedia.org/wiki/League_of_entropy).

This application shows our interest in implementing a drand client as a Substrate pallet. Details can be found in our Markdown application. 

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, **Ethereum** (USDT/**USDC**/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. This is actually something we discussed quite some time ago. Are you also in contact with protocol labs/filecoin? We discussed this previously with them directly and could theoretically involve them in the project. Would it be possible to share some additional information about your previous work either here or via email (david@web3.foundation)?

**Comment by random-ham** [comment]
> Are you also in contact with protocol labs/filecoin? We discussed this previously with them directly and could theoretically involve them in the project.

We're not in contact with them, but we'd love to have them involved in the direction and scoping of this for a variety of reasons. That said, we would like be the primarily implementors of at least the first iteration of this, from a personal development and grant recipient perspective.

> Would it be possible to share some additional information about your previous work either here or via email ([david@web3.foundation](mailto:david@web3.foundation))?

If we're in the right ballpark regarding the project scope and grant amount, and previous work experience proves to be satisfactory, @random-bacon suggested we start with adding you and/or the rest of the grants team to our private repos, as we've already started the implementations of the client and pallet/node. Thoughts?

**Comment by CluEleSsUK** [comment]
hey! I work for protocol labs on the drand team and would love to hear more/help out where I can.

**Comment by Noc2** [comment]
@random-ham sounds good, feel free to add me to the repo. The grant application looks pretty good and to be honest, I think we can get this approved in the coming days/weeks.

**Review by Noc2 — APPROVED** [review]
Thanks for the invite. I’m happy to approve the application and share it with the rest of the team.

**Review by alxs — APPROVED** [review]

**Review by keeganquigley — APPROVED** [review]

**Comment by CluEleSsUK** [comment]
@random-ham I don't see any contact details on your github profile so i'll post here: drand has a slack workspace - if you have any questions or want to discuss any of the details, feel free to join: https://join.slack.com/t/drandworkspace/shared_invite/zt-1il4cggya-u~6xaE7aO~RzVMck6bQjjg

**Comment by random-ham** [comment]
Hey @Noc2 , please check the `master` branch of `drand-substrate-client` for our submission for the Milestone 1 requirements.

**Comment by Noc2** [comment]
@random-ham Thanks for pinging me here. But could you officially deliver the milestone here https://github.com/w3f/Grant-Milestone-Delivery Thanks!

**Comment by keeganquigley** [comment]
Hi @random-ham how is milestone 2 coming along?

**Comment by keeganquigley** [comment]
@random-ham friendly ping.

**Comment by keeganquigley** [comment]
Hi @random-ham seeing as there has been no activity on the [drand-client repo](https://github.com/random-meat/drand-substrate-client/graphs/code-frequency) in 5 months, and neither of your personal accounts either, I think it's best that we close the grant and you can open in the future should you want to continue working on it. 

If we don't hear back in a couple of weeks, the committee will file a PR to cancel the grant. Thanks for your work so far and let me know if you have any questions.

**Pull request merged**
