### PR TITLE
[Aviraj] Added Ink Boxes follow up grant

### PR DESCRIPTION
**Pull request by avirajkhare00**
#### Project Abstract

We are introducing NFT marketplace Ink Box as part of Ink Boxes. People will be able to spin up their own ink box fast.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (aUSD/USDT) address for the payment of the milestones is provided in the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by avirajkhare00** [comment]
Hey @Noc2, Merry Christmas. I hope you are doing great.
I have completed the Ink Boxes grant. I have opened up a follow-up grant to create an NFT marketplace separately because creating an NFT marketplace is a huge task.

Can you please take a look at it today, if possible?

Thanks

**Comment by avirajkhare00** [comment]
Just saw the README. Merry Christmas and happy new year :)

**Comment by avirajkhare00** [comment]
@Noc2 , I am having one more doubt. Can I create follow up grants?
If not, I will close this and work on existing grants.

**Review by Noc2 — CHANGES_REQUESTED** [review]
To be honest, my recommendation would probably be to close it for now and first finish your outstanding grants. I was going to ask @0xCaso to take a look at it since he wasn’t super happy with your initial deliveries. So if you finish your other grants first, you can also make a better case for why we should support this one.

**Comment by avirajkhare00** [comment]
Sure. I will close this grant for now. Since I have money now, I will hire a front-end developer to make the website more pretty.

**Pull request closed without merging**
