### PR TITLE
Create Shivarthu.md

### PR DESCRIPTION
**Pull request by amiyatulu**
# Grant Application

## Abstract

> Provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous one, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.
>
> The details should be in the application document that is being added to the repository via this pull request.

## Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] The total funding amount of the project is below USD $30k for first-time grant applications and $100k for follow-up ones.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Sorry for the late response here. The formatting of your application seems to be off, could you please fix this? Also see “Deliverables 0a-0d are mandatory for all milestones, and deliverable 0e at least for the last one. If you do not intend to deliver one of these, please state a reason in its specification (e.g. Milestone X is research oriented and as such there is no code to test).” https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#milestone-1-example--implement-substrate-modules Furthermore, I’m not fully sure why you want to use the schelling game for KYC, isn’t the purpose of the schelling game to kind of get rid of the KYC requirement in the first place.

**Comment by amiyatulu** [comment]
@Noc2 Thank you for the comment. I have updated my application by fixing the formatting and adding deliverables 0a-0d in new commit. Schelling game is for evaluation of representative evidence of experience not KYC. One can't become a representative without some experience.

**Comment by Noc2** [comment]
Thanks for the update and the quick reply. Do you already have some mock-ups/initial designs for the UI, which you could share?

**Comment by amiyatulu** [comment]
@Noc2 Thanks for the reply, I have added a few rough mock-ups for the UI, these are not the exact designs, exact designs will have much more details and will look better with css framework like bootstrap.

**Comment by Noc2** [comment]
Thanks for the update. I will share the application with the rest of the team. However, given that the UI is quite an important part of the application, I would personally like to see more before accepting the complete project in its current stage. But I would be willing to already only accept milestone 1 and after this potentially sign an additional follow-up grant.

**Review by semuelle — CHANGES_REQUESTED** [review]
Thanks for the application, @amiyatulu. It seems like an interesting idea overall. 

I have two issues: one, your `Future Plans` are what is already covered by this grant application. What we are looking for there is an idea of what you are planning to do after the grant, i.e. how you are going to use or improve the software/material. Given that you would need to onboard a significant number of people for this project to succeed, this should contain field trials, experiments or similar practical work. Second, your third milestone contains marketing, which we don't fund, and an Android app, which I find unnecessary at this point. So, my suggestion would be to remove Milestone 3 (you can always apply for a follow-up grant).

**Comment by amiyatulu** [comment]
@semuelle Thank you for comment. I have removed the Milestone 3. Android app will be needed to onboard more users, but as you said I can apply for follow-up grant.  Thank you again.

**Comment by semuelle** [comment]
> @semuelle Thank you for comment. I have removed the Milestone 3. Android app will be needed to onboard more users, but as you said I can apply for follow-up grant. Thank you again.

The milestone costs and the total cost don't match now. I assume the total should be 20,000.

**Comment by amiyatulu** [comment]
@semuelle Yes, updated.

**Review by semuelle — APPROVED** [review]

**Review by Noc2 — APPROVED** [review]

**Review by Lederstrumpf — APPROVED** [review]

**Comment by Noc2** [comment]
For future reference, I just moved the file to the correct folder: https://github.com/w3f/Grants-Program/commit/cd651427b06625cd37e920d844d455f047126f19

**Comment by amiyatulu** [comment]
Thank you for accepting my application.

**Comment by alxs** [comment]
@amiyatulu hey, how is the project coming along? We were hoping to receive your first delivery a bit over 2 months ago. As long as you're actively working on the project, delays aren't a big problem, but please keep us in the loop.

**Comment by amiyatulu** [comment]
Hi @alxs I am actively working on the project. I have converted sortition sum tree to rust for schelling game.  Substrate has a huge learning curve, also I shifted to frame 2, so its taking time to grasp how to do the things. I am working and also asking for help to the substrate developer in stackoverflow where ever I have a doubt.

**Pull request merged**
