### PR TITLE
Demand Abstraction Based on Intent-centric and AI Agent.md

### PR DESCRIPTION
**Pull request by mryings**
#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).

Empowered by Web3 and AI agents, we enable a better new way of user interaction from Web2 based on Apps to Web3 based on the demand of users called demand abstraction. Users just need to express their needs and then directly get what they want without going through specific Apps by themselves in a fully natural, straightforward and convenient way.

> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) or BTC address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Your first milestone looks similar to https://github.com/w3f/Grants-Program/pull/2007. Could you list a few papers regarding demand abstraction that you want to research as part of the application? Also, we usually don't support the initial research phase of a project.

**Comment by mryings** [comment]
Dear @Noc2:

Thanks for your kindly review and inquiry! Our demand abstraction is based on the concept of intent-centric which is first proposed by [Paradigm](https://www.paradigm.xyz/2023/06/intents), and now many crypto projects, ventures, and communities are doing research to study it like [Anoma](https://anoma.net/blog/an-introduction-to-intents-and-intent-centric-architectures), [Particle Network](https://medium.com/@particleblog?source=post_page-----9989deb70530--------------------------------), [YBB Capital](https://medium.com/ybbcapital?source=post_page-----67f2f0aec25a--------------------------------), [CMCC Global](https://www.cmcc.vc/insights/anoma-and-intent-centric-design). As for the academia, many research has also been done about [intent-based networking](https://scholar.google.com/scholar?hl=zh-CN&as_sdt=0%2C5&as_vis=1&q=intent+based&btnG=), which is similar to intent-centric although it mainly focuses on the area of communication network.  

We have conducted initial industry research and we plan to further dive deep into this space to do more scientific and systematic research, so we apply for your grant. 

Any other questions feel free to ask us. Thanks a lot!

**Review by semuelle — CHANGES_REQUESTED** [review]
Thanks for the application, @mryings. I have a few issues with the application.

1. As David already pointed out, we don't usually fund the intial research phase of a project. 
2. Your main value proposition is an agent that can generate intents/transactions from natural language. I would like to see more details of how this is accomplished before committing funds to this. It's simple to build a parser that converts known phrases to known transactions, but a general purpose agent needs a lot of background knowledge.
3. You are mentioning a lot of complex technical concepts without any details, such as zk proofs. The application needs _a lot_ more details. 
4. Since you are mentioning Partisia: which parts of this grant are Polkadot-specific? I would suggest that you apply for the Polkadot-specific parts with this application.

**Comment by mryings** [comment]
Dear @semuelle:

Thanks for your kindly review and inquiries! We have done some research to write this research proposal and make sure it's feasible and reasonable. We can do more research to dive deep into details after getting funding. We are confident and competent to finish our research and reach our goal, but it takes a lot of work and expenditure, so we need the grant to do so.

Any other questions feel free to ask us. Thanks a lot!

**Review by semuelle — CHANGES_REQUESTED** [review]
Thanks for the reply, @mryings. I understand that this is a research grant you are looking for. However, it currently reads more like a loose collection of vaguely related ideas.
- The proposal you have linked to is completely EVM-centered and I don't see any Substrate/Polkadot-specific research or results. - You have specified delivering a mobile app and an ink! smart contract, but no word on the scope or tech stack. 
- I don't see the phrases "demand abstraction" or "Decentralised AI agent" in the linked proposal. I would expect to find some previous work on these somewhere; if you have any articles, blog posts, research diaries, etc. to share about this, that would help a lot.

**Comment by Noc2** [comment]
I'm closing this application due to inactivity. Let us know if we should reopen it.

**Comment by mryings** [comment]
Dear @semuelle:

Thanks for your review and sorry for the late response as we are investigating your inquiries and applying for blockchain academy. Regarding your critiques:

> The proposal you have linked to is completely EVM-centered and I don't see any Substrate/Polkadot-specific research or results. - You have specified delivering a mobile app and an ink! smart contract, but no word on the scope or tech stack.

We will deploy our project on Polkadot blockchain and Substrate ecosystem. We will support both EVM chains in Solidity and non-EVM chains in Rust. I previously discussed with Tim Dobie when we applied for the blockchain academy and he also fully endorsed our plan.

> I don't see the phrases "demand abstraction" or "Decentralised AI agent" in the linked proposal. I would expect to find some previous work on these somewhere; if you have any articles, blog posts, research diaries, etc. to share about this, that would help a lot.

Our demand abstraction is based on intent-centric, and upgrades intent-centric to support understanding and meeting higher level of user demands via AI agent and AA. For intent-centric, feel free to review: [Intent: The Start of Intelligent Web3 Interactions](https://medium.com/@ACCapital1/en-intent-the-start-of-intelligent-web3-interactions-c10c7a882cf7)
[Intent-Based Architectures and Their Risks](https://www.paradigm.xyz/2023/06/intents)

For AI agent, feel free to review: [Enhancing AI Agents With User-centric Model](https://medium.com/@hexlinkofficial/empower-better-ai-agents-with-web3-3f7c65449953)
[Bill Gates says AI agents will send a "shock wave" through the tech industry](https://the-decoder.com/bill-gates-says-ai-agents-will-send-a-shock-wave-through-the-tech-industry/)

Feel free to review our latest [research proposal](https://drive.google.com/file/d/15GpYINg3rlTnSIkV9HLTTE8kbh8qSg4w/view?usp=sharing). Thanks a lot!

**Comment by mryings** [comment]
Sure @Noc2 please reopen this issue. Thanks a lot!

**Comment by Noc2** [comment]
Thanks for the update and all the effort you put into this. However, the grants committee decided today not to go ahead with the application. Independent of it, we wish you all the best for your project. Let us know if you have any questions.

**Pull request closed without merging**
