### PR TITLE
Evolving OpenGov 

### PR DESCRIPTION
**Pull request by monsieurbulb**
#### Project Abstract

Whilst influential, large ‘public good’ treasuries are just one component in what can be understood as a phased innovation process that should be structured through the full life cycle of R&D, productisation and go to market, with motivations, oversight, rewards and ROI contingent on the phase and the entity involved.

To encourage an innovative culture, we need to understand just how to identify, support and scale that culture through a phased approach that approaches talent, focus and outcomes independently but as part of a cohesive whole, evolving technical, social and meritocratic structures as we go.

The aim of this initial paper is to set context for, and a hopeful path towards a more structured approach to innovation in the ecosystem - beginning at the lowest levels of creative endeavour.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [X] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [X] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`evolving_opengov.md`).
- [X] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [X] Payment details have been provided (Polkadot AssetHub (DOT, USDC & USDT) address in the application and bank details via email, if applicable).
- [X] I understand that 30% of each milestone will be paid in vested DOT, to the Polkadot address listed in the application.
- [X] I am aware that, in order to receive a grant, I (and the entity I represent) have to successfully complete a KYC/KYB check.
- [X] The software delivered for this grant will be released under an open-source license specified in the application.
- [X] The initial PR contains only one commit (squash and force-push if needed).
- [X] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `` (change the homeserver if you use a different one).

### CODE REVIEW

**Comment by monsieurbulb** [comment]
I have read and hereby sign the Contributor License Agreement.

**Review by semuelle — CHANGES_REQUESTED** [review]
Hi @monsieurbulb, thanks for the application. This sounds generally interesting, but I have a few questions/requests:

1. Have you considered requesting funding for this from OpenGov? If not, why?
2. Are you planning to fund the subsequent research through grants as well?
3. Why are you focusing on Kusama only? I'm sure much of it would apply to Polkadot as well.
4. You say that the paper is going to be largely qualitative. I understand that a lot of the work will be hard to measure, but I'd still be interested in at least trying to substantiate the work with data. Perhaps this could be structured beforehand (see next point)?
5. The deliverables are not well defined. The specs of the `0x` deliverables should be adapted to your specific project (you have not mentioned any data or artifacts to be delivered). The remaining deliverables are rather vague. It might make sense to structure these differently, e.g. by separating them into a bibliography, data and analytical tools and resulting paper.

**Comment by monsieurbulb** [comment]
Hi @semuelle thanks for the comment.

> Have you considered requesting funding for this from OpenGov? If not, why?

Short answer Yes. 

However...

I decided to submit this due to @anaelleparity's RFP [Action Research for OpenGov](https://github.com/w3f/Grants-Program/blob/c8617cf42df90fe07a5bfa5c348e889b290dc544/docs/RFPs/action_research_opengov.md)... in conversations with her after she submitted the RFP that W3F preferred to see these go via the treasury as (paraphrasing) _this would give contributors chance to learn about the system on which they are reporting._ 

Ultimately I want to assess the viability of this particular RFP - and indeed learn from the responses from people such as yourself... not to get too meta, but in some ways this proposal is just another active part of 'evolving opengov' paper. 

I've spent an unbroken 5 years deep in the weeds of on-chain governance / treasury funding at decred, edgeware, kabocha, kusama and polkadot with my main curiosity related to how we create more collaborative, productive and sustainable funding environments compared to current incentives/structures/processes and the second order effects they produce on culture, politics and output.

> Are you planning to fund the subsequent research through grants as well?

Perhaps, i wouldn't commit to a single route.

We're launching a new [community oriented stablecoin](https://rfc.decent.partners/t/funding-brale-integration-with-kusama-assethub/57) with Brale on Kusama AH and they are taking their integration fee in KAB, the native token of [Kabocha](https://forum.polkadot.network/t/introducing-kabocha-an-experimental-kusama-parachain-incubated-by-the-edgeware-community/327) (which W3F has a 7.5% stake). The yield from that project is designed to create an alternative funding model to W3F grants and KSM/DOT treasuries, though we do see ways to involve them in the economic opportunity.

> Why are you focusing on Kusama only? I'm sure much of it would apply to Polkadot as well.

Since this is a W3F stablecoin grant, I tend to think more holistically about the behaviour + output, rather than a particular brand narrative - please see [Is Polkadot a brand?](https://forum.polkadot.network/t/is-polkadot-a-brand/3640) for further context. 

Were the grant funded by DOT or KSM directly, then it would ensure the narrative would feature either Polkadot or Kusama more strongly.

Though Kusama and Polkadot are technically similar, they are not technically identical - ie there are different parachains running on each network and the treasuries fund different things, the token holdings are different and ultimately the cultures are different in obvious and non-obvious ways.

> You say that the paper is going to be largely qualitative. I understand that a lot of the work will be hard to measure, but I'd still be interested in at least trying to substantiate the work with data. Perhaps this could be structured beforehand (see next point)?

Well I imagine much of this may come together with existing research that is more quantative that frames current ecosystem orthodoxy. I did a lot of work outlining data around Kusama treasury spending and modelling Coretime income. 

- [Kusama treasury annual spending analysis - 2020 > 2023 (june)](https://forum.polkadot.network/t/kusama-treasury-annual-spending-analysis-2020-2023-june/3264)
- [Kusama historical analysis - spending, coretime demand and treasury ROI](https://forum.polkadot.network/t/kusama-historical-analysis-spending-coretime-demand-and-treasury-roi/3436)

> The deliverables are not well defined. The specs of the 0x deliverables should be adapted to your specific project (you have not mentioned any data or artifacts to be delivered). The remaining deliverables are rather vague. It might make sense to structure these differently, e.g. by separating them into a bibliography, data and analytical tools and resulting paper.

The output is a single paper working title _Evolving OpenGov_ that brings together historical analysis to present a strategic rationale for structuring support and spending across the _full innovation cycle_. 

This is is not theoretical analysis, but pragmatic and actionable work (that we are actioning). In many ways I see this paper  as a way of better communicating the strategy we are currently executing on, allowing a larger group to contribute to what is in effect a grass-roots rethinking of current ecosystem orthodoxy.

Maybe I've misunderstood the deliverables aspect of the grant template - would you like to see this section with more info?

1. 	Consolidate information 	Aggregate existing research
2. 	Structure document 	Outline the structure of the paper
3. 	Complete paper 	Bring together the research into the paper

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. But at the moment the deliverables contain not a lot of details. For example, what kind of existing papers would you aggregate? Also not sure that our grants program should support: “‘thinking in public”. And just to mention it here: an RFP doesn’t necessarily be funded via the grants program. You could also apply for treasury funding with this.

**Comment by monsieurbulb** [comment]
Thanks David.

> at the moment the deliverables contain not a lot of details. For example,
what kind of existing papers would you aggregate?

The RFP I’m responding to relates to action research (ie applied) within
the OpenGov domain which is itself a novel area of analysis.

To be clear on language here, when I reference “existing papers” I’m
considering only those that relate directly to this domain - intrinsic
rather than extrinsic such as academic papers on onchain governance /
voting and the like.

As a long term onchain contributor, researcher and analyst of novel
governance systems, I’m referencing my own work - and indeed those of
participants within these new political arenas.

> Also not sure that our grants program should support: “‘thinking in
public”.

Perhaps this is just semantics, but this means to me open source research
released in public to better understand the systems of which we are part.
It is self referential. All work produced in an opengov analysis capacity
by those operating within its domain are by definition works that seek to
“think ion public”.

> just to mention it here: an RFP doesn’t necessarily be funded via the
grants program.
You could also apply for treasury funding with this.

Yes I’m absolutely aware of that. This submission is in part a test of the
viability of this RFP.



[image: photo]
*Richard Welsh*
Managing Partner, Decent

+447832104148 | ***@***.***

decent.partners | Skype: richardwelsh_81
<#SignatureSanitizer_SafeHtmlFilter_>

**Comment by semuelle** [comment]
> The output is a single paper working title _Evolving OpenGov_ that brings together historical analysis to present a strategic rationale for structuring support and spending across the _full innovation cycle_.
> 
> This is is not theoretical analysis, but pragmatic and actionable work (that we are actioning). In many ways I see this paper as a way of better communicating the strategy we are currently executing on, allowing a larger group to contribute to what is in effect a grass-roots rethinking of current ecosystem orthodoxy.
> 
> Maybe I've misunderstood the deliverables aspect of the grant template - would you like to see this section with more info?

Research grants provided by the Grants Program have always been focused on small, well-defined questions and topics that allow (or rather, require) a thorough description of questions, methods, metrics and expected results. I think the OpenGov RFP also points in this direction. Your current proposal sounds more like a critique, which would be extremely difficult to evaluate. As such, I think it would be better suited for the treasury in its current form.

**Comment by monsieurbulb** [comment]
@semuelle 

> Research grants provided by the Grants Program have always been focused on small, well-defined questions and topics that allow (or rather, require) a thorough description of questions, methods, metrics and expected results. I think the OpenGov RFP also points in this direction. 

I’ll add more detail related here. 

Quoting RFP;

> There is the need for more encompassing, neutral, practical, and actionable case studies of OpenGov’s implementations, which can help establish a feedback mechanism and prioritise future developments for OpenGov.

The challenge with the nature of this framing is that operating within OpenGov is a subjective experience that leads to strategic insights that are by definition opinionated rather than neutral. 

In part, as someone who has lived / worked under the system for a few years, we have an interesting collision where the W3F assess the validity of this experience without being party to it.  

> The current proposal sounds more like a critique, which would be extremely difficult to evaluate. 

This is where the discussion becomes much more interesting - “what metrics matter in OpenGov” is an open question and is a part of the intended output. 

We also connect back into the point of the submission which is a review of the system related to how innovation works. 

How are we to assess the output of the system? 
 
> As such, I think it would be better suited for the treasury in its current form.

Let me do one more round of changes based on your feedback, this is a useful feedback loop for all sorts of reasons.

**Comment by keeganquigley** [comment]
Thanks @monsieurbulb feel free to ping us once we should take another look.

**Comment by monsieurbulb** [comment]
Hey you can close this application - will be approaching this stuff in a
different way going forward.

Thanks for the feedback to date.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the update here. I'm going to close the PR.

**Pull request closed without merging**
