### PR TITLE
Broken link checker

### PR DESCRIPTION
**Pull request by nikw3f**
Broken link checker github action.

### CODE REVIEW

**Review by Noc2 — DISMISSED** [review]

**Review by semuelle — COMMENTED** [review]
Thanks for that, @nikw3f! I tried it out on my own fork and ran into this issue: https://github.com/semuelle/Grants-Program/actions/runs/6224755500/job/16893649946 
Do you know what's might be the issue there?

**Comment by semuelle** [comment]
Next run I got `Validation Failed: {"resource":"Issue","code":"custom","field":"body","message":"body is too long"}, {"resource":"Issue","code":"custom","field":"body","message":"body is too long (maximum is 65536 characters)"}`

Not sure how to address that.

**Comment by nikw3f** [comment]
> Thanks for that, @nikw3f! I tried it out on my own fork and ran into this issue: https://github.com/semuelle/Grants-Program/actions/runs/6224755500/job/16893649946 Do you know what's might be the issue there?

Rerunning will fix the issue.

**Comment by nikw3f** [comment]
> Next run I got `Validation Failed: {"resource":"Issue","code":"custom","field":"body","message":"body is too long"}, {"resource":"Issue","code":"custom","field":"body","message":"body is too long (maximum is 65536 characters)"}`
> 
> Not sure how to address that.

Ah, the number of links are large. Let me take a look.

**Comment by semuelle** [comment]
any updates, @nikw3f?

**Comment by nikw3f** [comment]
Sorry still facing github rate limits. I need some more time.

**Comment by semuelle** [comment]
Can we exclude `/applications` for now? I assume that would help a lot.

**Comment by nikw3f** [comment]
Excluding applications is passing the run https://github.com/nikw3f/Grants-Program/actions/runs/6325671552/job/17177673545

**Review by Noc2 — APPROVED** [review]

**Pull request merged**
