### PR TITLE
Create CESS.md

### PR DESCRIPTION
**Pull request by Cumulus2021**
### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

Cumulus Encrypted Storage System (CESS) is dedicated to develop a new global decentralized cloud data storage platform – a blockchain-based network infrastructure that is transparent, efficient, and equal opportunity to all members of the global community. CESS encourages excess or under-utilized resources as nodes to join CESS’s unrestricted expandable network via the token economy incentive method. Each node joins the CESS peer-to-peer network by contributing data storage resources, computational resources, or network bandwidth. Built on our state-of-the-art virtualization and cloud computing technologies, CESS organizes and manages the participating resources providing clients with secure, high performance, and boundless cloud data storage services. Furthermore, the CESS protocol enables interconnection of network nodes, to build a large decentralized cloud storage system that supports up to 100PB storage scale to meet the demand of enterprise level data storage. CESS will adopt a phased approach to implement the above goals.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Review by mmagician — APPROVED** [review]
Sounds interesting, if perhaps a little ambitious. Good luck!

**Comment by semuelle** [comment]
Hi @Cumulus2021, thank you for the application. Two questions:

1. Who runs the scheduling nodes? Does a scheduling node require some special kind of onboarding (wrt the TEE)?
2. The fingerprinting sounds computationally expensive; where does it take place? Is there some kind of mechanism preventing someone to create fake fingerprints? 
 
Also, even though it's not part of the grant: how are disputes handled in your system? Just because I was the first to upload something, doesn't mean I'm the copyright owner.

**Comment by Cumulus2021** [comment]
> Hi @Cumulus2021, thank you for the application. Two questions:
> 
> 1. Who runs the scheduling nodes? Does a scheduling node require some special kind of onboarding (wrt the TEE)?
> 2. The fingerprinting sounds computationally expensive; where does it take place? Is there some kind of mechanism preventing someone to create fake fingerprints?
> 
> Also, even though it's not part of the grant: how are disputes handled in your system? Just because I was the first to upload something, doesn't mean I'm the copyright owner.

1. In the CESS system, the scheduling node is one of the community nodes, and also participates in the CESS network in a distributed form. However, at present, the design is a server with TEE environment. Generally, the user's computing power is relatively weak, and some calculations need to be performed on the scheduling node. However, in order to prevent data privacy disclosure, data blocking and encryption need to be performed in the tee environment.
2. The data fingerprint is usually calculated on the client, but for nodes without computing power, the scheduling node API interface of cess can also be used. The function of data fingerprint is mainly to confirm the right of data. For each data, CESS system will calculate a similarity hash value and store it in the blockchain system. The person who uploads the data first does not mean that he owns the copyright of the data. Cess network will only provide suggestions on data copyright. However, each uploaded data will see similar or related chain data on the blockchain browser

**Comment by semuelle** [comment]
Thanks for the reply. M3 mentions zk snarks, but it isn't mentioned in your whitepaper. Could you explain where zero knowledge proofs come into play in your system?

**Comment by Cumulus2021** [comment]
> Thanks for the reply. M3 mentions zk snarks, but it isn't mentioned in your whitepaper. Could you explain where zero knowledge proofs come into play in your system?

In CESS system, the real storage node is still the miner. In order to verify that the miner actually stores the data sent by the scheduling node, ZK-snark technology needs to be used. Using this technology, the verifier can complete the data integrity verification without holding the original data, and we use the zero knowledge proof technology to verify the miner's storage capacity space and data capacity space.

**Comment by semuelle** [comment]
Thanks for the reply, and sorry for the slow responses. I am trying to understand the system in detail.

I understand that zk snarks are used to prove the existence of stored data. I suppose what I meant was, how does it work? There are references to zk papers in your whitepaper, but nothing is explicitly mentioned. 

I also have a question regarding the encryption: where does the encryption take place? Do I upload my unencrypted data, and the encryption key is generated on the node(s)? It sounds like there are three copies of my data encrypted with three different keys. Does each of them then re-encrypt the data when I share it? On the other hand, your whitepaper mentions "the user's unique private key". Where is this private key stored?

**Comment by Cumulus2021** [comment]
> Thanks for the reply, and sorry for the slow responses. I am trying to understand the system in detail.
> 
> I understand that zk snarks are used to prove the existence of stored data. I suppose what I meant was, how does it work? There are references to zk papers in your whitepaper, but nothing is explicitly mentioned.
> 
> I also have a question regarding the encryption: where does the encryption take place? Do I upload my unencrypted data, and the encryption key is generated on the node(s)? It sounds like there are three copies of my data encrypted with three different keys. Does each of them then re-encrypt the data when I share it? On the other hand, your whitepaper mentions "the user's unique private key". Where is this private key stored?

Apologies for the delayed response.

1. Once the client data files are uploaded and distributed to storage nodes, CESS performs periodical data integrity verification(The current design is about 24 hours with 17280 block intervals). The integrity verification includes initial data proof generation by storage nodes and periodical verification between verifiers and provers. Due to the limited data storage capacity on the chain and the need to protect data privacy, we use zk-SNARK algorithm. Compare other proof algorithms, zk-SNARK data proof method has advantages of, 1) compressed data proof, 2) fast verification response, 3) data privacy protection, therefore well accommodates our requirements. This algorithm is also used in a large number of blockchain projects, such as zcash and filecoin.
In our implementation, to generate data proof, storage nodes label and re-encode the Merkel Hash tree derived from data files by Stacked-DRG algorithms. Then, based on the metadata provided at initialization stage (including PK, random number obtained from blockchain), storage nodes apply Bellman’s zk-SNARK algorithms, and generate compressed data proof to submit to blockchain. Later on, verifiers can verify the correctness without obtaining the target files.
2. There is only one key for all three copies of a data file. The key is generated by the user and negotiated through Diffie Hellman algorithm. The key is transmitted to the secure execution environment of the scheduling node to prevent key leakage.
Clients can choose data encryption to be performed either by scheduling nodes or by client end software.  Data files are encrypted symmetrically using the unique key. After encryption the encrypted data is  sent to a scheduling node (with TEE environment) for processing. The scheduling node generates data hash tree, multiple file copies and executes data slicing, then submits data proof to the blockchain. Finally,  the data segments are sent to storage nodes to store.
For each copy of a data file, CESS appends a unique randomly generated number as its identity.

Thanks for your time.

**Review by semuelle — APPROVED** [review]
Thanks for the reply. I am happy to go ahead with this.

**Review by mmagician — APPROVED** [review]

**Pull request merged**
