### PR TITLE
Added Node Red project

### PR DESCRIPTION
**Pull request by johnuopini**
#### Project Abstract

The Node Red Client for Polkadot by Zooper Corp is a practical tool designed to simplify the use of blockchain technology. It integrates the Polkadot ecosystem with Node Red, a user-friendly flow-based programming interface. This project is focused on making blockchain interactions straightforward and accessible, especially for those without extensive technical knowledge. Users can track transactions, automate processes, and interact with the Polkadot network more easily. This application is our first request for support under the Web3 Foundation's Maintenance Grants Program and represents an independent initiative developed by Zooper Corp.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [X] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [X] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [X] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) address in the application).
- [X] The software delivered for this grant will be released under an open-source license specified in the application.
- [X] The initial PR contains only one commit (squash and force-push if needed).
- [X] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [X] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@johnuopini:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by johnuopini** [comment]
I have read and hereby sign the Contributor License Agreement.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Could you change the DOT payment to one of the other supported payment options: https://github.com/w3f/Grants-Program#pencil-process? Apart from this, could you add more details to the milestone deliveries, especially regarding the second milestone? The milestones are basically the requirements of our contracts that we need to evaluate. Milestone 2 currently is completely unspecific and could mean anything. It might make even sense to remove it completely for now and later apply for another grant or treasury funding.

**Comment by johnuopini** [comment]
I have addressed following points:

- Added a DAI address
- Added detailed milestones on how the first maintenance year might look like, this is also a maintenance request so the idea is in parallel to also keep fixing bugs and checking for pull requests from other users

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. However, each milestone should have the default deliverables of the template see https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#milestone-1-example--basic-functionality. Because of this, I also recommend to combine milestone 1 and 2. We usually want to have inline documentation to be able to test the delivery. Furthermore, my recommendation would be to initially only apply for a regular grant and apply later for the maintenance part. For example, "Addressing and resolving issues " could mean anything at this stage.

**Comment by johnuopini** [comment]
- Merged milestones
- Consolidate documentation / test tasks into one
- Made milestones compliant with template

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. However, it's still not very specific. For example: " Web3 technologies" could mean anything. The same is true for "basic Node Red nodes". Additionally, all milestones should contain the default deliverables of the template (0.a to 0d.). Could you try to improve the application and add more details?

**Comment by johnuopini** [comment]
Thanks for the feedback, doc was updated:
- Clarified stack
- Added docker to default deliverables
- Clarified objectives

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. I will mark the application as ready for review. However, I'm personally not convinced by the project and the usability. Also, the default deliverables are still missing for milestones 2, 3, and 4! Furthermore, I don't think the Maintenance Grant should be part of this proposal. But maybe the rest of the committee has a different opinion.

**Comment by johnuopini** [comment]
- Added default deliverables
- Clarified maintenance

**Comment by keeganquigley** [comment]
Thanks @johnuopini for all your time and effort in making the changes to the application. I must agree though, that I'm also not convinced about the usability of the project. Node Red is cool, but it seems that you'd need to use a proxy in order to send txs which complicates things, and I'm not sure how this is any easier than learning how to use user-friendly wallets such as Talisman, or Multix for multi-sig txs. 

In my opinion, anyone making advanced or complicated txs should probably learn what they are doing anyway, since many things can go wrong. We've already had many users get funds stuck because they didn't understand how anonymous proxies work, for example. 

I also see the the maintenance grant is still included, which would have to be removed and funded under a separate [maintenance grant](https://github.com/w3f/Grants-Program#hammer_and_wrench-maintenance-grants). Also we don't pay in DOT, so the payment option would need to be changed there anyway.

For these reasons as well as the ones above, I'm going to go ahead and close this application. But I thank you again for your time, and wish you the best of luck in finding funding.

**Comment by johnuopini** [comment]
@keeganquigley thanks for looking into this, you do not actually need a proxy, nodered has plugins for vaults that can be used to pull secrets and i could include a way to securely store a seed. Also i am not sure you understood how Node Red works, Node Red is a visual "no code" programming platform and can be hosted on docker, k8s or basically anything, having a polkadot client there allow users to quickly develop polkadot flows like they would on IFTTT, for example you could quickly create a telegram bot that alerts you whenever your balance hits a given amount or a specific event occurs, honestly i do not see any visual way to do that today, how would you implement such a logic in Talisman or Multix?? Node Red is a bout automation and no code programming, it has nothing to do with a wallet so maybe the use case was not understood

**Pull request closed without merging**
