### PR TITLE
Organise RFPs into collapsible tables

### PR DESCRIPTION
**Pull request by semuelle**
image

### CODE REVIEW

**Review by Noc2 — APPROVED** [review]
Looks really good.

**Review by Noc2 — APPROVED** [review]
I resolved the merge conflict from my own update.

**Comment by NM2146** [comment]
Hey @semuelle Looks great! May I add a suggestion of ordering the RFPs by date instead of alphabetical order so It's easier to see which one's have been last modified and the ones that haven't, i.e 2021 etc..

**Comment by semuelle** [comment]
> May I add a suggestion of ordering the RFPs by date instead of alphabetical order so It's easier to see which one's have been last modified and the ones that haven't, i.e 2021 etc..

Sortable table is in the works, @NM2146. :)

**Pull request merged**
