### PR TITLE
Nolik application

### PR DESCRIPTION
**Pull request by amrbz**
### Project Abstract

Nolik is a protocol for delivering digital content for web 3.0. It allows developers to create applications for formal communication that connect people without any form of censorship or third-party control. The protocol design is based on the ServiceLess approach, meaning that no services from third parties are needed for users to communicate.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Review by Noc2 — APPROVED** [review]
Thanks for the application and sorry for the delay to do the holidays here. Since this is a level 1 grant and I generally think it's a nice project, I’m happy to immediately accept it and share it with the rest of the committee.

**Review by BenWhiteJam — APPROVED** [review]

**Comment by amrbz** [comment]
Wow, thank you guys, that's amazing! I really did not expect that it will be that fast 😆

**Comment by semuelle** [comment]
Hey @amrbz. How is work on Milestone 2 progressing? It seems like there isn't much activity on your repos anymore. According to my calculations, you had planned to submit it in February.

**Comment by amrbz** [comment]
Hi, @semuelle 
Yes, I apologise for the delay. I'm actively working on Milestone 2. I could not realise that it would be that challenging ) At some point, I had to start from scratch. However, I am happy to say that I've almost finished the coding part. I can send messages, create a whitelist, and a blacklist. 

The problem I'm facing at the moment is receiving messages. It turned out that Substrate node does not have RPC methods to get events. I created a [StackExchange discussion](https://substrate.stackexchange.com/questions/1393/getting-extrinsic-data-with-the-transaction-hash) to clarify that. I do not know how to solve this task yet, but there is an option to use third-party libraries like [Subsquid](https://subsquid.io/) and run an extra docker images with blockchain parser and a local database. It will work, but I really want to find out the native solution.

At the same time, I'm excited about the progress. The library allows to send an encrypted set of key-value entries and even send binaries. The repository with the CLI app is private, but I'm going to make it public after I finish my work, and you will be able to track the history of commits.

**Comment by semuelle** [comment]
Great to hear about your progress, @amrbz. Why is the websocket function not an option? Did you see [this comment](https://substrate.stackexchange.com/questions/1393/getting-extrinsic-data-with-the-transaction-hash#comment1191_1408)? In any case, could you submit an amendment to your application to reflect the new timeline? You can be generous where you have no good prediction of when it'll be finished. We are not trying to rush you, just keeping tabs on things. :)

**Comment by amrbz** [comment]
Sure, @semuelle I did see that comment. I tried to use websockets, but in that case, I would have to rewrite everything. Of course I can submit an amendment, but I've almost finished my work. The only thing that left is to properly decode runtime events. I've recently created [this](https://substrate.stackexchange.com/questions/2656/decoding-events-with-rust) post to move forward.

**Comment by semuelle** [comment]
Thanks for the update. In that case, no amendment needed for now.

**Comment by amrbz** [comment]
Hi @semuelle 
Just wanted to share a quick update. I've published [the repo](https://github.com/chainify/nolik-cli) with the app which I intended to build during the grant program. It took much more time then I expected, but totally worth it. I'm working on the docs and about to commit the last milestone.

**Comment by Noc2** [comment]
Thanks for the update!

**Pull request merged**
