### PR TITLE
Update lastic-grant3.md - update to payment in Fiat

### PR DESCRIPTION
**Pull request by poppyseedDev**
#### Context:
The Lastic grant invoice lists a bank account and Euro, while the grant agreement specifies a DOT address and USDT.

#### Resolution:
We have amended the grant agreement to use fiat currency (EUR, CHF, USD) for consistency.

#### Legal Entity Changes:
The legal entity's address has been updated. For confidentiality, the specific details will remain private.

### CODE REVIEW

**Review by semuelle — COMMENTED** [review]
Changing the costs from 30k USD to 30k EUR would turn this into a Level 3 grant. Is that what you intended, @poppyseedDev? If you want to indicate that you want to be paid in EUR, line 4 would suffice. We would then convert the milestone cost from USD to EUR at the time of payment.

**Comment by poppyseedDev** [comment]
I see, sorry for misunderstanding. Should I enter the amount as €27,684.00?

**Comment by semuelle** [comment]
> Should I enter the amount as €27,684.00? Or leave the amount as 30k USD and change the payment into EUR on line 4?

You can leave it as 30k USD. Just indicate EUR in line 4. Thanks.

**Comment by poppyseedDev** [comment]
> > Should I enter the amount as €27,684.00? Or leave the amount as 30k USD and change the payment into EUR on line 4?
> 
> You can leave it as 30k USD. Just indicate EUR in line 4. Thanks.

@semuelle should be fixed now :)

**Review by semuelle — APPROVED** [review]

**Review by keeganquigley — APPROVED** [review]

**Review by takahser — APPROVED** [review]

**Pull request merged**
