### PR TITLE
Create Carbon Capture Backers.md

### PR DESCRIPTION
**Pull request by BooneTB**
### Project Abstract

> Multi-chain IDO platform to bring funding to projects that capture carbon and yields Carbon Removal Credits. 

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [x] **Level 2**:  Up to $50,000, 3 approvals

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x ] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Comment by semuelle** [comment]
Hi Boone, thank you for your application! Looks interesting. We will look into it as soon as possible. 

In the meantime, could you expand on the milestones in your roadmap by providing a list of deliverables (with a verifiable and reproducible specification)? See our [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#milestone-1-example--implement-substrate-modules) for examples.

**Comment by semuelle** [comment]
Pinging @BooneTB

**Comment by BooneTB** [comment]
Thanks for the ping @semuelle :) 
We are in the process of mapping out the milestones, and preparing to go live with the initial IDO. 
We are working on this so please keep our application open, and stay tuned for updates in coming weeks.
Best wishes!

**Comment by semuelle** [comment]
Glad to hear! Keep us posted.

**Comment by alxs** [comment]
@BooneTB any updates? Note that we generally close applications after 2 weeks of inactivity. If you're not sure when you'll be able to get back to it, you can always close it and reopen it when you're ready, especially seeing as you were planning to expand on it anyway.

**Comment by alxs** [comment]
I'll go ahead and close this for now. Feel free to reopen this PR or create a new one when you're ready to apply.

**Pull request closed without merging**
