### PR TITLE
Create RubeusKeeper.md

### PR DESCRIPTION
**Pull request by dsrdrk11a**
#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Looks like an interesting project. What programming languages/frameworks are you going to use for the extension and/or the mvp landing page? Or are you going to reuse an existing extension? I would probably recommend separating this into two deliverables, one for the extension and one for the testing page.

**Comment by dsrdrk11a** [comment]
Hello, David @Noc2 !
The extension will be fully developed by our team, we are going to use JavaScript, as well as for the testing page.
I've split the first milestone in two, so now there are 3.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update and sorry for the late reply. Could you add the programming language to the deliverables? My recommendation would also be to remove the last milestone from the deliverables for now. This way you only need three approvals and you could apply for a follow-up grant later. Finally, maybe you could add a little bit more information about potential attack vectors and the encryption you are going to use.

**Comment by dsrdrk11a** [comment]
Hey, @Noc2 , thank you for your suggestions! We fully accept them. I've corrected the application - it now contains only 2 milestones. Also, I've added description about cryptographic algorithm to be used in this project.

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I’m happy to support this and share it with the rest of the team.

**Review by alxs — APPROVED** [review]

**Review by gautamdhameja — APPROVED** [review]

**Pull request merged**
