### PR TITLE
SnapWallet Proposal

### PR DESCRIPTION
**Pull request by RakeshUP**
### Project Abstract

SnapWallet is a localStorage based Web Wallet SDK for Substrate chains. It makes user-onboarding easier and quicker and can also be used as a burner wallet.

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] The total funding amount of the project is below USD $30k for first-time grant applications and $100k for follow-up ones.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] :warning: The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. In general, we are quite interested in user friendly wallets (e.g. burner wallet in combination with a faucet, or a wallet that makes use of the [social recovery pallet](https://www.parity.io/blog/social-recovery-on-substrate/#:~:text=The%20Substrate%20Recovery%20pallet%20is,authentication%20mechanism%20has%20been%20lost.&text=You%20can%20specify%20the%20set,access%20to%20your%20account%20again.)). Would it be possible to share some initial designs/mock-ups with us as part of the grant? What’s the advantage of using the SDK compared to just using polkadot.js?

**Comment by RakeshUP** [comment]
Hey David, I've added screenshots of the mock-ups to the proposal doc. Sharing the figma link here(https://www.figma.com/file/JnP5poKMld5EiXzbEeOMMW/SnapWallet?node-id=0%3A1)

SnapWallet will be completely relying on @polkadot/ui-keyring package, with all the UI flows on top of it like creating & importing accounts, signing transactions, and sending/receiving tokens. It will be combining all UI elements(with a lot of customization possibilities) with a nice abstraction of polkadot.js API.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. To be honest, it looks a little bit expensive to me, given the current scope. Could you potentially reduce the price or add more details? Also maybe specify as part of the milestones, which UX options you will implement as part of the deliveries and specifically point out if something is unique for your implementation. For example, polkadot.js/apps also let you download the account.

**Comment by alxs** [comment]
@RakeshUP I'm closing this for now due to inactivity. Let us know once you've revised your application and we'll reopen the PR (please don't force-push).

**Pull request closed without merging**
