### PR TITLE
Submit the application for Web3go

### PR DESCRIPTION
**Pull request by Moehringen**
### Project Abstract

Web3Go is an open data platform that focuses on the formatting, visualization, sharing, and collaboration of the on-chain data generated in the Polkadot ecosystem.

Our project is to build a data platform for the Polkadot ecosystem and provide a series of toolsets so that everyone can easily obtain visualized results of data analysis. We will track all valuable information on-chain such as smart contracts, including various parameters like the stake and CDP of different Defi protocols, NFT circulation, and cross-chain assets on Polkadot ecosystem, and make these data formatted and persisted. With the help of the smart contract on Substrate parachain, non-professionals can publish their data needs on the platform and use rewards to motivate professionals to help them perform data analysis; for professionals, they can publish their own professional analysis for everyone to use paid or for free. In the second situation, they can get the reputation from the community. In the end, we broke the monopoly of some existing companies on data analysis and interpretation, so that everyone can truly enjoy the true value behind blockchain data.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. This looks interesting. I have a few questions:

- Isn’t a lot of the things you promise as part of the first milestone already implemented here: https://web3go.xyz/#/? (e.g. bar chart, line chart, etc support here: https://web3go.xyz/#/CustomQuery?id=28&editSupport=false). It might make more sense to focus on new things that you want to implement as part of the grant.   
- In general, could you try to be more specific with your deliverables. These are basically the requirements of the contract. For example: What exactly do you change as part of the customization of the indexer. 
- I think the biggest issue of the current prototype is the lack of documentation/tutorials. If you open the website it’s difficult to understand what you can do with it. 
- Could you add the default deliverables 0a. to  0e. also to milestone 2.

**Comment by Noc2** [comment]
Thanks for the quick reply. Yes, it would be nice if you could focus on the new/upcoming features that will be delivered in the future and less on the features which are already integrated. That said it definitely helps with the approval of the grant, that you are already working on it. And feel free to integrate more specific descriptions regarding the tutorials/documentation. Ideally this is also integrated into the website itself. Let me know, once you have updated the application.

**Comment by Moehringen** [comment]
Dear Sir, 
I have changed the application according to your comment: 
1.  Add the default deliverables 0a. to 0e. also to milestone 2. 
2. Adjust the deliverables in the milestone and make it more specific, and move the already implemented function from the milestone part to the Development Status part. 
3. Create a tutorial page here: https://doc.web3go.xyz/, and it can be navigated from the web app directly.
4. Adjust the amount of the grant as some function is excluded from the deliverables in the milestone.  
5. We are keeping developing every day, so the website could be changed anytime, just let you know that. 

Waiting for your response!

Mit freundlichen Grüßen

**Review by Noc2 — DISMISSED** [review]
Looks good to me. But it would be nice to support more kusama tokens instead of erc20 tokens. Independent of it, I will share the application with the rest of the team.

**Review by gautamdhameja — DISMISSED** [review]
Looks good to me. I would also like to see support for GraphQL in the query module, if that is possible. Most of the new users are now moving towards GraphQL. Can you add this?
Also, would be good to see support for more of Polkadot/Kusama ecosystem tokens.

**Review by gautamdhameja — APPROVED** [review]

**Comment by takahser** [comment]
Hi @Moehringen
I don't see any activity yet. Is there any way we can support you?

**Comment by Moehringen** [comment]
hi actually we just want to deliver the M1, we have done much more than the commitment in the contract. please take a look at our APP: https://web3go.xyz/#/.  our app is attracting lots of users now.  but anyway we will submit the M1 ASAP.

**Comment by Noc2** [comment]
Sounds great.

**Comment by Moehringen** [comment]
yes, we will submit it next week.  we have done a lot already!

**Comment by alxs** [comment]
Hey @Moehringen, are you still planning to submit the second milestone?

**Comment by Moehringen** [comment]
yes, as the UI is very complex, it will take some time!

Aleixo Sanchez ***@***.***> 于 2022年11月1日周二 00:25写道：

**Comment by alxs** [comment]
@Moehringen friendly reminder.

**Comment by keeganquigley** [comment]
Hi @Moehringen how is M2 coming along?

**Comment by Moehringen** [comment]
hi Keegan,

We will submit it soon.

Sorry for the delay.

**Comment by keeganquigley** [comment]
Thanks for the update @Moehringen, just bumping a friendly reminder. If you think there might be a significant delay I would recommend filing an [amendment](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval) for an extension. Thanks!

**Comment by Moehringen** [comment]
wiil submit soon, we pack the docker image recently.

**Comment by keeganquigley** [comment]
Hi @Moehringen are you about to submit the delivery? If not could you please file an amendment to extend the timeline? Thanks!

**Comment by Moehringen** [comment]
Submitted!

**Pull request merged**
