### PR TITLE
Ventur Proposal

### PR DESCRIPTION
**Pull request by Gryczka**
#### Project Abstract

Ventur is focused on decentralizing business processes and services for professionals. Ventur’s initial goals are:
1. To enable decentralized marketplaces for professional engagement, encompassing business-to-business engagement and employment contracts between businesses and individuals.
2. To enable assignment and evaluation of technical credentials.

[Project Overview on Google Slides](https://docs.google.com/presentation/d/15kMwFxIbvGHCOPvR7gi7RVZAmYfQczMNFKr9NEBDNK4/edit?usp=sharing)
[Project Summary on Google Docs](https://docs.google.com/document/d/1gFBQufcYHUP4rBwN_Ck6ERT6l4eyhA0_PKXf__AbmzQ/edit?usp=sharing)

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the application. Sounds like an interesting project. Are you aware of the following implementations/projects: 

- https://github.com/w3f/Grants-Program/pull/1094 
- https://github.com/rmrk-team/rmrk-substrate/blob/4cda1825ca38eb29c958c7264b49f5545e679e30/pallets/rmrk-core/src/lib.rs#L384 (which is essentially a soulbound nft, if you make it non transferable).

**Comment by Gryczka** [comment]
Hi, thank you for taking the time to review our application.

For rmrk’s NFT implementation, we believe we will need to extend functionality beyond just the transferability flag.  Many of the Technical Certifications we want to represent have expirations.  We believe that we’ll need to add expiration functionality to appropriately represent those certifications.  Outside of our core certification/accreditation target, we have also seen significant interest in Soulbound Subscriptions with expiration functionality, which we believe our implementation could better address vs the current implementation.  Additionally, rmrk’s implementation does not currently need a functionality for discarding non transferable nfts, we believe there may be interest in having the ability to discard certain soulbound tokens (even within their expiry time should that be applicable) if their relevance is no longer beneficial to the holder.

The Escrow pallet #1094 intends to implement 2 party escrow.  While that is part of what we functionally wish to deliver, it might make sense for us to rename our feature, as we want our escrow fund to be something which can hold and distribute funds across a category of rfps (initially targeted as rfps from a single provider).  We also want to enable a configuration for escrows to accept open funding.  Enabling organizations to raise funds for a given category of work that might be of value to their community or a broader audience.

**Review by Noc2 — APPROVED** [review]
Thanks for the quick reply. Makes sense. I’m happy to go ahead with the application and I will mark it as ready for review. These modules might also be interesting in case we ever want to put our grants program on-chain.

**Review by alxs — APPROVED** [review]

**Review by laboon — APPROVED** [review]

**Comment by keeganquigley** [comment]
Hi @Gryczka Just checking up to see how the progress is going on M2?

**Comment by Gryczka** [comment]
Hi @keeganquigley, greatly appreciate the check in here.  

Maciej from our team has had most of the technical delivery for the pallets wrapped up since late November, but we hit some delays in prioritizing the delivery submission itself and the walk-through test guides.

I've just pushed the test guides and some test coverage that should complete the M2 deliverables, and we should have the delivery milestone submitted for initial review and feedback within the next 48 hours.

**Pull request merged**
