### PR TITLE
ammend iris grant prop

### PR DESCRIPTION
**Pull request by driemworks**
### Project Abstract

Iris is a substrate-based decentralized storage network. It builds off of work done by a team at [equilibrium](https://github.com/rs-ipfs/substrate) which laid the foundation by embedding rust-ipfs within the substrate runtime. With the ability to track the DHT status onchain, we aim to provide decentralized storage which solves some of the issues present in DSNs today: governance, availability while retaining full decentralization, security, and indexability. Further, Iris is intended to work alongside parachains which communicate with Iris via a pallet (using XCM) that we provide. Nodes in Iris-compatible parachains  can create iris-backed assets within their parachains, which allow the creation of a "ticket", an asset that allows access to some item in Iris. This allows users (nodes in a parachain) to use Iris as a (private) storage layer and manage or monetize access to it within their own parachains, using their own tokens and governance (retaining sovereignty). 

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the amendment. I noticed that you also reduced the FTE and Estimated Duration for milestone 2 and 3. Could you potentially also reduce the price accordingly?

**Review by Noc2 — CHANGES_REQUESTED** [review]
Sounds good to me. Could you maybe also update the total costs? Just so it doesn’t lead to any confusion.

**Comment by driemworks** [comment]
Absolutely. It's updated now.

**Review by Noc2 — APPROVED** [review]
Thanks. I will share it with the rest of the team.

**Comment by driemworks** [comment]
Just sending a little nudge as I am approaching the completion of milestone 2.

**Comment by Noc2** [comment]
Thanks for chasing us. I will share it again with the team.

**Review by alxs — APPROVED** [review]
LGTM.

**Review by takahser — APPROVED** [review]
LGTM as well.

**Pull request merged**
