### PR TITLE
Application for Candymint

### PR DESCRIPTION
**Pull request by AshutoshSingh00001**
#### Project Abstract

> Candy Mint is a tool built for Asset Hub for building scalable nft mint dapps built with the use polkadot-js/api and react-js similar to ethereum based mint dapps but by using Candy Mint builders won't have to write smart contract

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) or BTC address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by AshutoshSingh00001** [comment]
> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/T%26Cs.md) before we can accept your contribution. Please submit the following text as a separate comment:
> 
> I have read and hereby sign the Contributor License Agreement.
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request

I have read and hereby sign the Contributor License Agreement.

**Comment by AshutoshSingh00001** [comment]
I have read and hereby sign the Contributor License Agreement.

**Comment by AshutoshSingh00001** [comment]
@keeganquigley @semuelle Requesting a Review

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for your interest in the grants program. However, the project currently consists of four times "milestone 1". At least the first three milestones don't have any concrete details and feel free to remove all the template text that isn't bold and clean up the formatting of the application.  To already add, I _personally_ don't think the mock-ups are super attractive or there will be a lot of use for this application, so in general unsure if the committee is willing to support something like this.

**Comment by AshutoshSingh72** [comment]
> Thanks for your interest in the grants program. However, the project currently consists of four times "milestone 1". At least the first three milestones don't have any concrete details and feel free to remove all the template text that isn't bold and clean up the formatting of the application. To already add, I _personally_ don't think the mock-ups are super attractive or there will be a lot of use for this application, so in general unsure if the committee is willing to support something like this.

Sure I will make changes right now

**Comment by AshutoshSingh72** [comment]
> Thanks for your interest in the grants program. However, the project currently consists of four times "milestone 1". At least the first three milestones don't have any concrete details and feel free to remove all the template text that isn't bold and clean up the formatting of the application. To already add, I _personally_ don't think the mock-ups are super attractive or there will be a lot of use for this application, so in general unsure if the committee is willing to support something like this.

I understand you concern about the mocks-up but it's just a demo app which  i'm not even building it will fully different yaou can just say that as a test app

**Comment by AshutoshSingh72** [comment]
> Thanks for your interest in the grants program. However, the project currently consists of four times "milestone 1". At least the first three milestones don't have any concrete details and feel free to remove all the template text that isn't bold and clean up the formatting of the application. To already add, I _personally_ don't think the mock-ups are super attractive or there will be a lot of use for this application, so in general unsure if the committee is willing to support something like this.

I understand you concern about the mocks-up but it's just a demo app which  i'm not even building it will fully different you can just say that as a test app

**Comment by AshutoshSingh72** [comment]
> Thanks for your interest in the grants program. However, the project currently consists of four times "milestone 1". At least the first three milestones don't have any concrete details and feel free to remove all the template text that isn't bold and clean up the formatting of the application. To already add, I _personally_ don't think the mock-ups are super attractive or there will be a lot of use for this application, so in general unsure if the committee is willing to support something like this.

I tried to figure out what are problem in my Grant application compared with other grants i finally found that my grant application has several mistakes so i'm going to make changes as soon as possible

**Comment by AshutoshSingh00001** [comment]
@Noc2 Changes Done 👍

**Comment by AshutoshSingh00001** [comment]
> Thanks for your interest in the grants program. However, the project currently consists of four times "milestone 1". At least the first three milestones don't have any concrete details and feel free to remove all the template text that isn't bold and clean up the formatting of the application. To already add, I _personally_ don't think the mock-ups are super attractive or there will be a lot of use for this application, so in general unsure if the committee is willing to support something like this.

well when it comes to the using of mint dapp then I have clear example of bored ape yatch club mint which is one of the biggest nft project on ethereum this project had it's first NFT sold using the application which we're trying to build the difference is that they were on eth and we are on polkadot

**Comment by AshutoshSingh00001** [comment]
Re-submitted  https://github.com/w3f/Grants-Program/pull/2064

**Comment by takahser** [comment]
closing this PR in favor of https://github.com/w3f/Grants-Program/pull/2064

**Pull request closed without merging**
