### PR TITLE
add Listen-Network App

### PR DESCRIPTION
**Pull request by JimYam**
#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by JimYam** [comment]
> Thanks for the application. I have a couple of initial questions/comments:
> 
> * We have the rule that “We do not award grants for projects that have been the object of a successful token sale.”. Given that you successfully participated in a parachain auction, I assume that the rest of the committee might have some questions about this. Could you comment on it?
> * Deliverables 0a-0d [of the template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) are usually mandatory for all milestones, and deliverable 0e at least for the last one. Could you add these?
> * For design-focused milestones, we usually ask teams to provide some initial mock-ups or designs.



> 

Thank you very much for your reply, we have not sold any tokens on the market so far, although we have taken the slot. We didn't have time to apply for the grant because we were too busy. We believe that this project is very meaningful, and winning the grant will have a positive effect on our market. In fact, our project has done a lot of milestones 1 and 2, but some things are not done yet, so we decided to further standardize and improve it. As for 0a-0e, I will further improve it according to the requirements, thank you for your valuable suggestions. Our design is the function mentioned in the milestone, of course, there will be more functions, such as the reputation point system, etc., which are planned in the future. Our design has always been very clear, first to do the basic functions well and have a group of loyal users

**Comment by JimYam** [comment]
> Thanks for the application. I have a couple of initial questions/comments:
> 
> * We have the rule that “We do not award grants for projects that have been the object of a successful token sale.”. Given that you successfully participated in a parachain auction, I assume that the rest of the committee might have some questions about this. Could you comment on it?
> * Deliverables 0a-0d [of the template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) are usually mandatory for all milestones, and deliverable 0e at least for the last one. Could you add these?
> * For design-focused milestones, we usually ask teams to provide some initial mock-ups or designs.

Thank you very much for your reply, we have not sold any tokens on the market so far, although we have taken the slot. We didn't have time to apply for the grant because we were too busy. In fact, our project has done a lot of milestones 1 and 2, but some things are not done yet, so we decided to further standardize and improve it. As for 0a-0e, I will further improve it according to the requirements, thank you for your valuable suggestions. Our design is the function mentioned in the milestone, of course, there will be more functions, such as the reputation point system, etc., which are planned in the future. Our design has always been very clear, first to do the basic functions well and have a group of loyal users

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update and sorry for the delay. We currently are on a company retreat. I have a couple of follow-up questions: 

- Regarding the design, could you integrate a few images into the application or provide a link to it? 
- Also, it would still be nice if you could integrate more technical details. For example, how exactly are you going to implement ipfs and TEE? 
- Regarding the Substrate module: NFT-Sell, how is this different from https://github.com/rmrk-team/rmrk-substrate/tree/main/pallets/rmrk-market? 
- Btw. if you are using other pallets, like Acala, you don’t need to mention this as part of the application. We only pay for the development of new pallets, or the improvement of existing ones.

**Comment by alxs** [comment]
@JimYam note that we generally close applications after 2 weeks of inactivity. Are you still interested in this?

**Comment by Noc2** [comment]
I’m closing this due to inactivity. Let me know if you want to re-open it.

**Pull request closed without merging**
