### PR TITLE
Supersig: second grant proposal to be included in system level chain (statemine)

### PR DESCRIPTION
**Pull request by decentration**
#### Project Abstract

Supersig has completed it's first [grant](https://github.com/w3f/Grants-Program/pull/959). This follow up grant is required to make the necessary changes in order for it to be included in Statemine, Polkadot JS main repo, and approved by the Fellowship. 

Supersig is like Multisig but provides more flexibility when it comes to scaling your organisation. You have features such as:

-  you can add and remove members; 
- enumerated threshold (i.e. simpleMajority, instead of fixed threshold); 
- and you have the option to add either Standard users which is 1 vote for 1 user, or Master users which has 50% voting power,.

> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. I have a couple of initial questions: 

- First, did you consider applying for treasury funding with this? With our grants program, we focus more and more on teams that are unfamiliar with our ecosystem and ask teams that are familiar with the treasury to apply there for funding.
- One thing that might be controversial regarding the application is that you plan to/have your own token KAB, see our guidelines: https://github.com/w3f/Grants-Program#guidelines 
- Regarding the deliveries, ideally, these contain as many details as possible. For example, what do you mean by “various changes,” and do you have a mock-up or UI design you can share already?

**Comment by decentration** [comment]
Hi @Noc2 David, thanks for your questions. 

Re: launching this with the polkadot treasury, i'm not sure this grant is completely suitable for the polkadot treasury, especially as it may take at least 6 weeks to get confirmation of the work. Also there are various downsides in regard to the current treasury proposals from my experience, being the increased stresses that is involved in a gruelling public process, where people can tend to throw rocks. So due to time, suitability and increased stress level we would much prefer W3F. Though for a future project we would consider it. Let me know if that is not ok with you?

Also to add, i have noticed various projects getting multiple grants with W3F, which is why i saw this as a great track. Also I have had pleasurable experience interacting with this process, so that's something i wouldn't want to give up. 

And if we can touch up this holistically, Supersig second grant is a continuation of the same project, and we want to make those grant dollars as valuable as possible, so that the tools are used by the most people, we want to be part of the percentage of grants that have made a big impact. 

Re: not having a token... Let me clear up. Decentration is independent of any chain, we do not have our own token, and we haven't launched a token. To clarify, we got a small grant to build Kabocha parachain on behalf of Edgeware. The KAB you are referring to is Kabocha parachain token. The KAB is not on any exchanges and didn't go through a token sale. Decentration has 1.5% of KAB and W3F has 7% of that token, and Edgeware community own 90%, but nothing was sold, it is currently still in an experimental playground phase, but even if it was an active token, we are not the object of it, we just earned some for doing the work, but the community were unable to put it on an exchange, which was a shame for us because we are earning tokens that have not much value, so that is actually why we need to find other ways to work and get funded in this ecosystem and earn to work. Personally, I am not interested in launching a token. I prefer to build universal tools and common good parachains. Let me know if that is not sufficient to clear up that issue?

Re: Details of milestone 2 UI, yes my apologies I forgot to add mockup let me add that in. 

Let me know if the initial two points are not sufficient for you? and perhaps I can try clarify further.

Cheers

**Review by decentration — COMMENTED** [review]
mockup added and more clarity for M1 polkadot-js

**Review by Noc2 — DISMISSED** [review]
Thanks for the quick reply here. Sounds good to me. I will share it with the rest of the team.

**Comment by Noc2** [comment]
This is because GitHub doesn't allow us to have different PR rules for different PRs. We will merge it after three approvals.

**Comment by decentration** [comment]
hello @keeganquigley thanks for the feedback:

1) indeed, my apologies, it will have a suitable testing guide with end to end tests, that will be seamless for the reviewer. 

2) 
> Is your custom UI meant to be easier to use than Polkadot-JS? What other advantages will it have?

Yes, i personally love polkadot-js and the tool suite as an engineer, however the Custom UI, will be simpler and more bespoke to organising, initally around supersig. It will begin with similar features to page-supersig on polkadot-js app, however it will be the foundation for then future building blocks, such as: multisig interface, automated payments, and other statemine/mint primitives, etc. We can prioritise on what those will be based on feedback in future milestone.

**Review by keeganquigley — APPROVED** [review]
Thanks for the changes @decentration happy that you want to keep working on it. Based on your team's previous reputation I'm happy to approve.

**Comment by decentration** [comment]
Thank you @keeganquigley I appreciate those words.

**Review by Noc2 — APPROVED** [review]

**Review by SBalaguer — APPROVED** [review]

**Pull request merged**
