### PR TITLE
Polkadot Smart Chain 

### PR DESCRIPTION
**Pull request by icodezjb**
#### Project Abstract

Polkadot Smart Chain (PSC) is an Ethereum-compatible smart contract parachain which uses directly DOT as the native gas fee.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (aUSD/USDT) address for the payment of the milestones is provided in the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_____:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the quick reply and update. For reference:  https://github.com/w3f/Grants-Program/pull/1424 Additionally could try not to mention specific tokens in the application but rather focus on the technical open-source development that needs to be done. See our guidelines: https://github.com/w3f/Grants-Program#guidelines

**Comment by Noc2** [comment]
Let me know if I should take another look at the application.

**Review by dsm-w3f — COMMENTED** [review]
Thank you for your application. Bridges even between technologies raise security concerns. What is the plan to secure these bridges? This is in the scope of this grant request or is it a future work?

**Comment by icodezjb** [comment]
> Thank you for your application. Bridges even between technologies raise security concerns. What is the plan to secure these bridges? This is in the scope of this grant request or is it a future work?

Unlike statemint using teleport xcm instructions, PSC uses reserve xcm instructions, which obviously does not pose any security risks to the relaychain network.

In the scope of this grant request, only related to `xcmp`, `substrate` technology.
Please refer to [pallet-assets-bridge](https://github.com/OmniBTC/PSC/tree/main/pallets/assets-bridge) for details, it is a bridge on PSC of wasm assets into evm tokens, it is not a cross-chain bridge.

We do have plans similar to cross-chain bridges in the future, and PSC will be a partial chain of the [DOLA protocol](https://github.com/OmniBTC/DOLA-Protocol).

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for pinging me. But could you still remove the DOT token from the application? Maybe replace it with “substrate native token” or something like that and "substrate account" instead of "DOT account", etc. We basically only care about the technical development and that we can test it on a local substrate chain.

**Review by dsm-w3f — COMMENTED** [review]
@icodezjb I still believe that even though it is not a cross-chain bridge it can bring security issues for the users, not for the relay chain, and some security analysis needs to be performed in the pallet and contracts involved. Can be as future work. 

One more question, if you already have the code developed [pallet-assets-bridge](https://github.com/OmniBTC/PSC/tree/main/pallets/assets-bridge), why are you applying for a grant?

**Comment by icodezjb** [comment]
> Thanks for pinging me. But could you still remove the DOT token from the application? Maybe replace it with “substrate native token” or something like that and "substrate account" instead of "DOT account", etc. We basically only care about the technical development and that we can test it on a local substrate chain.

Thank you for your reply. We have removed the DOT token.

You can quickly start the local test network through [zombienet](https://github.com/OmniBTC/PSC/blob/main/zombienet/psc-small-network.toml), and need recompile [this polkadot](https://github.com/OmniBTC/polkadot/tree/release-v0.9.32-fix).

We will provide a basic **tutorial** that explains how to complete the cross-chain asset transfer of Native Currency between relaychain and PSC through DMP/UMP, and how to deploy and call the evm contracts on PSC.

**Comment by icodezjb** [comment]
> @icodezjb I still believe that even though it is not a cross-chain bridge it can bring security issues for the users, not for the relay chain, and some security analysis needs to be performed in the pallet and contracts involved. Can be as future work.

Thank you for your suggestion, we are calling evm call in wasm now, it is cryptographically safe, we will do more security analysis in the future to ensure the security of user assets.

> One more question, if you already have the code developed [pallet-assets-bridge](https://github.com/OmniBTC/PSC/tree/main/pallets/assets-bridge), why are you applying for a grant?

First, our community users voted for us to get a parachain, and they suggested that we apply for this grant.
Second, We do encounter some financial difficulties now, and we don’t even have enough DOT to endorse for [proposal 21](https://polkadot.polkassembly.io/proposal/21)

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. Could you replace “Polkadot account” with “substrate account”? And to clarify: Have you already finished all the development for this grant? While we usually appreciate teams working on open-source projects without any funding, the grant itself should always also contain new features that are developed after the approval of the grant application.

**Comment by icodezjb** [comment]
> 

Thank you for your review. We have replaced.

> And to clarify: Have you already finished all the development for this grant?

This grant still has some documentation and testing not done. 

The current grant is just the beginning of our grant requests, and we will have a grant request about the Dola protocol next.

**Comment by gguoss** [comment]
> Thanks for your review. We have replaced.
> 
> > And to clarify: Have you already finished all the development for this grant?
> 
> This grant request still has some documentation and testing not done.
> 
> The current is just the beginning of our grant requests, and we will have a grant request about the [DOLA protocol](https://github.com/OmniBTC/DOLA-Protocol) next

You should answer: The content of this grant has not been completed, wait for the grant to agree, and then start to complete the development, and then organize documents, codes and tests.

As you mentioned later, the development of dola is the next grant, which has nothing to do with this grant. After this grant is over and delivered, apply for the next dola-related development grant

**Review by Noc2 — APPROVED** [review]
Thanks for the quick reply and the transparency here. Obviously, people can always close source code and only release it after we approve the grants, etc. However, given that this is only a level 1 grant and the tools that you develop are open-source and useful for others, I’m happy to go ahead with it and support this initial grant. However, keep in mind that potential parachain teams ideally should be funded via VC and other investors, so not sure we will be willing to support the "DOLA Protocol." (ultimately, it depends on the scope of the grant application).

**Comment by icodezjb** [comment]
@gguoss 
Thank you for your addition, avoiding unnecessary ambiguity.

@Noc2 
Thanks for your review and support.
We will seriously consider your suggestion about DOLA.

**Review by dsm-w3f — APPROVED** [review]
As there is some scope to do and it is an interesting project, I'm happy to support it as well.

**Pull request merged**
