### PR TITLE
Amend Standard Protocol Grant and add milestone 2

### PR DESCRIPTION
**Pull request by hskang9**
### Project Abstract

Standard Protocol adds a new milestone reflecting current developer infrastructure.

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for creating the amendment. Could you sign the latest version of the cla? Also are the 10 DAI on purpose? It might cost more to transfer the 10 Dai, so I would suggest either to reduce it to 0 DAI or to integrate the 10 DAI into another milestone.

**Comment by hskang9** [comment]
@Noc2  0 dai is fine.

**Comment by Noc2** [comment]
In this case, could you update the PR?

**Comment by semuelle** [comment]
ping @hskang9

**Review by alxs — CHANGES_REQUESTED** [review]
@hskang9 please commit so that we can review the amendment. When do you expect to deliver this new milestone? The PR has been opened for almost a month now, so if the estimate is anything to go by it's almost due.

**Pull request closed without merging**
