### PR TITLE
Amend proposal

### PR DESCRIPTION
**Pull request by willemolding**
Add amendments to the proposal to reflect the delivered project

- Add Willem as a contributor
- Remove task to deploy to IPFS
- Update scope for signer-provider
- Update API for rpc-wrapper

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#676

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. Could you sign the latest version of the terms and conditions? Ideally, @mpetrunic also confirms here that he is happy with the PR, since he originally applied for the grant.

**Comment by mpetrunic** [comment]
> Thanks for the update. Could you sign the latest version of the terms and conditions? Ideally, @mpetrunic also confirms here that he is happy with the PR, since he originally applied for the grant.

I'm happy with PR :)

**Comment by Noc2** [comment]
@willemolding this is just a reminder to sign the terms and conditions. See CLA bot. Let me know if you have any questions.

**Review by alxs — COMMENTED** [review]
See my [comments](https://github.com/w3f/Grant-Milestone-Delivery/pull/610#issuecomment-1310296251) in the delivery, you may want to update the deliverables here. Other than that, it would make sense to also reduce the price since you've reduced the scope.

**Comment by willemolding** [comment]
> @willemolding this is just a reminder to sign the terms and conditions. See CLA bot. Let me know if you have any questions.

Signed

**Review by Noc2 — CHANGES_REQUESTED** [review]
I agree with Alex here. It would be nice if you could reduce the price as well.

**Comment by Redoudou** [comment]
@alxs I am a little confused as we worked with Polywrap on re-submitting everything to follow your format. 


- [0a – License](https://github.com/ChainSafe/integrations/pull/33/files#diff-b4b52eee206eb9455a883474d827c23e51710acf8c7e59d2a5414e17d89f6d27R8)
- [0b – Inline docs, basic tutorial](https://github.com/ChainSafe/integrations/pull/33/files#diff-b4b52eee206eb9455a883474d827c23e51710acf8c7e59d2a5414e17d89f6d27R8)
- 0c – Testing guide >> we have e2e testing for the wrapper that answer those needs and repo explains how it is done
- 0d – Article >> [here](https://docs.google.com/document/d/1G7l0sgyEI_X9ucnEkJMUcD_bYo-FeCm9Ot_ETR7giiM/edit#heading=h.uzkbekb348bf)
- Clean up repo todo list >> We answered everything that leftover were solved and removed from scope
- QA on the PR submission

What are we missing ?

**Comment by alxs** [comment]
@Redoudou if you're referring to my comment [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/610#issuecomment-1333805083), could you please make sure the list of deliverables in the application and the delivery file match? As for the reduction in scope, I mean [this section](https://github.com/w3f/Grants-Program/pull/1262/files#diff-317ef07932ce9253acfe4627820c8537cf924c9565ddc0eae2cea0d002fec3ecL163-R170) in particular.

**Comment by dOrgJelli** [comment]
Hey @alxs, we've pushed changes to address all of the outstanding comments above. Please let us know if are any remaining issues.

### Signer-Provider-Plugin ([Comment](https://github.com/w3f/Grants-Program/pull/1262#issuecomment-1335067344))
In this new PR, I've added back the details that were originally apart of the signer-provider-plugin section, as well as some code snippets to describe how they are possible in the current codebase: https://github.com/ChainSafe/Grants-Program/pull/6/files

The plugin now supports any of Polkadot.js' keystore implementations, as shown here: https://polkadot.js.org/docs/ui-keyring/start/init/#additional-create-options If nothing is specified in the plugin's constructor, the injected browser extension will be used by default.

### IPFS Deployment + CI/CD ([Comment](https://github.com/w3f/Grant-Milestone-Delivery/pull/610#issuecomment-1297436761))
We have also added CI/CD to the repo, which you can see successful runs of here:
- [example CI run](https://github.com/polywrap/integrations/actions/runs/3636322041/jobs/6136190304)
- [example CD run](https://github.com/polywrap/integrations/actions/runs/3636322399/jobs/6136191060) + [ipfs deployment artifact](https://github.com/polywrap/integrations/blob/main/protocol/substrate/rpc-wrapper/deployment.json)

And you can find the [substrate-rpc-wrapper on IPFS](https://wrappers.io/v/ipfs/QmWKnVv1M5pj9C5cuY9EwNB3QPvbUBGKgBSGUDiWkWHEPG) here.

### RPC Methods -> Wrapper Methods ([Comment](https://github.com/w3f/Grant-Milestone-Delivery/pull/610#issuecomment-1306030274))
Lastly I want to echo what @willemolding has said, all originally specified RPC methods in the proposal are supported via the exposed methods in the wrapper. It just made more sense to replace the underlying RPC methods with their wrapper equivalent functions. The wrapper's methods can be viewed here in its schema: https://github.com/polywrap/integrations/blob/main/protocol/substrate/rpc-wrapper/schema.graphql

**Comment by keeganquigley** [comment]
Thanks @Redoudou and @dOrgJelli your mandatory deliverables 0a. - 0d. look good. What @alxs is referring to is the fact that the deliverables in your delivery file contain [1 - 6](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1262), while the application only contains deliverables [1 - 3](https://github.com/w3f/Grants-Program/pull/676/files#diff-317ef07932ce9253acfe4627820c8537cf924c9565ddc0eae2cea0d002fec3ecR147-R149) (and they are different). So either the delivery file or the application file needs to be updated in order for them to match.

Also, we recently made changes to our [CLA](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1262) if you don't mind signing it again. Thanks!

**Comment by dOrgJelli** [comment]
Hi @keeganquigley, I'm quite confused by your reply. What are the "1-6 deliverables" that you are referring to? Your hyperlink redirects to the CLA, which I think might be a mistake.

It appears to me that [all deliverables in the 1st milestone](https://github.com/w3f/Grants-Program/pull/676/files#diff-317ef07932ce9253acfe4627820c8537cf924c9565ddc0eae2cea0d002fec3ecR143-R149) are indeed complete (0.a - 0.d, 1 - 3).

**Comment by dOrgJelli** [comment]
Okay thank you for pointing this out @keeganquigley, also FYI I believe this is the correct hyperlink you meant to include for "1-6" above: https://github.com/w3f/Grant-Milestone-Delivery/pull/610/files#diff-d82ffd9f0d2b482272abb51f0f254cc5d803463a655a07f50a1152b4cd4371b6R34-R39

Will be sure to align the submission w/ the original proposal.

**Comment by dOrgJelli** [comment]
How does this look @keeganquigley? https://github.com/ChainSafe/Grant-Milestone-Delivery/pull/2

**Comment by keeganquigley** [comment]
Ah I apologize @dOrgJelli I did post the wrong link. Thanks for finding the correct one. Looks a lot better now! I am happy to go ahead and approve the amendment.

**Review by keeganquigley — APPROVED** [review]

**Review by Noc2 — CHANGES_REQUESTED** [review]
@dOrgJelli could you also update this here: https://github.com/w3f/Grant-Milestone-Delivery/pull/610

**Comment by alxs** [comment]
Thanks @keeganquigley for jumping in here and to the team for the changes and additional information. @willemolding we've updated our T&C's again in the meantime, could you sign the CLA one last time?

**Review by alxs — APPROVED** [review]
Thanks everyone! I'm happy to approve this now and will share it with the rest of the committee.

**Review by Noc2 — APPROVED** [review]

**Review by keeganquigley — APPROVED** [review]

**Review by SBalaguer — APPROVED** [review]

**Review by dsm-w3f — APPROVED** [review]

**Pull request merged**
