### PR TITLE
Add substrate-parachain-PoS-template

### PR DESCRIPTION
**Pull request by octavei**
#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (aUSD/USDT) address for the payment of the milestones is provided in the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for your interest in our grants program. But you are currently adding seven files to our repository rather than a single application. Could you update this PR?

**Comment by octavei** [comment]
> Thanks for your interest in our grants program. But you are currently adding seven files to our repository rather than a single application. Could you update this PR?



> Thanks for your interest in our grants program. But you are currently adding seven files to our repository rather than a single application. Could you update this PR?

thank you so much for your suggestion. I have made corresponding modifications to the submitted pr.

**Comment by octavei** [comment]
> Thank you for submitting a grant application. We've assessed your submission and have found that it requires a higher level of technical detail in order to be considered for review. We encourage you to expand on it by providing a more precise specification/technical details. The [section on project details](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#project-details) in the application template is a good reference as to what type of information we expect applicants to provide, and these [category-specific requirements](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md) contain more precise guidelines depending on what type of software you're building. An area of the application that we often find to be insufficiently elaborated are the milestone deliverables. At a minimum, please indicate what languages/technologies you will be using to implement each deliverable, and provide a technical summary of its expected functionality. Note that deliverables should be tangible, reusable by other teams and in most cases not already present in the ecosystem. If they are, you will need to provide a comparison to existing implementations and explain why it makes sense to fund your approach. Also see our [FAQ](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md#-general) for a breakdown of what we fund and what we don't. Let us know as soon as you're done with your changes, and we'll give your application another look!

The focus of this grant is not on technical breakthroughs, but on the convenience of the community and developers. Let them no longer do repetitive work because there is no unified PoS template.

**Comment by octavei** [comment]
> > Thanks for your interest in our grants program. But you are currently adding seven files to our repository rather than a single application. Could you update this PR?
> 
> > Thanks for your interest in our grants program. But you are currently adding seven files to our repository rather than a single application. Could you update this PR?
> 
> thank you so much for your suggestion. I have made corresponding modifications to the submitted pr.

I have added the technical details. If there are other details that I need to add, I hope you can point them out and I will finish them as soon as possible. We think it is really important to have such a PoS development template, which will speed up the development of other teams without having to do repetitive things. Of course, in this template, you can also use PoA if you have requirements for random block generation.

**Comment by octavei** [comment]
> > > Thanks for your interest in our grants program. But you are currently adding seven files to our repository rather than a single application. Could you update this PR?
> > 
> > 
> > > Thanks for your interest in our grants program. But you are currently adding seven files to our repository rather than a single application. Could you update this PR?
> > 
> > 
> > thank you so much for your suggestion. I have made corresponding modifications to the submitted pr.
> 
> I have added the technical details. If there are other details that I need to add, I hope you can point them out and I will finish them as soon as possible. We think it is really important to have such a PoS development template, which will speed up the development of other teams without having to do repetitive things. Of course, in this template, you can also use PoA if you have requirements for random block generation.

At present, many parachain projects have not been able to use Substrate's Staking, which we think is a pity. This is not good for their token economic model, and also increases the economic burden on the project side, especially for small teams. On the other hand, Polkadot's technology needs to be unified, instead of each project party having its own Staking. They need such templates to develop.

**Comment by octavei** [comment]
> > > > Thanks for your interest in our grants program. But you are currently adding seven files to our repository rather than a single application. Could you update this PR?
> > > 
> > > 
> > > > Thanks for your interest in our grants program. But you are currently adding seven files to our repository rather than a single application. Could you update this PR?
> > > 
> > > 
> > > thank you so much for your suggestion. I have made corresponding modifications to the submitted pr.
> > 
> > 
> > I have added the technical details. If there are other details that I need to add, I hope you can point them out and I will finish them as soon as possible. We think it is really important to have such a PoS development template, which will speed up the development of other teams without having to do repetitive things. Of course, in this template, you can also use PoA if you have requirements for random block generation.
> 
> At present, many parachain projects have not been able to use Substrate's Staking, which we think is a pity. This is not good for their token economic model, and also increases the economic burden on the project side, especially for small teams. On the other hand, Polkadot's technology needs to be unified, instead of each project party having its own Staking. They need such templates to develop.

Dear @Noc2 , Is there anything else to add here? If so, please let me know. Merry Christmas

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update, and sorry for the late reply. In general, the application looks much better now. I just have a few more questions/comments:

- What exactly do you mean with “try-runtime”? If this already exists, could you link to it? 
- Could you specifically list all the “staking-related substrate native modules”? 
- What do you exactly mean by collectors? Or did you mean Collators here? In general, some of your text is a little bit hard to understand. I assume the main reason is that English isn’t your native language, which obviously isn’t a problem.

**Comment by octavei** [comment]
> * try-runtime



> * Collators

English is really not my native language, I'm trying to improve it. 

`try-runtime` means that I want to add code related to data migration testing in the client, just like [https://github.com/substrate-developer-hub/substrate-parachain-template/blob/main/node/src/command.rs#L234](https://github.com/substrate-developer-hub/substrate-parachain-template/blob/main/node/src/command.rs#L234), which is not currently in my template. `collectors` really means `Collators`.

**Comment by octavei** [comment]
> * staking-related substrate native modules

`staking-related substrate native modules` means adding Staking, ElectionProviderMultiPhase, VoterList and NominationPools modules to this pos template, and the code has been completed [here](https://github.com/Aband-Network/substrate-parachain-PoS-template/blob/main/runtime/src/lib.rs#L119).

**Comment by octavei** [comment]
> Thanks for the update, and sorry for the late reply. In general, the application looks much better now. I just have a few more questions/comments:
> 
> * What exactly do you mean with “try-runtime”? If this already exists, could you link to it?
> * Could you specifically list all the “staking-related substrate native modules”?
> * What do you exactly mean by collectors? Or did you mean Collators here? In general, some of your text is a little bit hard to understand. I assume the main reason is that English isn’t your native language, which obviously isn’t a problem.



> Thanks for the update, and sorry for the late reply. In general, the application looks much better now. I just have a few more questions/comments:
> 
> * What exactly do you mean with “try-runtime”? If this already exists, could you link to it?
> * Could you specifically list all the “staking-related substrate native modules”?
> * What do you exactly mean by collectors? Or did you mean Collators here? In general, some of your text is a little bit hard to understand. I assume the main reason is that English isn’t your native language, which obviously isn’t a problem.

We want to make a general POS parachain development template, just like the POA development template

> Thanks for the update, and sorry for the late reply. In general, the application looks much better now. I just have a few more questions/comments:
> 
> * What exactly do you mean with “try-runtime”? If this already exists, could you link to it?
> * Could you specifically list all the “staking-related substrate native modules”?
> * What do you exactly mean by collectors? Or did you mean Collators here? In general, some of your text is a little bit hard to understand. I assume the main reason is that English isn’t your native language, which obviously isn’t a problem.

We want to make a general POS parachain development template, just like the [POA development template](https://github.com/substrate-developer-hub/substrate-parachain-template). This is very valuable. It will save developers time if they want to develop a parachain with PoS.

**Comment by octavei** [comment]
> Thanks for the update, and sorry for the late reply. In general, the application looks much better now. I just have a few more questions/comments:
> 
> * What exactly do you mean with “try-runtime”? If this already exists, could you link to it?
> * Could you specifically list all the “staking-related substrate native modules”?
> * What do you exactly mean by collectors? Or did you mean Collators here? In general, some of your text is a little bit hard to understand. I assume the main reason is that English isn’t your native language, which obviously isn’t a problem.

We want to make a general POS parachain development template, just like the [POA development template](https://github.com/substrate-developer-hub/substrate-parachain-template). This is very valuable. It will save developers time if they want to develop a parachain with PoS.

**Comment by octavei** [comment]
> > Thanks for the update, and sorry for the late reply. In general, the application looks much better now. I just have a few more questions/comments:
> > 
> > * What exactly do you mean with “try-runtime”? If this already exists, could you link to it?
> > * Could you specifically list all the “staking-related substrate native modules”?
> > * What do you exactly mean by collectors? Or did you mean Collators here? In general, some of your text is a little bit hard to understand. I assume the main reason is that English isn’t your native language, which obviously isn’t a problem.
> 
> We want to make a [general POS parachain development template](https://github.com/Aband-Network/substrate-parachain-PoS-template), just like the [POA development template](https://github.com/substrate-developer-hub/substrate-parachain-template). This is very valuable. It will save developers time if they want to develop a parachain with PoS.

**Comment by octavei** [comment]
I have made changes to the [application](https://github.com/Aband-Network/Grants-Program/blob/master/applications/substrate-parachain-PoS-template.md), maybe the previous information was not described accurately enough. Thank you so much for your kind and valuable reply.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. I have one last comment: could you also add unit tests and not only "manual test"?

**Comment by octavei** [comment]
> 



> Thanks for the update. I have one last comment: could you also add unit tests and not only "manual test"?

Both unit tests and manual tests are provided.

**Comment by Noc2** [comment]
Could you add this to the milestone and the specification of it?

**Comment by octavei** [comment]
> Could you add this to the milestone and the specification of it?

I just added it.

**Comment by octavei** [comment]
> Could you add this to the milestone and the specification of it?

Thanks for replying so quickly. If there is anything else to add, I will do it as soon as possible.

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I'm happy to go ahead with it and mark the application as ready for review.

**Review by SBalaguer — APPROVED** [review]

**Pull request merged**
