### PR TITLE
Substrate polywrapper application

### PR DESCRIPTION
**Pull request by mpetrunic**
### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

Polywrapper in Rust which enables users to interact with substrate-based chains using any language on any platform.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Comment by semuelle** [comment]
Hi Marin, thank you for your application. Looks interesting! We will look into it as soon as possible.

In the meantime, could you remove the template text from the `Development Status` section, and ideally replace it with what you have done so far?

**Comment by mpetrunic** [comment]
> Hi Marin, thank you for your application. Looks interesting! We will look into it as soon as possible.
> 
> In the meantime, could you remove the template text from the `Development Status` section, and ideally replace it with what you have done so far?

Hey @semuelle, "Development Status" section is updated.

**Comment by semuelle** [comment]
Thanks for the update, @mpetrunic. I will share this with the rest of the team.

**Comment by Noc2** [comment]
@mpetrunic I just sent you an email to organize a pitch call.

**Comment by alxs** [comment]
Hi Marin, would you mind further breaking down the costs/deliverable list before the pitch call? Traditionally, milestones have been roughly under the $30k mark and we've always required a detailed list of deliverables we can base the evaluation on, so these seem pretty significant amounts to me with little specification. Besides, assuming the FTEs and estimated duration of each milestone you provide are accurate, the rate you're asking for is pretty outlandish if you don't mind me saying! That being said, the project looks fantastic - I'm looking forward to the pitch call.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks again for the presentation and sorry for the late reply. It was really helpful. As quickly already discussed during the meeting. I think it would either make sense to reduce the scope of this initial grant, for example remove milestone 3 and only implement one pallet as an example and tutorial for others or replace milestone three with a generic tool that can be used for all kinds of pallets. Furthermore, during the meeting, you mentioned that you already have some kind of specification, could you share this? And in general, it would be helpful if you could reduce the current rate. To be honest, my biggest concern here is that you develop this grant only for the money + marketing, but you don’t maintain it or improve the project further and instead focus on other ecosystems. So a maintenance period as part of this grant might also help with this.

**Comment by kev-ngo** [comment]
Hey @alxs and @Noc2, thank you again for meeting with us.  This is great feedback.  We're discussing internally on how to best refine our proposal and present the changes to you.  Stay tuned!

**Comment by dOrgJelli** [comment]
Apologies for the delay here @Noc2, the end of year has been very hectic. Will be sure to push our changes based on the feedback provided very soon. Hope everyone has a wonderful holiday season!

**Comment by Noc2** [comment]
Np. I’m currently ooo anyway.

**Comment by alxs** [comment]
@dOrgJelli @kev-ngo any updates? Note that we generally close applications after 2 weeks of inactivity.

**Comment by dOrgJelli** [comment]
@alxs @Noc2 @semuelle please see the updated proposal. Awaiting your continued feedback :clap:

**Comment by alxs** [comment]
Hey @dOrgJelli. I'm afraid in its current state I won't support the proposal, since it's still heavily underspecced and overpriced for I think the largest grant we'd ever have accepted. In particular milestone 1 looks to me like it should cost 1/10th of the price as all it currently describes is writing a GraphQL schema. Besides, the rates you're asking for are comparable to those of leading auditing companies, and this not being highly specialised code I frankly don't see why we should be ready to pay them. Lastly, maybe I'm missing something but I don't think it makes sense to deliver a wrapper for the balances pallet first for $55k and then a generator that allows doing this automatically. Thank you for applying and best of luck with the project.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the update. In general, I think the project is interesting and I would like to support it. However, a rate of 55000 $ per month is difficult to justify for this project at this stage in my opinion. In the end, you should also have an interest in expanding to our ecosystem, otherwise the risk on our side is extremely high that you won’t continue to work on it anyway. Would you be willing to reduce the price?

**Comment by dOrgJelli** [comment]
Hi @alxs and @Noc2, thank you for this feedback.  We're working closely with ChainSafe to figure out pricing & scope.  This integration is high priority on our roadmap, and we believe it'll bring tremendous value to Polkadot's developer ecosystem.  We hope to present you an update within a week.

**Comment by mpetrunic** [comment]
@alxs @Noc2 @semuelle We updated the proposal reflecting that Polywrap DAO has approved co-sponsoring the grant.

**Comment by dOrgJelli** [comment]
Additionally please note the reduction in scope to only the first milestone (substrate core integration)

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. In this case could you also integrate an article in the first milestone see https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md. Additionally could you list under costs of the milestone only the web3 costs, so it doesn’t lead to any confusion. And just for your information, if you reduce the grant to 50k and level 2, you only need 3 approvals, which is a lot easier to get.

**Comment by alxs** [comment]
@mpetrunic @dOrgJelli I'm happy to hear that the Polywrap DAO would co-fund this milestone. However, the application still lacks information about what it is that you want to build. Currently, all you provide is the following list:

- Bootstrap polywrapper project using w3/cli
- Write graphql schema for substrate core methods
- Implement graphql schema methods in rust using Polywrap http plugin
- Deploy polywrapper to ipfs

Since we don't cover deployment costs, only the first 3 items are relevant. For me, that is too vague to gauge the scope of the project and to understand why it's worth $100k. Could you please be more prices, e.g. what is `w3`? Is the first item a deliverable that will allow others to bootstrap a project, or is it a step in your development? What are the scheme methods you want to implement in rust, what is the Polywrap HTTP plugin and why do you need to use it? Please list each item as a deliverable and use the specification column to describe its functionality and tech stack. If possible, break them up into smaller deliverables.

**Comment by dOrgJelli** [comment]
Hi again @Noc2 @alxs, we've made some updates, would appreciate one more review. Happy to answer any questions you may have.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the additional details. But could you also take a look at my comment above: 

> In this case could you also integrate an article in the first milestone see https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md. Additionally could you list under costs of the milestone only the web3 costs, so it doesn’t lead to any confusion. And just for your information, if you reduce the grant to 50k and level 2, you only need 3 approvals, which is a lot easier to get.

**Comment by dOrgJelli** [comment]
@Noc2 the additions have been added in the latest commits.

**Review by Noc2 — DISMISSED** [review]
Thanks for the update. I’m willing to support it and will share the application again with the rest of the team. However, keep in mind that you need 5 approvals (because it’s above 50k), which might be difficult to get.

**Review by alxs — DISMISSED** [review]
Thanks for the additional details, I'm also happy to accept it in its current form. However, I really suggest you reduce the price to $50k since it's only 10% less but will significantly improve the chances of your application being accepted, seeing as it hasn't received much interest from anyone else since you applied. FYI we can also discuss [VC introductions](https://github.com/w3f/Grants-Program#rooster-level-3) for a level 2 grant if you care about that.

**Review by gautamdhameja — DISMISSED** [review]
I am willing to support it too. And I agree with the previous comments that if you bring it down to 50k, then you are already good to go.

**Comment by SBalaguer** [comment]
Thank you all for such an interesting discussion. I'm willing as well to support this implementation, but yet again for 50K. Lowering that will basically get you the grant.

**Comment by dOrgJelli** [comment]
Hey all, the Polywrap DAO has a proposal going live today that will increase its grant for ChainSafe by $5k. This will allow the W3F grant to be lowered by $5k, meeting the $50k level 2 requirement.

Will report back with the result shortly :)

**Comment by Noc2** [comment]
That's great to hear. Thanks for the update!

**Comment by laboon** [comment]
It looks like you already have the 3 reviewers necessary if you're going to do a Level 2 grant, but just wanted to add that I'll be keeping an eye on this, looks like a very useful project for the space.

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I’m happy to go ahead with it. Let get this finally merged!

**Review by sbp-parity — APPROVED** [review]
Thanks! Looking forward to this.

**Review by takahser — APPROVED** [review]

**Pull request merged**
