### PR TITLE
GIRAF - Legislation for communities

### PR DESCRIPTION
**Pull request by slonigiraf**
#### Project Abstract

We plan to build a system on top of Substrate that allows the creation and lobbying of laws in groups of different size: from small communities to a size of a country. It will be used in groups that lack legislation due to the small size of a group or in bigger societies to speedup the creation of a public consensus.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`[project_name.md](http://project_name.md/)`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (aUSD/USDT) address for the payment of the milestones is provided in the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@[_______:matrix.org](http://_______:matrix.org/)` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by Noc2** [comment]
Also could you still sign the latest terms and conditions (see CLA bot above)?

**Comment by slonigiraf** [comment]
@Noc2 David, thank you very much for the prompt review. I've changed the 1st Milestone description to incorporate your suggestion about the substrate functionality. It's good idea to submit slon token to some EVM parachain to be able to make a bridge to our current ecosystem. However I'm not sure that we can maintain such bridge now, as our current implementation of SLON token is a native [balance pallet of our parachain](https://ui.slonigiraf.org/#/accounts) and the bridge is not our first in line target. The mentioned EVM slon token repo was used to make a first token release on Ethereum in 2019, then we switched to Polkadot and discontinued Ethereum version of the token.
I'm happy with your interest on our progress during this year. So let me update you what have been done since the finishing our previous web3 grant.
- we've migrated the recommendation-letter-pallet to Substrate v4 to be able use it inside the parachain: [updated pallet version](https://github.com/slonigiraf/recommendation-letter), [updated node](https://github.com/slonigiraf/slon-node-testing)
- we've created a new UI compatible with polkadot.js wallet to use recommendation-letter-pallet. See [repo](https://github.com/slonigiraf/slonigiraf-front-end) and our current [web-site](https://ui.slonigiraf.org/#/recommendations)
- updated web site: [https://slonigiraf.org/](https://slonigiraf.org/)
- migrated all our services to another cloud provider and orchestrate them as docker containers - not standalone servers as they were.
- we've grown from a single person project to the 4 person team able to drive the project faster.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update, and sorry for the late reply. Currently, a lot of things need to be done before Christmas, and part of the team is already OOO. I have one follow-up question/comment: Since your first milestone is now focused on the substrate chain, I'm not sure your second milestone still makes sense. For example: "As a user of polkadot.js wallet fork, I can sign up and sign in to the app." What app do you mean here? Independent of it, I will mark the application as ready for review so that others take a look at it as well.

**Comment by slonigiraf** [comment]
@Noc2 David, many thanks for pointing me to the description of Milestone 2. I've corrected it as you recommended.

**Comment by alxs** [comment]
A reminder to sign our T&C's (presented by the CLA bot [above](https://github.com/w3f/Grants-Program/pull/1364#issuecomment-1351891041)).

**Comment by slonigiraf** [comment]
> A reminder to sign our T&C's (presented by the CLA bot [above](https://github.com/w3f/Grants-Program/pull/1364#issuecomment-1351891041)).

@alxs is it signed now? I've used the button above.

**Comment by alxs** [comment]
@slonigiraf it doesn't look like it. You need to click on the link.

**Comment by reshetovdenis** [comment]
> @slonigiraf it doesn't look like it. Please note that since [reshetovdenis](https://github.com/reshetovdenis) authored the first commit, he needs to sign it too.
Done)) many thanks!

**Review by Noc2 — CHANGES_REQUESTED** [review]
I'm sorry for not getting back to you sooner, and thanks for the update. So if I understand it correctly, you now want to create a fork of [polkadot.js/app](https://github.com/polkadot-js/apps), instead of your own UI, correct? In this case, you should probably also remove the part about the UI from the application: "we also plan to develop a user interface (UI) for the database." And I noticed that you say the FTE is 4 for each milestone. What will the other team members contribute to these milestones? It currently looks like only you are contributing to the project on GitHub, but I might be wrong.

**Comment by slonigiraf** [comment]
> hat will the other team members contribute to these milestones? It currently looks like only you are contributing to the project on GitHub

@Noc2 David, thank you very much for new questions. Our new team members mentioned in milestones are joining the project now and I'm trying to get money to pay for their future work. So if Web3 foundation will accept our grant application they will contribute to our Github. We think to split the work as following: Rust: Denis Reshetov and Aleksey Pastutsan; JavaScript: Ilya Moskvin, Aleksey Pastutsan and Denis Reshetov; Project management, UI/UX, documentation: Natalie Andreeva.
About UI - we are planning to develop React/Typescript modules that can be used in any Substrate based chain to interact with the Substrate module as it was done recently with other our pallet: [source code](https://github.com/slonigiraf/slonigiraf-front-end/tree/master/packages/page-recommendations) and [UI](https://ui.slonigiraf.org/#/recommendations).
Do you mean that you recommend us instead create an UI that can't be directly integrated with polkadot.js/app, for example like [this app](https://github.com/slonigiraf/recommendation-letter-example-ui)?

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the reply. My recommendation wasn’t to create a UI that could be integrated into polkadot.js apps. But I was a little bit confused regarding what you meant by “polkadot.js wallet fork.” Maybe you can specify this a little bit more or link to the code that needs to be forked, just for clarification.

**Comment by slonigiraf** [comment]
@Noc2 David, I agree fork sounds confusing. Actually we plan to develop a module for polkadot.js not fork of it. You know that polkadot.js UI consists of modules, see page... in this [repo](https://github.com/polkadot-js/apps/tree/master/packages). We plan to add a functionality by providing an additional page-giraf module. We did the same way recently with other our pallet: [page-recommendations](https://github.com/slonigiraf/slonigiraf-front-end/tree/master/packages/page-recommendations), [UI](https://ui.slonigiraf.org/#/recommendations).

**Review by Noc2 — CHANGES_REQUESTED** [review]
Sorry for the late reply here. I would recommend integrating this into the application. So it’s easier also for the rest of the committee to understand this as well as for the evaluation process. In the meantime, I will ping the rest of the committee again to take a look at it. However, I personally won’t approve the application. Besides some of the concerns that I raised above, I also think that “lobbying” won’t be put on-chain any time soon. But this is just my personal opinion, and others might have a different opinion about the project.

**Comment by slonigiraf** [comment]
@Noc2 David thank you very much for the review. We've incorporated the requested changes.

**Comment by Noc2** [comment]
Thanks for integrating the changes and all the effort you put into this application. However, the grants committee isn’t willing to support the application, so I’m closing the PR. Independent of it, we wish you all the best for your project. Let me know if you have any questions.

**Pull request closed without merging**
