### PR TITLE
ISO-8583 RFP Proposal

### PR DESCRIPTION
**Pull request by adit313**
#### Project Abstract

> This proposal is in [response to the ISO-8583 RFP, that aims to make it easy and possible for the traditional finance industry to leverage substrate and ink! smart contracts to interact with ISO 8583 in various ways](https://github.com/w3f/Grants-Program/blob/master/rfps/open/ISO_8583.md). While it seems the original RFP was primarily for a straightforward techincal implementation, the actual implementation of ISO-8583 on a distributed, permissionless architecture has several unsolved challenges. This grant proposal is to research and develop acceptable solutions to those challenges or at the very least provide the Web3.0 Foundation with a comprehensive view of the options and tradeoffs.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [X] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [X] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [X] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [X] The software delivered for this grant will be released under an open-source license specified in the application.
- [X] The initial PR contains only one commit (squash and force-push if needed).
- [X] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — APPROVED** [review]
Thanks a lot for the application. I’m happy to support it. Feel free to also include some research regarding ISO-20022 and maybe also potentially problematic patents, like https://patentimages.storage.googleapis.com/71/bc/cc/05e3ac26081906/US20160342989A1.pdf

**Comment by Noc2** [comment]
Fyi: We are more than happy to support the implementation of your research after you finished this project.

**Review by SBalaguer — APPROVED** [review]
Thanks for putting this proposal forward, very much looking forward to it. I'd also be happy to see an implementation after the research.

**Comment by adit313** [comment]
@Noc2 @SBalaguer Sorry guys, just wanted to give an update as it's been 6 weeks. It's been a lot of information to sort through and I've been trying to be as comprehensive as possible. I ended up doing a dive into competitive solutions to see if any blockchains support ISO8583 today (none do) and how all of the current batch of "crypto payment cards" work. In addition, I've been digging into VISA's blockchain strategy and all they've done/are planning to do in the space, it's taken me a bit longer than expected, but I should be wrapped up by late next week.

Again, sorry for the delays, but I think I have a pretty good summary and architecture for you guys.

**Comment by takahser** [comment]
@adit313 thanks for keeping us posted. That's not an issue at all, we're looking forward to seeing your results :)

**Comment by keeganquigley** [comment]
Hi @adit313 do you by chance have another update for us regarding your progress?

**Comment by adit313** [comment]
Hi @keeganquigley! This application was successfully delivered and closed but it was only a deep dive into the technical details of ISO8583 and the challenges adopting it for the blockchain. There is a potential architecture that addresses the shortcomings however that utilize the "oracle problem" as a way to deliver a centralized solution to a functionality that needs to inherently be centralized. The resulting report is here: https://github.com/adit313/ISO8583-Blockchain-Integration-Plan

In terms of follow-on, I apologize for the radio silence. This is a project I plan to pick up in the coming year, and invest in heavily after the holiday. After issuing the report, I attempted to join the substrate builders program for the follow up build and was essentially told that I didn't have enough technical skills to join the program. I was starting a job as the lead Web3 dev at Open Earth Foundation, an open source environmental non-profit, so I was pretty busy and I really didn't want to prove my dev skills.

I've been busy building some necessary skills in the meantime though, I launched a chainlink oracle node and have been playing with the intricacies of how best to get centralized command and control onto the blockchain. I know it's not ideal, but you'll see from the report, there aren't many ways around it if you want to integrate with Visa/MC's payment networks.

**Comment by adit313** [comment]
Hi @keeganquigley, it's been a while so I wanted to give an update as to why progress is so slow and taking so long. I've also received a Phase I SBIR award grant from the U.S.'s National Science Foundation in Distributed Ledger Technology so I've been completely swamped with blockchain research work. I just haven't really had time to sit down and focus on this. I just wanted to apologize and to keep you guys in the loop. 

It sounds like project is of interest to the Web3 Foundation so I'm happy to jump on a call and talk through options. It's all open source research and work so there are plenty of options. I'm more than happy to help another team tackle it if you know of any who are looking for a project to take on. We can also discuss my timelines and figure out a plan if you prefer I work on it, but to be honest, I'm going to be swamped for about 5-6 months with my NSF work.

**Comment by keeganquigley** [comment]
@adit313 thanks for keeping us in the loop! That's no problem at all seeing as you already completed the grant. But yes I would love to have a call to discuss next steps for whatever team decides to work on this! I'm in the EST time zone, here is a link to my Calendly: https://calendly.com/keeganweb3/meeting-with-grantee

**Pull request merged**
