### PR TITLE
amendment: Split milestone 2 into 2 parts

### PR DESCRIPTION
**Pull request by katerinabc**
#### Project Abstract

Previous pull request: https://github.com/w3f/Grants-Program/pull/1482
Milestone 2 discussion: https://github.com/w3f/Grant-Milestone-Delivery/pull/1047#issuecomment-1881796131

**Brief description**
Building a strong community requires metrics that measure the quality and stickiness of a community, and not just vanity metrics. We use behavioral and network science to create a community health dashboard for members and moderators to understand and get a bird's eye view of the health of their community.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) address in the application).
- [x] I am aware that, in order to receive a grant, I (and the entity I represent) have to successfully complete a KYC/KYB check.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by semuelle — CHANGES_REQUESTED** [review]
Hi @katerinabc. Unfortunately, Github doesn't allow conditional approval rules, so 5 approvals is the default as it's the maximum we need. Once you have three approvals, we merge it manually. 

Regarding the CLA: it's possible that @takahser is the one who needs to sign it, as he appears as commit author. 

But could you submit a PR from a more recent fork? You are trying to add the whole document again, which is already in our repo. It also makes it hard to see what has been changed.

**Review by takahser — CHANGES_REQUESTED** [review]
@katerinabc could you resolve the merge conflicts?

image

**Comment by katerinabc** [comment]
Ok, gonna close this pull request and submit the amendment using a more recent fork

**Comment by keeganquigley** [comment]
Conversation has moved here: https://github.com/w3f/Grants-Program/pull/2195

**Pull request closed without merging**
