### PR TITLE
Updated grant application for Qlone.ai

### PR DESCRIPTION
**Pull request by QLONEAI**
#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by keeganquigley — CHANGES_REQUESTED** [review]
Thanks for the application @QLONEAI but could you please update the formatting to adhere to the [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md)?  For example the title needs to be fixed, and an [Overview](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#overview-1) section needs to be added with the total costs.

You can also remove all the template text and replace it with your own. The delivery tables also need to be fixed to match the template. Essentially, the left column is the name of the deliverable and the right column contains the description. Thanks!

**Comment by QLONEAI** [comment]
Please reopen, we will fix it today.

**Comment by Noc2** [comment]
Done

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the updates. However, the formatting of the milestone tables still seems to be off, and there are still not a lot of technical and concrete details regarding the deliverables. For example, will this be implemented as ink! smart contract or pallet? Did you take a look at existing pallets/smart contracts and can you reuse some of them? What is the exact functionality of your solution?

**Comment by semuelle** [comment]
pinging @QLONEAI

**Comment by Noc2** [comment]
I'm closing this again due to inactivity. Let me know if I should reopen it.

**Pull request closed without merging**
