### PR TITLE
Skynet Substrate - update

### PR DESCRIPTION
**Pull request by dghelm**
### Project Abstract

This project updates Skynet and Substrate Integration #489 to amend payout address, make note of missing initial timeline, and adjustments of publishing an SDK for use in off-chain workers alongside working sample repos.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### CODE REVIEW

**Comment by dghelm** [comment]
For additional context, the repos we've worked in are:

https://github.com/SkynetLabs/skynet-substrate
(Documentation: https://skynetlabs.github.io/skynet-substrate/skynet_substrate/ )
https://github.com/SkynetLabs/skynet-substrate-offchain-worker-node/tree/skynet-substrate/frame/examples/offchain-worker
https://github.com/SkynetLabs/skynet-substrate-front-end-example

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the PR and the update. Could you potentially also update the “Total Estimated Duration” and the duration of the milestone? Thanks!

**Comment by alxs** [comment]
Thanks for the amendment @dghelm. In addition to what David said, could you also update the deliverables as you describe?

**Comment by dghelm** [comment]
@alxs @Noc2 Thanks for the feedback -- I've changed the milestone to point that we should be able to finish milestone submission feedback in the next couple of weeks, along with updating language to focus more on the SDK implemented in an OCW.

**Review by alxs — APPROVED** [review]
LGTM. Thank you for the changes.

**Review by takahser — APPROVED** [review]

**Pull request merged**
