### PR TITLE
Blockchain Interoperability through DNS and Asset Discovery

### PR DESCRIPTION
**Pull request by khalidzahra**
#### Project Abstract

This project aims to enhance blockchain interoperability by addressing a fundamental issue: DNS and network and asset discovery. Inspired by traditional DNS, our approach allows different blockchain networks to opt in and make their networks, assets, and services discoverable by claiming a domain and registering it on appropriate networks. This facilitates the discovery of blockchain networks and their assets with user-friendly querying methods. Therefore, the project ensures seamless connectivity and discoverability, which are essential for blockchain ecosystems' growth. We introduce incentives for nodes maintaining the DNS infrastructure, providing a sustainable economic model that promotes stability and dynamic participation, ultimately contributing to a cohesive Internet of Blockchains.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [ ] Payment details have been provided (Polkadot AssetHub (DOT, USDC & USDT) address in the application and bank details via email, if applicable).
- [x] I understand that an agreed upon percentage of each milestone will be paid in vested DOT, to the Polkadot address listed in the application.
- [x] I am aware that, in order to receive a grant, I (and the entity I represent) have to successfully complete a KYC/KYB check.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by sara-rouhani** [comment]
I have read and hereby sign the Contributor License Agreement.

**Review by semuelle — CHANGES_REQUESTED** [review]
Thank you for the application, @khalidzahra. As this is a semi-private application, we will follow up via email. In the meantime, could you add contact name and email to the document as per [the template](https://github.com/w3f/Grants-Program/blob/0c699389dbf4acce467360fd9186ce8da2204ce7/applications/application-template.md?plain=1#L73-L74)?

**Comment by khalidzahra** [comment]
> Thank you for the application, @khalidzahra. As this is a semi-private application, we will follow up via email. In the meantime, could you add contact name and email to the document as per [the template](https://github.com/w3f/Grants-Program/blob/0c699389dbf4acce467360fd9186ce8da2204ce7/applications/application-template.md?plain=1#L73-L74)?

Thank you for your swift reply. I have added the contact information to the application document as you requested.

**Comment by PieWol** [comment]
I'll close this public application in favor of the private application we have received. In case of any questions or feedback please feel free to send us an e-mail.

**Pull request closed without merging**
