### PR TITLE
FiDi DotSight: M4 proposed to be taken out of scope

### PR DESCRIPTION
**Pull request by fidiroman**
Hi team,

Hope you're all doing great. DotSight has evolved quite a bit since our original proposal!

This revision aims to address that — regarding milestone 4 (SQL querying), we're proposing to move away from that objective for the time being. The community's feedback has been clear: the priority is on effortless, code-free analytics. Our latest milestone delivery reflects just that, with a user-friendly platform where dashboards are created in seconds, rich with a variety of metrics and parachain data. We've also integrated Parity’s DotLake dataset as well as Chainlink, DappRadar, Subsquid, DeBank, Ankr, and more providers—going well beyond our original scope from last year.

Looking forward to your thoughts and excited as ever to keep delivering for our Polkadot users.

### CODE REVIEW

**Comment by fidiroman** [comment]
Also, linking the most recent milestone's [delivery](https://github.com/w3f/Grant-Milestone-Delivery/pull/1157) here for the context.

**Review by keeganquigley — APPROVED** [review]
Thanks for the update, changes look good to me.

**Comment by fidiroman** [comment]
I have read and hereby sign the Contributor License Agreement.

**Review by semuelle — COMMENTED** [review]
I trust your judgement on this, but if you don't mind me asking, how did you collect this feedback from the community? I see a need for easy to use visualisations, but for me personally, the platform would be incomplete if I wasn't able to construct my own.

**Comment by fidiroman** [comment]
Thanks Sebastian @semuelle , we hear you! And, frankly, we had quite a discussion internally back in November regarding what direction to take first here, and what second. We’ve gathered feedback from ambassadors to Moonbeam, Astar, Distractive.xyz, data providers, e.g., Subsquid, oracles, e.g., DIA, Chainlink, and engaged our early adopters on Discord -- all of them together shaped the direction.

It’s been a balancing act between “the non-dev community wants code-free analytics” and “developers want SQL and a high level of customization”. We will soon have both, but we had to decide which one to enable first and foremost and which user group is larger today. Let me know if that makes sense!

**Pull request merged**
