### PR TITLE
Fix website sidebar

### PR DESCRIPTION
**Pull request by randombishop**
Refactored website from fully autogenerated sidebar to manually defined.
To do that:
- Renamed `rfps` folder to `RFPs`
- Renamed `Support Docs` to 'Support_Docs'
- Moved `index.md` from subfolders to `docs` root to exclude them from autogenerated menu items
- Defined the new sidebar in sidebar.js
- Added simlinks so that there's a docs folder relative to the applications folder

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
What is the benefit of renaming docs/Support Docs to docs/Support_Docs? Because if we update this, we also need to double-check again all the links in the delivery repo and the wiki etc.

**Comment by randombishop** [comment]
@Noc2 Just felt like a better practice to avoid spaces in website folders, old traumas from working on windows in the 90s :)
Renamed it back to `Support Docs`

**Review by Noc2 — APPROVED** [review]

**Comment by spencerbh** [comment]
link to RFPs in README.md broke

**Comment by Noc2** [comment]
@spencerbh Thanks! I fixed it: https://github.com/w3f/Grants-Program/commit/3595659a4d089a9905edbae085eb99835a4c67c9 You can find the rfps here: https://github.com/w3f/Grants-Program/blob/master/docs/rfps.md

**Pull request merged**
