### PR TITLE
helixstreet grant application / Level 2

### PR DESCRIPTION
**Pull request by helixstreet**
### Project Abstract

helixstreet is a project to extend the use of Blockchain technology to genomics. helixstreet chose substrate as technology to implement a pallet to store a Merkle tree hash of genomic raw sequencing data. Relationsships ( ancestry ) can be documented in the blockchain based on relationships between genomic data. Currently we are planning to implement helixstreet as parathread.

Ancestry data and personal genomic relationships are today centralized. helixstreet's approach allows the representation of ancestry data in a decentralized manner.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [x] **Level 2**:  Up to $50,000, 3 approvals

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Comment by helixstreet** [comment]
Now signed [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=820)

**Comment by helixstreet** [comment]
Now signed [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=820)

**Review by rolfreddy — DISMISSED** [review]

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application and sorry for the late reply here. In general this sounds interesting. Something to be aware of: Deliverables 0a-0d of the template are mandatory for all milestones, and deliverable 0e at least for the last one, see https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md Also could you add a little bit more details about the rust program? Potentially as a separate deliverable number 2. For example: is the rust program a CLI Tool, what is the functionality for the program? Additionally, where do you plan to store the data itself (Ipfs?)?

**Comment by helixstreet** [comment]
Thx David for the feedback. The mandatory deliverables are added. The rust program is removed as milestone for the grant application - it would be difficult to test the rust program in a docker image due to the space limitations of docker images.
The storage of the data itself is in the early phase in the hands of the owner of the private key.  Ipfs is for sure in a later stage a good possibility ( either encrypted or public ).

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the quick reply and update. In this case, I would rather recommend getting rid of the docker image.  Currently your delivery basically only contains a pallet, which is able to store some hashes. This is rather simple and could be done very quickly (and was already done by multiple teams for multiple purposes).

**Comment by helixstreet** [comment]
Thanks indeed for the clarification. I added Milestone 2.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. Could you add more details regarding the Program (e.g. previously your applications mentioned that you are going to use rust for it, what functionality does it have,etc. )? Also is there any additional on-chain logic, which you are planning to write that you could integrate into the grant (e.g. approving/trusting hashes of data, selling this data, some kind of identity system etc.)? And in general, is it possible to share more information? Your website also contains very little information about the project itself in its current state.

**Comment by helixstreet** [comment]
Thx for the feedback. I added some details regarding the program and the project. I am quite aware and agree that there are better teams who could realize the blockchain part far quicker. This Level 1 grant proposal is an early stage application specific parathread which extends the use of Polkadot/Kusama ecosystem to a whole new use case and user base.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update and thanks for being transparent about it. I will mark the application as ready for review and share it with the rest of the team, but I personally think it’s a little bit expensive at this stage. 

Also could you maybe expand on your background regarding the  genomic sequencing part and why it’s useful to combine this with a blockchain? For example I see a lot of legal problems with this. And/or could you potentially reduce the price further? Also to be completely transparent here, in my experience it’s usually not the best to have already so many details about the [tokenomics](https://helixstreet.io/tokenomics/), but barely any infos about the project itself.

**Comment by takahser** [comment]
Hi @helixstreet 

Thanks for your application and your interest in the web3 foundation grants program!

Regarding deliverable _1. Substrate module: genomics_ I'm with @Noc2, I think it's fairly straightforward to implement as you already seem to partly have done [here](https://github.com/helixstreet/helixstreet-node2/blob/392e10912d8c58606eb5b9edd07830d49b6f2b07/pallets/genomics/src/lib.rs#L68).

Regarding deliverable _2. Program to generate Hashtree_, I have a few questions:

> (..) store a vector ( or the main root ) of the root hashes automatically in the Blockchain assigned to the private key

So you want to use the merkle hash as entropy for a user's private key, is that correct?

> A flag is needed to distinguish between entries made by a machine ( e.g. Sequel II ) or by the identified owner of the DNA raw data

I'm definitively not an expert in that area, but I suppose any DNA sequencing would happen by a machine, right? Also, how would you safely identify the owner of the DNA using a script? In general, I have the impression that the script will just create a hash tree from the DNA raw data and store it on the blockchain, is that fair to say?

Furthermore I'm not sure how your pallet could be used, so it might be helpful if you could come up with some concrete use cases.

To wrap up, I think for the scope of your project (according to my current understanding) the price is too high which is why I'm currently not ready to support it.
Pls let me know if I got something wrong because again, I'm far from an expert in the field and I might be missing something.

**Comment by helixstreet** [comment]
Hi
> Hi @helixstreet
> 
> Thanks for your application and your interest in the web3 foundation grants program!
> 
> Regarding deliverable _1. Substrate module: genomics_ I'm with @Noc2, I think it's fairly straightforward to implement as you already seem to partly have done [here](https://github.com/helixstreet/helixstreet-node2/blob/392e10912d8c58606eb5b9edd07830d49b6f2b07/pallets/genomics/src/lib.rs#L68).
Well i thing that's just a template and would be far from production ready. I would like to have a pallet which would be production ready in a parathread with correct weights and could accept calls to prove authenticity of Sequencing data.

> 
> Regarding deliverable _2. Program to generate Hashtree_, I have a few questions:
> 
> > (..) store a vector ( or the main root ) of the root hashes automatically in the Blockchain assigned to the private key
> 
> So you want to use the merkle hash as entropy for a user's private key, is that correct?
> 
> > A flag is needed to distinguish between entries made by a machine ( e.g. Sequel II ) or by the identified owner of the DNA raw data



> 
> I'm definitively not an expert in that area, but I suppose any DNA sequencing would happen by a machine, right? Also, how would you safely identify the owner of the DNA using a script? In general, I have the impression that the script will just create a hash tree from the DNA raw data and store it on the blockchain, is that fair to say?
In the case the blockchain entry is made directly by a machine ( which would be ideal, because, that ensures nobody has changed the data )  the private key would be a "technical" private key. In this case there is the need for a governance to assign the data to a human being who owns the data. It's absolutely clear there is more functionality needed. For the future it is incredible important to know no one has modified anything. The next evolving tech is reverse sequencing -(e.g. TWIST ) creating DNA from the data and recreating life. 
> 
> Furthermore I'm not sure how your pallet could be used, so it might be helpful if you could come up with some concrete use cases.
The pallet in this basic functionality just ensures to have an immutable record of a sequencing run. Sequencing in HiFi is still expensive - but gets cheaper from year to year ( Moore's Law in genomics ) 
> 
> To wrap up, I think for the scope of your project (according to my current understanding) the price is too high which is why I'm currently not ready to support it. Pls let me know if I got something wrong because again, I'm far from an expert in the field and I might be missing something.

Well - i calculate 30% taxes; Some additional effort at the end to get the grants and still would think it's a very very small subsidy for the project. But i am not doing it for the money - more to get through the process in case i start Level 2 - which would be the interesting because of the badge.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Just to add here: You could theoretically immediately apply for a level 2 grant, you don’t need to finish a level 1 grant first. Also you can apply for a level 2 grant and for example only ask  for 1k.

**Comment by helixstreet** [comment]
Thx indeed for the hint. I did this ( L2 / 1k ). The tokenomics is removed ( from the menu - the link will work but it's not referenced in the menu )

**Review by Noc2 — APPROVED** [review]
Thanks for the update. In this case, I’m happy to go ahead with it and give you a chance. As part of the delivery/article it would be nice to learn more about the project and the background of it, etc.

**Comment by takahser** [comment]
@helixstreet Thanks for answering the questions.

> Once variant calling is done this could be done by identifying a few variant (e.g. eye color is the easiest encoded )

I'm assuming that said eye color will come in the form of a very specific color code, is that correct?
According to my (very limited) understanding of variant calling, this process is very prone to errors, the same goes for the sequencing done by the machine in the previous step. If that's the case, can we still assume that identification of these variants will be accurate? To stay at your example of eye color, let's say the sequencing and/or the variant calling made some errors and identifies the color as _colorcode_ABC_ however, in reality, the color is _colorcode_XYZ_. In that case, the person will be rejected, right? In general, my question is, how reliable are these processes for identifying a person?
Pls correct me if any of my assumptions are wrong or if I'm missing something.

In general, it's still a bit fuzzy to me how the pallet will be used and what it will do which is why I'm with David here w.r.t. the article. It would be nice to have some more context to understand e.g. who's the target audience for this pallet and how it can be used.

That being said, given the updated price I'm also fine to give it a shot. 👍

**Review by takahser — APPROVED** [review]

**Comment by helixstreet** [comment]
> @helixstreet Thanks for answering the questions.
> 
> > Once variant calling is done this could be done by identifying a few variant (e.g. eye color is the easiest encoded )
> 
> I'm assuming that said eye color will come in the form of a very specific color code, is that correct?

No. It's not so easy. Several variants play a role.
For example: 

https://www.ncbi.nlm.nih.gov/gene/4948


 According to my (very limited) understanding of variant calling, this process is very prone to errors, the same goes for the sequencing done by the machine in the previous step. If that's the case, can we still assume that identification of these variants will be accurate? To stay at your example of eye color, let's say the sequencing and/or the variant calling made some errors and identifies the color as _colorcode_ABC_ however, in reality, the color is _colorcode_XYZ_. In that case, the person will be rejected, right? In general, my question is, how reliable are these processes for identifying a person? Pls correct me if any of my assumptions are wrong or if I'm missing something.

Variant calling is not prone to errors. 
Sequencing is - but the errors are not systematic; so multiple reads correct errors 

> 
> In general, it's still a bit fuzzy to me how the pallet will be used and what it will do which is why I'm with David here w.r.t. the article. It would be nice to have some more context to understand e.g. who's the target audience for this pallet and how it can be used.
> 
> That being said, given the updated price I'm also fine to give it a shot. 👍

Thx indeed.

**Comment by alxs** [comment]
@helixstreet personally I think the distinction between level 1 and level 2 grants is there for a reason, and the badge is only awarded to projects that already have a slight understanding of what they're trying to build because we can't possibly endorse individuals without a team who are at the absolute earliest stage of their crypto journey. We can at most provide some funding, which is what a level 1 grant accomplishes.

So I personally won't approve it and my recommendation is that you change it back to a level 1 grant, in which case it's already approved. Or you can wait in case someone else wants to provide the third approval.

**Comment by helixstreet** [comment]
> @helixstreet personally I think the distinction between level 1 and level 2 grants is there for a reason, and the badge is only awarded to projects that already have a slight understanding of what they're trying to build because we can't possibly endorse individuals without a team who are at the absolute earliest stage of their crypto journey. We can at most provide some funding, which is what a level 1 grant accomplishes.
> 
> So I personally won't approve it and my recommendation is that you change it back to a level 1 grant, in which case it's already approved. Or you can wait in case someone else wants to provide the third approval.

Thx for your feedback - nevertheless i think i have "a slight understanding of what i am trying to build".

**Comment by alxs** [comment]
Right. Replace that with "a solid understanding" then, my bad.

**Comment by helixstreet** [comment]
> Right. Replace that with "a solid understanding" then, my bad.

I even think i have quite "a solid understanding" of what i am planning to build.

**Comment by helixstreet** [comment]
I am slightly shocked by the arrogance and rudeness here.

**Comment by alxs** [comment]
@helixstreet I apologise if that's how it came accross.

As evidenced by the fact that you've improved the application several times and pivoted in response to feedback, and given your lack of experience with blockchain technologies, I think it's fair to say you're still trying to figure out exactly how you will accomplish your vision. That's perfectly fine and we're happy to support you along the journey, and I don't think there's anything wrong with me saying it.

If you don't mind, I would be happy to jump on a call to talk about what you want to achieve to give this a positive spin. I've sent you an email so we can find a time.

**Comment by helixstreet** [comment]
"give my lack of experience with blockchain technoligies"

Really - is this rudeness the style of W3F or your personal?

**Comment by alxs** [comment]
@helixstreet I'm sorry, I was just fixing that. You didn't list any experience in your application.

**Comment by laboon** [comment]
This is an interesting application for blockchain tech that I'd never considered before. I'm curious to see where it goes and will approve.

**Review by laboon — APPROVED** [review]

**Comment by helixstreet** [comment]
> This is an interesting application for blockchain tech that I'd never considered before. I'm curious to see where it goes and will approve.

Thx indeed. Highly appreciated - also the positive and encouraging attitude.

**Comment by keeganquigley** [comment]
Hi @helixstreet are you able to provide an update on how your progress is coming along?

**Comment by helixstreet** [comment]
Hi, Slow ( very ) but steady. Just doing a deep dive of Polkadot in Buenos Aires - so some more progress coming soon. If i understood correctly there is no deadline.

**Comment by keeganquigley** [comment]
Thanks for the update @helixstreet, there is no hard deadline per se, however, seeing as this grant has been open for almost a year, we want to make sure that it is still actively being worked on. I noticed that there has been no activity on the [repo](https://github.com/strategyobject/substrate-client-java/commits/develop) in quite some time. If you think it will be significantly delayed further we would ask you to submit an [amendment](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval) to update the timeline. Thank you!

**Comment by keeganquigley** [comment]
Hi @helixstreet seeing as no work has been done on the project since last August, I think it's probably a good idea to go ahead and terminate the grant, and then you can re-open it when you are ready to work on it. Let me know your thoughts - if we don't hear back from you after 2 weeks, we will go ahead and terminate due to inactivity.

**Pull request merged**
