### PR TITLE
Set concrete timeline for walt.id - NFT infrastructure

### PR DESCRIPTION
**Pull request by philpotisk**
#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

https://github.com/w3f/Grants-Program/pull/1209

### CODE REVIEW

**Comment by philpotisk** [comment]
As discussed via mail, I have updated the original grant-application and set a concrete timeline when we estimate to complete the grant. 
All the best,
Phil

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I will share it with the rest of the team.

**Review by dsm-w3f — APPROVED** [review]

**Review by alxs — APPROVED** [review]

**Comment by keeganquigley** [comment]
Hi all, how is the progress on M1 coming along?

**Comment by philpotisk** [comment]
Hey @keeganquigley ,

as M1 is actually the whole project in our case, we have not submitted it yet. 

A short status update:
- Indexing issue: As our solution proofs NFT ownership, we rely on efficiently retrieving NFTs + metadata from the various Polkadot networks. Therefore we investigated a lot and tried several tools, which took much longer than expected.
- The good thing is, that we came to a working implementation and support now the EM-compatible chains Astar/Moonbeam as well as the Unique ecosystem in the NFT Kit (which is the core of our product).
- We have also confirmed with the Subsquid team that they will support indexing for RMRK in near future. Once this is enabled we would also support RMRK.
- We are currently working in extending our wallet with Polkadot NFTs. Once this is done (probably next week), I guess it makes sense to hand over the project for review. We could come up with a set of written instructions, or a video or 1-on-1 call to take you through the stack. What would you prefer?

All the best,
Phil

**Comment by keeganquigley** [comment]
@philpotisk thanks for the update! I'm not sure who will be reviewing the milestone so it is up to you on which one you want to do. We typically love to see great written docs that users can also refer to, but if you feel like you are better at explaining through video that works too. Or a combo of both!

**Comment by philpotisk** [comment]
FYI: The final project has been submitted for review here https://github.com/w3f/Grant-Milestone-Delivery/pull/837

**Pull request merged**
