### PR TITLE
Update He-Chain

### PR DESCRIPTION
**Pull request by mutobui**
### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Comment by mutobui** [comment]
Update He-Chain:
1. Rename He-Chain to Gafi (gafi.network)
2. Add pallet_proof_mapping to milestone 1
3. Add pallet_staking_pool to milestone 1

**Review by semuelle — CHANGES_REQUESTED** [review]
Thanks for the PR, @mutobui. It would be a lot easier to review the changes, though, if you renamed `HE-Chain.md` and made the changes there. That would allow the reviewers to `git diff` and also prevent us from having two merged application files for one grant.

**Comment by mutobui** [comment]
Thank you, please check the pull request again

**Review by semuelle — CHANGES_REQUESTED** [review]
Hey @mutobui, thanks for the update. I don't see any issue with this amendment, but could you briefly explain why you chose to replace the pallet? Staking was not mentioned in your original application at all. And did you check others' implementations of the AccountId/H160 conversion, such as Moonbeam's? It might be beneficial to reuse existing solutions.

**Comment by mutobui** [comment]
Hi @semuelle, thank you for your quick advice, please let me explain the two new pallets.

pallet_staking_pool: this is the additional pallet to provide users one more option to join the pool so it does not replace original modules. Sorry for the name "staking" making confusion, this option basically locks the amount of token to give users a discount on transaction fees.

pallet_proof_mapping: this is extended from the default trait (AddressMapping)[https://github.com/paritytech/frontier/blob/master/frame/evm/src/lib.rs#L504] of Frontier and claim token of [Polkadot](https://github.com/paritytech/polkadot/blob/master/runtime/common/src/claims.rs). The Unified Accounts of Moonbeam is great for EVM compatible projects, we only affair that took us a lot more resources to integrate, and the trade-off for scalability in the future when completely using H160 so we think using the default mechanism is fitted with our philosophy "support EVM" not "EVM compatible".

**Review by semuelle — APPROVED** [review]
Thanks for the clarification.

**Review by takahser — APPROVED** [review]

**Comment by Noc2** [comment]
Just to add for reference https://github.com/w3f/Grants-Program/pull/836

**Comment by Noc2** [comment]
Sorry for the late reply. Besides frontier the only thing that comes to my mind, which might be helpful for you are the evm efforts by acala, e.g. https://github.com/AcalaNetwork/bodhi.js

**Comment by Noc2** [comment]
Ah and https://github.com/AstarNetwork/astarbase

**Pull request merged**
