### PR TITLE
Create CoinFabrik_On_Ink_Integration_Tests_2.md

### PR DESCRIPTION
**Pull request by valeriacaracciolo**
#### Project Abstract

We have discovered that integration tests for ink! contracts lack some of the functionalities, or present implementation differences, when compared to E2E testing. Integration tests run significantly faster than E2E (end-to-end) tests. If a full range of functionalities were provided, it could reduce testing and QA times. Our intention is to `flatten the anvil` of ink! integration testing. With a properly flattened anvil, quality tools can be built.

We have already conducted a comprehensive analysis to identify any missing functionalities in integration tests and implementation differences with E2E tests, and to propose and develop new testing features based on our findings. This analysis was carried as part of a previous grant ([link](https://github.com/w3f/Grant-Milestone-Delivery/pull/998)).

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by nikw3f** [comment]
Hey team, thanks for the application. In my opinion $60k seems a bit expensive as in the original grant you asked [for $40.5K](https://github.com/w3f/Grants-Program/pull/1875/commits/7cc39c9dfa98e1da7b92eade6039ae63516fc399#diff-95395f04cacfe76da94d227b4aa6b87460dd1efac8c5f1b89449c31300ff9339R112).

**Comment by valeriacaracciolo** [comment]
Hello @nikw3f <https://github.com/nikw3f> thanks for your review. In the previous application that you mentioned <https://github.com/w3f/Grants-Program/pull/1875/commits/7cc39c9dfa98e1da7b92eade6039ae63516fc399#diff-95395f04cacfe76da94d227b4aa6b87460dd1efac8c5f1b89449c31300ff9339R112>, we roughly estimated a shorter job (4 weeks vs. 8 weeks) and a smaller team (2.75 FTE vs. 4 FTE). After completing the analysis, our estimate is effectively more accurate in both time and resources. Yet, considering some pricing concerns mentioned by the team on the previous application, we have applied a ~20% discount to our market price. I hope this helps clarify the price difference. We look forward to your full review.

**Comment by valeriacaracciolo** [comment]
Hello @nikw3f we have identified a bug in the e2e tests. When contracts are in a workspace with dependencies defined in Cargo.toml, and these dependencies are inherited in contracts, the e2e tests fail to compile. However, manually specifying dependencies in each contract resolves the issue.
We've logged this bug on GitHub: [Issue #1919](https://github.com/paritytech/ink/issues/1919). We'd like to address it as part of our grant work. Please confirm if we need to update our application or if we can proceed with the fix in our current work - once confirmed. Thank you! Best,

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the quick reply here. It's best to integrate [this](https://github.com/paritytech/ink/issues/1919) into the deliverables of the application. Apart from this, I have one question: you estimate an FTE of 4, but you only shared 4 LinkedIn Profiles. Who is the fourth person in your team?

**Comment by nikw3f** [comment]
> Hello @nikw3f we have identified a bug in the e2e tests. When contracts are in a workspace with dependencies defined in Cargo.toml, and these dependencies are inherited in contracts, the e2e tests fail to compile. However, manually specifying dependencies in each contract resolves the issue. We've logged this bug on GitHub: [Issue #1919](https://github.com/paritytech/ink/issues/1919). We'd like to address it as part of our grant work. Please confirm if we need to update our application or if we can proceed with the fix in our current work - once confirmed. Thank you! Best,

Yes please update the application.

**Comment by valeriacaracciolo** [comment]
Hello @Noc2 and @nikw3f thanks for your reply. On [this](https://github.com/paritytech/ink/issues/1919), we will do so.

Regarding the team, our company policy prioritizes confidentiality and doesn't typically disclose specific team assignments. However, in response to your inquiry, here is the team assigned to this project:
0.5 (PM) Cristian Paz Mezzano [LinkedIn](https://www.linkedin.com/in/cristian-paz-mezzano-791bb210/)
1 Agustin Aón [LinkedIn](https://www.linkedin.com/in/agustin-aon/)  
1 Victor Gonzalez (not active on any social media)
0.5 Brian Ramirez [LinkedIn](https://www.linkedin.com/in/brian-leonel-ramirez-brandan-5045257a/) 
0.5 José García Crosta [LinkedIn](https://www.linkedin.com/in/jgcrosta/ )
0.5 Sofia Nicoletti [LinkedIn](https://www.linkedin.com/in/sofianicoletti/) 

Ariel Wassbein, our Head of Research, will supervise the project and engage in pivotal moments as required. As for my role (Valeria Caracciolo), I am actively involved but in a peripheral capacity.

I hope the above helps clarify, we are happy to address any further inquiries.

**Review by keeganquigley — DISMISSED** [review]
Thanks @valeriacaracciolo for making the changes. I do also think that the price is a bit high, and this could be a point of contention for other committee members. But based on the quality of your previous work, I'm willing to go ahead and approve it at this rate. Looking forward to the results.

**Review by nikw3f — DISMISSED** [review]
Thanks @valeriacaracciolo. Although i still feel price is high for this development, i am going to approve this. I am impressed with the previous [report](https://github.com/w3f/Grants-Program/pull/1875) and would like to see the findings implemented for ink integration test infrastructure.

**Comment by valeriacaracciolo** [comment]
Hi, wanted to inform you that, as we work on rectifying the end-to-end tests to operate within a workspace ([Issue #1919](https://github.com/paritytech/ink/issues/1919)), we are also addressing a few issues related to 'cargo-contract' (which also pertains to 'parity'). For the moment, there will be two pull requests: one to that repository and another to the 'ink' repository. Here are the issues that mention this error:
- https://github.com/paritytech/cargo-contract/issues/1265
- https://github.com/paritytech/cargo-contract/issues/1341
- https://github.com/paritytech/cargo-contract/issues/1172

We believe that our [last change](https://github.com/w3f/Grants-Program/commit/681c44734391e3f45a2650ce83368ccf454b071e) to the Project Status and Deliverables in our proposal correctly specifies these types of add hoc developments needed for the implementation of the proposed improvements.

We plan to document each ad hoc modification in our delivery report, but let us know if you see an additional change to our proposal necessary for clarity.

**Comment by valeriacaracciolo** [comment]
Hi everyone!

We came across a possible issue with e2e testing. We found that, when using the weight_to_fee function in e2e tests, the value of gas_price always returns zero. We provide a code example in the following link (https://github.com/CoinFabrik/on-ink-integration-tests/tree/d0c4deeb2b1d21f76d0020df7ab4330885c42da4/test-cases/weight-to-fee).

We plan to include this issue and the estimation for its resolution in our report of Milestone 2, but after validating with Michi (from partity) we where recommended to raise an issue in the respective repository. Do you concur?

**Comment by valeriacaracciolo** [comment]
Hi @nikw3f @keeganquigley @Noc2 

We came across a possible issue with e2e testing. Concretely we found that, when using the `weight_to_fee` function in e2e tests, the value of `gas_price` always returns zero. We provide a code example in the following link (https://github.com/CoinFabrik/on-ink-integration-tests/tree/d0c4deeb2b1d21f76d0020df7ab4330885c42da4/test-cases/weight-to-fee).

We plan to include this issue as part of our report of Milestone 1, since `weight_to_fee` was one of the functions pending analysis during this milestone. However, after talking to Michi from parity, he recommended us to post an issue to the corresponding repository. Do you concur?

**Comment by keeganquigley** [comment]
Thanks @valeriacaracciolo yes feel free to file an issue in the repo since those are the engineers who will be working on it, and then you can link it in the delivery if necessary. Thanks for checking!

**Review by Noc2 — APPROVED** [review]

**Review by semuelle — CHANGES_REQUESTED** [review]
Thanks for the application, @valeriacaracciolo, and sorry for the late response. 
We have had issues with grants relying on merging PRs with other people's repositories, so I'd be in favor of starting with M1 for now, or a subset of the proposed functions anyway. However, I'll ping the rest of the committee again to see if they think differently.

**Comment by valeriacaracciolo** [comment]
Thank you for your review @semuelle 

I'd like to point out that this application is an extension of a prior one, where we had estimated the required effort (#1875 https://github.com/w3f/Grants-Program/pull/1875 <https://github.com/w3f/Grants-Program/pull/1875>). To first perform an analysis and to later commit to execution, on 2 separate grant applications, was a suggestion from the grant’s team. 
Also, we are currently in communication with the Ink! team to address any inquiries or comments that may arise. Additionally, we've already engaged with the Parity team on a related topic (refer to #1358 at https://github.com/paritytech/cargo-contract/pull/1358 <https://github.com/paritytech/cargo-contract/pull/1358>). In the interest of adhering to repository guidelines and requirements, we've included specific team members in the process.

On another note, we've maintained momentum in our work to ensure the necessary continuity for the team. We're on track to complete our 1st delivery for Milestone 1 by next week. We would appreciate your guidance on how to proceed from here.

Looking forward to your instructions.
Best,

**Comment by valeriacaracciolo** [comment]
Hi [@semuelle](https://github.com/semuelle), we consulted with @keeganquigley and divided the milestones, keeping only the first one for this current application and leaving the second one for another grant application.

Please notice that we also changed the Level to 2.

Regards!

**Review by keeganquigley — APPROVED** [review]
Thanks for the changes @valeriacaracciolo re-approving.

**Review by nikw3f — APPROVED** [review]
Good from my side

**Review by Noc2 — APPROVED** [review]

**Pull request merged**
