### PR TITLE
Tribal Protocol Grant Application

### PR DESCRIPTION
**Pull request by Zyther**
### Project Abstract

The Tribal Protocol is a layer 1 blockchain designed for people to “tribe” online. Our primary mission is to allow anyone to become the co-founder of their own social networks, and in turn collectively change how people organize and socialize online.

Communities have been built online for over 20 years and the social feature innovation has been amazing to watch: feeds, groups, reels, lives, threads, clubhouses, likes, follows, and pokes. While many might think that the design space for social media is tapped out, we think that just around the corner is a place where all these innovative features can be remixed in a new category of social: niche, co-owned experiences tailored by and for specific communities and purposes.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying?

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [X] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [X] I have read and understood the [FAQs](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md), [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md) and [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md).
- [X] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [X] I have read and acknowledge the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [X] The software delivered for this grant will be released under an open-source license specified in the application.
- [X] The initial PR contains only one commit (squash and force-push if needed).
- [X] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).
- [X] I prefer the discussion of this application to be in a private Element/Matrix channel. My username is: ``@smartalec:matrix.org`` (note: we don't particularly care if communication is public or private, but since it's on the checklist, figured i'd share my username nonetheless)

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] Hackathon
- [ ] Personal Recommendation
- [ ] Substrate Builders Program
- [ ] Investor/VC
- [X] Online Search
- [ ] Other: _______

### CODE REVIEW

**Review by Noc2 — APPROVED** [review]
Thanks for the application. First of all, a nice website ;-) Apart from this, I’m happy to support the project and share it with the rest of the team. Did you already take a look at the following projects? Maybe you are able to leverage some of their work: 

- https://github.com/RainbowcityFoundation/RainbowDAO-Protocol-Ink-milestone_1 
- https://github.com/SubDAO-Network/subDAO-contracts

**Review by hakan-w3f — APPROVED** [review]
hi @Zyther , really nice take on DAOs, content ownership w/ lease, all leveraging ink! and Substrate. You may want to check out our grantee OpenBrush wrt ink!. If you'd like to leverage existing storage solutions for Tribal's encrypted content, Substrate ecosystem has plenty of offerings.

**Comment by silly-hack** [comment]
> hi @Zyther , really nice take on DAOs, content ownership w/ lease, all leveraging ink! and Substrate. You may want to check out our grantee OpenBrush wrt ink!. If you'd like to leverage existing storage solutions for Tribal's encrypted content, Substrate ecosystem has plenty of offerings.

Thanks for the feedback! Honestly we had not heard of OpenBrush, but a quick look at their offering is very impressive. As you pointed out, storage solutions are a very important aspect of what we need to build. I believe @jsondevlin already connected with subspace team. Offhand what other storage solitions would you recommend?

**Review by Noc2 — APPROVED** [review]
If you are looking for off-chain storage, you might want to take a look at the stack: https://github.com/w3f/Grants-Program/blob/master/docs/polkadot_stack.md specifically storage. We have a bunch of ipfs integrations (like https://github.com/DanHenton/pocket-substrate/tree/ipfs-ocw) as pallets, but nothing so far for ink! Smart contracts. In case, you want to work on this we would be happy to support it.

**Comment by Zyther** [comment]
> If you are looking for off-chain storage, you might want to take a look at the stack: https://github.com/w3f/Grants-Program/blob/master/docs/polkadot_stack.md specifically storage. We have a bunch of ipfs integrations (like https://github.com/DanHenton/pocket-substrate/tree/ipfs-ocw) as pallets, but nothing so far for ink! Smart contracts. In case, you want to work on this we would be happy to support it.

Hi @Noc2, 

This grant application is for the **initial** groundwork that will serve as some of the fundamental "blockchain-specific" functionality. 

We have a vision of how we want to want to address storage which we believe is attainable, and would be interested in teasing the idea of contributing towards storage related functions within smart contracts -- however we strongly believe the work efforts defined in this application are where we need to start. 

Best,
Alec (Zyther)

**Review by laboon — APPROVED** [review]

**Review by takahser — APPROVED** [review]
I'm happy to go ahead with your grant application as well.
However, I have a few questions. Feel free to address them.

> Users — who are using the Tribal chain — can upload content that the user owns. 

Are there any mechanisms in place to check whether the user actually owns said content?

> To activate an instantiated tribe, all listed founders must accept the terms, and conditions of said tribe, as defined in the initial `create_tribe` event.

Are these terms and conditions just a document or are you planning to support any structural data here as well?

> We expect to have some client-side services to communicate with back-end services in real time via REST calls, and web sockets to communicate with multiple back-ends simultaneously.

Couple of questions regarding said backends:
- will they be centralised or decentralised in some form?
- who will be supposed to run them?

**Comment by Zyther** [comment]
Hello there @takahser, see responses inline below.

> @Zyther I'm happy to go ahead with your grant application as well. However, I have a few questions. Feel free to address them.
> 
> > Users — who are using the Tribal chain — can upload content that the user owns.
> 
> Are there any mechanisms in place to check whether the user actually owns said content?

A: By definition any content created by the user will be stored with encrypted key on chain with that users pk.

> > To activate an instantiated tribe, all listed founders must accept the terms, and conditions of said tribe, as defined in the initial `create_tribe` event.
> 
> Are these terms and conditions just a document or are you planning to support any structural data here as well?

A: We expect the tribe "terms and conditions" to be a real structured dataset, capable of being parsed, and actioned upon by automated systems and triggers. (smart contract consumption)

> > We expect to have some client-side services to communicate with back-end services in real time via REST calls, and web sockets to communicate with multiple back-ends simultaneously.
> 
> Couple of questions regarding said backends:
> 
> * will they be centralised or decentralised in some form?
> * who will be supposed to run them?

A: While we are still in the very early stages of this project, we expect "backends" to represent a collection of blockchain nodes themselves. Nodes register themselves as online, and clients neogotiate multiple, asyncroneous connections to nodes.  

We also intend on allowing anyone (**most people) run a node who has resources to do so.
We expect, with the exception of initial discovery endpoints, to be able to function completely decentralized.



Also, excited to be a part of this grant program! Look forward to our first milestone's release! 

Best,
The Tribal Labs Team

**Comment by alxs** [comment]
Hey @Zyther, any updates on the second milestone? Unless you plan to deliver soon, could you please submit an [amendment](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval) with an updated timeline?

**Comment by alxs** [comment]
@Zyther friendly reminder. Note that if we don't hear anything from you within the next two weeks, we'll assume you're no longer interested and terminate the grant.

**Pull request merged**
