### PR TITLE
Nft2point0

### PR DESCRIPTION
**Pull request by avirajkhare00**
#### Project Description

We are building an infrastructure for developers to create interactive Gen 2 NFTs to plug-n-play in their own NFT marketplace.

Our NFTs are interactive in nature, i.e you can interact with them using your mouse and keyboard.

Please read this blog to understand it much better. It has around 5k views: https://learn.block6.tech/nft-2-0-the-interactive-nfts-e4e4df621922

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`nft2point0.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by avirajkhare00** [comment]
Hey @takahser 

You may close this PR: https://github.com/w3f/Grants-Program/pull/1173

We have decided to keep our game separate from our interactive NFT marketplace. Also, I will be looking the entire development of this.

Answering your questions here:

Question: While you're right, that there is indeed an NFT standard that is similar to ERC-721 in some ways, it is not an exact implementation: [psp-34](https://github.com/w3f/PSPs/blob/master/PSPs/psp-34.md). Also, the [polkadot wiki](https://wiki.polkadot.network/docs/learn-nft) includes other NFT approaches that currently exist in the Substrate ecosystem. It would be helpful for us to understand, if you're planning to build on any of these existing technologies or if you plan to implement something completely different, from scratch. Both options are possible, as long as they're reasonable and justifiable.
Answer: We are planning to build on these existing technologies.

Question: A question to the [M1.1](https://github.com/w3f/Grants-Program/pull/1173/files#diff-276af145b2e5470220d821c01e4eb0a4eb19de9321a26c90ce93b544e2f319cbR75), why do you need to add a field here? AFAIK the metadata JSON schema does already support IPFS URIs.
Answer: JSON Metadata schema doesn't support an array of URIs but a single URI, hence need to extend it.

Question: Could you add a bit more information to M1.2, M2.0, and M2.1, so we can better understand, what you're planning to build there?
Answer: We have covered it in the doc itself.

Request: Generally, we fund the development of open-source software, but not marketing and design tasks like M1.3 and M2.2. Feel free to remove these.
Response: Removed :)

We will put all the deliverables from 0a-0d.
Please note that
[Deliverables 0a-0d are mandatory for all milestones, and deliverable 0e at least for the last one.](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md)

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for your interest in our grant program. But your application is missing a few details: 

- For which level are you applying? Could you also specify this as part of the grant application, see the template 
- Which smart contract language are you going to use? We usually don’t support the development of solidity projects, since we are no expert when it comes to solidity and rather focus on ink!. 
- We ask teams to denominate grants in USD and at the time of payment we would convert it to BTC
- Deliverables 0a-0d of the template are mandatory for all milestones, and deliverable 0e at least for the last one.

**Comment by avirajkhare00** [comment]
Hello. Thanks for your input. We have updated our document.
Answering it here too.

Q. For which level are you applying? Could you also specify this as part of the grant application, see the template
A. We are applying for level 2 grant: 30,000 USD.
Q. Which smart contract language are you going to use? We usually don’t support the development of solidity projects, since we are no expert when it comes to solidity and rather focus on ink!.
A. We are building our smart contracts on Ink.
Q. We ask teams to denominate grants in USD and at the time of payment we would convert it to BTC
A. Done
Q. Deliverables 0a-0d of the template are mandatory for all milestones, and deliverable 0e at least for the last one.
A. Done

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. Could you maybe integrate the default deliverables into every table? This way it is easier for us to keep track of it. For example, the license seems to be missing for milestones 2 and 3. Also, could you add the programming language/framework to the deliveries? In general, feel free to add additional technical details. Regarding ERC-721, are you relying on a specific existing ink! implementation, that already exists? In this case, feel free to link to it.

**Comment by avirajkhare00** [comment]
Hey @Noc2. Please check again.

**Comment by avirajkhare00** [comment]
Hi @Noc2 . Any update on this?

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. Before I share it with the rest of the team. Could you update the formatting of the last milestone? And it would still be helpful if you could add additional details to the deliveries (like for example the programming language of the SDK and the backend).

**Comment by avirajkhare00** [comment]
Hey @Noc2. I have fixed the formatting issue and included the tech stack in milestones. Please do check and let me know 🙏.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. I will share it with the rest of the team and mark it as ready for review. However, I personally won’t approve it yet, because I think your first milestone is currently too expensive compared to the rest. Could you reduce the price? Also, could you potentially integrate mock-ups or initial designs of your UI? This is probably not too difficult given that you are already working on it.

**Comment by avirajkhare00** [comment]
Make sense. Instead of three, I will create four milestones.
Each milestone will be having $7,500
Hope it's better :)

**Comment by avirajkhare00** [comment]
Working on mockups

**Comment by avirajkhare00** [comment]
Here is the demo youtube video: [Demo Link](https://youtu.be/kHtJEbMozV0)
I have also updated the doc.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. However, we usually don’t support fully teched focused milestones. The main focus should always be on technical development. Could you either move this to another milestone or remove it completely? You can always apply for treasury funding for this.

**Comment by avirajkhare00** [comment]
Hey @Noc2. Thanks for the review. Please check the doc again. I have removed milestone 4.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. But why did you suddenly increase the cost of all other milestones?

**Comment by muskanmarwah1** [comment]
We are applying for $30,000
I have removed milestone 4 and adjusted that cost in other milestones. If you want, I can reduce it as before.

**Comment by avirajkhare00** [comment]
I have removed milestone 4, so I adjusted its cost in other milestones. If you want, I will revert it to the original cost.

**Comment by avirajkhare00** [comment]
Hey @Noc2. I have reverted back to previous cost.

**Comment by avirajkhare00** [comment]
Hi guys. Any update on this?

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. I’m personally still not fully convinced about the application. For example, couldn’t your use case simply be implemented by creating new and destroying existing NFTs, if you interact with them in a certain way? Also regarding your witch example, isn’t this something you can already publish with the current NFT standard? Since the NFT could also represent some code and not necessarily need to represent an image.

**Comment by avirajkhare00** [comment]
> Thanks for the update. I’m personally still not fully convinced about the application. For example, couldn’t your use case simply be implemented by creating new and destroying existing NFTs if you interact with them in a certain way? Also, regarding your witch example, isn’t this something you can already publish with the current NFT standard? Since the NFT could also represent some code and not necessarily need to represent an image.

By destroying the NFT, I assume we have to set the owner address as null and remove the IPFS hash from the smart contract.
After thinking a lot, it's possible to push the code and base64 of an image in the same IPFS file. The IPFS file would simply be a JSON file.

**Comment by avirajkhare00** [comment]
I have updated the document. Please check

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks again for the update. However, what do you mean by “We need to create a Storage layer that will store the output of interactive NFT”? Aren’t you using IPFS for this?

**Comment by avirajkhare00** [comment]
> Thanks again for the update. However, what do you mean by “We need to create a Storage layer that will store the output of interactive NFT”? Aren’t you using IPFS for this?

Hi. As we know that IPFS is a file-storage system, not a data-storage system. The output of interactive NFT might be computed and stored inside a smart contract.

IPFS will be used to store JS code and image files.

**Comment by avirajkhare00** [comment]
You may read this blog for the better understanding: https://medium.com/@avirajkhare00/nft-2-0-the-interactive-nfts-e4e4df621922

**Comment by avirajkhare00** [comment]
Hello @Noc2 . Any update?

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for pinging me. But I’m still not convinced by this application. What exactly is this “Storage layer”? Do you simply mean storing variables on-chain? Also, can the functionality that you describe not simply be implemented by burning an existing NFT and minting a new one? In any case, I will ping the rest of the team again. Somebody else might be able to provide more input on this.

**Comment by Noc2** [comment]
For reference: https://github.com/w3f/Grants-Program/pull/1201#pullrequestreview-1144003243

**Comment by avirajkhare00** [comment]
Hey. I came to know that we can't work on two different grants. Requesting you to close this grant.

**Comment by Noc2** [comment]
K, I will close it. We can reopen it, if you finished one grant or the other one got rejected.

**Comment by avirajkhare00** [comment]
Thanks. Once we are done with ChainEducation. We will get back on this one.

**Pull request closed without merging**
