### PR TITLE
Add the YibanChen application

### PR DESCRIPTION
**Pull request by davidrhodus**
# Grant Application Checklist

- [x] The [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Looks interesting. I have a few questions/comments:

- Are you aware of [system.remark](  https://github.com/paritytech/substrate/blob/master/frame/system/src/lib.rs#L314), which also lets you take notes?  
- Also you should probably take a look at [Substrate Names](https://github.com/xaya/substrate-names) and [ENS on Substrate](https://github.com/hskang9/substrate-name-service). Potentially you can reuse some of their work and reduce the price accordingly. 
- Are you aware of offchain::ipfs https://rs-ipfs.github.io/offchain-ipfs-manual/? This might be interesting for you. 
- Could you potentially share some initial mock-ups or designs with us? 
- Why did you only include unit tests for the last milestone?

**Comment by davidrhodus** [comment]
HI @Noc2 thanks for your feedback.

> * Are you aware of [system.remark](https://github.com/paritytech/substrate/blob/master/frame/system/src/lib.rs#L314), which also lets you take notes?

I updated the application to clarify our thinking with regards to system.remark.
"We looked at the system.remark call, while we found system.remark would allow for simple note creation, but would limit the ability to enhance our Note feature. In the future we plan to add two gatekeeper mechanisms on the note receiver side. First, whitelist a set of wallet address senders, and secondly the ability of a wallet address to set an amount of token required to be sent along with the note before the wallet address would accept the note. We also have had some initial feedback that users would be interested in selling the notes, which we believe utilizing ORML-NFT would be the best for this scenario for selling notes in the future."

> * Also you should probably take a look at [Substrate Names](https://github.com/xaya/substrate-names) and [ENS on Substrate](https://github.com/hskang9/substrate-name-service). Potentially you can reuse some of their work and reduce the price accordingly.

Thanks for these examples, I haven't come across them in my research. Reading the source code they do offer some code and good ideas that we will leverage and utilize. I updated the application to reference these source code repositories and adjust the price.

> * Are you aware of offchain::ipfs https://rs-ipfs.github.io/offchain-ipfs-manual/? This might be interesting for you.

I have looked at offchain::ipfs and at this time we would like to have the client application read/write with an IPFS gateway given the alpha state of the offchain module. I do think we'll add in support to the nodes to support this module and an option within the application UI.

> * Could you potentially share some initial mock-ups or designs with us?

Yes, I updated the application to include some of the UI design. 

> * Why did you only include unit tests for the last milestone?

This is actually a mistake, I have updated the application to include unit testing for the pallets and selenium tests for the ReactUI.

**Review by Noc2 — APPROVED** [review]
Thanks for the updates. Looks good to me. I will share it with the rest of the team.

**Review by mmagician — APPROVED** [review]
Looks promising!

**Review by BenWhiteJam — APPROVED** [review]

**Comment by takahser** [comment]
Hi @davidrhodus 
I just wanted to quickly check how the development of M3 is going for you since we haven't heard back from a while.
Is there any way we can support you?

**Comment by davidrhodus** [comment]
> Hi @davidrhodus I just wanted to quickly check how the development of M3 is going for you since we haven't heard back from a while. Is there any way we can support you?

Thanks for reaching out. Have been on extended holiday. I am still actively working on this project and will submit within the next couple of weeks.

**Comment by alxs** [comment]
@davidrhodus it's been 4 months since your last delivery - could you please submit an [amendment](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval) to update the duration of the last milestone, unless you're planning to deliver in the next 2 weeks?

**Comment by davidrhodus** [comment]
> @davidrhodus it's been 4 months since your last delivery - could you please submit an [amendment](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval) to update the duration of the last milestone, unless you're planning to deliver in the next 2 weeks?

Hi @alxs Thanks for your follow up. 

I think we can submit within the next two weeks. We are currently wrapping up getting the sign and verify using the polkadot.js browser extension which is critical for the milestone 3. We have been slowed down due the examples in the Polkadot JS API documentation do not work. This week we were able to move forward by finding a working example by reviewing code we found on GitHub.

**Pull request merged**
