### PR TITLE
Footprint-Analytics.md

### PR DESCRIPTION
**Pull request by LynnTsang**
#### About Footprint Analytics
Footprint Analytics is a data platform blending web2 and web3 data with abstractions. We help analysts, builders, and investors turn blockchain data into insights with accessible visualization tools and a powerful multi-chain API across 20+ chains for NFTs, GameFi, and DeFi.

#### Proposal on how Footprint can help build Polkdot & Kusama
Our main target is to provide a cross-chain data service.  
The Detailed solution is written below:
- Provide the raw, full-time period of data of the Polkdot & Kusama chain.
- Provide protocols’ information on the Polkdot & Kusama chain.
- Provide abstract, normalized data and metrics. Create a "de facto standard" to simplify analysis across multiple protocols or chains.
- Provide a powerful analytics tool for Polkdot & Kusama users, analysts, and developers to explore Polkdot & Kusama data on a deeper level.

#### How Footprint can benefit the Polkdot & Kusama ecosystem

1. Provide the Polkdot & Kusama team with data on the ecosystem in order to monitor the development of the ecosystem.
- Data on user and developer participation, number of users, activity level, etc. This is good for discovering potential projects, monitoring the condition of the ecosystem, and providing support and backing for the developers on the chain.
- Comparison between Polkdot & Kusama chain and other chains to understand the situation of competing chains.
2. Providing data solutions for the developers on Polkdot & Kusama to help them understand project data to better operate the project
- Free and ready-to-use project 0-coding Analytics. Footprint provides a standard dashboard based on structured tables. Polkdot on-boarding projects can claim their dashboards without any investment in dev or analyst resources.
- Free and ready-to-build APIs. Accelerate the development of the Polkdot & Kusama ecosystem.
3. Brand awareness improvement: Data can show the strength and development of Polkdot & Kusama and attract more developers and users
- With dashboards and reports, we can spread the word around about Polkdot & Kusama's progress.
- We have more than 50+ media channels with 500k exposure, such as [Cryptoslate](https://cryptoslate.com/author/footprint-analytics/) and [CoinMarketCap](https://coinmarketcap.com/alexandria/author/footprint-analytics). Our content could be reprinted by yahoo finance and many other media. Also other tens of social media platforms.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@ :matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for your interest in our grants program. Could you add the default deliverables to the milestone tables ([see](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#milestone-1-example--basic-functionality))? Also, we would need to have the technical details of the integration as part of the milestone tables. Additionally, I would be interested to hear how your solutions compare to other existing open-source solutions in our ecosystem, like https://www.subsquid.io/

**Comment by LynnTsang** [comment]
> Thanks for your interest in our grants program. Could you add the default deliverables to the milestone tables ([see](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#milestone-1-example--basic-functionality))? Also, we would need to have the technical details of the integration as part of the milestone tables. Additionally, I would be interested to hear how your solutions compare to other existing open-source solutions in our ecosystem, like https://www.subsquid.io/

**Comment by LynnTsang** [comment]
@Noc2 Thanks for your comment. 
I have added milestones in the application, you can check https://github.com/footprintanalytics/W3F-Grants-Program/blob/master/applications/Footprint-Analytics.md or check https://github.com/w3f/Grants-Program/pull/1921/files

And I just added technical details of the integration, too. 

About your last question, I will take a look at https://www.subsquid.io/ and get back to you later.

**Comment by LynnTsang** [comment]
@Noc2 Here is a comparision between Footprint Analytics and other data platforms.
Subsquid requires developers to use sdk to parse data for product development.
Footprint is a platform that parses full historical and real-time data for all analysts and developers to use. 
competitor

**Pull request closed without merging**
