### PR TITLE
Slushie Mixer.md

### PR DESCRIPTION
**Pull request by Kyrylog**
Create Slushie Mixer

Update Slushie Mixer.md

### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying?

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] I have read and understood the [FAQs](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md), [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md) and [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).
- [ ] I prefer the discussion of this application to be in a private Element/Matrix channel. My username is: ``@_______``

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] Hackathon
- [x] Personal Recommendation
- [ ] Substrate Builders Program
- [ ] Investor/VC
- [ ] Online Search
- [ ] Other: _______

### CODE REVIEW

**Comment by Kyrylog** [comment]
@Noc2 
thanks for your comments. I will address them one by one.
> * The following link doesn’t work for me: https://github.com/4IRE-Labs/Slushie
Yes, the repository was private; we fixed it.
> * Did you previously work on something similar? And if so, is it open source?
Nope, we are fairly new to privacy-focused tools and have never developed them before as open source. However we are a member of Substrate Builders Program with expertise in ink! smart contracts and understand well the needs of the ecosystem. We have a strong cryptography engineer on our team, and we think she’ll perform beautifully on this project.
> * We usually pay after the successful delivery of the milestone. Therefore it would be nice if you could add an amount to each milestone, see https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md
Done.
> * Also feel free to add the programming language to each specification
Also done.

**Review by mmagician — APPROVED** [review]
Looks better! I'd still unify Development Roadmap{S} (you have it outlined twice), but other than that would give it a green light.

**Comment by Kyrylog** [comment]
> @Kyrylog Thanks for the application. I’ve had a quick look, and it seems that your project is really a 1:1 copy of the RFP. Please be aware that I wrote that RFP about a year ago, and a lot of things have changed since then. Just as an example, I think the most efficient Poseidon implementation is [Neptune from Filecoin](https://github.com/filecoin-project/neptune), but there are probably various other implementations out there, some of them might also be using `no_std` already, basically rendering that milestone obsolete. Same for MerkleTrees in `ink!`, I can imagine you’d be able to find libs that are directly importable into the smart contract.
>
> I would suggest making a deep-dive into each of the milestones from the RFP and verifying whether the requirements still hold, and adapt the proposal accordingly, before we can proceed any further.

Yes, you’re right; we updated the application with the new libs and significantly reduced milestone timelines.

**Review by Noc2 — DISMISSED** [review]
Thanks for the update. I’m happy to go ahead with it and share it with the rest of the team.

**Comment by Kyrylog** [comment]
> 

Thank you, corrected in PR. 

By the way, could you let us know why it passing 5 reviews instead of 3?

**Comment by mmagician** [comment]
@Kyrylog It is actually 3, but you can only set repo-wide merge permissions, which we set to 5, and not per-application-cost permissions :) Once it reaches 3 reviewers from the Grants Committee (e.g. I don't count) it will be merged by someone with a write access.

**Review by semuelle — CHANGES_REQUESTED** [review]
Happy to proceed with this project. Just one remark: your website, 4irelabs.com, lists Polkadot as your partner, as well as "Community & Development Partner", with the latter linking to an article unrelated to Polkadot titled "How to Build a Mobile Wallet App". Afaik "Polkadot" does not partner with anyone, so I'd like to ask you to remove the logo from your website.

**Review by BenWhiteJam — APPROVED** [review]

**Comment by Kyrylog** [comment]
> Happy to proceed with this project. Just one remark: your website, 4irelabs.com, lists Polkadot as your partner, as well as "Community & Development Partner", with the latter linking to an article unrelated to Polkadot titled "How to Build a Mobile Wallet App". Afaik "Polkadot" does not partner with anyone, so I'd like to ask you to remove the logo from your website.

Polkadot logo removed from the company website

**Review by SBalaguer — APPROVED** [review]

**Comment by Noc2** [comment]
Congratulations and welcome to the Web3 Foundation Grants Program! Please refer to our [Milestone Delivery repository](https://github.com/w3f/Grant-Milestone-Delivery/) for instructions on how to submit milestones and invoices, our [FAQ](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md) for frequently asked questions and the [support section of our README](https://github.com/w3f/Grants-Program/blob/master/README.md#support) for more ways to find answers to your questions. <br/><br/> Before you start, take a moment to read through our [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md) for all communications related to the grant or make them known to the right person in your organisation. In particular, please <b>don't announce the grant publicly before at least the first milestone of your project has been approved.</b> At that point or shortly before, you can get in touch with us at grantsPR@web3.foundation and we'll be happy to collaborate on an announcement about the work you’re doing.<br/><br/> Lastly, please remember to let us know in case you run into any delays or deviate from the deliverables in your application. You can either leave a comment here or directly request to amend your application via PR. We wish you luck with your project! :rocket:

**Pull request merged**
