### PR TITLE
Unified deployment for the collator node

### PR DESCRIPTION
**Pull request by markblaize**
#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. I shared the application with the person that wrote the RFP. Some initial quick feedback from me: 

- The default deliverables 0a-0d of the [template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) are usually mandatory for all milestones. Could you integrate these or at least point out why you haven’t integrated them?
- The price currently seems relatively expensive to me. Could you expand a little bit more regarding the required work or/and reduce the price?

**Comment by markblaize** [comment]
Hi @Noc2 

> Thanks for the application. I shared the application with the person that wrote the RFP. Some initial quick feedback from me:
> 
> * The default deliverables 0a-0d of the [template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) are usually mandatory for all milestones. Could you integrate these or at least point out why you haven’t integrated them?
I've added `0c` as it makes sense to provide information how to run infrastructure tests,
about `0d` - Docker, I don't see a reason for a specific container to run infrastructure tests because there is a better solution for that, so that's why this deliverable is not included


> * The price currently seems relatively expensive to me. Could you expand a little bit more regarding the required work or/and reduce the price?
We have updated the price, please check.

**Comment by markblaize** [comment]
> 

Hi @alxs we have postponed the proposal for the validator  https://github.com/w3f/Grants-Program/pull/1268 so right now our team is focused on the collator

**Review by Noc2 — CHANGES_REQUESTED** [review]
@siexp could you also sign our terms and conditions (see CLA assistant above)?

**Comment by markblaize** [comment]
> @markblaize Thanks for the update. Could you potentially also integrate [0e. | Article](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#milestone-1-example--basic-functionality) as a delivery (0d. in your case)? You are probably interested in announcing the grant anyway.

We definitely want to post an article about this project; we do it in the form of blog posts like that https://blaize.tech/clients/money-market-protocol-development-for-omomo/, so if it fits this deliverable, we would be more than happy to include it.

**Comment by alxs** [comment]
@markblaize I assume the setup will be different depending on the collator. Are you planning to support all existing parachains?

**Comment by markblaize** [comment]
> @markblaize I assume the setup will be different depending on the collator. Are you planning to support all existing parachains?

We have reviewed about ten substrate chains from what we see that we can provide a unified approach for all of them; we would not give a contribution to those projects' deployment scripts, but in the documentation, we will show that anyone can set up a Collator node for any parachain with our approach.

We see risk in the unification "build" step because it may use any dependencies, prerequisites or even build system different from the Cargo. But we will mitigate it with a good-default building container (any future chain could extend that) and the ability to deploy from the container provided by parachain maintainers.

Terraforming itself is pretty much the same for all nodes and may only differ in instance size (which would be adjustable and specified by a concrete chain. e.g., our parachain has huge memory consumption, so you need to allocate "AWS x2gd.large" instance instead of "AWS t2.large")

The same is true for deployment; we see that for all parachains, it's pretty much the same; it requires a supervisor (in most cases, it `Systemd` that not really scales) that would be handled by our deployment scripts and startup parameters that parachain maintainers would provide as they are chain specific.

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I'm happy to go ahead with it.

**Review by gautamdhameja — APPROVED** [review]

**Review by alxs — APPROVED** [review]

**Comment by babebort-blaize** [comment]
Hello. 
Could you provide an environment for testing? 
For example, AWS would be good for this purpose.

@Noc2 
@gautamdhameja  
@alxs

**Comment by Noc2** [comment]
We usually don’t provide any testing environments or infrastructure for grants.

**Pull request merged**
