### PR TITLE
Patch-1

### PR DESCRIPTION
**Pull request by El-khana**
#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [ ] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [ ] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [ ] The software delivered for this grant will be released under an open-source license specified in the application.
- [ ] The initial PR contains only one commit (squash and force-push if needed).
- [ ] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for your interest in our grants program. Let me know once the application is ready. Currently, a lot of information is still missing. Also, I'd like to point out that we usually don't fund audits or deployment-related deliveries. Additionally, the second milestone should also contain the default deliverables of the template (0a., etc.)

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. Just a reminder to ping me here once the application is ready for review. There still seems to be a lot of information missing and additional things like deployment/launch should be removed (see above) since we usually don't fund them.

**Comment by El-khana** [comment]
Hello David Hawig,,
My name is Muchiri and we would like to continue with our grant procedure
under the web3 foundation and build for Polkadot community and ecosystem in
Africa. We were experiencing some few financial issues with our projects
but we have rallied past them and we are ready to continue building our
project and community. Kindly help us get back and we will do our best to
deliver.

with regards,
Muchiri Elkanah,
CEO Jua Labs

**Comment by Noc2** [comment]
Thanks for pinging me here. I suggest that you open a new PR. But keep in mind that we don't fund ecosystems or community-focused projects via our grants program. If this is your main goal, you might want to take a look at the treasury instead: https://github.com/w3f/Grants-Program#treasury

**Pull request closed without merging**
