### PR TITLE
Application: "SubIdentity" - Substrate Identity Directory

### PR DESCRIPTION
**Pull request by a-oertel**
### Project Abstract

SubIdentity is a fully client-side web application build with Vue.js in Typescript. The application enables searching of on-chain identities by any identity field in a substrate-based chain that implements the identity pallet.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Review by semuelle — CHANGES_REQUESTED** [review]
Thanks for the application, @a-oertel. It looks very promising. A few minor questions/requests:

- The RFP mentions IPFS multiple times, e.g. "allow users to enter their pinata key, and store set of fetched information to IPFS and pin on pinata", but your application doesn't. I personally think it would be great if I could store data and settings on IPFS. Are you not planning on including this? We have had several grants implement similar functionality, so if you want I could point you to one.
- Milestone 4 of the RFP, a combination of documentation and maintenance, is not included. At this point we have specialised [maintenance grants](https://github.com/w3f/Grants-Program/#hammer_and_wrench-maintenance-grants), so that part of the milestone could be agreed upon later. But if we leave out the maintenance part, we really need thorough documentation to ensure that it is usable and extendable for everyone for a while. 
- Sending tokens requires a wallet connection. Given that the RFP highlights mobile use, have you put any thought into supporting more than just polkadot.js?

**Comment by a-oertel** [comment]
Thanks for your feedback @semuelle 

- As part of the second milestone we plan on focussing on performance improvement. I specified that step to point out, that we plan on providing a caching option to IPFS. 
- We included number 0b in every milestone in order to record, that we will provide thorough  documentation and an updated tutorial with every step. I've expanded the future plans chapter to signal our readiness for maintenance tasks beyond the scope of the project.
- We plan on using an open protocol (e.g. wallet connect) to establish a secure connection to a wallet. This also allows connections to a wallet on mobile devices.

**Comment by SBalaguer** [comment]
Thanks @a-oertel for the submission! It seems like the mokups that are part of the submissions are the same as the [Shard's Lab Identity Hub](https://github.com/Shard-Labs/identity-hub). If this is the case, would you mind providing your own UI mockups? For these type of grants its good to have a very draft first initial mockup to visualize better what you are going after.

Thanks!

**Comment by a-oertel** [comment]
> Thanks @a-oertel for the submission! It seems like the mokups that are part of the submissions are the same as the [Shard's Lab Identity Hub](https://github.com/Shard-Labs/identity-hub). If this is the case, would you mind providing your own UI mockups? For these type of grants its good to have a very draft first initial mockup to visualize better what you are going after.
> 
> Thanks!

Hey @SBalaguer, we created our own Mockups. You can view them here:
https://tdsoftware-dev.de/subidentity/home.png
https://tdsoftware-dev.de/subidentity/search-results.png
https://tdsoftware-dev.de/subidentity/profile-details.png
Could you please clarify what you mean exactly?

**Comment by SBalaguer** [comment]
For sure! And I might be missing something, but when I go to the [Shard's Lab Identity Hub repository](https://github.com/Shard-Labs/identity-hub#figma-design-link), I see [this figma](https://www.figma.com/file/Q8ueqnAQYtDQq4bVgwY1Uf/Identity-Directory---Design?node-id=0%3A1) link that has the same (or at least very similar) mockups. That's where my confusion lies.

**Comment by a-oertel** [comment]
It's true that the designs/mockups are looking similar. One reason is that both are based on the same requirements from the RFP. The other one is that we have chosen the same pink main color as known from polkadot. If you want, we can provide some more mockups of planned pages and components.

**Comment by a-oertel** [comment]
It seems that the previous solution had performance issues ([Evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/identity_directory_1_alxs.md)) that we want to avoid. We're eager to find a more sensible solution and therefore we hesitate to continue using the code base.

Regarding the design: The designs/mockups look similar. This is because they are based on the same requirements of the RFP and we also chose pink as the main color to match the polkadot design.
Further our design addresses some of the issues with the previous design, for example:
- Having the search box and the list view appear together on the landing page detracts from the search box's attention. We solve this by making it a central element in the landing page and adding a separate list view.
- It was unclear how a closed column could be reopened. We, on the other hand, rely on an intuitive folding solution.
On request, we can provide you with additional mockups of planned pages and components.

As mentioned before, we are very interested in doing maintenance work for the project. The development of additional plugins to extend the solution is also an option for us, as we plan to expand our open source activities.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the quick reply. I have one additional question, just to double check: have you considered potentially also developing a backend. A fully client side solution might be rather slow.

**Comment by a-oertel** [comment]
We considered developing a backend for performance reasons, but the RFP specifically calls for a fully client-side application. Therefore, we did not further investigate this approach. We definitely have the know-how and will keep the option in mind to put a server layer e.g. with Node.js in between the web app and the blockchain.

**Review by Noc2 — APPROVED** [review]
Thanks. I’m happy to go ahead with it.

**Review by semuelle — APPROVED** [review]

**Comment by takahser** [comment]
@a-oertel just as a side note, the website linked in your application seems to be offline:
https://kusama.polkaperson.com/swader

**Comment by alxs** [comment]
For what it's worth, I don't think it's that important that this is a fully client-side application and I'm certain you will have performance issues if you don't do any indexing before. The last project did and still had issues. For some features, I don't see this working without a backend since you need to query the chain for specific events. Since you say you want to focus on usability and avoid performance issues, maybe you want to rethink that. I'm also curious as to what and how you intend to cache to IPFS.

**Comment by a-oertel** [comment]
Thanks for your input @alxs. We will look into this more closely and get back to you next week.

**Review by takahser — CHANGES_REQUESTED** [review]
@a-oertel thanks a lot for this well-formulated application. 👍
I'm very happy with its scope and contents, but the pricing seems a bit high to me. 
While I have nothing to criticize on M1 where most of the implementation seems to take place, the pricing of M2 and M3 seems to be a bit high. For example, M2.1 and M2.2 are probably limited to making the (probably previously hardcoded) node uri configurable and adding a simple form to add and select the node. M2.3 seems quite straightforward as well: parsing the values and applying them to the sorting function. Hence, I would have expected M2 to be a bit less pricy than M1. Also, M3 seems to be of similar complexity as M2. Therefore, I'd have expected M2 and M3 to be a bit cheaper.
Please feel to correct me if I'm wrong or if I'm overlooking something here. Also, feel free to lower the price of M2 and M3. Looking forward to your reply. :)

**Comment by a-oertel** [comment]
Hey @alxs, in response to your input, we included the development of a backend in our application. Please check our recent changes.

**Comment by a-oertel** [comment]
Hey @takahser, we changed the scope of our application based on @Alxs comment. M2 includes the complete initial development of a backend to increase performance and to enable the implementation of features of the next milestone that require the chain to be queried for specific events. This leads to efforts that justify the original estimation. With that in mind, we've moved the implementation of the send tokens feature to M3. This also expanded its scope. In addition the implementation of the plugins governance, treasury and validator is not trivial and should be done with appropriate thoroughness. To deliver a high quality solution we also added a quality assurance step in M3.

**Review by Noc2 — APPROVED** [review]
Thanks for the update!

**Review by semuelle — APPROVED** [review]
👍

**Comment by a-oertel** [comment]
Hey @takahser, could you please take a look at our recent changes?

**Review by takahser — APPROVED** [review]
@a-oertel given the updated scope, I'm willing to go ahead with it as well! Good luck, looking forward to your delivery! 👍

**Comment by a-oertel** [comment]
SubIdentity milestone 3 delivery will be delayed because of the current vacation time in the team. Delivery is expected in mid of August. If any questions come up, feel free to ask.

**Pull request merged**
