### PR TITLE
Action Research for OpenGov

### PR DESCRIPTION
**Pull request by stojanov-igor**
#### Project Abstract

The proposed research project aims to conduct action research on OpenGov systems, particularly focusing on mechanisms of decentralized governance, participatory decision-making, and the application of governance frameworks within the Polkadot and Kusama ecosystems. The objective is to assess the effectiveness of these systems and provide actionable insights to improve the governance processes.

This is a response to the following request for proposal: https://grants.web3.foundation/docs/RFPs/action_research_opengov

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [X] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (Polkadot AssetHub (DOT, USDC & USDT) address in the application and bank details via email, if applicable).
- [x] I understand that an agreed upon percentage of each milestone will be paid in vested DOT, to the Polkadot address listed in the application.
- [x] I am aware that, in order to receive a grant, I (and the entity I represent) have to successfully complete a KYC/KYB check.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [ ] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Have you considered applying for treasury funding instead? Ideally something like this is funded via the treasury directly.

**Comment by stojanov-igor** [comment]
Hi @Noc2 ,

We have not considered applying for treasury funds on OpenGov. The RFP was listed in your grants program so we are responding to that request. 

Please let us know if the Request is no longer valid and if we should apply via OpenGov. 

Many thanks

**Comment by PieWol** [comment]
Hey @stojanov-igor ,
the RFPs are still valid. The RFPs that we list are things we generally want to see being worked on in the Polkadot ecosystem. This doesn't mean that those RFPs are restricting the work to be done in the scope of the Grants Program. Instead, as David said, we even prefer it if work on these topics can be funded by the treasury. We would appreciate it if you could try to do so and construct a treasury proposal for your project. We hope that the RFP is helpful to you in trying to convince the treasury.

**Comment by stojanov-igor** [comment]
Thank you both for your feedback.

I have posted the proposal to OpenGov. You can find it [here](https://polkadot.polkassembly.io/referenda/1180)

If you have any further feedback, please share it with us. Many thanks

**Comment by stojanov-igor** [comment]
Hi @semuelle, @Noc2 

Our proposal on OpenGov is currently in vote with firm opposition toward conducting this research. (229 Nays vs 4 Ayes). You can review the details here: https://polkadot.polkassembly.io/referenda/1180 

Since both the W3F and OpenGov are not interested in the project, I suggest that you remove the request for proposals. ([RFP](https://grants.web3.foundation/docs/RFPs/action_research_opengov)). I saw that other [organizations](https://polkadot.polkassembly.io/referenda/1204) are also responding to the request with very little success.

 It doesn't make sense to have an open RFP if nobody is interested in funding the proposals. Thanks

**Comment by PieWol** [comment]
Hey @stojanov-igor , thank you for the feedback. With OpenGov not willing to put funding towards this we should really think about removing the RFP. I agree. Sorry to hear that your efforts weren't rewarded. Best wishes.

**Pull request closed without merging**
