### PR TITLE
modify daos m2.

### PR DESCRIPTION
**Pull request by JimYam**
#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by JimYam** [comment]
Hi, guys. The second milestone of daos should cancel UI-related functions here. In our opinion, polkadot-js has already done a good job, and the functions are very complete, and there is really no need to redesign the UI for it. daos is a general DAO framework, which means that every developer can quickly develop their own DAO template based on daos for users to use, and every DAO can design its own UI according to its needs, but it is not necessary. daos is flexible enough and highly scalable, you can create all the DAO templates you want to create, so there should be no UI design here. The most important thing is to let developers quickly create their own DAO templates, here we will add detailed development manual documents.

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I personally think that a separate UI would have been nice. But given the price of this delivery, I’m also happy to amend it.

**Review by Noc2 — CHANGES_REQUESTED** [review]
One more thing: Could you sign the latest version of our terms and conditions (see CLAassistant)?

**Comment by JimYam** [comment]
> Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Grants-Program?pullRequest=1294) before we can accept your contribution.
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Grants-Program?pullRequest=1294) it.

Thank you for such a quick reply. UI is not necessary, and poolkadot-js has done well enough. We hope to focus more on the function development of daos, and teach developers how to use daos to create their own DAO templates. Next, we will apply for milestone 3, and will add more governance-related functions.

**Comment by JimYam** [comment]
> One more thing, before I share it with the rest of the team: Could you sign the latest version of our terms and conditions (see CLAassistant)?

Thank you for such a quick reply. UI is not necessary, and poolkadot-js has done well enough. We hope to focus more on the function development of daos, and teach developers how to use daos to create their own DAO templates. Next, we will apply for milestone 3, and will add more governance-related functions.

**Review by semuelle — APPROVED** [review]

**Pull request merged**
