### PR TITLE
Static Resource Analysis for Substrate Pallets

### PR DESCRIPTION
**Pull request by ChainSecurityAudits**
### Project Abstract

Unlike blockchains such as Ethereum, fees in Substrate are not metered during runtime execution of transactions, but defined programmatically through the so called *weights functions*. A weight function summarizes execution time and the reads and writes to storage that an entry point makes. Critically, the weight function is a trusted code, and if such a function severely underestimates the computational cost of a transaction, then the Substrate chain becomes vulnerable to denial of service attacks.

Moreover, implementing weights functions is an error-prone task. A major difficulty that we would like to address with this proposal, is that to implement weights functions, pallet developers need to correctly reason about the worst-case resource consumption of pallet entry points. We propose to create a research prototype tool for static worst-case resource analysis of Substrate pallets. As input, the tool will receive the Rust source code of a pallet and an entry point of the pallet. The output will be a symbolic expression that bounds from above the resource usage of the entry point as a function of its inputs. The analyzed resources will be the storage reads and writes and virtual time defined by a cost model on Rust operations. The project itself is part of our long-term goals to build static analysis tools for smart contract development.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application. (will be shared privately)
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
@ChainSecurityAudits Thanks for the application. It seems you haven’t filled out the google form yet. Are you still planning to do this? See https://docs.google.com/forms/d/e/1FAIpQLSfMfjiRmDQDRk-4OhNASM6BAKii7rz_B1jWtbCPkUh6N7M2ww/viewform Or do you want to apply publicly? Sorry, in case we missed anything. Alexio is currently OOO for a longer period of time.

**Comment by ChainSecurityAudits** [comment]
Hello @Noc2 , we sent of the form just now, thank you for the nudge and sorry that it took so long! We also accepted the CLA multiple times, but somehow it stills hows as pending.

**Comment by semuelle** [comment]
Thanks for the submission, @ChainSecurityAudits. We will look into it as soon as possible.

The CLA needs to be signed by https://github.com/MatthiasEgli-Audit, as they are the author of the commit.

**Comment by ChainSecurityAudits** [comment]
Thanks for the info about the author @semuelle , I changed it on the commit and accepted the CLA now.

**Pull request closed without merging**
