### PR TITLE
Create signac.md

### PR DESCRIPTION
**Pull request by hskang9**
### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying?

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] I have read and understood the [FAQs](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md), [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md) and [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).
- [] I prefer the discussion of this application to be in a private Element/Matrix channel. My username is: ``@_______``

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] Hackathon
- [ ] Personal Recommendation
- [ ] Substrate Builders Program
- [ ] Investor/VC
- [ ] Online Search
- [x] Other: Applied before

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. But the total costs currently are not the same amount of money as milestone 1 plus milestone 2. In general, it might be faster to initially apply for 30k. Additionally deliverables 0a-0d of the template are usually mandatory for all milestones, see https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md Regarding the name, when people talk about kraken in this space they usually mean the exchange https://www.kraken.com/, so I would change the name or at least add an additional word.

**Comment by hskang9** [comment]
i change branch name

**Comment by hskang9** [comment]
I changed the name to signac, details are in the application. For submission 0a-0d, I am not sure docker is necessary to submit for javascript binary file.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update and reducing the costs. You are right that it doesn’t require a docker container. Could you already add your **USDC Payment Address:**? This way we basically prevent sybil attacks, when we payout grantees. Once the address is added, I’m happy to mark it as ready for review and support the project.

**Review by Noc2 — APPROVED** [review]

**Review by gautamdhameja — APPROVED** [review]

**Review by cruikshankss — APPROVED** [review]
I am approving this (one approval). This seems like a very focused, atomic and practical solution to aid with the complexity of ink!, wasm, rust, cargo, and smart contracts in general. Thank you for applying!

**Pull request merged**
