### PR TITLE
add RedStone Network Proposal

### PR DESCRIPTION
**Pull request by AmadeusGB**
### Project Abstract

The RedStone Network is a Web3 trigger network. Users combine and arrange simple atomic trigger elements according to certain rules and procedures, and finally realize a series of automatic operation circuits. We propose a transaction firewall function that can operate between any blockchain network, regardless of the cross-chain mechanism and network topology used to perform asset transfers, and regardless of the asset type being traded, we will build firewalls with different security levels for users. Using triggers and machine learning technology, we will provide users with passive defense and active alerting capabilities.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying?

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] I have read and understood the [FAQs](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md), [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md) and [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).
- [ ] I prefer the discussion of this application to be in a private Element/Matrix channel. My username is: ``@_______``

### How Did You Hear About our grants program?

- [ ] Social Media
- [x] Hackathon
- [ ] Personal Recommendation
- [ ] Substrate Builders Program
- [ ] Investor/VC
- [ ] Online Search
- [ ] Other: _______

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Sounds like an interesting proposal. Could you specify the deliverables a little bit more detailed? For example, could you mention if something is implemented as a substrate pallet or off-chain as well as the programming language as part of the specification? Additionally it would help to clarify things like “freeze configuration” or “power grab configuration” and what exactly this means. Also what kind of alert does the system support (email, etc)? Could you mention this as part of the specification of the milestones?

**Comment by AmadeusGB** [comment]
Thanks for giving some advice! I will edit it again based on the changes and I will let you know here when I'm done

**Comment by AmadeusGB** [comment]
@Noc2 Thank you very much for your patience, I have made content adjustments based on your suggestions.
Here I would like to briefly report to you about the changes:
1. In the milestone, which modules are implemented by Pallet, such as: Passive_Defense Pallet and Active_Alarming Pallet; which modules are implemented off-chain, such as: Analyzer Module and Tracker Module, and explain that these modules will be implemented in Go/Python;
2. Explain some concepts, including: transaction limit configuration, Freezing configuration and Capture account authority configuration, which I have explained in the milestone description;
3. Clarify the alarm methods supported by the system, which have been clearly written in the milestones, including: Mail, Slack, and Discord;

Finally, thank you very much for your suggestions! Please help me to move forward with the Grand application process, thank you!

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I’m happy to go ahead with it and I will share it with the rest of the team.

**Comment by cruikshankss** [comment]
Hi @AmadeusGB, I'm excited to take a look at your application next week. Thanks for your proposal.

**Comment by AmadeusGB** [comment]
@cruikshankss Thank you so much, looking forward to your review of our Grant Proposal next week
@Noc2 I updated a commit to change Robin to Ronin. I have noticed that aUSD has been stolen, and I hope our feature can help other project parties in the future

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I’m still happy to go ahead with it.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Ah sorry, I just noticed that you provided an BNB address. Could you please change this to an ethereum address? We only do USDT payments on Kusams and Ethereum as far as I know.

**Comment by cruikshankss** [comment]
This is a really interesting & unique project that I would be interested in trying & potentially using myself. I'm glad you're writing in Rust. I haven't studied your technology plan in great depth, but seems like a solid plan from what I have read. I would be looking forward to reviewing your article and code upon delivery so I could understand better. 

Please update to an ethereum address like @Noc2 mentioned and I'll be happy to approve this (one approvall). Thanks! 

By the way, is your project name based on Minecraft redstone? If so, GREAT CHOICE!!! The redstone computers in minecraft are SOOO COOL! Lol.

**Comment by AmadeusGB** [comment]
@Noc2 Thank you so much for pointing this out. After checking, fortunately, the provided address is still the Ethereum Address, but the address description is wrong, and it has been modified.

**Comment by AmadeusGB** [comment]
@cruikshankss Your guess is exactly right! 
An important use of redstone circuits in MC is to implement automated devices, and everyone from novices to experts raves about redstone circuits. In addition, the redstone charging mechanism is very interesting, analogous to the processing fee mechanism of blockchain, redstone builds the most basic and fundamental unit of MC, and what we want to do is to build different kinds and thousands of applications from the most fundamental principle of blockchain. We believe that the probability of success is highest when learning from a successful experience, so we choose Redstone as the thing that unites our thoughts.

**Review by Noc2 — APPROVED** [review]

**Comment by Noc2** [comment]
Thanks for the update.

**Review by cruikshankss — APPROVED** [review]
@AmadeusGB Thank you for explaining a bit more of your roots and vision for this middleware.

**Review by laboon — APPROVED** [review]

**Comment by keeganquigley** [comment]
Hi @AmadeusGB are you still making progress on milestone 2?

**Comment by keeganquigley** [comment]
pinging @AmadeusGB

**Comment by keeganquigley** [comment]
Hi @AmadeusGB do you still want to continue work on this grant? Seeing as it has been over 6 months since the last delivery, I think it's probably best to close the grant for now, and you can potentially re-open it in the future should you continue to want to work on it. 

Please note that if we don't hear back from you after 2 weeks, I will go ahead with filing a PR to cancel the grant. Let me know if you have any questions.

**Comment by AmadeusGB** [comment]
@keeganquigley Still working on the second part of the development, my partner will send you the most recent updates, via comment and email!

**Pull request merged**
