### PR TITLE
Update 2nd milestone

### PR DESCRIPTION
**Pull request by aliakseikulik**
#130

### CODE REVIEW

**Comment by aliakseikulik** [comment]
@alxs Hello, please review our updated proposal. We have updated milestone 2, please let me know if you need more details or have any questions. Thanks

**Review by semuelle — DISMISSED** [review]

**Comment by alxs** [comment]
Thanks @aliakseikulik. Could you also add deliverables 0a-e from the example milestone in the [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#milestone-1-example--implement-substrate-modules) to yours? These are mandatory for all milestones, which apparently we forgot to mention at the time of the last amendment.

**Comment by semuelle** [comment]
Pinging @aliakseikulik

**Comment by alxs** [comment]
@aliakseikulik note that given the repeated delays and unresponsiveness from your side, we will see ourselves forced to cancel the grant if we don't hear from you within the next week. Please address my feedback above. Note that this amendment to submit by the end of the month has yet to be approved.

**Comment by aliakseikulik** [comment]
@alxs hello guys, I apologize for delay. Will submit updates today.  Thank you

**Comment by semuelle** [comment]
Hi @aliakseikulik, thanks for the update. Is the target delivery date of end of December still in effect? You are free to update it, given that this PR is now a month old.

**Comment by aliakseikulik** [comment]
> Hi @aliakseikulik, thanks for the update. Is the target delivery date of the end of December still in effect? You are free to update it, given that this PR is now a month old.

Hi @semuelle . We are still targeting the end of December and doing our best to deliver in time, but due to holidays, full delivery (including all deliverables like articles, etc.) may happen a week or two later. Should I update?

**Comment by semuelle** [comment]
Make it end of January, no need to be stingy.

**Review by semuelle — APPROVED** [review]

**Review by Noc2 — APPROVED** [review]

**Review by mmagician — APPROVED** [review]

**Pull request merged**
