### PR TITLE
Create xcm_btp_integration.md

### PR DESCRIPTION
**Pull request by mohamedelshami**
XCM BTP W3F open grant proposal

### Project Abstract

A proposal to integrate BTP with XCM for extended cross-chain interoperability beyond Polkadot.

The aim is to connect ICE parachain and ICON’s BTP network hub with other parachains on Kusama/Polkadot by implementing an XCM/BTP services contracts and core interfaces that adapt a logical representation of XCM instructions on BTP-enabled chains.

Short-term scope is to base implementation needed to enable arbitrary messaging and asset transfers between ICON <> ICE, as well as concept validation for multi-chain messaging.

> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying?

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] I have read and understood the [FAQs](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md), [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md) and [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).
- [ ] I prefer the discussion of this application to be in a private Element/Matrix channel. My username is: ``@_______``

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] Hackathon
- [x] Personal Recommendation
- [ ] Substrate Builders Program
- [ ] Investor/VC
- [ ] Online Search
- [ ] Other: _______

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application and sorry for the late reply. Something to be aware of: We usually don’t support the development of Solidity smart contracts (little internal knowledge, hard to keep track of what has already been developed, etc.). Additionally it seems that your application is currently focused on MoonRiver and we try to be as objective as possible when it comes to different parachains. Therefore my recommendation would actually be to apply for a grant from the moonbeam foundation, see https://moonbeam.foundation/grants/ or potentially one of the other evm chains. Apart from this, we wouldn’t support the deployment of the bridge via our grants program (milestone 2). We only focus on open source software development, which can potentially be reused by others for their projects.

**Comment by mohamedelshami** [comment]
Thanks, @Noc2 for reviewing and the feedback. It sounds like I may need to rewrite some parts of the grant to make it more clear that the primary focus is use cases of XCM over BTP, these are some examples from the project details.

- Cross-chain messaging between Parachains and other chains outside Polkadot
- Multi-assets transfers between blockchains on ICON BTP hub and Polkadot parachains
- Ability of any BTP enabled chain to control sovereign account holding a reserve for its native asset

As for Moonbeam, it's one of the many layer1 networks that's been deployed on ICON's BTP networks Testnet hub, and so the integration of other networks I've mentioned in the overview section including Near, BSC, and Harmony currently in-flight -- we anticipate many layer1 networks to connect via BTP. Happy to emphasize a bit more in the development status section to clarify that Moonbeam is an example.

We are building [ICE network](https://github.com/web3labs/ice-substrate) to become a parachain on Polkadot. It supports both Wasm (ink!) and EVM. EVM is necessary for legacy applications and the wide spectrum of developers who would develop cross-chain applications on ICE and Polkadot. In our future plans, we would like to rewrite most parts of BTP as pallets so new BTP use cases and services can be implemented in ink!.

As for milestone 2, we can reduce the scope of the demo/workshop, and remove the deployment from the roadmap.

Let me know your thoughts and further elaborate on why we think this is an interesting proposal.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the quick reply. In this case, my recommendation would actually be to focus with the grant application on potential pallets or ink! Smart contracts that you need/want to develop for your ICE network. The demo/workshop or the deployment of milestone 2 isn’t something which we would fund via our grants program and as mentioned above the solidity smart contracts are usually also something which we don’t support. Additionally some of the grants committee members might argue against funding BTP, when there is also IBC and for example the trustless ethereum snowfork bridge: https://github.com/Snowfork/snowbridge

**Comment by mohamedelshami** [comment]
Thanks, @Noc2. This sounds good, we have a few ideas on how could approach this integration with ink! - but will require a redesign of some of the relay components.

I understand why this BTP might seem like it contends snowbrige and IBC -- but BTP is not focused on Ethereum, there are other non-Ethereum-based blockchain integrations on the roadman for ICON's BTP.

**Comment by alxs** [comment]
@mohamedelshami note that we try to keep only active applications open and usually close them if there's been no activity in over 2 weeks. Are you planning to update your current one, or do you prefer to apply again at a later date?

**Comment by Noc2** [comment]
I’m closing this PR due to inactivity. But I’m happy to reopen it as soon as you are ready.

**Comment by mohamedelshami** [comment]
hey @alxs @Noc2 apologies for the late response, we haven't incorporated the discussed changes above in this proposal yet. It makes sense to close it now, and we will reopen once we've made the changes and updated the scope.

**Pull request closed without merging**
