### PR TITLE
Lunatic Games Studio

### PR DESCRIPTION
**Pull request by mahajanridhima**
Project Abstract

Lunatic Games Studio is the first play for lifestyle blockchain gaming edition. Through Web3, we are developing a revolutionary product that aims to impact our users' daily lives.

We are building a browser-based web3 game where users will need to stake $SLNT tokens to play.

Designed with unreal Engine 5 and in-house resources, the Lunatic Game Studio framework provides the players with a greek history with countless spells, societies abilities and environment.

Our sole mission is to ‘Add Value’ to our players lives!

Our NFTs are interactive in nature, i.e you can interact with them using your mouse and keyboard. We are going to build our own in-game interactive marketplace. We will be building Interactive NFTs infrastructure so that they can serve in our in-game interactive NFTs.

Grant level Level 1: Up to $10,000, 2 approvals Level 2: Up to $30,000, 3 approvals Level 3: Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

Application Checklist

[x] The application template has been copied and aptly renamed (project_name.md).
[x] I have read the application guidelines. 
[x] A BTC address for the payment of the milestones is provided inside the application. 
[x] The software delivered for this grant will be released under an open-source license specified in the application. 
[x] The grant will only be announced once the first milestone has been accepted (see the announcement guidelines).

### CODE REVIEW

**Review by takahser — CHANGES_REQUESTED** [review]
Hi @mahajanridhima 
Thanks for your interest in the W3F grants program. Usually we don't support Solidity-focused grants, since we're not familiar with the existing tooling in the Solidity ecosystem nor are we Solidity experts, which makes it difficult to evaluate grants and potential deliveries thereof. Instead, we mainly focus on developments in the Substrate ecosystem. However, your project seems to mainly rely on Solidity contracts, if I'm not mistaken. Is my understanding correct?

**Comment by mahajanridhima** [comment]
We are building this on top of the Substrate ecosystem. We did not specify anywhere that we are going to use Solidity.

**Comment by avirajkhare00** [comment]
Hey, @takahser, it's true that our GitHub org has a few experimental repos on top of solidity, but we need to work from the ground up. We are not going to use those codes to build it.

**Comment by takahser** [comment]
@mahajanridhima @avirajkhare00 I was assuming you're using solidity because you intend to build on top of EIP-721 and ERC-721. Can you elaborate on that maybe?

**Comment by avirajkhare00** [comment]
EIP-721 is a token standard. It's not depended on any language, right?
Correct me if I am wrong

**Comment by avirajkhare00** [comment]
EIP(Ethereum Improvement Proposal)-721 comes in the category of ERC
https://eips.ethereum.org/EIPS/eip-721
Also, lot of open source code around implementation of ERC-721 in substrate.

**Comment by avirajkhare00** [comment]
Hey @takahser, any update on this?

**Comment by avirajkhare00** [comment]
Hey @takahser It's been 4 days. Can you please tell us the next steps?

**Review by takahser — CHANGES_REQUESTED** [review]
@avirajkhare00 sorry for the delay. I have a couple of questions here:

1. While you're right, that there is indeed an NFT standard that is similar to  ERC-721 in some ways, it is not an exact implementation: [psp-34](https://github.com/w3f/PSPs/blob/master/PSPs/psp-34.md). Also, the [polkadot wiki](https://wiki.polkadot.network/docs/learn-nft) includes other NFT approaches that currently exist in the Substrate ecosystem. It would be helpful for us to understand, if you're planning to build on any of these existing technologies or if you plan to implement something completely different, from scratch. Both options are possible, as long as they're reasonable and justifiable.
2. A question to the [M1.1](https://github.com/w3f/Grants-Program/pull/1173/files#diff-276af145b2e5470220d821c01e4eb0a4eb19de9321a26c90ce93b544e2f319cbR75), why do you need to add a field here? AFAIK the metadata JSON schema does already support IPFS URIs.
3. Could you add a bit more information to M1.2, M2.0 and M2.1, so we can better understand, what you're planning to build there?
4. Generally, we fund the development of open-source software, but not marketing and design tasks like M1.3 and M2.2. Feel free to remove these.
5. Please note that
    > [Deliverables 0a-0d are mandatory for all milestones, and deliverable 0e at least for the last one.](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md)

**Comment by takahser** [comment]
@avirajkhare00 please let me know once you're happy with the state of your grant application, so I can take a look again.

**Comment by avirajkhare00** [comment]
Hey @takahser 
Since clubbing it with a Game didn't make sense, I have created a new grant application.
Please take a look at here: https://github.com/w3f/Grants-Program/pull/1192
You may close this PR
Thanks

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update here. I’m closing this PR.

**Pull request closed without merging**
