### PR TITLE
Faterium application

### PR DESCRIPTION
**Pull request by enfipy**
#### Project Abstract

Faterium is a decentralized voting platform that provides business tools for content creators to monetize their projects and directly engage the community on important decisions. It helps game developers, creators, and artists to easily create their own tokens, distribute them and earn by providing polls on various topics that are important to their community.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by alxs** [comment]
Hi again @enfipy, thank you for your application!

Could you be more precise with the specification of the individual pallets? For example, could you provide an API and/or specify what you mean by "creating and managing Projects", "inner Project tokens", " with or without tokens or currency" etc.

Also note that most of this or similar functionality has already been implemented elsewhere, i.e. creating organisations/profiles, voting, token factories. Could you please see if there's anything out there you may want to reuse instead, or provide a brief comparison with existing projects?

Lastly, do you have any mockups? We usually ask teams to provide wireframes or mockups if they want to deliver any UI work as part of a grant.

**Comment by enfipy** [comment]
Hey @alxs, so glad to see you again! Thanks for your answer and questions. 

First of all, we would like to clarify that the main feature of our polls is that they are a new way for creators to raise money for a project or idea with the help of the community. This is not just a DAO voting, where users create and stake tokens, and after the end of the poll receive them back. In our poll, the author himself determines which currency he wants to use for voting and what percentage of stake he will receive after the end of the poll. We called them `Crowdfunding Polls`. If we make a comparison, it's more like [Kickstarter](https://www.kickstarter.com/), where the author creates a project and selects the minimum amount of funds to raise. Then if people want, they can finance the project with their own money.  

As you requested, we prepared wireframes for our website and added them to the grant application. Please note that this is only the first version of the website, in which users will be able to create their own communities (sort of spaces or groups), own assets, set up a profile, and of course, create `Crowdfunding Polls`. In future versions of the platform, we plan to add more functionality such as poll discussions, the ability to add rewards for poll winners, the ability to create polls with fiat, and many more features.  

Now, we would like to clarify our pallets and in general the architecture of our platform. We strive for the best UX for the Faterium platform, so from the very beginning, we design the platform not only for Web3 but also for Web2 users. Initially, we planned to store a user profile and a project/community profile on-chain, something like the [Subsocial](https://github.com/dappforce/subsocial-parachain) or [Preimage](https://github.com/paritytech/substrate/tree/master/frame/preimage) approach in Polkadot. But after research, comparisons, and discussions, we realized that the [OpenSea](https://opensea.io/), [Rarible](https://rarible.com/), [Polkassembly](https://polkassembly.io/) approach is more preferable for us, [to minimize storage on the chain](https://wiki.polkadot.network/docs/learn-treasury#announcing-the-proposal).
Therefore, we decided to store data of projects/communities and users' profiles off-chain. Also, we will use the standard `Assets Pallet` to create assets on our platform. But still, we will develop a pallet for `Crowdfunding Polls`, since we have not found anything similar to it.

We've updated our grant proposal to include some schemes and APIs for our pallet and backend, and we hope this will give you a better understanding of what we'll be doing and how it will work.

**Review by alxs — APPROVED** [review]
@enfipy glad to see you too :)

Thanks for adding more details to the application and for your explanations. Sounds good to me! I'm happy to accept the application as is and will share it with the rest of the committee.

**Review by alxs — CHANGES_REQUESTED** [review]
Note that, as last [time](https://github.com/w3f/Grant-Milestone-Delivery/pull/335#issuecomment-1013504281), we would need to sign a contract if you want to be paid in fiat. Could you add an address and currency to your application in case crypto also works, or send us an [email](mailto:grants@web3.foundation) to work out a contract otherwise?

**Comment by enfipy** [comment]
@alxs Thank you for the approval :)

We decided to proceed with crypto (ERC20 USDT) currency and added the payment address.

**Review by alxs — APPROVED** [review]

**Review by takahser — APPROVED** [review]

**Pull request merged**
