### PR TITLE
Create Sandox_plugins.md

### PR DESCRIPTION
**Pull request by TradeLinkEstonia**
#### Project Abstract

The initial idea of this entire grant is to add a plug-in feature to the SanDOx IDE, so all next improvements, feature add-ons and networks support could be added by our or any other interested team in form of plug-ins.

This project is a follow-up grant of the [SanDOx IDE](https://github.com/w3f/Grants-Program/pull/1694)

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) or BTC address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by TradeLinkEstonia** [comment]
I have read and hereby sign the Contributor License Agreement.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Have you already considered treasury funding for this? Also, do you have any user feedback, or how do you think you can increase the adoption of your tool? In general, the grants program shouldn't fund projects for a longer period of time, because we are probably also not in a good position to judge what is useful and what isn't.

**Comment by TradeLinkEstonia** [comment]
Hello, David @Noc2 .
No, we didn't consider treasury funding still as I'm not very confident of it. We've pledged the Polkadot panels (network, extrinsics, RPC calls) and Ink! support while applying for the first grant and planned to do 3 consecutive applications just to stay in the [level 2](https://github.com/w3f/Grants-Program/tree/master#level_slider-levels) grants. I see that my promises were reflected in the relevant [RFC](https://github.com/w3f/Grants-Program/blob/master/docs/RFPs/IDE_for_ink_Smart_Contracts.md), where our project is indicated as "under development".

Actually, adding Polkadot panels and Ink! support is our initial plan for significantly increasing the adoption. But generally, we think that the plug-ins support may affect as well, as developers will have the opportunity to build and add their plug-ins, needed for their entire projects.
Also, I've made a [pull request](https://github.com/w3f/polkadot-wiki/pull/5347) today to include information about Sandox on the [tool index wiki page](https://wiki.polkadot.network/docs/build-tools-index), so more developers could know about it. 

If you feel it more appropriate, we can include the entire estimated scope in this one grant so that the final goal of all grants will be determined and apply to level 3. And then with the complete tool we could proceed to the treasury with new add-ons and functions, if needed.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Sorry for the late reply here. I personally still think it makes sense to push for treasury funding as soon as possible with this project. But I will mark the application as ready for review and share it with the rest of the team to get the feedback from others.

**Review by takahser — CHANGES_REQUESTED** [review]
@TradeLinkEstonia thanks for submitting this follow-up proposal. I'm a bit hesitant to accept this proposal now, also because another grant for the same RFP is still under development. However, I believe at this point it'd be a good idea to validate the community support for your project by submitting a treasury proposal instead.

BTW, I checked your previous delivery on sandox.io, however, I noticed that the _File > open project_ feature is not working:

image

Correct me if I'm wrong, but milestone 3 was already successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery/pull/1032), correct?

**Comment by TradeLinkEstonia** [comment]
@takahser 
The upload (open project) feature was not stated in the project deliverables and thus the milestone was accepted. It's just the text on the blind that was incorrect. But anyway, we haven't stopped the development after finishing the grant and gradually improve some functions. After today's update this feature is live (in Git, as well as at the https://sandox.io page), you can check.

Thank you for your opinion, I'll see how to participate in the treasury funding.

**Comment by takahser** [comment]
@TradeLinkEstonia thanks for elaborating on that - you're right, it wasn't part of the M3 specs indeed.
Thanks also for fixing and deploying it, though I've checked again and exported the project as zip, however, when trying to upload it there is another error now:
image

Regarding getting this funded, another possible avenue would be the [decentralized futures program](https://futures.web3.foundation/) that we launched yesterday. A prerequisite of the program is to involve the community by opening a post in the polkadot forum, which I think represents a good way to evaluate the community support for your project.

**Comment by takahser** [comment]
@TradeLinkEstonia unfortunately, the W3F Grants Committee has decided not to move forward with your proposal this time. I recommend you to apply for alternative funding sources at this point, as already indicated earlier. Nevertheless, we wish you good luck and success for the future of your project!

**Pull request closed without merging**
