### PR TITLE
fix: remove incorrect previous jobs

### PR DESCRIPTION
**Pull request by cor**
These descriptions have been submitted without our reviews and are incorrect

### CODE REVIEW

**Review by semuelle — APPROVED** [review]
Thanks for the info, @cor. No need to worry about the CLA.

**Review by keeganquigley — APPROVED** [review]

**Review by takahser — APPROVED** [review]

**Review by takahser — APPROVED** [review]

**Comment by takahser** [comment]
I've put it on hold to double-check if this information is accurate. After that, it can be merged.

**Comment by 0xBrainjar2** [comment]
Hey sirs, Brainjar here, Founder & CEO of Composable Finance. We have recently undergone some internal restructuring, which has caused the delay in our submission. We value the support from the W3F and plan to update the status of the grant in the coming weeks.

Regarding the issue raised in this PR, we would like to clarify that the three team members mentioned are no longer with Composable Finance. We had planned to update this information when submitting the first milestone. Their descriptions were submitted incorrectly due to an error made by the grant writer, who used a template from a previous grant instead of starting from scratch and therefore, mistakenly included the experiences of the team members involved in the grant application submitted prior to the CosmWasm grant. (see here: https://github.com/w3f/Grants-Program/pull/1171/files#diff-9e250327ede1091f86ec3e351eeaa7b3c81260a026d5495b0fecc0fed55034cdR258)

We are sorry for any confusion this may have caused and would be happy to hop on a call to provide any further clarifications needed.

**Comment by cor** [comment]
I can confirm that the information provided by @0xBrainjar2 is correct :+1:

**Review by Noc2 — APPROVED** [review]
Thanks a lot for the clarification here.

**Pull request merged**
