### PR TITLE
Dico

### PR DESCRIPTION
**Pull request by DICO-TEAM**
### Project Abstract

The `DICO` is to create a decentralized and governable ICO platform for the Polkadot/Kusama ecology. Our platform will allow entrepreneurs to quickly find investors. In a word: Be a platform to link ideas and capital.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Comment by cj1afs** [comment]
At the same time, when we were writing the substrate module, we also browsed some other existing modules. For example, when writing the KYC module, we found [identity](https://github.com/paritytech/substrate/tree/master/frame/ identity) is a good identity pallet provided by the official team. but it lacks audit and supervision.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Sorry for the late response. I’m pretty sure the Identity Module is audited, since it’s deployed on polkadot as well as on kusama. But maybe you mean something else here with audit. Could you therefore specify the functions of your pallets and clearly point out what’s unique about your implementation?  
Also you should probably add parity to your credits section, given that you reused the identity pallet: 
https://github.com/DICO-TEAM/dico-chain/blob/323a867b9b68ac39e56654174cbac9bf74b3786a/pallets/kyc/src/lib.rs 
https://github.com/paritytech/substrate/blob/dcad42f9b51130621e24c3a93ca1075cd1bb9d15/frame/identity/src/lib.rs

But also the collective pallet for your dao: 
https://github.com/DICO-TEAM/dico-chain/blob/323a867b9b68ac39e56654174cbac9bf74b3786a/pallets/dao/src/lib.rs 
https://github.com/paritytech/substrate/blob/ba153b9ae050eda022f002d74d76f98d1e339a81/frame/collective/src/lib.rs 

And please be transparent about any other project which you reuse. For example if you are just using existing implementation for the second milestone (oracle and swap) or the last milestone (nft), we don’t fund this via grants. So, we need to know what’s unique about your solution.

**Comment by DICO-TEAM** [comment]
hello, @Noc2 ,our team has made further changes. The purpose of our team is to launch the polkadot ecological ICO platform to accelerate the development of polkadot ecological applications. in this way, not only relying on web3found , but also allowing everyone/organization to participate. To enrich the ecology of polkadot, this is the mission of our team.

**Comment by cj1afs** [comment]
@semuelle Thank you very much for your patient review and guidance. The document has been updated.

**Comment by cj1afs** [comment]
> I'm sorry, but that is not enough.
> 
> For `1a`, `1b` and `1c`, please provide a list of functions that will be implemented and, for each, a description of the function. For `6`, please describe what the your vision for the pallet is, what the goal of your research is (What question are you trying to answer? What problem are you trying to solve?), how you are going to conduct it and how you are planning to report your findings.

Thanks again，The document has been updated.

**Comment by semuelle** [comment]
> The document has been updated.

Perfect, thanks.

**Review by semuelle — APPROVED** [review]

**Review by Noc2 — APPROVED** [review]

**Comment by alxs** [comment]
Hey @DICO-TEAM, how is the project coming along? Care to share a quick status update, along with an ETA if possible?

**Comment by alxs** [comment]
@DICO-TEAM note that since the grant is delayed by over 2 months and we haven't heard from you since the application, we will assume you're no longer interested and terminate the grant if we don't hear from you within the next two weeks.

**Comment by DICO-TEAM** [comment]
> @DICO-TEAM are you still interested in this? Note that since the grant is delayed by over 2 months and we haven't heard from you since the application, we will assume you're no longer interested and terminate the grant if we don't hear from you within the next two weeks.

yes, we are  still interested in this grant.

**Comment by Noc2** [comment]
> > @DICO-TEAM are you still interested in this? Note that since the grant is delayed by over 2 months and we haven't heard from you since the application, we will assume you're no longer interested and terminate the grant if we don't hear from you within the next two weeks.
> 
> yes, we are still interested in this grant.

That’s great to hear. In this case, could you also create a PR to update the timeline of the original contract?

**Comment by DICO-TEAM** [comment]
> > > @DICO-TEAM are you still interested in this? Note that since the grant is delayed by over 2 months and we haven't heard from you since the application, we will assume you're no longer interested and terminate the grant if we don't hear from you within the next two weeks.
> > 
> > 
> > yes, we are still interested in this grant.
> 
> That’s great to hear. In this case, could you also create a PR to update the timeline of the original contract?
Please forgive me for taking so long to deal with it, do we still need to update the timeline of the original contract?

**Comment by DICO-TEAM** [comment]
For the last two weeks, we have been dealing with the launch of the ksm parachain.

**Comment by alxs** [comment]
@DICO-TEAM note that since we haven't heard from you in a while and you didn't reply to our feedback on your previous delivery, we'll assume you're no longer interested and terminate the grant unless we hear from you within the next two weeks.

**Pull request merged**
