### PR TITLE
A Knowledge-Oriented Approach to Enhance Integration and Communicability in the Polkadot Ecosystem

### PR DESCRIPTION
**Pull request by rbrandao**
A Knowledge-Oriented Approach to Enhance Integration and Communicability in the Polkadot Ecosystem.

#### Project Abstract

This project is an R&D initiative towards enhancing integration and communicability in the Polkadot ecosystem. The first step encompasses a theoretical contribution to map, structure and formalize Polkadot's multi-chain environment concepts and relationships, by adopting an ontological approach. Afterwards, we expect this ontological framework to be applied on the building of a controlled natural language (CNL) and a querying engine for the Polkadot ecosystem. 

Ontologies represent concepts and relationships in a manner that approximate the way humans perceive interconnected abstractions, while promoting machine reasoning on top of that representation to offer insights to users, developers and intelligent applications. In addition to supporting reasoning capability, ontologies provide a coherent and easy interpretation, enhancing communication in the ecosystem. They allow users to navigate from one concept to another, supporting the current understanding about the fundamentals of the modeled domain, and also its natural expansion. The R&D process and contributions will be documented in a scientific paper and an ontology representation. Both will be publicly available on github.
#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (aUSD/USDT) address for the payment of the milestones is provided in the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by dsm-w3f — CHANGES_REQUESTED** [review]
However, I notice that you just copy and paste them for our template and didn't adjust them to your application. Just to clarify, the intention of these deliverables is to enable the grantee to deliver incrementally and the evaluator to access the quality of the work of the incremental deliverable.  So, for each milestone, you need to state the copyright applied, the methodology that will be used to produce the deliverable, which written part of the article associated with the specific deliverables will be delivered, and so on. This also will be used to evaluate if you have a good plan for executing the project and it will work as a contract if the grant would be approved. Hence, please be more specific regarding the mandatory deliverables in the milestones. Take your time to produce a more detailed and specific plan for the research project.

**Comment by rbrandao** [comment]
Thank you for the comments, Diogo. I understand your point.

I will adjust our proposal accordingly with the mandatory deliverables and
get it back through a pull request, asap.

Kind regards
_______________________
Rafael R.M. Brandão
rafaelbrandao(at)gmail.com

**Comment by rbrandao** [comment]
Hi, we have just updated the proposal with mandatory deliverables as requested by the template.

**Review by dsm-w3f — CHANGES_REQUESTED** [review]
Thank you for the improvements and changes. Regarding the template, I think the application is ok. One last thing, by the completion of the grant, in the last milestone, we expected to receive a full article with an acknowledgment in the body of it stating that the paper was supported by Web3 Foundation and it must be publicly available as a preprint in some preprint archive, such as https://arxiv.org/.  Can you fulfill this requirement? If yes, please state that in the paper deliverable in the last milestone.

**Comment by rbrandao** [comment]
Added required info about the article deliverable in last milestone.

**Comment by dsm-w3f** [comment]
@rbrandao thank you for adding the comment in the deliverables but I think the right place to put it is in the scientific paper deliverable or rephrased the article deliverable to match the same scope of the scientific paper.

**Comment by rbrandao** [comment]
Done. Merged deliverables 'article' and 'scientific paper' in last milestone.

**Review by dsm-w3f — APPROVED** [review]
I'm happy to support the project. The project will be shared with the committee for review.

**Comment by rbrandao** [comment]
Thanks, Diogo. Really appreciated your prompt support.

Em ter., 24 de jan. de 2023 12:10, Diogo ***@***.***>
escreveu:

**Review by Noc2 — APPROVED** [review]
Thanks for the application. I'm happy to support it.

**Review by gautamdhameja — APPROVED** [review]

**Comment by rbrandao** [comment]
> Thanks for the application. I'm happy to support it.

Thank you,  Web3 Foundation Grants Team. The MOBR team really appreciates the opportunity and the interest in our research proposal. With your support we are confident on delivering a solid outcome.

**Pull request merged**
