### PR TITLE
add Solang_Playground

### PR DESCRIPTION
**Pull request by salaheldinsoliman**
#### Project Abstract

Solang Playground is a web based IDE that will enable Solidity developers to edit, compile, deploy and interact with smart contracts. The IDE will target parachains that use the `wasm` contracts pallet as well as Solana.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. I have one quick feedback: I would remove the Solana part from the application. Our grants program specifically focuses on projects that are beneficial for Polkadot. Also, we don't support specific parachains with our grants program in order to be objective. It, therefore, would look really bad if suddenly we indirectly support Solana with this project. Apart from this, for UI-focused applications, we usually ask teams to provide some initial mock-ups or designs.

**Comment by salaheldinsoliman** [comment]
@Noc2 Hello,
Thanks for the quick feedback! I removed the Solana stuff from the application.
However, regarding the UI side, It would be a monaco code editor (very similar to VS code), with some added functionalities like compile, deploy, test and interact. Very similar to existing projects I mentioned in the application (Remix and Ink! Playground).  Is it ok to include screenshots from existing open source projects?

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. I will mark the application ready for review. But could you reduce the price? For example, milestones 2 and 3 at the moment both say: 3 months, fte of 0.5, but the total cost of milestone 2 is twice as high. Also, the estimated duration of this grant is very long.

**Comment by salaheldinsoliman** [comment]
@Noc2 Hello,
I removed the Solana stuff without removing the time/money associated, thanks for the pointer!
For the timeline, I reduced 4 months, I know it is still over stretched but does that work now? 
Thanks for your help!

**Review by Noc2 — APPROVED** [review]
Thanks for the super quick update. I'm happy to go ahead with it, but let's see what others say about it.

**Review by keeganquigley — APPROVED** [review]
Thanks @salaheldinsoliman this looks good. I was impressed with your last deliveries, and based on your track record, I'm happy to go forward with it. Hopefully this will help in getting more devs to try out Solang.

**Review by dsm-w3f — APPROVED** [review]
The deliveries from your last grant were very good, and I also think this project very useful for our community. I'm happy to go forward with it. Hope to see the results soon.

**Comment by salaheldinsoliman** [comment]
@keeganquigley @dsm-w3f Thanks for your nice words and the awesome grants program experience you provide. Let's attract more Solidity devs to our world!

**Comment by keeganquigley** [comment]
Hi @salaheldinsoliman just checking in, how is progress on M1 coming along?

**Comment by salaheldinsoliman** [comment]
@keeganquigley Hello, thanks for asking!
I have been in contact with W3F over email, stating that I will be using the 1 month spare period mentioned in my application.
Therefore, the submission will be coming in 2 weeks. Also, I have requested a hyperledger lab for this, here it is: https://github.com/hyperledger-labs/solang-playground

**Comment by salaheldinsoliman** [comment]
@keeganquigley @Noc2 
Hi folks,
Me and @tareknaser have been discussing details on how to implement Milestone 3 (Substrate node interactions). The optimum solution we have found is to make use of Contracts UI: https://ui.use.ink/.
That is, our IDE will forward the user to Contracts UI, with the WASM Blob/Contract already instantiated and ready to be called. 

What do you think?

**Comment by keeganquigley** [comment]
Hi @salaheldinsoliman sure that would be fine to forward the user there, I think the Contracts UI is a really nice tool and helps to easily see an overview of contract functions and descriptions. For milestone testing purposes it will also be helpful for us to be able to compile the contracts from source to upload to a local contracts node. Thanks!

**Comment by keeganquigley** [comment]
Hi @salaheldinsoliman any updates you can provide?

**Comment by salaheldinsoliman** [comment]
@keeganquigley Hi Keegan 
Third milestone is ready for delivery, we're or going to make the delivery PR in the next week or two :)

**Pull request merged**
