### PR TITLE
[Aviraj] Added maintenance grant ink-boxes

### PR DESCRIPTION
**Pull request by avirajkhare00**
#### Project Abstract

Maintenance grant for ink boxes

GitHub: https://github.com/w3f/Grants-Program/blob/master/applications/ink-boxes.md

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) or BTC address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by avirajkhare00** [comment]
I have read and hereby sign the Contributor License Agreement.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. I have one initial question: why do you want to update this old repo that doesn't seem to be used by a lot of projects? The smart contracts that are part of this repo are maintained in other repos already, see https://github.com/paritytech/ink-examples  So to be honest, I don't see a lot of value in updating it. A Project that is in a much better stage is for example: https://github.com/scio-labs/inkathon

**Comment by avirajkhare00** [comment]
Hey @Noc2 @takahser
Original idea is it like [Truffle Boxes](https://trufflesuite.com/boxes/) make ink-boxes which unfortunately I was unable to accomplish previous time.
I will be taking inkathon as an inspiration. Beautiful UI
My primary goal is that more and more people should come up with ideas and create their boilerplate boxes.

Also, to begin with, you can also suggest some project whose ink box I should create.

**Review by takahser — CHANGES_REQUESTED** [review]
@avirajkhare00 I have some doubts here as well. I can't justify the value added for maintaining a repo that contains an erc20, erc721 and example flipper contract that is currently not widely used in the community at that price point, especially since the maintenance seem to be limited to improving docs and comments, replying to issues ([I don't see any within ~1 year](https://github.com/nerdsince98/ink-boxes/issues)) and fixing bugs (although we don't know what bugs exist). But anyway, the [openbrush contracts](https://github.com/Brushfam/openbrush-contracts/tree/main/contracts/src/token) already features implementations of psp-22 and psp-34 which are very similar and afaik cover the same functionality. I think it's already much more established and widely used by the community, for example, they have group chats on [element](https://matrix.to/#/!utTuYglskDvqRRMQta:matrix.org?via=matrix.org&via=t2bot.io&via=web3.foundation) and [discord](https://discord.gg/9FRETSPmp9).

**Comment by avirajkhare00** [comment]
@takahser I really wish to work on this. Should I lower the price of maintainance. I promise I will deliver nice results this time. I have a lot of ideas around the same. Also, I will use inkathon as my base image.

Few people reached out to me on Telegram personally when I was actively working on it.

You are correct, in maintainance grant, scope is only limited to maintain it, but i wish to extend it with new features. Shall I create new grant altogather with lower cost or should I lower my price here. Maybe there is some missing context here.

**Review by semuelle — COMMENTED** [review]
I think in order for a project like this to be maintained over a sufficient period of time would require a larger team or community behind it. Since ink boxes doesn't seem to have a community, we currently have projects that accomplish similar results (OpenBrush wizard, Contract wizard), and the first deliveries ([1](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ink-boxes_2_0xCaso.md#general-notes-v1---dec-19-2022), [2](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ink-boxes_1_0xCaso.md#general-notes-v1---nov-21-2022)) weren't particularly promising, I would also withhold my vote.

**Comment by takahser** [comment]
@avirajkhare00 the W3F Grants Committee decided not to consider this proposal further based on the points that have already been made in this thread. We'd like to thank you for your interest in our program and wish you all the best for the success of your project, in case you decide to pursue it. Also, you're welcome to apply for other grants in the future.

**Comment by avirajkhare00** [comment]
I am happy with the decision made my W3F grant committee.

**Pull request closed without merging**
