### PR TITLE
Action Research for OpenGov

### PR DESCRIPTION
**Pull request by anaelleparity**
# Request for Proposals

## Abstract

OpenGov was introduced as a new governance system for the Polkadot ecosystem in November 2022 on Kusama, before being deployed on Polkadot in June 2023. It pioneered the transition from a centralised decision-making model to a more decentralised executive system. 

However, after 14 months of operations, there is still no comprehensive research, analysis, or review of OpenGov's model and mechanisms. This RFP submission proposes some avenues for Action Research on OpenGov to help establish a feedback mechanism and prioritise future developments for OpenGov.

## Background

The idea behind this RFP is to gather the insights of a range of academics, analysts, and governance experts from within and outside the blockchain industry to summarise the current discourse on OpenGov, formalise a theoretical framework around OpenGov, and propose practical initiatives to optimise the impact of OpenGov.

## Checklist

- [X ] I have checked the [RFPs](https://github.com/w3f/Grants-Program/tree/master/docs/rfps) to make sure this is not a duplicate.
- [ X] I have read and followed the [RFP Suggestion instructions](https://github.com/w3f/Grants-Program#mailbox_with_mail-suggest-a-project).

### CODE REVIEW

**Comment by anaelleparity** [comment]
I have read and hereby sign the Contributor License Agreement.

**Comment by anaelleparity** [comment]
Hello team,

I see that this PR is still pending after 4+ weeks. 
Is there anything that needs to be done from my end to move the review process forward?

Thanks for your help.

**Review by semuelle — COMMENTED** [review]
Hi @anaelleparity, sorry for the long wait. I have been mulling over this proposal for a while and I'm unsure how it would work. Some of the answers are easily available (when OpenGov was deployed) while others are so complex that you can probably get different conclusions based on the metrics you use (patterns in on-chain voting, challenges/setbacks, etc). Some of the questions could be discussed in an academic article while some answers are quickly outdated if they are not in a format that's updatable. 

I don't know if you had a specific use case for the results of this in mind, but perhaps it would make more sense to post this as a more general "research into OpenGov" RFP where people can pick and choose some of the suggested questions or topics to dive into and choose an appropriate medium to publish in. What do you think?

**Comment by anaelleparity** [comment]
Hello Semuelle,

Thank you very much for your feedback on this proposed RFP.
I am aware that this suggested Action Research on OpenGov does not fall into the traditional topics covered by previous RFPs, which makes it difficult to evaluate its value proposition. That said, your suggestion for "Research on OpenGov" is perfectly aligned with what I had in mind when writing this RFP.

The main use-case for this RFP is to invite and fund people to do some research on OpenGov and share insights/recommendations that can be picked up by Polkadot stakeholders (voters, devs, fellows, etc.) to propose changes to existing procedures/mechanisms. 

How this would work in practice? Interested teams choose any of the 4 topic areas mentioned (i.e the "Milestones", although there is no linearity for the delivery) and work on it from their chosen angle and with their own methodology. However, the bottomline is to have **a research that is actionable** (i.e Action research); beyond a compilation of thoughts/theories or a comparison with other governance technologies. Over time, teams with proven track records of contributing to OpenGov's improvements could form a core of researchers for R&D on OpenGov, but that is out of the scope of this RFP.

Ideally, anybody (whether familiar with Polkadot or not) should be able to contribute to this RFP, this is why a (non-exhaustive!) list of questions has been included. The list provide some starting points for teams/individuals who don't know anything about OpenGov (yet). Experienced teams will likely overlook this list, but it is better to have something than rather than nothing.

I have been in touch with Rae (Parity Asia) who has some contacts in Academia who have expressed interest in working on this project as part of their research on Governance and Blockchain technologies. 

I am happy to make any change you recommend to get things moving, so let me know what the next steps are.

Thanks!

**Review by semuelle — COMMENTED** [review]
Hi @anaelleparity, thanks and again sorry for the wait. My suggestion would be to rephrase the application slightly to make it more clear that the listed questions and milestones are _suggestions_, e.g. by calling it "Example objectives" and "Example outcomes". 

We can then start a conversation about useful combinations of those with individual applicants. What do you think?

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/decentralized-futures-a-research-for-security-governance-framework/7615/1

**Comment by anaelleparity** [comment]
Hi again @semuelle,

I have implemented your suggestions and rephrased relevant portions of the document.

Thanks. 🙏

**Review by semuelle — APPROVED** [review]
Great, thank you very much, @anaelleparity!

**Review by Noc2 — APPROVED** [review]
Looks good to me as well. But I think ideally something like this is actually funded via the treasury.

**Review by PieWol — APPROVED** [review]
Thanks for the initiative! I'm happy to go ahead with this one @anaelleparity .

**Pull request merged**
