### PR TITLE
Application for Q&A-based query builder for data analysis

### PR DESCRIPTION
**Pull request by MeerKatDev**
#### Project Abstract

We are applying with a solution in response to [this RFP](https://github.com/w3f/Grants-Program/blob/master/docs/RFPs/Open/analysis-website-and-data-platform.md). The idea is to create a user interface which will build an SQL `SELECT` query, based on a series of closed-choice questions.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by dtuzi** [comment]
I have signed the CLA on behalf of Eiger.

**Comment by dsm-w3f** [comment]
@MeerKatDev Thank you for your application. Happy to see that your company applied for a RFP. I read the application and have some questions:

1. One of the main purposes of this RFP is to enable users to make queries and reuse dashboards like Dune Analytics. I saw in your applications a tool to make it easier to make the queries but no feature to share those dashboards. Do you plan to have some features related to that?
2. The query builder proposed when used on top of a GraphQL interface would be very close to [explorer](https://www.apollographql.com/docs/graphos/explorer/) of Apollo server. Could you compare your proposed solution with this one?
3. Regarding the price, I think 24k per full-time equivalent is expensive. Furthermore, developing a query builder on top of a GraphQL interface provided for other tools doesn’t look to be a very complex task. Could elaborate more on the price formation?

**Comment by MeerKatDev** [comment]
> @MeerKatDev Thank you for your application. Happy to see that your company applied for a RFP. I read the application and have some questions:

Hi @dsm-w3f glad you're asking questions! In order:
> 1. One of the main purposes of this RFP is to enable users to make queries and reuse dashboards like Dune Analytics. I saw in your applications a tool to make it easier to make the queries but no feature to share those dashboards. Do you plan to have some features related to that? 

This proposal is the "part one" of a tool like that. I just added in the future plans section a note that it will be similar to Dune Analytics. We did not yet draw up plans for future proposals in concrete, it depends on how this first part will go. We would like to apply for a series of grant proposals, which eventually will form a complete tool like Dune Analytics and hopefully "more".

> 2. The query builder proposed when used on top of a GraphQL interface would be very close to [explorer](https://www.apollographql.com/docs/graphos/explorer/) of Apollo server. Could you compare your proposed solution with this one?


There aren't mockups so the vision of the final product might be a bit unclear, but the whole point of the application is to form query without knowing any specific language - to use the explorer you linked, you need to know GraphQL. To use other existing tools, you may need SQL or other languages. 

In our proposal, the end goal is to build a *visual* tool that let people build queries without knowing any particular language, but just answering a series of questions, like in a Google Form survey for example. From there, they could go and create graphs, statistics, and various analytics and/or metrics. 

If it is not clear yet, let me know so I can add mock ups.

> 3. Regarding the price, I think 24k per full-time equivalent is expensive. 

24k per FTE is a standard at our company, we cannot budge on that.

> Furthermore, developing a query builder on top of a GraphQL interface provided for other tools doesn’t look to be a very complex task. Could elaborate more on the price formation?

Having a definitive plan, it is an "easy" task - but most of the time we will be researching how to properly ask questions in a way that it is easy for the user to answer, and granular enough to be able to make valuable research. This requires a lot of trial and error, in addition to experienced engineers.

**Comment by dsm-w3f** [comment]
@MeerKatDev thank you for the answers. I notice that you already have [another grant application with us](https://github.com/w3f/Grants-Program/pull/1769). As described in [our guidelines](https://github.com/w3f/Grants-Program#guidelines), you cannot have two grants at the same time. Even if this is not applicable to grant applications, only one of them could be approved at the time to not violate this rule. In this way, I'm asking you to select one to move forward with it. [This application](https://github.com/w3f/Grants-Program/pull/1769) is already ready to review and with one approval then seems more feasible to be approved but it is up to you to choose.

**Comment by MeerKatDev** [comment]
> @MeerKatDev thank you for the answers. I notice that you already have [another grant application with us](https://github.com/w3f/Grants-Program/pull/1769). As described in [our guidelines](https://github.com/w3f/Grants-Program#guidelines), you cannot have two grants at the same time. Even if this is not applicable to grant applications, only one of them could be approved at the time to not violate this rule. In this way, I'm asking you to select one to move forward with it. [This application](https://github.com/w3f/Grants-Program/pull/1769) is already ready to review and with one approval then seems more feasible to be approved but it is up to you to choose.

Thank you, I hadn't notice that before. I will close this proposal and reopen it maybe in the future.

**Pull request closed without merging**
