### PR TITLE
Add wasm-opt-for-rust maintenance grant

### PR DESCRIPTION
**Pull request by brson**
#### Project Abstract

`wasm-opt` for Rust is a project to create Rust bindings to [Binaryen's
`wasm-opt`][`wasm-opt`] tool. It allows creators of WebAssemly toolchains
written in Rust to directly optimize their WebAssembly output instead of
calling a 3rd-party non-Rust binary.

[`wasm-opt`]: https://github.com/WebAssembly/binaryen

It has been integrated into

- Ink!'s [`cargo-contract`](https://github.com/paritytech/cargo-contract/pull/766)
- Substrate's [`wasm-builder`](https://github.com/paritytech/substrate/pull/12280#issuecomment-1295079049)
- Stellar's [Soroban CLI](https://github.com/stellar/soroban-cli/pull/236)

This grant will primarily provide funding to update the `wasm-opt` crate
following new releases of Binaryen, after which we will also upgrade
`cargo-contract` and `wasm-builder`.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [ ] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md). **this document doesn't exist**
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by brson** [comment]
I marked this as a level 3 because the total possible yearly budget is 72k USD, but I also included text indicating that I don't expect to spend that much, possibly significantly less. How the monthly budget is calculated is included in the text.

Note that this requests funding to fix https://github.com/brson/wasm-opt-rs/issues/40, in which upstream Binaryen does not handle Unicode correctly on windows. It is a significant bugfix and will take a number of hours.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the application. We recently discussed with our legal department that our current terms and conditions don’t fully cover maintenance agreements. Would it be possible to sign a regular contract for this via DocuSign? If so, I would mark the application as ready for review here to get the necessary number of approvals, but we would still need to sign a separate document before we merge it once enough people have approved it.

**Comment by brson** [comment]
@Noc2 Yes, I can sign a contract via DocuSign.

**Review by Noc2 — APPROVED** [review]
Great! In this case, I will mark the application as ready for review, and I’m personally happy to go ahead with it.

**Review by alxs — APPROVED** [review]

**Review by keeganquigley — APPROVED** [review]
Thanks @brson I agree that this will help for ink! and Substrate maintenance, happy to approve!

**Review by dsm-w3f — APPROVED** [review]

**Review by takahser — APPROVED** [review]
@brson I'm also happy to approve.
CC @Noc2 - Just FYI, so you can move on with the DocuSign contract.

**Comment by Noc2** [comment]
@brson Just to keep you posted: We are currently drafting the contract and will share it with you shortly. The grant is already officially accepted since it has five approvals.

**Comment by Noc2** [comment]
The agreement is signed, so I’m going to merge it. Thanks!

**Pull request merged**
