### PR TITLE
Submit the application of GreenVerse

### PR DESCRIPTION
**Pull request by hermione6**
#### Project Abstract

GreenVerse is an innovative platform that combines gamification with sustainability, empowering users to take tangible actions towards a greener future. By offering diverse eco-friendly challenges, a rewarding point system, GreenVerse makes it fun and rewarding for users to adopt sustainable habits. With impact tracking features and strategic partnerships with environmental organizations and eco-conscious brands, GreenVerse provides users with the tools and support they need to make a real difference in the world. 

GreenVerse leverages interoperability and scalability of Substrate and the Polkadot ecosystem to allow existing users and projects to interact and collaborate with it easily.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (Polkadot AssetHub (DOT, USDC & USDT) address in the application and bank details via email, if applicable).
- [x] I understand that 30% of each milestone will be paid in vested DOT, to the Polkadot address listed in the application.
- [x] I am aware that, in order to receive a grant, I (and the entity I represent) have to successfully complete a KYC/KYB check.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by h4n0** [comment]
I have read and hereby sign the Contributor License Agreement.

**Comment by h4n0** [comment]
recheck

**Comment by hermione6** [comment]
I have read and hereby sign the Contributor License Agreement.

**Comment by hermione6** [comment]
recheck

**Review by keeganquigley — CHANGES_REQUESTED** [review]
Hi @hermione6 thanks for the application. Though it looks interesting, generally we don't support parachain development or starting a company; see our [FAQ](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md#i-am-starting-a-company-that--i-want-to-use-polkadotkusamasubstrate-to-build-a-blockchainparachain-and-connect--would-i-be-eligible-for-a-grant) for more info. Also, we aren't usually interested in front-end mobile stuff unless it is beneficial for the entire community.

That being said, this may be a better fit as a [Decentralized Futures](https://futures.web3.foundation/) proposal, which aims to fund new initiatives such as parachains. They also have a broader scope of support, meaning they can fund additional areas such as marketing, audits, etc.

If this sounds good to you let me know and I will close this application.

**Comment by hermione6** [comment]
Hi @keeganquigley , thanks a lot for the reply! I've looked into the Decentralized Future program and it seems like a good match for our project. Thanks for the recommendation and please close my application here then.

**Comment by keeganquigley** [comment]
Sounds good @hermione6 thanks for your reply. I'll go ahead and close it, and you can always re-apply if it isn't accepted in DF program. Cheers!

**Pull request closed without merging**
