### PR TITLE
Application for MoveVM Substrate Pallet, part 2

### PR DESCRIPTION
**Pull request by MeerKatDev**
#### Project Abstract

This application is a response to **[Move Smart Contract Pallet RFP](https://github.com/w3f/Grants-Program/blob/master/docs/RFPs/Open/move_smart_contract_pallet.md)** and a follow-up to our [previous work](https://github.com/w3f/Grants-Program/pull/1769) on the RFP. The deliverables were submitted [with this PR](https://github.com/w3f/Grant-Milestone-Delivery/pull/974).

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [ ] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. One quick feedback from the airport: The formatting of the milestone table seems to be off. Could you fix this?

**Comment by MeerKatDev** [comment]
> Thanks for the application. One quick feedback from the airport: The formatting of the milestone table seems to be off. Could you fix this?

Thanks for noticing, yeah there were some pesky newlines. Fixed!

**Review by Noc2 — CHANGES_REQUESTED** [review]
Sorry for the delay here. I'm happy to mark the application as ready for review. Would you be willing to reduce the price? If I take your previous [grant application](https://github.com/w3f/Grants-Program/pull/1769) as a reference, this one would cost 96k ;-) Apart from this, it would be nice if we could finance the final milestone either together with some parachain teams that are willing to potentially integrate the pallet or ask the community via the treasury to support it.

**Comment by MeerKatDev** [comment]
Recheck

**Review by Noc2 — APPROVED** [review]
Thanks. Regarding the CLA, @semuelle recently added a new tool. It should be fine for now.

**Review by niklabh — APPROVED** [review]

**Review by niklabh — CHANGES_REQUESTED** [review]
.

**Comment by semuelle** [comment]
Sorry for the confusion, @MeerKatDev. I have updated the instructions for the CLA bot. Could you submit the text between the horizontal lines as a comment here, as a way of signing the CLA? Cheers!

**Comment by MeerKatDev** [comment]
I have read and hereby sign the Contributor License Agreement.

**Review by laboon — APPROVED** [review]

**Review by BenWhiteJam — APPROVED** [review]

**Review by dsm-w3f — APPROVED** [review]

**Comment by keeganquigley** [comment]
Hi @MeerKatDev just checking in, how is progress coming along?

**Comment by MeerKatDev** [comment]
> Hi @MeerKatDev just checking in, how is progress coming along?

Hi @keeganquigley , great timing! We have just submitted the deliverables 👍

**Pull request merged**
