### PR TITLE
Update anagolay-project-idiyanale-phase-1.md

### PR DESCRIPTION
**Pull request by woss**
Amending the PR https://github.com/w3f/Grants-Program/pull/719

----

As per @cruikshankss recommendation and advice, i am updating the grant with the new cost we had throughout the milestones. I didn't touch M1 since it is closed and paid out, so i put the difference in the M2.  I updated the actual time that it took us to finish this grant. As we agreed with Ashley, she will share the M2 evaluation document draft here in this PR.

### CODE REVIEW

**Review by cruikshankss — DISMISSED** [review]
I am approving this (1 approval). While working on the eval of their M2 (their final milestone), I saw how much work they completed and I recommended this cost amendment. 

I believe the updated cost is a fair trade, especially @woss has already completed the work. Since this is a Level 2 grant, they should need 2 more approvals.

Here is my [M2 evaluation draft](https://github.com/cruikshankss/Grant-Milestone-Delivery/blob/anagolay-idiyanale/evaluations/anagolay-project-idiyanale_2_cruikshankss.md) explaining the work they've completed. It's a draft because I am waiting to see if others accept this cost amendment or if I should simply accept their M2 as is. 

EDIT: [here is the merged eval](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/anagolay-project-idiyanale_2_cruikshankss.md)

**Comment by cruikshankss** [comment]
[I just commented on the M2 delivery](https://github.com/w3f/Grant-Milestone-Delivery/pull/453#issuecomment-1170587941), but want to follow up here for some clarification. 

@woss : I think the confusion may be arising here because of lack of understanding. [Here are the Idiyanale pallets](https://github.com/anagolay/anagolay-chain/tree/w3f-project-idiyanale-phase1_milestone-2/pallets). Could you provide or link to explanation of each pallet? Which are useful only for your own chain? Which pallets could potentially be used for the larger open-source community? What is your plan to further make these pallets useful to the entire open-source community? I understand that you make many dev tools in general, but I suppose I'm not sure if those are mainly usable via your CLI and UI or if the pallets are reusable and accessible to devs as well? Thank you!

**Comment by woss** [comment]
Hi @cruikshankss, you already provided the link to all the pallets, it's https://github.com/anagolay/anagolay-chain/tree/w3f-project-idiyanale-phase1_milestone-2/pallets. 

I really don't understand that is the issue. All the links are in the support repo AND in the deliverable. They didn't change since Milestone 1, i believe [this](https://github.com/anagolay/w3f-grant-support-repo/tree/project-idiyanale-phase1_milestone-2#anagolay-project-idiyanale-phase-1-nr-1---milestone-2) clearly explains the contents of the Milestone 2 regarding the already existing content in Milestone 1. 

I also do not understand what is the point of the questions.

WE are building this for everybody to use, how can we know its full and true potential at this stage, we cannot, it is up to the ecosystem to create additional value and usability. WE are building Anagolay to handle Intelectual Property storing, verifying, and transferring while building the Tech that is generic and usable by everybody. 

If you (evaluators) do not see this to be a good fit for the ecosystem, please say it, save us the time and frustrations, decline the amendment and please pay us what we have earned.  

Thank you

**Comment by woss** [comment]
@Noc2 changes are made as per your suggestion. https://github.com/w3f/Grants-Program/pull/1010/commits/3de5c445080ad8857aa7ebce37b35d2a682b81e5

**Review by cruikshankss — APPROVED** [review]

**Review by Noc2 — APPROVED** [review]
I’m happy to go ahead with it

**Comment by Noc2** [comment]
@woss It’s not a mistake, see https://github.com/w3f/Grants-Program/pull/1004#issuecomment-1172121535 We will merge it, once it has three approvals.

**Comment by Noc2** [comment]
@woss feel free to send us an update invoice for the second milestone.

**Comment by woss** [comment]
@Noc2 done

**Pull request merged**
