### PR TITLE
Veridise grant proposal

### PR DESCRIPTION
**Pull request by fredfeng**
### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying?

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] I have read and understood the [FAQs](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md), [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md) and [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).
- [x] I prefer the discussion of this application to be in a private Element/Matrix channel. My username is: ``@fredfeng``

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] Hackathon
- [x] Personal Recommendation
- [ ] Substrate Builders Program
- [ ] Investor/VC
- [ ] Online Search
- [ ] Other: _______

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
(see email)

**Comment by fredfeng** [comment]
Addressed @Noc2 's feedback.

**Comment by fredfeng** [comment]
@semuelle I just registered my account (fredfeng). Thanks!

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I’m happy to go ahead with it and I will mark it as ready for review.

**Review by alxs — APPROVED** [review]

**Review by SBalaguer — APPROVED** [review]

**Comment by alxs** [comment]
Hey @fredfeng, care to share a quick status update? When are you planning to deliver?

**Comment by fredfeng** [comment]
Hi @alxs, sorry for the late response as my git stopped receiving notifications for some reason. We’re updating the vanguard architecture to make it easier for developers to add their own detectors. We currently have a few detectors from the version of Vanguard including a reentrancy detector and we’re working on migrating that over to the new architecture.

**Comment by fredfeng** [comment]
The new version of Vanguard will be ready in Q1-2023

**Comment by alxs** [comment]
Hi @fredfeng, thanks for the reply. In that case, could you please submit an [amendment](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval) and add an estimated delivery date? Otherwise, the date the application is accepted [is considered](https://github.com/w3f/Grants-Program#2-application-review) the starting date of the first milestone.

**Comment by Noc2** [comment]
@fredfeng, just to mention it here. We are quite interested in supporting this and other security-focused initiatives. Feel free to apply for another grant for [V] or other tools that you might want to develop for our ecosystem.

**Comment by keeganquigley** [comment]
Hi @fredfeng friendly remdiner, do you plan on submitting an amendment?

**Comment by keeganquigley** [comment]
@fredfeng are you able to give us an update on the progress? If you think there will be significant delays, please consider submitting an [amendment](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval) as Alex mentioned above. Thx.

**Comment by keeganquigley** [comment]
Hi @fredfeng please note that if we don't hear back from you in 2 weeks' time we will terminate the grant due to inactivity. Thanks and please let us know if you have any questions.

**Comment by fredfeng** [comment]
> Hi @fredfeng please note that if we don't hear back from you in 2 weeks' time we will terminate the grant due to inactivity. Thanks and please let us know if you have any questions.

Hi @keeganquigley, so sorry about the delay as I don't check git messages often and missed your previous ones. could you forward future communication to my email (yu at veridise dot com) instead? We finished the prototype that I originally proposed and would like to schedule a meeting to demo what we build and discuss how we go from there.

**Comment by keeganquigley** [comment]
@fredfeng sounds good, thanks for the update. I will reach out to you by email tomorrow to schedule a call.

**Comment by keeganquigley** [comment]
After comfirming with @fredfeng in private Telegram channel, the grants committee has decided to close this grant for now. It can potentially be re-opened in the future should you want to continue to work on it, but please note that the committee will likely take the cancellation into account. Thanks for all your efforts up to this point and for your interest in the W3F grants program.

**Pull request merged**
