### PR TITLE
Democratic Governance

### PR DESCRIPTION
**Pull request by pifragile**
#### Project Abstract

Encointer has started the development of a pallet that facilitates democratic voting based on Proof-Of-Personhood and we would like to continue working on this pallet. We believe that this work can be a basis for Proof-Of-Personhood based governance protocols for varios applications such as DAOs or parachains, which could benefit from improved legitimacy when using a democratic over a plutocratic design. We are interested in building this project as it builds on top of our expertise with Proof-Of-Personhood and it lays an important foundation to facilitate non-plutocratic governance in Web3.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by pifragile** [comment]
I have read and hereby sign the Contributor License Agreement.

**Review by Noc2 — DISMISSED** [review]
Thanks for the application. I'm happy to mark it as ready for review and share it with the rest of the team.

**Review by takahser — CHANGES_REQUESTED** [review]
@pifragile could you add the missing [mandatory deliverables](https://github.com/w3f/Grants-Program/blob/fe8f6b28ef7b35af17c54abde423e9cfc85d963e/applications/application-template.md#milestone-1-example--basic-functionality) _0d. | Docker_ and _0e. | Article_?

**Review by Noc2 — APPROVED** [review]

**Comment by semuelle** [comment]
Hi @pifragile, sorry for the inconvenience, but we [just started requiring KYC/KYB checks](https://grants.web3.foundation/docs/faq#what-is-kyckyb-and-why-do-i-have-to-provide-this-data) for all potential grantees. Could you please provide the information outlined under [this link](https://in.sumsub.com/idensic/l/#/uni_JRqwo72Y5AjXaRDO)? Let me know if you have any questions or issues.

**Comment by pifragile** [comment]
> Hi @pifragile, sorry for the inconvenience, but we [just started requiring KYC/KYB checks](https://grants.web3.foundation/docs/faq#what-is-kyckyb-and-why-do-i-have-to-provide-this-data) for all potential grantees. Could you please provide the information outlined under [this link](https://in.sumsub.com/idensic/l/#/uni_JRqwo72Y5AjXaRDO)? Let me know if you have any questions or issues.

ok done!

**Comment by keeganquigley** [comment]
Thanks @pifragile this looks interesting, and at this price I'm willing to approve it as well. Good luck!

**Review by keeganquigley — APPROVED** [review]

**Comment by pifragile** [comment]
> Thanks @pifragile this looks interesting, and at this price I'm willing to approve it as well. Good luck!

thank you very much😄🥳

**Pull request merged**
