### PR TITLE
Create Rubeus_keeper_st2.md

### PR DESCRIPTION
**Pull request by dsrdrk11a**
#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (aUSD/USDT) address for the payment of the milestones is provided in the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. I shared it with @keeganquigley, who evaluated your last deliveries. I have one initial question: Would you be willing to reduce the price a little bit or add additional features? Especially the second milestone seems relatively easy to me.

**Comment by dsrdrk11a** [comment]
Hi, @Noc2 , thanks for the comments.
I've added more description of the autofill functionality to show, that we assumed smt more then there was described before. I.e. a suggestion to generate a password is actually a password generation feature as we see it and I have described it well now and added a sample picture to show what we will do. Also autofill functionality is not so simple as the password forms can be different on all websites, so we'll try to cover some of them. For example on one site there can be an `email` and `Passwd` fields and on MS they are `MemberName` and `PassWord`, more of that the forms can be split.
And also we've already slighty re-estimated the autofill milestone as it used to be +2K in the 1st stage.

**Comment by keeganquigley** [comment]
Thanks for the application @dsrdrk11a I'm happy to see it. I was impressed with your work in the last grant and would be interested in seeing it expanded upon. Just a few questions in mind:

- M2 & M3 are mostly focused on UI improvements, can you explain how your efforts will help the wider ecosystem? Any plans to build out an SDK or something similar to help developers integrate your app?
- I don't see anything listed under the **Future Plans** section. Curious about how you plan to maintain this project; do you perhaps have any future plans you would consider, such as creating a pallet, collaborating with other projects, etc.?
- The overall price still seems high to me for upgrading one smart contract and adding UI functionality. Would you be willing to lower it a bit more?

**Comment by dsrdrk11a** [comment]
Hey, @keeganquigley , thanks for your opinion!
We see Rubeus to address the broad audience offering specific benefits for all user groups: security for the most advanced, usability and flexibility for beginners. We suppose that adding Rubeus to the ecosystem will help to lower entry barrier to new users (as Rubeus itself can be a lead for the new users to the whole ecosystem), add value to the existing customers and rise the avarage number of transactions per wallet. Offering UI development in this stage of our project we don’t try to make a UX or graphical design for Rubeus as our own product, but to complete the functionality that could be used by other projects “out of the box” with their own UX. So it is still a test page (extension) functionality.
About our future plans: yes, we have’em and they are huge! As for now we plan to widen the functionality – from holding credit cards credentials to PIN codes and recovery questions, everything that should be remembered for personal use can be in Rubeus. Also we think that a 2FA on a blockchain could be a great feature, so it is seen in our future plans for Rubeus. But for now we don’t think that an API for SSO would be useful as this feature is already widely used in wallets and this could be an inexpedient competition.
Answering your supposition about the budget, I can offer to remove the 3rd milestone as this is really a common wallets’ feature and its value for contribution to the ecosystem development is not obvious, I agree with you. Also I will exclude Cypress tests from the scope of the 2nd MS as we develop a test UI, not a complete product. So, in this case the overall estimation will be 25K: 13+12.
If this is ok, I’ll add corrections to the file.

**Comment by keeganquigley** [comment]
@dsrdrk11a Got it, thanks for the detailed explanations! I think that makes sense regarding removing the Cypress tests, as long as unit tests are included for the contract itself. In this case I would be happy to support it. Once you make the changes I will mark the application as ready for review and share it internally with the grants committee. Happy holidays!

**Comment by dsrdrk11a** [comment]
@keeganquigley done!

**Review by keeganquigley — APPROVED** [review]

**Review by Noc2 — APPROVED** [review]

**Review by BenWhiteJam — APPROVED** [review]

**Review by Noc2 — APPROVED** [review]

**Pull request merged**
