### PR TITLE
DotGate application

### PR DESCRIPTION
**Pull request by ekenigs**
#### Project Abstract

DotGate is a wallet and extension management UI library specifically tailored for the Polkadot ecosystem. Inspired by successful tools like RainbowKit and WalletConnect in the Ethereum space, DotGate aims to simplify wallet integration and management for developers by providing a standardized and user-friendly interface across Polkadot projects.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (Polkadot AssetHub (USDC & DOT) address in the application and bank details via email, if applicable).
- [x] I understand that an agreed upon percentage of each milestone will be paid in vested DOT, to the Polkadot address listed in the application.
- [x] I am aware that, in order to receive a grant, I (and the entity I represent) have to successfully complete a KYC/KYB check.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@elmar._:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by ekenigs** [comment]
I have read and hereby sign the Contributor License Agreement.

**Comment by PieWol** [comment]
Hey @ekenigs ,
thank you for applying to our Grants Program :).
After skimming through your application I immediately had to think about [Talisman Connect](https://github.com/TalismanSociety/talisman-connect) which I think is exactly such a solution you are trying to create. What do you think? Did you find this project when researching about the Polkadot ecosystem? Looking forward to hear your thoughts.

Best

**Comment by ekenigs** [comment]
Hey @PieWol, thanks for checking. You are right that the projects are similar in some ways. I saw their project during my research when we were considering whether to build DotGate. However, I think there are a few important differences:

1. Framework Agnosticism: The project from Talisman is a React library, whereas DotGate is built using Web Components. This makes DotGate framework-agnostic, allowing it to be used with any frontend framework.

2. Developer Experience and Integration: We are focusing on developer experience and easy integration. DotGate handles the state of connecting with an extension internally. Additionally, we will provide React hooks to significantly simplify the integration and use of DotGate in DApps.

3. Comprehensive Documentation and Examples: We will also focus on providing thorough examples and documentation to make integration even easier.

**Comment by PieWol** [comment]
Hey @ekenigs ,
thanks for explaining. Would you be available for a quick call sometime to talk about your project? I'd appreciate it if you could book a slot in my calendar. https://calendar.app.google/e9uQsnJ1FAXAuJqn9
Thanks!

**Comment by PieWol** [comment]
Got it. Thanks for adding the article to the deliverables. Still upon further digging through existing tech I don't understand what benefit your solution will offer to developers over [subwallet connect](https://github.com/Koniverse/SubConnect-v2). You mentioned framework agnosticism as a big benefit which maybe the deprecated talisman-connect didn't have but the subwallet connect solution seems to do. So I'm currently not convinced by your application. Do you have other ideas which would offer something completely new and exciting to the dApp/ wallet space?

**Comment by PieWol** [comment]
Got it! Well I think it's great that you are planning to support more js frameworks but with React and Vue being two of the most popular framework I suspect the need for being completely framework agnostic is rather low. Do you have any evidence that this is something dearly needed within the Polkadot ecosystem? 

I also think that subwallet-connect has a pretty solid UI and I don't see why your UI would be an improvement, given the screenshots you attached. In my opinion this application doesn't bring enough improvements to the table to be awarded a level 2 grant. I hope other colleagues will provide feedback soon.

**Comment by ekenigs** [comment]
> Do you have any evidence that this is something dearly needed within the Polkadot ecosystem?

I don't have evidence. I just think it's a right approach and might be helpful for some projects.

**Comment by PieWol** [comment]
Hey @ekenigs ,
my apologies for the delay here. Sadly your application couldn't gather enough support among the committee. With a heavy heart I have to let you know that your application won't be approved.

We wish you all the best and hope that you manage to build your projects even without our support. Potentially you can convince the treasury to fund your ideas. Best of luck.

**Comment by ekenigs** [comment]
Hey @PieWol,
thank you for reviewing our application and for your time. We are considering whether to continue the project without support or to explore other ideas that might be beneficial for the Polkadot ecosystem.

**Pull request closed without merging**
