### PR TITLE
New order

### PR DESCRIPTION
**Pull request by hskang9**
#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Are you aware of https://github.com/Polkadex-Substrate/Polkadex and how is your solution different? Also isn’t the confirmation time for this potentially problematic, at least in case it’s implemented as part of a parachain?

**Comment by hskang9** [comment]
Polkadex relies on layer 2 to process its order. They have not clarified their data structure in layer 2 yet, as they did not provide any technical details after private funding. Meanwhile, all orders in this dex stays within parachain, with full open source code.

**Comment by hskang9** [comment]
In addtion, their grant is terminated, so I am not sure if this is ok for W3F to compare closed-source, private software who have not finished exposing its full system to an fully open source project with thoughtful technical consideration because previous one just had a vague idea.

**Comment by hskang9** [comment]
> Thanks for the application. Are you aware of https://github.com/Polkadex-Substrate/Polkadex and how is your solution different? Also isn’t the confirmation time for this potentially problematic, at least in case it’s implemented as part of a parachain?

It may be problematic in user experience perspective as the order may take a loading time. However, it provides clarity to its system and transactions are processed in each block atomically. I don’t see any problems except user experience.

**Comment by Noc2** [comment]
> In addtion, their grant is terminated. It is not ok for W3F to compare **closed-source, private software** who have not finished exposing its full system to an fully open source project with thoughtful technical consideration because previous one **just had a vague idea.** This is like Polkadex has a patent without even passing its technical specification requirements then claim they own every copyright in web2.0. Maybe care to look up technical details instead of raising patent trolls?

Thanks for the quick reply. I wasn’t aware that it’s closed sourced, it seems to be actively maintained https://github.com/Polkadex-Substrate/Polkadex/tree/Develop, but I haven’t looked into it in detail for a while. Could you specify this? We generally ask teams to compare their solutions to other open source software as part of the application (see template [ecosystem fit](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#ecosystem-fit)) that is similar simply because it makes no sense to fund the same project twice. This is completely independent of previous grants, etc. Obviously, if their solution is not fully open source, this would be a clear reason for us to support an alternative open source solution. The termination of their grant was because they reused code without attribution and it doesn’t matter for this grant application.

**Comment by hskang9** [comment]
If you see their active development. They have a component which is called ‘ocex’. I believe they send ingress/engress messages using snapshot from its solution. Their order primitives are not also atomic since they put vague range of numbers on trading assets, so if you are asking for potential problems, ask them.

**Comment by hskang9** [comment]
> > In addtion, their grant is terminated. It is not ok for W3F to compare **closed-source, private software** who have not finished exposing its full system to an fully open source project with thoughtful technical consideration because previous one **just had a vague idea.** This is like Polkadex has a patent without even passing its technical specification requirements then claim they own every copyright in web2.0. Maybe care to look up technical details instead of raising patent trolls?
> 
> Thanks for the quick reply. I wasn’t aware that it’s closed sourced, it seems to be actively maintained https://github.com/Polkadex-Substrate/Polkadex/tree/Develop, but I haven’t looked into it in detail for a while. Could you specify this? We generally ask teams to compare their solutions to other open source software as part of the application (see template [ecosystem fit](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#ecosystem-fit)) that is similar simply because it makes no sense to fund the same project twice. This is completely independent of previous grants, etc. Obviously, if their solution is not fully open source, this would be a clear reason for us to support an alternative open source solution. The termination of their grant was because they reused code without attribution and it doesn’t matter for this grant application.

There are always two sides of the story. Here is the Polkadex’s response on grant termination.

https://www.reddit.com/r/polkadex/comments/pu2v01/why_was_polkadexs_web3_foundation_grant_terminated/he0mers/?utm_source=share&utm_medium=ios_app&utm_name=iossmf&context=3

**Comment by hskang9** [comment]
I am leaving screenshots of the comments as I concerned there is corruption in this organization. This is because:
1. This organization has passed [Substrate Builders Program](https://substrate.io/ecosystem/substrate-builders-program/) as a closed-source project violating its code of conduct a year ago.
2. The project was even in the [Polkadot Decoded 2022](https://www.youtube.com/watch?v=NjQtIkxpS9Q) without any technical demo or specification while going through Substrate builders program when it is supposed to be passing at least a milestone.
3. @Noc2 has not even verified the source on the termination of the grant.

I will not talk privately in Element/Matrix Channel for every application for every grant until there is a clarification on the reasons for the concern.

Screen Shot 2022-09-05 at 8 37 27 PM

Screen Shot 2022-09-05 at 8 47 57 PM

**Review by Noc2 — COMMENTED** [review]
Not sure if I fully understand your concern about the grant application and polkadex here, so I try to clarify things. But let me know if I misunderstood something, I’m also happy to jump on a call if this helps. You can also record everything if this would help. I’m very much fully committed to complete transparency.    

- First, I simply asked you to compare your solution to potential similar solutions in the ecosystem as part of the application and polkadex came to my mind). Some members of the grants committee are less technical, might not be aware of it, etc. So in general it helps to add this information to the application. This is all I asked for.
- Regarding polkadex see: https://github.com/w3f/Grants-Program/blob/master/docs/accepted_grant_applications.md This list only terminations that happened due to a breach of the terms of the grants programs and polkadex clearly was terminated and breached their contract. So the Reddit post is wrong, regarding the reason see my post above. Not sure what you mean regarding “@Noc2 has not even verified the source on the termination of the grant,”. The reason I haven't replied here yet, is simply that I haven’t had the time in the last few hours. 
- Regarding the Substrate Builders Program, It’s run by parity, not Web3 and it’s not a requirement of the SBP to open source everything as far as I know. The SBP team also gets access to private repos as part of the review process as far as I know. But I’m no expert when it comes to the SBP. That said, with a quick google search I found the following: https://www.parity.io/blog/substrate-builders-program-milestone-update-october-2021, and I’m not sure that certain branches of the polkadex repo contain the code as an open source delivery. 
- Regarding “Polkadot Decoded 2022”, if I remember correctly it was not a requirement to have a “technical demo or specification” for presenting during this event. It was decided via [vote](https://decoded.polkadot.network/faq/?category=voting&item=how-to-vote), who presents.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Regarding the application itself, I just like to add that I’m happy to go ahead with your milestone 1 since we have clarified that there isn’t any similar open source solution easily accessible. At least I haven’t found any. However, I’m not sure we should support your milestone 2 since it specifically focuses on Subquery and it might be better to apply to the [SubQuery Grants Program](https://subquery.network/grants) in this case, also since Web3 tries to be as objective as possible. So I personally would be willing to go ahead with milestone 1 for now. In the meantime, I will mark your application as ready for review, since others might have a different opinion about this.

**Comment by hskang9** [comment]
@Noc2 I changed milestone 2 with frontend api.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. But why did you increase the price of milestone one without changing the amount of work?

**Comment by hskang9** [comment]
Quality of documentation; We are now writing out own docs instead of gitbook with guides including revolving tools in the parachain. I will specify guides then.

**Review by alxs — CHANGES_REQUESTED** [review]
@hskang9 thank you for your application. A big +1 from my side for the focus on documentation of your application. The [Overview](https://github.com/w3f/Grants-Program/blob/606d803b024a7419f6c9a9496a2a53c2d569ab92/applications/new-order.md#overview) and [Problem Addressed](https://github.com/w3f/Grants-Program/blob/606d803b024a7419f6c9a9496a2a53c2d569ab92/applications/new-order.md#problem-addressed) sections in your application are identical, could you remove the duplicate contents? And while the specification for milestone 1 is highly detailed, you don't provide one for milestone 2. Could you please describe the functionality these two deliverables will provide?

**Review by alxs — CHANGES_REQUESTED** [review]
@hskang9 that's more of a high-level description. Could you describe their API and specify the functionality they will provide?

**Comment by hskang9** [comment]
@alxs what else?

**Comment by alxs** [comment]
Thanks @hskang9. To me, those seem like rather simple APIs and I'm not sure if the milestone price is justified. But more importantly, they seem incomplete - how would users know which pairs exist or which assets are in each pair? Shouldn't they be able to query their orders? Also, the `add_pair` and `remove_pair` operations won't be useful to normal users. Note that I'll be out of office for a while, so I'll let the rest of the committee provide more feedback and approve your application if they decide to.

**Comment by hskang9** [comment]
It should be incomplete as getting user's order usually involves with indexer. If all orders are done in the runtime, it would just be a bottleneck. If the frontend API and documentation of interacting with the blockchain does not matter, I can just remove the second milestone.

**Comment by hskang9** [comment]
@alxs before you evaluate, **what kind of production experience you had when you launch an web3.0 app**? It is just totally absurd that sudo users are simply not users.

**Review by Noc2 — APPROVED** [review]
Sorry for the late response here. I was OOO for a longer period of time and @alxs is now also ooo. In any case, I’m happy to go ahead with it and we can still approve the second milestone later as a follow-up grant.

**Comment by hskang9** [comment]
Thank you for your clarification. I value more on shipping and building for community so it is never too late to discuss later with follow up grant.

**Review by takahser — APPROVED** [review]

**Review by alxs — APPROVED** [review]

**Comment by hskang9** [comment]
Hey @alxs @Noc2 I made solidity implementation last month, and the reference project Kujira Fin was a cunt project with closed source. https://twitter.com/teamkujira/status/1595490930668490752?s=46&t=YCMkAyRon50vEIei4KewNA I will amend project and replace reference with solidity implementation.

**Comment by keeganquigley** [comment]
Thanks @hskang9 can you give us an update on M1? Do you still plan to submit an amendment?

**Comment by keeganquigley** [comment]
Hi @hskang9 friendly reminder on your comments regarding the implementation. We ask that you would submit an amendment if you plan on pivoting from your original plans.

Also, just something to keep in mind, we don't generally support Solidity development since we aren't experts in it. But feel free to submit the amendment regardless and the committee will take a look at it. Thanks!

**Comment by keeganquigley** [comment]
Hi @hskang9 please note that if we don't hear back from you in 2 weeks' time we will terminate the grant due to inactivity. Please let us know if you have any questions.

**Comment by hskang9** [comment]
It is done in EVM for now [here](https://github.com/standardweb3/new-order-contracts). I wonder if BUSL still applies to the grant?

**Comment by semuelle** [comment]
> @keeganquigley It is done in EVM for now [here](https://github.com/standardweb3/new-order-contracts). I wonder if having BUSL license still qualifies to the grant?

As @keeganquigley said, we don't usually fund Solidity projects. Regarding BUSL, we haven't had any projects involving it, so we haven't looked into it, but personally I'd stay away from it for now as it's [not technically an open source license](https://mariadb.com/bsl-faq-adopting/#osl).

**Comment by hskang9** [comment]
Ok I might consider GPL-3.0 on Substrate runtime module as there were many grifters who just copies the smart contract in EVM developer ecosystem, but Rust is harder and have many other components. The company cannot maintain Substrate blockchain because budgets are tight, but yeah I want this grant to be done.

**Comment by hskang9** [comment]
Ok so After thinking, Polkadot is currently not ready to implement UX compared to EVM implementation of this. 
To build fully functional implementation of this with web app, I need:

- Next.js React hook library like https://wagmi.sh/. 
- Easier signing UI module like https://web3modal.com/

As a CEO of a startup, I need to ship something that works and can be used in the market, so I might not be able to work on this until 2022 Q3 until EVM implementation is finished. Meanwhile, I think extra milestone may be added for adding React hook library.

**Comment by semuelle** [comment]
Thanks for the update, @hskang9. I suppose you mean Q3 2023. If you are also planning on adding milestones and/or changing contents of the grant, I would suggest we cancel this one and you can apply for a new grant when you are ready. Alternatively, could you submit an amendment to the current one with an updated timeline (and possible changes in contents)?

**Comment by 0xCaso** [comment]
Hi @hskang9, try to see if the following libraries can fit your project:
- React hook library: [useink](https://github.com/paritytech/useink)
- Connect wallet modal: [SubConnect](https://github.com/Koniverse/SubConnect)

**Comment by hskang9** [comment]
Thanks, but I would prefer react hook for runtime. At least there is a react hook, I guess Polkadot finally figures out what is missing.

**Comment by hskang9** [comment]
Why can't you just make react hook out of polkadot.js example code? it has all things there.

**Comment by 0xCaso** [comment]
I don't think complaining this much here will help a lot. I agree a `wagmi` like library is more than needed, and If you think `useink` cannot be a good starting point, you can propose a new grant (as you stated) to build something similar to it.

**Comment by semuelle** [comment]
[Please keep the conversation professional](https://github.com/w3f/Grants-Program/blob/master/CODE_OF_CONDUCT.md#L32), @hskang9. 

I would again like to ask you to submit an amendment with an updated timeline. Alternatively, if you prefer to work on other things first, let's cancel it for now and you'd be free to (re-)apply at any time.

**Comment by Noc2** [comment]
@hskang9 Please also see our [Code of Conduct](https://github.com/w3f/Grants-Program/blob/master/CODE_OF_CONDUCT.md) and the [terms & conditions](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/T%26Cs.md#6--obligations-of-user) and consider this an official warning.

**Comment by keeganquigley** [comment]
Hi @hskang9 just following up. Reminder that if we don't receive an amendment after 2 weeks or so the committee will likely terminate the grant due to inactivity.

**Pull request merged**
