### PR TITLE
Update stable-asset.md

### PR DESCRIPTION
**Pull request by shengda**
#286

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### CODE REVIEW

**Comment by shengda** [comment]
The reason for the amendment is, during our deployment of milestone 1 and 2 to Mandala, we found that support of yield asset and amplification update are extremely import for Polkadot ecosystem assets.

We spent more than three weeks to implement, test and deploy our solutions in Mandala. It works well and we are planning to deploy to Karura early next week. We believe it’s sufficient as milestone 3 deliverable.

As for stable savings, we are going to apply it as a separate grant since its work scope is bigger than a single milestone, especially with XCM integrated.

**Comment by alxs** [comment]
@shengda sounds good, thank you for the update. Could you provide a few more details on those two items? What do you mean exactly by yield assets, and what are amplification parameters? Ideally, please update the summary on lines 51-53.

**Comment by shengda** [comment]
I have removed Stable Saving from the project details, and provided more details on the milestone 3 deliverables.

**Review by alxs — APPROVED** [review]
Thanks, looks good to me! I'll go ahead and share it with the rest of the team.

**Review by Noc2 — APPROVED** [review]

**Comment by takahser** [comment]
@shengda Thanks for the amendment proposal.

Quoting from the application document:

> Comprehensive tests that cover yield asset and _amplification parameter_ change

A) I'm still confused about the meaning of _amplification parameter_. Could you elaborate on that?

> Since all assets in the baskets are of the same value peg, their prices should fluctuate about the peg prices with low variation expected so that the overall collateral ratio should be slightly over 100%

B) I was just wondering why you expect it to be >100% and not around 100% since the fluctuations obviously can go both directions. Note that this is not relevant for the acceptance of the amendment since your application was already accepted, I'm just being curious. Apologies in case this was already discussed. :)

**Pull request merged**
