### PR TITLE
Revert "Terminate Relation Graph"

### PR DESCRIPTION
**Pull request by relationlabs**
Reverts w3f/Grants-Program#1128

### CODE REVIEW

**Comment by relationlabs** [comment]
Since there is no source code in the milestone1 we submitted before, the milestone1 is not easy to check. so we completed the milestone1, 2, and 3 , hoping to submit all the milestones at one time. Now that we're finished these developments task, hopefully revert the aborted state and allowing our delivery to be checked.

**Review by Noc2 — CHANGES_REQUESTED** [review]
It’s great to hear that you are still interested in this project. So just to double check: You open-sourced your code at this stage and we can review the code?

**Comment by relationlabs** [comment]
> It’s great to hear that you are still interested in this project. So just to double check: You open-sourced your code at this stage and we can review the code?

yes, in this version, we finished all functions and opened the source code. pls help to review them.

**Review by Noc2 — APPROVED** [review]
Sorry for the late response. I’m happy to revert the termination and will share the PR with the rest of team. Usually we would probably ask you to apply for a new grant instead, but I think in this case it’s a lot easier to update the existing document. But the PR itself still requires three approvals.

**Review by alxs — APPROVED** [review]
Note that the team already submitted their delivery here: https://github.com/w3f/Grant-Milestone-Delivery/pull/569

Application PR: https://github.com/w3f/Grants-Program/pull/928

**Review by laboon — APPROVED** [review]

**Pull request merged**
