### PR TITLE
Ruby Substrate client

### PR DESCRIPTION
**Pull request by xuxiaohu**
### Project Abstract

>This library Support providing additional convenience methods to deal with substrate in ruby(like py-substrate-interface)。 include SR25519/ED25519， submit sign extrinsic，get chain data。

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Comment by semuelle** [comment]
Hi @xuxiaohu, thank you for your application! Looks interesting. However, we don't usually sign two simultaneous grants; it might have to wait until after approval of your second NFT explorer milestone.

We already supported a Ruby Substrate client a while back: https://github.com/itering/scale.rb. Couldn't you use (and contribute to) this one? Also, may I ask what your motivation for building this is? Are you planning to use it yourself, or who is your target audience? Since you left the `Development Status` section empty, do I understand correctly that you haven't done any work towards this yet?

**Comment by xuxiaohu** [comment]
> Hi @xuxiaohu, thank you for your application! Looks interesting. However, we don't usually sign two simultaneous grants; it might have to wait until after approval of your second NFT explorer milestone.
> 
> We already supported a Ruby Substrate client a while back: https://github.com/itering/scale.rb. Couldn't you use (and contribute to) this one? Also, may I ask what your motivation for building this is? Are you planning to use it yourself, or who is your target audience? Since you left the `Development Status` section empty, do I understand correctly that you haven't done any work towards this yet?

Yes, We have used the scale.rb gem in our project(https://app.uniarts.me/), But now there is no Sr25519 gem in ruby, and no submit extrinsics in scale.rb gem. So we want to write the gem to help other ruby developers . And I add the `Development Status` section.

**Comment by semuelle** [comment]
> We have used the scale.rb gem in our project

Have you considered contributing your work to the scale.rb repository, seeing that there would be quite a bit of overlap between the two projects? Is your work based on a fork of scale.rb?

**Comment by xuxiaohu** [comment]
> > We have used the scale.rb gem in our project
> 
> Have you considered contributing your work to the scale.rb repository, seeing that there would be quite a bit of overlap between the two projects? Is your work based on a fork of scale.rb?

I want to wirte SR25529 gem, and maybe submit extrinsics works is suit to merge to scale.rb.

**Review by semuelle — APPROVED** [review]

**Review by Noc2 — APPROVED** [review]

**Comment by takahser** [comment]
Hi @xuxiaohu
I don't see any activity on your 2nd milestone yet. Is there any way we can support you?

**Comment by xuxiaohu** [comment]
> Hi @xuxiaohu I don't see any activity on your 2nd milestone yet. Is there any way we can support you?

Sorry, I am updating the metadata 14, already finish 70% jobs.

**Comment by takahser** [comment]
Very good, looking forward to your delivery! Thanks for the update.

**Comment by semuelle** [comment]
Any updates on this, @xuxiaohu? Could you submit an amendment to your application with an updated timeline? If we don't hear back from you in the next two weeks, we will assume that you are no longer interested in completing the grant and will cancel the contract. You would be free to reapply.

**Pull request merged**
