### PR TITLE
Threshold signature wallet

### PR DESCRIPTION
**Pull request by gguoss**
### Project Abstract

ComingChat is a privacy social software that supports the signal protocol at the bottom. Substrate supports sr25519 and Schnower's multi-signature, but does not support threshold signatures.  The purpose of this project is to provide a threshold signature wallet for the substrate blockchain that supports the sr25519 protocol.
Implementation categories include: 
  -  End-to-end private encrypted group chat based on ComingChat, which serves as the basis of private communication for each distributed node with threshold signatures.
  -  Implement the MAST protocol of BTC taproot in the form of a module on Substrate, which is used to combine the multisig logic of sr25519 to implement threshold signatures based on aggregate signatures.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Comment by semuelle** [comment]
Hi @gguoss, thanks for the application. We will look into it as soon as possible. In the meantime, could you 

- sign the CLA,
- add documentation and test deliverables to each milestone, such as in our [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#milestone-1-example--implement-substrate-modules), 
- add sections `Ecosystem Fit` and `Development Status` as per the application template, and
- add some more technical details? This could be interface definitions, architecture diagrams, tech stack, wireframes or design documents on the UI and/or textual descriptions of the most important aspects of your deliverables.

**Comment by rjman-ljm** [comment]
Ping @semuelle

**Comment by AAweidai** [comment]
Ping @semuelle

**Comment by semuelle** [comment]
@AAweidai, thank you for the updates. Could you get in touch with kuba at web3.foundation to arrange a time for a pitch call?

**Comment by duyh37** [comment]
> @AAweidai, thank you for the updates. Could you get in touch with kuba at web3.foundation to arrange a time for a pitch call?

Hi , @semuelle 
We want to confirm with you that we contacted @kuba:web3.foundation from the element, right?

**Comment by semuelle** [comment]
Yes. Email would work as well.

**Comment by duyh37** [comment]
> Yes. Email would work as well.

Ok, Could you give me Kuba's email address ?

**Comment by semuelle** [comment]
kuba at web3.foundation

**Comment by gguoss** [comment]
@semuelle  Is there anything we need to modify further?

**Comment by semuelle** [comment]
We have a bit of a backlog with evaluations, it will probably take a few days before the rest of the team had a chance to read your proposal. Sorry about that.

**Comment by alxs** [comment]
Hey @gguoss. Several things here, aside from the discussion above which seems unrelated to the application:

- Could you explain briefly what the advantages of your approach are compared to the existing [multisig pallet](https://github.com/paritytech/substrate/tree/master/frame/multisig)? I only see privacy as a potential advantage if the keys of other authorized signers that aren't taking part in a transaction aren't disclosed, but this seems like a very slim benefit in relation to the price.
- Either way, the price seems to me disparately high in relation to what you want to implement.
- As pointed out in our [README](https://github.com/w3f/Grants-Program/#guidelines), not only must all code produced as part of a grant be open-sourced, but it must also not rely on closed-source software for full functionality. This would mean in your case that you would need to open-source ComingChat, which currently isn't in your public [repos](https://github.com/coming-chat).
- I don't see how the deliverables of milestone 2 wouldn't already be included in milestone 1. Deliverable 1a. of M2 is "Construct Merkle tree and 1b. "Build an aggregated signature transaction" while the milestone 1 deliverables describe "generating a Merkle tree" and "sending the transaction that has completed the aggregation signature".
- Many of the advantages of MAST that you list in your application are straight out copied from the MAST BIP and simply do not apply to Polkadot. See [Ecosystem fit](https://github.com/w3f/Grants-Program/blob/364b104ed99101e56e3ebc36ed0b240262abeb7a/applications/threshold_signature.md#ecosystem-fit) vs. [BIP](https://github.com/bitcoin/bips/blob/master/bip-0114.mediawiki#merkelized-abstract-syntax-tree) (there is no "script size and opcode limit" on Polkadot). There are also no "contracts" or "scripts" as you refer to several times.
- In general, I can't make head nor tail of the idea of using MAST here. MAST is entirely defined in terms of Bitcoin's scripting capabilities and language so I'm puzzled as to why or how you plan to "[implement MAST](https://github.com/w3f/Grants-Program/blob/364b104ed99101e56e3ebc36ed0b240262abeb7a/applications/threshold_signature.md#technology-stack)" in your pallet. It should be easy to modify the mulstisig pallet to support sending transactions from a multisig without disclosing the accounts that haven't signed it e.g. via Merkle trees, without that having anything to do with MAST and of course this pallet would need to be included in the runtime so you would not have this functionality on Polkadot (as shown on your mock-ups). Same goes for computing the Merkle tree and derived account and generating signatures off-chain.
- In practice, if you want this functionality in your application (or e.g. for Polkadot), you'd likely want to leverage something like [FROST](https://eprint.iacr.org/2020/852.pdf) at the application level and drop the pallet altogether. If you want it in your runtime, you'd likely want to start by forking [schnorrkel](https://github.com/w3f/schnorrkel), implementing the necessary changes in your fork and then modifying your host+runtime, but this is not likely to be easy and carries obvious security implications unless you really know what you're doing. The approach above would be a compromise, though I'm not sure of the tradeoffs.
- You did not pitch us anything during your pitch call, which would have been your opportunity to explain to us the thought process behind your application.

Given the issues above and assuming I'm not really misguided somewhere, from my side I won't approve your application. Feel free to clarify in case I misunderstood something.

**Comment by gguoss** [comment]
@alxs Thank you for pointing out, for the recent detailed related questions, we will update the answers to these recent questions, and we will update them in the last 2 days.
We have a Substrate taproot to implement a complete solution. We should completely integrate this solution onto this grant, and we can see that this grant is very suitable.  https://github.com/chainx-org/Substrate-taproot/blob/main/README.md

**Comment by duyh37** [comment]
Hey @alxs 

Thank you very much for pointing out the problem and raising the confusion in detail. I hope our supplement can answer your confusion and change your decision about this grant.

- Advantages of threshold wallets compared to existing multisig pallet

Compared with the existing multisig pallet, the threshold wallet has three main advantages. One is the address privacy brought by the aggregate signature, the other is that the aggregate signature saves a large amount of handling fees, and the last is the concealment of transactions brought by the MAST contract. Concealment. What needs to be emphasized here is that the fee saved by aggregating signatures will be very different due to the frequency of user use and the number of multi-signatures.We gave a more detailed introduction to the [calculation of transaction fees](https://github.com/w3f/Grants-Program/blob/be37bb0369f6a3aee7eb0463f71d1cdf0e51b2fa/applications/threshold_signature.md#save-transaction-fees)

- About Grant development costs

  Time to achieve milestone1： 4 week

  Cost of Milestone1( 5 developer * 4week + 1 PM * 4week + 1 test engineer * 4week):

  - Operating activities paments: $5600 ( Rent and Devices: $200 per employee * week )
  - Developer payments: $36000 ($1800 Rust developer *4 week)
  - Product Manager payments: $7200 ($1800 per PM * 4week)
  - Test engineer payments: $6000 ($1500 per Test engineer * 4week)

  - Total Cost: $54800

  Time to achieve milestone2： 4 week 

  Cost of Milestone1( 5developer * 4week + 1 PM * 4week + 1 test engineer * 4week):

  - Operating activities paments: $5600 ( Rent and Devices: $200 per employee * week )
  - Developer payments: $36000 ($1800 per Rust developer *4 week)
  - Product Manager payments: $7200 ($1800 per PM * 4week)
  - Test engineer payments: $6000 ($1500 per Test engineer * 4week)

  - Total Cost: $54800

- About open source ComingChat

  The code we apply for Grant is mainly about the code of the threshold signature pallet but ComingChat , so we won't open source ComingChat. We only use ComingChat as a tool, so that Polkadot ecological users can use this function more conveniently,but it does not mean that other software cannot call the interface we provide to complete the threshold signature. Based on your consideration that all of Grant's code should be open source, we will not regard ComingChat related code as the content of Grant, but will change it to provide three versions of interfaces for multsign interaction : SWIFT, JAVA and JS .

- About Milestone's arrangement

  Our idea is to manually construct the test data first and complete the work on the chain as Milestone1. The main work of Milestone2 is to complete different versions of multisig interactive interface work. We have updated the details of [Milestone in the readme](https://github.com/w3f/Grants-Program/blob/be37bb0369f6a3aee7eb0463f71d1cdf0e51b2fa/applications/threshold_signature.md#development-roadmap-nut_and_bolt).

- About MAST contract in Substrate

  - Technical part

    We realize that there is a big difference between Substrate-based account and Bitcoin-based UTXO, so we do not directly follow the code in Bitcoin BIP, but redesigned the account system of substrate.[Substrate_MAST Contract](https://github.com/chainx-org/Substrate-taproot/blob/main/README.md#customized-substrate-mast-contract).

  - Application part

    The upgraded Substrate taproot will solve many existing demand scenarios due to its address anonymity and concealment of transactions . For example， [On-chain token crowdfunding and distribution system](https://github.com/chainx-org/Substrate-taproot/blob/main/README.md#business-scenario-1)，[DAO system](https://github.com/chainx-org/Substrate-taproot/blob/main/README.md#business-scenario-2-anonymous-voting-system) and so on.

- About trust in ComingChat

  ComingChat is an encrypted communication software that has more than 150K registered users and covers more than 100 countries. It can be trusted. Due to the originality of the blockchain, we think it will become a good tool in the Web3.0 era. As the number of its users increases, the crisis of trust will gradually be eliminated. In addition, as we said above, the content of our grant this time is mainly for the development of pallets and interfaces, and is the development of infrastructure. In other words, if users do not trust ComingChat, they can also use other software to access the threshold wallet pallet to complete the use of threshold signatures.

- About pitch call

  We are sorry again that the last pitch call did not introduce you to the details of our project clearly ,because we mistakenly thought that the pitch call was asking for technical details. We look forward to the opportunity to have pitch call again . We will prepare more fully.

In  summary, we believe that the threshold wallet mentioned in this Grant is a very big improvement compared to the existing multi-signature module. Judging from the development content in Milestone, the price is reasonable. And the Grant's core content is the development of pallets and interfaces related to aggregated signatures and MAST contracts. The interaction in ComingChat is more like an additional contribution to substrate ecology, it is not included in the grant, so its lack of open source or trust should not be used as a reason to reject this grant.

Looking forward to your reply, please feel free to point out any problem about our content.


Best.

**Comment by alxs** [comment]
Hey @duyh37. Thank you for the elaborate response but I still see a number of significant issues with the application and your reasoning.

> Advantages of threshold wallets compared to existing multisig pallet

Agree with your points but as I already pointed out FROST or similar would be a better approach to solve what you intend to achieve. This is the approach we're likely to pursue for Polkadot, whereas your proposed solution seems rather hacky and is in my opinion unlikely to be reused.

> Grant development costs

The cost breakdown for milestone 2 is copy-pasted from M1.

> About open source ComingChat

Right, I now realise this is not part of the deliverables, but then why did you include so much information about it and all the mockups in the application?

> About MAST contract in Substrate

I still don't think your approach makes a whole lot of sense for the reasons I pointed out in my last comment.

> trust in ComingChat

Usage metrics are [no indication of a platform's security](https://haveibeenpwned.com/).

Given the above points & my previous concerns and seeing as your application has now been in the review stage for 3 weeks without raising further interest from the committee, I'll go ahead and close it. Nevertheless, I'd like to thank you wholeheartedly for your efforts and interest in the grants program. Best of luck with your project.

**Comment by gguoss** [comment]
@alxs I'm sorry, but you will regret your shortsightedness.

**Pull request closed without merging**
