### PR TITLE
Application: Subalfred

### PR DESCRIPTION
**Pull request by AurevoirXavier**
#### Project Abstract

- [Project GitHub](https://github.com/hack-ink/subalfred)
- [Project Documentation](https://subalfred.hack.ink)

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the application. We currently don’t pay teams in DOT, see https://github.com/w3f/Grants-Program#pencil-process Could you update your preferred payment method and address? Regarding the deliveries, Deliverables 0a-0d of the [template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#milestone-1-example--implement-substrate-modules) are usually mandatory for all milestones. Also, could you integrate the specification of what you deliver into the milestones, with as many technical details as possible? These are basically the requirements of our contracts according to our terms and conditions. Regarding your first milestone, it’s currently not fully clear to me what you have already implemented and what you will implement as part of the grant. In general, we recommend focusing on new/additional work, but we obviously will take into consideration that you already put a lot of effort into the project.

**Comment by AurevoirXavier** [comment]
@Noc2 Could you review it again?

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. But I noticed that the total costs are no longer below 30k and therefore this would be a level 3 grant. I recommend reducing the costs to 30k again.
Also in general the day rate and FTE currently don’t make a lot of sense in most cases. See milestone 2 vs milestone 3 for example.

**Comment by AurevoirXavier** [comment]
> Thanks for the update. But I noticed that the total costs are no longer below 30k and therefore this would be a level 3 grant. I recommend reducing the costs to 30k again. Also in general the day rate and FTE currently don’t make a lot of sense in most cases. See milestone 2 vs milestone 3 for example.

Hey! Thanks for replying!
When could you estimate the cost of this application?
I'm considering adding/removing some planning features.
There are still a lot of things can do, for a toolbox.
Maybe I could put them into something like Subalfred-2.0.

**Review by takahser — CHANGES_REQUESTED** [review]
@AurevoirXavier 

> When could you estimate the cost of this application?

We don't usually do that. It's up to the grantee, which price he asks for. However, W3F grant committee members take the price into consideration when reviewing a grant application. Also, it should be transparent to any reviewer, how you come up with the price.

> I'm considering adding more planning features.
> There are still a lot of things can do, for a toolbox.
> Maybe I could put them into something like Subalfred-2.0.

You're free to submit a follow-up grant application after successfully completing your first one. This is usually the better solution, especially for first-time grantees. I hope this helps, otherwise, feel free to reach out again.

**Comment by AurevoirXavier** [comment]
Thanks for the explanation! @takahser 

I saw you requested a change here. What information should I provide?

**Review by Noc2 — CHANGES_REQUESTED** [review]
Sorry for the late reply here. Could you change the duration costs for each milestone, so that it roughly reflects your weekly rate? For example, milestone 3 shows currently a weekly rate of 1500. If I take this as your weekly rate, it means you worked/will work on milestone 1 for roughly 4 months, etc. And feel free to maybe reduce the price a little bit, when you do this ;-)

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the quick reply. You don’t necessarily need to update the total costs, but the duration and costs for each milestone should at least roughly make sense and reflect your weekly/daily rate and the amount of effort you put into this (regarding milestone 1 this could also contain work done in the past, so feel free to update the duration accordingly). FTE is only something that you should change if more developers have worked on it.

**Comment by AurevoirXavier** [comment]
> Thanks for the quick reply. You don’t necessarily need to update the total costs, but the duration and costs for each milestone should at least roughly make sense and reflect your weekly/daily rate and the amount of effort you put into this (regarding milestone 1 this could also contain work done in the past, so feel free to update the duration accordingly). FTE is only something that you should change if more developers have worked on it.

Thanks! Does it make sense now?

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I’m happy to go ahead with it. I think the weekly rate is a little bit high, but you also already put a lot of effort into this project.

**Review by laboon — APPROVED** [review]

**Review by gautamdhameja — APPROVED** [review]

**Pull request merged**
