### PR TITLE
Upgrade Gafi application from level 2 to level 3

### PR DESCRIPTION
**Pull request by mutobui**
### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] Hackathon
- [ ] Personal Recommendation
- [x] Substrate Builders Program
- [ ] Investor/VC
- [ ] Online Search 
- [ ] Other: _______

### CODE REVIEW

**Comment by mutobui** [comment]
Hi, after months of building, Substrate gives us more clarity on the possible features that we did not add to the Gafi grant application in the first place. We would like to add pallet sponsored pool, pallet cache, and pallet game creator to the delivery of milestones 2 and 3 (milestone 1 we have passed).

**Review by semuelle — CHANGES_REQUESTED** [review]
Thanks for the submission, @mutobui. 

1. Why is Game Creator its own pallet? From your description, it is a mechanism to divert funds to a game's creator, which sounds like something that could be easily implemented in your existing functions.
2. What is the purpose of caching data in a pallet? I couldn't find an explanation for this pallet and functionality anywhere.

To be honest, I am a bit hesitant to grant another 20,000 USD for pallets that will be tightly coupled with your other, already very specific pallets. I would be more comfortable funding this as a follow-up grant after seeing your current plan in action. In any case, I will share your amendment with the rest of the team.

**Comment by semuelle** [comment]
> player spam join<->leave pools

Can you expand on this? People spam transactions? Why would they do that? Sounds like a problem with the economics.

**Comment by mutobui** [comment]
Every 30 minutes, players in the pool get a specific number of tickets to use for a discount on the transaction fee. When they run out of tickets they would rejoin to refresh the tickets, but the pallet cache will prevent that by giving the remaining tickets to that player when they rejoin.

**Review by Noc2 — APPROVED** [review]
I’m happy to support this, but it might be hard to get the five approvals.

**Review by gautamdhameja — APPROVED** [review]
I find this interesting solution and I would be looking forward to seeing it built. All the best.

**Comment by mutobui** [comment]
Thank you for being so supportive, after receiving the grant from milestone 1 we have the momentum. Until now, Gafi is just at the beginning of the long development process, therefore we believe Substrate will give us more ideas and solutions to achieving Level 3.

**Review by laboon — APPROVED** [review]

**Review by hakan-w3f — APPROVED** [review]
Looking forward to seeing this challenging Substrate based project.

**Review by takahser — APPROVED** [review]
I feel like the price is rather high for what you're planning to additionally deliver. However, given the high quality of your M1 delivery, I'm willing to support this amendment. Looking forward to your future deliveries! 👍

**Pull request merged**
