### PR TITLE
Create signet.md

### PR DESCRIPTION
**Pull request by replghost**
#### Project Abstract

Signet is blockchain-native financial workflow management software for enterprises. The goal of Signet is to enable enterprises or institutional users to perform blockchain operations such as treasury management, payments, staking and governance in a way that is friendly to non-technical users. The software is built natively on top of Substrate, including the multisig, proxy, governance and staking pallets, but adds an open-source self-hostable software layer on top that enables configurable workflows for the purpose of internal risk mitigation.

This grant proposes two milestones:

1. Take the "Sign in with Substrate" functionality that has been developed in Signet and package it as a documented, reusable component focused on developer experience similar to the "Sign in with Ethereum" standard. We believe this should be a common good and will have a halo effect on Substrate adoption by providing a new avenue for both existing web2 and current web3 developers to build for the ecosystem. After the grant, we will solicit interest for moving forward with a standard.
2. Build staking-related modules into the Signet multisig dashboard, including selection/rotation of validators for a nomination pool or staking position, including the advanced use case of doing so when the staking proxy is a pure proxy controlled by a multisig. This is a challenging and potentially error-prone process for users who need to perform the action using Polkadot.js.

This application is not a follow-up to a previous grant.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) or BTC address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [x] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@replghost:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by replghost** [comment]
I have read and hereby sign the Contributor License Agreement.

**Comment by replghost** [comment]
recheck

**Comment by replghost** [comment]
recheck

**Comment by replghost** [comment]
Hello, checking in here. Can someone help with the "discussion_private" check that is failing, as well as set up a chat? Would love to hear any feedback.

**Review by Noc2 — CHANGES_REQUESTED** [review]
(ask some questions in the private channel)

**Review by Noc2 — CHANGES_REQUESTED** [review]
(additional comment in the private channel)

**Review by Noc2 — DISMISSED** [review]
Thanks for the update. I'm happy to go ahead with it.

**Review by laboon — APPROVED** [review]

**Review by takahser — APPROVED** [review]

**Review by Noc2 — APPROVED** [review]

**Review by laboon — APPROVED** [review]

**Pull request merged**
