### PR TITLE
Create Dot's Journey

### PR DESCRIPTION
**Pull request by giankbo**
#### Project Abstract

Dot's Journey is a qualitative data tracker and user-friendly onboarding tool designed for non-crypto users within the Polkadot & Kusama ecosystems. Aimed primarily at Spanish speakers, but also accessible to English users, it simplifies understanding by providing intuitive categorization/subcategorization, vision cards, and step-by-step guides to help users quickly engage with the ecosystem. For projects, Dot's Journey acts as a visibility and onboarding platform, offering frictionless listings and streamlined processes in both languages. In its next phase, it will also serve as a source of qualitative data accessible via API.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (Polkadot AssetHub (USDC & DOT) address in the application and bank details via email, if applicable).
- [x] I understand that an agreed upon percentage of each milestone will be paid in vested DOT, to the Polkadot address listed in the application.
- [x] I am aware that, in order to receive a grant, I (and the entity I represent) have to successfully complete a KYC/KYB check.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by giankbo** [comment]
I have read and hereby sign the Contributor License Agreement.

**Review by semuelle — COMMENTED** [review]
Thank you for the application, @giankbo. I will share it with the rest of the committee. However, based on similar projects we have seen and funded in the past, I don't think a separate platform is the solution to attract Spanish users or a less technical audience, so I'll abstain.

**Comment by giankbo** [comment]
Thank you, @semuelle. I fully understand that other projects may have tackled similar challenges, but we believe Dot’s Journey has some unique features that could make a real difference.

We see it as an effective solution in both Spanish and English to bring Polkadot and Kusama to underrepresented communities, which currently lack web apps in their native languages. This improves understanding and onboarding with relay chains, parachains, and dapps.

Instead of being just another informational platform, Dot’s Journey aims to be a direct action tool: it combines a categorized project visibility environment with no use of routes (something we haven’t found in our research within the Polkadot ecosystem - if you’re aware of any, please let us know), a dynamic step-by-step interaction guide in a single interface (which we also haven’t seen), and the ability to actively track projects.

Furthermore, we aim to reduce the significant friction that Spanish-speaking users face, while also recognizing areas for improvement in the English-speaking space. Looking ahead, we see potential in expanding Dot’s Journey by developing a qualitative data API for projects (which we haven’t found in Polkadot either), supporting additional languages, among other enhancements.

Our concept tests for the Vision section have yielded very positive results. We’d love the opportunity to demonstrate how this web dapp truly offers something different.

**Comment by giankbo** [comment]
Hi all,

I hope you’re doing well! I appreciate that the committee is reviewing our proposal, and I understand that this process takes time. However, any updates or feedback you could provide would be greatly appreciated.

Thank you for your efforts! If you need anything else, just let me know.

**Comment by PieWol** [comment]
Hey @giankbo , I struggle to understand what the overall benefit of this project will be. I mean it all sounds and looks good, don't get me wrong. Yet how will this improve the onboarding of people into the Polkadot ecosystem? If a person is  interested in anything about Polkadot he would already find all necessary information by searching the web. At the same time you will have to do a lot of maintenance work to keep up with any changes within the ecosystem only do duplicate existing content. At the same time I think you are asking for a reasonable amount of money for the estimated 3 FTEs for 4 Months. I'll side with @semuelle and also abstain from voting. I hope that other committee members will shortly follow up with their feedback. Thanks for all the effort you put into this application. Best wishes.

**Comment by giankbo** [comment]
Hi @PieWol, thanks for the feedback. Working collaboratively with projects reduces the maintenance workload, which can be achieved through the Vision section once the initial ecosystem data and listings (as outlined in the proposal) are fully loaded. For onboarding, it’s about setting up clear step-by-step processes, and handling data in the Cloud would minimize issues. The main maintenance issues arise with static data, which isn’t our case. The only potential bottleneck might be translating support guides.

I believe this project offers unique value as a discovery and direct-action tool. Rather than simply replicating existing information, it organizes and contextualizes resources in a streamlined, accessible hub that helps users easily access and act on key resources within the ecosystem.

Our proposal outlines a web app with minimal risk to production, with potential to attract users to the ecosystem (not only for DOT but for the entire ecosystem) and that it’s maintainable.

Additionally, I have a different perspective. I don’t think it’s that simple to find what one wants to do within Polkadot. (Here I’m not including buying DOT or storing it in a CEX or a wallet, which is easy). Rather, I’m referring to identifying the ecosystem, understanding it, knowing which dapps belong to which parachains, and learning the processes needed to engage. In my opinion (and I could be wrong), this isn’t straightforward in English and is very challenging in Spanish.

Thanks again for the feedback!

**Comment by keeganquigley** [comment]
Thanks @giankbo for taking the time to answer all questions and for your efforts in submitting the application. I do agree with you that it can be hard to navigate the Polkadot ecosystem in terms of finding resources. I also agree that there is probably a great need for Spanish documentation. But the issue I have here is that the deliverables are mainly for a dashboard/website that doesn't have much to do with Polkadot tech. A project like this would be much better supported by [treasury funding](https://wiki.polkadot.network/docs/learn-polkadot-opengov-treasury), if the community has a demand for it. Feel free to submit a OpenGov proposal.

Also, I think a better alternative might be translating existing docs to Spanish, rather than create a Spanish-language portal and then attempt to maintain it and keep everything up to date, as my colleague @PieWol mentioned above. I also agree that adding features like price feeds are nice, but not really necessary when aggregator sites like CoinGecko already support multiple languages. Additionally, we typically don't fund design components such as the vision cards.

Since that makes three of us abstaining, I will go ahead and close the application. I wish you the best of luck with funding, and let us know if you have any questions.

**Pull request closed without merging**
