### PR TITLE
Re-submission of Application for Candymint tool

### PR DESCRIPTION
**Pull request by AshutoshSingh00001**
#### Project Abstract

> Candy Mint is a tool built for Asset Hub for building scalable nft mint dapps built with the use polkadot-js/api and react-js similar to ethereum based mint dapps but by using Candy Mint builders won't have to write smart contract

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) or BTC address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by AshutoshSingh00001** [comment]
@Noc2 @takahser Re-submission of https://github.com/w3f/Grants-Program/pull/2050 updated with all new commits previous pull request had some issue with fetching newly made commits

**Review by takahser — CHANGES_REQUESTED** [review]
@AshutoshSingh00001 thanks for you interest in our program. I see a couple of problems with this proposal:

- The UX of the [current UI](https://polkadot-punks.vercel.app/) is not very good.
- We usually don't do retrospective funding.
- The proposal is currently poorly written - for example, I see still a lot of template text, rather than the actual contents that'd apply to your project.

Hence, I'm not going to approve it. Other members might have a different take on this.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the updated application and all the effort you put into this. However, the grants committee decided not to go ahead with the application due to the reasons listed above. Let me know if you have any questions.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the updated application and all the effort you put into this. However, the grants committee decided not to go ahead with the application due to the reasons listed above. Let me know if you have any questions.

**Comment by AshutoshSingh72** [comment]
Thanks

**Pull request closed without merging**
