### PR TITLE
Create ParaSpell_follow-up.md

### PR DESCRIPTION
**Pull request by dudo50**
#### Project Abstract

ParaSpell is XCM & XCMP related tool built to save developers time when interacting with the network. It is no longer necessary to search for correct XCM pallets, fill lengthy XCM messages with all the required details or go through research on launching network. Developers can use ParaSpell to download/install/start necessary nodes with a single command, execute XCM transactions from a user-friendly UI, or open & close HRMP channels between nodes in the launched network from a user-friendly UI. ParaSpell now also offers SDK, which features compatibility with multiple Parachains & allow for easy integration into new dApps. They can then right out of the box create XCM related calls in moments.

[Previous Approved application](https://github.com/w3f/Grants-Program/pull/1118)
[Previous Approved delivery](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/ParaSpell-milestone_1.md)

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. I have a couple of questions/comments: 

- Could you link to the implementation of the xTokens pallet as part of the specification?
- In general, could you add more technical details to the specification of the deliveries? For example what exactly do you mean by “template for Web3 projects”? (ink!, solidity or the pallet, etc.). And feel free to add the programming language to the specification of the deliveries. 
- Deliverables 0a-0d of the [template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#milestone-1-example--basic-functionality) are mandatory for all milestones and deliverable 0e at least for the last one. Could you integrate these?

**Comment by dudo50** [comment]
Hey @Noc2, I will try to deliver the changes you requested as soon as possible. 
With kind regards,
Dudo

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. But as @keeganquigley said, could you remove the Bounty funding from the milestones? This is something we don't fund, also because it is hard to evaluate.

**Comment by dudo50** [comment]
Hey @Noc2 , @keeganquigley  I have removed bounty funding as requested. Hope everything is now in order.
If any other suggestions or questions arise, feel free to let me know. I will answer them asap.
With kind regards,
Dudo

**Comment by keeganquigley** [comment]
Hey @dudo50 apologies for the late response, we were at a company retreat this past week. I also needed to study up on the xTokens pallet. I appreciate the detailed specifics and the comparisons to the Moonbeam SDK.

Personally, I was impressed with the amount of effort on your last grant and would be happy to move forward with supporting this one. I agree with your opinion that there aren’t many XCMP/HRMP tools yet, and a unified SDK for XCM transfers would be very helpful for the entire ecosystem. Glad to see [in this forum post](https://forum.polkadot.network/t/grant-ideas-and-wishlists/399/4) that parachain devs like your ideas and agree that there is a huge need for this. I think the price is reasonable as well. 

Lastly, I will point you to [these comments](https://github.com/w3f/Grants-Program/pull/1022#issuecomment-1176108445) by my colleague regarding standards as food for thought, although it sounds like you have already thought a lot about how to implement the SDK in a way that will allow others to easily adopt it.

I will mark your application as ready for review and wait to see if the rest of the committee has any other questions/concerns.

**Review by keeganquigley — APPROVED** [review]

**Comment by dudo50** [comment]
@keeganquigley thank you for your kind words. It is amazing to see just how much you dive into this with us and even more amazing that you see our vision the way we do and that can be crucial on our way to deliver something truly valuable. 

In regards to standards, that is very useful and we will have a look into it and will for sure take notes.

Many thanks again.

With kind regards,
Dudo

**Review by alxs — APPROVED** [review]
@dudo50 happy to support this too. Thank you for the effort you put into writing the application and defining clear deliverables, and to @keeganquigley for diving deeper and providing more context.

**Review by Noc2 — APPROVED** [review]

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/enhancing-cross-chain-experience-of-your-dapps-with-revolutionary-xcm-tool-set-from-paraspell/8792/1

**Pull request merged**
