### PR TITLE
Escrow pallet

### PR DESCRIPTION
**Pull request by herou**
### Project Abstract

We aim to build an Escrow pallet that will help communities to release funds easier to devs/teams
and the web3 community would have a simple escrow system implemented in web3.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying?

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] I have read and understood the [FAQs](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md), [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md) and [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).
- [x] I prefer the discussion of this application to be in a private Element/Matrix channel. My username is: ``@_______``

### How Did You Hear About our grants program?

- [x] Social Media
- [ ] Hackathon
- [x] Personal Recommendation
- [ ] Substrate Builders Program
- [ ] Investor/VC
- [x] Online Search
- [ ] Other: _______

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. But you are currently adding two files to the repo. Could you remove one of them? Also, if you prefer a private discussion, could you share your element username?

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. Are you aware of https://github.com/interlay/interbtc/blob/7942cfcd8a41013639285fe099285530438df3db/crates/escrow/src/lib.rs? Will all functions be implemented as part of a single pallet? Could you also add weights/benchmarking to the deliverables of the milestone?

**Comment by herou** [comment]
> Thanks for the update. Are you aware of https://github.com/interlay/interbtc/blob/7942cfcd8a41013639285fe099285530438df3db/crates/escrow/src/lib.rs? Will all functions be implemented as part of a single pallet? Could you also add weights/benchmarking to the deliverables of the milestone?

I have seen the link but my idea is something different. All the functions would be implemented as part of a single pallet. I added benchmarking to the deliverables of milestones.

**Review by Noc2 — DISMISSED** [review]
Thanks for the update. I’m happy to support it and share it with the rest of the team.

**Review by takahser — CHANGES_REQUESTED** [review]
@herou you still have some leftover example texts from the template, e.g. "Milestone 1 Example". Could you fully replace these with your own texts (e.g. "Milestone 1 — Implement sign functionality")?

**Comment by herou** [comment]
> Example
Done

**Comment by herou** [comment]
> @herou you still have some leftover example texts from the template, e.g. "Milestone 1 Example". Could you fully replace these with your own texts (e.g. "Milestone 1 — Implement sign functionality")?

Done

**Review by Noc2 — APPROVED** [review]

**Review by takahser — APPROVED** [review]

**Pull request merged**
