### PR TITLE
Tali AI Grant Request 

### PR DESCRIPTION
**Pull request by OlypsisAli**
#### Project Abstract

We propose to build a specialized Discord bot (and or widget that lives on docs page) for Polkadot that will use the latest technology around LLM’s (Large Language Models) to import Polkadot's Github repos, documentation, video content and Discord Q&A’s to provide an interface for Polkadot users/developers to ask questions in natural language.
The idea is to provide another member to Polkadot's DevRel team, reducing support hours on Discord and a path of triage for commonly asked questions (making the team and users get answers quicker).

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x] **Level 1**:  Up to $10,000, 2 approvals

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Could you integrate the default deliverables into the milestones? (see https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#milestone-1-example--basic-functionality). Also, ideally, the requirements (= milestone deliveries) should be polkadot specific? Furthermore, please sign our terms and conditions (see the message above).

**Review by semuelle — CHANGES_REQUESTED** [review]
Thanks for the application, @OlypsisAli. To add to what David said, the grants program requires deliverables to be open source. We are also looking for deliverables that are reproducible and verifiable, so it'd be great if you could restructure your deliverables to incorporate this.

**Comment by Noc2** [comment]
I wanted to let you know that I'm closing this because of inactivity. Let me know if you still want to work on it.

**Comment by OlypsisAli** [comment]
Sorry for the inactivity! I did not see the notifications!! I can get on this ASAP. Thanks for the consideration.

**Comment by Noc2** [comment]
@OlypsisAli should I reopen the PR?

**Comment by OlypsisAli** [comment]
> 

Yes please!

**Comment by Noc2** [comment]
Done

**Comment by OlypsisAli** [comment]
@semuelle @Noc2 I have updated the grant request. Please let me know if you have any further feedback.

**Review by keeganquigley — CHANGES_REQUESTED** [review]
Hi @OlypsisAli thanks for the application. A couple of questions:

- The mandatory deliverables (0a. - 0d.) are required for each milestone. Can you include these into milestone 1?
- Is there a reason it says "Milestone 1 Example" and "Milestone 2 Example"? Can you remove the "example" part if this is what you plan to implement?
- Have you done any temperature checks in the Polkadot Discord to see if this feature is needed/wanted? The ambassadors and Discord Mods are more in tune with what the community wants regarding Discord, and it would be nice to see proof that they like this concept. Otherwise, there is the possibility that it goes unused.
- Have you talked to the Parity DevRel team or have they expressed interest in collecting metrics from a bot like this?

**Review by semuelle — CHANGES_REQUESTED** [review]
To add to what Keegan said, I'd be interested to see some hard numbers on what these bots actually accomplish. I think they are useful as a sort of switchboard operator to guide people in the direction of information, but I don't know if there are enough recurring questions that require a setup as complex as an LLM. Given the speed with which information changes in this ecosystem, it would require a lot of maintenance compared to an FAQ.

**Comment by semuelle** [comment]
I am closing this application due to inactivity. Please let me know if you want to continue working on it, so I can reopen it, @OlypsisAli.

**Pull request closed without merging**
