### PR TITLE
Create apps-wallet-mobile.md

### PR DESCRIPTION
**Pull request by slonigiraf**
#### Project Abstract

Our project focuses on the development of mobile compatibility for the [Polkadot apps wallet](https://polkadot.js.org/apps/#/explorer), an official interface to the Polkadot ecosystem that is currently unoptimized for mobile use. With the understanding that mobile traffic makes up a significant percentage of all web traffic, we see a need for a version of the wallet that can be easily accessed and navigated on mobile phones. This modification will enable us to tap into the potential new users who have been deterred by the wallet's current limitations.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by dsm-w3f** [comment]
@slonigiraf thank you for the grant application. Do you already reach @jacogr or other people from Polkadot.js to check if this demand is not already under development or if there is interest to have this demand developed? It seems to be a good thing to have a responsive interface for Polkadot.js but could be difficult to convince Polkadot.js admins to merge the result of this grant proposal. Would be high-risk to fund or start to work on this proposal without a confirmation that there is interest to merge this contribution into Polkadot.js codebase. Please let me know if you already had this conversation or if not let's start to discuss this with Polkadot.js first.

**Comment by slonigiraf** [comment]
Thank you very much for you prompt responce.
We've contacted @jacogr through https://github.com/polkadot-js/apps/issues/9759
However if you could ask him to review this proposal would also help, because we don't have any contact data of @jacogr

**Comment by dsm-w3f** [comment]
@slonigiraf thank you for starting the conversation with Polkadot.js. As you just open the issue today let's give a time for them to answer.

**Comment by semuelle** [comment]
In any case, @slonigiraf, but especially if we don't hear from Jaco on time, we should split this grant into several small milestones. Getting things merged into the apps repo has proven difficult in the past and we would very much like to avoid you having to maintain a separate fork.

**Comment by slonigiraf** [comment]
> In any case, @slonigiraf, but especially if we don't hear from Jaco on time, we should split this grant into several small milestones. Getting things merged into the apps repo has proven difficult in the past and we would very much like to avoid you having to maintain a separate fork.

Rebuilding the UI will require changes to the CSS, which will affect the appearance of the entire site on mobile phones. If we split our milestones into smaller ones and merge changes to the app's repo, pages redone under each milestone will look great. However, other pages might look worse than before the merge. We don't believe the community would accept partial work in this case. We propose delivering the UI changes as a separate fork and adding an additional milestone for the merge. Would this be acceptable to Web3?

**Comment by semuelle** [comment]
> We don't believe the community would accept partial work in this case.

I understand. The problem is that we have previously funded apps forks, and they didn't prove to be very useful. We can set the grant up to include a milestone for merging, but the main goal should be to get something merged.

**Comment by keeganquigley** [comment]
Thanks for the application @slonigiraf and for your time and effort.

In my opinion, the Polkadot-JS Apps console isn't designed to be used with mobile devices for a reason. That's because it is just that - a console for devs and powerusers, not meant to be seen by the end user. I don't know how much it would end up being used since the main user base of Polkadot-JS Apps most likely will continue to use the browser version.

Therefore, I'm unsure why the development of your parachain would rely on Polkadot-JS being optimized for mobile. Ideally, you would be building front-end UIs for your users so that they can log in directly using a popular Polkadot wallet extension. Essentially, they should be able to use your parachain without seeing Polkadot-JS apps at all. I also have a hard time seeing this be merged into the Polkadot-JS apps repo. Therefore I will personally pass on the application for now.

**Comment by slonigiraf** [comment]
@keeganquigley, thank you very much for your feedback. Let's imagine a company, XYZ, that envisions a stellar dApp and wants to settle on a specific blockchain platform. This company has two founders and limited funds to produce a minimum viable product (MVP) for initial user testing. A typical approach for startups is to develop a web app that can run on both computers and smartphones, primarily because it's cost-effective. Currently, Company XYZ might hesitate to choose Polkadot. This is because developing for Polkadot would necessitate creating a web app, an iPhone app, and an Android app. Company XYZ simply lacks the funds for such an undertaking. Even if they did have the resources, it would go against the fundamental startup principle of rapid development and user interaction. Managing three separate apps isn't conducive to agility.
If startups avoid Polkadot, the platform could potentially fade into obscurity. We hope this doesn't happen as we recognize the immense potential in Polkadot's blockchain design.
That's why Polkadot needs an app that startups can fork and use as an MVP template on both computers and smartphones.

**Review by dsm-w3f — COMMENTED** [review]
@slonigiraf thank you for the comments. I'll mark the application as ready to review, but I personally won't approve it. I think very risky to try to develop for Polkadot.js without any consent from Jaco. We have other initiatives, such as [Capi](https://github.com/paritytech/capi), that aim to solve this kind of situation. I think your efforts would be better applied to other projects.

**Comment by slonigiraf** [comment]
@Noc2, it's strange that the UI is primarily designed to assist developers, yet it's advertised as "the main Polkadot user interface" here:
https://www.polkadot.network/ecosystem/community/
I've personally heard from my friends about how unappealing "the main Polkadot user interface" is.

**Review by takahser — CHANGES_REQUESTED** [review]
@slonigiraf thanks for your suggestions. I mostly agree with the points made by other members of the grants committee, namely:

- unless coordinated with the core polkadot.js devs I don't think a web-based mobile version of polkadot.js apps is useful
- native wallets are the preferred approach here

I also want to highlight the parallels with metamask here: their browser extension doesn't have mobile support, but instead there is a corresponding native wallet. Exploring a similar effort would IMHO more viable than a browser-native mobile version, but also here it should be coordinated with the core polkadot.js devs I believe. Also, existing mobile wallets should be taken into consideration. Please note that polkadot.js is arguably very different from metamask though, so I'm not 100% sure if these parallels can or should even be drawn here.

Regarding this point:

>it's advertised as "the main Polkadot user interface" here:
>https://www.polkadot.network/ecosystem/community/

For context, I think here they target people who are interested in running nodes which are arguably rather technical people. That being said, I tend to agree with the problem you're describing about the UI being not the most user-friendly.

**Comment by semuelle** [comment]
Hi @slonigiraf. Thanks again for your application, but the committee has decided not to support the project at this point due to the concerns mentioned above. Thank you for your continued interest in the Polkadot ecosystem, though. Feel free to apply again in the future!

**Pull request closed without merging**
