### PR TITLE
Solidity Trie Verifier Implementation

### PR DESCRIPTION
**Pull request by Doordashcon**
#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (aUSD/USDT) address for the payment of the milestones is provided in the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the new grant application. See my comment on the other open application by your team: https://github.com/w3f/Grants-Program/pull/1481#pullrequestreview-1274623912 Apart from this, could you specify as part of the application, what your goal is and why for example, darwinia and snowfork don’t have this or what the benefit of your solution is? Also, I personally find the application very expensive, but this is just my personal opinion.

**Comment by Doordashcon** [comment]
Hello @Noc2 Both Snowfork and Darwina don't verify state proofs, One can only assume the technical cost of implementing the trie verifier is too much for them.

An update to the proposal has been made highlighting sub implementations required for the verifier.

**Comment by Noc2** [comment]
Thanks! Let me know once I should take another look at the proposal.

**Comment by Doordashcon** [comment]
Hello @Noc2 the proposal is ready for review.

**Comment by Doordashcon** [comment]
Hello @ Noc2 just had a recent look at Composable's implementation, no support for enums encoding/decoding.

our hope in building a general Scale Codec covering all rust primitive types is to support trie verification for all kinds of values that could potentially be included in the Parachain state.

Also the scope of work presented is for a team of three,  the current time frame is an optimistic estimate and can potentially take longer. 

Some added work like tests( i.e fuzz test for both the trie and codec) that are needed also factor into the scope of work.

**Review by Noc2 — CHANGES_REQUESTED** [review]
In this case, I recommend updating the FTE and the duration inside the application.  Also, just to mention it, if you reduce the price to 30k, it's only a level 2 grant and will be easier to approve. ;-)

**Review by randombishop — APPROVED** [review]
Thanks for reducing the price @Doordashcon 
I am OK to go forward now.

**Review by Noc2 — APPROVED** [review]
Thanks for the update

**Review by dsm-w3f — APPROVED** [review]

**Pull request merged**
