### PR TITLE
Vue.js + TypeScript Substrate Front-End Template Project Proposal

### PR DESCRIPTION
**Pull request by DanHenton**
#### Project Abstract

When building our app, we have used a very useful existing community template - the [Substrate Front End Template](https://github.com/substrate-developer-hub/substrate-front-end-template) from the Substrate Developer Hub. This template is built using React.js and JavaScript. We are proposing to create an alternative version of this template, which would achieve two major outcomes:

- Have an extendable template app, where developers can quickly connect and interface with the Substrate blockchain
- It would be written using TypeScript as opposed to JavaScript.
- It would use Vue.js instead of React.js.

We believe that the combination of TypeScript's strong, static typing, and Vue's simplicity will together serve the purpose of providing an alternative source of very clear examples of how to interface with a Substrate Node from a modern front-end application, which should be of great value to the community.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [x] I prefer the discussion of this application to take place in a private Element/Matrix channel. Our usernames are: `@dan:wunderbar.ems.host`, `@milos:wunderbar.ems.host`, `@mila:wunderbar.ems.host`

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Just a reminder that each contributor needs to sign our terms and conditions before I share it with the rest of the team. Apart from this, my main personal concern regarding the application at the moment is that it’s relatively expensive. 20k per month per dev is a lot, and not sure if you actually need three months for the project, given that you can leverage the existing template for your work.

**Comment by DanHenton** [comment]
Hey, thanks for the reply. All members have signed the cla now. Could we discuss your feedback in a private channel on the element or setup a call? 🙂

**Review by Noc2 — CHANGES_REQUESTED** [review]
Sorry for the late reply and that I previously overlooked the private conversation part of the PR. I created a room and invited you to it. However, I wasn't able to invite @mila:wunderbar.ems.host to the room.

**Comment by DanHenton** [comment]
After some decisions, we have decided that we can reduce the total cost of this work by extending the timeline.

**Comment by DanHenton** [comment]
After some decisions, we have decided that we can reduce the total cost of this work by extending the timeline.

**Comment by semuelle** [comment]
For transparency: I have updated your PR body to reflect the fact that this is now a Level 2 grant.

**Review by keeganquigley — APPROVED** [review]
Thanks for the changes @DanHenton I'm happy to go forward with it.

**Review by semuelle — APPROVED** [review]
Same

**Comment by keeganquigley** [comment]
Hi @DanHenton please see my comments in the private chat.

**Comment by keeganquigley** [comment]
Closing grant for now, for reference see private Element chat.

**Pull request merged**
