### PR TITLE
MangoBOX-Protocol

### PR DESCRIPTION
**Pull request by Mangoboxlabs**
### Project Abstract

MangoBOX is a fork and upgrade of fund-raising protocol Juicebox on Ethereum. It rewrites the logic and functions of Juicebox in the smart contract language of Ink! and allows the ecological projects in Polkadot to raise funds from their community and introduce the Juicebox treasury management model into the Polkadot ecosystem. Anyone can utilize the MangoBOX platform to freely create a project fundraising page, customize the funding structure, customize how the project allocates funds and reward community members with tokens.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying?

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] I have read and understood the [FAQs](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md), [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md) and [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).
- [ ] I prefer the discussion of this application to be in a private Element/Matrix channel. My username is: ``@_______``

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] Hackathon
- [x] Personal Recommendation
- [ ] Substrate Builders Program
- [ ] Investor/VC
- [ ] Online Search
- [ ] Other: _______

### CODE REVIEW

**Comment by laboon** [comment]
I would be happy to support this if the milestones were more specific. The functionality is specified earlier; I would just like to see the milestones re-worded so that they focused on the specific *functionality* available at that milestone, as opposed to the modules that will be completed at each milestone. This will make testing and approving the milestones much easier.

Other than that minor point, looks good and I think it would be a great addition to the ecosystem.

**Comment by Mangoboxlabs** [comment]
> I would be happy to support this if the milestones were more specific. The functionality is specified earlier; I would just like to see the milestones re-worded so that they focused on the specific _functionality_ available at that milestone, as opposed to the modules that will be completed at each milestone. This will make testing and approving the milestones much easier.
> 
> Other than that minor point, looks good and I think it would be a great addition to the ecosystem.

Thank you for your advice, and your encouragement has given us more courage to do this career.
As you said, we're going to re-word our two milestones to make them more specific.
Please wait for our further updates.

**Comment by Mangoboxlabs** [comment]
Hi, @laboon, based on your suggestion and after discussions within our team, we have re-optimized our two milestones.
In the first milestone, we mainly realize how to create a fundraising project and initialize the project.

The second milestone we mainly complete when a project is launched, how to manage the funds raised by the project and manage its governance tokens.

This way, it makes our goals for both milestones clearer.

If you have any other suggestions, please feel free to leave us a message.

**Comment by Mangoboxlabs** [comment]
Hi, @Noc2 ,  thank you very much for your reminder, it is very helpful to us. Since Ink! smart contract is a very new technology, there are not many project cases in the ecosystem at present. Our technical team has now started working on each of the Ink! projects and learning their code. We want to maximize the best possible development of Ink!. We also hope that with the efforts of more and more teams, Ink! will grow and mature faster.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the quick reply. Are you planning to update the PR? If you want to work on an ink! ERC-721 implementation, you need to specify why this is necessary compared to the existing implementation.

**Comment by Mangoboxlabs** [comment]
Hello @Noc2 , thank you very much for your suggestions and reminders, now that we have updated the PR, and here I explain in more detail the ERC-721 implementation in our first milestone.

First of all, the NFT we developed here is not a standard ERC721 token, it represents a management authority.

What we are doing is a DAO fundraising system, anyone can build a DAO organization to raise funds. When this fundraising system is established, it is necessary to have administrative rights to configure parameters for this organization. At this time, we did not directly set the management rights from the code, but abstracted the management rights into an NFT. Whoever owns the NFT can control the DAO organization and adjust the corresponding fundraising parameters.

Such a logical design can make the management authority of the DAO organization very easy to transfer, which is very convenient for the project party to manage the project.

This NFT function is just a small function in the first milestone. Our first milestone is mainly to complete the creation of the fundraising system, initialize its various functions, and finally realize that anyone who does not understand the code can quickly create a DAO fundraising system.


Thanks again for the reminder, and if you have any other new questions, please feel free to leave us a message.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. I have two additional questions: 

- Regarding the frontend, what do you mean by providing “frontend files”? Do you actually develop a frontend? And if so, will this be based on the substrate frontend template or could you provide some mock-ups/design in case you create a new frontend.
- Could you maybe add links to the Juicebox solidity code that you are going to reuse as part of the specifications?

**Comment by Mangoboxlabs** [comment]
Hi, @Noc2 , thank you very much for your patient answer, I will further clarify your two questions.

In our second milestone, when all Ink smart contracts have been developed, we are ready to develop a front-end file to realize the interaction between the contract file and the front-end file. Eventually we will develop a new set of UI pages and finally implement our DAO fundraising system.

Do we need to provide mock-ups if we develop front-end files? If necessary we will design a mock-ups and update it in the application file.

This is the solidity code link for Juicebox, we have updated this link to the PR.
https://github.com/Mangoboxlabs/juice-contracts-v2

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the quick reply and update. Just to double check: front-end files = front-end, which can be compiled and run locally, correct? It would be nice to have some very rough mock-ups or something similar as part of the application. Just to get an idea of what you plan to deliver.

**Comment by Mangoboxlabs** [comment]
> Thanks for the quick reply and update. Just to double check: front-end files = front-end, which can be compiled and run locally, correct? It would be nice to have some very rough mock-ups or something similar as part of the application. Just to get an idea of what you plan to deliver.

Thanks for your quick reply, it gave us more clarity on what to do next. Yes, as you said: front-end files = front-end, which can be compiled and run locally, it is right.

We will design a few more product mock-ups and update them in the application file, please wait for us for a few more days.

Thanks again for your hard work!

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the quick response and take your time. I will put the application on hold for now. 
Feel free to ping me once you are done.

**Comment by laboon** [comment]
Looking forward to seeing the updates!

**Comment by Mangoboxlabs** [comment]
Hi, @Noc2 @laboon , thank you very much for your continued help. Now we have updated six product UI mock-ups  in the application documents, and we will develop products with such mock-ups  in the future. However, it should be emphasized that this is not our final version, we will optimize and modify it in the actual development process. Now please review again.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. I have one last question: Would you be willing to reduce the price of your second milestone also to 20k (same estimated work 1 month, FTE 4)?

**Comment by Mangoboxlabs** [comment]
> 
Thanks for your quick reply. As you said, we have reduced the price for the 2nd milestone to 20k. We will go all-in on development work, so please look forward to our work.

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I’m happy to go ahead with it and I will share it with the rest of the team.

**Review by gautamdhameja — APPROVED** [review]

**Review by SBalaguer — APPROVED** [review]

**Pull request merged**
