### PR TITLE
Create storage-aggregator.md

### PR DESCRIPTION
**Pull request by lk2684753**
### Project Abstract

Storage Aggregator provides a unified storage API, making it easier to retrieve and store billions of blockchain data! Provide dozens of custom storage platforms and intelligent retrieval file services!

Built on Substrate, and provides a native cross-chain communication tray based on SCMP (Cross-Chain Message Passing), through a unified data exchange API that is 100% compatible with Amazon S3 API in SA storage cloud storage and storage Retrieve user data.

This allows any project to use any AWS library or SDK and start using our system without extensive integration work, we use Polkadot parachain for transaction billing (per data storage/retrieval operation)

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the updated application. However, could you take another look at our template and update the formatting of the application and especially the milestones: https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#milestone-1-example--implement-substrate-modules Deliverables 0a-0d of the template are usually mandatory for all milestones. Furthermore our grants program focuses on funding open source software development. So, we usually don’t directly support things that aren’t necessarily helpful to others in our ecosystem, like the finalisation of requirements or deployment. Additionally, feel free to add as many technical details as part of the milestones as possible (e.g. programming languages). These are usually the requirements of our contracts, which we will check during the milestone evaluations.

(For reference: https://github.com/w3f/Grants-Program/pull/842)

**Comment by lk2684753** [comment]
> 感谢您更新的应用程序。但是，您能否再看看我们的模板并更新应用程序的格式，尤其是里程碑：[https ://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#milestone- 1-example--implement-substrate-modules](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#milestone-1-example--implement-substrate-modules)模板的可交付成果 0a-0d 通常对于所有里程碑都是强制性的。此外，我们的赠款计划侧重于资助开源软件开发。因此，我们通常不会直接支持对我们生态系统中的其他人不一定有帮助的事情，例如需求或部署的最终确定。此外，请随意添加尽可能多的技术细节作为里程碑的一部分（例如编程语言）。这些通常是我们合同的要求，我们将在里程碑评估期间对其进行检查。
> 
> （供参考：#842）


Thank you for your suggestion, we have modified the content according to the template, please check, if you have any other questions, we will be happy to answer

**Comment by lk2684753** [comment]
> Thanks for the updated application. However, could you take another look at our template and update the formatting of the application and especially the milestones: https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#milestone-1-example--implement-substrate-modules Deliverables 0a-0d of the template are usually mandatory for all milestones. Furthermore our grants program focuses on funding open source software development. So, we usually don’t directly support things that aren’t necessarily helpful to others in our ecosystem, like the finalisation of requirements or deployment. Additionally, feel free to add as many technical details as part of the milestones as possible (e.g. programming languages). These are usually the requirements of our contracts, which we will check during the milestone evaluations.
> 
> (For reference: #842)

Thank you for your suggestion, we have modified the content according to the template, please check, if you have any other questions, we will be happy to answer

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update and sorry for the late reply. I just realized, I forgot to post my message here this morning.  With Deliverables 0a-0d are mandatory, we usually mean exactly the default deliverables of the template. So specifically the open source licence, documentation, unit tests and docker. Could you integrate this for each milestone as well as an article/announcement at least for the last milestone?

**Comment by lk2684753** [comment]
> Thanks for the update and sorry for the late reply. I just realized, I forgot to post my message here this morning. With Deliverables 0a-0d are mandatory, we usually mean exactly the default deliverables of the template. So specifically the open source licence, documentation, unit tests and docker. Could you integrate this for each milestone as well as an article/announcement at least for the last milestone?

I've done the 0a-0d update, integrating the relevant stuff, thanks for the advice!

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks again for the update. As I said before, we usually don’t fund the “Requirements finalisation” as well as “official website UI design”. Also “Bug fixes and Improvements” isn’t really specific and would be hard to evaluate, since you could also say we didn’t find any bugs. Furthermore: “Deploying Application” and “Tokenomics Finalised” is something, which we usually don’t fund. In general, the aim of our grants program and the deliveries should be to develop open source tech that is useful for the entire ecosystem and the deliverables are the requirements of our contracts. 

Apart from this I have a few questions regarding the remaining deliverables: 

- “Substrate module: Aggregator” Is this purpose of this to list all the possible storage solution and how to interact with them? 
- What do you mean with “Mainstream storage platform node construction”? Do you mean you will integrate the systems which you list as part of the deliverable? 
- Regarding “Develop primer switching engine”. Why don’t you use one of the existing solutions for this? 
- “Payment System Design” How exactly does this work? What are potentially attack vectors and how do you make sure that files are actually stored? 
- “Develop decentralized index query middleware” Do you mean something like thegraph? This alone is a huge and complex problem.

**Comment by lk2684753** [comment]
> Thanks again for the update. As I said before, we usually don’t fund the “Requirements finalisation” as well as “official website UI design”. Also “Bug fixes and Improvements” isn’t really specific and would be hard to evaluate, since you could also say we didn’t find any bugs. Furthermore: “Deploying Application” and “Tokenomics Finalised” is something, which we usually don’t fund. In general, the aim of our grants program and the deliveries should be to develop open source tech that is useful for the entire ecosystem and the deliverables are the requirements of our contracts.
> 
> Apart from this I have a few questions regarding the remaining deliverables:
> 
> * “Substrate module: Aggregator” Is this purpose of this to list all the possible storage solution and how to interact with them?
> * What do you mean with “Mainstream storage platform node construction”? Do you mean you will integrate the systems which you list as part of the deliverable?
> * Regarding “Develop primer switching engine”. Why don’t you use one of the existing solutions for this?
> * “Payment System Design” How exactly does this work? What are potentially attack vectors and how do you make sure that files are actually stored?
> * “Develop decentralized index query middleware” Do you mean something like thegraph? This alone is a huge and complex problem.

Sorry, I have revised the relevant content, about the finalization of requirements" and "UI design of the official website, I have deleted, I think this is not in the content of the proposal, I have added some proposal details, including the pallet we want to provide;

Regarding the node construction of mainstream storage platforms, I think this is the infrastructure construction we need to do behind the scenes. We will build many storage platforms ourselves, which will improve the stability of user storage; about the indexer, it will be developed by us using Go language. Yes, the main user retrieves data from all storage platforms, because the API of each storage platform is different, we will encapsulate it into a unified API, which is convenient for us to query data;

Regarding the actual storage of files, we develop a repeater. When we receive the storage fee, we will call the contract and record the storage contract in the contract. Our storage will return the storage credentials, storage node information, etc., any stored Users can see your storage credentials, which ensures the authenticity of data storage;

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. However, it is hard to keep track of all the changes (and it seems you changed a lot!), since you moved the file into a new folder: 应用. Could you move the file again into the application folder?  I still have the following question, which are not really clear to me: 

- What are potentially attack vectors regarding your storage solution and how do you make sure that files are actually stored? You mention you have a repeater, how does this work in a trustless way? 
- “Develop decentralized index query middleware” Do you mean something like thegraph? This alone is a huge and complex problem.

Regarding your new deliverables, I have the following comments:
- Substrate module: pallet_did, or Substrate module: pallet_dao	: We have a bunch of did and dao pallets in our ecosystem. Couldn’t you just use one of the existing solutions? What is the difference between you solution and others? 
- Transaction relayer: Which programming languages are you planning to use for this? 
- For your last milestone: Do you already have mockups or an initial design?

**Comment by lk2684753** [comment]
> Thanks for the update. However, it is hard to keep track of all the changes (and it seems you changed a lot!), since you moved the file into a new folder: 应用. Could you move the file again into the application folder? I still have the following question, which are not really clear to me:
> 
> * What are potentially attack vectors regarding your storage solution and how do you make sure that files are actually stored? You mention you have a repeater, how does this work in a trustless way?
> * “Develop decentralized index query middleware” Do you mean something like thegraph? This alone is a huge and complex problem.
> 
> Regarding your new deliverables, I have the following comments:
> 
> * Substrate module: pallet_did, or Substrate module: pallet_dao	: We have a bunch of did and dao pallets in our ecosystem. Couldn’t you just use one of the existing solutions? What is the difference between you solution and others?
> * Transaction relayer: Which programming languages are you planning to use for this?
> * For your last milestone: Do you already have mockups or an initial design?

- Regarding the potential attacks on storage, there will be many, such as big data consuming bandwidth attacks, storage hardware damage, non-propagable data storage, etc.; we will have disaster recovery testing, disaster recovery failover and failover, and we have decades of data Storage experience is particularly important in the construction of basic storage facilities; for the actual storage of data, we will provide credentials. According to different storage platforms, we provide three different storage methods. Object storage, providing key-value storage, its interface is simple GET, PUT, DEL and other extensions; block storage: This interface usually exists in the form of QEMU Driver or Kernel Module, which needs to implement the interface of Linux's Block Device Or the Block Driver interface provided by QEMU, such as Sheepdog, AWS's EBS; file storage: usually means supporting POSIX interface, which is a type of traditional file system such as Ext4, but the difference is that distributed storage provides the ability to parallelize , such as Ceph's CephFS (CephFS is Ceph's file storage-oriented interface)
- The index query middleware is similar to thegraph, which we mainly use for data retrieval. It is not as complicated as it is, but it also has a lot of workload
- Regarding the Substrate module: Yes, I saw the did pallet, I decided not to develop this module, I think we still need to write the dao pallet ourselves, we need to have some dao proposals on storage, and better integrate with the system
- Transaction Repeater: We are going to use `go` or `rust`
- For the last milestone: yes, we already have a mockup and initial design on the UI, which I think can be implemented in the first phase

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for moving the file into the correct folder and updating the document as well as the reply. I have a few follow-up questions/comments:

- Regarding the potential attack vectors and the storage solution, it’s still hard for me to understand how this works in a decentralised way.  Your current solution seems to me rather centralised or how does your solution ensure that files are actually stored in a decentralised way. 
- If you want to leverage something similar to thegraph in our ecosystem, you might want to take a look at https://github.com/subsquid/hydra and potentially see if you could reuse it. 
- Could you integrate the mockup/design into the application?

**Comment by lk2684753** [comment]
> 感谢您将文件移动到正确的文件夹并更新文档以及回复。我有一些后续问题/意见：
> 
> * 关于潜在的攻击媒介和存储解决方案，我仍然很难理解它是如何以分散的方式工作的。在我看来，您当前的解决方案似乎相当集中，或者您的解决方案如何确保文件实际上以分散的方式存储。
> * 如果你想在我们的生态系统中利用类似于图的东西，你可能想看看https://github.com/subsquid/hydra并可能看看你是否可以重用它。
> * 您能否将模型/设计集成到应用程序中？

  - Not all storage is decentralized, such as using ipfs storage, it will be decentralized storage, we also use ipfs_cluster to help us better backup files, most storage platforms are decentralized storage, it depends on the user storage Of course, we can also help him choose. For example, through ipfs storage, we have many distributed storage nodes and cluster nodes. This is a working example diagram of a single node. https://bafybeie6xwa2az7tw2ucm3tzdkaqymh3eqv2vdmsfcpl6icqxbbh4y5j5m.ipfs.dweb.link/sync_deal.png
  - https://github.com/subsquid/hydra This is a really good project solution, I will work with the team to see if it can be integrated into the project, thank you for sharing
  - Yes, we can integrate the model/design into the application！

**Comment by lk2684753** [comment]
> Thanks for moving the file into the correct folder and updating the document as well as the reply. I have a few follow-up questions/comments:
> 
> * Regarding the potential attack vectors and the storage solution, it’s still hard for me to understand how this works in a decentralised way.  Your current solution seems to me rather centralised or how does your solution ensure that files are actually stored in a decentralised way.
> * If you want to leverage something similar to thegraph in our ecosystem, you might want to take a look at https://github.com/subsquid/hydra and potentially see if you could reuse it.
> * Could you integrate the mockup/design into the application?

Not all storage is decentralized, such as using ipfs storage, it will be decentralized storage, we also use ipfs_cluster to help us better backup files, most storage platforms are decentralized storage, it depends on the user storage Of course, we can also help him choose. For example, through ipfs storage, we have many distributed storage nodes and cluster nodes. This is a working example diagram of a single node. https://bafybeie6xwa2az7tw2ucm3tzdkaqymh3eqv2vdmsfcpl6icqxbbh4y5j5m.ipfs.dweb.link/sync_deal.png
https://github.com/subsquid/hydra This is a really good project solution, I will work with the team to see if it can be integrated into the project, thank you for sharing
Yes, we can integrate the model/design into the application！

**Comment by lk2684753** [comment]
> Thanks for moving the file into the correct folder and updating the document as well as the reply. I have a few follow-up questions/comments:
> 
> * Regarding the potential attack vectors and the storage solution, it’s still hard for me to understand how this works in a decentralised way.  Your current solution seems to me rather centralised or how does your solution ensure that files are actually stored in a decentralised way.
> * If you want to leverage something similar to thegraph in our ecosystem, you might want to take a look at https://github.com/subsquid/hydra and potentially see if you could reuse it.
> * Could you integrate the mockup/design into the application?

 - Not all storage is decentralized, such as using ipfs storage, it will be decentralized storage, we also use ipfs_cluster to help us better backup files, most storage platforms are decentralized storage, it depends on the user storage Of course, we can also help him choose. For example, through ipfs storage, we have many distributed storage nodes and cluster nodes. This is a working example diagram of a single node. https://bafybeie6xwa2az7tw2ucm3tzdkaqymh3eqv2vdmsfcpl6icqxbbh4y5j5m.ipfs.dweb.link/sync_deal.png
  - https://github.com/subsquid/hydra This is a really good project solution, I will work with the team to see if it can be integrated into the project, thank you for sharing
  - Yes, we can integrate the model/design into the application！

**Review by Noc2 — CHANGES_REQUESTED** [review]
Sorry for the late reply here and thanks for taking a look at hydra and integrating mockups. Regarding the decentralisation of the storage solution, I was mostly referring to the storage process as a whole including the deal. So right now your file is stored on IPFS (or AWS, etc) and you have a hash that represents the file and you paid for this storage. But this doesn’t ensure that the file is actually stored and is actually available. You basically need to trust a single person here to keep his promise or am I missing something.

**Comment by Noc2** [comment]
I’m closing this application due to inactivity. Let me know if I should reopen it.

**Pull request closed without merging**
