### PR TITLE
Added AletheiaData.md (#681)

### PR DESCRIPTION
**Pull request by aletheiadata**
### Project Abstract

Aletheia is a citizen effort's project that seeks to encourage both public and private entities to facilitate access to public information so that it can have a more relevant social impact.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [X] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [X] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [X] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [X] The software delivered for this grant will be released under an open-source license specified in the application.
- [X] The initial PR contains only one commit (squash and force-push if needed).
- [X] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Comment by aletheiadata** [comment]
Hi Sebastian,

Thank you for reaching out.

At the moment we haven't implemented any contract yet. Our intention is
creating a DAO which will have smart contracts to reward users and
contributors. We haven't started yet to develop our smart contracts but
it's on the roadmap.

Our Smart Contract will do as follow:
- Reward users who participate with Aletheia Tokens
- Consumer will be able to pay our service with Aletheia Token or Fiat

hope it's clear,

Thank you.
Enzo

**Comment by semuelle** [comment]
@aletheiadata, the Web3 Foundation grants program funds projects that benefit the web3 ecosystem, usually by building open source software, or by providing a new service or infrastructure. If you have a novel concept for making use of Substrate/smart contracts to manage payments/rewards for and access to your API, I am happy to review it. However, the application currently lacks any technical detail about how you want to accomplish that. I will therefore close this PR. 

I would encourage you to have a look at accepted and ongoing applications [here](https://github.com/w3f/Grants-Program/pulls) or [here](https://github.com/w3f/Grants-Program/blob/master/docs/accepted_grant_applications.md), and our [Polkadot stack](https://github.com/w3f/Grants-Program/blob/master/docs/polkadot_stack.md) document to see what's already out there and what isn't. Please reapply once you have worked out the details.

**Comment by aletheiadata** [comment]
Hi @semuelle , I don't know if this is the right forum for this. But I think I didn't explain myself well. What I was trying to say is   that Aletheia is an Open Source project that seeks to encourage both public and private entities to facilitate access to public information so that it can have a more relevant social impact. We use IPFS as our secure File Storage. We'd like to integrate Filecoin to our system. This solution allows keep this public information (dominican republic gov) safe, secure, and always available.

As developers we have seen the need to make use of public information (information in the public domain that should be available and accessible by law) but in the search we quickly realised that although the information is (in part) available, it is not organised in a way that is easy to use (uses that can be from the consultation of the data, to the elaboration of the same for statistical use or to create computer products oriented to citizens. Another problem that we frequently find is the lack of a standard in the format of these files. As well as the use of formats that DO NOT allow the extraction of information. We know that, like us, there are other Dominicans who need to access this data and that is why we decided to develop a REST API to facilitate access and distribution The objective is to create an ecosystem where these files are ALWAYS available, accessible 24 hours a day and accompanied by APIs to facilitate the consumption and exchange of this information, immutable and reliable "single source of truth".

We want to promote the use of this tool in the public administration. If i don't do it right, the status quo will keep people uninformed with not reliable access to public information. This project has a level of complexity related to the big data component of it.

What I was referring to before about the tokens is the intention of our organization of becoming a DAO and distribute tokens in the future to reward community members, but that one part of the plan. Bellow I'll post our current milestones:

Milestone 1: Core, Security Layer
3 month

- Improve search and transform algorithms
- Pin all available IPFS files
- Integrate Web.storage
- Integrate Filecoin

Milestone 2: Documentation and demos
1-2 month

- Improve Documentation and Demos

Milestone 3: Community
1 month

- Create community
- Weekly meetings
- Discord / Slack channels
- Email list
- Governance rules
- Promote to schools and institutions

Milestone 4: Independence Day
4 month

- Create DAO
- Airdrop for contributors

Milestone 5: Open Services

- Release to public all public Services (which includes minting docs)



Hope this help you understand better our project. If you think that this is not something you guys fund anyway, please let me know. I just glad to be able to clarify.

Have a great day,
Enzo

**Comment by semuelle** [comment]
Hi Enzo, 
thanks for your message. Supporting Open Data is a noble goal, and I know how frustratingly bad some information can be found. 
The main problem with your application is that it is largely about community-building, which the W3F grants program doesn't support. So all the meetings, promotion, release, airdrop, channels, lists and rules deliverables would have to be removed. On top of that, we usually look for some kind of technical advancement that is unique to the project. You could achieve this by precisely laying out the functionality of the smart contract(s) and explaining what it accomplishes that others don't. It is not a guarantee for acceptance, though; it needs to be generalised enough to be used by others outside your project.

If you want to continue with your application, I'd suggest you look at the links I provided above, incorporate the changes I suggested and then open a new PR. I would highly recommend looking at the [smart contract projects we have supported](https://github.com/w3f/Grants-Program/blob/master/docs/polkadot_stack.md#memo-ink-smart-contracts) in the past, find their pull requests and look at what they promised to deliver and the questions we asked them. 

Otherwise, do you know about the [IPFS](https://github.com/ipfs/devgrants)/[FileCoin](https://github.com/filecoin-project/devgrants) grants program? From what I can gather, any project that utilises IPFS/FileCoin can apply. 

Either way, best of luck!

**Pull request closed without merging**
