### PR TITLE
Epirus Substrate Explorer grant proposal

### PR DESCRIPTION
**Pull request by conor10**
### Project Abstract

This proposal is for a grant to add Substrate-based blockchain support to the Epirus Blockchain Explorer. 

The Epirus Substrate Explorer will be a modular explorer for Substrate-based blockchains centred on supporting the Substrate contracts pallet and ink! smart contracts.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying?

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] I have read and understood the [FAQs](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md), [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md) and [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).
- [ ] I prefer the discussion of this application to be in a private Element/Matrix channel. My username is: ``@_______``

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] Hackathon
- [] Personal Recommendation
- [ ] Substrate Builders Program
- [ ] Investor/VC
- [ ] Online Search
- [x] Other: From the Parity team

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. We are indeed very interested in an ink! Smart contract explorer. I have just one question: Will the UI be based on your current UI: https://www.web3labs.com/epirus-explorer Usually we ask teams to provide some mockups or an initial design with us, when they apply for a grant that contains UI deliveries. Additionally, you still need to sign our CLA. These are basically the terms and conditions of our grants program. Independent of it, I will already mark the application as ready for review.

**Comment by conor10** [comment]
Hi @Noc2, the UI will be based on our existing UI. @frozenpomelo can comment further. 

Regarding the CLA, I have signed it, but it's not updating here for some reason. I can see the signed CLA in https://cla-assistant.io/my-cla.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the quick reply. Each contributor needs to sign the CLA, so I guess @frozenpomelo hasn’t signed yet. Regarding the UI, feel free to specifically mention this as part of the application/milestones.

**Review by sbp-parity — APPROVED** [review]
I'm excited to go ahead with this! Very much looking forward to seeing it in action.

**Review by SBalaguer — APPROVED** [review]
This looks very good, looking forward to this!

**Review by takahser — APPROVED** [review]
@conor10 I'm happy to go ahead with it as well. Looking forward to your delivery! 👍

**Pull request merged**
