### PR TITLE
DMTP_Grant Request

### PR DESCRIPTION
**Pull request by Arusasaki**
### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] Hackathon
- [x] Personal Recommendation
- [ ] Substrate Builders Program
- [ ] Investor/VC
- [x] Online Search 
- [ ] Other: _______

### CODE REVIEW

**Comment by AruSasaki** [comment]
We are just starting to develop and there are quite a few things we don't know. Even if we are not selected by Grant for this application, we would like to know where we should improve.
I intend to spend my life trying my hand at this field.
Let's create the era of Web3 together.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the interest in our grants program. However, at the moment you changed two files. Could you please submit a single application instead? Additionally, in one of your documents it says Total Costs: 600,000USD, which is far from a level 1 grant. Furthermore some milestones seem to be missing and generally the application seems to be unfinished. Let us know once we should take a look at the application.

**Comment by AruSasaki** [comment]
We have corrected the estimates and milestones that you pointed out. Please check it.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. However, as part of the PR you are still deleting the application-template. Additionally your delivery no longer contains the milestone table and all the other information. Maybe it’s helpful for you to take a look at all the merged applications, to see how a successful application should look like: https://github.com/w3f/Grants-Program/tree/master/applications

**Comment by semuelle** [comment]
ping @AruSasaki. 

It's probably easiest if you create a new pull request from a new fork and simply paste the `applications.DMTP.md` file into it. [This section of our README](https://github.com/w3f/Grants-Program/blob/master/README.md#1-application) explains what to do.

**Comment by Noc2** [comment]
I’m closing this application due to inactivity. Let me know if I should reopen it.

**Pull request closed without merging**
