### PR TITLE
Centrifuge gsrpc v2

### PR DESCRIPTION
**Pull request by mikiquantum**
#### Project Abstract

Initially Go-Substrate-RPC (GSRPC for short) was designed under the premise of being a low-level, static and strongly typed library, where all the type resolution happen at compilation time. This approach allowed almost full flexibility to developers to build their own types and events depending on the target chain/s they were connecting to.

On the other hand, since the types are statically defined, this didn’t leave room to, gracefully, deal with parsing errors when a type (defined on the chain runtime) is not defined in the GSRPC client.

More details in the application commit.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [ ] The initial PR contains only one commit (squash and force-push if needed).
- [ ] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the application. In general, this is definitely something that we want to support. However, could you structure the milestones as shown in our template, here: https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#milestone-1-example--basic-functionality? The default deliverables 0a-0d below are usually mandatory for all milestones. This helps us with the evaluations and is also part of the terms and conditions. Regarding the maintenance part, ideally, we would keep this separate. Also, our legal team said that for now, we should sign regular contracts for this. So could you remove this initially?

**Comment by mikiquantum** [comment]
Hi @Noc2, thanks for the feedback. I just pushed the changes suggested. Let me know if anything else is needed.

**Review by Noc2 — APPROVED** [review]
Thanks a lot for the update. I’m happy to support it and share it with the rest of the team. I personally think the price is relatively high, but given that you already put so much effort into it and also maintained it in the past without any support from us, I’m happy to support it.

**Comment by dsm-w3f** [comment]
@mikiquantum thank you for your application. As David said, this is definitely something that we want to support. Just for understanding, why did you pick this specific demand as a new grant proposal since seems that you have many other community demands on the [GitHub issues from the project](https://github.com/centrifuge/go-substrate-rpc-client/issues)? Is this the best demand to work for now? I think is great to have many demands regarding this project since showing us that is being actually used by the community. I also notice that you are working on that demands as far as possible.

**Review by alxs — APPROVED** [review]

**Review by dsm-w3f — APPROVED** [review]

**Review by keeganquigley — APPROVED** [review]
Thanks for the explanation @mikiquantum, I'm quite familiar with team's reputation and am happy to support it as well.

**Comment by mikiquantum** [comment]
Thank you all for the support!

**Comment by keeganquigley** [comment]
Hi @mikiquantum how is milestone 2 coming along?

**Comment by mikiquantum** [comment]
@keeganquigley We just merged the [v2 work](https://github.com/centrifuge/go-substrate-rpc-client/pull/338) . We will open the deliverable asap.

**Pull request merged**
