### PR TITLE
massbit_route application

### PR DESCRIPTION
**Pull request by daywednes**
### Project Abstract

- Codelight team’s vision is to build a decentralized, user-operated, and governed Blockchain Distribution Network. To achieve the goal, we build Massbit blockchain on Substrate framework, with MBT token to create an economy, where Node Providers stake and earn Massbit token for servicing the BDN and Consumers pay in token for global access to decentralized blockchain APIs. 

- The majority of existing dApps are utilizing blockchain Infrastructure-as-a-Service (IaaS) such as Infura or GetBlock to shorten the time to bring their products into production. Those blockchain IaaS services have gained traction quickly and contributed to the growth of many layer 1 and 2 blockchain networks. But that added value comes with a downsize, many "dApps" are relying on a centralized blockchain IaaS service and prone to outage caused by IaaS providers. Massbit Route eliminates blockchain API single-point of failure by forming a global network of Independent node providers to allow dApps access to the nearest blockchain datasource with optimal response time.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying?

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] I have read and understood the [FAQs](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md), [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md) and [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).
- [x] I prefer the discussion of this application to be in a private Element/Matrix channel. My username is: ``@_______``

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] Hackathon
- [ ] Personal Recommendation
- [x] Substrate Builders Program
- [x] Investor/VC
- [ ] Online Search
- [ ] Other: _______

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the grant application. Could you add the default deliveries of the template to the milestones: https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md? Like for example a licence file, testing guide etc. Could you also specify the programming language of your deliveries? For example, what will be implemented as pallets or ink! Smart contract? Also you should remove the integration of DOT and ETH or tokenomics from the deliveries. We focus with our grant program only on the technical open source deliveries and don’t want to support a specific integration, etc.

**Comment by hoanito** [comment]
@Noc2 David, I signed the CLA

**Review by Noc2 — CHANGES_REQUESTED** [review]
Sorry for the late reply here and thanks for the update. However, could you still add the default deliveries of the template to the application? Deliverables 0a-0d are usually mandatory for all milestones, and deliverable 0e at least for the last one. If you do not intend to deliver one of these, please state a reason in its specification (e.g. Milestone X is research oriented and as such there is no code to test). See https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md Also please try to focus on the technical deliveries as part of the milestones. We usually don’t support things like “Internal Performance test in 6 zones” or the deployment of testnests. On the one hand they are difficult to evaluate as part of the delivery, on the other hand it’s not something others can easily reuse.

**Comment by hoanito** [comment]
@Noc2 Thank you for your feedback !!!

I have updated the Milestones to focus more on our technical deliveries of Massbit Route and excluded the testing and deployment phases. 

0a-0e items are also added to match with the standard grant format. These are already parts of our development process so we though it was unnecessary to include in here.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks again for the update. I have a few follow-up questions:

- How do you make sure that the nodes actually fulfil the Performance requirements?  
- How does your system deal with  denial-of-service (DDoS) attacks? Isn’t this potentially a problem?
- Do you have design mock-ups for the Web Portal implementation? 
- Could the first milestone already contain something polkadot/substrate related? For example could you first implement milestone 2 or switch some of the deliveries. Because currently, it looks like you could implement milestone 1 for any blockchain.

**Comment by hoanito** [comment]
@Noc2 Thanks for reviewing our documentation. I have included the answers for your follow-up questions.

1. [Question 1](https://github.com/massbitprotocol/Open-Grants-Program/blob/massbit_route_application-1/applications/massbit_route.md#how-does-massbit-make-sure-that-the-nodes-actually-fulfil-the-performance-requirements)
2. [Question 2](https://github.com/massbitprotocol/Open-Grants-Program/blob/massbit_route_application-1/applications/massbit_route.md#how-does-massbit-system-deal-with-denial-of-service-ddos-attacks)
3. I have included the UI design of the Portal under section **7. Portal**
4. I have updated Milestone 1 to include Subtrate related deliveries and this is actually reflecting what we are working on now. I  thought I would be clearer to separate Subtrate part into a different Milestone

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. I have two more questions: 

- Could you add the overview part to the application again: https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#overview-1 
- Would you be willing to reduce the price? For example it currently says for both milestones Estimated duration: 1 month, FTE: 6, but the costs are completely different.

**Comment by daywednes** [comment]
Hi @Noc2 - let me take the second part. Our team has actually been working on this project for over 9 months as you can check at https://github.com/massbitprotocol/ - In the beginning, I was thinking about asking for a 100k grant because it's a really big and complicated project. But going that round could take very long time, so we decided to go with level 2.

I would like to mention there is only Pocket Network working on the same problem, but our design to solve the problem is different and, I believe, more effective than the Pocket Network approach in terms of performance.

Though we are proposing one month for each milestone, we have prepared and done some partial work in advance to be able to finish on the proposed timeline. Our team has done a lot of work for milestone 1 and it will still require more work for internal testing. That's why the cost of each milestone is different.

> Thanks for the update. I have two more questions:
> 
> * Could you add the overview part to the application again: https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#overview-1
> * Would you be willing to reduce the price? For example it currently says for both milestones Estimated duration: 1 month, FTE: 6, but the costs are completely different.

**Review by alxs — APPROVED** [review]

**Comment by hoanito** [comment]
@alxs what is the due date for our Milestone 2? Is it 1 month after the due date of Milestone 1 (7/27)? or 1 month after Milestone 1 delivery get approved?

Thanks!!

**Comment by alxs** [comment]
@hoanito usually, 1 month after it was approved. It's not an issue if it's a bit delayed either. if you think you'll only be able to submit over 2 weeks after the deadline, you can submit an [amendment](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval).

**Pull request merged**
