### PR TITLE
hyperfridge

### PR DESCRIPTION
**Pull request by wstrametz**
#### Project Abstract

With our previous grant [FIAT-on-off ramp](https://github.com/w3f/Grant-Milestone-Delivery/pull/854) users are able to "plug in" their bank account into the Polkadot network. This means being able to query balances and transactions and trigger new transactions (wire-transfers) using an off-chain-worker. The aim of Hyperfridge is to make this process trustless through the usage of Zero-Knowledge Proofs and Multi Party Computation. As a result, we are able to create and consume events on-chain from any bank account supporting ISO20022/Ebics standards which thousands of banks support. This reduces [information asymmetry](https://en.wikipedia.org/wiki/Information_asymmetry) between FIAT and Crypto and eliminates the need of FIAT-intermediaries except for the bank serving the account holder - with full proof of (correct) computation adding the property of soundness to the system. 

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) or BTC address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by wstrametz** [comment]
I have read and hereby sign the Contributor License Agreement.

**Comment by wstrametz** [comment]
recheck

**Comment by dastansam** [comment]
I have read and hereby sign the Contributor License Agreement.

**Comment by wasabrot** [comment]
I have read and hereby sign the Contributor License Agreement.

**Review by keeganquigley — CHANGES_REQUESTED** [review]
Thanks for the application @wstrametz this looks really interesting. I have a couple of initial comments:

- Great job of describing technical details in the application, but could you also integrate these into the milestone tables themselves?
- Docker and unit tests are usually part of the mandatory deliverables 0c. and 0d. section, so these could be moved up and swapped out with  0c. "Swagger" which is not a mandatory deliverable and should be moved down into the numbered list. If you could adjust these that would help adhere to the [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md). 
- I'm not quite sure why a stablecoin app is needed in M4. I don't see much info about it in the application, could you provide more details about its purpose?

Thanks!

**Comment by wstrametz** [comment]
Thanks a lot for feedback @keeganquigley! The hyperfridge crate can be used independently from the node for sure, thats also our goal. The reason why we would like to add a node is to show a simple-enough application how the crate is used in a node - but more importantly - to show the whole “round-trip” which includes triggering state changes on be bank account as well (not only reading, also writing). So it shows how to create a wire-transaction safely on-chain in a kind-of 2-phase-commit: first we need to send the instructions to the backend and thus tell the bank account to do a wire-transfer. Only after we see that this transaction has been executed by checking daily statement of the bank account, can we “commit” this transaction on-chain in a node to make it public. The crate only provides the lower level APIs to do so, but should not provide the logic e.g. to which bank account  the funds should be transferred. This is by intention, because we want the crate to be as low level and flexible as possible. The app with the stable coin shows how to work with the crate end-to-end, therefore we would like to add it. Please me know your thoughts on that. Regarding your other request - I will add more details on API level to Milestone 4 based on the specifications of the FIAT-on-off-ramp.

**Review by keeganquigley — CHANGES_REQUESTED** [review]
Thanks for the explanation @wstrametz could you also implement the other requested changes as well? That will help it adhere to the template.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the application. It sounds interesting. I would mostly be interested in learning more about your long-term funding plans and the future of the project. Ideally, you are either getting funding via VCs at some point or you focus on being a "common good" project and you are requesting funds from the treasury. The grants program tries to not support projects over a longer period of time.

**Comment by wstrametz** [comment]
> Thanks for the explanation @wstrametz could you also implement the other requested changes as well? That will help it adhere to the template.

Hi @keeganquigley - I updated the requested things now.

**Comment by wstrametz** [comment]
> Thanks a lot for the application. It sounds interesting. I would mostly be interested in learning more about your long-term funding plans and the future of the project. Ideally, you are either getting funding via VCs at some point or you focus on being a "common good" project and you are requesting funds from the treasury. The grants program tries to not support projects over a longer period of time.

@Noc2  - thx for feedback - not sure if this is positive or negatve :)  .. I think the base technology (libs) should be common good and kept free of tokens or mandatory commercial services - banking APIs are easy to access and we should not do worse. If the idea gets traction, it might help the whole industry to use blockchain-tech to adapt real world scenarios, because we do not need tokens to transfer value (they still might represent it - like wo do with proposed stablecoin app).  I am looking at that problem for quite some time with different implementations and also experimented with ZK proofs to make it trustless. Up to now - unzipping files, parsing XML etc. was not quite doable in reasonable time with existing circuit technology - risc0 finally does the job. The ask in the grant is as small as possible but tries do be complete to achieve soundness - e.g. we do not implement transaction inclusion proofs as described in the whitepaper or aim at parachain (which would make perfect sense). But we can be trustless for on- and off-ramping, and get more confident with the tech (e.g. execution time, using recursive proofs on transaction table, Snark the stark for on-chain verification) to define next steps which would give us a much better position to ask treasury or a VC. Let me know if this makes sense - you have more experience how to get such things started. I m very interested in long-term funding and "all-in" if its makes sense to push it now.

**Review by keeganquigley — APPROVED** [review]
Thanks for your answers @wstrametz I'm happy to see that @dastansam research is being used, and excited for the prospects of what ISO20022 can bring to the table. Also partly based on your previous work, I'm happy to go ahead with it. I will mark it as ready for review and ping the rest of the committee.

**Review by Noc2 — APPROVED** [review]

**Review by SBalaguer — APPROVED** [review]
Based on the previous discussions I'm happy to support this. Excited about seeing this being available for everyone to integrate, and eventually becoming a used product of Polkadot.

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/hyperfridge-zk-web-proofs-for-tradional-financial-backends-tradfi/8637/1

**Comment by keeganquigley** [comment]
Hi @wstrametz I believe that milestone 5 is all that is needed to complete the grant. Can you provide a quick update on it? Thanks!

**Comment by wstrametz** [comment]
> > Hi @wstrametz I believe that milestone 5 is all that is needed to complete the grant. Can you provide a quick update on it? Thanks!
> 
> Hey @keeganquigley, it's coming along well. Will submit the milestone in the coming days. Thanks!

Thanks for answering @dastansam !

**Comment by keeganquigley** [comment]
Hi @wstrametz @dastansam just checking in.

**Comment by dastansam** [comment]
> Hi @wstrametz @dastansam just checking in.

hey sorry for late reply, we are working on it.

**Comment by keeganquigley** [comment]
Hi @dastansam @wstrametz I don't believe we have received a delivery yet. Do you plan to submit one soon?

**Comment by keeganquigley** [comment]
Hey @wstrametz @dastansam let me know if you are still working on it. Any further delays would need an amendment. Thanks.

**Comment by dastansam** [comment]
> Hey @wstrametz @dastansam let me know if you are still working on it. Any further delays would need an amendment. Thanks.

hey @keeganquigley if we won't finish by the end of this week, we will open an amendment PR. We are dealing with some dependency version issues. Thanks

**Comment by keeganquigley** [comment]
Hi @dastansam any luck fixing the issues? Can you provide an update?

**Comment by dastansam** [comment]
> Hi @dastansam any luck fixing the issues? Can you provide an update?

hey,

we are doing the amendment. expect a PR from us soon. thanks!

**Comment by keeganquigley** [comment]
nvm found it [here](https://github.com/w3f/Grants-Program/pull/2453).

**Comment by dastansam** [comment]
> nvm found it [here](https://github.com/w3f/Grants-Program/pull/2453).

Yes, we are submitting the last milestone this week. Thanks!

**Comment by keeganquigley** [comment]
Thanks @dastansam let me know when you submit it.

**Comment by keeganquigley** [comment]
Hi @dastansam just a friendly nudge on M5 :)

**Comment by keeganquigley** [comment]
Hi @wstrametz @dastansam can you provide an update please?

**Comment by dastansam** [comment]
> Hi @wstrametz @dastansam can you provide an update please? 

Hey, sorry for the delay. We are pushing to submit it by the end of the week. Will submit amendments if we can't make.

**Comment by dastansam** [comment]
> Hi @dastansam can you please provide an amendment for this otherwise we will put up a vote to cancel in a few weeks since the milestone is far overdue. Thank you.

ok, will do

**Pull request merged**
