### PR TITLE
TREX Phase 2

### PR DESCRIPTION
**Pull request by kaisuki**
#### Project Abstract

This is an application for a follow-up grant for the [TREX_Network](https://github.com/NexTokenTech/Grants-Program/blob/main/applications/TREX_Network.md) that has been completed in the following delivery: https://github.com/w3f/Grant-Milestone-Delivery/pull/724

The main goal of this stage is to perfect the ecosystem related to key holders, which includes key splitting, distributed encryption and its tools, visualized encryption and decryption dApp, and the key holder economic system.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks for the application @kaisuki I like the idea of an alternative to trusted setups. 

- Would the arbitrary data that is encrypted by dTRE be able to work in tandem with XCM? Or is this an entirely separate system?
- Have you researched other privacy projects in the Polkadot space which you might be able to re-use, such as [this page](https://wiki.polkadot.network/docs/build-open-source) for example?
- How does time-release encryption compare to existing TEE reputation systems such as [Encointer](https://github.com/encointer)  and [Integritee](https://github.com/integritee-network)?

**Comment by kaisuki** [comment]
Thanks for your idea @keeganquigley
1.We have upcoming work on XCM collaboration, where we plan to utilize the Relay Chain in the Polkadot network for a series of interactions.
2.We have familiarized ourselves with some of the tools in the Polkadot toolchain, and in this phase, we plan to implement certain functionalities that require expanding the Polkadot wallet to support our own features, such as sending encrypted key fragments to the chain for user-specific functionalities, and more.
3. For the functionality of SGX registration and status monitoring, there is no significant difference between theirs and ours.
We reuse their modules as a Lego pieces in our architecture for our specific applications but we modify and add many new functinalities to fit our needs. IntegreTEE's pallet is not designed for data encryption but program execuation so they do not have any supports for encrypted data and secured communication.
We removed all unrelated codes from their pallets.
Moreover, we put enclave workers' RSA public keys into the enclave registration record so that the end-users can send encrypted data to specific enclave workers.
We deisgned new RPC interfaces so that user can select a random set of enclave workers and send them encrypted key pieces thru the blockchain.
Our innovation and works leverage decentralized SGX enclave workers but not reinventing the wheel.
Our works are primarily about:
Integration of threshold encryption and distributed enclave workers. Our architecture is designed to enable reliable and decentralized timed-release encryption effectively.
Enclave runtime to hold and release encryption key in a threshold way.
Integration of Network Time Security Protocol in enclave runtime to achieve time security.

**Comment by keeganquigley** [comment]
Thanks for the answers @kaisuki I will mark the application as ready for review so others can take a look and comment as well.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. I have a couple of questions:

- Could you add additional technical details to the milestone delivery tables, like, for example, the programming language? 
- One concern I have here is that the application is quite specific to your project, and you plan to have your own token for it. See also our guidelines: “We do not award grants for projects that have been the object of a successful token sale.” Could you comment on this?

**Comment by kaisuki** [comment]
Thank you very much for your comment @Noc2, I have updated my markdown doc, please check it out, in addition our project does not serve in the token sale, and our tokens are only used for the implementation of our key-holder function, not for circulation.

**Review by Noc2 — CHANGES_REQUESTED** [review]
What do you mean with `"does not serve in the token sale" `? Also to me at the moment it looks like this work is covered by your [whitepaper here](https://onedrive.live.com/view.aspx?resid=BEF98A7CB59E1060!111488&ithint=file%2cdocx&wdLOR=c0817FD0B-8C86-4C5E-AAFB-C2A5B4F5B1CA&authkey=!AKvaEqPMtuKBCog) and the token that you mention as part of the whitepaper. But I will also ping the rest of the team again to take another look at the application.

**Comment by kaisuki** [comment]
That was written in the whitepaper a long time ago and it caused some misunderstanding. We apologize for that. Our strategy has changed since we applied for Phase 1 in October. Our company is based in the US, where the sale of virtual currency is highly regulated, and several companies have run into trouble. Therefore, we have adjusted our direction and do not publicly sell tokens. At the moment, we do not have any plans for token sales, and our focus is on validating the technical model and creating a closed loop. Thank you.

**Comment by kaisuki** [comment]
> What do you mean with `"does not serve in the token sale" `? Also to me at the moment it looks like this work is covered by your [whitepaper here](https://onedrive.live.com/view.aspx?resid=BEF98A7CB59E1060!111488&ithint=file%2cdocx&wdLOR=c0817FD0B-8C86-4C5E-AAFB-C2A5B4F5B1CA&authkey=!AKvaEqPMtuKBCog) and the token that you mention as part of the whitepaper. But I will also ping the rest of the team again to take another look at the application.

**Comment by kaisuki** [comment]
> What do you mean with `"does not serve in the token sale" `? Also to me at the moment it looks like this work is covered by your [whitepaper here](https://onedrive.live.com/view.aspx?resid=BEF98A7CB59E1060!111488&ithint=file%2cdocx&wdLOR=c0817FD0B-8C86-4C5E-AAFB-C2A5B4F5B1CA&authkey=!AKvaEqPMtuKBCog) and the token that you mention as part of the whitepaper. But I will also ping the rest of the team again to take another look at the application.

That was written in the whitepaper a long time ago and it caused some misunderstanding. We apologize for that. Our strategy has changed since we applied for Phase 1 in October. Our company is based in the US, where the sale of virtual currency is highly regulated, and several companies have run into trouble. Therefore, we have adjusted our direction and do not publicly sell tokens. At the moment, we do not have any plans for token sales, and our focus is on validating the technical model and creating a closed loop. Thank you.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update here. I shared your proposal again with the rest of the team to also get some additional feedback. In general, something to be aware of is that the grants program shouldn't be the only funding tool for projects that potentially have other business models. So even if you gave up your token sale idea, I still recommend trying to find other funding possibilities besides grants.

**Comment by kaisuki** [comment]
> Thanks for the update here. I shared your proposal again with the rest of the team to also get some additional feedback. In general, something to be aware of is that the grants program shouldn't be the only funding tool for projects that potentially have other business models. So even if you gave up your token sale idea, I still recommend trying to find other funding possibilities besides grants.

[new whitepaper](https://1drv.ms/b/s!AmAQnrV8ivm-h-gXJpFZgbI0srleUA?e=ItUMuQ),We have uploaded the latest version of our whitepaper, please review it for more details. At this stage, our focus is solely on refining our technical model, and we do not have any potential plans for a commercial model. Additionally, our project will be entirely open-source, and we believe it will hold value for other partners in the Polkadot community. We aim to contribute to a safer and more convenient environment for Polkadot.

**Comment by kaisuki** [comment]
> Hi @kaisuki. The `Ecosystem Fit` section of the application is the same as in your previous grant. I'm curious if you have made any adjustments or discoveries since then, especially concerning potential users. Also, could you describe where you are in terms of roadmap and funding, compared to where you were when you applied for the first grant?

Thank you for your question. In the previous application, our goal was to validate the feasibility of our idea at a high level. In the upcoming application, we will focus on refining the technical details based on the foundation we have established. This includes aspects such as key slicing and key restoration, cross-chain timestamp retrieval, and developing a user-friendly toolchain for encrypted communication aimed at Web2 users. There is still significant foundational technical work that needs to be done.

**Comment by kaisuki** [comment]
> Thanks for the update here. I shared your proposal again with the rest of the team to also get some additional feedback. In general, something to be aware of is that the grants program shouldn't be the only funding tool for projects that potentially have other business models. So even if you gave up your token sale idea, I still recommend trying to find other funding possibilities besides grants.


I apologize for any confusion caused by our previous communication. Let me clarify the situation: We had prepared the whitepaper a long time ago and successfully used it to apply for [Phase 1](https://github.com/w3f/Grant-Milestone-Delivery/pull/724). During [Phase 1](https://github.com/w3f/Grant-Milestone-Delivery/pull/724), the members of the Web3 Foundation provided us with significant technical advice and assistance, which helped us avoid many pitfalls and achieve the [Phase 1](https://github.com/w3f/Grant-Milestone-Delivery/pull/724) milestone. As a result, we have decided to apply for Phase 2 based on the progress made in Phase 1. Throughout the period between applying for [Phase 1](https://github.com/w3f/Grant-Milestone-Delivery/pull/724) and now, we have not engaged in any token sales, and our future focus remains on further refining our technical model. Token sales have been excluded from our roadmap. Thank you for your understanding.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update here, and sorry for the late reply. I'm personally still not convinced about this application. Partly also because there is no activity at the moment in your repos: https://github.com/NexTokenTech, and the grants program shouldn't be the only one funding the project, but I will share the application again with the rest of the team. Maybe someone else is interested in supporting it.

**Comment by semuelle** [comment]
Since this application hasn't garnered any approvals by the committee and there hasn't been any progress in two weeks, I am going to close it now. Thanks again for the applicaction, @kaisuki. Best of luck going forward and feel free to apply again down the road!

**Pull request closed without merging**
