### PR TITLE
DevPool by Ubiquity DAO v0.1

### PR DESCRIPTION
**Pull request by sergfeldman**
#### Project Abstract

DevPool is a crypto-native platform that organically sits on top of GitHub to optimally match developers with open tasks and get paid in crypto while automating the administrative components for DAOs and Repo managers.
https://github.com/ubiquity/

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@rser:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for your interest in our grants program. I know this is still in the draft status, but I just want to provide already some feedback here. The most important part of the application is usually the milestone tables of our template, including the default deliverables. Also ideally the deliverables are included in the application itself (=contract) and not in a linked document. Apart from this, I recommend including Polkadot-specific technical deliveries and integration.

**Comment by sergfeldman** [comment]
> Thanks for your interest in our grants program. I know this is still in the draft status, but I just want to provide already some feedback here. The most important part of the application is usually the milestone tables of our template, including the default deliverables. Also ideally the deliverables are included in the application itself (=contract) and not in a linked document. Apart from this, I recommend including Polkadot-specific technical deliveries and integration.

@Noc2 Hello, great thank you for the valuable feedback!

**Comment by Noc2** [comment]
Thanks. Let me know once I should take another look at the application.

**Comment by Noc2** [comment]
I'm closing the application due to inactivity. Let me know if I should reopen it.

**Comment by sergfeldman** [comment]
> I'm closing the application due to inactivity. Let me know if I should reopen it.

Yes, this draft PR should be closed. We'll create a new one when we're ready. Thank you!

**Pull request closed without merging**
