### PR TITLE
Proposal: Storage solution on Polkadot

### PR DESCRIPTION
**Pull request by dtuzi**
Create proposal

#### Project Abstract

The main goal is to implement and maintain a Filecoin-like system parachain that uses DOT as the native token and is easily usable for all kinds of parachain projects in the ecosystem via XCM.
To accomplish this we are submitting this initial proposal to update our[ previous research](https://github.com/common-good-storage/report/blob/master/src/first.md) and test how XCM could be used to allow the ecosystem to use this storage network.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — APPROVED** [review]
Thanks a lot for the application. I'm happy to go ahead with it and share it with the rest of the team.

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/referendum-234-data-availability-retroactive-funding-and-on-chain-invoices/3421/42

**Review by semuelle — CHANGES_REQUESTED** [review]
Thanks for the application, @dtuzi. Could you update the spec of `0d`? It's currently the template text. In fact, given that you are planning to deliver code as well, it might make sense to include the default deliverables of our [regular application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) instead, such as a testing guide.

Also, given that you are planning to apply for another grant to build the project, could you expand on the extent of the MVP you are planning to deliver in this one?

**Comment by dtuzi** [comment]
@semuelle I updated the deliverable spec and extended the explanation per your request, let me know if there's anything else that can be improved

**Review by semuelle — APPROVED** [review]
Thanks for the updates, @dtuzi. LGTM.

**Review by Noc2 — APPROVED** [review]

**Review by laboon — APPROVED** [review]

**Pull request merged**
