### PR TITLE
RV KMIR Grant

### PR DESCRIPTION
**Pull request by ehildenb**
#### Project Abstract

We seek to develop **KMIR: the [K](http://github.com/kframework) semantics of the [MIR language](https://rustc-dev-guide.rust-lang.org/mir/index.html)**, which is an [internal representation for the Rust compiler](https://blog.rust-lang.org/2016/04/19/MIR.html). This will enable more scalable verification for the Rust programming language. A robust commitment to security and assurance does not end with a completed security audit (which we have experience doing for various Rust-based projects). Rather, it requires that all available tools and techniques are used, including rigorous proof-based formal verification (among others). Supporting the development of the KMIR semantics will enable verification at scale for smart contract developers targeting the Polkadot (and related) ecosystem.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [ ] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by ehildenb** [comment]
The provided link to grants guideline does not exist?

**Comment by semuelle** [comment]
Thank you for your application. We will look into it as soon as possible!

> The provided link to grants guideline does not exist?

Thanks for the notification. I fixed the links in your PR.

**Review by Noc2 — CHANGES_REQUESTED** [review]
see email

**Comment by Noc2** [comment]
I’m closing this due to inactivity. Let me know if you want to re-open it.

**Comment by ehildenb** [comment]
@Noc2 please re-open, I've since made the changes asked for, including:

- Updating the template, and
- Reducing the projcet size.

**Comment by Noc2** [comment]
@ehildenb Thanks for pinging me. That is great to hear, but I can not reopen the PR. I get the following message: 
Screenshot 2023-01-09 at 17 18 16
Could you create a new PR?

**Comment by ehildenb** [comment]
Done: https://github.com/w3f/Grants-Program/pull/1422

**Comment by Noc2** [comment]
Thanks!

**Pull request closed without merging**
