### PR TITLE
Addition of Health Hero's Web-3 Grant Submission

### PR DESCRIPTION
**Pull request by emailnjv**
# Grant Application

## Abstract

The NFT Product Analytics Suite will aggregate various data points both off and on chain to provide NFT minters the metrics they need to use to decide how to best serve their target audience. This will include tracking the transfers of the user's minted NFTs, when and how much they are being sold for, and price trends. We will also aggregate the meta data associated with a given NFT to see the effectiveness of various gamification methods. With this data being tracked, you will be able to compare your NFTs to other leading projects and artists to see what the difference is and how to better target end users.

## Checklist

- [x] The [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] The total funding amount of the project is below USD $30k for first-time grant applications and $100k for follow-up ones.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

### CODE REVIEW

**Comment by alxs** [comment]
Hi @emailnjv. Thank you for your application. We'll review it as soon as possible, in the meantime I have the following initial remarks:

- Please edit your comment to provide an abstract and tick the last item of the application checklist.
- Deliverables 0a-0d are mandatory for all milestones, and deliverable 0e at least for the last one as indicated in the [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#development-roadmap-nut_and_bolt).
- Besides, deliverables need to be quantifiable, potentially useful to other teams and not already present in the ecosystem. I.e. we won't fund things like deliverable 5 of M2 "With all of the metrics in hand, we'll start computing the metrics to formalize the insights that we'll offer on our platform". They also need to be much more well-defined and explicit, i.e. deliverable 1 of M1 "creating the various structs for the needed data structures and ERC standards." is not a suitable specification.
- Please include more technical details, such as which languages or frameworks you'll be using for each deliverable.
- Please indicate which projects you'll be basing your work off of (re "previously Web-3 funded project").
- All deliverables should be related to Polkadot/Kusama/Substrate (re "Implementation of an Ethereum chain indexer").
- Please provide a technical specification of the data you want to index and the insights you want to provide. It currently seems all a bit too "up in the air" to me.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Just three additional comments from my side for now:

- Regarding existing projects, you should take a look at https://github.com/w3f/Grants-Program/blob/master/docs/polkadot_stack.md#wrench-tools-apis-and-languages (see Blockchain Indexing Engine). Maybe you could reuse some of these projects. 
- Is the substrate indexer for ink! Smart contracts or pallets? 
- Regarding “Ethereum Based Chain Indexer”, I guess a indexer specifically for https://github.com/paritytech/frontier or the [Acala evm](https://github.com/AcalaNetwork/Acala/tree/master/modules/evm) would be more useful for us

**Comment by emailnjv** [comment]
@alxs @Noc2 Thanks for quickly getting back to us. We'll review the comments, and update the submission as soon as possible.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. I would be willing to go ahead with milestone 1. However, milestone 2 is currently really specific to enjin/Efinity and it seems that Efinity isn’t open source. Correct me if I’m wrong here. Therefore, I don’t think that the Web3 Foundation should support it at the moment, since we would basically support one specific closed sourced product this way (and ignore other solutions like Unique Network). In this case my recommendation would be to either remove milestone 2 for now or to make it more generic. Sorry for not bringing this up before.

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I’m happy to go ahead with it and will share it with the rest of the team.

**Review by gautamdhameja — APPROVED** [review]

**Comment by emailnjv** [comment]
@alxs @Noc2 @mmagician

Hi everyone, just wanted to give you guys an update on our progress. Currently, wrapping up the final two tasks for milestone 1. We are aiming to have submitted following the guidelines around mid-day Tuesday. We wanted to show you guys a mockup of our first iteration of how we envision the project admins dashboard. We would love to hear your thoughts.

web3 dash

**Comment by alxs** [comment]
Hey @emailnjv, thanks for the update, it's appreciated. We look forward to receiving the milestone and good work on the mock-ups. I'm personally more curious about the back-end, but it looks great.

**Comment by emailnjv** [comment]
@alxs @Noc2 @mmagician Hi everyone, just wanted to update you guys again. Over the weekend I ran into a bit of a bottleneck regarding the last two steps for milestone 1, and am still working on it. I will update you everyone here again once I've worked through the issues.

**Pull request merged**
