### PR TITLE
Changes in BrightTreasury Milestone 3 scope

### PR DESCRIPTION
**Pull request by bufta**
There is a need to amend the current grant proposal. When we sent our proposal earlier this year, the bounties module was evolving and we decided to include also the sub-bounties mechanism that was planned for development. Unfortunately, the sub-bounties haven’t been implemented yet, which means that we need to exclude the user stories connected to them from the proposal. They were just additional elements and the planned app flow doesn’t have to change, so we just removed the user stories that applied to the sub-bounties only and edited the stories that mentioned them as well. What we propose to be included instead of the sub-bounties is to prepare and deploy to production Milestone 1 and Milestone 2, which already cover the Proposals flow. We feel it might be beneficial to allow users to use the app already, get the feedback and start to promote it within the community as plan to maintain the app beyond the current grant. We would love for the BrightTreasury to become an important part of the community, a living and useful tool that increases the Treasury activities. Going to production earlier might contribute to this goal.

### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Comment by alxs** [comment]
Thanks for the amendment @bufta. It doesn't look like deliverables 16-18 are related to sub-bounties, did you perhaps remove them by mistake?

**Comment by bufta** [comment]
> Thanks for the amendment @bufta. It doesn't look like deliverables 16-18 are related to sub-bounties, did you perhaps remove them by mistake?

We changed the numbering of the deliverables and user stories so they'd be numbered in a consistent and continuous manner. Sorry if it turned out to be confusing, we can edit it so the previous numbers would be kept. We removed deliverables number 11, 12 and 13 from the previous version as they referred to sub-bounties only.

**Comment by semuelle** [comment]
Seems reasonable to me. Only I don't understand why User Story 39 was replaced; was that on purpose? It seems to me like that should still be implemented.

**Comment by bufta** [comment]
@semuelle thank you for your feedback. Indeed, User Story 39 was removed by accident. I'm updating the file, apologies for the confusion.

**Review by semuelle — APPROVED** [review]

**Review by alxs — APPROVED** [review]

**Review by Noc2 — APPROVED** [review]

**Pull request merged**
