### PR TITLE
Tracking Chain Amendment for milestone 4

### PR DESCRIPTION
**Pull request by FedeC87p**
#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [X] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [X] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [X] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) or BTC address in the application).
- [X] The software delivered for this grant will be released under an open-source license specified in the application.
- [X] The initial PR contains only one commit (squash and force-push if needed).
- [X] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by FedeC87p** [comment]
Unfortunately I am forced to remove this:
- Frontend Registry: Improvement that allows you to view not only the data present in the Registry but also to take directly from the data saved in the onchain smart contract  

It was supposed to be a simple development that displayed the data in the frontend part, but the SubstrateGaming library does not support the "ContractsApi_call" call needed to display this data.
Since it is not a core requirement for my application and since it takes a long time to develop, I have decided that I will try to implement this functionality by including it in "SubstrateGaming" later and without using the Grant program.

**Comment by FedeC87p** [comment]
I have read and hereby sign the Contributor License Agreement.

**Review by semuelle — APPROVED** [review]
Thanks for the amendment, @FedeC87p. LGTM.

**Review by keeganquigley — APPROVED** [review]
Thanks for the update @FedeC87p looks good.

**Review by takahser — APPROVED** [review]

**Pull request merged**
