### PR TITLE
Polkawatch Proposal

### PR DESCRIPTION
**Pull request by rvalle**
### Project Abstract

Polkawatch will provide decentralization analytics about Polkadot. Allow all stake-holders to gain insights about where network activity is taking place (regional, network provider, validator group, nominator segment, etc).

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed (`Polkawatch.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. This is indeed something we are very interested in. Could you maybe add a few more technical details to specification of the milestones (for example programming language of the deliveries)? Otherwise it looks good to me and I’m happy to support it.

**Comment by rvalle** [comment]
@Noc2 let me know if you need further details.

**Review by Noc2 — DISMISSED** [review]
Additional details are always welcome, but I’m happy to already approve it and share it with the rest of the team.

**Comment by rvalle** [comment]
> Additional details are always welcome, but I’m happy to already approve it and share it with the rest of the team.

@Noc2 noted. I added some more details to the deliverables.

**Review by Noc2 — DISMISSED** [review]

**Comment by takahser** [comment]
@rvalle thanks for the proposal, this looks very interesting to me.
One small thing: Unfortunately, the LinkedIn link seems to be broken (https://www.linkedin.com/rvalle).

**Comment by rvalle** [comment]
@takahser thanks for spotting it. 
Now updated the linkedin profile url

**Review by alxs — CHANGES_REQUESTED** [review]
Happy to support this too. The links to the mock-ups on IPFS seem to be broken, could you fix those? You can just paste an image into the document and it will be hosted on GitHub. Also, what would be the extent of the changes required to deploy this for a different chain?

**Comment by rvalle** [comment]
@alxs thanks for the attachment tip, I have moved the diagrams from IPFS.

Support for other Substrate chains will depend on the pallets used at the new chain. Depending on those the indexer will find the required extrinsics and events when indexing the chain.

For Polkadot we trace Heartbeats  to Validator (using session keys) to Payout and to Regards and cross with external databases.... so that we can aggregate all the information related to that reward, which can be considered the unit proportional to decentralized computation to analyze.

Kusama works the same way, at it is the canary network for Polkadot and there are some difference in Era lengths but the validation/rewards are similar.

In the worst case scenario in which a different Substrate chain is indexed, another event, representative of computing activity would be selected, the indexer project would be different but would also return a single document with all desired data. The live query server would have other templates for the required filters/aggregations that the DAPP UI would probably need changes that reflect the actual structure of that blockchain.

I think the architecture would work for different blockchains, but the level of change required would depend of how different the set of pallets is.

**Review by Noc2 — APPROVED** [review]

**Review by gautamdhameja — APPROVED** [review]
LGTM!

**Review by alxs — APPROVED** [review]
Thanks for the details. In that case, I'll just mention that the infrastructure costs are something both the Polkadot and Kusama treasuries would likely be happy to cover. Let us know if you need any pointers or would like to be introduced when the time comes.

**Comment by rvalle** [comment]
How fast! Fantastic.
We are really looking forward to contributing to this great ecosystem!

**Comment by hakan-w3f** [comment]
Hi @rvalle, quick question: Following a `yarn install`, a `yarn test:e2e` works but `yarn test` doesn't, complaining that it cannot find module `@lqs/client`. Please advise. Thx

**Pull request merged**
