### PR TITLE
grant proposal for substrate-tutorials

### PR DESCRIPTION
**Pull request by tdelabro**
### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

We are a company that bring new developers to the ecosystem, training them and finding them position. To do this we started to build our own tutorials in order to shorten the training time of new substrate developers. We got lot of positive feedback about this so we open sourced it and we got even more positive feedback, so we would like a grant to make it better and more complete and involve the ecosystem on it.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying?

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] I have read and understood the [FAQs](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md), [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md) and [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md).
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] Hackathon
- [ ] Personal Recommendation
- [ ] Substrate Builders Program
- [ ] Investor/VC
- [ ] Online Search
- [x] Other: talking to people on the ecosystem (clients and partners)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. In general, something to be aware of, we mostly focus on open source software development and research with our grants program and usually don’t support projects that only focus on teched. However, in this case, you also make a lot of code open source. So I guess we could fund milestone 1 and 2. And potentially after this we could involve the treasury and ask them to support the videos plus potential additional work. Would this be an option for you? If so could you remove milestone 3 for now?

**Comment by tdelabro** [comment]
> So I guess we could fund milestone 1 and 2. And potentially after this we could involve the treasury and ask them to support the videos plus potential additional work. Would this be an option for you? If so could you remove milestone 3 for now?

Yeah totally, it was added because we though it would make sense as a extension of the project. But it's really more an add-on.
We will remove it for now

**Review by hakan-w3f — APPROVED** [review]
Hey @tdelabro , I'm looking forward to watching your videos, and following your tutorials.

**Comment by alxs** [comment]
Hey @tdelabro, any updates on the second milestone? Unless you plan to deliver soon, could you please submit an [amendment](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval) with an updated timeline?

**Comment by alxs** [comment]
Makes sense, thanks for the update! You too have a nice day.

**Comment by tdelabro** [comment]
Two new exercises were added this weekend :)
On weights and imbalances

**Comment by tdelabro** [comment]
@keeganquigley Yep exactly. 
I pushed one more exercise last month, and I only have two more to go: mock (make the student write a mock for an existing pallet) and offchain worker, which should be fast as I was using them recently for another project.

Let's say it will be ready in two more weeks, at the end of April. Ready for a first review.
Wdyt?

**Comment by tdelabro** [comment]
https://github.com/w3f/Grant-Milestone-Delivery/pull/860
Here is our submission PR for the second milestone :)

**Pull request merged**
