### PR TITLE
Application: Sub-concensus mechanism

### PR DESCRIPTION
**Pull request by AurelienFT**
#### Project Abstract

This application aims to answer to the first milestone of the [RFP sub-consensus mechanism](https://grants.web3.foundation/docs/RFPs/sub-consensus)

> Parachain dApps suffer from long confirmation times due to the time taken for the Relay Chain to issue an on-chain verification of the parachain blocks. This proposal aims at providing an alternative mechanism for providing parachain users with an alternative, probabilistic sub-consensus mechanism.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) address in the application).
- [x] I am aware that, in order to receive a grant, I (and the entity I represent) have to successfully complete a KYC/KYB check.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by AurelienFT** [comment]
I have read and hereby sign the Contributor License Agreement.

**Comment by AurelienFT** [comment]
recheck

**Review by keeganquigley — CHANGES_REQUESTED** [review]
Thanks for the application @AurelienFT 

- Can you specify which payment currency next to your Polkadot address?
- I see the default deliverables (0a. - 0e.) but no main deliverables (1., 2., etc.) could you add at least a research deliverable with concrete details on how we would evaluate the outcome?
- What will be produced as a result of the research? A formal spec, a report, a publication, etc.
- Have you discussed your approach with others, or otherwise examined previous research done in this area?

Thanks for any insights you can provide!

**Comment by AurelienFT** [comment]
Hello @keeganquigley ,

Thank you for reading our proposal. We made the modifications on the proposal to answers your questions in this [commit](https://github.com/w3f/Grants-Program/pull/2218/commits/684fcf9c58d7ba9428b1648a6e5583b99b923475).

Feel free to ask us other questions if needed.

**Review by keeganquigley — CHANGES_REQUESTED** [review]
Thanks for the changes @AurelienFT much appreciated. Just a couple of additional questions:

1. You mentioned that you had done some research related to BFT / PoS based consensus algorithms previously. Could you link to any examples of your previous work?
2. Since you mentioned you have yet to become super familiar with Polkadot ecosystem, what made you interested in this research? Were there any glaring issues in your experience with Massa nodes, for example, that made you realize you were well-suited for this RFP?

In the meantime, I will also cc my colleague @laboon who co-wrote the RFP, in case he is available to take a look. Thanks!

**Comment by AurelienFT** [comment]
Hello @keeganquigley,

We modified the proposal to add a bit more details about our researches and our knowledge at Massa in this [commit](https://github.com/w3f/Grants-Program/pull/2218/commits/844eda1a5e3ea0faa373640f1aa954bd5e7015cd). I hope it answer your two questions.

We are very enthusiastic about this research and we are still open to new questions :)

**Comment by keeganquigley** [comment]
Thanks for including the publications @AurelienFT much appreciated. I will go ahead and mark the application as ready for review and ping the committee to comment.

**Review by semuelle — COMMENTED** [review]
Hey @AurelienFT, thanks for the interest in the RFP and application. 

Given that [coretime](https://www.youtube.com/watch?v=j7b8Upipmeg) is already [live on Westend](https://twitter.com/Polkadot/status/1760027662427574593), I'm curious if you have considered it in your preliminary research. The RFP was written before coretime was thought up, so I'm not sure the approach is still applicable once coretime moves to Kusama and Polkadot.

**Comment by AurelienFT** [comment]
Hello @semuelle !

We hadn't considered coretime during our initial research. We mainly based it on the RFP, the current code, and the Polkadot [Parachain Host Implementers' Guide](https://paritytech.github.io/polkadot-sdk/book/index.html).

Coretime seems to focus on the management of the allocation of parachains to the relay chain (from the current long-term auction system to a more flexible long-term and short-term market approach). The RFP states: "note that this sub-consensus on parachains will have no effect on the decision of relay chain validators' votes". From our understanding, as the sub consensus should not have a direct impact on the Relay chain, the sub consensus proposal would be both still needed, and not impacted too heavily by these changes.

However, we are not fully aware of what the impacts could be.
We would gladly include the constraints of coretime into the Milestone 1 of this RFP. In that case, it would help greatly to be put into contact with the coretime team to get a better view of how it impacts the current protocol.

**Comment by AurelienFT** [comment]
Hello,

It's been weeks and we didn't had feedback on this. Can you update update us on the current status that you have assign to our proposal please ?

**Comment by semuelle** [comment]
Hi @AurelienFT, sorry for the long radio silence. Unfortunately, we cannot facilitate access to core devs. Also, our research team suggested closing the RFP as elastic scaling will require a different sub-consensus mechanism as outlined in the RFP.

I will bring up your proposal with the committee again asap to see what the best way forward is.

**Review by semuelle — APPROVED** [review]
Sorry for the long wait, @AurelienFT. A rewrite of the RFP might take some time, so in the meantime I think we should go ahead with your proposal. I'll share it with the rest of the committee now.

**Review by Noc2 — APPROVED** [review]
Thanks for the application. Looks good to me.

**Review by keeganquigley — APPROVED** [review]
Thanks for the changes @AurelienFT LGTM

**Comment by semuelle** [comment]
@AurelienFT, could you fill out the [KYB form](https://in.sumsub.com/idensic/l/#/uni_JRqwo72Y5AjXaRDO) (assuming you are applying as an entity, otherwise have every benefactor use [this form](https://in.sumsub.com/idensic/l/#/uni_mjcB05gJZfh8dbr7), please)?

**Comment by keeganquigley** [comment]
Hi @AurelienFT are you still working on this grant? It's been open for a year now and we haven't seen any deliveries from you. Thanks for any updates you can provide.

**Comment by keeganquigley** [comment]
Hi @AurelienFT please let us know if you are still working on this grant. Otherwise we will close it in a few weeks due to inactivity. Thanks.

**Comment by AurelienFT** [comment]
Hello,
I'm not working at this company anymore I informed them. Ty for closing

**Comment by keeganquigley** [comment]
Thanks for the update @AurelienFT sounds good, will do.

**Pull request merged**
