### PR TITLE
add imbue network grant application

### PR DESCRIPTION
**Pull request by samelamin**
### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Comment by semuelle** [comment]
Thank you for the delivery. We will look into it as soon as possible.

In the meantime, could you expand the specification of the deliverables a bit? Our [FAQ](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md#-general) (see `What activities/positions do you fund?`) and [grant category guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md) might be of help.

**Comment by samelamin** [comment]
@semuelle thanks, happy to flesh it out a bit

Do you mean adding method signatures to the pallets we are proposing among the other requirements [here](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md) ? 

or if not maybe you can point out to what else is missing?

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Could you update the costs, so it’s clear how much funding you want to receive per milestone? If I understand correctly you are not applying for 150k but only for 50k. Although I have to say that 60k is a lot of a single pallet (milestone 1) or will you also deliver a UI as part of this milestone? Currently it says “We will hire a front end dev to implement a DAPP to display proposals which have been stored onchain”, which is hard to evaluate for us and only means that you will hire someone to work on it, as far as I understand it. Furthermore how is the Democracy pallet different from existing implementations like the on-chain treasury?

**Review by Noc2 — CHANGES_REQUESTED** [review]
Regarding the UI, do you already have some mockups or could you share more information about it (programming language, etc.)? Regarding reusing the [Democracy Pallet](https://github.com/paritytech/substrate/tree/master/frame/democracy) and potentially the [Treasury Pallet](https://github.com/paritytech/substrate/tree/master/frame/treasury), it would be nice to have more details about the scope before we sign the grant. So, the milestone delivery doesn’t end up to be a slightly changed treasury and democracy pallet.  Also feel free to remove Kusama or Polkadot launch from the deliveries, since this is something we can not influence and we usually only focus on the open source code and not things like deployment. Furthermore, “Refine the UI based on feedback from the previous rounds.”, is also quite hard to define. For example we could complain about a lot of things during the milestone delivery process, which would require a complete redesign of the UI.

**Comment by samelamin** [comment]
Thanks for the useful feedback, this is great please keep them coming! 

1) The UI mockups can be found here. They are also added  to the grant
```
- https://github.com/ImbueNetwork/website-assets/blob/main/templates/new-project.jpg
- https://github.com/ImbueNetwork/website-assets/blob/main/templates/project-details-page.jpg
- https://github.com/ImbueNetwork/website-assets/blob/main/templates/projects.jpg
```

2) Added more details regarding the flow. My thinking for V1 is we can initialise a vote via the democracy pallet for proposals/milestones and have the treasury payout, each of these actions will be initialised/approved by a council. That would reduce the need for rework and redesigning the wheel. But eventually, I want the milestones voted on by the DAO and not require a council at all

3) Removed Kusama/Dot launches

4) I have removed it. That said Ideally, I want this to be community-driven, hence the public board. I wanted it to be on the milestone to communicate the fact that we are committed to listening to feedback from day 1, even if it means redesigning the UI to what is seen best by the community. I very much would like a way of demonstrating that commitment publicly

**Comment by samelamin** [comment]
@Noc2 let me know if the changes require further details

**Comment by alxs** [comment]
@samelamin I have to agree with David here, this just sounds very similar to treasury + democracy. You could just combine these pallets, tweak them a little bit and you'd be done. While I like the idea, to be honest I think the deliverables themselves aren't all that interesting and I'm sorry to say I likely won't approve this. In any case, you should probably completely remove milestone 3 and I also suggest you remove the token name from the application, since the focus should lie on the technical implementation.

**Comment by samelamin** [comment]
> @samelamin I have to agree with David here, this just sounds very similar to treasury + democracy. You could just combine these pallets, tweak them a little bit and you'd be done. While I like the idea, to be honest I think the deliverables themselves aren't all that interesting and I'm sorry to say I likely won't approve this. In any case, you should probably completely remove milestone 3 and I also suggest you remove the token name from the application, since the focus should lie on the technical implementation.

@alxs thank you for the feedback. I appreciate your point of view and perhaps the fact that I am creating a token means I should not be applying for a grant


I am happy to close this grant application if @Noc2 also feels the same as you


We were planning to build this out whether we got the grant or not as we feel the polkadot ecosystem has a funding problem.  Statemint will go a long way to resolve this for now but as far as I am aware there is still no clear way for a new project to get funding outside VCs. There is also the governance element that is missing from the ecosystem both of which are what we are trying to solve here. 

The value I was hoping to receive from the grant is not the $50k but the feedback to ensure this is built in the right way which benefits the ecosystem as a whole

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. I definitely think the UI is worth receiving funding and also potentially changing the pallets and adapting this makes sense in my opinion. How about you remove milestone 3 for now and we only fund milestone 1 + 2 for 15k each? So 30k in total. This way we also see what exactly you are going to change and are able to provide feedback and we can always sign additional follow-up grants later or amend the contract in case the scope changes.  Btw. Are you going to use react for the UI?

**Comment by samelamin** [comment]
> Thanks for the update. I definitely think the UI is worth receiving funding and also potentially changing the pallets and adapting this makes sense in my opinion. How about you remove milestone 3 for now and we only fund milestone 1 + 2 for 15k each? So 30k in total. This way we also see what exactly you are going to change and are able to provide feedback and we can always sign additional follow-up grants later or amend the contract in case the scope changes. Btw. Are you going to use react for the UI?

Hi @Noc2 I removed milestone 3. Happy with the $30k total.

The plan was to use a mixture of Node and Typescript for the UI but happy to build it out in React. This really just depends on whether we can find the resources. That said, I am confident we can get a react resource in

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I will share it with the rest of the team.

**Review by BenWhiteJam — APPROVED** [review]

**Comment by samelamin** [comment]
Thank you @BenWhiteJam @Noc2 for your approvals!

If you don't mind me asking, the template says I need 3 approvals but the PR says I need 5

Did I perhaps make a mistake in the PR?

**Comment by Noc2** [comment]
No, GitHub only allows you to adjust the number of approvals based on the branch and not per PR. We will merge it manually after 3 approvals.

**Comment by semuelle** [comment]
Hi @samelamin, thanks again for the application. I finally had time to review and, while I agree with David and Aleixo that there is quite an overlap with existing pallets, I also think the project might be very useful if done well. I have some questions:

- Why a parachain? Have you considered writing this in `ink!`?
- Who holds IMBU tokens? Do I get tokens for providing funds?
- What does the voting mechanism look like? Does each vote require a quorum, or is it simple majority? Are the tokens locked for submitting/supporting a proposal or voting on a milestone? Or is there any way to prevent a single whale from blocking anything that's not in their interest, like conviction voting?
- Have you considered wrapping all this functionality under a DAO framework and allowing others to start their own (possibly specialised) funding DAO (a community of communities, if you will)? Perhaps in a way that would allow DAOs to share the cost of a grant?

Other than that, some features (beyond this grant) I'm sure you have already thought about, but that I would find useful to have:

- Allow modifying milestones after grant approval (speaking from experience),
- more structure around a project (deliverables, deadlines, etc.),
- a forum on each project for people to discuss and voice their opinion,
- use data from identity pallet to de-anonymise applicants/grantees,
- a reputation system (e.g. `Applicant has successfully delivered two projects previously`)

**Comment by samelamin** [comment]
> Hi @samelamin, thanks again for the application. I finally had time to review and, while I agree with David and Aleixo that there is quite an overlap with existing pallets, I also think the project might be very useful if done well. I have some questions:
> 
> * Why a parachain? Have you considered writing this in `ink!`?
> * Who holds IMBU tokens? Do I get tokens for providing funds?
> * What does the voting mechanism look like? Does each vote require a quorum, or is it simple majority? Are the tokens locked for submitting/supporting a proposal or voting on a milestone? Or is there any way to prevent a single whale from blocking anything that's not in their interest, like conviction voting?
> * Have you considered wrapping all this functionality under a DAO framework and allowing others to start their own (possibly specialised) funding DAO (a community of communities, if you will)? Perhaps in a way that would allow DAOs to share the cost of a grant?
> 
> Other than that, some features (beyond this grant) I'm sure you have already thought about, but that I would find useful to have:
> 
> * Allow modifying milestones after grant approval (speaking from experience),
> * more structure around a project (deliverables, deadlines, etc.),
> * a forum on each project for people to discuss and voice their opinion,
> * use data from identity pallet to de-anonymise applicants/grantees,
> * a reputation system (e.g. `Applicant has successfully delivered two projects previously`)


Hi @semuelle thanks so much for the feedback
 * Why parachain ->. because I wanted it to be its own blockchain and utilise statemint as well as communicate to other chains to facilitate future integrations/partnerships. for example, accepting KUSD/USDC/USDT or any other currencies
* Anyone who wants to fund future projects. Anyone that wants to be part of the DAO. We are considering using some incentives for you voting using your IMBU by rewarding you some more, a form of staking to incentivise people to vote
* For MVP I was thinking of simple majority, but as soon as MVP is done we can take feedback from the community on how to run votes in future. We prevent a whale by only allowing the funders to vote on milestones. in other words you are only a whale in terms of how much you funded, and if you are then you deserve the most say as you are at risk of losing the most
* We certainly want to become a DAO so anything that helps with that goal is considered. One for potential milestone 3? 
* All these features are amazing and we definitely did not think of some of them. This is exactly why I wanted the grant, to be able to discuss features like this. This can also be integrated in milestone 3

I love some of these ideas and we will almost certainly want to implement them for milestone 3. My goal is to ensure we deliver the MVP in less than 6 months, my only hesitation about adding some of these ideas - esp the DAO framework - is that they are a known unknown. I.e I am concered it might delay a release

Is it unreasonable to add them to milestone 3 or are they a blocker for this grant

**Comment by semuelle** [comment]
> Is it unreasonable to add them to milestone 3? or are they a blocker for this grant

My suggestion would be to expand the description of the pallet deliverables of M1 and M2 to illustrate the differences to existing pallets, and then, where reasonable, add some features. For example, the treasury pallet doesn't allow modification after creation and only includes value and beneficiary address. 

> Anyone who wants to fund future projects. Anyone that wants to be part of the DAO. 

Can you explain a bit more what your plan for the token is? It is the native parachain token, right? Have you considered implementing a DAO-specific token that represents a share in the DAO funds? A separation of concerns might be beneficial here. And will grants be denominated in $, like in the example you provided, or in IMBU? Token-based grants encourage speculation, which is one of the reasons why we started denominating grants in USD.

**Comment by samelamin** [comment]
> > Is it unreasonable to add them to milestone 3? or are they a blocker for this grant
> 
> My suggestion would be to expand the description of the pallet deliverables of M1 and M2 to illustrate the differences to existing pallets, and then, where reasonable, add some features. For example, the treasury pallet doesn't allow modification after creation and only includes value and beneficiary address.
> 
> > Anyone who wants to fund future projects. Anyone that wants to be part of the DAO.
> 
> Can you explain a bit more what your plan for the token is? It is the native parachain token, right? Have you considered implementing a DAO-specific token that represents a share in the DAO funds? A separation of concerns might be beneficial here. And will grants be denominated in $, like in the example you provided, or in IMBU? Token-based grants encourage speculation, which is one of the reasons why we started denominating grants in USD.

Thanks @semuelle I have added more details around the pallets. 

Regarding what currencies we fund, we certainly thought about his because the core utility of the Imbu token is governance

We will eventually build the ability to fund in a stable token but for MVP I wanted to keep it simple enough that you can receive funding in the native Imbu token

However, that said assuming MVP gets built we can iterate over it to add stable currencies. To be clear though I don't want to create a new stable coin and would rather reuse what is already there either in ERC-20 or ones that are substrate native

**Review by semuelle — APPROVED** [review]
Thanks for the update, @samelamin. I would have liked to get a more thorough definition of the pallet structures, but I also understand that this is early in the project and that you don't want to build everything at once. I hope it goes well and we see some exciting new ideas for Milestone 3. :)

**Review by Noc2 — APPROVED** [review]

**Review by BenWhiteJam — APPROVED** [review]

**Comment by samelamin** [comment]
Thank you all so so so much! Really excited to build this!

**Pull request merged**
