### PR TITLE
Etch Grant Application

### PR DESCRIPTION
**Pull request by achhibbar**
### Project Abstract

Etch is software for organizations to make enduring commitments regarding their social responsibility.

An organization’s social responsibility (CSR) can take the form of a wide variety of commitments. These can range from having a diverse workplace to increasing green energy use. It’s easy for an organization to make claims regarding how they’re run, but these often exist only as marketing copy. Etch is software that allows organizations to make socially responsible commitments and have them written indelibly to the blockchain using smart contracts. This will make an organization's stated goals regarding social responsibility transparent and permanent. It will also provide a place for workers to see what an organization stands for.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying?

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] I have read and understood the [FAQs](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md), [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md) and [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).
- [ ] I prefer the discussion of this application to be in a private Element/Matrix channel. My username is: ``@_______``

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] Hackathon
- [ ] Personal Recommendation
- [ ] Substrate Builders Program
- [ ] Investor/VC
- [x] Online Search
- [ ] Other: _______

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the interest in our grants program. We usually require teams to already have done some initial research and have at least a basic mock-up/design of their application before they apply for a grant (basically your milestone 1). Otherwise we don’t really know the deliverables of your second milestone. Therefore, my recommendation would be to first do at least some more initial research and design and after this to update the application accordingly. Apart from that, deliverables 0a-0d of the application template are mandatory for all milestones, and deliverable 0e at least for the last one (see https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md).

**Comment by achhibbar** [comment]
Hi David,

Appreciate you getting back to me so promptly. We'll look at completing the
tasks outlined in milestone 1 and then update the application accordingly.
Do you have any additional feedback regarding the concept of Etch itself?
Also, should I close the pull request for now?

Thanks,
Ash

**Comment by Noc2** [comment]
Hi. Thanks for the quick reply. I will close the PR for now. Let me know if I should reopen it or feel to simply create a new PR, once you are ready. Regarding the application itself, I think it’s a very interesting project and something that we would want to have. I’m not aware of any similar project in our ecosystem. Maybe you can work together with some of the DAO projects, see https://github.com/w3f/Grants-Program/blob/master/docs/polkadot_stack.md

**Comment by achhibbar** [comment]
That's great to hear, we've had good feedback regarding Etch from those
we've done research with also.
We'll crack on with the work and reapply when we're ready.

Thanks,
Ash

**Pull request closed without merging**
