### PR TITLE
add DC

### PR DESCRIPTION
**Pull request by onexie**
#### Project Abstract

- DC: Decentralized Cloud
- DC is a DePIN,We will build a decentralized network infrastructure for developers very convenient to develop decentralized applications with their Web2.0  development experience.And the user experience of using DApps based on DC is just like using the Apps based on Web2.0.
- We provide developers with a complete gRPC interface and client SDK to enable rapid integration with the DC network services for the development of DApps.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) address in the application).
- [x] I am aware that, in order to receive a grant, I (and the entity I represent) have to successfully complete a KYC/KYB check.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [x] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_onexie_:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by onexie** [comment]
Hello, I have already modified our application and added technical details related to the project.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. I will mark the application as ready for review and share it with the rest of team. However, I have some follow-up comments:
- It sounds like you already developed most of the project and only asking us for a payment to open-source the code. Is this correct? 
- We usually only support deliverables that are beneficial for others, so "
The DC network has entered the public testing phase, and anyone can participate." isn't something that we would support.

**Comment by keeganquigley** [comment]
Thanks for the application @onexie I have to agree that since the project is already in the public beta phase, and much of it has been built, it's probably not the best fit for the grants program. This is because we focus on early-stage PoCs that don't exist yet, and I'm not sure that the components would be re-usable for others. 

Additionally, we don't fund Solidity development, since our expertise is mainly in ink! contracts. Therefore for these reasons I'm not going to support this application, but I thank you for the time and effort you put into it, and I wish you the best of luck in finding funding.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the application and all the effort you put into this. The grants committee decided today to close your application, given the reasons above. We wish you all the best for your project, and let us know if you have any questions.

**Pull request closed without merging**
