### PR TITLE
Added requested changes

### PR DESCRIPTION
**Pull request by wstrametz**
Added requested (@alxs) changes - summary: 

### FIAT-on-off-ramp.md (this document):
- Naming  and documentation of methods which are shown in Swagger-UI
- More specific (inline) documentation with external links related Ebics standard
- Removed getBalance because balance is integrated getBankstatements statement

### CODE REVIEW

**Comment by alxs** [comment]
Thanks for the update @wstrametz. I'm not sure how the current wrapper hides the complexities of Ebics, as far as I understand it the only difference is that one can call the API using a json file instead of XML?

Also could you please move the list of changes made to the delivery to the delivery PR?

**Comment by alxs** [comment]
Following up on direct communications I'm sharing this with the committee. I've removed the [list of changes](https://github.com/w3f/Grant-Milestone-Delivery/pull/184#issuecomment-886516970) made to the delivery to facilitate the review of the amendment, hope that's okay. Also linking to the original application for reference https://github.com/w3f/Grants-Program/pull/348

**Review by alxs — APPROVED** [review]

**Review by semuelle — APPROVED** [review]

**Review by Noc2 — APPROVED** [review]
@wstrametz we recently updated the T&C, see https://github.com/w3f/Grants-Program/pull/541. Could you sign the latest version? Otherwise it looks good.

**Comment by wstrametz** [comment]
> @wstrametz we recently updated the T&C, see #541. Could you sign the latest version? Otherwise it looks good.

Hi - just signed the licence - thanks a lot to the whole team for the input and the support!
walter

**Pull request merged**
