### PR TITLE
Infinity Wallet & Web3 Browser Grant Application

### PR DESCRIPTION
**Pull request by InfinityWallet**
#### Project Abstract
Infinity Wallet is an all-in-one multi-chain wallet ecosystem providing a one-stop solution for all a user's payment, DeFi and crypto needs. Along with the first standalone Web3 browser for seamless access to Web3, removing the need for browser extensions. While providing an enhanced user experience and solving many of todays issues within the wallet/web3 space.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [X] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [X] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [ ] The software delivered for this grant will be released under an open-source license specified in the application.
- [X] The initial PR contains only one commit (squash and force-push if needed).
- [X] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by semuelle** [comment]
Hi @InfinityWallet. Thank you for the application! We will look into it as soon as possible.

Just to make sure: are you aware that one of the core [requirements of the grants program](https://w3f.github.io/Grants-Program/docs/Introduction/intro) is that all code produced as part of the grant must be published under open source license and "also not rely on closed-source software"?

**Comment by InfinityWallet** [comment]
> Hi @InfinityWallet. Thank you for the application! We will look into it as soon as possible.
> 
> Just to make sure: are you aware that one of the core [requirements of the grants program](https://w3f.github.io/Grants-Program/docs/Introduction/intro) is that all code produced as part of the grant must be published under open source license and "also not rely on closed-source software"?

Hi @semuelle, we had reached out via email before applying and were informed that while you mostly fund Open Source projects, you are also willing to look into projects that can bring benefit/value to the ecosystem. To protect our users from the pitfalls of being fully open source, we only open source libraries such as for tokens, DApps and smart contracts, to allow for wider contribution and usage.

**Comment by keeganquigley** [comment]
Thanks @InfinityWallet I'm not seeing that you specified a license type. Regarding the code you plan to build for this grant, can you specify what parts would be open-source vs what would stay close-sourced? If it is meant to be closed-source in its entirety, what license were you planning to use?

**Comment by keeganquigley** [comment]
Thanks for your answers @InfinityWallet can you by chance specify the license type(s)?

**Comment by InfinityWallet** [comment]
> Thanks for your answers @InfinityWallet can you by chance specify the license type(s)? Also, deliverables 0a. - 0d. are typically mandatory for every project/milestone.

The software would be closed source, while the mentioned repositories would be open source under the MIT license.

Regarding deliverables 0a-0d mentioned, 0b, 0c and 0d would not be applicable to the proposal as the repositories are not executable software by themselves.

**Review by semuelle — CHANGES_REQUESTED** [review]
> you are also willing to look into projects that can bring benefit/value to the ecosystem. 

I'm not sure what was said, but we are pretty strict with [deliverables being open source](https://w3f.github.io/Grants-Program/docs/Introduction/intro), so you would have to remove any deliverables that won't be open source. For the rest, please indicate if and how they depend on closed-source code.

**Comment by Noc2** [comment]
I'm closing this PR due to inactivity. Let me know if I should reopen it.

**Comment by InfinityWallet** [comment]
Hello @semuelle, open source would be the libraries for assets, contracts and DApps supporting Polkadot. If you are interested in supporting creation of those then we will be happy to integrate them and Polkadot & Kusama into the ecosystem ourselves.

**Comment by Noc2** [comment]
I'm sorry for not getting back to you sooner. You can always apply for a grant for open-source smart contracts/dapps as long as they don't already exist in our ecosystem and are potentially helpful for others.

**Pull request closed without merging**
