### PR TITLE
Add PolkaSign

### PR DESCRIPTION
**Pull request by WannaM**
# Grant Application

## Abstract

> Provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous one, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.
>
> The details should be in the application document that is being added to the repository via this pull request.

## Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] The total funding amount of the project is below USD $30k for first-time grant applications and $100k for follow-up ones.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

### CODE REVIEW

**Comment by semuelle** [comment]
Hi @WannaM, thanks for the application. Could you fix the link to the previous application? It currently points to a milestone delivery.

I might be missing something, but in the most common use case, agreements are private and people are not keen to have their files stored on IPFS, where everyone theoretically has access and they have no way of deleting it. Have you thought about this? Or is your target audience different?

Also, why are only PDFs supported currently? What is missing for me to upload a .txt or .docx file?

**Comment by WannaM** [comment]
Hi @semuelle , thanks for your time.

> Hi @WannaM, thanks for the application. Could you fix the link to the previous application? It currently points to a milestone delivery.
> 
> I might be missing something, but in the most common use case, agreements are private and people are not keen to have their files stored on IPFS, where everyone theoretically has access and they have no way of deleting it. Have you thought about this? Or is your target audience different?

Indeed, normally agreements between normal people are private. In PolkaSign, agreements can be encrypted if needs to be private agreements for sigers. Also, there are needs of public agreements for different orgs like DAO, NGO, and some public orgs. For example, files from gov should be public to all people, and we should know who signed them.

> 
> Also, why are only PDFs supported currently? What is missing for me to upload a .txt or .docx file?

PDF is well spread till now and simple with format, so it's good for the initial version of PolkaSign. While .txt is too simple, only content without formating and .docx is too complex. In future versions of PolkaSign, more and more file types will be supported, not just PDF.

**Comment by semuelle** [comment]
> While .txt is too simple, only content without formating and .docx is too complex.

Can you explain what the technical problem with txt and docx is? I don't understand where and why the system you are proposing is dependent on the filetype.

**Comment by WannaM** [comment]
> > While .txt is too simple, only content without formating and .docx is too complex.
> 
> Can you explain what the technical problem with txt and docx is? I don't understand where and why the system you are proposing is dependent on the filetype.

All the filetypes you mentioned will be supported. In the proposal, you may notice in the draft UI design, the name of the pdf file is blue, which is a link. When you click the file name, you will open the preview of the pdf file in PolkaSign. Of course, as an agreement, there will be complex scenarios, such as all the signers want to modify or change the agreement, and we need to track the differences between versions. For example, those grant applications may be changed or modified after being accepted, which is one kind of agreement. To track the differences, we have to decode files and compare the changes, then show them to signers.

Why does PolkaSign just accept PDF files at the beginning? It's not tech-related, but a project management strategy. You know supporting more features means more development works should be done, and more bugs will exist. In PolkaSign, any filetype can be the first one to be supported, but we just choose PDF as the first one.

**Comment by semuelle** [comment]
Thanks for the reply. I will share the application with the rest of the team.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Looks interesting. Could you integrate unit tests, at least for the ink! Smart contracts? And what tech stack will you use for the front-end, react? Are you also planning to develop a backend or could it potentially even be deployed on ipfs?

**Comment by WannaM** [comment]
> Thanks for the application. Looks interesting. Could you integrate unit tests, at least for the ink! Smart contracts? And what tech stack will you use for the front-end, react? Are you also planning to develop a backend or could it potentially even be deployed on ipfs?

Sure, the unit tests of smart contracts will be included as default. The front-end will use react and it will be hosted with github page at the beginning. IPFS will be considered later.

**Comment by WannaM** [comment]
@Noc2 Unit test is added in deliverables.

**Review by Noc2 — APPROVED** [review]

**Review by semuelle — APPROVED** [review]

**Review by gautamdhameja — APPROVED** [review]

**Comment by alxs** [comment]
@WannaM could you give us an update on your progress? Note that since the first milestone is already very delayed and we previously asked you for an update, if we don't hear from you in the next 2 weeks we will assume you're no longer interested and terminate the agreement.

**Comment by WannaM** [comment]
> @WannaM could you give us an update on your progress? Note that since the first milestone is already very delayed and we previously asked you for an update, if we don't hear from you in the next 2 weeks we will assume you're no longer interested and terminate the agreement.

Hi, @alxs @semuelle sorry for the late reply. We are preparing the documents for delivery. All the development works were done in the past weeks but met an issue of accessing ink contracts.

The submission will be in this week.

**Pull request merged**
