### PR TITLE
MangoSale  Protocol

### PR DESCRIPTION
**Pull request by Mangoboxlabs**
#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (aUSD/USDT) address for the payment of the milestones is provided in the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [x] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@mangoboxlab:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Let me also share it with @dsm-w3f, who evaluated your deliveries. I have some initial questions/comments: currently, your first milestone doesn't contain any front-end deliveries, but it looks like you want to create a UI for this. Could you integrate this UI into the first milestone? It also might help with testing the delivery. Apart from this, could you specify, as part of milestone 2, what exactly "Front-end files" means and what functionality this front-end supports?

**Review by Noc2 — CHANGES_REQUESTED** [review]
Requested additional changes in the private room.

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I'm happy to go ahead with it and mark the application as ready for review.

**Review by dsm-w3f — APPROVED** [review]
My requests made in the private room were achieved in the application. My last suggestion is to stress out the test cases not only in the contract but also in the e2e tests since token auctions are very critical and usual targets for hacking. A pretty complete test suite including acceptance and defect cases is needed. Happy to support the project.

**Review by gautamdhameja — APPROVED** [review]

**Comment by Mangoboxlabs** [comment]
Thanks for all your support, we will try our best to develop this product!

**Pull request merged**
