### PR TITLE
Marco Polo Technologies

### PR DESCRIPTION
**Pull request by armo-dio**
#### Project Abstract

Marco Polo Technologies (MPT) is pioneering the transformation of alternative finance through its innovative web3 infrastructure. Our platform is engineered to facilitate the integration of financial instruments and the creation of alternative finance platforms with real-world assets (RWAs), aiming at creating new private markets, enabling community-driven financial interactions and access to alternative investments. MPT bridges traditional finance with decentralized finance (DeFi) and cutting-edge web3 technologies, bringing a growing set of financial instruments, mechanisms and workflows, for the creation of new digital private markets as well as for SMEs direct use. We are committed to fostering a more inclusive, liquid, and transparent alternative finance market, democratizing access to financial opportunities and empowering a global community of asset owners, investors, and issuers.

Leveraging the robust capabilities of the Substrate framework and the Polkadot ecosystem, MPT introduces financial inclusivity and asset interoperability, for business owners and private investors. Our focus is on building a dynamic and adaptable infrastructure that supports the tokenization of diverse assets and ensures their secure and compliant issuance, management and exchange. We aim at connecting offline to digital asset markets, offering unmatched access and flexibility to SMEs, experienced financial professionals and new market entrants. We are continually expanding our platform capabilities to disrupt the alternative finance landscape, making it more accessible and efficient for people worldwide.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`MPT.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [x] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@[marcopolotechnologies](marcopolotechnologies:matrix.org`)

### CODE REVIEW

**Comment by armo-dio** [comment]
I have read and hereby sign the Contributor License Agreement.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Could you move it to the applications folder? Also, it's easier to link to the PDF instead of uploading it to our repo. Additionally, we usually only support the technical development via our grants program and not the deployment of a chain, or the initial research phase, or anything in regards to tokenomics or the token, unless it's technically unique. Furthermore, how is your solution different from centrifuge and their technical implementation, and in general add as many technical details to the milestone as possible.

**Review by armo-dio — COMMENTED** [review]
Thank you David, changes made. Addressing your initial comments:

**On technical development support:** We are developing and building out an alternative finance runtime layer, and we are going to set up the asset tokenization layer, aimed at improving the protocol for token standards that represent real-world assets and a diverse set of financial instruments and mechanisms that can be attached to RWAs. The MPT chain will be provided to all market participants to operate in a permissioned manner, emphasizing its role in alternative finance and the creation of digital private markets for a diverse set of assets.
**On exclusion of deployment, research phase, and tokenomics:** bur funding request is strictly for the development of technical modules and does not cover these areas. Any mention of tokens within our proposal is solely to describe their functional role within the technical infrastructure we are building, that is essentially to facilitate transactions and governance for all platforms built on it.
**On differentiation from Centrifuge:** MPT distinguishes itself from Centrifuge by concentrating on developing a digital finance hub specifically designed for SMEs and alternative finance businesses. Our protocol aims at supporting the tokenization of a wide array of assets, instruments, and mechanisms, empowering SMEs and non-traditional investor firms to digitize, manage, and exchange their assets with ease. Our primary focus lies on equity instruments and ownership exchanges, aimed at stimulating the creation of new digital markets for SMEs and facilitating alternative finance businesses in tokenizing and democratizing access to their assets to enhance liquidity. Additionally, our unique social network module enables platforms built on our infrastructure to advance financial inclusivity, breaking down traditional barriers to asset access and ownership. This feature is especially beneficial for underdeveloped markets and communities, as well as broadening the investor base to include those previously unable to access alternative investments. Ultimately, our objective is to transition a substantial amount of off-chain activities in the alternative finance sector online, through our alternative finance protocol. In this endeavor, Real World Assets (RWAs) serve as a key to unlocking an array of disruptive features around digital assets, revolutionizing the landscape of alternative finance.

**Review by keeganquigley — CHANGES_REQUESTED** [review]
Thanks for the application and further explanations @armo-dio I have a few additional comments:

- We don't support token sales, and also wouldn't fund the creation of a token. We also don't care too much about the tokenomics aspect, so I would argue that M2 could be removed completely. This would perhaps allow you to reduce the scope to a level 2 grant, which would only require 3 approvals.
- You mentioned that "MPT is a private project and its repositories are kept private". We would require these to be public eventually, since we only fund purely open-source software. If you are unwilling to publish the repos, it wouldn't be a great for our program, I'm afraid.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the application and all the effort that you put into this. However, the grants committee decided today to close your application since it's not a fit for the program (see our comments above). Let us know if you have any other questions.

**Pull request closed without merging**
