### PR TITLE
Application for User Account Access Security in Wallets

### PR DESCRIPTION
**Pull request by ainhoa-a**
#### Project Abstract

This research proposal targets analyzing Polkadot's user-facing security protocols, focusing on complex account generation and access mechanisms, including multi-signatures and proxies. It plans to model and evaluate these processes in popular Polkadot wallets, aiming to identify security loopholes and user lockout scenarios while streamlining authentication and enhancing user experience.

This project will serve as the basis for the Bachelor Thesis of [Carlo Sala](https://github.com/carlosala), who has been working during the last two years at zondax contributing in building and maintaining several Ledger apps in the Polkadot ecosystem. This research will lead him towards completing his degree in Mathematics at [Universtat Autònoma de Barcelona](https://www.uab.cat/).

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) address in the application).
- [x] I am aware that, in order to receive a grant, I (and the entity I represent) have to successfully complete a KYC/KYB check.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [x] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@ainhoa_a:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by PieWol** [comment]
Hey @ainhoa-a , thank you for the application.

I've started a conversation on element 👋

**Comment by semuelle** [comment]
I left some questions in the chat room.

**Review by semuelle — APPROVED** [review]
Thank you for the update, @ainhoa-a. Looks good to me. 
While we wait for more reviews, could you fill out the [KYB form](https://in.sumsub.com/idensic/l/#/uni_JRqwo72Y5AjXaRDO)?

**Comment by ainhoa-a** [comment]
> Thank you for the update, @ainhoa-a. Looks good to me. While we wait for more reviews, could you fill out the [KYB form](https://in.sumsub.com/idensic/l/#/uni_JRqwo72Y5AjXaRDO)?

Thank you  @semuelle I've transferred this to our team to complete it.

**Comment by ainhoa-a** [comment]
Hi @semuelle  we have completed the KYB form :-)

**Comment by semuelle** [comment]
> Hi @semuelle we have completed the KYB form :-)

Thanks for the update, @ainhoa-a, but it looks like the submission wasn't completed.

**Review by keeganquigley — APPROVED** [review]

**Review by Noc2 — APPROVED** [review]

**Comment by keeganquigley** [comment]
Hi @ainhoa-a how is the milestone coming along? I believe it has been due for a few months at this point.

**Comment by semuelle** [comment]
@keeganquigley, please check with Bhargav about this. I believe it was submitted to him some time ago.

**Pull request merged**
