### PR TITLE
Crypto Aegis

### PR DESCRIPTION
**Pull request by CryptoAegis8**
_**Present and defend legitimate and favourable crypto and blockchain projects.**_

### CODE REVIEW

**Comment by CryptoAegis8** [comment]
J'ai lu et signe par la présente l'accord de licence de contributeur.

**Comment by CryptoAegis8** [comment]
recheck

**Comment by CryptoAegis8** [comment]
I have read and hereby sign the Contributor License Agreement.

**Review by semuelle — CHANGES_REQUESTED** [review]
Thanks for the application, @CryptoAegis8. I'm unclear though what it is that you are planning to deliver as part of this grant. Are you planning to analyse projects in the Polkadot ecosystem? Or build a structure for others to do so? Could you review our application template and provide a list of milestones with a list of deliverables? Also, you don't have to provide your banking details, but a DOT payment address and send an email with your banking details to us (as described in the application template).

**Comment by CryptoAegis8** [comment]
Hello Semuelle, 
We plan to analyze projects in the Polkadot ecosystem. We apologize for the lack of clarity. Should we modify our application directly? Or send you a message explaining things in detail? 
We added our wallet number to the application 5 min ago.

**Comment by CryptoAegis8** [comment]
Hello Semuelle,
We plan to analyze projects in the Polkadot ecosystem. We apologize for the lack of clarity. Should we modify our application directly? Or send you a message explaining things in detail?
We added our wallet number to the application 5 min ago.

**Comment by semuelle** [comment]
Hi @CryptoAegis8, thanks for the clarification. You can make changes to the application document directly, like you did, so everyone from the grants committee has access to it. 

That being said, the Grants Program focuses on open source software development and research, and your proposal doesn't seem to fit either. See our [guidelines](https://grants.web3.foundation/docs/Introduction/intro), [grant categories](https://grants.web3.foundation/docs/Support%20Docs/grant_guidelines_per_category) and application templates ([standard](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md), [research](https://github.com/w3f/Grants-Program/blob/master/applications/application-template-research.md)). I think applying with the [treasury](https://grants.web3.foundation/docs/funding) makes more sense here.

**Comment by CryptoAegis8** [comment]
Hello, Do you think it would be possible to get a contact (e-mail address) to present our project/grant application to you, given that it's really specific and has more to do with a form of "certification" of crypto projects (in order to increase the trust and security of the network) rather than the creation of a crypto project for the Polkadot ecosystem? It is indeed complex to fill in the treasury form, so specific does our request seem to be.

**Comment by CryptoAegis8** [comment]
> Hi @CryptoAegis8, thanks for the clarification. You can make changes to the application document directly, like you did, so everyone from the grants committee has access to it.
> 
> That being said, the Grants Program focuses on open source software development and research, and your proposal doesn't seem to fit either. See our [guidelines](https://grants.web3.foundation/docs/Introduction/intro), [grant categories](https://grants.web3.foundation/docs/Support%20Docs/grant_guidelines_per_category) and application templates ([standard](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md), [research](https://github.com/w3f/Grants-Program/blob/master/applications/application-template-research.md)). I think applying with the [treasury](https://grants.web3.foundation/docs/funding) makes more sense here.


Hello, Do you think it would be possible to get a contact (e-mail address) to present our project/grant application to you, given that it's really specific and has more to do with a form of "certification" of crypto projects (in order to increase the trust and security of the network) rather than the creation of a crypto project for the Polkadot ecosystem? It is indeed complex to fill in the treasury form, so specific does our request seem to be.

**Comment by semuelle** [comment]
Hi @CryptoAegis8, you can email the grants team at grants@web3.foundation.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the application and all the effort you put into it. However, the grants committee decided to close the PR since it’s not a fit for our current program. We tried to reach out via email, but it looks like the email bounced. Feel free to reach out to grants@web3.foundation in case you have any questions or want to discuss it further.

**Pull request closed without merging**
