### PR TITLE
Add  Ares M2

### PR DESCRIPTION
**Pull request by jiyilanzhou**
### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying?

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] I have read and understood the [FAQs](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md), [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md) and [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md).
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).
- [ ] I prefer the discussion of this application to be in a private Element/Matrix channel. My username is: ``@_______``

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] Hackathon
- [x] Personal Recommendation
- [ ] Substrate Builders Program
- [ ] Investor/VC
- [ ] Online Search
- [ ] Other: _______

### CODE REVIEW

**Review by semuelle — CHANGES_REQUESTED** [review]
Thank you for the application, @jiyilanzhou! Some minor change requests:

- Could you expand the `Development Status` section a bit? It would be great if you could also describe what you did in your previous grant, how/if it relates to this one and what you have done in the meantime.
- There are a number of oracle solutions out there (see, for example, the oracle section in [our tech stack document](https://github.com/w3f/Grants-Program/blob/master/docs/polkadot_stack.md#link-chains-and-pallets)). It would be great if you could explain how your oracle is different and why another oracle is needed.

**Comment by semuelle** [comment]
Thanks for the update, @jiyilanzhou. I will share this application with the rest of the team. In the meantime, feel free to put your answers into the document itself under `Development Status` and `Ecosystem Fit`.

**Comment by jiyilanzhou** [comment]
> What solution do you mean here? There are several existing oracles. It would be great if you could go into more detail regarding the differences between your and those others solutions.

In the above solution, price submitters can be basically divided into three categories,
* Root account
* Specify whitelist for root account
* Members of the collective

The problem revealed is that it is too centralized and prone to single point of failure. There is no decentralized election update strategy for price submitters, and new price submitters cannot freely join and exit the network. This is just like the difference between POA network and POS network.


1. [Laminar](https://github.com/laminar-protocol/open-runtime-module-library/tree/master/oracle) use root or [whitelist member](https://github.com/open-web3-stack/open-runtime-module-library/blob/master/oracle/src/lib.rs#L196)
```
	fn do_feed_values(who: Option<T::AccountId>, values: Vec<(T::OracleKey, T::OracleValue)>) -> DispatchResult {
		// ensure feeder is authorized
		let who = if let Some(who) = who {
			ensure!(T::Members::contains(&who), Error::<T, I>::NoPermission);
			who
		} else {
			T::RootOperatorAccountId::get()
		};
```
2. [Parallel Finance](https://github.com/parallel-finance/parallel/blob/feature-oracle/pallets/ocw-oracle/src/lib.rs)  Members of the [collective](https://github.com/parallel-finance/parallel/blob/master/pallets/prices/src/lib.rs#L101)
```
        pub fn set_price(
            origin: OriginFor<T>,
            asset_id: CurrencyId,
            price: Price,
        ) -> DispatchResultWithPostInfo {
            T::FeederOrigin::ensure_origin(origin)?;
            <Pallet<T> as EmergencyPriceFeeder<CurrencyId, Price>>::set_emergency_price(
                asset_id, price,
            );
            Ok(().into())
        }
```
```
    type FeederOrigin = EnsureRootOrMoreThanHalfGeneralCouncil;
```
```
type EnsureRootOrMoreThanHalfGeneralCouncil = EnsureOneOf<
    EnsureRoot<AccountId>,
    pallet_collective::EnsureProportionMoreThan<AccountId, GeneralCouncilCollective, 1, 2>,
>;
```
3. [Katal Chain](https://github.com/katalchain/blockchain/tree/master/modules/oracle) Root [account](https://github.com/katalchain/blockchain/blob/master/modules/oracle/src/lib.rs#L59)
```
        // Set the value of an existing data feed or creating a new one.
        pub fn dispatch_set(origin, id: H256, value: Real) -> Result {
            // Only chain root should be able to set this value.
            ensure_root(origin)?;
```

What we need to do is to solve the following problems：
* The price submitter can enter without permission
* The submitter needs to stake certain tokens through staking
* Submitters can update regularly according to era
* The submitter randomly submits the price according to the babe consensus
* Anyone can challenge the price on the chain

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the follow-up grant application. I have a few questions: 

- If I understand it correctly, you want to use babe to randomly select the oracle. Are you referring here to actually using the same blockproduction as for the validators or running a separate version of babe, because a lot of the validators might not be able to provide the oracle service and in this case you might wait a long time before a validator is selected that is actually able to submit a price.
- Did you consider other mechanisms to randomise this?  
- How do you prevent sybil attacks, when you rely on the average price? 
- What’s the purpose of the audit? I mean if these are just random tests, then attackers could simply provide the correct results.

**Comment by jiyilanzhou** [comment]
> Thanks for the follow-up grant application. I have a few questions:
> 
> * If I understand it correctly, you want to use babe to randomly select the oracle. Are you referring here to actually using the same blockproduction as for the validators or running a separate version of babe, because a lot of the validators might not be able to provide the oracle service and in this case you might wait a long time before a validator is selected that is actually able to submit a price.
> * Did you consider other mechanisms to randomise this?
> * How do you prevent sybil attacks, when you rely on the average price?
> * What’s the purpose of the audit? I mean if these are just random tests, then attackers could simply provide the correct results.
Thanks for the reply.
1. Use the same blockproduction as for the validators not a separate version of babe. We added a hook to the election algorithm, `staking-extends` will implement this, Before becoming a validator, the candidate validator must have the ability to submit prices,  It will be realized through `Validator Pre-Audit`.
   *   Ares-oracle obtains the newly elected validator through the `IStakingNPOS::pending_npos` trait,and submits the `pre-check` task to the chain through `submit_create_pre_check_task` extrinsics.
   *   Use the `IStakingNpos::near_era_change` trait to determine whether the session period close to the election has been reached, and if so, submit the new verification task to the chain through `submit_offchain_pre_check_result` extrinsics.
    *   Validators that do not pass the review will not appear in the list of targets for elections.
 
    Therefore, each validator can offer services. If the price requirements are relatively timely, it can submit extrinsic `Paid Trade-price`.
     *    Users can submit a `submit_ask_price` transaction to have all nodes on the chain make an offer, but this requires payment some fee, which is more time-sensitive than getting the price for free.
     *    If submit a task successfully, you need to get the `purchase_id` from the `Event::NewPurchasedRequest` event, which will be used as the associated key value for other queries. The amount of payment is related to the number of `trade pairs` requests. If the nodes participating in the response are less than the response threshold, the task will fail, and the fee will not be deducted. (This threshold can be modified by extrinsics `update_purchased_param`).
     *   Once the price are aggregated successfully, an `Event::PurchasedAvgPrice` event will be generated, and the relevant fees will be deducted from the `origin` account. Users can also read the corresponding result data through the `aresOracle.purchasedAvgPrice` store.
2. At present, many randomness are pseudo-random. Only VRF is truly random and unpredictable, which is also the current upgrading direction of chainlink.
3. Our submitter needs to stake a large number of tokens to become a validator. For any perpetrator who wants to control many nodes, it needs to hold a large number of tokens.
4. The purpose of audit is to require nodes to have the ability to submit prices, The candidate validator needs to submit the prices of several assets. These data will be compared with the data on the chain. If there is no problem, it will become the validator,  If an attacker wants to submit a malicious price, it's cost will very high. First, It needs to pledge tokens to become a candidate validator, which needs to wait for one era, second exit the asset after submitting malicious data. it needs to wait for 28 era before redemption, Within 28era, the price challenger can be found and submitted to the reputation Committee for review. In the process of price aggregation, the price with large deviation will be eliminated or the weight will be reduced

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the detailed response and sorry for the late reply. I have a few follow-up questions: 
- Where can I find the latest version of your oracle pallet? Ares modules wasn’t updated the last 17 month: https://github.com/aresprotocols/ares-module/tree/main 
- If I see this correctly the features you are mentioning are already implemented, see https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fgladios.aresprotocol.io#/extrinsics. Is this correct?
- And last but probably the most important: “We do not award grants for projects that have been the object of a successful token sale.” See https://github.com/w3f/Grants-Program. It looks like your token is already trading (https://www.gateio.pro/de/trade/ARES_USDT) and was specifically created for a “Decentralized Cross-Chain Oracle Platform”.

**Comment by jiyilanzhou** [comment]
> Thanks for the detailed response and sorry for the late reply. I have a few follow-up questions:
> 
> * Where can I find the latest version of your oracle pallet? Ares modules wasn’t updated the last 17 month: https://github.com/aresprotocols/ares-module/tree/main
> * If I see this correctly the features you are mentioning are already implemented, see https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fgladios.aresprotocol.io#/extrinsics. Is this correct?
> * And last but probably the most important: “We do not award grants for projects that have been the object of a successful token sale.” See https://github.com/w3f/Grants-Program. It looks like your token is already trading (https://www.gateio.pro/de/trade/ARES_USDT) and was specifically created for a “Decentralized Cross-Chain Oracle Platform”.

1. See in this link [https://github.com/aresprotocols/ocw-suit/tree/master/pallets/ares-oracle/src](https://github.com/aresprotocols/ocw-suit/tree/master/pallets/ares-oracle/src)
2. The implementation based on aura is completed, and the implementation based on babe is in progress.
3. It's frustrating to hear this news. We will always strive to improve the development of Oracle.

**Pull request closed without merging**
