### PR TITLE
php substrate api application

### PR DESCRIPTION
**Pull request by tejbahadursingh**
### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [ ] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [ ] The initial PR contains only one commit (squash and force-push if needed).
- [ ] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Comment by neha0921** [comment]
I am working as a contributor.

**Comment by Noc2** [comment]
Also for reference: https://github.com/w3f/Grants-Program/pull/638 Could you point out what has changed since your last application.

**Comment by tejbahadursingh** [comment]
Thanks for your comment. I am aware of https://github.com/w3f/Grants-Program/blob/master/applications/php-rpc-lib.md and there work on php-scale-code. There work on RPC end points are still in progress, but we have already implemented those endpoints and work on packaging of this code in going on.  In earlier PR #638 we had only 3 endoints integrated and costing of whole task was $7K. In this PR we have integrated all endpoints and whole costing is now $5500. Costing of 2nd mileston has changed to $500. 
I did not get that "address of example" if it needs payment address then once PR is accepted then in subsequent PR we will add that address.

**Comment by semuelle** [comment]
> I did not get that "address of example"

@tejbahadursingh, we usually ask for an address at time of application so that there is no confusion/argument over where the payment goes to. Also, you have not ticked all boxes of the [pull request](https://github.com/w3f/Grants-Program/pull/655#issue-1030322141) template and your application still contains template text, such as the "For each milestone," list. The `FTE` numbers you have provided also seem off (I assume there won't be 45 people working on milestone 1 simultaneously).

**Pull request merged**
