### PR TITLE
Create CryptoCheckout.md

### PR DESCRIPTION
**Pull request by BenraouaneSoufiane**
#### Project Abstract

Secure simple decentralized crypto payments gateway.
The merchant must provide a valid DOT address when generating merchant ID in order to receive DOT payments (the only thing required).
The team interesting developing this project to redefine the online payments by using the crypto wallet instead credit cards.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (Polkadot AssetHub (USDC & DOT) address in the application and bank details via email, if applicable).
- [x] I understand that an agreed upon percentage of each milestone will be paid in vested DOT, to the Polkadot address listed in the application.
- [x] I am aware that, in order to receive a grant, I (and the entity I represent) have to successfully complete a KYC/KYB check.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [ ] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by BenraouaneSoufiane** [comment]
I have read and hereby sign the Contributor License Agreement.

**Comment by keeganquigley** [comment]
Thanks for the application @BenraouaneSoufiane is there a reason you don't want to use a newer technology than PHP?

**Comment by BenraouaneSoufiane** [comment]
> Thanks for the application @BenraouaneSoufiane is there a reason you don't want to use a newer technology than PHP?

Thank you for your reply @keeganquigley, depends on the platforms I'll build, WordPress is built with php, plugins/themes will be also with php, Shopify provide two possibilities, choosing between php & javascript (nodejs) app templates, I'll choose the nodejs template for my app.

**Review by keeganquigley — CHANGES_REQUESTED** [review]
Thanks @BenraouaneSoufiane additionally:

- For UI deliverables we require mockups to be provided up front, even if they are rough. Are you able to provide these?
- I don't think it's realistic that a lot of online retailers would have a DOT address. How would you plan to gain adoption among merchants?

**Comment by BenraouaneSoufiane** [comment]
> Thanks @BenraouaneSoufiane additionally:
> 
> * For UI deliverables we require mockups to be provided up front, even if they are rough. Are you able to provide these?
> * I don't think it's realistic that a lot of online retailers would have a DOT address. How would you plan to gain adoption among merchants?

Thank you @keeganquigley  for your reply

- Sure, I'll try to design the mockups.
- Getting a DOT address does not require much/specific work as I think, It requires just a TrustWallet/Metamask wallets or any other wallet that everybody have without being merchant, I'll add a link to instructions how to get a DOT address just after the input.

**Comment by BenraouaneSoufiane** [comment]
> Thanks @BenraouaneSoufiane additionally:
> 
> * For UI deliverables we require mockups to be provided up front, even if they are rough. Are you able to provide these?
> * I don't think it's realistic that a lot of online retailers would have a DOT address. How would you plan to gain adoption among merchants?

I have tried to make the mockups using Canva:
https://www.canva.com/design/DAGVtE0jm24/00PxFz0sx8qymgd4COUQQw/view?mode=prototype#untitled-page-4
Don't forget to click arrows to move between slides,  concerning the checkout pages, they are almost the same for WooCommerce & Shopify, so I did only one

**Comment by keeganquigley** [comment]
Thanks @BenraouaneSoufiane I will mark the application as ready for review so the rest of the committee can comment. Personally, I won't approve it because I don't think it is realistically scalable and I don't see a novel concept here. None of the deliverables are really related to Polkadot and I disagree with the use of PHP and Wordpress for an app like this. But I will give the rest of the committee a chance to respond before closing.

**Comment by BenraouaneSoufiane** [comment]
@keeganquigley thank you for your feedbacks
> I don't think it is realistically scalable.

the scalability will appear after submissions (the WP plugin to the WordPress plugin directory, & tge Shopify app to the Shopify app store), then they will be installable (via one click/tap) & searchable, shoud I extend the milestones for that?



> I don't see a novel concept here.

I started wotking on this on 2021, it was a novel concept, I think it's also about if it can add a significant value to the ecosystem or not, another says if it's usable & loved by people.



>None of the deliverables are really related to Polkadot

It's related with Polkadot as a crypto payment currency not as a project dedicated to the Polkadot (but it's related with Polkadot on its basic as I said).

> I disagree with the use of PHP and Wordpress for an app like this

I decide to make the WordPress plugin (as a result, the use of php) just because the WordPress runs/powers 43.6% of the web (493M website), & just because WooCommerce (a Wordpress plugin) powers approximativly the 25% of global online stores (itself has a user base of 1.7M active installlations/merchants)

**Comment by Noc2** [comment]
(see above)

**Comment by BenraouaneSoufiane** [comment]
Thank you

**Pull request closed without merging**
