### PR TITLE
ICS 11 - BEEFY

### PR DESCRIPTION
**Pull request by Wehbix**
### Project Abstract

Centauri is a trustless bridge that links the Inter-Blockchain Communication protocol (IBC) with our Kusama parachain, 
Picasso. 

It consists of:
- A Pallet that implements the IBC framework
- An RPC subcrate for exposing IBC state
- A runtime-api subcrate that provides an interface for the rpc subcrate to query IBC state from the runtime 
- A chain agnostic, event-driven relayer implementation in rust.
- Light client for Polkadot/ Kusama parachains that is implemented in Go for the IBC framework

Specifically, ICS 11 - BEEFY is the light-client implementation for the Polkadot BEEFY protocol. It enables 
sovereign Cosmos chains to follow Polkadot's parachain consensus. This allows the chains to verify which headers 
have been finalized and which messages are sent at the heights in these finalized headers. It is 
generalized so that it can follow any parachain consensus so long as the chains are connected to the same relay chain. 
It does so using Go implementation of the Parity-trie library.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying?

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] I have read and understood the [FAQs](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md), [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md) and [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).
- [ ] I prefer the discussion of this application to be in a private Element/Matrix channel. My username is: ``@_______``

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] Hackathon
- [x] Personal Recommendation
- [ ] Substrate Builders Program
- [ ] Investor/VC
- [ ] Online Search
- [ ] Other: _______

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Feel free to remove the non-bold parts of the template from the application (e.g. “If the name of your project is not descriptive, a tag line (one sentence summary”). It makes it really hard to read at the moment. 
Apart from this, I have a couple of questions/comments: 

- Where can I find the existing open source code of Centauri? Also the following link doesn’t seem to work: https://github.com/ComposableFi/composable/blob/david/substrate-ibc/frame/ibc/src/lib.rs 
- Do you essentially plan to implement [this](https://github.com/Snowfork/snowbridge/blob/main/ethereum/contracts/utils/MMRProofVerification.sol) in go? 
- We usually don’t pay for audits for grantees. Especially if teams already are fully funded.

**Review by semuelle — CHANGES_REQUESTED** [review]
Thanks for the application, @Wehbix. A few minor requests:

- Could you remove the template text throughout the document? That would make it a lot easier to read.
- Please fill out the `Overview` part in the `Development Roadmap` section. I believe it should be
  - Total Estimated Duration: 12.3 weeks
  - Full-Time Equivalent (FTE): 1
  - Total Costs: 49,999
- We don't fund audits. Please have a look at our [FAQ](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md) and make sure that the deliverables are actually covered by the grants program.

**Comment by Wehbix** [comment]
Hello @Noc2 & @semuelle. Thanks a lot for your feedback. We have updated the application.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. I have a few follow-up questions:  

- Why did removing the audits not reduce the total costs? 
- For milestone 1, the estimated duration is 1 month, FTE: 1 and the costs are Costs: 23,333 USD, this is a significantly higher day rate than for milestone 2. 
- What part is already covered by the grant by ICF? (regarding: “We have received a grant from Interchain Foundation for Centauri.”). 
- Isn’t https://github.com/nervosnetwork/merkle-mountain-range/blob/master/src/mmr.rs already implemented here: https://github.com/ComposableFi/go-merkle-trees/blob/main/mmr/mmr.go and the work for this grants essentially already finished?

**Comment by Wehbix** [comment]
Hi @Noc2, thanks for you input. We are going to reconsider the grant scope and update the milestones accordingly by the end of the week.

**Comment by semuelle** [comment]
ping @Wehbix

**Comment by alxs** [comment]
@Wehbix note that we try to keep only active applications open and usually close them if there's been no activity in over 2 weeks. Are you planning to update your current one, or do you prefer to apply again at a later date?

**Comment by Wehbix** [comment]
> @Wehbix note that we try to keep only active applications open and usually close them if there's been no activity in over 2 weeks. Are you planning to update your current one, or do you prefer to apply again at a later date?

Hi @alxs, apologies for the delay. We had some changes in the team which set us back a little bit. We have been actively working on the review of milestones and budgeting over this past week. Would appreciate it if we could keep this application open, we're in the process of finalizing the re-submisison. Thanks a lot

**Comment by JafarAz** [comment]
Hey @Noc2 @alxs @semuelle, I hope you're all well. As mentioned in the application, ICS 11 - BEEFY is only one of the multiple components of the Centauri bridge connecting Kusama to Cosmos. This grant application is for a level 2 grant; however, as I have re-evaluated the scope of our application and based on the parameters of the W3F grants, I have a couple of questions before we finalise the application from our side:

1. Can we continue with the current application and apply for other level 2 grants consisting of separate components of Centauri?
2. Or would you recommend us to apply for a level 3 grant that encompasses a combination of the components of Centauri?

Apologies for the delay with this application, this is our first grant with the W3F. You can expect a swifter process moving forward. 

Thank you

**Comment by Noc2** [comment]
Thanks for the question. We generally recommend teams to initially apply for smaller grants (e.g. level 2) and issue follow-up grants later. This way we get a better understanding of the project and scope. But obviously, in case the project only makes sense if we immediately fund it with a bigger grant, we are also happy to do this. However the review time might take longer in this case. I hope this answers your questions. Let me know if you have any other questions.

**Comment by JafarAz** [comment]
> Thanks for the update. I have a few follow-up questions:
> 
> * Why did removing the audits not reduce the total costs?
> * For milestone 1, the estimated duration is 1 month, FTE: 1 and the costs are Costs: 23,333 USD, this is a significantly higher day rate than for milestone 2.
> * What part is already covered by the grant by ICF? (regarding: “We have received a grant from Interchain Foundation for Centauri.”).
> * Isn’t https://github.com/nervosnetwork/merkle-mountain-range/blob/master/src/mmr.rs already implemented here: https://github.com/ComposableFi/go-merkle-trees/blob/main/mmr/mmr.go and the work for this grants essentially already finished?

Kind sirs the application has been updated and should answer the questions raised.

In regards to the ICF grant, they covered the part to support Substrate chains on the Cosmos side and merge a BEEFY-IBC client into the IBC-go repo.

Regarding the repos you linked, they are two different implementations; the MMR libraries linked in our repo are in Go, whereas the libraries you have linked for Nervos are in Rust.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Sorry for the late reply here and thanks for the update. I have a few follow-up questions:

- To be honest, it doesn’t look good that you initially applied for a grant of 23,333 for the first milestone and now say that this was already funded by the Interchain foundation. It looks like you tried to get double funding for the same work, which is clearly against our guidelines. Could you explain this? 
- Also our guidelines say the following: [“We do not award grants for projects that have been the object of a successful token sale”](https://github.com/w3f/Grants-Program#guidelines). Looking at your website and your vision, it seems to me that the main goal of your project is to bridge between different ecosystems. So isn’t this project already funded via your private sales?  
- Could you add the overview section (as Sebastian already requested above)? https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#overview-1

**Comment by Wehbix** [comment]
Thank you for your feedback.

- Regarding your first point: Initially we split the funding request for Milestone 1 'Implementation of the BEEFY Finality Verification Library' across the Interchain grant and W3F grant applications. Given its complexity, the resources required to implement this milestone far exceed the 23,000 USD requested for 1 engineer over 35 days (from W3F). Since you don't fund any work that's already implemented, we ended up covering the cost initially requested from W3F ourselves, with the Interchain foundation grant funding the remaining portion. We kept that milestone in the application for full transparency and to specifically address your question above of "What part is already covered by the grant by ICF?"

-Regarding your second point: The goal of our project is to build an interoperable infrastructure for Modular DeFi. Our tech stack consists of core infrastructure products (e.g. XCVM, cross-chain virtual machine), bridging products (e.g. Centauri) and a variety of Defi primitives that sit on top of this infrastructure. This grant specifically, is to cover the cost of a single component of Centauri. Our private sale covers tokens for our Kusama and Polkadot parachains. ICS 11 - BEEFY is fundamental to create the bridging infrastructure to bridge between Kusama parachains and Cosmos chains. As our website is currently under redevelopment, feel free to check out our gitbook for more detail: https://docs.composable.finance/

- We will add the Overview section as requested

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the quick response and the update. Makes sense. Regarding the application itself, I think the only outstanding issue is that your second milestone is at the moment focused on deployment and doesn’t include any concrete development. We usually try to focus only on the development, since the deployment on kusama or a cosmos sdk chain, is not something we can influence. And we also don’t want to support this directly or indirectly. So a local testnet for example would be sufficient for this.
I personally would still have concerns regarding the funding of this application and if it’s covered by your token sale or not. But this is something that the entire grants committee should decide, since this rule is highly subjective.

**Comment by JafarAz** [comment]
Hey sirs, apologies for the lack of response in this application. I can confirm that we have decided to withdraw and cancel this application as we will submit a new and improved application covering every component of our Kusama and Polkadot bridge.

I have a quick question if you don't mind: is $30,000 the limit for a level-2 grant? I noticed for >$100k, you would need to apply for a level-3 grant, but does that mean we are unable to apply for a grant between $30k and 100k?

**Comment by alxs** [comment]
@JafarAz sounds good. Thanks for letting us know. Level 3 grants [start at $30k](https://github.com/w3f/Grants-Program#level_slider-levels) and require 5 approvals from grants committee members; those above $100k require council approval in addition.

**Pull request closed without merging**
