### PR TITLE
PolkaGPT - All Polka-lover

### PR DESCRIPTION
**Pull request by CocDap**
#### Project Abstract

`PolkaGPT` is an application tool for the `LLM (Large Language Model)` model designed for developers, researchers, and users to search for documents, suggest code, hint at bug solutions, and more. Additionally, the Polkadot-loving open-source community can contribute to the data repository so that PolkaGPT can be updated continuously

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) address in the application).
- [x] I am aware that, in order to receive a grant, I (and the entity I represent) have to successfully complete a KYC/KYB check.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [ ] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by CocDap** [comment]
I have read and hereby sign the Contributor License Agreement.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. The formatting of your first milestone currently doesn't seem to be correct, and the second milestone is missing the default deliverables. Additionally, I have one big question: why do you think someone would use your service rather than ChatGPT or Bard? Both seem to already be capable to answer the questions that you listed above.

**Comment by keeganquigley** [comment]
Hi @CocDap thanks for your time and effort in submitting the application. Due to the reasons above, and also the fact that it isn't really coupled with Polkadot tech in a novel way, the committee has decided to go ahead and close this application. We appreciate your interest in the W3F grants program, and wish you the best of luck in finding funding.

**Comment by CocDap** [comment]
For some personal reasons, I am responding late. Here are two key differences between PolkaGPT and ChatGPT or Bard:

1. ChatGPT and Bard are trained on general knowledge, while PolkaGPT focuses on Polkadot-related information (a specific knowledge domain). Additionally, PolkaGPT includes links to YouTube and other learned sources. In terms of in-depth knowledge, PolkaGPT is more specialized, as ChatGPT and Bard may not provide detailed answers.

2. The `Contribute To Earn` model is implemented for PolkaGPT, where users contribute data that is verified. Contributions from the community and developers are highly valued, encouraging participation in the Polkadot ecosystem.

3. Currently, a person's credibility is based solely on their verified social account, which does not necessarily indicate whether they contribute to Polkadot. The proposed idea is to introduce on-chain credit to provide a more accurate measure of credibility for Polkadot enthusiasts. This would involve incorporating additional on-chain factors such as the amount you're staking, nominating, and your participation in activities within Parachains, ...

One more thing, the chatbot is the initial idea, while the combination of `Contribute to Earn` with `On-chain Credit` will utilize the tech stack of Polkadot

@Noc2 @keeganquigley Thank you for reviewing my initial proposal.

**Pull request closed without merging**
