### PR TITLE
Quid

### PR DESCRIPTION
**Pull request by johnquid**
#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [ ] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) address in the application).
- [x] I am aware that, in order to receive a grant, I (and the entity I represent) have to successfully complete a KYC/KYB check.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [ ] The initial PR contains only one commit (squash and force-push if needed).
- [ ] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for your interest in our grants program. Could you add a milestone table to each milestone that also includes the [default deliverables of the template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#milestone-1-example--basic-functionality)? Ideally also providing as many technical details as possible.

**Comment by Noc2** [comment]
I wanted to let you know that I'm closing this because of inactivity. Let me know if I should reopen it.

**Comment by johnquid** [comment]
> I wanted to let you know that I'm closing this because of inactivity. Let me know if I should reopen it.

Hello, yes, please re-open it. I've added a lot of details.

**Review by takahser — CHANGES_REQUESTED** [review]
@johnquid the doc currently doesn't adhere to the [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md). Apart from that, our program focuses on technical projects and the implementation thereof. We won't cover any maintenance activities:

image

Finally, we usually prefer new teams to initially apply for a level 1 or level 2 grant. Note that you can always apply for follow-up grants, which might include level 3 grants, if you've done a good job on the initial grant.

**Review by semuelle — COMMENTED** [review]
> We won't cover any maintenance activities, since they're not reusable by other teams and add less value to the ecosystem:
> image

I assume that the grant is supposed to cover the 90k R&D costs mentioned in the total costs. However, they also contain activities that aren't in line with the grants program guidelines (see [FAQs](https://grants.web3.foundation/docs/faq#what-activitiespositions-do-you-fund)). Some of the specifications are also rather abstract. It's better to make them as concrete and verifiable as possible to avoid any misunderstandinds.

That being said, I believe you have a much better shot with this at the Decentralized Futures Program, so I would recommend you apply there first. It's a bit more business-oriented, but it seems to me that this would suit your current roadmap.

**Comment by takahser** [comment]
@johnquid The W3F Grants Committee decided not to go ahead with this proposal, since there hasn't been a lot of activity and the doc still doesn't adhere to our template, even >1 month after opening this PR. Nevertheless, we wish you all the best for the future of the project and hope, it will be a success. Thanks for your interest in our program!

**Comment by johnquid** [comment]
Many people got into Polkadot through "A Hands-On Cookbook for Aspiring Blockchain Chefs" so I'm going to reuse the kitchen analogy here. The matter in question is an experimental dish that uses knock-in options as one of its main ingredients.

@Noc2 requested to provide as many details as possible...so I included the maintenance costs that @takahser objects to...as they are actually a dependency for there to be an R&D effort in the same way that a table is a dependency for there to be a dinner party. I hate to be captain obvious, but a misconception keeps reappearing in the grants space about R&D costs, treating them almost like real estate development; the type of labor is very different and the maintenance costs of a legal structure are definitely useful to other projects (e.g. for giving out grants), even though the structure itself houses only one project. 

Next point..."we usually prefer new teams to initially apply for a level 1 or level 2 grant." That would effectively be taking Milestone 2 from the current application and breaking it up granularly into a unit test outline...where essentially every row in the table would be a function in the contract. That would certainly be more concrete and less abstract, but maybe it's because I'm leaning too much on the fact that most of our code is already public. So we are definitely not a "new team," except from your perspective, perhaps.

We don't have cross-chain bridging components yet, and researching exactly what those would entail is part of the work for milestone 3 (there are research papers linked which will serve as a springboard for our efforts on that front). For a project of QU!D's scope and stage of development, downgrading from Level 3 to Level 2 does not make sense.  

Finally, the last point...
"activities that aren't in line with the grants program guidelines"
Are you referring to the podcast? I thought that promotional, entertaining, and educational content that's contextually rooted in Polkadot was part of the agenda of bringing a wider audience to the network. Aren't "influencers" getting some form of sponsorship as well, regardless of the quality of their content? 

Apologies for coming across somewhat unapologetic, if that juxtaposition even makes sense, but it's very annoying that my PR keeps getting closed before I've taken the time to produce a quality response. Even the Battle of Stuttgart had a 9 day window (don't expect a quiet surrender)...🥶 I can understand the general urge to reduce the size of the open PR list. It creates the impression of productivity, but can sometimes create a conflict of interests with patience and respect.

@takahser the character of your feedback was of the same quality that could also be provided by a linter. This can only mean that you haven't even necessarily noticed the actual substance of the document in question. I haven't seen a single specific question about the workings of the mechanism described therein...so how can I take your words seriously when you talk about "bringing value to the ecosystem"? And with that said, in regards to the actual template, so what if omitted a couple of headers? 

People often have high conviction about values, like aesthetics or stylistics, and unfortunately, conviction can lead to stiffness which results in sticking to a very narrow idea of what value means, with an inability to see beyond that idea. I thought the whole reason Polkadot had been born in the first place was in response to how my previous point applies to the Ethereum community. 

Prior to embarking on this grant application, I was somewhat alarmed by a post from my fellow 🐝 of [Supercolony](https://medium.com/brushfam/brushfam-is-leaving-polkadot-story-unfold-4fa5c38716dc). Now I've seen for myself exactly how pedantic things can get! So, for the sake of completeness (and without sarcasm, truly), I will relay some kind wishes back to you in exactly the form they were received...
"We wish you all the best for the future of the project and hope, it will be a success."
I'll also add, "knock on wood!" @gavofyork

**Pull request closed without merging**
