### PR TITLE
Substate Multisig pallet and its MVP fontend

### PR DESCRIPTION
**Pull request by tinydjp**
### Project Abstract

> This project implements a minimum viable functioning multisig product on a Substrate. The goal of this project is to eventually launch a multisig product that is integrated with Dora Factory's testnets and parachain.

[dora-factory-multisig.md](https://github.com/w3f/Grants-Program/files/7943687/dora-factory-multisig.md)

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `dora-factory-multisig.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [ ] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Comment by semuelle** [comment]
Thanks for the application, @tinydjp. We will look into it as soon as possible. In the meantime: do you have any designs or wireframes for the UI you could add to the doc?

**Comment by tinydjp** [comment]
Hi, @semuelle we plan to work on the pallet implementation first, the design is still on the way, once we finalize, I'll let you know.

**Comment by mmagician** [comment]
Thanks for the application!
I am trying to understand how much will your pallet differ from the current FRAME multisig module?
For example, how would `Create wallet by organization` work - i.e. what is it exactly that is not possible (or difficult) to do via the existing pallet, and how will you make it possible/easier?
It would be great if you could expand on these points for all your listed deliverables.

**Comment by tinydjp** [comment]
Hi @mmagician sorry for the late response, The reasons why build a new pallet are below

1. Multisig pallet only provides 3 methods, which can not meet requirements application-level and DAO use cases
2. The multisig pallet has not been updated for a while, we’ll implement more new features to help community to build a multisig pallet faster
3. The latest polkadot{.js} has removed feautres to support multisig, which makes this pallet hard to debug/demonstrate
4. As Dora Factory is working on DAO infrastructures, most of our users are organization users, we are creating a multisig for organization users (e.g. a DAO can deposit and manage funding using the pallet and get access to a broader range of applications from Dora Factory). In this way this pallet can integrate with other Dora Factory pallets seamlessly.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. In general, we are well aware that the UI of the multisig tools is less than perfect and we would be more than happy to support a team to work on the UI. For this it would be really helpful to have some initial mockups. However, I’m not sure I understand the benefits of your pallet. What does “Create wallet by organization” mean? You can already with the current multisig pallet create multisigs that consist of multisig accounts as far as I know. Also what is “Multi assets management”? “ Initiate a transaction in a wallet, sign a transaction, confirm a transaction” is also already supported by the current pallet. The only new feature would be “Add a signer, update multisig rule”. However, I’m not sure how you want to implement this technically, since in this case the multisig address would change as well. Theoretically, you can do this also already with the current pallet plus a transfer. (create a new multisig + transfer the funds to the new account), which could be solved via the UI.

**Comment by tinydjp** [comment]
Hi @Noc2 , maybe our description mislead you guys, actually, our pallet will derive from the parity multisig pallet. Those functions are designed in the view of product. To be honest, current multisig pallet can fulfill our requirements in some way of other. We just want to make that pallet more user friendly so that developers know which methods to call at a glance. More precisely, our pallet development is to refactor the pallet, not to create a brand new one.  I think we can follow @semuelle 's suggestion, focus on the frontend first. As of the pallet, do you think is it necessary for us to do the refactor?

**Review by Noc2 — CHANGES_REQUESTED** [review]
In this case I would recommend to focus on the front-end and not to refactor the current pallet. The pallet itself is audited in its current form and if you refactor it, you might break something or integrate additional security risks. Could you update the application accordingly?

**Comment by tinydjp** [comment]
Hi @Noc2 , we just updated the application form, the requested fund also decreased due to the removal of pallet implementation. Would you mind reviewing again, thanks!

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. You currently say this is a level 1 grant (see above), but you are actually applying for 15k, which is above the limit of level 2 grants. Also some of the mandatory deliveries are missing in your application (see Deliverables 0a-0d are mandatory for all milestones, see https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md).  Furthermore, for purely UI focused projects, we usually require teams to share some mockups, before we sign the grant. Btw, you can also use westend for testing your UI. I don’t think you need to deploy your own chain, but this is up to you.

**Comment by Noc2** [comment]
I’m closing the application for now due to inactivity. Let me know if I should reopen it.

**Comment by tinydjp** [comment]
Hi @Noc2 , hope it's not too late, we've just finished the MVP design, would you please help review again, thanks! The design link https://www.figma.com/file/NBavL709zClLkDMAqP1maR/Substrate-Multisig-Frontend-MVP?node-id=225%3A1575

**Comment by Noc2** [comment]
@tinydjp Thanks for sharing the MVP design. It looks nice. I’m going to reopen the application. Could you please update it?

**Comment by tinydjp** [comment]
Hi @Noc2 I've just updated our doc. As for milestone 1, it's more meant to be our workload for the design. I'm not sure whether we should remove it and just provide you the final requested amount.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks again for the update. However, the [figma link to your design](https://www.figma.com/file/NBavL709zClLkDMAqP1maR/Substrate-Multisig-Frontend-MVP?node-id=225%3A1575) still isn’t part of the application. Could you add this? And correct, usually we don’t fund the initial design phase, so I suggest removing the first milestone, if this is possible. But feel free to add additional milestones or deliverables?

**Comment by tinydjp** [comment]
Thanks for you advice, we've decided to remain only 1 milestone, please help review our latest document.

**Review by Noc2 — DISMISSED** [review]
Thanks. I’m happy to go ahead with it and will share it with the rest of the team.

**Review by alxs — CHANGES_REQUESTED** [review]
Hi @tinydjp. Thank you for your application. The wireframe looks really good and I'd generally be happy to support this. However, as David said we don't fund the design phase. You just removed milestone 1 containing the design but added its cost to milestone 2. Seeing as this seems to be mostly done, you say it is meant to be your workload and the remaining deliverable is only an MVP, I'd be more comfortable giving my approval at the initial price point of $10k.

**Comment by tinydjp** [comment]
Hi @alxs and @Noc2 , thanks for your review, we're ok with price. I've just updated the doc and request.

**Review by Noc2 — APPROVED** [review]
Thanks.

**Review by tinydjp — COMMENTED** [review]
changes have been done

**Review by mmagician — APPROVED** [review]

**Pull request merged**
