### PR TITLE
kaladin grant application

### PR DESCRIPTION
**Pull request by VinceKLDN**
#### Project Abstract

Kaladin's cross-chain protocol allows the exchange of assets between blockchains without an intermediary or bridge. The Kaladin protocol can enable to direct transfers and exchanges between any blockchain asset with <0.1% transaction fees and in <0.25 seconds without using a bridge or a central third party. Swaps between Bitcoin variants, ETH chains, Stellar and Algorand can be done in less than 1 second, and we can support over 6,000 tps for exchanges.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) or BTC address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@CryptoKaladin:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for your interest in our grants program. However, the application at the moment contains very little information, and the milestones are simply based on the template. Could you please update this?

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. Let us know once we should take another look at the application. But just be aware that for example "We are currently developing a wasm smart contract for Polkadot." doesn't contain any technical details. (e.g. programming language). The milestone table represents the technical requirements of our contracts. 


<br class="Apple-interchange-newline">

**Comment by VinceKLDN** [comment]
We have just updated the information, let us know if there is anything else that needs to be changed

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. However, the formatting of the application seems to be wrong. The tables don't render correctly. Could you fix this? Also what is the reason for the additional price increase? Why is the smart contract repo that you shared archived? Additionally, the estimated duration seems very high to me, especially given that you want to reuse an existing solution developed in solidity. Could you comment on this?

**Comment by Noc2** [comment]
I'm closing this application due to inactivity. Let me know if I should reopen it.

**Pull request closed without merging**
