### PR TITLE
Create ori.md

### PR DESCRIPTION
**Pull request by AB3rtz**
### Project Abstract

SyntiFi is actively developing ORI, an On-chain Risk Intelligence tool to fight and prevent financial crime. We do believe that with the great power of decentralized finance comes the great responsibility of ensuring that no financial crime, money laundering or terrorist financing is taking place. For this reason, some crucial capabilities of our tool is made available open source. In this grant we ask for support to add Polkadot to our growing ecosystem of chains and tokens.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. The project sounds interesting. So just to double check, it’s okay if we pay you in stablecoins for example, but you don’t want to share your on-chain address here, correct? The reason why we usually want to have a payment address as part of the application process is that this way no one can later send us a fake invoice etc, because we only pay the money to the specified address. Which btw. can be an address that will only be used for the grant. 
Regarding the application itself, could you add more technical details, for example what kind of database are you using? Also did you take a look at existing indexers [here](https://github.com/w3f/Grants-Program/blob/master/docs/polkadot_stack.md) and explain why you are not using them.

**Comment by AB3rtz** [comment]
Hi Noc2, thank you for the feedback. Yes, we are fine in receiving stablecoins, we just prefer not to have the wallet address publicly available. That being said, your solution to create one just for the grant could be a simple solution. Now, regarding the technical details. Up until now we were indexing directly on ElasticSearch but we are currently changing that to use postrgresql together with elastic search for a faster search (more precisely we use a hibernate-elastic-search module to facilitate the sync between the SQL DB and Elastic Search). As per indexers, it is a fair question, we could have used the available indexers for the different chains. The issue is that these indexers are often storing the whole information of the blocks and merkle trees, but we just need a smaller portion of that. For this reason we decided to create our own, simple crawler, to index just what we need and replicate that for the different chains. Hence facilitating the cross-chain approach.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the quick reply. In this case, I recommend updating the PR and to add a crypto currency address. This way the whole process will be much easier and quicker and feel free to add the explanation regarding the indexer to the application.

**Comment by AB3rtz** [comment]
Hi Noc2, I just updated the file as we spoke. How shall we proceed? We are looking forward to joining the ecosystem.

**Comment by alxs** [comment]
Hi @AB3rtz, thank you for your application. This is indeed an interesting topic and ever more relevant with financial crimes involving cryptocurrencies on the rise. I have a few questions:
- What other indexers have you tried?
- In your application, you mention that you want to add Polkadot to your 'growing ecosystem of chains and tokens'. What does that ecosystem currently consist of?
- What exactly is cross-chain about your approach?
- What features does ORI currently provide and what is on your roadmap?
- You describe your project as being targeted towards financial institutions and applications on Polkadot. However, these actors are likely to be more than willing to pay for a subscription for access to a leading blockchain forensics solution, most of which have already integrated support for Polkadot while offering a myriad of existing features, data and legal backing. Why should they use this project instead?

**Comment by AB3rtz** [comment]
Hi @alxs, thank you for taking a look into our proposal. Here are our take on your questions:
- For the Polkadot ecosystem we looked at the indexers listed [here](https://github.com/w3f/Grants-Program/blob/master/docs/polkadot_stack.md).

- ETH-based tokens and other layer 1 tokens such as CSPR. We are also working on the BTC integration and Polkadot would be our next one.

- Cross-chain in the meaning of not only multi-chain but also including bridges.

- To mention some of them, we have the crawler to index the chains, a REST API to query the indexed chains, and perform AML calculations (built using Java) together with a basic front-end built in React. All are available under Apache 2 license.
Roughly speaking, the roadmap looks as follows:
  1. integrate as many chains as possible/feasible to broaden the multi-chain capabilities;
  2. implement rule-based AML scoring procedures;
  3. build solutions for bridges as part of the cross-chain analytics features;
  4. enhance the AML scored to use our Machine Learning/AI models;
  5. expand the use case to add fraud detection capabilities.

- It is true that a couple of solutions already exist, however, most (if not all) are proprietary. We believe in the power of open-source software, open financial services, and tools that grow with the communities rather than centralized commercial bodies. That being said, institutions can decide to run their service using a transparent tool or purchase the service from third-party providers.

**Comment by alxs** [comment]
Thank you for your answers @AB3rtz. I'm pretty sure [SubQuery](https://subquery.network/) allows you to query other nodes and only store the data that you need locally. What issues did you find with it?

Sounds great, how do you index the Ethereum-based tokens and what other L1 tokens do you support? The post-installation instructions only mention a crawler for the Casper blockchain.

I suppose by AML calculations you mean [these four metrics](https://github.com/syntifi/ori/blob/master/src/main/java/com/syntifi/ori/service/README.md#aml-scores)? What AML regulations do they address?

**Comment by AB3rtz** [comment]
HI @alxs , thank you for your comments (and for going ahead and looking at our repo ;)). As per your questions:

- There are no issues with SubQuery, it is actually great for the chains they cover, but they are not a solution for us, they don't cover CSPR for instance.

- For ETH we are using Web3j, GETH and Spring batch job, the code is under review and will be published in the coming weeks.

- You need to populate the database (it takes a while, because many blocks have no transactions).

- For the ML/AI models we cannot share anything so far. As per regulations, there is specific regulatory framework we are following. The idea is to have the tools in place to facilitate the life of the compliance officer to fulfill the regulatory requirements on his/her jurisdiction.

- Probably we are talking about the same players, they all provide tools, to facilitate the life of the compliance officers. Sure, the 4 metrics are just some of them we are offering. These are the ones we are proposing to have as part of the open-source solution, together with the trace the coin capabilities.

Happy to have a call to touch on all your points.

**Comment by alxs** [comment]
Hey @AB3rtz. Thank you for your answers again. At this point, I have to say I'm afraid I won't support your application due to the following concerns:

- You initially claimed that the issue with other indexers was that those 'are often storing the whole information of the blocks and merkle trees, but [you] just need a smaller portion of that', and that you had tested SubQuery along with other indexers in the ecosystem. However, then you say you didn't have this issue with SubQuery and the reason you don't want to use is that it doesn't cover other chains, which:
  - is a different issue invalidating your initial answer, which leads me to believe you hadn't given enough consideration to using an existing solution,
  - is not a reason to build your own indexer for Polkadot, which is mainly what you're applying for, and
  - in my opinion is not a reason not to use it in the first place.
- Your 'growing ecosystem of chains and tokens' in that case currently only consists of CSPR, so I'd consider this an overinflated claim. You also haven't answered my question as to what other L1s you support, so I have to assume there are none and this was a false claim.
- I've let the database populate for a while and still running the application does nothing.
- Without evidence of you having any ML/AI models or you being able to share anything at all about them, I have to assume you don't actually have any and this was also a false claim.
- You haven't answered my questions as to what AML regulations you're targeting or whether anyone in your team has experience in AML compliance, so I have to assume you're not targeting any specific regulations yet and no one in your team has experience in the field.
- If your open-source version will only provide 4 random metrics and the rest will be closed-source, this won't be useful to the community and I don't see why we should fund it.

Nevertheless, I'll share your application with the rest of the committee for review.

**Comment by AB3rtz** [comment]
@alxs We are extremely surprised that you have chosen to act in a way which we consider inappropriate in a professional setting by responding to our application for a grant using unsupported accusations in an official and public channel of the W3F foundation. You have released false and damaging statements (without any basis in reason or fact), accusing us of bringing false and, as you say inflated, claims (which we strongly refute). This can only serve to harm and damage our project, our team, and ourselves as applicants. In addition you have chosen this path without evidence and without knowing our team or ever having directly talked with us. Please be advised that we strongly deny your statements. Such behavior displays extreme unprofessionalism on W3F’s part and breach of your code of conduct.
We will take this up with the foundation.

@noc2 it saddens me to see unsupported accusations of false claims taking place in an official and public channel of the W3F foundation. We are well aware that W3F runs its due diligence processes with integrity and that you have the sole discretion to decide on accepting or rejecting a grant. However, we will not sit quietly when individuals publicly express their assumptions and state we are lying without any evidence of it. Such false claims can only damage our project, and such an attitude displays unprofessionalism from W3F. W3F's team is entitled to have a personal opinion but jumping to conclusions without any evidence shows a low level of professionalism on your side.

**Comment by Noc2** [comment]
I agree that @alxs makes claims and assumptions without knowing if it’s true or false and should have at least given you the opportunity to clarify this before communicating it like he did. Your repository and answer above clearly shows that you at least have worked on different layer 1s.  Furthermore, some of the points he shared aren’t directly relevant to the application itself and its deliveries. I apologist for it. If it’s okay with you I will try to take another look at the application next week. I’m currently OOO. Also feel free to disagree/refute his arguments.

**Review by Noc2 — CHANGES_REQUESTED** [review]
I quickly took another look at the application and especially [your refactor branch](https://github.com/syntifi/ori/tree/refactor), which seems to also contain the front-end. In general, I personally would be more than happy to support another indexer that uses a different technology stack, independent of the specific reason for this decision. My biggest concern at the moment is the price of the application. For example all milestones have an estimated duration of 1 month, 1.5 FTE and the costs are completely different for each milestone and they generally seem relatively expensive to me. Would you be willing to reduce the price and/or integrate additional deliveries (e.g. front-end)? 

Btw. I’m not sure it’s helpful in your Web3 grant application to mention that you want to also integrate BTC and ETH in future ;-) (just joking)

**Comment by alxs** [comment]
@AB3rtz I apologise for my unprofessional behaviour and will make sure to discuss the situation with @Noc2. I'm also more than happy to change my mind if you want to refute my arguments, which I should have pointed out.

I also agree that the point regarding your ML/AI models was irrelevant to the application and making my assumptions public was unprofessional. I've edited my comment to reflect this, though my original answer remains in the history for the record. Please accept my sincere apologies.

**Comment by Noc2** [comment]
Closed the application (see email).

**Pull request closed without merging**
