### PR TITLE
Update SaaS3

### PR DESCRIPTION
**Pull request by SaaS3Lab**
#### Project Abstract

SaaS3 is a protocol in layer2 that is highly scalable, crypto incentivized, and results in a solution that can serve as a decentralized APIs (dAPI) middleware to provide off-chain services to blockchain smart contracts.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (aUSD/USDT) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

Previous PR: https://github.com/w3f/Grants-Program/pull/821

### CODE REVIEW

**Review by alxs — CHANGES_REQUESTED** [review]
Thanks for the amendment @SaaS3Lab. Since the original application was accepted back in March, could you specify when you intend to deliver the new milestones? Otherwise, the date of acceptance [is considered](https://github.com/w3f/Grants-Program#2-application-review) the starting date of the first milestone.

**Comment by alxs** [comment]
Thanks @SaaS3Lab, sounds good. Could you please make sure your application complies with the following section in our [guidelines](https://github.com/w3f/Grants-Program#guidelines):

> Applications must not mention a specific token. Furthermore, the focus of the application should lie on the software that is being implemented/research being carried out as part of the grant, and less on your project/venture/operation. For the purpose of the application and delivery, think about how others might also benefit from your work.

Please focus on the necessary technical development of the project and remove any token-specific aspects.

Also one question, can Phat contracts be run on any chain supporting WASM smart contracts?

**Review by alxs — APPROVED** [review]
Thanks. I'm happy to approve the amendment and will share it with the rest of the committee.

**Review by Noc2 — APPROVED** [review]

**Review by dsm-w3f — APPROVED** [review]

**Comment by keeganquigley** [comment]
> Thanks @alxs. The first milestone has been finished. Currently, we are fixing some bugs and preparing related files and documents for review. We will submit the first milestone for review in 2 weeks.
> 
> The Payment has been modified to add a Polkadot/Kusama address.

Hi @SaaS3Lab do you have any updates you can share with us regarding this delivery?

**Comment by keeganquigley** [comment]
@SaaS3Lab thanks for the update! That's not a problem. If you think it will take more than 2 weeks to submit the delivery, please consider submitting an [amendment](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval) to extend the timeline. That will take any added pressure off. Thanks!

**Comment by keeganquigley** [comment]
Hi @SaaS3Lab how is milestone 2 coming along?

**Pull request merged**
