### PR TITLE
Amendment to Chainviz v1 application

### PR DESCRIPTION
**Pull request by kukabi**
This an amendment to the original Chainviz v1 [application](https://github.com/w3f/Grants-Program/pull/1254) with the following changes/updates:

- Removed shader development. New design does not currently require custom shader development.
- Removed extrinsic and event arguments from block contents. We do display the list of extrinsics and events, and it is technically very feasible to get arguments for both, but the design doesn't have space for arguments. We might include arguments in the future versions should we move in more of a block explorer direction.
- Removed the development of the custom block details service for the SubVT backend. Polkadot JS API and [Polkaholic XCM API](https://docs.polkaholic.io/#xcm) are perfectly enough for all our needs to get block content and XCM data. Furthermore our assumption that it should be possible to get complete XCM data just using the relay chain storage turned out false. Polkaholic indexes all data from all chains to be able to present complete XCM data, end to end.
- Merged two milestones into one and changed the duration to 8 months taking late 2022 as the start date, and workload at 0.2 FTE.

Thanks.

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the update. Are you also planning to deliver the milestone now? Regarding the milestone table, it would be nice to have additional details and the open-source software as part of the delivery. At the moment, it looks a little bit like you are only delivering the deployed Web application, which we usually don't care so much about.

**Comment by kukabi** [comment]
> Thanks a lot for the update. Are you also planning to deliver the milestone now? Regarding the milestone table, it would be nice to have additional details and the open-source software as part of the delivery. At the moment, it looks a little bit like you are only delivering the deployed Web application, which we usually don't care so much about.

**Comment by kukabi** [comment]
> Thanks a lot for the update. Are you also planning to deliver the milestone now? Regarding the milestone table, it would be nice to have additional details and the open-source software as part of the delivery. At the moment, it looks a little bit like you are only delivering the deployed Web application, which we usually don't care so much about.

@Noc2 Sorry, yes we are going to deliver the complete source code of the software and documentation on how to run it. I have updated the milestone table. Development is happening at [github.com/helikon-labs/chainviz-v1](https://github.com/helikon-labs/chainviz-v1) at the moment, but will be moved over to the main Chainviz [main repository](https://github.com/helikon-labs/chainviz) once the development is completed.

And we're planning the delivery for the end of this week.

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I'm already happy to go ahead with the amendment and share it with the rest of the team.

**Comment by kukabi** [comment]
Thanks @Noc2, we're doing our best to complete & submit it all this week.

**Comment by takahser** [comment]
@kukabi mostly LGTM, but could you help me out with explaining me what shaders are?

**Comment by kukabi** [comment]
Sure, @takahser. A shader is basically a small program that runs during the 3D render and tells the renderer how to render certain objects/surfaces. They are utilized for custom graphics programming where either the graphical primitives provided by the 3D framework are not enough, or don't perform well enough.

We were able to satisfy the complete visualization in a performant manner using the graphical primitives provided by [Three.js](https://threejs.org/), our framework of choice for WebGL graphics. So it turned out we do not need to program custom shaders for our 3D world.

**Review by takahser — APPROVED** [review]

**Review by keeganquigley — APPROVED** [review]
LGTM

**Pull request merged**
