### PR TITLE
Roloi - Grant Application 

### PR DESCRIPTION
**Pull request by RoloiMoney**
Added Roloi.md

### Project Abstract

Roloi is a **real-time finance protocol** that allows users to stream money from one wallet to another.
A user only needs to configure a **recipient, amount and end date** to create a stream. Then, the recipient will see the available balance increase in real time.

Why money streaming?
**Time acts as a restriction for every money-related operation**: Monthly salaries, daily price candles, weekly token airdrops, billing cycles for subscriptions, etc.
Roloi introduces the real-time finance concept to change the perception of money and enable real-time token streaming on Polkadot.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying?

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] I have read and understood the [FAQs](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md), [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md) and [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).
- [ ] I prefer the discussion of this application to be in a private Element/Matrix channel. My username is: ``@_______``

### How Did You Hear About our grants program?

- [x] Social Media
- [ ] Hackathon
- [x] Personal Recommendation
- [ ] Substrate Builders Program
- [ ] Investor/VC
- [ ] Online Search
- [ ] Other: _______

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the grant application. Looks like an interesting project. I have two initial questions: 

- Are the original CosmWasm smart contracts open source? If so could you share a link? 
- Is it possible to change the number of transactions per time? And how do you deal with high transaction fees?

**Comment by RoloiMoney** [comment]
> Thanks for the grant application. Looks like an interesting project. I have two initial questions:
> 
> * Are the original CosmWasm smart contracts open source? If so could you share a link?
> * Is it possible to change the number of transactions per time? And how do you deal with high transaction fees?

Hi @Noc2, thank you for your reply!

Our smart contracts are not open source yet, we are planning on doing that once we migrate to the ink! version.

About the transactions, the way this first version will work is by locking the deposited amount in the smart contract and allowing the recipient to manually withdraw from the **available balance** when needed. This allows users to decide the best time to withdraw their desired balance.

Let us know if you have any other questions or feedback.
Thanks!

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the quick reply. I will already change the status of your application to ready for review, so that others also take a look at it. 
So it’s actually similar to the [vesting module](https://github.com/paritytech/substrate/tree/master/frame/vesting) if I understand it correctly. This makes sense. I have just one more question: The price seems relatively high for me. Would you potentially either be willing to reduce the price or integrate additional deliverables like the front-end?

**Review by Noc2 — CHANGES_REQUESTED** [review]
One additional delivery might also be to write an article/tutorial about how to switch from CosmWasm to ink!.

**Comment by hakan-w3f** [comment]
Hi @RoloiMoney, thanks for applying. How would you compare and contrast your project to [OAK Network](https://oak.tech)?

**Comment by RoloiMoney** [comment]
@Noc2 @hakan-w3f Thank you for your feedback! 

Here are some comments to answer your questions:

About the deliverables, we are already including an article explaining our experience migrating from CosmWasm to ink!. We consider this is an important part of our work to help onboard other teams and collaborate with them.

About the price, from our experience as developers and managers, we took a $65/hour price, and we are rounding down to $20,000. This is less than our usual development price but we are prioritizing the collaboration with the community and the experience of building an ink! based smart contract. Finally, we checked other grant applications and validated that our numbers were accurate.

About Oak Network: 
- We mentioned their project because Roloi could potentially leverage an automation feature. So a partnership between teams would be great. 
- Roloi's main focus is to provide the best UX to solve real-life problems while Oak's focus is to build infrastructure that other teams can leverage, that's why we think collaboration is key.
- The main difference between Roloi and Oak is that our smart contract platform is scoped to payments and token streaming while their parachain is focused on transaction automation.
- Roloi will provide tools like payroll management for companies and service subscription tools for merchants. Our vision for Roloi is to become the main payment customization platform on Web3. So in case of a collaboration, Roloi would help with the onboarding of users to Oak network.

Let us know what you think about our comments, feedback is always appreciated!

Thanks!

**Review by Noc2 — CHANGES_REQUESTED** [review]
Sorry, I overlooked the article and thanks for the quick reply. The hourly rate seems fine to me, but I’m not sure it will take you two full time employees for one month to implement an existing smart contract in ink!. That’s why I brought it up.

**Review by Noc2 — APPROVED** [review]
Thanks again for the quick reply. In this case, I’m willing to make an exception and accept the grant at the current rate.

**Review by SBalaguer — APPROVED** [review]
I'm more than happy to support this proposal. I believe it's going to be very interesting to see what the path from CosmWasm to ink! looks like, so very much looking forward for that article as well.

**Review by gautamdhameja — APPROVED** [review]

**Comment by meldien** [comment]
Hi @RoloiMoney,

I noted the correct vendor address is missing (street). 
Could you please update the invoice and sent it again? 

Many thanks. 

Best wishes,
Melanie

**Comment by RoloiMoney** [comment]
@meldien Sorry for the delay, we submitted the invoice again. Thanks!

**Comment by meldien** [comment]
@RoloiMoney thank you. The invoice is booked and will be paid asap

**Pull request merged**
