### PR TITLE
Reference blockchain token system.md

### PR DESCRIPTION
**Pull request by hoho-yin**
### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [ ] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [ ] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [ ] The software delivered for this grant will be released under an open-source license specified in the application.
- [ ] The initial PR contains only one commit (squash and force-push if needed).
- [ ] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] Hackathon
- [ ] Personal Recommendation
- [ ] Substrate Builders Program
- [ ] Investor/VC
- [x] Online Search 
- [ ] Other: _______

### CODE REVIEW

**Comment by takahser** [comment]
@hoho-yin thanks for your application. I took a quick look and saw that there are no milestones defined. Please keep in mind that any application should always [adhere to our template](https://github.com/w3f/Grants-Program/blob/master/README.md#1-application). Feel free to ping me once you've updated your application or in case of further questions.

**Review by takahser — CHANGES_REQUESTED** [review]
see [previous comment](https://github.com/w3f/Grants-Program/pull/923#issuecomment-1114506234)

**Comment by hoho-yin** [comment]
> @hoho-yin thanks for your application. I took a quick look and saw that there are no milestones defined. Please keep in mind that any application should always [adhere to our template](https://github.com/w3f/Grants-Program/blob/master/README.md#1-application). Feel free to ping me once you've updated your application or in case of further questions.

Dear takahser:
Hello!

Thanks for your timely review. According to your golden critiques, I have updated the application by adding **technical details** in _Development Status_ section and adding **expected deliverables** in _Development Roadmap_ section. That's what we plan so far. 

Feel free to have a look and give more feedback. Any other questions, feel free to ask me. Thanks for your kindly consideration!

Kindly Regards,
Jieliang Yin

**Review by takahser — CHANGES_REQUESTED** [review]
@hoho-yin thanks for the update and for adding additional information. However, you still didn't define the milestones in the same format as in the [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#milestone-1-example--implement-substrate-modules). Please add the tables, including the detailed deliveries, duration, FTE, costs, etc. Also, lmk if you have any further questions.

**Comment by hoho-yin** [comment]
> @hoho-yin thanks for the update and for adding additional information. However, you still didn't define the milestones in the same format as in the [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#milestone-1-example--implement-substrate-modules). Please add the tables, including the detailed deliveries, duration, FTE, costs, etc. Also, lmk if you have any further questions.

Dear @takahser:
Hello!

Thanks for your kindly feedback. Now I have added specific milestones into the proposal according to your template. I also revised other parts including team members and future plan. Feel free to have a look again and give any other golden critiques. Thanks a lot!


Kindly Regards,
Jieliang Yin

**Comment by semuelle** [comment]
Superseded by #942

**Pull request closed without merging**
