### PR TITLE
NuLink Update

### PR DESCRIPTION
**Pull request by pawnz0**
#455

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### CODE REVIEW

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I’m happy to approve this.

**Comment by Noc2** [comment]
@pawnz0 Fyi: It looks like you still need to sign the latest CLA.

**Comment by alxs** [comment]
Thanks for the amendment @pawnz0. I'll also approve it pending signature of the CLA. Just to double-check so there's no need for any more amendments, everything else in your delivery is as described in the application?

**Review by alxs — CHANGES_REQUESTED** [review]
Looking at the delivery it doesn't make sense to keep the deliverable. It's a simple set membership check.

**Comment by pawnz0** [comment]
> Looking at the delivery it doesn't make sense to keep the deliverable. It's a simple set membership check.

Thanks for the suggestion and there would not be any more amendments now.

**Review by alxs — APPROVED** [review]
Thanks, sounds good. You still need to sign the latest CLA (first comment on this PR).

**Review by Noc2 — APPROVED** [review]

**Review by takahser — APPROVED** [review]

**Pull request merged**
