### PR TITLE
BitBadges Integration Application

### PR DESCRIPTION
**Pull request by Mentors4EDU**
### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

We are working on creating a storage network module on substrate compatible w/ the BitBadges blockchain. This will allow for substrate to interact in a meaningful way with the BitBadges ecosystem, which follows an experimental PoCP or Proof of Computation proof. 

Other projects like [Crust](https://crust.network/) or [Subspace](https://www.subspace.network/) are within the same realm of trying to create some form of storage network. The difference is how BitBadges goes about accomplishing this and what a substrate module as an integration will provide. BitBadges as a whole is working on offline-centric networks and integrating variations of distributing sharding algorithms. Their data is transmitted w/ CouchDB being an integral part of its core for node syncronization. BitBadges is also integrating w/ various third party networks viewed as either pegs or applications. 

We believe that the substrate ecosystem can provide another integration w/ our network and we might even be able to create something similar to what Crust is doing on their mainnet, but w/ BitBadges as the storage method or a mirrored peg for the data. Our team, which is currently just two people, are passionate and have years of blockchain development experience under our belts. We think Substrate can work great as one of our third party integrations or pegged chains.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Comment by Mentors4EDU** [comment]
Hi, I been drafting an FAQs section and shall get this over to you this weekend.

**Review by Mentors4EDU — COMMENTED** [review]
Please see the FAQs section in regards to your questions.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the reply. But do you have any open source implementation of your blockchain? The paper, which you link contains almost no information (5 pages). Also regarding side chains, how exactly do they work in your case? Do you implement the information provided in the link, which you shared? (https://academy.horizen.io/technology/expert/cross-chain-transactions/) Regarding the deliverables, it’s best to just update these directly instead of adding additional information in the faq section. This way it’s easier for the rest of the team to understand your application.

**Comment by Noc2** [comment]
@Mentors4EDU Thanks for the reply, but the link, which you shared isn’t public. To be honest, based on the current level of details, I think there is very little chance of this grant being accepted.

**Pull request closed without merging**
