### PR TITLE
Update polkadot_stack.md

### PR DESCRIPTION
**Pull request by jonathanpdunne**
- Updating Polkadot Stack to include Talisman Wallet

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the PR. Really appreciated! But do you know if the extension is actually open source and if so could you update the link to the open source code instead of the website?

**Comment by Noc2** [comment]
> We'll open source the extension soon, but it's closed source for now! I can update the docs with the repository link when it's public.

That’s great to hear! I will put the PR on hold until it’s open source.

**Review by inderashah007 — APPROVED** [review]

**Comment by Noc2** [comment]
I’m closing this due to inactivity. Let me know if I should reopen it.

**Comment by inderashah007** [comment]
Hello guys

**Pull request closed without merging**
