### PR TITLE
LightSpell: XCM API

### PR DESCRIPTION
**Pull request by dudo50**
#### Project Abstract

This proposal aims to create the first XCM API for the Polkadot ecosystem. We have heard a number of times, that XCM API is very needed in the ecosystem. Alice & Bob's tweet goes to show this also [link](https://twitter.com/alice_und_bob/status/1664564442456109057?cxt=HHwWgsC9pdGi3JkuAAAA). This API will save developers from the need of integrating any packages into their dApp which will save space and headaches with dependencies. It will also be faster to generate calls and make dApp more responsive as heavy computing of generating calls will be lifted from them. The API will utilize already hardened and fully developed XCM SDK. 

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by dsm-w3f — COMMENTED** [review]
@dudo50 Thank you for the application. Let me ask some questions about it. I understood that the motivation to have an API for XCM is to easier integrate with apps and make faster requests. On the other hand, you will need to maintain a server running to make these requests, which you intend to ask for funds from the treasury to maintain. 

1. Do you know how many requests are expected to be performed to this API?
2. What are the numbers of the SDK today? 
3. The API is another option or is a migration for the SDK? Do you plan to maintain both options or all requests will pass to the API before being submitted to the blockchain?
4. How faster the XCM would be if using the API? Could you give me an idea about it?
5. As now the usage of the API incurs in having costs for you, how do you plan it to be financially sustainable over time?

**Comment by dudo50** [comment]
@dsm-w3f thanks for your questions!
We are going to answer them below:
1. We cannot predict this as we do not have metrics for how many XCM calls are generated by SDK as these are only known by dApps integrating the SDK. We can predict that at the beginning months, it wouldn't be over a few million which if we transfer into costs is not insanely expensive.
2. The SDK is used by Kodadot (The largest marketplace on Kusama), Basilisk team is planning the integration of it and there are some smaller projects like Sub-scaffold which we helped to create. Again we am unable to give full stats as some projects are not open source. We can only see, that SDK is integrated into 14 github projects total and has about 1.5k downloads per month see the picture below:
Screenshot 2023-06-23 at 21 40 26
What we can say is, that we expect usage to claim over time as getting new daps to onboard will be much simpler and faster with the introduction of API.
3. API is another option and both SDK and API will be maintained at the same time as SDK will be a vital part of API.
4. This figure is also unavailable as API is not yet developed. What we predict however is, that this will vary per use case as some applications are heavily dependent on generating calls if many users hit send button at the same time it could cause some heavy load on dApp servers. If the request is generated from API it offloads that dApp significantly. If these dApps are only for local use and each computer has to download them this will have a significant boost if the computer is not that powerful. On the other hand, if this wouldn't have major improvements in speeds for dApps that are running powerful servers it could at least bring their costs down and increase ease of integration.
5. For now we do not expect costs to be significant as our usage will claim slowly over time as we have to get old projects to implement API and new projects will implement API as well. Our plan to make this sustainable is to ask for maintenance funds from the treasury and Parachain teams that potentially could implement API in the future. Again, unable to predict anything long-term but our focus after the development of this API will be on getting those implementations rolling. If we are unable to get funds for our maintenance we will only ask for funds to cover server expenses and work for free. As our team have stated before we are not in this for profit and we see significant improvement this can bring to the ecosystem it is in our utmost interest to keep this project alive. If none things will work out we will pass the project to a well-funded team within the ecosystem that will be able to keep it running. It is hard to predict long-term sustainability with common good tools without business models or interests in making money from their users. 

We hope we answered all your questions. If any else occur feel free to ask them.
With kind regards,
Team ParaSpell

**Comment by dudo50** [comment]
Hey @keeganquigley !
Happy to answer your questions below:
1. Will update the unit tests asap!
2. It will always be free. That is our policy.
3. We have 2 more plans. Rework the maintenance request and add API to it. Lower the asking price and contact other Parachain teams that are most involved with XCM to try and cooperate with them. The last plan is just work for free as long as we are able and repeat after a while.

**Comment by keeganquigley** [comment]
Thanks @dudo50 sounds good, feel free to ping me once it is updated.

**Comment by dudo50** [comment]
Hey @keeganquigley,
proposal has been updated as requested.

With kind regards,
Team ParaSpell

**Review by keeganquigley — APPROVED** [review]
Thanks @dudo50 LGTM. I will also mark the application as ready for review and ping the rest of the committee to take a look.

**Review by Noc2 — APPROVED** [review]

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/introducing-complex-set-of-xcm-tools-paraspell/5625/1

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/enhancing-cross-chain-experience-of-your-dapps-with-revolutionary-xcm-tool-set-from-paraspell/8792/1

**Pull request merged**
