### PR TITLE
Deliberative Governance Stack for Web3

### PR DESCRIPTION
**Pull request by crjobo**
#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the new PR, but you are currently adding three files (=three proposals) to our repo. Could you update this?

**Comment by crjobo** [comment]
Ok, I squashed the file.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. But you are still adding three files to the repo.
Screenshot 2022-08-19 at 11 47 14

**Comment by crjobo** [comment]
Hi David, sometinhg is jinxed WITH e.  I wanted to update the file to adjust Costs and to delete the non relevant files. But now I see Only the Budget change is there and the rest of the Content is gone.  Def Need to Level up WITH GitHub.  I will correct this with a new commit. Antoine Gesendet von Mail für Windows Von: David HawigGesendet: Freitag, 19. August 2022 11:49An: w3f/Grants-ProgramCc: crjobo; AuthorBetreff: Re: [w3f/Grants-Program] Draft (PR ***@***.*** requested changes on this pull request.Thanks for the update. But you are still adding three files to the repo.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by crjobo** [comment]
Ok, I see that everything is there in the last Version in Application.So it Should good now. Antoine  Gesendet von Mail für Windows Von: David HawigGesendet: Freitag, 19. August 2022 11:49An: w3f/Grants-ProgramCc: crjobo; AuthorBetreff: Re: [w3f/Grants-Program] Draft (PR ***@***.*** requested changes on this pull request.Thanks for the update. But you are still adding three files to the repo.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Review by Noc2 — CHANGES_REQUESTED** [review]
Sorry for the late response here. I’m super busy at the moment. This looks good. I have only one more comment: In the total costs you say milestone 1: $25.000, but below it says 27k. Could you please update this? Ideally to 25k ;-)

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I’m happy to go ahead with it and share it with the rest of the committee.

**Comment by alxs** [comment]
@crjobo since your proposal has now been in the review state for over 2 weeks without any comments from other members of the committee, I'll go ahead and close it. This application may not have gotten enough votes to sway the committee, but don't be discouraged—check out other [sources of funding](https://github.com/w3f/Grants-Program#rocket-alternative-funding-sources) in the ecosystem, or otherwise you're always welcome to apply again with another project.

**Pull request closed without merging**
