### PR TITLE
Amended application for the bit.country m2.

### PR DESCRIPTION
**Pull request by justinphamnz**
Good day,

As suggested in the original m2 application, we have amended the scope and deliverables in this application. 

### Changes logs.

> Changes summary.
There are some changes from the original [application](https://github.com/w3f/Grants-Program/pull/305). 
The reason for the changes is that some UI features that were not aligned on our roadmap and we shifted more focus on delivering public testnet and canary network.

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the PR. Could you update the [original contract](https://github.com/w3f/Grants-Program/blob/master/applications/bit_country_m2.md) and not create a new file?

**Comment by justinphamnz** [comment]
Thanks @Noc2  for the feedback, I just updated the [original contract](https://github.com/w3f/Grants-Program/blob/master/applications/bit_country_m2.md).
Please let me know if there is any change required.

**Review by semuelle — COMMENTED** [review]
- Regarding `1b`, instead of leasing functionality you want to implement fixed price sales? And this will be implemented within the Continuum pallet?
- Can you expand on how `NFT Sign Support` works? Do you store any information on-chain?
- What does `NFT-Future-Event (e.g. time capsule)` mean?
- As a seller, what motive would I have to limit my sales to a local NFT market?

**Comment by justinphamnz** [comment]
> * Regarding `1b`, instead of leasing functionality you want to implement fixed price sales? And this will be implemented within the Continuum pallet?

Yes, due to a big impact on coordinates change on the map engine after the lease expired as well as the business logic, we would like to park the leasing for now. We instead offer the fixed price set by the council for a certain period so metaverse can buy Continuum spot at a fixed price. The logic is on Continuum pallet.

> * Can you expand on how `NFT Sign Support` works? Do you store any information on-chain?

Sign to support NFT feature allows NFT holder can gain trust by getting signed by supporters, they can optionally contribute token which holds in that specific NFT fund. This not only support NFT financially but also publicity by number of supporters.

We store all information of supporters e.g AccountId on-chain.

> * What does `NFT-Future-Event (e.g. time capsule)` mean?

It's a special type of NFT that is only run by a game engine in a specific block. The execution logic handled off-chain.

> * As a seller, what motive would I have to limit my sales to a local NFT market?

There are some items in bit.country only available in local NFT market e.g land, subdivisions of that local metaverse. Global marketplace is designed for network-level item e.g raw land, global building, avatars and games. As a seller, really depends on what type of product you are selling.

**Review by alxs — APPROVED** [review]
LGTM. When do you intend to deliver?

**Review by Noc2 — CHANGES_REQUESTED** [review]
Looks good, but I have one more request: Could you maybe add the programming language to the deliverables? This might help to clarify a few things, for example I’m currently not sure how NFT Market will be implemented (UI, CLI, etc.).

**Comment by justinphamnz** [comment]
> LGTM. When do you intend to deliver?

Thanks @alxs. We are adding some more validation and unit tests on the newly added features to ensure all conditions are covered. We tend to make a delivery PR by the end of the week.

**Comment by justinphamnz** [comment]
> Looks good, but I have one more request: Could you maybe add the programming language to the deliverables? This might help to clarify a few things, for example I’m currently not sure how NFT Market will be implemented (UI, CLI, etc.).

Thanks David @Noc2.

I just updated the programming languages, the deliverables are developed on-chain so mainly Rust. The NFT marketplace deliverable logic is handled purely on-chain, we also will share the fully functional version through either Docker or UAT access.

**Comment by Noc2** [comment]
> > Looks good, but I have one more request: Could you maybe add the programming language to the deliverables? This might help to clarify a few things, for example I’m currently not sure how NFT Market will be implemented (UI, CLI, etc.).
> 
> Thanks David @Noc2.
> 
> I just updated the programming languages, the deliverables are developed on-chain so mainly Rust. The NFT marketplace deliverable logic is handled purely on-chain, we also will share the fully functional version through either Docker or UAT access.

So, just to double check: A front-end is not part of this deliverable only pallets, correct? (because you now added the programming language of the UI as well).

**Comment by justinphamnz** [comment]
> > > Looks good, but I have one more request: Could you maybe add the programming language to the deliverables? This might help to clarify a few things, for example I’m currently not sure how NFT Market will be implemented (UI, CLI, etc.).
> > 
> > 
> > Thanks David @Noc2.
> > I just updated the programming languages, the deliverables are developed on-chain so mainly Rust. The NFT marketplace deliverable logic is handled purely on-chain, we also will share the fully functional version through either Docker or UAT access.
> 
> So, just to double check: A front-end is not part of this deliverable only pallets, correct? (because you now added the programming language of the UI as well).

Yes, that's right. A front-end is not part of this deliverable. We can demonstrate the UI on Docker or give the team access to the UAT environment.

**Review by semuelle — APPROVED** [review]
Thanks for the clarification. Works for me.

**Review by Noc2 — APPROVED** [review]

**Review by alxs — APPROVED** [review]

**Pull request merged**
