### PR TITLE
Pennyworth

### PR DESCRIPTION
**Pull request by EmmyConceptNg**
#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`pennyworth.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) or BTC address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by EmmyConceptNg** [comment]
I have read and hereby sign the Contributor License Agreement.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for your interest in our grants program. However, the milestones are not yet defined and contain copies of the template that don't make a lot of sense, like substrate module X. Could you update this?

**Comment by keeganquigley** [comment]
pinging @EmmyConceptNg

**Comment by semuelle** [comment]
I am closing this application due to inactivity. Please let me know if you would like to continue working on it, @EmmyConceptNg.

**Comment by EmmyConceptNg** [comment]
I’m really sorry. I’ll work on the suggestion today

**Comment by keeganquigley** [comment]
Hi @EmmyConceptNg I'm still not seeing that there have been any changes so I'm going to close again due to inactivity. Let us know if you have any questions.

**Pull request closed without merging**
