### PR TITLE
LIP payments pallet

### PR DESCRIPTION
**Pull request by olanod**
### Project Abstract

This is a ~~amendment~~ successor to our initial [PLIP proposal](https://github.com/w3f/Grants-Program/blob/master/applications/plip.md) to accommodate to the update scope of the Virto Network(previously Valibre). 

This proposal focuses on the core primitive of the [Virto Network](https://virto.network), the **payments pallet** that will enable our mission of providing decentralized infrastructure for marketplaces with local impact. 

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Comment by semuelle** [comment]
Thanks for the submission, @olanod. We use the term 'amendment' for minor changes to an existing grant. Given that the scope and funds in this proposal are quite different from your previous grant (#520), I have replaced the term in your PR above. It also means that the previous grant will be cancelled if this application is accepted. That's just a technicality, though.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Could you maybe also update the old application as part of the PR, so we don’t forget about it? See for example https://github.com/w3f/Grants-Program/pull/653/files as reference. Just add terminated and link to the reason. Also it seems you increased the price quite significantly. Do I understand correctly that you now want to have 48k for a single pallet?

**Comment by olanod** [comment]
@Noc2 yes we did greatly underestimate our costs of development and timelines(as we developers usually do). Being a project we've been working on for almost the entire year going through different phases of redesign and iteration, the proposal might not even reflect the actual costs of development.  
We believe our *single pallet* that represents the core of our technology will be of great benefit to the community and hope it can become the enabling primitive that will connect projects in the ecosystem and give crypto in general utility in the real world :)

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. I will share the application with the rest of the team and I'm aware that sometimes the development of such a project requires a lot of iterations and a lot of additional work. However, teams that don’t develop core infrastructure shouldn’t seek to cover 100% of their early-stage funding via our grants program. Therefore, in my opinion the current grant application is too expensive and I personally won’t approve it at this price point. Feel free to reduce the price or wait for additional feedback from others.

**Comment by olanod** [comment]
Thanks for the feedback :) No problem updating the price to something that feels more suitable, right now our team values more the "Web3 grant" status than its profitability. Wanted to note that by no means we are trying to cover 100% of our (non-so-)early-stage funding, perhaps I'll also mention "self-funding" and my previous affiliation with Valiu in the last section of the document to reflect better the effort put in the project for the past couple of years. 

Just sharing thoughts and context, I guess in my effort to reduce the scope of our application to make it more digestible and simpler to asses I made the mistake to make it look too simple, sometimes it's actually harder to write less code which I think It's the case with payments pallet, we went from a whole chain with multiple pallets doing one thing(on&off ramps) to a slick general purpose pallet that fits well in any chain and can have way more use cases, all thanks to not rushing and taking time to gather feedback from real non crypto users that are the ones that will ultimately benefit from what we're building.

For the price adjustment, the estimation was based only on the time spent last couple of months and **1 FTE -> 80kUSD/h**(I've rejected Rust/Substrate offers higher than that😳 ... blame desperate teams I guess? 😅). With a lower rate of **1 FTE -> 60??USD/h** the total value would be **36000 kUSD**, does it look more appropriate?. 

One last thing, what does core infrastructure look like? we have hopes to continue breaking down our infrastructure in smaller pieces that can apply for grants, perhaps is not the best approach? it's been a goal from the begging to try to keep Virto Network "pure" and not depend(for now) on institutional investment but I'm not sure now it's the best thing to do.

**Review by Noc2 — APPROVED** [review]
Thanks for your update and reducing the price. I completely understand your point (especially regarding rust developers) and I’m willing to accept it at the current price rate. Regarding core infrastructure, obviously this is hard to define (especially in advance),  to me this is software that a lot of projects in our ecosystem can and will leverage.

**Comment by alxs** [comment]
Looks good to me @olanod. Could you also add an article to the milestone 2 deliverables, similar to delivery 0e. [in the template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#milestone-1-example--implement-substrate-modules)? This is generally mandatory for all grants and we can provide feedback on it as well as cross-promote it.

**Comment by olanod** [comment]
An article as in a blog post in our site that talks about what was built and how the Web3 grant made our dreams come true, etc? :)

**Comment by alxs** [comment]
Correct. The second part is up to you, but if it did, you should definitely mention it ;)

**Review by alxs — APPROVED** [review]

**Review by Noc2 — APPROVED** [review]

**Comment by mmagician** [comment]
Could you expand on the details of your deliverables of Milestone 1?
E.g. `Escrow functionality` is a broad term - please describe how you envision this being implemented in substrate. What I'm looking for is an idea of what kind of storage you will need, and what public interface your substrate modules will have.

**Comment by olanod** [comment]
@mmagician Since milestone 1 code is complete a good reference is the [pallet readme](https://github.com/virto-network/virto-node/tree/master/pallets/payment) and the code itself. Elaborating a bit more here, the escrow works by transferring funds to the recipient and holding the assets until the sending account calls a second extrinsic to release the funds(e.g. user received a product, bank transfer, etc). Users have an incentive to release the funds because the payment includes a fee that is returned to the user after the release, also each payment gets assigned a "judge" account via a configurable handler to resolve any disputes.

Let me know if I should include further details or write it in the proposal document

**Review by mmagician — APPROVED** [review]
Ah thanks! The pallet is a good reference indeed. Thanks for the info and good luck :)

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/kusama-2025-private-daos-regional-chains-lip-and-more/11394/1

**Pull request merged**
