### PR TITLE
Proposal: Schnorr Wallet

### PR DESCRIPTION
**Pull request by wuyahuang**
#### Project Abstract

The Schnorr Signature has been playing an increasingly important role in the blockchain ecosystem.

It is a simple algorithm leveraging elliptic curve cryptography, it enables several improvements over the existing scheme all while preserving all of its features and security assumptions. Notably, Schnorr signatures support “native multi-sig” which enables the aggregation of multiple signatures into a single one valid for the sum of the keys of their respective inputs. 

The Schnorr wallet is an aggregation signature wallet for the Polkadot ecosystem, based on the Schnorr signature.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (aUSD/USDT) address for the payment of the milestones is provided in the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by keeganquigley** [comment]
Hi @wuyahuang nice to hear from you again and thanks for the applications. The committee will take a look at it shortly. In the meantime, a few initial questions:

- We now offer USDT payments on Kusama (Statemine) and Polkadot (Statemint) instead of Ethereum. Would you be open to receiving it via one of these methods instead? If so can you modify the payment section to reflect this?
- Are you aware of the Subkey CLI wallet which supports `sr25519` Schnorr signatures?
- It sounds like you essentially want to build a multi-sig wallet. Have you checked the other [multi-sig projects](https://wiki.polkadot.network/docs/build-open-source) in the works to see if there is anything you can use?
- Are there any future plans to build out a front-end UI or do you intend to only build the CLI functionalities?

**Review by Noc2 — CHANGES_REQUESTED** [review]
See @keeganquigley message above. Apart from this, I also shared it with jeff.

**Comment by wuyahuang** [comment]
Hi, @keeganquigley Thanks for your quick reply.

* I will modify the payment hours later.
* Subkey is able to sign the transaction supports Ecdsa, Ed25519, and Sr25519. But not able to merge the Schnorr signature off-chain which is one of the most important parts that our proposal will bring to the community.
* All the multi-sig projects you mentioned are verified multi-signature on-chain, which is also a good solution. But our proposal is merging signatures off-chain, and only need to verify one merged signature on-chain.
* We are interested to build frond-end UI or any other tools based on Schnorr Signature, such as a website or iOS/Android implementation.

**Comment by burdges** [comment]
Is this for a wallet front end?  or a signature scheme?

**Comment by burdges** [comment]
The protocol described is insecure.  Alice could forge signatures by Bob if she can interact with Bob enough.  See https://eprint.iacr.org/2018/417.pdf  Also https://eprint.iacr.org/archive/2020/1245/1602243406.pdf 

I implemented two secure multi-signature protocols in schnorrkel, both musig and dwms, but the code is not production quality.  We've a parity dev who'll rewrite it to do arbitrary k-of-n thresholds, including the DKGs they require, likely with optimizations for large signer sets ala mugig2, and then help parity signer deploy it.

It's possible other wallets need help too though.  And yeah a bunch of UX questions exist.

**Comment by wuyahuang** [comment]
Hi, @burdges Thanks for your reply.

Our proposal is focusing on the personal security level of the private keys. This means that all private keys belong to the same person. For example, I'm able to store one private key in the wallet of my computer and store another private key in the wallet of my mobile phone. So if one private key is leaked, my account is still secure.

I think that merging the public key and merging the signature from the multi-party have a lot of potentials.

The k-of-n thresholds you mentioned is cool, looking forward to it.

**Comment by wuyahuang** [comment]
I'm closing this PR, perhaps this proposal conflicts with what the Parity team is working on.

**Comment by keeganquigley** [comment]
Thanks again for your efforts @wuyahuang and please feel free to take a look at our open [RFPs](https://github.com/w3f/Grants-Program/tree/master/docs/rfps) to see if any other ideas strike your fancy.

**Pull request closed without merging**
