### PR TITLE
Amendment: Payment Address

### PR DESCRIPTION
**Pull request by Fiono11**

### CODE REVIEW

**Review by semuelle — APPROVED** [review]

**Review by PieWol — APPROVED** [review]

**Comment by semuelle** [comment]
For reference: https://github.com/w3f/Grants-Program/pull/2250

**Comment by PieWol** [comment]
Hey @Fiono11 ,
thanks for providing your banking details. We have received them. In order to switch from USDC to FIAT, we still need a Polkadot address of yours so that we can transfer the vested DOT which make up for 30% of the total amount. Thanks!

**Review by PieWol — CHANGES_REQUESTED** [review]
See comment. Please include a Polkadot address of yours for the vested DOT.

**Comment by Fiono11** [comment]
> Hey @Fiono11 , thanks for providing your banking details. We have received them. In order to switch from USDC to FIAT, we still need a Polkadot address of yours so that we can transfer the vested DOT which make up for 30% of the total amount. Thanks!

Done!

**Review by PieWol — APPROVED** [review]
Great, thanks!

**Review by keeganquigley — APPROVED** [review]

**Review by semuelle — APPROVED** [review]

**Pull request merged**
