### PR TITLE
Create tracking_chain.md

### PR DESCRIPTION
**Pull request by FedeC87p**
#### Project Abstract

Streamlining Blockchain Adoption for Enterprise Companies: Building Infrastructure to Enable Web2 Integration

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the application. I have one quick feedback: We usually don't support the development of solidity smart contracts. The reasons for this are that we are no experts when it comes to solidity, and it's hard to track what already exists and what doesn't. Also, it's not native to our ecosystem. So we would be much more willing to support an ink! implementation of this for example. Would you be willing to change it?

**Comment by FedeC87p** [comment]
Hello, thanks for the feedback. The Ink! version was already planned in the future planning phase (aka milestone 3 for which I didn't want to apply for funding from w3f). I can move it to milestone 2, although it will result in a delay in the delivery of that milestone. However, there's no problem as this architecture aims to be a transparent bridge to the language in which the smart contract is written. The potential of the project doesn't concern the development of the smart contract itself (which is actually in a different repository), but rather providing a scalable infrastructure that can call any smart contract for anyone who needs it.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. I have a follow-up question/request: Could you define "It will be used to support the massive request for data to be included in the smart contract." a little bit more? Same for the second milestone. I know you mention above in the application that smart contract means ink! and solidity, but it would be nice to have this also defined as part of the milestone tables since these are actually deliveries that will be double-checked.

**Comment by FedeC87p** [comment]
Sorry, I was rather unclear. I just proceeded to give a more detailed description. If that wasn't enough I've also started a Wiki (which is part of the required documentation stuff) where they are covered in more detail https://github.com/TrackingChains/TrackingChain/wiki/ . I remain available should there be a need for further insights.

**Comment by FedeC87p** [comment]
Hi, I hope I understood correctly, should the smart contract be included in Milestone 1? I proceeded to move it to 1 and review the delivery times.
I also added the languages used for each of the services

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I'm happy to go ahead with it and share it with the rest of the team.

**Review by keeganquigley — APPROVED** [review]
Thanks for the application @FedeC87p this looks very interesting. I've always thought that supply chain management is one of the biggest use cases for blockchain and therefore has a lot of room for improvement. I'm happy to go forward with it as well.

**Pull request merged**
