### PR TITLE
feat: add SubGame Network m2

### PR DESCRIPTION
**Pull request by xtony77**
### Project Abstract

In [Milestone 1](https://github.com/w3f/Grants-Program/blob/master/applications/SubGame_Network.md), we created the first game module, and then we will add more game modules for users to apply. Now, in the Milestone 2 of SubGame, we will launch other game modules in succession. In order to display and explain these game modules and circulate them, we will build a pallet module lease platform where other users can lease. The way of leasing is to obtain the right to use the module according to his needs, so that other developers can easily develop games through the platform. Using the advantages of blockchain decentralization, compared with real leasing, to avoid the risk of performance, as well as the full traceability of leasing, to ensure the authenticity and non-tampering of data, which will upgrade the virtual currency ecology to a new level.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Comment by mmagician** [comment]
Please note that the total cost should be specified in USD - bitcoin payment is possible, but the exchange rate will only be determined at the time of payment.

**Comment by xtony77** [comment]
@mmagician The total cost has been modified to USD.

**Comment by mmagician** [comment]
Thanks. I'm glad to see that you're continuing to work on your project. Could you please explain what happens after a user successfully completes the lease step? What does it mean, on a technical level, that a user has access to a module for a limited time? They have permission to use the source code in their own chain?
Or rather, does the SubGame team deploy each module into your runtime, and then allow the users to call methods on that pallet? (in which case, would you keep some kind of a whitelist of users?). Perhaps you could illustrate this all with an example?

**Comment by xtony77** [comment]
1. First, there is the question of time constraints, the permissions will disappear after the subscription period, and you need to stake to renew. Since our lease platform is a subscription system, it is not free. We will develop some game pallets and put them on the lease platform. Other users can subscribe to our pallet through stake and call the pallet on our chain. Compared with their own Development, leasing on our leasing platform can reduce a lot of development times.
2.  Then, after successfully leasing, the user will go to the following page, which supports the Markdown format, so the developer will directly attach the usage method of the pallet to the top, include how to call methods on that pallet.

    e.g.
    
    
3. Finally, because it is a subscription system, users need to stake the subscription before they can use it. Of course, the pallet is open source, and any user can move it to their own chain, but our lease platform saves users a lot of trouble in setting up infrastructure.

**Comment by mmagician** [comment]
I see, thanks for the answers, that all makes sense. Still, I wonder - the game developer needs to agree to a fixed set of functions inside the game that you deployed with your pallet, and if they want to get updates, they need to rely on you to upgrade the runtime. And I imagine it would only make sense for *one* such developer to use this pallet (otherwise the same game would get deployed twice - not much benefit for neither the users nor developers probably). And why doesn't the pallet creator deploy the game themselves, rather than leasing it out - assuming that the game makes brings some profit, I would think it's in the interest of creator to benefit first, no?

**Comment by xtony77** [comment]
1. I know what you mean. First of all, we lease a pallet. The pallet is a specific function (such as drawing/synthesis/combat... etc.) rather than the entire game, so our expected usage scenario is that the user will lease and need to build The function of own game. Therefore, the main game logic will be packaged by other game developers, but some functions will use our pallet. The degree of use depends on other game developers, so the same game will not appear multiple times.
2. Then, of course we will deploy our own games, but the lease is still the pallet, not the entire game. The reason for this is to maintain the diversity of the game. If it is to lease a deployed game, the same game will appear multiple times like you said. Finally, if it is operated in the form of a lease pallet, because the pallet is a single function, although users may rely on our upgrade, the impact is not significant.

**Comment by mmagician** [comment]
Right, makes sense. I have a really hard time imagining this model being adopted by developers (compared to the devs building and deploying their own modules), despite all the arguments you've provided. I do think the general idea of leasing out modules is very interesting though and is something that could be re-used by the wider community, I hope - so overall, I'm on the fence here.
Would it perhaps be possible for you to reduce the cost such that you fall under Level 1 grant (i.e. to $10,000)? Let me know if this option is feasible, I think this way it would be much easier to get your application through with the committee (I'll be already happy to support, so then you would just need 1 extra approval).

**Comment by xtony77** [comment]
We understand what you mean. The team also hopes to be approved. In terms of price, our team has some flexibility. However, Level 1 is a Individuals plan. We still hope to pass the review as Level 2, thanks!!

**Comment by mmagician** [comment]
It is not strictly necessary to be a solo developer to apply for Level 1. Mostly it's about the price - the lower the price, the quicker it should be to get the necessary approvals.

**Comment by xtony77** [comment]
Okay, we understand that our team has revised the price and handed it to you for approval, thanks!

**Review by mmagician — APPROVED** [review]

**Review by Noc2 — APPROVED** [review]

**Pull request merged**
