### PR TITLE
SubFlow: Web3 microblogging Smart Service

### PR DESCRIPTION
**Pull request by deus4**
#### Project Abstract

SubFlow aims to develop a decentralised social media platform that empowers users with control over their data and interactions.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).
- [x] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@antsu:matrix.org`

### CODE REVIEW

**Comment by deus4** [comment]
> I have read and hereby sign the Contributor License Agreement.

I have read and hereby sign the Contributor License Agreement.

**Comment by deus4** [comment]
I have read and hereby sign the Contributor License Agreement.

**Review by Noc2 — CHANGES_REQUESTED** [review]
(Requested changes in the private room)

**Comment by keeganquigley** [comment]
For reference, conversation has moved to https://github.com/w3f/Grants-Program/pull/1997

**Pull request closed without merging**
