### PR TITLE
project_Nomis.md

### PR DESCRIPTION
**Pull request by sxlveign**
### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying?

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] I have read and understood the [FAQs](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md), [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md) and [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).
- [x] I prefer the discussion of this application to be in a private Element/Matrix channel. My username is: ``@sxlveign``

### How Did You Hear About our grants program?

- [x] Social Media
- [ ] Hackathon
- [ ] Personal Recommendation
- [ ] Substrate Builders Program
- [ ] Investor/VC
- [ ] Online Search
- [ ] Other: _______

### CODE REVIEW

**Comment by semuelle** [comment]
@sxlveign, is your homeserver matrix.org?

**Comment by sxlveign** [comment]
> Hi @sxlveign, thanks for your application. We will look into it as soon as possible. Is your homeserver matrix.org?

Hi @semuelle. Thanks for your response. No, we're not using matrix.org.

**Comment by semuelle** [comment]
Well, I need it in order to invite you to the private chat.

**Comment by semuelle** [comment]
Chat is [here](https://matrix.to/#/!jFAQCCgrTCcrjXbvTB:web3.foundation?via=web3.foundation)

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks again for your grant application and your interest in our grants program. However, the grants committee wasn’t fully convinced by your application. I’m therefore closing the PR. Feel free to apply again in the future.

**Pull request closed without merging**
