### PR TITLE
Create proposal for bison

### PR DESCRIPTION
**Pull request by philoniare**
#### Project Abstract

A streamlined developer tool for Solidity smart contract deployment and testing on Polkadot.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [X] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (Polkadot AssetHub (USDC & DOT) address in the application and bank details via email, if applicable).
- [x] I understand that an agreed upon percentage of each milestone will be paid in vested DOT, to the Polkadot address listed in the application.
- [x] I am aware that, in order to receive a grant, I (and the entity I represent) have to successfully complete a KYC/KYB check.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by SBalaguer** [comment]
@philoniare thanks for the proposal, this indeed is very interesting for me as well. I would, however, ask you to instead of forking Foundry making this proposal about contributing upstream directly to Foundry so that they support natively Polkadot. This way we ensure that current Solidity Developers don't have to go hunting for another tool, but rather use the development flow that they are familiar with today.

At the same time, I would also encourage you to make sure Polkadot Asset Hub is a target usable within Foundry. The community has already approved the development of EVM on AH, and it will be very important to ensure the success of it that all the tools people are used to using on EVM land are compatible on AH as well. Foundry, particularly, is a very important tool.

**Comment by philoniare** [comment]
@SBalaguer Thank you for the insightful feedback. I agree that integrating Polkadot support directly into Foundry would be the ideal long-term goal. However, for this initial iteration, I believe that building an independent tool first would be more practical for a few reasons.

The first issue is the complexity of adding Polkadot and JAM support into Foundry. Polkadot’s non-EVM PolkaVM environment introduces a different dependency tree, particularly with tools like `subxt`. This would add significant complexity to Foundry’s current architecture, which is heavily optimized for EVM-based workflows. I worry that attempting to integrate this from the outset could make the project cumbersome, slowing development and potentially fragmenting the tool’s user base.

Furthermore, I’d prefer to ensure the project’s success and stability first before pushing for upstream changes in Foundry. We want to showcase solid community support, proven use cases, and a stable toolset before proposing to merge into Foundry. This way, we can approach the Foundry community with a tested, working solution that has clear benefits and a demand from developers already using Polkadot and JAM protocols.

I still believe there will be an opportunity to merge into Foundry at a later stage, but for now, focusing on delivering a standalone, optimized tool that fits the Polkadot ecosystem is a more achievable and valuable first step.

Thanks again for your input, and I look forward to continuing the discussion as the project evolves.

**Review by keeganquigley — APPROVED** [review]
Thanks for the thorough answer @philoniare based on your previous work I'm also willing to approve.

**Review by Noc2 — APPROVED** [review]

**Comment by keeganquigley** [comment]
Hi @philoniare just checking in, how is M1 coming along?

**Comment by philoniare** [comment]
Hey @keeganquigley, thanks for checking in. I was asked to make pivot as Parity is already working on this project internally: https://github.com/paritytech/foundry-polkadot. Given that the project has already been accepted, what vertical can I pivot to for this grant?

**Comment by philoniare** [comment]
> Hey @philoniare thanks for the update. Would you be interested in working on supporting tech such as plugins?

Ofc! More than willing, I'll update my proposal, thanks for the suggestion.

**Comment by keeganquigley** [comment]
Hi @philoniare did you ever submit an amendment PR to update the proposal?

**Comment by keeganquigley** [comment]
Hi @philoniare just an update, we will close this in the next few days due to inactivity if we don't hear back. Thanks!

**Comment by keeganquigley** [comment]
Hi @philoniare the grant has been canceled due to inactivity, please see above.

**Pull request merged**
