### PR TITLE
Cross-chain Wallet - XCW

### PR DESCRIPTION
**Pull request by 0xslipk**
#### Project Abstract

Blockcoders is proud to propose the development of a revolutionary cross-chain wallet, capable of importing and creating both EVM and WASM accounts. This wallet will make it easy for users to manage and transfer tokens between the two chains. Built with the user experience in mind, the wallet will feature the same sleek and intuitive design as Astar or Moonbean UI. The term cross-chain in this case refers to the ability to transfer tokens between parachains for both EVM and WASM.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (aUSD/USDT) address for the payment of the milestones is provided in the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. I have some quick initial feedback/comments: 

- For UI-focused applications, we usually ask teams to provide initial designs or mock-ups. For example, your first milestone currently could simply be you reusing the polkadot.js extension or something similar and integrating the possibility to show EVM balances. It would be nice to have more details here. 
- The deliveries and the specification are basically the requirements of our contracts that we need to evaluate. “Enhance the design and user experience of the wallet.” for example, could be anything. Could you define these better? 
- Do you have a plan to maintain the project? We supported multiple wallets that are no longer maintained in the past, so we would like to avoid this.

**Comment by 0xslipk** [comment]
> Thanks for the application. I have some quick initial feedback/comments:
> 
> * For UI-focused applications, we usually ask teams to provide initial designs or mock-ups. For example, your first milestone currently could simply be you reusing the polkadot.js extension or something similar and integrating the possibility to show EVM balances. It would be nice to have more details here.
> * The deliveries and the specification are basically the requirements of our contracts that we need to evaluate. “Enhance the design and user experience of the wallet.” for example, could be anything. Could you define these better?
> * Do you have a plan to maintain the project? We supported multiple wallets that are no longer maintained in the past, so we would like to avoid this.

Awesome, Thank you for the feedback, we are gonna work on these item and get back to you.

**Comment by Noc2** [comment]
Let me know if I should take another look at the application.

**Comment by 0xslipk** [comment]
> Let me know if I should take another look at the application.

Hi @Noc2,

We addressed the comments. Please take a look and let us know what do you think.

Thank you.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update and for sharing the mock-ups. I will mark the application as ready for review. But I also have some additional questions/comments: The hourly rate seems to be different for different milestones at the moment. Why is this the case? Especially the second milestone seems to be extremely expensive. Would you be willing to reduce the price a little bit?

**Comment by fersirni** [comment]
Hi @Noc2! I just reviewed the proposal and fix that! You will notice that we reduce it from 75k to 64k :+1:

**Comment by randombishop** [comment]
One more question about the security approach to storing the private keys: can you elaborate on where and how these will be stored?

**Comment by fersirni** [comment]
@randombishop

**"I'd like to understand more about the specifics of XCM Wallet: how will it be different from existing projects like [Talisman](https://github.com/TalismanSociety/talisman-web) or [Primis](https://github.com/Primis-Labs/client)? Why not simply add the XCM/XVM feature to an existing one? (Either through collaboration with the team or after forking their repo)"**

> The XCM Wallet aims to differentiate itself from existing projects like Talisman and Primis by providing support for both EVM and WASM accounts and the ability to transfer assets between them. This feature is not currently available in any other wallet in the ecosystem. Instead of adding this feature to an existing wallet or forking an existing repository, we want to build a new wallet with a user-friendly interface that makes it easy for users to understand and use.

**"We also already have a project in the ecosystem who developed an [sdk](https://github.com/paraspell/sdk) and a [ui](https://github.com/paraspell/ui) to teleport assets between parachains using XCM, will you leverage that existing SDK or build a different version? If the latter, can you please provide the reasons?"**

> We have an open grant for our own XCM SDK and we are expecting to use it to teleport the assets between parachains. Regarding the UI, we believe it is not the same experience to have a platform vs a wallet, it is way more easy for users to have their tokens in one place and be able to move them without having to use some external tool.

**"Ideally, I would prefer to move forward with this project if it were a new feature built on top of one of the existing open source solutions, that way it would be easier to specify the exact deliverables; and reduce the scope and cost. But I am open to be convinced otherwise after hearing your arguments and the opinions from the other evaluators."**

> We understand your concern about creating a new feature on top of existing solutions. However, we believe that creating a unique and differentiated product is crucial for the success of this project. Our team has a strong track record of creating and maintaining our own set of projects, such as the Ink Explorer which can now deploy Ink contracts to any parachain that is using the contracts pallet. This experience and expertise will be leveraged to create a high-quality, secure and user-friendly XCM Wallet.
We believe that offering new features and capabilities that are not currently available in the ecosystem will provide significant value to users and contribute to the growth of the Polkadot/Substrate/Kusama ecosystem. In addition, we have a clear plan and roadmap for the development, launch and maintenance of the XCM Wallet, which will provide a clear set of deliverables and timelines.
We understand that collaboration is important and we are open to integrate other technologies to improve the wallet and we are willing to work with other projects to achieve that. We are committed to maintaining the XCM Wallet and providing continuous support to users through Telegram and Discord channels. We believe that our approach will provide a comprehensive and valuable solution for the ecosystem.

**"One more question about the security approach to storing the private keys: can you elaborate on where and how these will be stored?"**

> We are committed to ensuring the security of our users' private keys. To achieve this, we plan to implement the Keyring concept, which is the core of the secret storing and account management system in MetaMask. This approach ensures that private keys are stored locally on users' devices using browser built-in storage capabilities such as IndexedDB or WebSQL, making them accessible only to the user. Additionally, we will use encryption techniques similar to MetaMask, such as PBKDF2 iteration and AES-GCM mode, to provide an extra layer of security for the private keys. We understand the importance of security in the blockchain space and are confident that these measures will ensure the safety of our users' assets. We plan to implement the same feature that Polkadot's extension has, which allows users to see the availability of different parachains before they make a transfer. This feature will provide users with an added layer of security and peace of mind, as they can ensure that their transfer will go through smoothly.

**Review by Noc2 — APPROVED** [review]
Thanks for the detailed reply and for reducing the price. I’m personally happy to support this project.

**Review by randombishop — DISMISSED** [review]
@fersirni Thank you for your answers. I am curious now to see how this new wallet will look like, and happy to approve this application.

**Review by keeganquigley — DISMISSED** [review]
Thanks for the application @fersirni. Seeing that your team does have a strong track record and you seem to know what you're doing when it comes to security, I'm happy to go ahead and approve it as well. Looking forward to seeing what you come up with.

**Comment by fersirni** [comment]
Thanks for your replies! Looking forward to start this amazing project!

**Comment by 0xslipk** [comment]
Thank you guys for you support and feedback. We just added a section about the [security](https://github.com/w3f/Grants-Program/blob/444d7187d98a25607132528f1846206334d0768d/applications/cross-chain-wallet.md#security) of the wallet.

Please take a look of that @Noc2 @randombishop @keeganquigley

**Review by keeganquigley — APPROVED** [review]

**Review by randombishop — APPROVED** [review]

**Review by dsm-w3f — APPROVED** [review]

**Review by gautamdhameja — APPROVED** [review]

**Pull request merged**
