### PR TITLE
RV KMIR Grant

### PR DESCRIPTION
**Pull request by ehildenb**
applications/rv-kmir: closer to original template

applications/rv-kmir: copy application template

applications/rv-kmir: first draft

applications/rv-kmir: corrections to application

#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (aUSD/USDT) address for the payment of the milestones is provided in the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — APPROVED** [review]
Thanks for the updated application. I mark it as ready for review and share it with the rest of the team. I'm also personally happy to go ahead with it.

**Review by randombishop — APPROVED** [review]
LG. Happy to approve this exciting line of R&D.

**Review by gautamdhameja — APPROVED** [review]

**Review by keeganquigley — APPROVED** [review]

**Comment by ehildenb** [comment]
Wooow! Excited to get started! :smile:

**Comment by bhargavbh** [comment]
Thanks a lot for the application and we are excited to work with RV on this grant. 
I had a few comments on the proposal:

- It might be worthwhile to check out other attempts at formalising MIR semantics: https://github.com/nikomatsakis/a-mir-formality. It has formal models of MIR syntax, and layers for type-checking and declarations. Another attempt at defining the operational semantics is https://github.com/RalfJung/minirust for subset of Rust, which might be a good starting point. 

- Could you please provide more details on the strategy to prioritise MIR features in deliverables 2 &3? For instance, if verifying ink! smart contracts is the objective, then the conformance test-suite would have to include `procedural macros` feature.

**Comment by ehildenb** [comment]
`a-mir-formality` should definitely be a useful reference for us, it looks to attempt an operational semantics in PLT Redex.

MiniRust may be useful for reference, though maybe less directly useful than a-mir-formality.

**Comment by keeganquigley** [comment]
Hi @ehildenb how is milestone 3 coming along?

**Pull request merged**
