### PR TITLE
Zero Network: Privacy Preserving Transactions Blockchain based on Substrate

### PR DESCRIPTION
**Pull request by NoCtrlZ**
### Project Abstract

We would like to implement a `parachain` which specializes in privacy. This `parachain` supports **confidential transfers** and **privacy preserving smart contracts** on the mainchain based on the `plonk`. These functionalities are designed relying on only the **cryptographic hardness assumptions** instead `L2 technologies`, `TEE` and `centralized security assumption`. The documentation is [here](https://zero-network.github.io/).

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] Hackathon
- [x] Personal Recommendation
- [ ] Substrate Builders Program
- [ ] Investor/VC
- [ ] Online Search 
- [ ] Other: _______

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. This looks really interesting to me and is something which we really want to support. I shared it with @mmagician, who previously reviewed your delivery. Are you also aware of https://github.com/ConsenSys/anonymous-zether? Additionally, you might want to take a look at this patent: https://patents.google.com/patent/US20190164153A1/en But in general, I would be happy to jump on a call. Feel free to reach out to david@web3.foundation

**Comment by NoCtrlZ** [comment]
@Noc2 
Thank you for the reply.
> Are you also aware of `Zether`

Yes and it's described in grant paper [Similar Project](https://github.com/zero-network/Grants-Program/blob/master/applications/zero-network.md#similar-project) section.
And also propose the solution to their problem in documentation [Gas Limit](https://zero-network.github.io/1_3_gas_limit.html#gas-limit) section.
> Additionally, you might want to take a look at this patent: https://patents.google.com/patent/US20190164153A1/en

Thank you!
I didn't know this one.
I am going to take a look.
> I would be happy to jump on a call. Feel free to reach out to [david@web3.foundation](mailto:david@web3.foundation)

I would be happy too.
I sent a mail.
I would appreciate it if you would check.

Thank you.

**Comment by mmagician** [comment]
Looks pretty good to me, although I do have some questions regarding milestone 2 deliverables. Could you describe your exact strategy for doing e.g.:
`We are going to implement zk-[contracts](https://github.com/paritytech/substrate/tree/master/frame/contracts) pallet which allows us to execute deployed contract WASM binary on top of contracts pallet.`?
I am not sure what the above statement would entail on a technical level.
Same applies for other points from M2.

Finally, I've read through your documentation so far and was wondering whether you could expand on the frontrunning section? I understand the problem definiton, but can't really see what you mean by:
`To avoid this attack, we implement the pending transfer. The proof is generated for balance so by implementing pending transfer balance, we can save the transfer information without changing the balance used for proof. `

Thanks! Otherwise looks good.

**Comment by NoCtrlZ** [comment]
Hi @mmagician 
Thank you for the review!
> Could you describe your exact strategy for doing e.g.:

That makes sense.
I am going to add exact strategy to documentation because it's a bit complicated and core part.
Please give me three days.
>  I've read through your documentation so far and was wondering whether you could expand on the frontrunning section?

I added description about it.
https://zero-network.github.io/1_6_security_protection.html#front-running

Long story short, we implement extra state storage to handle the incoming transactions.
It doesn't change the user balance so generated proof is still valid even if the user receive incoming transactions.
The extra state storage will be processed after some block productions.

**Comment by NoCtrlZ** [comment]
Hi there.
I describe the confidential smart contract following.
I also updated the [documentation](https://zero-network.github.io/2_0_transaction_constraints.html)

# Confidential Smart Contract Implementation

## Flow
About confidential smart contract, we assume the following sequence.

1. Develop smart contract
2. Test smart contract
3. Compile smart contract
4. Deploy smart contract
5. Execute smart contract

I described on grant paper on [`Use Case`](https://github.com/zero-network/Grants-Program/blob/master/applications/zero-network.md#use-case) more detail.

## Components
In above flow, we need following components.

1, 2 -> `zkink! eDSL` on top of [ink::lang](https://github.com/paritytech/ink/tree/master/crates/lang)
3 -> `cargo-zk-contract` compiler on top of [cargo-contract](https://github.com/paritytech/cargo-contract)
4 -> `zk-contract` on top of [contracts](https://github.com/paritytech/substrate/tree/master/frame/contracts)
5 -> `client wallet`

## Implementation

### `zkink!` eDSL
`smart contract language`

We add encrypted number and hash function for commitment.
We change the account to ElGamal form and introduce homomorphic calculation.
We modify the `event`, `storage` and test, environment variable accordingly.

### `cargo-zk-contract` compiler
`smart contract compiler`

This inputs the smart contract consisting of eDSL and outputs the metadata.
The compiler converts smart contract eDSL to circuit gates and calculates the corresponding group of polynomials
This metadata describes the function input data (public / private) and polynomials (condition).
With this metadata, user can generate the witness for the proof.

### `zk-contract`
`smart contract runtime`

This changes the state according to Wasm opcode.
It's necessary to implement pending transfer and rollover function.
The `zk-contract` operations are only proof verification and state transition.
We remove operations we don't need anymore and `EVM` compatible.
We optimize the gas cost and change the address type to ElGamal form.

### `client wallet`
`transactor library`

This allows users to generate wallet and send transaction.
The user uses the two function `genWitness` and `genProof`

- `genWitness`
This inputs the metadata, input values and private key, and outputs the witness.

- `genProof`
This inputs the witness and srs, and outputs the proof.

Please feel free to ask questions.
I would appreciate it if you confirm.
Thank you!

**Comment by mmagician** [comment]
So the idea is for an end-user to use `zkink!` for compiling the contracts, instead of standard `ink!`? I assume that you'll be forking the ink repository, correct? Isn't there a way to instead integrate the changes necessary into upstream `ink!` (at some point), maybe behind a feature flag that enables zk compatibility? I'm not sure what the `ink!` team would think of that, of course :) I'm just worried about maintenance effort that'd need to go into maintaining such a forked library. Also, would the experience for a developer trying to write a smart contact in `zkink!` be the same, i.e. will they be able to port it directly from `ink!` and just use a different compiler (kind of like what all the zkEVM teams are trying to do - zksync, Scroll, Hermez etc).

**Comment by NoCtrlZ** [comment]
> So the idea is for an end-user to use zkink! for compiling the contracts, instead of standard ink!?
I assume that you'll be forking the ink repository, correct?

Yes.
> Isn't there a way to instead integrate the changes necessary into upstream ink! (at some point), maybe behind a feature flag that enables zk compatibility?

I think `zkink!` won't be compatible with `ink!` because the account is made by ElGamal encryption.
> will they be able to port it directly from ink! and just use a different compiler

That makes the most sense.
Let me check more details.

Thank you for the nice feedback!

**Review by Noc2 — APPROVED** [review]
I’m happy to already approve the application and mark it as ready for review so that others can take a look at it as well. Just want to point out that I was referring above to Anonymous Zether, which is slightly different from Zether and has this public available solidity implementation. Also I agree with Marcin’s point, in general it’s always hard to maintain a separate programming language (especially account based), but also it’s hard to convince enough people to start using it. Maybe you can reuse another programming language. But I'm not sure what’s the best solution here, so I’m also happy with zkink!

**Comment by Noc2** [comment]
@NoCtrlZ Do you have any specific questions for Oana?

**Comment by NoCtrlZ** [comment]
@Noc2 
Thank you too.
> Do you have any specific questions for Oana?

We are writing white paper.
Is it possible to be reviewed by her?
Of course we would be happy to add as co-author and acknowledgement if she wants.

**Comment by NoCtrlZ** [comment]
Oh wow...

Thank you @Noc2 
This must be the best support.

Hi @InaOana 
I am very honored with this opportunity.
I will finish white paper within 2 months.
I will do my best.

**Review by BenWhiteJam — APPROVED** [review]

**Review by rrtti — APPROVED** [review]

**Comment by alxs** [comment]
Hey @ashWhiteHat, any updates on the first milestone? Unless you plan to deliver soon, could you please submit an [amendment](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval) with an updated timeline?

**Comment by ashWhiteHat** [comment]
Hi @alxs 
Thank you for notice.
I am going to submit amendment.
We already implemented ElGamal encryption and made plonk compatible.
We are curious to introduce ecfft and complex multiplication to our protocol so it takes a bit more time than we expected.

**Comment by ashWhiteHat** [comment]
Hi @alxs 
I created PR about amendment.
I would appreciate it if you could confirm.
https://github.com/w3f/Grants-Program/pull/1258

**Comment by alxs** [comment]
Confirmed, thanks.

**Comment by alxs** [comment]
@ashWhiteHat I just realised that the amended deadline for the first milestone is in the past but it hasn't been delivered yet, did you mean January 2023?

**Comment by ashWhiteHat** [comment]
@alxs 
Yes exactly.
It's my mistake.

**Comment by ashWhiteHat** [comment]
Hi there.
We are working on milestone1.
https://github.com/w3f/Grants-Program/blob/master/applications/zero-network.md#milestone-1--confidential-transfers

The deliverable number 1, 2, 3 was done.

1. Lifted-ElGamal pallet
https://github.com/zero-network/zero/tree/master/primitive/elgamal
2. encrypted-balance pallet
https://github.com/zero-network/zero/tree/master/pallets/encrypted_balance
3. plonk pallet
https://github.com/zero-network/zero/tree/master/pallets/plonk

About 4, we are working on following PR.
https://github.com/zero-network/zero/pull/46

When it's merged, the milestone 1 is completed.
Please wait a while.

**Comment by Noc2** [comment]
Great to hear. Feel free to deliver the milestone once you are done. See https://github.com/w3f/Grant-Milestone-Delivery

**Comment by ashWhiteHat** [comment]
Thank you!
The implementation is almost done, we will deliver by the weekend.

**Comment by ashWhiteHat** [comment]
Hi there
I created PR about milestone 1.
https://github.com/w3f/Grant-Milestone-Delivery/pull/688

I would appreciate it if you could confirm.
Thank you!

**Comment by Noc2** [comment]
@ashWhiteHat Looks correct. One of our evaluators will look into it. Thanks

**Pull request merged**
