### PR TITLE
Bay Aggregator grant application

### PR DESCRIPTION
**Pull request by manangouhari**
#### Project Abstract

Bay Aggregator is a multi-parachain DEX aggregator with limit order functionality for the Polkadot & Kusama ecosystems.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (aUSD/USDT) address for the payment of the milestones is provided in the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks @manangouhari for the well written application.

- One of the main issues I see initially is that we don't generally support Solidity or EVM contract development since we are not experts in the field. Would you be willing to build them as ink!/WASM contracts instead? It sounds like you want to cater to the Moonriver/Moonbeam ecosystem in which case their [grants program](https://moonbeam.foundation/grants/) might be more suitable.
- Regarding [the title of M2](https://github.com/w3f/Grants-Program/pull/1455/files#diff-f7506a87ee2b39c7591f4cd04986865b61d466bdc1e3563da02bd2f2cd85ab03R192), please note that we don't pay to ship production ready code, so please consider rephrasing this and reducing the scope/price accordingly. The current price is relatively expensive compared to the previous YieldScan grants. 
- Can you include the front-end framework (Next.js, Tailwind) into the delivery tables?

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Just to add here: When it comes to solidity, it is also hard for us to judge what already exists and what needs to be developed by your team, given that it’s not our focus. There are probably already a lot of Solidity DEX Aggregator Protocols at this stage.. Please keep in mind that we only focus on the technical deliveries of the project (not the deployment etc. So if you want to focus on solidity, I would indeed try to apply for a grant from moonbeam or Astar instead.

**Comment by manangouhari** [comment]
Thank you for the feedback @keeganquigley and @Noc2. :pray:

Regarding @Noc2’s concern, our vision is actually to build “Dotsama’s Native DEX Aggregator” and the decision to start with EVM first was purely tactical. Because:
1. Majority of trading volume within the ecosystem is on EVM parachains.
2. WASM contracts are available only on one mainnet, Shiden.
3. Other parachains don’t support contracts and don’t have more than one DEX, hence, no need for an aggregator on any given parachain by itself.


However, we are on the same page regarding your feedback and are currently researching cross-parachain swaps for substrate native chains.

We shall update the application soon (current estimate: about 1 week) and share the same with you as soon as possible.

**Comment by Noc2** [comment]
Thanks for the update here.

**Comment by manangouhari** [comment]
Hey @keeganquigley, we’ve decided to table the grant application for the moment.
Though, we’re still highly interested in building Dotsama’s DEX Aggregator.

We feel that it may be too early for us to start working on this. Because the key pieces for a decentralized architecture, like the one we envision, are still in development. For example, Stateswap and multi-hop XCM.

If the grants committee would be open to it, we would love to revisit this proposal sometime down the line.
Thanks again for taking the time to review the proposal and sharing your valuable feedback, really appreciate it. :pray:

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. In this case, I will close the application. But feel free to reapply once you are ready.

**Pull request closed without merging**
