### PR TITLE
SimPolk, a simulator for Polkadot

### PR DESCRIPTION
**Pull request by ff13dfly**
### SimPolk, a simulator for Polkadot, coded by PHP.

> Goal of simPolk is that developers who have never been in contact with blockchain development, can quickly understand blockchain and Polkadot, then quickly build application on Polkadot.Just as myself.
> Currently,simPolk has released version 0.1.
>Demo: [http://simpolk.android.im/ui](http://simpolk.android.im/ui) ,
>Github : [https://github.com/ff13dfly/simPolk](https://github.com/ff13dfly/simPolk)

>More details:
>Introduction of simPolk : https://www.youtube.com/watch?v=FmbLfxatk0Q
>Roadmap of simPolk : https://www.youtube.com/watch?v=uHhSgAT014k

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Sounds like an interesting project. Could you add an english readme to https://github.com/ff13dfly/simPolk? (or it seems there is already a file but it doesn’t work). Also could you add concrete deliverables to the milestones? The tables currently only contain the default deliverables. These are basically the requirements of our contracts, so they should be as specific as possible.

**Comment by ff13dfly** [comment]
> Thanks for the application. Sounds like an interesting project. Could you add an english readme to https://github.com/ff13dfly/simPolk? (or it seems there is already a file but it doesn’t work). Also could you add concrete deliverables to the milestones? The tables currently only contain the default deliverables. These are basically the requirements of our contracts, so they should be as specific as possible.

Ok, will do. Thanks.

**Comment by ff13dfly** [comment]
> Thanks for the application. Sounds like an interesting project. Could you add an english readme to https://github.com/ff13dfly/simPolk? (or it seems there is already a file but it doesn’t work). Also could you add concrete deliverables to the milestones? The tables currently only contain the default deliverables. These are basically the requirements of our contracts, so they should be as specific as possible.

Sorry for the failure of the MD file, I used the base64 image by using typora, but github can not decode successful.

**Comment by Noc2** [comment]
Thanks for the update and no problem. Let me know once you added the deliverables to the tables and I should take another look at the application.

**Comment by mmagician** [comment]
Looks interesting indeed, I'm looking forward to seeing the full deliverables list!

**Comment by ff13dfly** [comment]
> Looks interesting indeed, I'm looking forward to seeing the full deliverables list!

Thank you. I will check the project file labeled ready for review and add the deliverables in details.

**Comment by ff13dfly** [comment]
Hi, @Noc2 @mmagician , have updated the deliverables in details. Hope it reach the standard.

**Review by mmagician — CHANGES_REQUESTED** [review]
@ff13dfly Polkadot and Kusama are using the account-based transaction model, not UTXO, perhaps you want to revise your deliverables and description.

Aside, I have a few questions:
1) I assume all the data that is available in the simulator is fake, right? How do you generate this data?
2) When I want to test how my application integrates with Polkadot, then as a developer I will most likely subscribe to the on-chain events or specific extrinsics via a websocket connection, or by making RPC calls to a node to retrieve some chain state/info. I don't see that much value in a purely UI-based simulator. Do you plan to support websocket and/or RPC connections?
3) What is the advantage of using a simulator over spinning up a local test network? It is really quite easy to run a local substrate node.

**Comment by ff13dfly** [comment]
@mmagician Thanks for comment. 

Question：Polkadot and Kusama are using the account-based transaction model, not UTXO, perhaps you want to revise your deliverables and description。

Answer:
That's very helpful. I will move UTXO part to blockchain knowledge part as the mining demo, and will update the deliverables by learn more about Polkadot.
I am a web developer using PHP and JS, felt pretty hard to run a substrate based paramchain and can not figure out the relationship of many new conception. By writing simPolk, I am confident that I can continue to develop on Polkadot. 

Q1:I assume all the data that is available in the simulator is fake, right? How do you generate this data?
The data is generated from the simulator which is localed "api/lib/simulator.class.php". When new block created or manually appended, coinbase transaction will happen. You also can transfer coins from fake account to another fake account in the UI. These transaction list will be written to a new block on the simchain.
The simchain can be pended to check data, that is very helpful for understanding the relationship between data.

Q2: When I want to test how my application integrates with Polkadot, then as a developer I will most likely subscribe to the on-chain events or specific extrinsics via a websocket connection, or by making RPC calls to a node to retrieve some chain state/info. I don't see that much value in a purely UI-based simulator. Do you plan to support websocket and/or RPC connections?
The UI is used to access the RPC of the simulator. Currently, the goal is to fixing the basic logic and using the same data structure as Polkadot. After that, new version will have the access to parachain as a gateway. User of simPolk can connect to the paramchain such as Kusama  very easily.


Q3:  What is the advantage of using a simulator over spinning up a local test network? It is really quite easy to run a local substrate node.
I have tried run a private chain by substrate and developed 2 pallet. But when the RUST updated or substrate updated, there are too much issue to fix and I failed to fix all of them.  So I have to pend the application virtural block world to Polkadot.
It is efficient to write a PHP file simulating a pallet. It is easy to fast iterating by interacting with application.

I think a video will be helpful to introduce simPolk, let me try.

**Comment by ff13dfly** [comment]
Have uploaded two videa to youtube.
1. Introduction of simPolk : https://www.youtube.com/watch?v=FmbLfxatk0Q
2. Roadmap of simPolk : https://www.youtube.com/watch?v=uHhSgAT014k

**Comment by mmagician** [comment]
> After that, new version will have the access to parachain as a gateway

Could you elaborate on this? I don't understand the comment. 

>  User of simPolk can connect to the parachain such as Kusama very easily.

So just a minor correction: Kusama isn't a parachain, but a relay chain in itself. Anyway, what do you mean by connecting to parachains? Will you be simulating the data from each parachain?

> The UI is used to access the RPC of the simulator.

So that means I will be able to run queries from the command line as well? What about websocket connection? In my point of view this is as important or more than RPC queries, since developers want to subscribe to events/Tx's happening on-chain in real-time (as opposed to actively making frequent RPC calls)

> I have tried run a private chain by substrate and developed 2 pallet. But when the RUST updated or substrate updated, there are too much issue to fix and I failed to fix all of them.

It is true that substrate is a moving target and breaking changes are still being introduced. However, now that parachain codebase is becoming more and more stable, one can expect the number of breaking changes will decrease over time. 
In addition, if you aim to create a simulator that is up to date with Polkadot, you should be aware that your simulator will *also* need to receive updates - otherwise, Polkadot moves forward while the simulator keeps serving blocks with outdated structure.

Finally, are you planning to support [all RPC calls](https://polkadot.js.org/docs/substrate/rpc)?

**Comment by ff13dfly** [comment]
> > After that, new version will have the access to parachain as a gateway
> 
> Could you elaborate on this? I don't understand the comment.
> 
> > User of simPolk can connect to the parachain such as Kusama very easily.
> 
> So just a minor correction: Kusama isn't a parachain, but a relay chain in itself. Anyway, what do you mean by connecting to parachains? Will you be simulating the data from each parachain?
> 
> > The UI is used to access the RPC of the simulator.
> 
> So that means I will be able to run queries from the command line as well? What about websocket connection? In my point of view this is as important or more than RPC queries, since developers want to subscribe to events/Tx's happening on-chain in real-time (as opposed to actively making frequent RPC calls)
> 
> > I have tried run a private chain by substrate and developed 2 pallet. But when the RUST updated or substrate updated, there are too much issue to fix and I failed to fix all of them.
> 
> It is true that substrate is a moving target and breaking changes are still being introduced. However, now that parachain codebase is becoming more and more stable, one can expect the number of breaking changes will decrease over time.
> In addition, if you aim to create a simulator that is up to date with Polkadot, you should be aware that your simulator will _also_ need to receive updates - otherwise, Polkadot moves forward while the simulator keeps serving blocks with outdated structure.
> 
> Finally, are you planning to support [all RPC calls](https://polkadot.js.org/docs/substrate/rpc)?

Thank you fro replying, @mmagician. I am reading the docs of polkadot and thinking about the important question you asked that what is the advantage of using a simulator.

> > After that, new version will have the access to parachain as a gateway
> 
> Could you elaborate on this? I don't understand the comment.
> 
> > User of simPolk can connect to the parachain such as Kusama very easily.
> 
> So just a minor correction: Kusama isn't a parachain, but a relay chain in itself. Anyway, what do you mean by connecting to parachains? Will you be simulating the data from each parachain?
> 
> > The UI is used to access the RPC of the simulator.
> 
> So that means I will be able to run queries from the command line as well? What about websocket connection? In my point of view this is as important or more than RPC queries, since developers want to subscribe to events/Tx's happening on-chain in real-time (as opposed to actively making frequent RPC calls)
> 
> > I have tried run a private chain by substrate and developed 2 pallet. But when the RUST updated or substrate updated, there are too much issue to fix and I failed to fix all of them.
> 
> It is true that substrate is a moving target and breaking changes are still being introduced. However, now that parachain codebase is becoming more and more stable, one can expect the number of breaking changes will decrease over time.
> In addition, if you aim to create a simulator that is up to date with Polkadot, you should be aware that your simulator will _also_ need to receive updates - otherwise, Polkadot moves forward while the simulator keeps serving blocks with outdated structure.
> 
> Finally, are you planning to support [all RPC calls](https://polkadot.js.org/docs/substrate/rpc)?

Thank you fro replying, @mmagician. I am reading the docs of Polkadot and thinking about the important question you asked that what is the advantage of using a simulator.
Sorry, I will explain simPolk by benifit logic, which does not correspond to your question one-to-one.

**Comment by ff13dfly** [comment]
Thanks for your good questions, simPolk has become more clearer.

1.Perhaps the misunderstanding comes from the fact that I call simPolk a simulator. It would be more appropriate if I regard it as an introductory tool for developers who don’t understand blockchain at all.

2.SimPolk should be able to help developers in these two stages, one is when they first contacted Polkadot, and the other is when they want to develop pallet by themselves.


3.Based on the two aspects of simPolk's role, the current priority is to solve the simulation of the data structure, and the priority to be solved in the later period is the simulation of cross-chain data (this is a very complicated problem).

4.Regarding the gateway, it is still an idea without too many details. The original intention is because Polkadot is a very large system, and for application developers, it will become difficult to fully grasp it. 
If like we treat databases, not everyone can develop a database engine, but using database to develop application is not a thing that requires a high threshold.
The gateway of simPolk is the same thing, which is to simplify Polkadot into a key-value database engine. What the application has to do is to call APIs to put the data on the chain without worrying about what is going on. In the future, even cross-chain data can be obtained, which will depend heavily on Polkadot's cross-chain capabilities.

I will modify the milestones. In the first stage, the integration part will be removed, only to simulate the data structure of Polkadot and guide to the use of local nodes.

**Comment by ff13dfly** [comment]
These days, I am trying new version of substrate and its RPC calls, find that current simPolk as a simulator should be pending. Two reasons:
1.Substrate v3 is easier to code than v2, I have add a key-value pallet successful.
2.Polkadot is much convenient now, do not need to run in code way.

@mmagician @Noc2 ,thanks for the patience, I will change the goal of simPolk by treating substrate as a key-value storage engine.
I think simPolk is still a good name , but means simplifying Polkadot. 
The applying will be updated and submitted later.

**Comment by mmagician** [comment]
@ff13dfly Any updates here?

**Comment by Noc2** [comment]
I’m closing the PR for now due to inactivity. Let me know once I should reopen it.

**Pull request closed without merging**
