### PR TITLE
jua grant application

### PR DESCRIPTION
**Pull request by gichuhibrian**
#### Project Abstract

JUA DEX is building an escrow-based decentralized exchange on the Astar parachain to facilitate easy onramping and offramping of cryptocurrencies for users in Africa. The exchange will utilize smart contracts and chain interoperability features like XCM and XVM to enable trading between different blockchains. The project aims to provide a user-friendly platform for buying, selling, and converting crypto assets, starting with support for Polkadot and EVM-compatible chains.

The long-term vision is to create an open decentralized financial framework with features like compliance integration, limit orders, and smart wallet functionality to offer cost-effective alternatives to centralized exchanges and international remittances. The roadmap includes milestones like smart contract development, compliance framework integration, limit orders, full launch, and future plans for multi-currency support, deployment on other chains, incentivization, bridging capabilities, applications, and parachain functionality. Overall, JUA DEX seeks to drive adoption of Polkadot and blockchain in Africa through an accessible decentralized finance platform.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) or BTC address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by gichuhibrian** [comment]
I have read and hereby sign the Contributor License Agreement.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. However, we usually don't support two grants per team; see https://github.com/w3f/Grants-Program/pull/2069 Could you close one of them and focus on the other?

**Comment by El-khana** [comment]
I have closed my application, i was finding issues applying via my account we will go on with this one if it is okay

**Review by semuelle — CHANGES_REQUESTED** [review]
Thanks for the application, @gichuhibrian. I think financial inclusion is a worthwhile pursuit, but I'm afraid this proposal is not a good fit for our grants program since we (a) don't fund Solidity development, (b) we don't fund security audits, and (c) it's lacking technical details. Please add architecture or sequence diagrams, a comparison of your approach to other existing projects in the Polkadot and similar ecosystems and a tech stack. Also, there is currently a lot of content duplicated. Furthermore,

- you are currently requesting 10k for 10 person days,
- there are no costs and FTEs for the individual milestones,
- none of the team code repos you have linked is accessible for me.

**Comment by keeganquigley** [comment]
Hi @gichuhibrian I'm going to close this application due to inactivity. Let us know if you would like it re-opened.

**Pull request closed without merging**
