### PR TITLE
Submission of Dot Marketplace for Open Web3 Grant

### PR DESCRIPTION
**Pull request by abeoye**
Added application for Dot Marketplace

# Grant Application Checklist

- [x] The [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [ ] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

### CODE REVIEW

**Comment by mmagician** [comment]
@abeoye Thanks for the submission. Just a few follow up questions:

> Registration Module | Form based user registration

If I understand correctly, this deliverable combines both the substrate module and the UI will submit data entered in the form?

---
> Support for user to link their Polkawallet with the account

Perhaps you could shed more light on how you envision this integration to look like

---
> Substrate based Smart Contract transfer function

Before you mention creating modules, and here you're creating a pallet. Is there any reason that you're mixing up the two, or is it just a naming mistake?

---
> Support for the locking of assets by time

What do you mean by this? Are you aware of the [vesting pallet](https://substrate.dev/rustdocs/latest/pallet_vesting/index.html)?

---
Lastly, you mention testing the build, but we also require explicitly committing to providing unit tests, as outlined in our [template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md).

**Comment by alxs** [comment]
@abeoye I'm closing this for now due to inactivity. Let us know once you've revised your application and we'll reopen the PR (please don't force-push).

**Comment by abeoye** [comment]
> > Registration Module | Form based user registration
> 
> If I understand correctly, this deliverable combines both the substrate module and the UI will submit data entered in the form?
> 
Yes, the UI will submit the form data that will be using substrate module at the backend to record the details on-chain. 
The UI would be plain vanilla and built on top of the default substrate-front-end-template
The party forking would be expected to customise their own UI, like we have done for Yoda (shared in the Gif) 

> > Support for user to link their Polkawallet with the account
> 
> Perhaps you could shed more light on how you envision this integration to look like
> 
We'll need to change this point. 
We will be integrating Math wallet, Guarda wallet along with the Polkadot Js apps, this will be a dropdown for the wallets with these three options for the users to integrate with any of these. 
Can share an image if needed. 


> > Substrate based Smart Contract transfer function
> 
> Before you mention creating modules, and here you're creating a pallet. Is there any reason that you're mixing up the two, or is it just a naming mistake?
>
We are creating a pallet with different modules. 
Example: "Programmatic Wallet Transfer"
Since there will be multiple users following a specific pallet (tasking) entire decl_module! (functions) lifecycle, and once they complete the entire flow, only then the wallet will release the funds to their respective wallets

> > Support for the locking of assets by time
> 
> What do you mean by this? Are you aware of the [vesting pallet](https://substrate.dev/rustdocs/latest/pallet_vesting/index.html)?
> 
Yes we are aware of the above mentioned pallet, this locking of assets (funds) by time means as per the task completion and approval deadline. The funds will only be unlocked after the entire approval flow is validated.

> Lastly, you mention testing the build, but we also require explicitly committing to providing unit tests, as outlined in our [template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md).
Yes, of course! We commit to it. 
The manual testing is an additional activity, that we believe is mandatory.

**Comment by abeoye** [comment]
We have signed the CLA again. Please advise if there is anything more to be done at our end. 
Or if you would like us us to refine something in our proposal.

**Review by Noc2 — CHANGES_REQUESTED** [review]
The formatting of your application seems to be a little bit off compared to our [template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#overview-1). Could you update this? Could you also integrate unit tests into the application? And it seems your current front-end is open source. Do you plan to keep this open source? In this case you could integrate it into the deliverables. It would definitely help with testing the application and the approval ;-)

**Comment by abeoye** [comment]
> The formatting of your application seems to be a little bit off compared to our [template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#overview-1). Could you update this? 

Yes definitely

> Could you also integrate unit tests into the application? 

Sure

> And it seems your current front-end is open source. Do you plan to keep this open source? In this case you could integrate it into the deliverables. It would definitely help with testing the application and the approval ;-)

The current frontend is a part of our internal product (Yoda) which we are not ready to open source just yet. 
But we are building a simpler frontend that would help with the testing of the application which will be released as a part of Dot Marketplace. It is built on top of the Substrate Frontend Template. And yes, we would include it as a part of the deliverables. We'll also replace the gif we have uploaded, to avoid confusion. 
Please give us a couple of days to complete this activity and update.

**Comment by abeoye** [comment]
We have made all necessary changes. 
Awaiting your review.

**Comment by abeoye** [comment]
Hola folks! 
As requested we have: 
1. Adapted the application to the latest grants template
2. We have included Unit Tests explicitly 
3. We have made Frontend UI as a deliverable in each of the milestones

By when would you be able to review and revert please?

**Review by Noc2 — APPROVED** [review]
Sorry for the late reply. I’m happy to go ahead with it and will share it with the rest of the team.

**Review by mmagician — APPROVED** [review]
Thanks for all the work put into improving the application 👍🏼

**Review by semuelle — COMMENTED** [review]
- Could you expand on what you mean by `boilerplate code that parachain teams can customize`? Reusability is more or less expected, which is why we require grant results to be published under an open source license.
- According to the sequence diagram, a customer can reject a submission, upon which funds are returned to their wallet. How do you ensure that a customer doesn't just take off with a valid submission? I see you are saying this is out of scope, but I'm sure you already have some thoughts about that.
- Are payments limited to native currencies?
- What do you mean by `Support for multiple Substrate seed users`? Is this about multiple users working on one task? 
- Have you considered more complex scenarios, such as breaking down tasks and payments into milestones or multiple service providers working on a task concurrently (cf. Gitcoin)?

**Comment by abeoye** [comment]
> * Could you expand on what you mean by `boilerplate code that parachain teams can customize`? Reusability is more or less expected, which is why we require grant results to be published under an open source license.

The frontend would be **fully functional** and reusable as is. 
However we anticipate that serious projects would want to customise it as per their requirements, the same way we have customised `substrate-front-end-template`. 


> * According to the sequence diagram, a customer can reject a submission, upon which funds are returned to their wallet. How do you ensure that a customer doesn't just take off with a valid submission? I see you are saying this is out of scope, but I'm sure you already have some thoughts about that.

Great question! We are assuming that the Worker would work in her own environment to create the deliverable. Access to this deliverable would be unlocked only after the Customer approves the submission. This approval would also automatically trigger transfer of locked funds in the escrow to the Worker. 
The specifics of how to allow the Customer to verify the deliverable without having access to it, would depend upon the nature of the task. We anticipate the team implementing the marketplace to customise the runtime logic for their components. 

Lastly, in Phase 2, we would be creating a simple workflow which allows the Customer and Worker to message each other to discuss the deliverable. It would support image/ video and file attachments. People would be able to use this workflow for a wide variety of use cases. 
Ex. Consider a task of getting a meme designed by a community member. It could be uploaded with a watermark, which automatically disappears once the deliverable is approved. 

> * Are payments limited to native currencies?

At the moment yes.

> * What do you mean by `Support for multiple Substrate seed users`? 

The initial code we wrote in the Hackathon supported only two users. This point refers to making the application support up to 10 users, identical to pre-funded seed users provided by Substrate. 

> Is this about multiple users working on one task?

No 

> * Have you considered more complex scenarios, such as breaking down tasks and payments into milestones or multiple service providers working on a task concurrently (cf. Gitcoin)?

Yes, it would be implemented in Phase 3. We have mentioned it in the Future Plans section of the application too.

**Comment by semuelle** [comment]
Thanks for the quick reply, @abeoye. I still don't understand the bit about the multiple user support. In the end, I'd expect to be able to sign up with my own address. Why don't you go straight for that?

**Comment by abeoye** [comment]
> Thanks for the quick reply, @abeoye. I still don't understand the bit about the multiple user support. In the end, I'd expect to be able to sign up with my own address. Why don't you go straight for that?

Oh, we are providing the sign up and login functionality! 
This line item was for the demo purpose, if any account originally doesn't have the actual tokens with them, they can still play around with the marketplace with the seed users provided by Substrate.

For anyone to meaningfully engage, they would have to stake tokens and we felt this was a barrier for entry for people to try/test the platform. So, just like the substrate-front-end-template a user can use Alice and Bob's account Id's to test the functionality of any extrinsics. 

To reiterate, we are providing the default sign up/ login as well as test user functionalities as mentioned above. 
Let us refine it in the deliverables column as well.

**Comment by abeoye** [comment]
Hi @semuelle, I have just edited our my last line where I suggested modifying the application, as it would trigger a fresh set of approvals. Please advise if the explanation in the comment is satisfactory and sufficient. 
Many thanks!

**Comment by semuelle** [comment]
I understand. Like Marcin, I got confused by the use of the term `module`. I would expect some form of testing setup (pre-funded or via faucet) to be part of the testing deliverables, but no need to split hairs.

**Review by semuelle — APPROVED** [review]

**Comment by abeoye** [comment]
Thank you very much gentlemen! 
Glad to get this alignment. 

We have been building since the day we applied for the grant. 
And we have been making some steady progress on that front. 
We'll submit Milestones 1 and 2 soon!

**Pull request merged**
