### PR TITLE
Grants webapp

### PR DESCRIPTION
**Pull request by lawmeskiviahs**
Grants Management Webapp

The Grant Management Web Application is a comprehensive software solution designed to streamline and enhance the process of managing grants. It aims to provide w3f and other grant-making institutions with a centralized platform to efficiently handle grant applications, evaluation, tracking, reporting, and overall administration. By reducing the number of clicks, the web application will enable better navigation of data, better UI, greater ease and effectiveness in the grant management process.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [ ] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — APPROVED** [review]
Thanks for the application. I personally think that especially all kinds of (automated) statics for the grants program would be pretty helpful. Maybe you can partly focus on this with your UI. But independent of it, I'm a huge fan of additional transparency for any grants program, and I'm happy to mark the application as ready for review and share it with the rest of the team.

**Review by keeganquigley — APPROVED** [review]
Thanks for wanting to work on this RFP! The application looks really good and will be very helpful to us. I'm also happy to go forward with it.

**Comment by lawmeskiviahs** [comment]
Thankyou @keeganquigley for the approval. Looking forward to contribute :))

**Review by semuelle — CHANGES_REQUESTED** [review]
Thanks for the application, @lawmeskiviahs. We got several applications for this RFP at the same time, and due to the nature of the RFP we wanted to take a moment to make sure we make the best use of the talent. 

We would like to ask you to modify the application to fit into a Level 1 grant covering only the first milestone (or whatever combination of deliverables you deem wise). Based on the delivery of that milestone, we would then evaluate whether we want to proceed with the rest of the proposed roadmap. Would this be possible?

**Comment by lawmeskiviahs** [comment]
Thankyou @semuelle for the updates. We have changed the milestone 1 so as to fit in a level 1 grant. Kindly review @Noc2 @keeganquigley

**Review by keeganquigley — APPROVED** [review]
Thanks @lawmeskiviahs for the changes and being willing to implement it this way. LGTM.

**Review by Noc2 — APPROVED** [review]
I'm happy to support it as well.

**Pull request merged**
