### PR TITLE
Applying for Polkadot js Plus follow-up: Pool Nominations

### PR DESCRIPTION
**Pull request by Nick-1979**
### Project Abstract

This is an application for a follow-up grant for providing POOL STAKING in "[Plus:Polkadot js Plus Extension](https://github.com/w3f/Grants-Program/pull/778)".

Recently, Parity Technologies staking team released a new pallet, named **"Nominations pools"**, which will make **pool staking** available on Kusama, and Polkadot. Now, it is available on Westend, will be available on relay chains soon. Therefore, we have decided to be among the first to provide this new coming functionality for Dotsama community in Polkadot js plus extension.

With Pool staking, stakers (delegators) with a small amount of tokens (e.g., 1 DOT) can pool their funds together and act as a single nominator. The earnings of the pool are split pro rata to a delegator's stake in the bonded pool.
        
The following features will be available in pool staking:
* auto vs manual staking (pool creation, join, nomination,etc.)
* unstaking (unbonding, claim payout, redeem)
* view own pool information (including pool name, Id, state, members Info, roles, and their accounts, reward/stash Id, and pool destroying)
* view nominations (including selected validators information, its nominators, actives, oversubscribeds, and ability to re-nominate)
* viewing pool staking general information (e.g., minimum to join/create, max pools, etc.)

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### How Did You Hear About our grants program?

- [ ] Social Media
- [x] Hackathon
- [x] Personal Recommendation
- [ ] Substrate Builders Program
- [ ] Investor/VC
- [ ] Online Search 
- [ ] Other: _______

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the application. This is great. However, could you please change the total costs to USD. We no longer denominate grants in BTC. We basically take the exchange rate at the time of the payment for the BTC amount, because of this it’s usually easier to get paid in stablecoins.

**Review by gautamdhameja — APPROVED** [review]

**Review by takahser — APPROVED** [review]
Exciting! I'm happy to go ahead with it as well.

**Comment by alxs** [comment]
Hey @Nick-1979, any updates on the second milestone? Unless you plan to deliver soon, could you please submit an [amendment](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval) with an updated timeline?

**Comment by Nick-1979** [comment]
> Hey @Nick-1979, any updates on the second milestone? Unless you plan to deliver soon, could you please submit an [amendment](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval) with an updated timeline?

Hey @alxs, The proposal was only one milestone, which is already delivered , merged and finished

**Comment by alxs** [comment]
Thanks, sorry there was a mistake in our internal records.

**Pull request merged**
