### PR TITLE
Add xcm-tools-follow-up-2

### PR DESCRIPTION
**Pull request by gmajor-encrypt**
#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (Polkadot AssetHub (DOT, USDC & USDT) address in the application and bank details via email, if applicable).
- [x] I understand that 30% of each milestone will be paid in vested DOT, to the Polkadot address listed in the application.
- [x] I am aware that, in order to receive a grant, I (and the entity I represent) have to successfully complete a KYC/KYB check.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Parasos — APPROVED** [review]
bb

**Review by semuelle — COMMENTED** [review]
Thanks for the application, and welcome back, @gmajor-encrypt.
Looking at the xcm-tools repository, I see that you are still the only contributor. I would hope and expect any open source project to eventually gather some contributions - raised issues, PRs, etc. - from the community. But that does not seem to be happening. Do you engage with the community at all? If so, where? Also, do you have any idea how many people/projects use the library?

**Comment by gmajor-encrypt** [comment]
@semuelle Thank you for your message. Currently, I am the sole maintainer of the xcm-tools repository, and indeed, we are lacking contributions such as PRs and issues from other developers.

I am considering using the Polkadot forum to attract more developers' attention to this project. According to GitHub insights, there have been approximately 7 unique clones recently, which shows some level of interest.

**Review by semuelle — APPROVED** [review]
Thanks for the quick reply, @gmajor-encrypt. The deliverables in this application seem useful, so I'm happy to approve it. Going forward, I would strongly suggest to get the community more involved, so that eventually the development and maintenance of the library can be funded through the treasury.

**Comment by Parasos** [comment]
good

**Comment by Parasos** [comment]
good

**Review by Noc2 — APPROVED** [review]

**Pull request merged**
