### PR TITLE
Create Subshots.md

### PR DESCRIPTION
**Pull request by shakawwq**
#### Project Abstract

Subshots - a decentralized blockchain snapshot repository. Anyone can upload blockchain snapshots to the repository, and anyone can download the snapshot files to quickly deploy a chain node.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the application. In general, it sounds like an interesting application. However, I have two concerns here: 

- On the one hand, we have supported CESS already with various grants applications, and it might be better at this point to get funding in other ways than the grants program. Especially since we don’t look into the business model of a project and don’t check its viability. 
- On the other hand, wouldn’t you require to pay for these snapshots with the CESS token, and therefore you have a clear incentive to implement this as a product for your network? 

Independent of it, I’m happy to mark the application as ready for review so that others also take a look at it.

**Comment by randombishop** [comment]
Thank you for this application @shakawwq 
Imo, at this stage, the project main challenge is designing the tokenomics in a way that incentives data storage and delivery.
From my understanding, the Subshots network will charge CESS tokens to upload the snapshot data, but downloads are free. If that's correct, who will pay for download cost to sustain the network? Also, if upload is a one-time fee, is data stored for a limited period of time or does it expire after a while?
Similar to @Noc2 opinion, I think the project should now find a way to sustainability through its business model and tokenomics rather than pure technical funding that we usually support.

**Comment by shakawwq** [comment]
Thank you both for your sincere advice, which has been very helpful to us.

The reason why we applied for the W3F grant program using Subshots is because we think this tool is great. It is similar to Docker Hub and aims to provide a trustless snapshot repository service for all projects in the Polkadot ecosystem for free. 

The reason why it can be completely free is that the CESS network has a public space where anyone can upload data with 0 gas fees, and downloading data itself does not require any fees. As there is no commercial model involved, we see it more as a pure technical project. Based on this, we hope to obtain a startup capital through the W3F grant program to implement this product.

We would be extremely grateful if you could reconsider.

**Review by Noc2 — CHANGES_REQUESTED** [review]
If uploading is possible without any fee, I recommend applying for treasury funding for this. See https://github.com/w3f/Grants-Program#treasury

**Comment by Noc2** [comment]
Thanks again for the application and all the effort you put into this. The committee decided against approving the application and recommended applying for treasury funding instead. Also, because similar initiatives like [polkashots have been funded via the treasury in the past](https://kusama.polkassembly.io/post/643). Feel free to let me know if you have any questions.

**Comment by shakawwq** [comment]
@Noc2 thank you for your advice. Our team will soon look into it.

With kind regards,
team CESS LAB

**Pull request closed without merging**
