### PR TITLE
Create Polkadot-Api-Cli-Gui.md

### PR DESCRIPTION
**Pull request by tolgayayci**
#### Project Abstract

Developing user-friendly graphical interface for the Polkadot Api CLI

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [X] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [X] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [X] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) address in the application).
- [X] I am aware that, in order to receive a grant, I (and the entity I represent) have to successfully complete a KYC/KYB check.
- [X] The software delivered for this grant will be released under an open-source license specified in the application.
- [X] The initial PR contains only one commit (squash and force-push if needed).
- [X] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by semuelle — COMMENTED** [review]
Thank you for the application, @tolgayayci. I have some initial questions:

- What does it take to implement all these modules and functions you are listing in the deliverables? Do you actually go through all these? I would assume that there is a way of generating a UI based on the function definition.
- Projects like these only succeed when they find adoption and a community. Since your previous projects don't seem to have done that, I'd be curious to know what your plan is for this one.

**Comment by keeganquigley** [comment]
Thanks for your thorough answers @tolgayayci though I like the concept, I also have some concerns:

> For this project, we request that this GUI application's link will be added to the relevant pages such as api-cli and tools in Polkadot wiki etc. Cli users will want to use it when they see such an easy-to-use alternative. We also tried to use cli, but as we mentioned in the proposal, the learning curve is high if you do not have deep experience with it before.

The foundation tries to stay objective when it comes to projects, so unfortunately, we wouldn't be able to add your tools to our web pages. We also can't provide guidance to teams to add themselves to the site. The grants program is here to bootstrap projects, but we always hope to see that projects can eventually develop a community organically. The grants program also shouldn't be the sole source of income for the project.

> Grant applications are required to write only development, so we did not talk much about maintenance, but we guarantee to fix the project if there is any breaking change for a year. Because if the polkadot runtime changes, the API may also change, so some modules and methods may not work.

I would disagree with this statement, because, as [our guidelines](https://github.com/w3f/Grants-Program#guidelines) state, successful applicants are required to write documentation as well. And while maintenance may not in the scope of the grant itself, we still ask teams to somehow demonstrate that the project will be maintained after the completion of the grant. I would have to agree that it doesn't appear this is the case with Awesome Polka or PolkaFlow.

**Comment by keeganquigley** [comment]
Thanks @tolgayayci for your reply. While I agree that the PolkaFlow site seems to be more active, the dashboard doesn't seem to be open-source, as there is nothing in the [repo](https://github.com/yk-labs-dev/soroban-cli-gui). This makes it a lot harder for us to judge the value of the project, and also personally makes me worry that you might not keep this cli tool published either.

Generally we look at things like commit activity, number of contributors, community forks, stars, and insights such as code frequency. We also look at external factors, such as your team's activity in forum discussions, and community engagement with the product. 

To answer your question, a great example of a level 1 grant that has continued to be maintained afterwards might be [ParaSpell](https://github.com/paraspell/xcm-sdk). By taking a look at their [code frequency](https://github.com/paraspell/xcm-sdk/graphs/code-frequency) I can see the activity from when the grant started. They had a couple of level 1 grants, and then subsequently went for Treasury funding once the community started using the project.

We understand that not every project will necessarily be successful, but we try to do our due diligence in ensuring that it _can_ become successful. This is why maintenance is important. At this point, I'm not yet convinced about this project and therefore am not going to approve it. But I appreciate the time and effort you've put into this application.

**Comment by keeganquigley** [comment]
Thanks @justmert for your response. I did go to https://flowana.app/polkadot/projects and when you scroll down and click on "GitHub" that's the repo it links to. This is why I thought it was the official repo. Apologies for the mistake. In that case though, I would ask why the website is hosted in your personal repos instead of the official one for YK Labs. 

I checked out both the repos above but the back-end repo has no .readme file and the front-end repo .readme is still the Next.js template text. I appreciate that they are active but I'm still not seeing much evidence of user adoption or dev engagement here. Without more information, I'm afraid this doesn't really change my stance.

**Comment by semuelle** [comment]
@tolgayayci, sorry for the long wait. Based on the price and scope of this proposal as well as previous deliveries, I am not going to support this application. I am also skeptical about the rest of the committee being convinced, but in any case I will bring your application to their attention on Wednesday. If there are follow-up questions then, we can discuss them here or schedule a call.

**Comment by keeganquigley** [comment]
@tolgayayci thanks for all your hard work and efforts regarding the application. Unfortunately, it wasn't able to garner enough approvals from the committee. Therefore I'm going to go ahead and close it, but we thank you for your interest in the W3F grants program, and wish you the best of luck in finding funding.

**Pull request closed without merging**
