### PR TITLE
add chainlens phase4 application

### PR DESCRIPTION
**Pull request by conor10**
#### Project Abstract

This is the phase 4 grant application for the Chainlens (Sirato) Substrate Explorer.

Previous grants and delivery milestones are included in the application.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. But milestone one currently doesn't have any details or deliveries. Could you add them?

**Comment by abhijeetbhagat** [comment]
> Thanks for the application. But milestone one currently doesn't have any details or deliveries. Could you add them?

hey @Noc2 ! the table describes deliveries for both the milestones.

**Comment by abhijeetbhagat** [comment]
hey @Noc2 the table has been split milestones-wise now.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update, and sorry for the late reply. Could you also add the programming language to the deliveries and maybe link to the specifications above in the document? The milestone tables are the requirements of our contracts according to our terms and conditions. Also, could you define what you mean by "various charts, labels for chain data." And a reminder to sign our terms and conditions: https://github.com/w3f/Grants-Program/pull/1909#issuecomment-1679321660

**Comment by abhijeetbhagat** [comment]
> Thanks for the update, and sorry for the late reply. Could you also add the programming language to the deliveries and maybe link to the specifications above in the document? The milestone tables are the requirements of our contracts according to our terms and conditions. Also, could you define what you mean by "various charts, labels for chain data." And a reminder to sign our terms and conditions: [#1909 (comment)](https://github.com/w3f/Grants-Program/pull/1909#issuecomment-1679321660)

hey @Noc2 ! sorry, not sure what you mean by 'maybe link to the specifications above in the document'

**Comment by Noc2** [comment]
You currently specify the deliveries partly as part of the application but not as part of the milestone specification. For example, the milestone says, "will support configuring storage option" and the text above actually defines three storage backends. It's currently not fully clear if you actually will deliver these storage options previously mentioned. The same is true for the microservice, etc.

**Comment by abhijeetbhagat** [comment]
hey @Noc2 ! i've added details against the delivery items. please check.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. I will mark the application as ready for review and share it with the rest of the team. However, I'm personally a little bit concerned that https://chainlens.com/ has a clear business model at this stage, and the application is a little bit expensive. Would you be willing to reduce the price? Also, have you considered applying for treasury funding?

**Review by dsm-w3f — CHANGES_REQUESTED** [review]
@abhijeetbhagat thank you for the grant application. I noticed that this project already received some grants from W3F. Could you provide information about the current usage of the product in our ecosystem? How many daily users do you have? What is the current impact of the project on our ecosystem? Is your project currently financially sustainable?

**Comment by conor10** [comment]
Hi @Noc2, regarding your query — the commercial product Chainlens is only serving EVM chains currently (our goal is for Chainlens Substrate to reach this point in the future). 

Chainlens Substrate is a separate code base and OSS. The motivation for Chainlens Substrate is to support the need for quality open-source explorers for the Substrate ecosystem.

At the current time, I'm not sure Chainlens is well-enough established to obtain treasury funding — I would anticipate once we have customers for it that would be a viable way forward to support relay chain deployments.

Hi @dsm-w3f, we don't currently have any commercial customers for the Chainlens Substrate project. We're proposing the development of features based on previous discussions with parachains, but its not feature-rich enough for them yet. 

We don't currently have impact metrics within the ecosystem, beyond that it serves as an OSS explorer for projects to use. This provides alternatives to Subscan for projects which is a closed-source paid-for product.

**Comment by abhijeetbhagat** [comment]
Hello @Noc2 @dsm-w3f is the review in progress?

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the quick reply here. Just to double-check, where can I find the latest "Chainlens Substrate" version or basically the result of the three previous grants for 150k? Is it https://substrate.sirato.xyz/. In my opinion, if you are actually aiming to develop a commercial product for substrate, you should also be willing to invest in it.

**Comment by Noc2** [comment]
That said, I will ping the rest of the team again to take another look at the proposal.

**Comment by abhijeetbhagat** [comment]
> Thanks for the quick reply here. Just to double-check, where can I find the latest "Chainlens Substrate" version or basically the result of the three previous grants for 150k? Is it https://substrate.sirato.xyz/. In my opinion, if you are actually aiming to develop a commercial product for substrate, you should also be willing to invest in it.

That’s the correct url.

**Comment by conor10** [comment]
Hi @Noc2, we are investing in the product by running up instances for teams to work with it and provide feedback that went into this grant application.

We do face a chicken and egg problem with respect to how much we can invest in the project — without paying customers we're heavily constrained by resources to work on the project. We haven't had any external funding so need to be careful in this respect.

Beyond being self-sustaining, our goal for the project is for it to be the default explorer that anyone launching a Substrate network using open-source tooling can use. This is something that the substrate ecosystem needs and we believe that this proposal gets us closer to our goal in this respect.

**Comment by abhijeetbhagat** [comment]
hello @Noc2 any updates on the application review?

**Comment by abhijeetbhagat** [comment]
hello @Noc2 @dsm-w3f ! just wanted to check whether you guys got an opportunity to review the application yet. thank you!

**Review by semuelle — CHANGES_REQUESTED** [review]
Thanks again for the application, @conor10 & @abhijeetbhagat, and sorry for the late reply. We currently have a bit of a backlog. I think a verified contract explorer is sorely missed, so I'd be happy to see this developed. 

Could you

- remove the `0e` deliverables? They aren't deliverables, really. The spec could be mentioned under `Technology Stack`.
- add a tutorial to M2 that shows how a user could have their already deployed smart contract verified?
- review the `0c` specifications? It seems to me that unit tests alone wouldn't make much sense.
- reduce the price? The price per month is currently quite high.

**Comment by abhijeetbhagat** [comment]
hello @semuelle ! thank you for taking time to review our grant application. i've made amends to the application as you requested. please have a look and let us know if there's anything else needed. thank you!

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks again for the updates and all the effort you put into this. I'm still personally unwilling to go ahead with it, but I will ping the rest of the team again (see above).

**Review by dsm-w3f — COMMENTED** [review]
@conor10 thank you for the comments and improvements. We have been supporting this project with some grants and I don't see the impact of it in our ecosystem. Furthermore, the development still looks expensive from what it is being proposed. In this way, I won't approve it. The other members of the committee can have a different opinion on that. Good luck in the search for funding your project.

**Comment by abhijeetbhagat** [comment]
hello @dsm-w3f ! thank you for taking time in reviewing our grant application.

In our grant application, one of the equally important functionalities we wish to contribute to the substrate ecosystem  is to showcase all verified contracts on the chain which we believe is an important insight into the smart contracts side of things. End-users definitely want to know which contracts they can trust before they can interact with.  

The end-users are free to perform any number of contract verifications; this obviously turns into a storage problem since we store all the uploaded artifacts on the same backend filesystem at the moment. Therefore, it is only natural to store them elsewhere to reduce load on the local storage media and so we are providing that flexibility to pick a suitable option.

We are also trying to maximize our usage of existing substrate tools to aid in things like performing contract verification using the the new cargo-contract feature and let go of our existing workaround. We use more-or-less the same strategy that this new feature employs but we want to not only use what we think should be the standard way for contract verification but also actively contribute towards its testing, bug reporting and fixing and enhancements.

Many users would also like to see substrate data skimmed into the form of quality statistics - charts, graphs, numbers, etc. - as is the case with any financial product.

We have found that these are not trivial features to architect and develop. Moreover, all of this is completely open source with no active funding source at the moment. Our expenses go into setting up infrastructure to host this development for end-users to test and these costs are not transferred over to them in any way.

**Comment by abhijeetbhagat** [comment]
hello @semuelle ! can you please get more eyes to get our grant app reviewed :) ? thank you!

**Comment by semuelle** [comment]
Thanks for the ping, @abhijeetbhagat. I sent a reminder to the rest of the committee.

**Comment by semuelle** [comment]
Hi @conor10 and @abhijeetbhagat. Thanks again for your application. However, the committee has decided not to support it at this point. I believe the comments above reflect the reasons why, so I won't reiterate them here. 

Thank you for the work you have put into Sirato and this application. We appreciate what you have done so far and welcome you to apply again at any time in the future. In any case, best of luck going forward!

**Pull request closed without merging**
