### PR TITLE
Added Block Alerts grant application

### PR DESCRIPTION
**Pull request by davidzindex999**
#### Project Abstract

> Block Alerts provide a platform to set up alerts in your smart contracts. Whether you want to get alerts for any transaction or events, the block alerts platform will listen to the alert and send it to your Slack, MS teams, etc.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by semuelle** [comment]
Thanks for the application, @davidzindex999. A few questions:

- Is there a reason you only address smart contracts, and not also pallets? I'd assume there would be interest in pallet activity notifications as well.
- Are you planning to support only ink!, or also EVM-based smart contracts?
- Since your Github account is new, is there any previous work you can share with us? Anything open source, ideally Substrate or blockchain related?

**Comment by davidzindex999** [comment]
Hey @semuelle. Thanks for showing interest in this application.
> Is there a reason you only address smart contracts, and not also pallets? I'd assume there would be interest in pallet activity notifications as well.
Support for pallets is not in the scope of this grant. We will create a follow-up grant, and we will have support for pallets along with some more functionalities.

> Are you planning to support only ink!, or also EVM-based smart contracts?
Yes, currently, we will only support Ink. Ultimately we will try to extend support to all the chains, including EVM-based chains.

> Since your Github account is new, is there any previous work you can share with us? Anything open source, ideally Substrate or blockchain related?
I have been working in an IT-based company for close to 6 years. We had our instance of GitLab, where I used to push the code. I will push a few ink based smart contracts and file downloader in Rust which I created sometime back.

**Comment by davidzindex999** [comment]
Hey @semuelle Hope you are doing well!  Any update on the same ?

**Comment by davidzindex999** [comment]
Hey @semuelle. I have added the following repositories. Hope it helps. The third one is just a boilerplate generated using `cargo contract new`:

 - https://github.com/davidzindex999/learning-rust
 - https://github.com/davidzindex999/file-downloader-rust
 - https://github.com/davidzindex999/ink-tutorial

**Review by Noc2 — CHANGES_REQUESTED** [review]
Closing this application, for now, see the email.

**Pull request closed without merging**
