### PR TITLE
Add eNFT.md

### PR DESCRIPTION
**Pull request by gusiri**
# Grant Application Checklist

- [x] The [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

### CODE REVIEW

**Comment by alxs** [comment]
Many thanks for the application @gusiri. We will look into it as soon as possible. Do you intend to deliver milestones 5-6 even though they are self-funded? If not and they represent future plans, I'd suggest moving them to that section to avoid confusion.

**Comment by gusiri** [comment]
@alxs Yes that's what we intend to do. We would like to contribute to Polkadot ecosystem and its expansion with real-world integration and use cases.

**Comment by gusiri** [comment]
@alxs Yes, we will deliver them as grant milestones as well even though they are self-funded.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. I have a few questions/comments: First of all, you should be aware of the following: “We do not award grants for projects that have been the object of a successful token sale.” (see [Guidelines](https://github.com/w3f/Open-Grants-Program#guidelines)). It looks like you already finished a successful token sale to work exactly on this project. Could you comment on this? Second, it looks like you haven’t actively worked on the ethereum project for more than two years. Why do you suddenly want to work on this project again? Furthermore, most of the github links don’t work for me. And could you add the Overview section to the roadmap?

**Comment by gusiri** [comment]
Thank you so much for your kind review and feedback. It was really valuable not only for the grant application itself but also for our future roadmap and direction. Here are the answers to your questions/comments.

Q1. First of all, you should be aware of the following: “We do not award grants for projects that have been the object of a successful token sale.” (see Guidelines). It looks like you already finished a successful token sale to work exactly on this project. Could you comment on this?
A. We are applying to the grant for the growth of the Polkadot ecosystem and for our opensource contribution to the Polkadot community.
As a non-profit organization, we have found great potential in Polkadot and we would like to deeply get involved in and contribute to the Polkadot opensource community. In this context, the milestones of this application mainly focus on the growth of the Polkadot ecosystem in both technology-wide and community-wide including a survey of the existing NFT projects in the Polkadot ecosystem, defining a Polkadot NFT standard together with other Polkadot NFT project teams, a proposal of the NFT reference architecture, interoperability among Polkadot NFT projects, etc.
For reference, the purpose of our previous fundraise is mainly focused on developing e-commerce client applications and production services for e-commerce platforms.

Q2. Second, it looks like you haven’t actively worked on the ethereum project for more than two years. Why do you suddenly want to work on this project again?
A. We have never stopped working on it. We have been operating as a stealth mode focusing on real-world integration and adoption. While we were working on these real-world applications, we realized that we were not able to build what we wanted to build mainly because of the limitations of Ethereum (gas, scalability, etc). Based on this experience, we think Polkadot will allow us to continue to disrupt the industry and Polkadot is the chain that can scale what we are building.

Q3. Furthermore, most of the github links don’t work for me.
A. Github links were not accessible because they were private repositories. We changed our Splyt_Polkadot repository to public and we will use this repository as our main repository for our future documentation and deliverables. We have set up a local Rococo testnet for substrate development based on the substrate cumulus workshop manual and are currently working on our very first substrate development.
We removed other broken links for repositories Splyt_Core, Splyt_alpha and Splyt_Shopify because they are private repositories.

Q4. And could you add the Overview section to the roadmap?
A. We have added the Overview section to the roadmap.

Again, thank you so much for your review and time. We are happy to discuss further and look forward to your other valuable comments!

**Review by Noc2 — CHANGES_REQUESTED** [review]
Sorry for the very late reply and thanks for the additional information. I was ooo last week. In general, I recommend finishing M1 before you apply for the grant, since you don’t want any money for it anyway and this way it will be easier to convince the committee. I’m also not fully sure why you need to develop your own standard for the polkadot ecosystem. Could you explain this a little bit more detailed? Why are you not able to use existing ethereum standards for this? To be honest, I also still find the combination of an erc20 token and no visible github activity quite concerning. Is there any code/recent development you could share?  The Splytcore Polkadot Substrate repo is basically only a fork of the node template plus your grant application as far as I can see it. Furthermore, if you want to focus on creating a standard, you probably should integrate the PSP process in your application: https://github.com/w3f/PSPs

**Comment by gusiri** [comment]
Thank you so much for your kind review and feedback! Here are the answers to your questions/comments.


Q. In general, I recommend finishing M1 before you apply for the grant, since you don’t want any money for it anyway and this way it will be easier to convince the committee.

Actually, we have been already working on M1 as you recommended :) We will share the deliveries of M1 this week. Let us get back to you with the delivers soon. 


Q. To be honest, I also still find the combination of an erc20 token and no visible github activity quite concerning. Is there any code/recent development you could share? The Splytcore Polkadot Substrate repo is basically only a fork of the node template plus your grant application as far as I can see it.

We fully understand your concern and we also would like to show that we are serious with Polkadot and this grant. As you recommend, we have been working on M1 to show that we are serious in this grant application and our future plan with polkadot. We also plan to work on M2 after we complete M1 regardless of this grant process so that we can show the committee that we are serious. 

So far, 1) we did set up local rococo testnet for parachain development (M1-D3), 2) we are learning and developing our very first pallet, which is a part of M2 (eNFT Asset), 3) we are working on M1-D1 (Polkadot NFT Projects Survey, 4) we are working M1-D2 (eNFT Ref Architecture). 

In terms of the Polkadot repository, as we mentioned above, we have been mainly working on milestone 1 so that did not have meaningful development-related commits yet. However, we already started working on M2-eNFT pallet for Asset and will commit those codes soon. We will wrap up M1-D1 and M1-D2 this week. Also, we will actively push our commits to the repository after wrapping up M1, because M2 is mostly about developing eNFT pallets. 

We were also invited to NFT Strategy on Kusama element group and we will communicate with other projects for the survey and future collaboration.

Also, since public repositories do not show many activities, we attached a brief screenshot of our private repositories. There are also some other developments going on without repositories setup and we will also share them once they are ready.

image



Q. I’m also not fully sure why you need to develop your own standard for the polkadot ecosystem. Could you explain this a little bit more detailed? Why are you not able to use existing ethereum standards for this?

First of all, we needed to develop a E-commerce specific NFT standards rather than the existing ethereum standards. During the time we were developing our E-commerce NFT standard on top of ethereum and trying to deploy use case applications, we suffered real-world problems (ex: gas and scalability) and that stopped us moving forward. We are eager to deliver real-world applications to the e-commerce industry and we thought Polkadot is best fit for our 



Q. Furthermore, if you want to focus on creating a standard, you probably should integrate the PSP process in your application:

Thank you so much for your advice, we looked at the PSP process and will study more about PSP. As we work on M2 and collaborate with other NFT projects (for detailed design specifications), we will consider PSP too.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the detailed reply. I’m looking forward to the update. Regarding the E-commerce NFT standard, it’s still not clear to me why you need a new standard for this. The problems you mentioned (gas and scalability) are not related to the standard itself. Maybe you can point out the differences between your standard and existing ones (e.g. erc-721) as part of your work on milestone 1.

**Comment by gusiri** [comment]
Thank you for your reply and sorry for the unclear explanation.
We thought the existing standards (e.g., erc-721) itself is not enough to be fully utilized in e-commerce use cases. They are perfect to define assets, but we needed something more to define marketplace, inventory management, arbitration, reputation, etc.
But yes, we agree that we should deeply study existing standards first, and should never develop unnecessary features if these features are overlaps or unnecessary development. Thank you so much for the previous comment. 
As you recommended, we will clearly point out the difference in our milestone 1. 
Thank you!

**Comment by alxs** [comment]
@gusiri I'm closing this due to inactivity. Feel free to leave a comment if you'd like us to review your application again and we'll reopen it!

**Comment by gusiri** [comment]
@alxs Hi alxs! Sorry for the delay. Can you re-open this pull request? We have worked on milestone #1 so far and now we would like to submit the deliverables. Also, can you please let us know how to submit those deliverables? It is okay that we add the github URLs of deliverables into the application? Thank you!

**Comment by Noc2** [comment]
Alex is currently OOO. I will reopen the PR. Usually you should use the [Grant Milestone Delivery repo](https://github.com/w3f/Grant-Milestone-Delivery), but since this isn’t a “normal” milestone delivery, you can also just include it in your application.

**Comment by alxs** [comment]
@gusiri the link you added to the application is broken, and https://github.com/splytcore/Splyt_Polkadot/tree/main/deliverables doesn't contain any deliverables.

**Comment by gusiri** [comment]
@alxs Sorry for that. I will ping you right after fixing them and uploading the deliverables.

**Comment by alxs** [comment]
@gusiri are you still interested in this? The application was reopened a month ago now so you could add the deliverables.

**Comment by gusiri** [comment]
@alxs Yes, Aleixo! We are very interested in this and we keep working on stuffs.
My Apologies for the late reply. We fixed the broken URL and also uploaded Milestone 1 - Deliverable 1, 2 and 3. 

- Deliverable 1. Survey on Polkadot NFT Projects
- Deliverable 2. eNFT Reference Architecture
- Deliverable 3. Dev Environment Setup

We are happy for feedbacks and we will update each deliverable based on the feedback. 
For Deliverable 1 and 2, we will update them continuously while we are working on the next milestones.

**Comment by alxs** [comment]
@gusiri could you remove milestone 1 from the roadmap so it's clear that it won't be delivered as part of the grant? Feel free to include the survey and other deliverables in the background information or project details. I also suggest you remove milestone 6 as we're very unlikely to accept a milestone of such long duration.

**Comment by gusiri** [comment]
@alxs Thank you so much for your kind feedback.
We removed milestone 1 and 6 as you recommended, and updated other related stuffs (e.g., milestone overview) accordingly :) .

**Comment by alxs** [comment]
Thanks. Could you also sign the CLA again?

**Comment by gusiri** [comment]
@alxs Thank you so much :) Just signed the CLA again.

**Review by Noc2 — CHANGES_REQUESTED** [review]
@gusiri I just looked at your [milestone 1 deliverables](https://github.com/splytcore/Splyt_Polkadot/tree/main/docs). First, the survey isn’t really a “survey of the current NFT projects and comparisons of their system design and architecture” and the conclusion basically only says, it would be nice to have more projects, without specifically mentioning why. Regarding the “eNFT Reference Architecture”, if I understand this correctly, this has nothing to do with creating another NFT standard (similar to ERC-721) and the document doesn’t provide a clear reason why you can not use the existing standard. The document is more about creating the necessary additional tools around the existing standards for marketplaces (e.g. oracle problem). Did you already take a look at https://opensea.io/ or similar existing marketplaces? What's the advantage of your solution?

**Comment by alxs** [comment]
Closing due to inactivity.

**Pull request closed without merging**
