### PR TITLE
SubstrateSnap maintenance proposal

### PR DESCRIPTION
**Pull request by mpetrunic**
### Project Abstract

Previous grant: https://github.com/w3f/General-Grants-Program/pull/244

- The SubstrateSnap (plugin) enables support for the Polkadot and Kusama network inside of Metamask and by doing so enables Polkadot dApps easy integration with Metamask.
- ChainSafe believes that Snaps are vital to fostering increased adoption of web3 systems and as such consider the maitainance of the ChainSafe SubstrateSnap a strategic priority. 

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the application. Sorry for the late reply here. I currently have covid. Signing this grant might also take a little bit longer, since this is the first maintenance grant, which applies publicly via a PR. So based on this we are probably also going to update the template, etc, which isn’t in its final form yet. In general, I want to support the application, but I have a few questions:

- Is 8000 per week, the maximum or do you plan to invoice this independently of the actual workload?  It might make more sense to structure it with a max. Also to potentially have something set up for a longer time period.
- How many hours per day do you work? The hourly rate seems to be 400 USD, if you assume 8 hours per day.

**Comment by Noc2** [comment]
For reference, we just updated the template a little bit: https://github.com/w3f/Grants-Program/pull/880

**Comment by bryant-chainsafe** [comment]
Thanks for getting back to us so quickly @Noc2 and I hope you are feeling better! 
Answers to your questions below.

1. $8000 is the budget required for us to maintain SubstrateSnap @ 0.5 FTE per week. In other words, this amount is fixed and will not change.
2. 3-months (rounded to 12 weeks) @ 0.5 FTE (20h/w) = 6 eng-weeks FTE
6 eng-weeks FTE @ $8000/eng week = $48,000

My apologies for the confusion! 

Please also bare in mind that we have chosen to do this at a discounted rate of $8000/w as opposed to our former base rate of $12,000/w due to the strategic importance. We have just raised our base rate to $14,000/w.

If you have any more questions please don't hesitate to reach out!

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the quick reply and the discount. Could you try to update/integrate the following part: https://github.com/w3f/Grants-Program/blob/master/maintenance/application-template.md?plain=1#L109-L113 Even if you plan initially always to invoice us for 16k per month, it might make sense to already structure this as a cap. This might make it easier to extend the contract in the future. Also given that it’s the first public maintenance grant, it would be nice to have this integrated. Let me know if you have any questions.

**Comment by bryant-chainsafe** [comment]
Hey @Noc2 , thanks for that! I am working through your comments.
In the meantime, I do have one question. Is the 50k cap on Level 2 grants per month, or per maintenance contract? 
We do intend for this to be a long-term agreement (longer than 3 months) but have opted for level 2 due to applciation simplicity in comparison to level 1. In the event that it is per month, we would extend the proposed duration of the grant so that we can avoid frequent renewals. Let me know your thoughts, thanks!

**Comment by Noc2** [comment]
@bryant-chainsafe The 50k is per contract. My recommendation would be to for now sign a grant below 50k and we start the discussion early for a long-term follow up contract.

**Comment by bryant-chainsafe** [comment]
Thanks for that @Noc2 , we should have the changes integrated shortly. Thanks!

**Comment by Noc2** [comment]
@bryant-chainsafe I’m sorry to inform you that I need to put this grant application on hold for now. I will send more information via email.

**Review by inderashah007 — DISMISSED** [review]

**Comment by Noc2** [comment]
@mpetrunic Thanks a lot for the update. I’m just waiting for one more reply and then we can probably go ahead with it.

**Review by Noc2 — APPROVED** [review]
The grant is no longer on hold and I’m personally happy to go ahead with it and will share it again with the rest of the team.

**Review by BenWhiteJam — APPROVED** [review]

**Comment by bryant-chainsafe** [comment]
Hey @Noc2!! 
Great news :)
Seeing as this is a maintenance grant without milestones per see, at what point will we be able to publicize this?
Thanks!

**Comment by Noc2** [comment]
@bryant-chainsafe That’s a good question. Given your track record, feel free to immediately get in touch with grantspr@web3.foundation

**Comment by bryant-chainsafe** [comment]
Thanks, @Noc2, will do!

**Comment by FlorianFranzen** [comment]
This was delivered in polkadot-js/apps#8070, but so far has not been reviewed or merged.

**Pull request merged**
