### PR TITLE
Pull request for Women of Polkadot - Milestone 1 

### PR DESCRIPTION
**Pull request by JustLuuuu**
#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (Polkadot AssetHub (DOT, USDC & USDT) address in the application and bank details via email, if applicable).
- [x] I understand that 30% of each milestone will be paid in vested DOT, to the Polkadot address listed in the application.
- [x] I am aware that, in order to receive a grant, I (and the entity I represent) have to successfully complete a KYC/KYB check.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by JustLuuuu** [comment]
I have read and hereby sign the Contributor License Agreement.

**Review by semuelle — CHANGES_REQUESTED** [review]
Hi @JustLuuuu, thanks for the application. I like the initiative, but unfortunately the application doesn't fit the grants program. As you can see in our [guidelines](https://grants.web3.foundation/docs/Introduction/intro) and [FAQ](https://grants.web3.foundation/docs/faq), we are looking for technical details in applications and projects improving the state of the art. Also, events, outreach and education are typically activities funded by the treasury. 
That being said, I would suggest that you apply for a [Decentralized Futures](https://futures.web3.foundation/) grant. The DF program is less about the technological aspects of a project and more about [establishing new entities](https://medium.com/@web3/shaping-tomorrow-introducing-decentralized-futures-and-a-vision-for-the-polkadot-network-3c28ff68ba75). Happy to answer any questions.

**Comment by poppyseedDev** [comment]
@JustLuuuu asked me to help out a bit. In my opinion all the milestones listed here are quite technical. We removed the only non-technical one and, as a consequence, also reduced the asking price a bit.

**Comment by poppyseedDev** [comment]
I have read and hereby sign the Contributor License Agreement.

**Comment by keeganquigley** [comment]
Hi @JustLuuuu and @poppyseedDev thanks for the application. I love the idea of creating more initiatives for women in the space, and cool to see that you have already successfully hosted a few side events. However I have to concur with my colleague that none of the deliverables are specific to Polkadot tech, and therefore isn't a great fit for the technical grants program, which aims to focus mainly on Polkadot core tech & tooling. A general website & merchandise platform might be better supported by the DF program or treasury, as mentioned above. 

Additionally, just a note regarding the deliverables, typically 0a. - 0e. are reserved for the mandatory deliverables. So I would argue that 0d. Error Logging could be moved further below in the numbered section, and Testing/Testing Guide could be added back in for 0d.

**Review by takahser — CHANGES_REQUESTED** [review]
Hi @poppyseedDev

I agree with @keeganquigley and @semuelle here, I think other funding mechanisms like Treasury or DF are better suited for this kind of project. Hence, unfortunately I'm not going to add my approval in this case.

**Comment by JustLuuuu** [comment]
Thank you. We will reconsider our options and proceed once we decide how to proceed. Thank you for your time.

**Review by Noc2 — CHANGES_REQUESTED** [review]
The committee decided to close the application. Independent of it, we wish you all the best for your project. Let us know if you have any questions.

**Pull request closed without merging**
