### PR TITLE
[Aviraj] Amend polkasearch.xyz contract

### PR DESCRIPTION
**Pull request by avirajkhare00**
Amend polkasearch.xyz application contract

I was on a break due to personal reasons. I have started the development of this project.

Here is the GitHub repo for the project: https://github.com/avirajkhare00/polkasearch and currently setting up CI pipeline using GitHub Actions so that it could be deployed in Railway.app infrastructure.

Thank you for your kind patience 🙏

### CODE REVIEW

**Review by semuelle — APPROVED** [review]
Works for me

**Review by keeganquigley — APPROVED** [review]
LGTM

**Review by Noc2 — APPROVED** [review]

**Comment by avirajkhare00** [comment]
@Noc2 Requesting you to please close the grant since I have moved on to other opportunities.
Thanks a lot :)

**Comment by Noc2** [comment]
Thanks a lot for the update. I'm sorry to hear this. I will create a PR to close the grant.

**Pull request merged**
