### PR TITLE
Typechain Polkadot Grant

### PR DESCRIPTION
**Pull request by TtomaS7**
[Preview](https://github.com/Supercolony-net/Open-Grants-Program/blob/feature/typechain/applications/typechain-polkadot.md)

### Project Abstract

We attempt to bring type safety to working with Polkadot contracts at the front-end side of development. Based on contracts ABIs' content, we generate corresponding runtime code in addition to TypeScript types definitions for the contracts, so that developers deal with pre-typed methods on the contract.

Generating such code automatically with CLI brings convenience to the dApps development, as well as speeds up required codebase updates, when contracts are changed in pre-release stage.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying?

- [x] **Level 2**:  Up to $50,000, 3 approvals

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed (`typechain-polkadot.md`) and updated.
- [x] I have read and understood the [FAQs](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md), [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md) and [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).
- [x] I prefer the discussion of this application to be in a private Element/Matrix channel. My username is: ``@toma.sadova:matrix.org``

### How Did You Hear About our grants program?

- [x] Other: Previous successful applications for `OpenBrush` and `Sol2Ink`

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Sounds interesting. How big is your team at the moment? Given that we only recently signed two grants with your team and it looks like some of your team members are working on multiple projects. Also could you please add the default deliveries of the template again (0a-0d)?

**Comment by TtomaS7** [comment]
> How big is your team at the moment? Given that we only recently signed two grants with your team and it looks like some of your team members are working on multiple projects.

Hello! thanks for quick response. Supercolony team is more than 25 people now. Green and I are leading Infrastructure Tools Development, this is the reason I applied for all the grants. 
All the developers are working only on 1 specific project to avoid refocus and increase a productivity.

**Comment by TtomaS7** [comment]
Hello!
Is it any more change requested ?

**Review by Noc2 — APPROVED** [review]
Sorry for the late reply here. We discussed internally how we should handle the situation, given that we recently already approved two grants by your team. Our conclusion was, that we are happy to support another project by your team, but in the future we might need to schedule a call with you and maybe @rrtti to discuss how we can best support SuperColony. That’s said, I’m happy to support this project and mark it as ready for review.

**Comment by TtomaS7** [comment]
sure, I will be happy to schedule this call!

**Review by BenWhiteJam — APPROVED** [review]

**Pull request merged**
