### PR TITLE
update

### PR DESCRIPTION
**Pull request by peter-jim**
### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

  The Eternity Network is building a "decentralized quantization protocol" based on the Substrate3.0 Framework. The protocol will provide basic simple quantitative services for crypto users of the blockchain. The Eternity labs team wants to use it as infrastructure for the quantified block of blockchain.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the application. However, we don’t support the delivery “Eternity Node Repo”, since simply reusing other code isn’t useful for anyone else. Also regarding “Ink! Contracts will be deployed to HECO, BSC, Ethereum.”, Ink! Is only available on substrate based chains. And “ security audit of exchange addresses” seems pretty useless to me. In general I have the feeling that potentially the translation messed up the application a little bit.

**Comment by peter-jim** [comment]
> Thanks for the application. However, we don’t support the delivery “Eternity Node Repo”, since simply reusing other code isn’t useful for anyone else. Also regarding “Ink! Contracts will be deployed to HECO, BSC, Ethereum.”, Ink! Is only available on substrate based chains. And “ security audit of exchange addresses” seems pretty useless to me. In general I have the feeling that potentially the translation messed up the application a little bit.

Hello, we have modified the document and deleted some possible problems in the translation process. And added some details. Hope to pass this time. Haha😊

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. Could you change the total costs to USD? Se https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#overview-1 And to be completely honest, I still don’t really know what the “quantitative problem of cryptocurrencies” is. Could you maybe give an example? Do you mean that on-chain computation is really expensive?

**Comment by peter-jim** [comment]
> Thanks for the update. Could you change the total costs to USD? Se https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#overview-1 And to be completely honest, I still don’t really know what the “quantitative problem of cryptocurrencies” is. Could you maybe give an example? Do you mean that on-chain computation is really expensive?

that great! I have updated! Let me give you two examples. In terms of technology, if I choose some programs requiring high performance, such as deep neural network, to predict the price of BTC, it needs to train the model first and then make prediction while ensuring the accuracy. It takes a lot of computing power. It's a little awkward to do it at Substrate. In the market, there are companies with quantified services, but they operate in a centralized manner, and there is potential for node evil. In fact, there are many quantified companies that do harm to users. Let me give you a simple mathematical example: if the user makes a profit, the company gets 60 percent of the profit and the user gets 40 percent. If the user loses money, the quantified company undertakes 40 percent and the user undertakes 60 percent. There are many other ways to do evil. It's clear that the only thing the company needs to do is to hedge and make a steady profit. But this is a huge loss to the user!! Therefore, our project hopes to solve the above two problems, and we hope to provide users with a secure quantitative trading platform through Substrate.

**Comment by Noc2** [comment]
Thanks for the quick reply. So, I guess something like the following might be interesting for you: https://devfolio.co/submissions/cerebrum-8090. Did you already look into multi-party computation (MPC)? Independent of it, I will share the application already with the rest of the team. But I’m personally at the moment not fully convinced about the use case, which you're describing (predict the price of BTC) or the technical implementation, since it doesn’t offer something unique which can easily be reused by others. However, others might have a different opinion.

**Comment by mmagician** [comment]
Sure, you cannot always trust a centralised service. However, simply by moving the computation to an off-chain worker doesn't solve this problem. Nor is it solved by storing something in IPFS (which helps decentralisation of storage, but provides no security guarantees).

Furthermore, I find your deliverables to be too vague. For example, what seems to be a key component to your proposal:
> Pledge the tokens to pallets to ensure node security

It is not explained at all how this security will be achieved.

> Grid transactions / Band tracking / DOT to be cast surely / etc.

Most of these models have no context and are meaningless to the reader of your application.

I honestly don't think your application is in a state that's ready for review. Perhaps as @Noc2 said it's an issue of translation, which prevents me from understanding what you really want to build. Therefore, I am going to take the liberty and close this application for now. 

You are welcome to apply at a further stage of your project with clearer project description and technical specification of your deliverables.

**Pull request closed without merging**
