### PR TITLE
Add scale application

### PR DESCRIPTION
**Pull request by MatthewDarnell**
### Project Abstract

> This is a SCALE encoding/decoding library written in C. It has only 1 dependency for UTF8 which is included. (standalone header file). It serializes and deserializes the types of Fixed Ints, Compact Ints, Bools, Options, Enums, Vectors (and Strings), Tuples, and User-Defined Data Structures.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Comment by alxs** [comment]
Thank you for the application @MatthewDarnell. Could you please:

- Merge both milestones into one, as we generally treat testing as being an integral part of a milestone and not a standalone deliverable.
- Denominate the cost in USD. The amount in BTC will be determined at the payout date according to the exchange rate. It should also be below $10k for a level 1 grant.
- Also commit to inline documentation, which helps us understand your code when evaluating the delivery?

**Comment by mmagician** [comment]
Why is the [C++](https://github.com/soramitsu/kagome/tree/master/core/scale) implementation not suitable as standalone? Could you point out what's missing/incompatible with their approach?

**Comment by MatthewDarnell** [comment]
> Why is the [C++](https://github.com/soramitsu/kagome/tree/master/core/scale) implementation not suitable as standalone? Could you point out what's missing/incompatible with their approach?

https://github.com/soramitsu/kagome/issues/906

I had issues building it and created an issue, it was explicitly stated that it is not intended for standalone use. Also, the example provided depends on Hunter. In addition, nothing is extern C so there will be name mangling issues.

**Comment by mmagician** [comment]
Ok, understood. That's a shame,  but I guess you will be able to re-use parts of their code? I will be happy to support your application as long as you also provide a cross-implementation test that ensures the cohesiveness with [parity's](https://github.com/paritytech/parity-scale-codec) SCALE implementation - something along the lines of [the SCALE codec comparison RFP](https://github.com/w3f/Grants-Program/blob/master/rfps/scale-codec-comparator.md) for your C implementation.

**Comment by takahser** [comment]
Hi @MatthewDarnell 
I just wanted to check how the development of M2 is going for you.
Is there any way we can support you?

**Comment by MatthewDarnell** [comment]
> Hi @MatthewDarnell I just wanted to check how the development of M2 is going for you. Is there any way we can support you?

I don't have the bandwidth to do it at the moment but hope to get to it soon!

**Comment by takahser** [comment]
Thanks for the update @MatthewDarnell 
Can you give me an approximate estimate on when you plan to work on it again and potentially also when you plan to deliver?

**Comment by alxs** [comment]
@MatthewDarnell please note that we'll need an [amendment](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval) to update the timeline unless you're planning to submit within the next 2 weeks, since the milestone is now delayed by over 2 months. Otherwise, we'll terminate the grant and you can reapply when you're ready to work on it again.

**Comment by MatthewDarnell** [comment]
> @MatthewDarnell please note that we'll need an [amendment](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval) to update the timeline unless you're planning to submit within the next 2 weeks, since the milestone is now delayed by over 2 months. Otherwise, we'll terminate the grant and you can reapply when you're ready to work on it again.

Hi @alxs, thanks for your reply. Unfortunately I can't get to it atm, but I certainly may reapply when I have the ability to work on it. I haven't done much with FFI and am not sure how to programatically capture the output of the Rust parity-scale-codec tests in order to match with cScale, so that will be something I'd need to investigate as well.

**Comment by alxs** [comment]
Sounds good. I'll open a PR to terminate the grant in that case. From the little I know about Rust's FFI, I think you'd have an easier time doing it the other way around i.e. calling your library from within a Rust project. As I said, feel free to reapply at any time.

**Pull request merged**
