### PR TITLE
Candle Auction Milestone-3: Workshop to substrate.dev

### PR DESCRIPTION
**Pull request by agryaznov**
### Project Abstract

This is a proposal to continue the project with **Milestone-3:** adding a Workshop to substrate.dev

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. In general, we usually don’t support grants that focus only on education/tutorials, but since this is an update to your previous grant application. I would be willing to go ahead with it. Could you maybe add a license to your deliveries. Also since we can not ensure that your delivery is actually merged into https://docs.substrate.io/

**Comment by agryaznov** [comment]
Hi David. The reason I haven't added a license to Milestone-3 is that the [substrate-docs repo doesn't specify the license itself](https://github.com/substrate-developer-hub/substrate-docs#license). So I'm not sure if *Apache 2.0* would be ok here, not to contradict with the target site (substrate.dev) license.

Please, kindly advise on it. If Apache 2.0 wouldn't be an obstacle there, I'll add just it. Thx.

**Comment by semuelle** [comment]
I think [this](https://docs.github.com/en/github/site-policy/github-terms-of-service#6-contributions-under-repository-license) applies here, i.e. it assumes the substrate-docs license when you submit a PR.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Good point, I wasn’t aware of this. I recommend to add a delivery that says “License: either merged into substrate-docs or published under apache 2 as part of a separate repo” or something similar.

**Comment by agryaznov** [comment]
Please find added license terms.

**Review by semuelle — APPROVED** [review]

**Review by Noc2 — APPROVED** [review]
Thanks for the update. Looks good

**Pull request merged**
