### PR TITLE
Zombienet Explorer (previously Polkaholic.io)

### PR DESCRIPTION
**Pull request by sourabhniyogi**
#### Project Abstract

[Zombienet Explorer](https://github.com/colorfulnotion/zombienet-explorer) indexes a [Zombienet](https://github.com/paritytech/zombienet) using purely local setup (just Mysql, no external HTTP API calls unless you use a non-standard flag). It is based off Colorful Notion's [Polkaholic.io](https://polkaholic.io) which has been running as a public Multi-Chain Block explorer for 5 months.  Key features are basically same basic multichain block explorer interface as Polkaholic.io, but running on spawned Zombienets instead of Polkadot + Kusama chains, specifically:
* EVM support (basic evm txn input/logs decoding only)
* WASM support
* linking and visualizing different XCM messages / extrinsics
* simple Mysql analytics
This amends our previous Web3 Foundation [proposal](https://github.com/w3f/Grants-Program/pull/1039) "Polkaholic.io's Multi-Chain Substrate Block Explorer" to focus exclusively on  Zombienet to support Substrate developers.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. Some quick feedback from me: 

- Could you not delete your original application as part of the PR? I think we can simply cancel/terminate this one via a separate PR, but it would be nice to keep the file for the records in the application folder. 
- Usually, the default deliverables 0a-0d of the [template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#milestone-1-example--basic-functionality) below are mandatory for all milestones. Could you integrate them? 
- It looks like you slightly increased the price compared to the previous application (considering FTE and the estimate for the duration). What is the reason for it?

**Comment by alxs** [comment]
@sourabhniyogi thanks for the amendment. I would like to see Polkaholic.io develop further, but this is a fantastic idea. I will only add the following to David's comments: please note that deliverables need to be concrete, verifiable and potentially useful to others in the ecosystem. I.e. we can't fund things like "Deleting as much useless code as possible from Polkaholic.io" or "Refactor [...] in a way that can easily be contributed to/further improved by parachain teams / developers". For both of these, you could in theory spend an hour on them and you would meet the requirements.  Please treat the application as a contract; the level of detail should be enough for us to later verify that your delivery meets the specification.

**Comment by sourabhniyogi** [comment]
Adjusted to conform to template and detailed Milestone 1 + 2 in [Zombienet Substrate Block Explorer Milestone 1 + 2]( https://docs.google.com/spreadsheets/d/1xfcmlh-q_tRuf4wQDvv2c_pZQTJEu71KVk1N59pXgXs/edit#gid=323796891), linked in the doc.  I added back the previous version.  We will finish this project over 2 months rather than 3 months now.

**Review by alxs — APPROVED** [review]
Many thanks @sourabhniyogi. We normally ask teams not to link to any external documents, but these look rather hard to integrate and given the context and the rest of the application, I'm happy to accept it as is. I will share it with the rest of the committee.

**Review by alxs — CHANGES_REQUESTED** [review]
Just one thing: could you please specify which currency you want to be paid in and provide either a Kusama, Bitcoin or Ethereum address? See the list of possible payment currencies in our [README](https://github.com/w3f/Grants-Program#pencil-process).

**Comment by alxs** [comment]
Also let's treat this as a new grant, in that case. I'll create a PR to cancel the previous grant.

**Comment by sourabhniyogi** [comment]
Specified USDT, thank you!

**Review by alxs — APPROVED** [review]

**Review by Noc2 — APPROVED** [review]

**Review by gautamdhameja — APPROVED** [review]

**Pull request merged**
