### PR TITLE
Add Solang maintenance

### PR DESCRIPTION
**Pull request by salaheldinsoliman**
Signed-off-by: salaheldinsoliman <salaheldin_sameh@aucegypt.edu>

#### Project Abstract
The aim of this project is to enhance Solidity developer experience on Substrate based chains through adding two main improvements to [Solang compiler](https://solang.readthedocs.io/en/latest/). The first improvement is to the debug buffer: A means to revamp the communication between the smart contract and developer during runtime. The second improvement is the implementation of "Solang projects", A better way for the developer to configure the compiler for the chosen runtime. Further details are under `Improvement Project Details` section in the `.md`.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the application. This is definitely something that we want to support. However, for maintenance grants, we need to sign a regular contract since it’s not fully covered by our terms and conditions. Given that you already have a very specific list of deliveries, my suggestion would be to change this to a normal grant application level 1 with the milestone specified according to the template, see https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#milestone-1-example--basic-functionality including the default deliverables. I’m pretty sure that once this is updated, we could basically merge it immediately.

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I'm happy to go ahead with it and share it with the rest of the team.

**Comment by alxs** [comment]
@salaheldinsoliman I just realised you asked to be paid in USDT on Ethereum. We [just changed](https://github.com/w3f/Grants-Program/commit/5dfbb07b413b074767e957481776137f40c8ccac) the list of payment currencies, so could you please open a new PR modifying the existing file and provide a Polkadot or Kusama address instead?

**Comment by salaheldinsoliman** [comment]
@alxs 
Hello, The same address could be used for DAI or USDC on Ethereum, does that work?

**Comment by Noc2** [comment]
> @alxs Hello, The same address could be used for DAI or USDC on Ethereum, does that work?

Hi. Yes, this would work for us. Thanks!

**Pull request merged**
