### PR TITLE
add frontier-pos-template

### PR DESCRIPTION
**Pull request by weimeme**
#### Project Abstract

This is a development template based on Polkadot's NPOS consensus, compatible with EVM.
It aims to enable new developers or teams in the Polkadot ecosystem to quickly create EVM-compatible chains based on NPOS consensus.

reopen [https://github.com/w3f/Grants-Program/pull/2342](https://github.com/w3f/Grants-Program/pull/2342)
#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (Polkadot AssetHub (DOT, USDC & USDT) address in the application and bank details via email, if applicable).
- [x] I understand that an agreed upon percentage of each milestone will be paid in vested DOT, to the Polkadot address listed in the application.
- [x] I am aware that, in order to receive a grant, I (and the entity I represent) have to successfully complete a KYC/KYB check.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by weimeme** [comment]
> I have read and hereby sign the Contributor License Agreement.

I have read and hereby sign the Contributor License Agreement.

**Comment by keeganquigley** [comment]
Thanks for the application @weimeme and I'm happy to see that you have identified a common pain point for developers. My question is, how do you plan to fund & maintain this project after this grant? What are your plans for gaining traction with devs and marketing this product in a way that it can gain some real adoption?

**Review by keeganquigley — CHANGES_REQUESTED** [review]
Thanks @weimeme we also now pay all of our grants partly in vested DOT. This DOT is vested linearly on-chain for two years. If you are okay with this can you please include a `DOT %` line, indicating the amount of vested DOT you you are willing to receive? See https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md?plain=1#L127

**Comment by weimeme** [comment]
> Thanks @weimeme we also now pay all of our grants partly in vested DOT. This DOT is vested linearly on-chain for two years. If you are okay with this can you please include a `DOT %` line, indicating the amount of vested DOT you you are willing to receive? See https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md?plain=1#L127

 Thanks @keeganquigley, I have updated it.

**Comment by PieWol** [comment]
Hey @weimeme , thanks for the update. I'll share the application with the committee.

**Comment by weimeme** [comment]
> Hey @weimeme , thanks for the update. I'll share the application with the committee.



Thank you very much @PieWol . Our two cooperating teams are also about to launch their mainnet and testnet. Hope it helps more teams.

**Comment by semuelle** [comment]
recheck

**Comment by semuelle** [comment]
recheck

**Comment by semuelle** [comment]
Thanks for the application, @weimeme. Happy to support it. While we wait for further reviews, could you fill out the [KYB form](https://in.sumsub.com/idensic/l/#/uni_JRqwo72Y5AjXaRDO) (assuming you are applying as a company, otherwise please use [this form](https://in.sumsub.com/idensic/l/#/uni_mjcB05gJZfh8dbr7))?

**Comment by weimeme** [comment]
> Thanks for the application, @weimeme. Happy to support it. While we wait for further reviews, could you fill out the [KYB form](https://in.sumsub.com/idensic/l/#/uni_JRqwo72Y5AjXaRDO) (assuming you are applying as a company, otherwise please use [this form](https://in.sumsub.com/idensic/l/#/uni_mjcB05gJZfh8dbr7))?

Thanks @semuelle  , I have done the identity verification.

**Comment by PieWol** [comment]
Hey @weimeme ,
I'm hopeful that you will keep maintaining the template with good documentation so that this will be a benefit to lots of teams trying to build on Substrate. I hope whatever projects are to launch with this template will still try to participate in the Polkadot ecosystem and not exist in complete isolation. I approve it as well. Once KYB has passed we can officially accept and merge your application. Thanks.

**Comment by weimeme** [comment]
> Hey @weimeme , I'm hopeful that you will keep maintaining the template with good documentation so that this will be a benefit to lots of teams trying to build on Substrate. I hope whatever projects are to launch with this template will still try to participate in the Polkadot ecosystem and not exist in complete isolation. I approve it as well. Once KYB has passed we can officially accept and merge your application. Thanks.

Yes, this solo chain is just an option for early teams to create projects. Many teams hope to build their own business on this  and build a parachain after reaching a certain number of users and funds. This coexistence mode is very useful.

**Review by semuelle — APPROVED** [review]
> I have done the identity verification.

Thanks, @weimeme. Are you the sole beneficiary of the grant? You added a team name and team member, and all beneficiaries should perform KYC. Other than that, happy to support.

**Review by PieWol — APPROVED** [review]

**Pull request merged**
