### PR TITLE
php substrate api rfp

### PR DESCRIPTION
**Pull request by tejbahadursingh**
### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [ ] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [ ] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [ ] The software delivered for this grant will be released under an open-source license specified in the application.
- [ ] The initial PR contains only one commit (squash and force-push if needed).
- [ ] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Comment by aratibongale95** [comment]
signed it. now i am contributing to this

**Comment by rohitdhanke** [comment]
I signed it. Now I am contributing to this RFP

**Comment by KapilJoshiNitor** [comment]
Signed the CLA to be a contributor. I would be working on the RFP.

**Comment by neha0921** [comment]
Contributing to grant rfp

**Comment by alxs** [comment]
We have a bot that should have said the following but missed your PR:

> Thank you for submitting a grant application.<br/>
We've assessed your submission and have found that it requires a higher level of technical detail in order to be considered for review. We encourage you to expand on it by providing a more precise specification/technical details. The [section on project details](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#project-details) in the application template is a good reference as to what type of information we expect applicants to provide, and these [category-specific requirements](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md) contain more precise guidelines depending on what type of software you're building.<br/>
An area of the application that we often find to be insufficiently elaborated are the milestone deliverables. At a minimum, please indicate what languages/technologies you will be using to implement each deliverable, and provide a technical summary of its expected functionality. Note that deliverables should be tangible, reusable by other teams and in most cases not already present in the ecosystem. If they are, you will need to provide a comparison to existing implementations and explain why it makes sense to fund your approach. Also see our [FAQ](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md#-general) for a breakdown of what we fund and what we don't.<br/>
Let us know as soon as you're done with your changes, and we'll give your application another look!

**Comment by tejbahadursingh** [comment]
@alxs and @mmagician thanks for the input. working on the suggested changes. I hope I can ask here if I want to have any clarification on the term or process?

**Comment by mmagician** [comment]
Sure, feel free to ask if you have any questions that are not covered by our README - we try our best to cover as much detail there regarding the application process as possible.

**Comment by mmagician** [comment]
@tejbahadursingh Any updates? Are you still planning to complete the proposal?

**Comment by tejbahadursingh** [comment]
@mmagician thanks for asking. I am definitely planning to complete it. In next 2 days I'll submit the updated file.

**Comment by semuelle** [comment]
Closing due to inactivity.

**Comment by tejbahadursingh** [comment]
@semuelle working on it. once done I'll create a new PR with application template as a reference.

**Pull request closed without merging**
