### PR TITLE
project idiyanale: multi-token community contributions for verified creators

### PR DESCRIPTION
**Pull request by woss**
#### Project Abstract

This application is a continuation of the previously successfully delivered grant called Project Idiyanale - Phase 1 approved and delivered on this [PR-719](https://github.com/w3f/Grants-Program/pull/719).

Anagolay is a peer-to-peer framework for storing and transferring records of Rights (such as Ownership, Copyright & Licenses), based on verified proofs for any digital content. Previously we have worked on building the base for the deterministic and transparent processes we call Workflows and the on-chain permanent storage for the verifiable Statements. In this grant, we will combine it all and add two more pallets to accomplish truly decentralized community-powered contributions for all verified creators.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`anagolay-project-idiyanale-multi-token-community-contributions-for-verified-creators.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the application. It looks really good and I will mark it as ready for review. However, I have two questions:

- Our guidelines say  “We do not award grants for projects that have been the object of a successful token sale.” Did you already do a private sale? It looks like you want to integrate your own token IDI into the project. 
- If you haven’t done any private sales yet, I would recommend looking for VCs and other funding sources and I’m happy to put you in touch with someone who can help you with it. In general, I think the grants program isn’t the ideal tool to continue to support such a project, since we don’t really are able to provide good feedback regarding the business/user side of the project.

**Comment by Eltairovy** [comment]
Hi @Noc2 ,
thanks for the prompt reply. Allow me to comment on the questions of funding here as Daniel's (@woss) non-technical co-founder.  
- No, we did not do a token sale. It is a plan somewhere in the future for Idiyanale (like for most of the projects in the ecosystem), as we aim for the wide adoption of our utility token, but these plans are beyond the timing of the grant and not linked at all to its scope.
- Thank you for pointing out the guideline, it is, of course, reasonable, and we are familiar with it. At the same time, as there is a number of past grant recipients with their own tokens (in some cases not just planned, but already launched), I presume the fact of having a token does not prevent a project from receiving a grant if what the team builds is beneficial to the ecosystem as a whole.
- The focus of our proposal, as you can see, is on enabling the additional functionality and onboarding new users for the entire ecosystem. IDI is referred to, alongside the DOT and KSM, where and when its usage is functional for the implementation.  

P.S. following the previous grant delivery, your colleagues kindly put me in touch with William Croisettier, who seems to be the only one overseeing this topic and, understandably, is extremely busy. After 2 months of wait, some canseled&resheduled calls, and a quick 30 min meeting, I understood he had no time to look into the project and provide any sort of support. If you have any additional recommendations for us regarding the business/user aspects, I'd appreciate it. But first, we'd like to focus on the implementation to test our hypotheses later on.

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I’m happy to go ahead with it.

**Comment by Eltairovy** [comment]
Hi @Noc2, any news from the team? 
Would you mind pinging them again please to have a look?

**Review by takahser — APPROVED** [review]

**Comment by Noc2** [comment]
> Hi @Noc2, any news from the team? Would you mind pinging them again please to have a look?

Thanks for chasing us. I pinged the rest of the team again.

**Review by keeganquigley — APPROVED** [review]

**Pull request merged**
