### PR TITLE
Add project Nutbox Blockchain

### PR DESCRIPTION
**Pull request by tolak**
### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] The total funding amount of the project is below USD $30k for first-time grant applications and $100k for follow-up ones.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the updated application. As far as I know, there isn’t yet a “Substrate v4”. Also we usually don’t support deployment, monitoring or hosting (regarding the Nutbox Chain deliverable), so feel free to remove this part. Could you provide more information about the account and content pallets? What functionality will you implement? Also in case you are interested in open sourcing the faucet, we would also be interested in supporting this part as well.

**Comment by mmagician** [comment]
I won't support your project in its current state. I have the impression that there hasn't been much effort put into investigating the substrate stack nor into making an application, for the following reasons:
1. As @Noc2 mentioned, there's no such thing as v4 now. 
2. Your project overview is the same text copied 3 times.
3. Milestone 3 about `ink!` integration seems to just be including a contracts pallet. This would not provide any new value to the system, but rather paying you to follow the tutorials for including the pallet in your runtime.
4. "Milestone 2, Nutbox Chain" or "M4, Asset Transfer" deliverables also bring nothing new, all these features are already available and plug-and-play in substrate.

Furthermore, you mention "storage proof validation" without providing any explanation of how you plan do achieve this, which is a non-trivial problem in the space.

**Comment by tolak** [comment]
@Noc2 @mmagician Hi, sorry for the late reply, i have updated the proposal, and thanks for you advise and suggestion, there some explanation about what you concerns:

**there isn’t yet a “Substrate v4”.**

Yes, we know that currently substrate is on v3, and i heard from others(not official) that v4 is comming soon, maybe it's not correct, but i think this is not so much import, we will use latest master branch during development.

**Your project overview is the same text copied 3 times.**

I am very sorry for the stupid mistake, because i copied those lines from other place, i should have a dobule review. The right content already been updated.

**Milestone 3 about ink! integration seems to just be including a contracts pallet. This would not provide any new value to the system, but rather paying you to follow the tutorials for including the pallet in your runtime.**

Yeah, it is easy if we just integrate ink module into our runtime. In our scenario we need read/write runtime from contract and verify if a image/video is exist with substrate offchain worker. So this would be the hard part we gonna to do. Thanks for substrate developers, dispatch call to runtime currently supported, see [here](https://github.com/paritytech/substrate/pull/9276). Besides, we would provide several contract templates to help our developers and communities build their DApps easily.

**"Milestone 2, Nutbox Chain" or "M4, Asset Transfer" deliverables also bring nothing new, all these features are already available and plug-and-play in substrate.**

There was a misunderstanding between us, sorry i haven't explained clearly in the document. The **Asset Transfer ** here is not transfer of balance-pallet, but a currency implementation by ourselves. It may be something like [orml](https://github.com/open-web3-stack/open-runtime-module-library/tree/master/currencies) implemented by Acala. As i know, we have no token standards like ERC20 in polkadot ecosystem, i saw some discussion in [element channel](https://matrix.to/#/!UGygryNZqUDiaXhbIh:web3.foundation?via=web3.foundation&via=matrix.org&via=matrix.parity.io) but nothing got so far, so we may implement by ourself or just use orml's.

The last one **storage proof validation** is the stuff that we need verify some offchain data(images/videos) saved in CDN or IPFS. We will verify them in offchain worker with the saved hash in runtime storage.

**Comment by mmagician** [comment]
Closing due to inactivity and missing details. Feel free to re-open the application with a more complete proposal.

**Comment by tolak** [comment]
@mmagician Thanks, we are preparing add more details into the proposal, would ask reopen this PR once it gets ready.

**Pull request closed without merging**
