### PR TITLE
binary merkle tree application

### PR DESCRIPTION
**Pull request by frisitano**
#### Project Abstract

This project aims to introduce binary merkle tree's as a first class citizen in substrate.  There is a large demand for the usage of binary merkle tree's, especially in the context on zero-knowledge circuits where substrate's native patricia merkle tree is not well suited.  The demand for the existence of binary merkle tree's can be evidenced by reviewing grant applications, many of which are implementing their own binary merkle tree on top of substrates native patricia merkle tree.  This is an inefficient solution and not production ready.  This project will introduce binary merkle tree's as a child tree such that developers can create an interact with the binary merkle tree's via a runtime api.  We are interested in delivering binary merkle tree's such that we can utilise them in the future for zero-knowledge focused substrate projects. 

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by takahser** [comment]
@frisitano thanks for the submission of your grant application! We currently have a rather large backlog to tackle, so it might take a bit longer than usual until we can give you feedback. Nevertheless, we're going to take a look at it as soon as we can.

**Comment by frisitano** [comment]
> @frisitano thanks for the submission of your grant application! We currently have a rather large backlog to tackle, so it might take a bit longer than usual until we can give you feedback. Nevertheless, we're going to take a look at it as soon as we can.

Ok no problem, thank you for giving me the heads up.  I look forward to your feedback!

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. This is quite interesting. (just for reference https://github.com/w3f/Grants-Program/pull/962) Could you add to the specification that the library will be implemented in Rust (just to make sure)? And I have one question regarding the costs of your second milestone. This seems a little bit expensive for just half a month of additional work compared to milestone 1, would you be willing to reduce it?

**Comment by frisitano** [comment]
> Thanks for the application. This is quite interesting. (just for reference #962) Could you add to the specification that the library will be implemented in Rust (just to make sure)? And I have one question regarding the costs of your second milestone. This seems a little bit expensive for just half a month of additional work compared to milestone 1, would you be willing to reduce it?

I've reduced the cost of milestone 2 to $15k and updated the application to explicitly state the use of rust:
"All deliverables of this project will be implemented in rust and will be no_std compatible such that they can be integrated into substrate core."

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I’m happy to go ahead with it and will share it with the rest of the team.

**Review by laboon — APPROVED** [review]

**Review by gautamdhameja — APPROVED** [review]

**Comment by keeganquigley** [comment]
Hi @frisitano is it possible to provide an update as to how M1 is coming along?

**Comment by frisitano** [comment]
Good progress has been made.  We have almost completed milestone 1 - see repo [here](https://github.com/frisitano/binary-merkle-tree).  Unfortunately development has been on pause due to a loss in the family.  We will get the ball rolling again over the next few days and hopefully have the first milestone delivered over the next few weeks.

**Comment by keeganquigley** [comment]
No problem @frisitano very sorry for your loss. Thanks for the update.

**Comment by keeganquigley** [comment]
Hi @frisitano I see that development has started back up which is great; if you find that the delivery will be delayed significantly, please consider filing an [amendment](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval) to extend the timeline, seeing as Milestone 2 will likely also be delayed. Thanks!

**Comment by frisitano** [comment]
Hi @keeganquigley, I have filed the amendment as requested - see here: https://github.com/w3f/Grants-Program/pull/1569

**Comment by keeganquigley** [comment]
Hi @frisitano how's the milestone 2 delivery coming along?

**Comment by frisitano** [comment]
> Hi @frisitano how's the milestone 2 delivery coming along?

Hi @keeganquigley, the delivery of milestone 2 is delayed.  Whilst the work has been fully scoped and planned we have not had an opportunity to start the engineering due to other responsibilities. I plan on making a start on this within the next two weeks. Sorry for the delay.  I hope this is not too much of an inconvenience.

**Comment by Noc2** [comment]
@frisitano Thanks for the update. In this case, could you create a PR to update the contract accordingly?

**Comment by keeganquigley** [comment]
pinging @frisitano

**Comment by frisitano** [comment]
> pinging @frisitano

Hey @keeganquigley, sorry for the delay. I will create a PR to update the contract.

**Comment by keeganquigley** [comment]
Hi @frisitano did you submit this yet?

**Comment by keeganquigley** [comment]
Hi @frisitano are you still planning to submit this? If not, I think we can probably go ahead and close the grant for now and you can possibly pick it back up later, should you wish to continue working on it. For administration purposes, we try to avoid having inactive grants.

**Comment by frisitano** [comment]
Hi @keeganquigley I am still planning to deliver this milestone but I am overloaded with commitments at the minute.  Apologies for the delayed response.  I understand your position of wanting to close this for now and am happy for you to go ahead and do so provided I will be able to open this again when my availability frees up (probably in a couple months time)?

**Comment by keeganquigley** [comment]
Thanks for the update @frisitano sounds good. Opening the grant again in the future will require a PR with 3 committee approvals again, but I personally think this would happen rather quickly, as we don't have any other projects working on merkle trees at the moment afaik. If this works for you I'll go ahead and close it. Thanks!

**Comment by frisitano** [comment]
Yep that works, thanks @keeganquigley!

**Pull request merged**
