### PR TITLE
Iris Amendment: Modify Estimated Duration

### PR DESCRIPTION
**Pull request by driemworks**
#### Project Abstract

This is an amendment to https://github.com/w3f/Grants-Program/pull/958. The only change is a modification of estimated duration.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by driemworks** [comment]
To provide some context:

- The second milestone was both underestimated and some members of the team encountered some extenuating circumstances, but we are nearly ready with that piece. I increased the estimated duration to 3 months from 1.5 months. The piece is near completion but I'll provide some extra buffer to make sue we do things the right way.
- I don't think the third milestone was underestimated, but to be safe I also increased the estimated duration there. I'll be attending the Polkadot blockchain academy in January and it's hard to say exactly how that could impact the duration.

**Comment by alxs** [comment]
Thanks @driemworks. Could you please sign the latest version of the terms and conditions (CLA)? Also to clarify, when do you expect to deliver the next milestone? The amended duration is 3 months, but it's been 5 months since the last delivery. Could you include this in the application?

**Comment by driemworks** [comment]
Signed! and yes, I updated the duration to 5.5. I intend to deliver the next milestone towards the end of next week. The only things remaining from our end is some final testing/fixes and properly documenting test scenarios/guide, so we are really close.

**Review by alxs — APPROVED** [review]
Sounds good! Thanks for the update.

**Review by semuelle — APPROVED** [review]

**Review by Noc2 — APPROVED** [review]

**Review by takahser — APPROVED** [review]

**Review by gautamdhameja — APPROVED** [review]

**Pull request merged**
