### PR TITLE
Amendment to dot_etl project proposal timelines

### PR DESCRIPTION
**Pull request by liangjh**
Add update / amendment to M1 and total timelines.  Have been working on other projects, but we are still committed to delivery of this grant proposal.

#### Project Abstract

This is an amendment (request for extension) of an earlier accepted grant proposal.  All of the details of the original proposal are still valid and are availabled [in the original PR](https://github.com/w3f/Grants-Program/pull/1716).  Thank you.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) address in the application).
- [x] I am aware that, in order to receive a grant, I (and the entity I represent) have to successfully complete a KYC/KYB check.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by liangjh** [comment]
@keeganquigley thanks for reaching out on an extension / amendment to [our original proposal](https://github.com/w3f/Grants-Program/pull/1716/files).  Adding an amendment for an extension on this.  We've been working on other things but are still committed to get to this proposal.  thanks.  (+ @johncandido )

**Comment by liangjh** [comment]
I have read and hereby sign the Contributor License Agreement.

**Review by Noc2 — CHANGES_REQUESTED** [review]
To clarify, what does "from the start of implementation" mean? Maybe you can actually add a date to the application or something like that.

**Comment by semuelle** [comment]
pinging @liangjh

**Comment by liangjh** [comment]
all - thanks for the feedback.  i will add a start date on this -

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. To be honest, a starting date of June 2024 plus 8 months is a significant delay and I don't make sense to sign this already now.  In this case, my recommendation is to cancel it, and if you are still interested in it you can reapply.

**Review by takahser — CHANGES_REQUESTED** [review]
@liangjh echoing @Noc2's concerns, I agree that closing it for now is the better option. Especially since we've already signed some very similar projects that currently are in development, so the landscape is subject to change quickly within the next few months. Hence, I think it makes more sense to re-assess this proposal, once you're ready to implement it.

**Comment by Noc2** [comment]
Thanks again for creating the PR. The committee decided to go ahead and close it. We will also terminate the current grant, but you are more than welcome to apply again, once you want to work on the project.

**Comment by liangjh** [comment]
Hi all, just got to the recent feedback this morning.  Thank you for the feedback, and the comments in the initial review rounds for this proposal back last year.  
I do have a question on this though, do you have a sense of what the review rounds will look like if we re-apply for this grant?  Given that this propose (dot_etl) was already approved by the committee, would an enhanced or updated proposal pass through fairly quickly?   We are still committed to the original thesis of extracting actionable and economically viable data from DOT / substrate.

**Comment by takahser** [comment]
@liangjh As you know, we've signed multiple grants related to the [Analytics Website/Data Platform RFP](https://github.com/w3f/Grants-Program/blob/master/docs/RFPs/analysis-website-and-data-platform.md). So whether I'd add my approval at the time you'd re-apply also depends on the maturity of similar tools and the additional value your solution would bring. However, that's just my opinion and doesn't necessarily reflect the opinion of other w3f grants committee members.

**Pull request closed without merging**
