### PR TITLE
Polkadart Follow-up

### PR DESCRIPTION
**Pull request by leonardocustodio**
#### Project Abstract

[Polkadart Grant](https://github.com/w3f/Grants-Program/blob/master/applications/Polkadart.md)

> We would like to propose support for smart contracts within the Polkadart library. The following features would be included:
> Abi encode & decode
> Support for contract metadata v0, v1, v2, v3, v4.
> Deployment of WASM contracts
> Send contract transactions
> 
> Additionally, we are proposing to make a centralized documentation dedicated to all levels of developers, from beginners to experts. We want to create a website like https://polkadot.js.org/docs where the person would find many tutorials, use cases, scenarios, explain concepts of Polkadot and how to use Polkadart with all best practices and security in mind.
> Only for context, every package has its documentation as delivered in the previous grant, but they are focused on experienced Flutter/Dart developers and people who already understand how Polkadot works.
> We believe that this new documentation would be a great addition to the community as it increases the number of people who will understand the lib and the whole concept of Polkadot, allowing more Flutter/Dart developers to get on board the Polkadot ecosystem.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (Polkadot AssetHub (DOT, USDC & USDT) address in the application and bank details via email, if applicable).
- [x] I am aware that, in order to receive a grant, I (and the entity I represent) have to successfully complete a KYC/KYB check.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by semuelle — COMMENTED** [review]
Hey @leonardocustodio, thanks for the follow-up application. I think it'd be great to have this functionality added to the library. Do you have any plans for further funding after this grant? Otherwise, perhaps it would make sense to _either_ convert this into a maintenance grant _or_ to add a maintenance period and submit it to the Decentralized Futures program.

**Comment by leonardocustodio** [comment]
Hello @semuelle, thank you for the reply.

I believe the team never considered other possibilities. I will talk with them and find out. Are there any other resources you could point us to for reading to help with the decision, mainly the "Decentralized Futures Programs"?

Please let me know if I understood correctly. There are three possible paths:

1. If we don't expect to need more funding after this one, possibly considering "the work is done," at least from our part/team, submit this project as is.
2. If we consider that this library could be continuously improved, like polkadot-js, we could submit the new features and keep doing the work as a maintenance grant, which means we would keep working on it until we or you guys decide that the maintenance grant is no longer needed.
3. Get this application and submit the new features + a maintenance period, similar to #2 but still divided with milestones (features + docs + maintenance) and a more limited maintenance time in mind.

The first would be a typical Grant, the second a Maintenance Grant, and the third a project at the Decentralized Futures Program.

**Comment by leonardocustodio** [comment]
Hello @semuelle, I've read a bit about each program, and at least from what I've read:

Please feel free to correct me. However, it seems this application doesn't qualify for a maintenance grant. The smart contract's new feature is a whole new package, and I consider it a large feature to implement. At the repository, we have the following paragraph:
```
Maintenance grants, as the name suggests, are meant to allow teams/individuals to maintain a particular project, and not to continue its development or implement larger features. Please use the traditional application process for this purpose.
```

We would be between a typical grant and a Decentralized Future Program, am I correct? However, I've talked with the team, and they do have an interest in continuing (if possible) working on the library after what is currently in the application is done. As seen in the repository, from the PRs/Issues/Discussions of developers using the library. There are some great ideas that would be very beneficial to implement and thus increase the adoption of Flutter developers to the Polkadot system even more.

Considering that, perhaps, would you recommend the best path to go forward?

**Comment by semuelle** [comment]
any comments, @leonardocustodio?

**Comment by leonardocustodio** [comment]
Hello @semuelle, sorry the late reply. Yes, totally agree with you, I posted in the polkadot forum a few days ago, per DF requirements: https://forum.polkadot.network/t/decentralized-futures-polkadart/7117
I will make the application in the next few days. Should we close here already?

**Comment by semuelle** [comment]
Let's close this one for now. We can reopen it later if necessary. Thanks, @leonardocustodio.

**Comment by leonardocustodio** [comment]
Hello @semuelle, After carefully evaluating the `Decentralized Future Programs,` we have given up on submitting an application. Unfortunately, we could not figure out how to fund the library's maintenance and development beyond 2024. Our maintainers have limited availability, and a project that would be able to fund the library would be too much work for us. We want to continue with the Grants Program if possible.

Thanks

**Review by semuelle — DISMISSED** [review]
Hi @leonardocustodio. Understood. As I mentioned initially, I'd be happy to see these implemented, so I'll give my approval. 
What I recommend is finding some way to track popularity/use of the library or other useful metrics, which could come in handy if you eventually want to ask for treasury funding.

**Comment by leonardocustodio** [comment]
Awesome, I believe that with the new docs website, we can also include analytics to include this information.
Also, I will add a new last thing to the roadmap (without changing the price). We now have the new offline metadata standard, so I would like to support that in our lib.

**Comment by leonardocustodio** [comment]
Done, if you can take a second look @semuelle .
Appreciate it :)

**Review by semuelle — APPROVED** [review]

**Review by keeganquigley — APPROVED** [review]
Thanks @leonardocustodio based on your answers and also your performance on previous milestones, some of which I personally evaluated, I'm also happy to approve. 

While waiting for other committee members, we recently started doing KYB/KYC checks for grants, could you please use [this KYB link](https://in.sumsub.com/idensic/l/#/uni_iW29BlDPIhrrmtck) to submit verification for your registered entity? Thanks!

**Comment by semuelle** [comment]
> While waiting for other committee members, we recently started doing KYB/KYC checks for grants, could you please use [this KYB link](https://in.sumsub.com/idensic/l/#/uni_iW29BlDPIhrrmtck) to submit verification for your registered entity? Thanks!

Actually, @leonardocustodio, I see that you already started KYB for the DF application. You should have just received an email from Sumsub with a link to that file, so you can continue from there. It seems that there is still some company documentation missing.

**Comment by leonardocustodio** [comment]
Hello @semuelle , I've resent the doc, but they declined it again. I'm not sure they understand how things work here in Brazil, they are requesting:
```
a document that establishes all ultimate beneficial owners (shareholders) of the company. This can include a recent excerpt from the company register, a certificate of incumbency, a register of shareholders, or other similar document
```
I'm sending it, but they refuse because the data is older than 12 months. I'm not sure how it works in other countries, but here, this document has no "remission" unless the company wants to change something. So the date will always remain the same. I don't know what to do here.

Can I change the application to my name instead of the company's name so we can go with KYC? Or do the grants only accept KYB?

**Comment by semuelle** [comment]
> I'm sending it, but they refuse because the date is older than 12 months. I'm not sure how it works in other countries, but here, this document has no "re-emission" unless the company wants to change something. So the date will always remain the same. I don't know what to do here.

Hi @leonardocustodio. Sorry, I'm afraid we rely on our KYB provider with these judgements. Is there a way to re-request the same document? I see that there are at least three different dates in that document. An indication that this document is still valid would probably suffice. Perhaps @dsm-w3f has some suggestions here.

**Comment by leonardocustodio** [comment]
Ok, after talking with the accounting department, I got another document that would serve the purpose. They KYB has been approved now. Thanks.

**Review by Noc2 — APPROVED** [review]

**Pull request merged**
