### PR TITLE
Followup grant for Subcoin

### PR DESCRIPTION
**Pull request by liuchengxu**
#### Project Abstract

Since completing the initial grant, I have been actively addressing the challenges identified in the previous phase (see my contributions to Substrate in this period [here](https://github.com/paritytech/polkadot-sdk/pulls?q=author%3Aliuchengxu+created%3A%3E2024-09-01)). With additional efforts and guidance from the Parity team, I’ve made progress on the critical OOM issue detailed in https://github.com/w3f/Grants-Program/pull/2376#issue-2479916837. I’m confident we can resolve the remaining obstacles in this follow-up grant, ultimately achieving the full vision of Bitcoin Fast Sync.

This follow-up work will also deliver a dedicated CLI tool that enables downloading the UTXO set snapshot compatible with Bitcoin Core without running a regular full node, offering a streamlined option for Bitcoin users and broadening Subcoin’s appeal.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (Polkadot AssetHub (USDC & DOT) address in the application and bank details via email, if applicable).
- [x] I understand that an agreed upon percentage of each milestone will be paid in vested DOT, to the Polkadot address listed in the application.
- [x] I am aware that, in order to receive a grant, I (and the entity I represent) have to successfully complete a KYC/KYB check.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by PieWol** [comment]
Hey @liuchengxu,
sorry for the delay first of all.
thank you for the follow-up application. I like the idea of subcoin and the fact that you are building this on substrate. Usually we only fund projects that try to enhance and build within the Polkadot ecosystem. Yet as a showcase project for Substrate we were able to fund the first application for Subcoin. I don't think we will be able to further fund it's development though. Have you explored all possible options to get funding from the Bitcoin community? I'd assume this would be the better place to finish up the Subcoin network. Especially as the OOM issue is currently listed as a non-goal of this application, even though this would probably be the most helpful improvement for the Polkadot-SDK. I hope you understand my view. Please rest assured that I really like your previous work on Subcoin in the scope of our Grants Program.

**Comment by PieWol** [comment]
I'd love it if we were able to find a way for a follow-up grant through focussing on the improvements to the Polkadot-SDK by resolving the OOM issue with fast-syncing. I also appreciate all the time and effort you put into the draft PR after finishing your grant, trying to solve this issue. I hope someone from Parity will take his time to review and provide feedback 🙏.

**Comment by liuchengxu** [comment]
>Especially as the OOM issue is currently listed as a non-goal of this application

@PieWol  There is a big misunderstanding here. The OOM issue is promised to be resolved as part of the delivery,  please do not forget to read the link at https://github.com/w3f/Grants-Program/pull/2436/files#diff-07c3b0ab56d858beac3add432ac373b100249778a21ee809eeabbb4cc48145ddR103. _The non-goal is the corresponding PR to polkadot-sdk is not guaranteed to be merged within the timeline of this grant_ as the PR review from polkadot-sdk maintainers could be way too slow (I have several PRs already pending for weeks).

>Have you explored all possible options to get funding from the Bitcoin community? I'd assume this would be the better place to finish up the Subcoin network.

I agree. The main idea is to first build something truly usable and then we can promote it to the Bitcoin community, but this is hindered by the obstacles remaining from the initial grant. This follow-up grant aims to resolve these challenges to implement the full fast sync.

**Comment by liuchengxu** [comment]
I have adjusted the milestones by swapping milestone 1 and milestone 2 so that there could be more time for the polkadot-sdk maintainers for the review work. @PieWol Let me know if you have any further questions.

**Comment by PieWol** [comment]
Hey @liuchengxu ,
thanks for your efforts in making this application more appealing to us by prioritizing the substrate fast sync issue. 

I have another funding route I would like to propose to you. You have demonstrated with your previous grant that you are very capable and dedicated. This is a great position to convince the treasury to fund your project. This way you could probably get the funding needed for the fast-sync issue while the remaining funds needed to further develop subcoin could be gathered from the bitcoin community. What do you think?

**Comment by liuchengxu** [comment]
@PieWol Thank you for considering an alternative funding approach. Given the progress we've made on this application, I’d prefer to build on our existing efforts rather than start from scratch with a new route.

If it would make this grant more feasible, I’d be happy to narrow the focus to address just the Substrate fast sync issue, as this represents the continuation of the work done under the initial grant. The UTXO snapshot download tool could then be pursued separately in another route. Let me know if this approach aligns better with your requirements!

**Comment by PieWol** [comment]
Hey @liuchengxu ,
I don't see the treasury route as a reason to start from scratch. Of course you would need to write a little proposal to fill in the general audience thats voting on OpenGov but you can reference this very application and thus reuse all your previous efforts. 

I wouldn't suggest this route if I weren't very confident that you can secure funding through the treasury.
Please understand that treasury funding is preferred by the committee as this allows us to get the most out of the budget we have for our Grants Program.

**Comment by liuchengxu** [comment]
@PieWol Thank you for the clarification and your confidence in securing funding through the treasury. let's go for that route then. I will prepare a treasury proposal that references this application and incorporates the previous work done (_writing a funding proposal is never fun_ :P)

**Comment by liuchengxu** [comment]
The [treasury proposal has been created](https://polkadot.polkassembly.io/referenda/1298). The requested funding on the fast sync task has been increased, as the proposal now includes the commitment to merge the corresponding PRs into the polkadot-sdk repository as the final deliverable. Thank you for your continued support here, and I truly appreciate your backing of the treasury proposal!

**Comment by PieWol** [comment]
Hey @liuchengxu ,
that was quick. Good job with the proposal. As I already said in an earlier comment I'm fond of your work and you have delivered a great first grant. All the best for your proposal and I hope it will be accepted quickly :)

**Comment by PieWol** [comment]
Hey @liuchengxu ,
I also commented your proposal. Here is my [comment](https://polkadot.polkassembly.io/referenda/1298#uxr1eH8VFYKLvfrVWQk8). 

This backlink should also serve the purpose of proving my identity ;)
Best wishes.

**Comment by liuchengxu** [comment]
@PieWol Thank you so much for your support! 🙏 I've submitted the [updated proposal](https://polkadot.polkassembly.io/referenda/1301).

**Pull request closed without merging**
