### PR TITLE
Create NFT_Observer.md

### PR DESCRIPTION
**Pull request by MusabShakeel576**
### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Could you add the deliverables to the tables of the milestones and more details (e.g. programming language)? (see application template: https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) It’s seems currently you only describe in the headline what you actually plan to do (e.g. UI Design & Substrate/Polkadot/Kusama NFTs Listing Option). Also could you share some initial mock-ups or designs with us? Usually this is a requirement for UI focused applications. Will it be based on the following: https://kedruga.com/nftobserver/?

**Comment by MusabShakeel576** [comment]
Thank you for your response, NFT Observer is and will be written in following programming languages: React JS, Node JS, PostgreSQL, and Strapi, which is mentioned in the application.

Yeah it is and will be based on https://kedruga.com/nftobserver, it's a usable website which went through mockups, design and development phases and now we'll be extending its functionality through the help of W3F grants program.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Could you update the application accordingly and feel free to add additional details?

**Comment by MusabShakeel576** [comment]
What should I update? Programming languages are already in the application https://github.com/w3f/Grants-Program/pull/795/files#diff-be57b97284aaeb5c04999fda17639e168b86b5bfa2f5cb912b19f00b8ab9d258R18

and you were only asking about mockup but we have the whole website ready, do you want us to share the mockup of current website?

**Comment by MusabShakeel576** [comment]
NFT Observer is simply just a single page website which showcase NFTs in two categories:

1. 🔥 HOTTEST OF THE HOUR (Premium category)
2. 👑 FRESHEST OF THE DAY (Free category)

For any NFT project who wants to get listed in our first category, they need to provide few information about their project and have to complete the payment according to their NFT blockchain by switching the Chain option.

For any NFT project who wants to get listed in our second category, they can either contact us on Twitter or we are constantly searching for blue chip projects that could be beneficial for investors to flip.

We only list projects that have good stats in a given day or hour, and when a day or hour ends we remove that project and lists new ones, as we are expanding our team we will be more active to search and list projects regularly. We've a dedicated Strapi CMS through which our team can CRUD the NFT projects.

> Are you creating a front-end for the uniques pallet or are you planning on supporting a different pallet, smart contracts or even rmrk or even everything?

Nope, it's not in our application nor in our roadmap, but we'll surely do our research on it.

In first milestone we'll provide frontend source code of NFT Observer written in React JS, with the addition of Polkadot NFT projects and their stats into our website as we currently support ETH, SOL and BSC NFT projects.

In second milestone we'll make NFT Observer's whole backend, frontend and cms open source, which will be available to download through Decentralized Cloud Storage of Polkadot (IPFS), and we'll make all React components like button, table easy to customize by provide theme options in it.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the reply. However, you still haven’t updated the application itself. As I pointed out now multiple times. The tables of the milestones need to contain the actual deliverables and specifications. These are the requirements of our contracts. Could you please update the application? 

Additionally, based on what you describe, it seems like a completely centralised service, almost like a simple blog and users have to pay you to get listed. I personally don’t think we should support something like this via the grant program. Especially since you already have a concrete (centralised) business model. However, this is just my personal opinion and if you update the application accordingly, I can share it with the rest of the team. Also if you want to work on a more decentralised system, it might potentially better fit in the scope of our grant program.

**Comment by MusabShakeel576** [comment]
Application updated, please have a look at it

**Review by Noc2 — COMMENTED** [review]
Thanks for the update. I will share it with the rest of the team. However, I personally won’t approve it, because of the above reasons.

**Comment by alxs** [comment]
@MusabShakeel576 unfortunately I'm with David here, I don't think the grants program is a good fit for your project. Best of luck nevertheless.

**Comment by MusabShakeel576** [comment]
OK thanks, if there is any suggestion to help improve our application, it would be really appreciated, which will help us to learn from this experience for future.

**Review by Noc2 — CHANGES_REQUESTED** [review]
I personally would be willing to support a decentralized version of this. As you pointed out, it could be hosted on IPFS. Ideally the NFTs are selected and shown based on actual statistics/usage and not based on a payment. This might be useful for the ecosystem. A later version could still let people pay for advertising NFTs on the site, but ideally fully transparent and via a smart contract.

**Comment by MusabShakeel576** [comment]
That's a really helpful tip about transparency, but we were thinking about a wide range of adoption so NFT project owners don't have to deal with contracts to pay gas fees, which are relatively costly in Ethereum, where most NFT projects are being built.

So will we pave our project towards your vision? If yes then we'll update the application and step up to Level 2 ($50,000) because it looks like a more work than just a UI change https://github.com/w3f/Grants-Program#:~:text=applying%20for%20a%20smaller%20grant%20that%20only%20consists%20of%2C%20say%2C%20UI%20work

Or is this application closed now?

**Review by takahser — CHANGES_REQUESTED** [review]
Hi @MusabShakeel576

Thanks for being interested in the Web3 Foundation Grants program and submitting this application.

Unfortunately, to me, it currently lacks technical details to be able to give you well-founded feedback. For example:
1. What do you mean by "Freshest" and "Hottest" NFTs?
2. How will you measure which NFTs are "trending"?
3. Which factors will decide if NFTs are "flip-able"?
4. From a technical standpoint, what kind of NFTs are you going to support?

In general, I'm with [@Noc2 's comment](https://github.com/w3f/Grants-Program/pull/795#pullrequestreview-878561621) here.
A decentralized & fully transparent NFT listing site could be interesting. But please add more technical details so we can get a better understanding of what you're planning to do.
Btw, IPFS is not the ["decentralized cloud storage of Polkadot"](https://github.com/w3f/Grants-Program/pull/795/files#diff-be57b97284aaeb5c04999fda17639e168b86b5bfa2f5cb912b19f00b8ab9d258R111), feel free to clarify this part of the application as well.

**Comment by Noc2** [comment]
I’m closing the PR/application due to inactivity. Let me know if I should reopen it.

**Pull request closed without merging**
