### PR TITLE
loop_ecosystem.md

### PR DESCRIPTION
**Pull request by afmmeira**
#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [ ] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for your interest in our grants program. Here is some quick feedback:
- We usually don't support the initial design phase (your milestone 1) and expect teams to have concrete deliveries (e.g., ink! smart contract with certain functionality). 
- For UIs, we usually ask teams to share some mock-ups with us. 
- Also, the payment address and the level needs to be defined at the top of the application, see https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md

**Comment by afmmeira** [comment]
> Thanks for your interest in our grants program. Here is some quick feedback:
> 
> * We usually don't support the initial design phase (your milestone 1) and expect teams to have concrete deliveries (e.g., ink! smart contract with certain functionality).
> * For UIs, we usually ask teams to share some mock-ups with us.
> * Also, the payment address and the level needs to be defined at the top of the application, see https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md

Hi @Noc2 David, thank you very much for your prompt response.

The Loop project is, indeed, in the initial stage of development. However, our developers are already working on basic smart contracts functionalities and a UI prototype, this initial work would be ready to share with you in a couple of weeks. Please bear in mind that those will be just mock-ups and to be able to develop a fully functional and ready to deploy platform, we would have to secure this grant to cover the development costs.

If we secure this grant and, therefore, are able to keep working on the project, we will have to set up a legal entity in Portugal (where we are based) and this entity will have its own bank account. Only when this account is opened I can share the payment address (IBAN) with you.

I look forward to hearing from you.

Best regards,
Andre

**Comment by keeganquigley** [comment]
Thanks for your answer @afmmeira it's okay for the mock-ups to be rough ones, no worries there. When you add them could you also please add some more technical details into the milestone delivery tables? The application is very detailed but the tables need to have the concrete units of work to be evaluated. For example you could integrate some of the tech stack into the deliverables (languages, frameworks, etc.)

Let us know when we should take another look.

**Comment by afmmeira** [comment]
> 

Hi @keeganquigley, thanks for you response. Our developers are working on a UI prototype and basic smart contracts functionalities. When ready, I will also add more details into the milestones. These updates should be ready around mid-August.

Feel free to reach out if you have any questions.

Thanks,
Andre

**Comment by keeganquigley** [comment]
Thanks for the update @afmmeira I will mark it as "on hold" for now but let us know when we should take another look.

**Comment by keeganquigley** [comment]
Hi @afmmeira any updates on the changes?

**Comment by afmmeira** [comment]
> Hi @afmmeira any updates on the changes?

Hi @keeganquigley, apologies for the delay. Due to some staffing constraints, usual during summer time, our developers are taking a bit longer to finalise the mock-ups. I'm aiming to deliver those to you on the second week of September. 

Thanks,
Andre Meira

**Comment by afmmeira** [comment]
Hi @keeganquigley,

I have updated the milestones with some of the technologies, languages and frameworks to be used in this project.
Please see below the link for the first version of the smart contract to be deployed and also attached the UI mock-up:

INK Smart Contract - https://github.com/QubitzAdmin/loop/tree/main 

Feel free to reach out to me if you have any questions.

Thanks,
Andre
[Loop UI mock-up.pdf](https://github.com/w3f/Grants-Program/files/12528445/Loop.UI.mock-up.pdf)

**Comment by afmmeira** [comment]
I have read and hereby sign the Contributor License Agreement.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. I removed the "on hold" label. However, the link https://github.com/QubitzAdmin/loop/tree/main doesn't work for me. Also, could you still update the milestones and the specifications? For example, I suggest removing milestone one completely. Additionally, we require teams to share a Registered Address with us. If you don't want to do this publicly, you at least need to send us an email at grants@web3.foundation with the address. Finally, could you add the level of the grant application at the top and in general make sure that the application is according to our [template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md)?

**Comment by afmmeira** [comment]
Hi @Noc2 , 

Thanks for you prompt response.
I have deleted the milestone 1 as you suggested so now the Loop's roadmap for development is broken down into 5 milestones. Level 3 added to the application. I have previously added the languages and frameworks for each milestone, may you please clarify what else is needed under specifications, so that I can discuss it with our developers? 
With regards to the link for the smart contract and a registered address, I will send you more info by email soon.

Thanks,
Andre

**Review by semuelle — CHANGES_REQUESTED** [review]
Thank you for the application, @afmmeira. I will add to what David and Keegan already stated and say that this proposal is not a good fit for the grants program. 

1. We would need more techical details to properly evaluate this application. For example, you write that you want to "deploy the system to the mainnet". What mainnet? 
2. The first milestone sounds like fungible and non-fungible token implementations, which already exist in abundance.
3. The backend is not part of the deliverables. Do I understand correctly that you are not planning to open source it then? This might be problematic, because deliverables shouldn't depend heavily on proprietary software. Also, how would we test the frontend (M2) without the backend?
4. Deployment (M5) costs are [specifically excluded from funding](https://grants.web3.foundation/docs/faq#what-activitiespositions-do-you-fund).

Feel free to improve upon the current application and wait for other committee members to comment, but in its current form I cannot support this application.

**Comment by afmmeira** [comment]
Hi Sebastian,

Thank you for taking the time to review our proposal for the initial phase
of the "Loop" project. We've carefully considered your feedback and would
like to offer clarifications and additional information regarding our
approach and vision.

   1. *Technical Details*:
      - We understand the need for more in-depth technical specifics. In
      our first phase, as detailed in "Milestone 1: Design &
Architecture," we've
      laid out plans for system design, data models, specifications, and a
      comprehensive whitepaper. These deliverables aim to offer a solid
      foundation, explaining the technical intricacies and rationale behind our
      choices.
   2. *Token Implementations*:
      - We'd like to emphasize that while fungible and non-fungible tokens
      (as per "Milestone 2") are integral parts of our platform, they
aren't the
      entirety. The uniqueness of our platform stems from the integration of
      these tokens into a cohesive loyalty rewards system, which is innovative
      and not just another run-of-the-mill token implementation.
   3. *Backend Concerns*:
      - As our project develops, our vision is to maintain a balance
      between transparency and proprietary business logic. Key backend
      components, essential for integration and testing, will be made available
      to the necessary stakeholders. Further, our comprehensive
documentation, as
      covered in "Milestone 6," will ensure that both developers and users have
      the required resources for successful integration and understanding.
   4. *Deployment Costs*:
      - We acknowledge the committee's concern about excluding deployment
      costs. However, the "Deployment" in "Milestone 6" encompasses
not just the
      associated costs but the culmination of our efforts across all
milestones,
      ensuring the platform is robust and ready for real-world use.

Our goal with this initial phase of Loop is to establish it as a proof of
concept. We firmly believe that this approach will effectively demonstrate
the utility and innovation behind Loop to our potential merchants and
brands, convincing them of the transformative potential of our platform.
Once this foundation is solidified, and we've garnered sufficient interest
and feedback, our intent is to initiate the migration of Loop to a
parachain infrastructure, enabling more advanced features, cross-chain
compatibility, and enhanced scalability.

We genuinely believe in the potential and innovativeness of Loop. While we
appreciate constructive feedback and will continuously refine our approach
based on it, we urge the committee to recognize the long-term vision and
the transformative impact Loop could have in the loyalty rewards landscape.

Looking forward to continued dialogue and collaboration.


Best regards,

Andre Meira

Sebastian Müller ***@***.***> escreveu no dia segunda,
25/09/2023 à(s) 19:03:

**Comment by semuelle** [comment]
Hi @afmmeira. I am going to reopen your pull request. Please add the information from your comment and make changes to the application as per the committee's comments above.

**Comment by afmmeira** [comment]
Hi @semuelle ,

Thanks for reopening our pull request. I have added more info to the milestones as per the committee comments. I am just waiting for some inputs from the developers to finalize it. I will let you know once ready. 

Best regards,
Andre

**Comment by keeganquigley** [comment]
Hi @afmmeira any changes here you can update us on? I will mark the application as on hold for now.

**Comment by afmmeira** [comment]
Hi Keegan,

Apologies for the delay of my response.
I have been discussing with the developers the best development roadmap
structure as per the committee's comments, which is taking longer than
expected. I will be updating the application and informing you as soon as
possible.

Best,
Andre Meira

Keegan | W3F ***@***.***> escreveu no dia terça, 24/10/2023
à(s) 23:45:

**Comment by afmmeira** [comment]
Hi @keeganquigley,

Apologies for the length of this application updating process. We have now made the necessary changes based on the committee's comments.
I look forward to hearing from you.

Best regards,
Andre Meira

**Comment by keeganquigley** [comment]
Thanks @afmmeira I will remove the "on hold" status and take a look later today.

**Comment by keeganquigley** [comment]
Thanks for making the changes @afmmeira and for all the hard work you've put into this application. However I personally am not willing to approve it, as I'm not seeing that much changed, since the price is still $80k, and some issues haven't been addressed. For example, I'm not sure what you mean by "Polkadot & Substrate mainnet". I'm not convinced that your team has enough knowledge about our ecosystem yet to

Thanks @afmmeira for making the changes, and for all the work you've put into this application. However, I'm not seeing that much has changed. For example, the overall price is the same, and I'm still not sure what you mean by "Polkadot & Substrate mainnet". At this point I'm not convinced that your team has enough knowledge about our ecosystem yet to fund something at this price point. Therefore I am personally not going to approve it.

That being said, I will mark the application as ready for review and ping the rest of the committee to take a look.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for your application, the updates, and all the effort you put into this. However, the grants committee decided to close the application. This is partly because of the missing details, as Keegan pointed out. Independent of it, we wish you all the best with your project, and we encourage you to try to get it funded via VCs instead.

**Pull request closed without merging**
