### PR TITLE
Fiat on-off ramps amendment

### PR DESCRIPTION
**Pull request by dastansam**
#### Fiat on-off ramps amendment

Hey there!

We are submitting this amendment as per our discussion in the Element chat. Core part of the deliverable of this milestone is updated, since it would not make sense to add smart contract support for a simple demo app. Instead, we are currently making necessary changes on the protocol level (adding extrinsics, storage entries, etc.) so that there is no need for us to add smart contract support. This is mostly a huge refactoring work, which you can track here in this [PR](https://github.com/element36-io/ocw-ebics/pull/21). It is almost complete and once we merge this PR, we will start working on the milestone 3 deliverable: a DApp connected to our chain.

Duration is increased to 1.5 months, due to the above details. So, we assume that the deliverable for this milestone will be ready in around 1 month, assuming that we are on the finish line with refactoring work.

### CODE REVIEW

**Comment by dastansam** [comment]
@keeganquigley tagging for visibility, thanks

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the PR and the update. Could @wstrametz  and @wasabrot also confirm that they are happy with the changes since they created the original application? Also, could everyone who contributed to the PR still sign our latest terms and conditions?

**Comment by wasabrot** [comment]
> Thanks a lot for the PR and the update. Could @wstrametz and @wasabrot also confirm that they are happy with the changes since they created the original application? Also, could everyone who contributed to the PR still sign our latest terms and conditions?

Yes - confirm that, we worked on that together last couple of days

**Comment by wstrametz** [comment]
> > Thanks a lot for the PR and the update. Could @wstrametz and @wasabrot also confirm that they are happy with the changes since they created the original application? Also, could everyone who contributed to the PR still sign our latest terms and conditions?
> 
> Yes - confirm that, we worked on that together last couple of days

Affirmative - also confirm that.

**Review by randombishop — APPROVED** [review]
LG

**Review by keeganquigley — APPROVED** [review]

**Pull request merged**
