### PR TITLE
Stardust Uncollateralized Stablecoin

### PR DESCRIPTION
**Pull request by adit313**
### Project Abstract

Response for uncollateralized stablecoin RFP (https://github.com/w3f/Grants-Program/blob/master/rfps/uncollateralized-stablecoin.md). We are proposing a derivatives backed stablecoin architecture. 

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the application. I’m personally quite interested in this. Could you maybe add to the deliverables the names of the stablecoins that you plan on investigating (e.g. Luna, Fei, etc) and potentially a review or summary of the existing research? I’m especially interested in the mechanism behind Luna and if it would also be stable without terraform labs basically controlling the entire supply ([see for example one of the addresses controlled by them](https://finder.terra.money/mainnet/address/terra1dp0taj85ruc299rkdvzp4z5pfg6z6swaed74e6)).

**Comment by adit313** [comment]
Hi David, we're also super interested in the stablecoin/defi space. We've done a healthy amount of research into it already, and are happy to collate, review and summarize the current state of academic research on it as a meta-study. There is actually quite a lot in terms of academic resources and we'd be happy to pull it together. 

In terms of the specific extant stablecoins we were planning to look at, we've got a pretty long list: Angle Labs, Luna, Terra, DAI, Tether, USDC, BinanceUSD, Gemini Dollar, TrueUSD, Pax Dollar, NeutrinoUSD, Tribe, Frax, Liquidity USD, HUSD, XSGD, Reserve Rights, Origin dollar, Facebook's Diem. We're looking at the current top stablecoins by demand/trading volume and some of the new interesting ones. Our logic here is to group them by mechanism where appropriate (e.g. BinanceUSD and Gemini Dollar) and deep dive into how they work and their advantages, limitations, and economic dynamics.

Then on top of that we wanted to study and report on a few big failures: IRON which was tied to TITAN, Fei, Ampleforth, EmptySetDollar, DynamicSetDollar, BasisCash, NuBits.

I also know it's not something in the original RFP, but there is also quite a bit out there from the U.S. Federal Government alone that has been published on Stablecoins, from the U.S. Treasury's summary from 6 months ago (https://home.treasury.gov/system/files/136/StableCoinReport_Nov1_508.pdf) to the most recent executive action from Biden a few days ago that has a lot of language about stable coins (https://www.whitehouse.gov/briefing-room/presidential-actions/2022/03/09/executive-order-on-ensuring-responsible-development-of-digital-assets/). I think a lot of that would also be very useful to summarize, particularly the future looking perspectives and regulatory implications.

Having written all that, it's a healthy amount of work to research and build; a general overview of the modern stablecoin ecosystem, deep dives into the largest existing ones and the most notable failures, and a summary of the current state of academic research. Do you mind if we add as a fourth topic, a section on the U.S. Government's current viewpoint and new developments and package all of this research as Milestone 1? Also this could be more than a 1 person-month amount of research so I wanted to get a gauge of whether we keep to the timeframe and resource allocation of the RFP or is it preferred to deep dive into each of these topics and expand the research scope? We are happy to do either, just wanted to get a sense of whether the team was looking for a relatively high-touch summary or if it's something the foundation would like to see analyzed in depth from all angles. We're thinking at a high-level we can do it in 1 person-month, but if we go deeper below the surface and analyze their holdings, accounts and smart contracts, we're estimating it more at 2 person-months.

Let us know your thoughts, and we'll be happy to adjust the proposal to best fit the desired scope.

-Adit

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the detailed reply here and sorry for the late reply. Feel free to add the protocols which you mentioned to the specification of the deliverables. You can also add a section on the U.S. Government's current viewpoint and new developments. In general, the scope of the RFP is far from perfect and can definitely be changed. That said, it’s usually best to start with a smaller grant and later apply for follow-up grants. This way we get a better understanding of your work, etc..

**Comment by adit313** [comment]
Perfect! We also agree on that logic, as it's a lot better to tackle this piece by piece. We might actually split this up into multiple milestones then, that have short durations and smaller deliverables. We are going to split those 4 sections into their own milestones of smaller amounts and durations, starting off with Milestone 1 as the current state of the stablecoin industry. That way we can deliver and get your feedback in tighter loops before tackling too much, too quickly.

**Comment by adit313** [comment]
We just pushed a new updated version, we separated the individual research pieces into milestones and moved the overall state of the industry as milestone 1 to be delivered in 2 weeks. Based on that we can update the following milestones which we've put as TBD but with our current estimates for duration and cost as well. Let us know if this scope/format works for you guys.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. But the total amount currently would require you to update the application to a level 2 grant. My suggestion would be for now to focus on the first 2 milestones and apply for a level 1 grant (max 10k). Later you can then apply for a follow-up grant. Also something to be aware of, we usually don’t sign grants with estimated amounts. The grant ideally should contain concrete numbers and we can potentially amend it later, if you put more work into it and the committee accepts this additional work.

**Comment by adit313** [comment]
Thanks for the feedback, we've made those changes and just pushed an updated version. We appreciate all the guidance so far. Just a question in terms of research deliverable format, does the team prefer white papers or PowerPoints? We'll probably end up including a ton of quantitative studies, which are easier for a reader to grasp in a well structured PowerPoint, but we're also happy to submit our research as a white paper and include the studies as relevant figures. It's really about what format you prefer.

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I’m happy to go ahead with it and share it with the rest of the team. Regarding the format, this is basically up to you. There might be certain requirements, in case you want to submit your research somewhere else.

**Review by alxs — APPROVED** [review]
LGTM. More than happy to support the first phase of the project given the current application.

**Comment by adit313** [comment]
Really appreciate it! We've already gotten started and look forward to submitting our first milestone report in 2 weeks. Really appreciate all the help!

**Comment by adit313** [comment]
Hi David, just wanted to keep you abreast of of our progress. We're making good progress and expect to have it to the team by next Friday. It's taking an extra week as we are trying to go a bit deeper into the dynamics of the space. It's been a bit slower then we would've liked hunting down all the different stablecoin projects, their numbers and reviewing all their whitepapers. The deck has swelled to 60 slides, but there is a lot of interesting material and we're super excited to share a lot of the insights with the team.

Let us know if you have anything you'd like to see in particular. We're through 40 slides and should be wrapped up by next Friday at this rate.

**Comment by adit313** [comment]
Hi David, we just finished and uploaded our summary to github. Feel free to check it out! Also let us know if you have any deeper questions or want to see anything teased out in more detail.

https://github.com/adit313/State-of-the-Stablecoin-Industry

Also we need to change the ethereum address that the payment will be sent to before we submit the milestone and invoice, is there an easy way to do that or should we fork, change the address and do another pull request?

**Comment by Noc2** [comment]
Great. Feel free to deliver the milestone [here](https://github.com/w3f/Grant-Milestone-Delivery) and if you want to update the ethereum address, you just need to create a pr to update your original application.

**Comment by adit313** [comment]
Hi David, in light of recent events, should we focus our M2 deliverable predominantly around the Terra depeg? Happy to update the grant request, but we feel we've done a pretty substantive high level summary of the non-algorithmic stablecoin architectures in milestone 1. The real story for milestone 2 is probably going to be Terra and recent events. There is a LOT to cover from the massive outflows in Anchor, to the saturation of Curve Pools, to the deployment of their BTC reserves. It's probably going to be the primary focus in any case as each of those topics has fascinating dynamics and that we'd have to cover it to do any breakdown of algorithmic coins like Terra any justice.

**Comment by Noc2** [comment]
@adit313 I fully agree with this. Feel free to update the contract. I actually told Seraya that this might make sense for this grant.

**Comment by adit313** [comment]
Perfect, just submitted the PR for the updated milestone 2.

**Pull request merged**
