### PR TITLE
Afloat's Migration to Polkadot

### PR DESCRIPTION
**Pull request by LouiseWReed**
### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).

[Afloat](https://stayafloat.io/#/) is one of the first real-use cases of blockchain technology in the accounting industry. It enables the fractional buying and selling of tax credits that historically have been inefficient, opaque, and centralized. It has already processed tax credits ranging in orders from $2K -$70k USD.

Afloat was built on a private Ethereum clone but wants to migrate to Polkadot due to its technology, identity management, and community. Parachains like Kilt and their identity services would be crucial at validating government roles and professional certifications like accountants and institutional sellers. 

> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

n/a
### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] Hackathon
- [x] Personal Recommendation
- [ ] Substrate Builders Program
- [ ] Investor/VC
- [ ] Online Search 
- [ ] Other: _______

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the application. This looks interesting to me. So, just to double check and for my understanding: Do you want to create a permissioned chain, since you previously used a private ethereum chain or do you want to actually connect to polkadot in the future? Because if you want to create a public chain, I’d like to know more about your privacy setup/features, since this is usually a big issue. Regarding your application itself, could you potentially split up the Substrate Modules deliverables into separate deliverables. It currently seems to contain not only substrate modules, but also frontend deliveries and other tools. Also feel free to add the programming language to the specifications. In general, the table of the milestones are basically the requirements of our contracts. So the more concrete technical information you provide with the specifications the better.

**Comment by 3yekn** [comment]
@Noc2 Hi David, in terms of private/public, the plan is to use encrypted data saved to IPFS (or similar) and referenced on a public chain. Some data and metadata, such as amount, expiration year, etc, will not be encrypted. However, there will be documents and other evidentiary materials that will be encrypted. Token balances and parties within a transaction will not be encrypted, so we won't need to use SGX or ZKP. A more accurate way to frame the required feature may be something like "Confidential Documents" (where `documents` is a loose term to include any data referenced within a transaction or NFT data but not on-chain data itself).

We have reviewed a number of approaches so far, and it seems like Multiparty Attribute-based Encryption may be a good option. There's been a good amount of research to draw on in this area, as well as development of some [libraries](https://github.com/Fraunhofer-AISEC/rabe). 

We may implement this in steps depending on the timeline and UX requirements. At it's simplest, we can use symmetric AES to encrypt IPFS documents and have the secret shared out of band. A step up from that, we would likely require our own wallet/plugin to encrypt the data based on the decryption needs. This could be user-to-user RSA encryption short-term, but this won't scale as nicely as we'd like because it will require re-encryption for each new user. This is where CP-ABE is much better.

I am also going to do a deep dive on [Kepler](https://www.spruceid.com/kepler), which isn't yet compatible with Substrate but it is with some other protocols. That team (Spruce) provides tooling (e.g. SSI) similar to Kilt, so perhaps there's an opportunity to integrate something around that. 

Here's the Issue where we are tracking our needs on this, which is a core problem/solution set of Hashed Network:
https://github.com/hashed-io/hashed-substrate/issues/27

I will work with @LouiseWReed to provide more concrete technical info on the other deliverables in the grant request.

**Comment by 3yekn** [comment]
Hi @Noc2 - I updated the milestones with more specific deliverables. Also, I noticed that the Verida proposal was just approved, and it may be something that we can use for Confidential Documents. This one: https://github.com/w3f/Grants-Program/blob/master/applications/verida_network.md

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I’m happy to go ahead with it and share it with the rest of the team. Just one more comment: maybe you can also add the programming languages to more specifications of the milestones. This usually helps a lot to understand what exactly is going to be implemented (pallet, front-end, etc.).

**Comment by Noc2** [comment]
> Hi @Noc2 - I updated the milestones with more specific deliverables. Also, I noticed that the Verida proposal was just approved, and it may be something that we can use for Confidential Documents. This one: https://github.com/w3f/Grants-Program/blob/master/applications/verida_network.md

Feel free to contact the team directly here on github or let us know if you want to be introduced to them.

**Review by laboon — APPROVED** [review]
Happy to approve this - it's quite an interesting approach and use case of blockchain tech.

**Comment by hakan-w3f** [comment]
Looking forward to seeing this migration from Ethereum, and its integration with identity providing parachains.

**Review by hakan-w3f — APPROVED** [review]
Looking forward to seeing this migration from Ethereum, and its integration with identity providing parachains.

**Comment by LouiseWReed** [comment]
Thank you for checking in. I’m checking in with the team

**Comment by LouiseWReed** [comment]
Submitted this afternoon…
Thank you for the reminder

**Comment by randombishop** [comment]
@LouiseWReed 
As I am evaluating milestone 2, I am also catching up with the grant scope and previous delivery. Please bear with me a few days as I digest all the details.
First, I like your very specific and practical application here.
Also wanted to shoot a question: how do you guarantee that the entity who submits the tax credits in chain won't go and "double spend" them through another means? Is there a process by which the credits are locked with the IRS knowing about it?
Thanks!

**Comment by 21abigail21** [comment]
Hi, @randombishop, that's a great question! 

Currently, Afloat holds the buyer's money until the buyer receives a confirmation letter from the credit's state tax department. We also facilitate a Sales Contract that specifically states that if a government jurisdiction deems the credits double-spent, the seller needs to make the buyer economically whole and that the buyer understands the value of the tax credits for their own personal tax situation.

In the future, we hope to be more integrated with the IRS tax credit transfer process, which is why we submitted a comment letter earlier this month after the IRS requested comments on preventing duplication and fraud with their new federal transferable tax credits. I've attached our letter to this comment.

[2022.11.04 IRS Comment Letter.docx](https://github.com/w3f/Grants-Program/files/10034433/2022.11.04.IRS.Comment.Letter.docx)

**Comment by randombishop** [comment]
@21abigail21 Thanks for the clarification and for sharing your letter to the IRS, very promising indeed. I hope the IRS understands the value and responds positively.
Good luck!

**Pull request merged**
