### PR TITLE
Vue.js + TypeScript Substrate Front-End Template Project Proposal

### PR DESCRIPTION
**Pull request by MilosRandelovic**
#### Project Abstract

When building our app, we have used a very useful existing community template - the [Substrate Front End Template](https://github.com/substrate-developer-hub/substrate-front-end-template) from the Substrate Developer Hub. This template is built using React.js and JavaScript. We are proposing to create an _alternative_ version of this template, which would achieve two major outcomes:

1) It would be written using TypeScript as opposed to JavaScript.
2) It would use Vue.js instead of React.js.

We believe that the combination of TypeScript's strong, static typing, and Vue's simplicity will together serve the purpose of providing an alternative source of very clear examples of how to interface with a Substrate Node from a modern front-end application, which should be of great value to the community.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [ ] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [x] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@milosr:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the grant application. Could you still sign the terms and conditions? Also, your PR is currently in the draft stage. Does this mean you still want to work on it before we take a look at it? Some of the information from the [application-template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) seems to be missing at the moment. For example “Payment Address:” or the default deliverables 0a-0d, which are usually mandatory for all milestones.

**Comment by MilosRandelovic** [comment]
Hey @Noc2, thanks for the reply. We are still working on the proposal, hence the draft stage (I wasn't expecting the bot would move it immediately from the forked repository, before being final, to be honest :)). I appreciate clarifying missing details, as I wasn't sure from the README if I should follow the application template or the RFP folder suggestion template.

I do have two questions at this stage, if you don't mind:
1) Is is possible to provide payment details at a later stage of the process?
2) Our team ([Wunderbar Network](https://wunderbar.network)) is already part of the Substrate Builders programme and has recently passed Milestone 1 on another project. Do we still need to provide all the Team details from the application template?

Thanks!

**Review by Noc2 — CHANGES_REQUESTED** [review]
Sorry for the delay here. I was OOO for some time and forget to reply here. You can always amend/update the contract later, by creating another PR. An amendment that adds the payment should usually be very easy to approve. So yes, you can add the payment address at a later stage. 
Regarding your second question, in general, we don’t care so much about the team details, but more about the milestone and the technical details of the deliveries. That said, not all grants committee members have access to the information that you shared with Parity as part of the SBP.  So if you want us to be aware of something, you need to integrate it here as well.

**Comment by Noc2** [comment]
Btw. since the application is not yet ready, I’m closing it for now. Feel free to ping me if I should reopen it or let me know if you have any other questions in the meantime.

**Pull request closed without merging**
