### PR TITLE
update hazelword.md

### PR DESCRIPTION
**Pull request by ydong3**
Thanks for your reply, we update for this.
Due to our reasons, it cannot be updated at #538, so our close #538 and keep the current

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
K, thanks for the new PR. Could you still sign the Terms & Conditions? Also the formatting of your application seems to be off. For example could you remove “Milestone 2 Example” or “Governance and staking” is probably a separate milestone, etc. Also in general it’s difficult to understand what you want to do exactly with each deliverable. So it might help if you make the specification more concrete (programming language, etc.). Furthermore, does dapp	Quote Vault UI only contain the UI? You should probably start with the smart contract/pallet before you develop the UI.

**Comment by ydong3** [comment]
> K, thanks for the new PR. Could you still sign the Terms & Conditions? Also the formatting of your application seems to be off. For example could you remove “Milestone 2 Example” or “Governance and staking” is probably a separate milestone, etc. Also in general it’s difficult to understand what you want to do exactly with each deliverable. So it might help if you make the specification more concrete (programming language, etc.). Furthermore, does dapp Quote Vault UI only contain the UI? You should probably start with the smart contract/pallet before you develop the UI.

Thank you for your reply, it has been updated

**Comment by ydong3** [comment]
### Project Abstract

Hazel is a blockchain-oriented prediction service which features decentralization, or more specifically, a new generation of verifiable oracle machine based on Polkadot. It aims to exactly support the on-chain operation of enterprise-level Internet applications with high-concurrency through consensus mechanisms, smart contracts, trusted computing, privacy protection and the interaction of on-chain and off-chain data.

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] The total funding amount of the project is below USD $30k for first-time grant applications and $100k for follow-up ones.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. However, regarding milestone 1: Something you should be aware of, is that we usually don’t fund the development of solidity smart contracts. The reason is that we are no experts when it comes to solidity and it’s very difficult to judge what is new and what does already exist at this point. For your second milestone: Do you have any mock-ups or designs? Regarding your last milestone, do you have more information about the tee module? Also did you take a look at other tee based projects in our ecosystem (e.g. https://github.com/integritee-network/substraTEE or crust network or Automata Network)?

**Comment by ydong3** [comment]
> Thanks for the update. However, regarding milestone 1: Something you should be aware of, is that we usually don’t fund the development of solidity smart contracts. The reason is that we are no experts when it comes to solidity and it’s very difficult to judge what is new and what does already exist at this point. For your second milestone: Do you have any mock-ups or designs? Regarding your last milestone, do you have more information about the tee module? Also did you take a look at other tee based projects in our ecosystem (e.g. https://github.com/integritee-network/substraTEE or crust network or Automata Network)?

Regarding Milestone 1: Our early thoughts were based on Vitalik Buterin article “UNI should become an oracle token” (https://gov.uniswap.org/t/uni-should- become-an-oracle-token/11988), this article has a big idea of our project, because our current R&D personnel are more professional in Solidity language. So is there any way to get funding?
The second milestone: we have a design model (https://github.com/Hazelword/hzl-sol/blob/main/doc/h1.png) (https://github.com/Hazelword/hzl-sol/blob/main/doc/h2.png) (https://github.com/Hazelword/hzl-sol/blob/main/doc/h3.png)

Regarding the third milestone tee module, thank you very much for sharing, we will investigate whether it can be used

**Comment by Noc2** [comment]
In this case, I suggest maybe take a look at other grant programs in our ecosystem that support the development of solidity smart contracts (and specifically focus on it), see for example https://moonbeam.foundation/grants/ or in general [here](https://github.com/w3f/Grants-Program#other-grant-programs). Therefore I’m closing the application for now. Let me know in case you want to use ink! or substrate instead for your project and I will reopen it.

**Comment by ydong3** [comment]
> In this case, I suggest maybe take a look at other grant programs in our ecosystem that support the development of solidity smart contracts (and specifically focus on it), see for example https://moonbeam.foundation/grants/ or in general [here](https://github.com/w3f/Grants-Program#other-grant-programs). Therefore I’m closing the application for now. Let me know in case you want to use ink! or substrate instead for your project and I will reopen it.

After discussion and feasibility evaluation, our team decided to adopt ink!  to realize our  oracle machine based on Polkadot,we need to revise the milestone again, please reopen it

**Comment by ydong3** [comment]
we revised the technical roadmap

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. I have a few follow-up questions/comments:

- Could you integrate the designs, which you previously shared into the application (specifically milestone 2)? 
- Could you replace lnk with Ink (L instead of i)? 
- Could you also integrate unit tests? 
- If you have already existing solidity smart contract for Price chain, etc. Feel free to link to them as part of the specification.

**Comment by ydong3** [comment]
> Thanks for the update

Thanks for your correction，We fixed the above issues and submitted the changes

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the updates and integrating the links. However, regarding the solidity smart contracts, you are just linking to your entire repo. Could you instead link to specific contracts that you want to implement in ink as part of the price chain delivery?  Also if I understand it correctly: Vitalik is basically arguing that the token that is used for such an oracle needs to have a really big market cap. How do you want to overcome this issue?

**Comment by ydong3** [comment]
> Thanks for the updates and integrating the links. However, regarding the solidity smart contracts, you are just linking to your entire repo. Could you instead link to specific contracts that you want to implement in ink as part of the price chain delivery? Also if I understand it correctly: Vitalik is basically arguing that the token that is used for such an oracle needs to have a really big market cap. How do you want to overcome this issue?

We believe that what Vitalik said is that the cost of an oracle attack is maximized, so the market value is the key. More want to express that the cost of an oracle attack must be very high, and infinitely high, for most of the price information generated by "trusted" nodes As far as the oracle is concerned, the attack cost is the cost of controlling more than 50% of the reputation nodes. So they need a high market value, and we, the price chain itself is an anti-attack algorithm. For example, the validator Y trades with the bidder X, and Y needs to leave a new quotation when the transaction is completed, and the size of the quotation is β times. When β = 2, Quote Vault p=1000ETH, time period T1=1 minute, initial quote x=10ETH, then in the case of all transactions, x1=2020ETH, x2=4040ETH, x3=8080ETH. .. By analogy, the attacker will either face a huge arbitrage opportunity in the market (the scale continues to increase, and this attack is almost ineffective), or continue to use extremely high-scale assets to conduct self-trading based on the opportunity to delay the price in the market. , If a block of the current chain can contain 10 transactions, then about 10 blocks can provide one hundred valid transactions in 1 minute, 1010^100=2*10^300ETH, which will be an impossible amount and The ability to resist attacks is also beyond the reach of most centralized data source oracles.

Finally, we believe that in the world of permissionless smart contracts versus smart contracts, each unit price provided by the oracle must be verified on the chain and be absolutely secure to be able to serve the trillion-dollar asset market in the future .

**Review by Noc2 — CHANGES_REQUESTED** [review]
Sorry for the late response here. However, the repo which you linked contains a lot of smart contracts, but I don’t know which ones specifically implement the logic of the “Price chain”. For example where can I find the predictor, consumer, corretor etc? Also the post, which you linked by “Vitalik Buterin” (not sure it’s actually vitalik) describes a potential oracle system for stablecoins. I’m pretty sure this wouldn’t work for ETH or DOT, given the price volatility and even for stablecoins, I’m not sure this works (as multiple people point out in the responses). And finally, I still have trouble understanding everything you mention as part of your application. The deliverables should clearly describe what you are going to implement.

**Comment by ydong3** [comment]
> contracts

Let's take Uniswap as an example. When there is no new transaction of ETH/USDT in Uniswap, we can determine that the current price of ETH/USDT in Uniswap can be equivalent to the market price, because no transaction means no arbitrage opportunity.
On the contrary, once the oracle quotation deviates from the market price, it means that the verifier has an opportunity for arbitrage. The verifier will implement the arbitrage strategy (https://github.com/Hazelword/hzl-sol/blob/main/doc/asset.png), and will correct the deviation of the oracle from the quoted market price until the arbitrage strategy is in the economy The above is no longer attractive, and the price of the oracle returns to the normal market price at this time.

some other, here(https://github.com/Hazelword/hzl-sol/blob/main/contracts/HzlMining.sol) implement the logic of the “Price chain”, This method(settlement) implements the construction

**Comment by Noc2** [comment]
The price of eth in USD is changing every second on various exchanges. There is obviously an arbitrage possibility between the different exchange rates from time to time for a very short time, however it is difficult to benefit from this and not sure how this is related to oracles.

**Comment by Lederstrumpf** [comment]
Hi @ydong3, we've discussed this application internally at length and I'm closing it because it lacks clarity, is verbose, and most importantly the technical scope and design goals are ill defined. Feel free to reapply if you can rewrite it more concisely, and in particular improve the structure of the `Project Architecture` section.

**Comment by ydong3** [comment]
> Hi @ydong3, we've discussed this application internally at length and I'm closing it because it lacks clarity, is verbose, and most importantly the technical scope and design goals are ill defined. Feel free to reapply if you can rewrite it more concisely, and in particular improve the structure of the `Project Architecture` section.

Our document may not express our ideas concisely, we have rewritten it，please help us reopen this

**Pull request closed without merging**
