### PR TITLE
FiDi DotSight Analytics Proposal

### PR DESCRIPTION
**Pull request by fidiroman**
#### Project Abstract
This project is a response to Keegan Quigley’s [RFP #1539](https://github.com/w3f/Grants-Program/blob/master/docs/RFPs/Open/analysis-website-and-data-platform.md) inspired by Rob Habermeier’s Polkadot forum [post](https://forum.polkadot.network/t/dune-analytics-style-data-service-for-polkadot-kusama/271).

We propose the development of FiDi DotSight, a platform designed to facilitate interactive on-chain analysis in the Polkadot and Kusama ecosystems. Think Dune for DotSama. FiDi will achieve this by providing a scalable platform that enables users to query on-chain metrics, integrate new protocols, and build beautiful custom dashboards with the power of Subsquid’s data archives. To accomplish this, FiDi, with Subsquid’s support, will offer a SQL-like interface for developers to associate existing and newly developed squids with a dashboard of their choice, along with a suite of default ready-to-use analytical dashboards for users to visualize on-chain data.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by keeganquigley — CHANGES_REQUESTED** [review]
Thanks for the application @fidiroman happy to see it. A couple initial comments:

- Your current dashboard is nice but I'm not finding the open-source code for it in your [repo](https://github.com/fidi-tech). Is it currently private?
- Are you able to provide the GitHub accounts for your devs to see previous work?
- More technical details could still be added to the delivery tables themselves, for example is the front-end just React? Or is a framework like Next.js used? Is it Javascript or Typescript? The more details the better. Thanks!

**Comment by fidiroman** [comment]
Appreciate your feedback @keeganquigley; see the updated [PR](https://github.com/w3f/Grants-Program/pull/1748/commits/63c2680ad94ebc5759b070ab735b22f3b1c8831b) - 

- Added more technical details in-line in the delivery tables; let us know if any other areas also need more clarity, and we'd be happy to add or discuss.
- Re: EVM/WASM - we'll support querying for both, in the scope of Astar, but also any other parachain allowing WASM contracts, e.g., Phala, Crust, Edgeware, et al. We'll abstract away the contracts' nature since DotSight will be a presentation and querying layer on top of higher-level metrics such as balances, counts, volumes, wallet numbers, and others. Just added that to the PR as well.
- Re: GitHub accounts and public repos - we just started on decoupling and open-sourcing parts of FiDi's stack and aim to have all UI widgets, data interface, and parts of the querying module completely open-sourced. The widgets will be made public as part of Milestone 1 in the coming weeks. Please let us know if you'd like us to accelerate this or if you prefer a public repo stub for now. The team members' GitHub accounts have only private contributions due to our backgrounds in corporate tech; let us know what else might help the foundation to confirm our ability to deliver.

Many thanks for your support, and we look forward to your further comments!

**Comment by keeganquigley** [comment]
Thanks for the changes @fidiroman it's looking a lot better now. I will go ahead and mark your application as ready for review and share it with the rest of the committee. However please note the following [requirement](https://github.com/w3f/Grants-Program#guidelines):

- All code produced as part of a grant must be **open-sourced**, and it must also not rely on closed-source software for full functionality.

So if the dashboard were to rely on React components that are in private repos for example, these would need to be made public. But we'll see what the rest of the committee says. Can you also specify which license you would be using?

**Review by keeganquigley — DISMISSED** [review]
Thanks for making the changes. I'm willing to go forward with it and give you a chance.

**Review by Noc2 — DISMISSED** [review]
Thanks for the application. I'm happy to support it.

**Comment by takahser** [comment]
@fidiroman I've got a couple of questions:

- can you lead me the process of onboarding/signing up a new user from a technical point of view? For example, are you going to use OAuth2 or would the user have to sign a message through their wallet? Where are the users going to be stored and how?
- will it be possible for users to fork other user's dashboards and modify these forks?
- you're mentioning a _SQL-powered option_ in M4. What exactly does that mean? Are you referring to an SQL editor here? I think it'd be good if you could add wireframes for the _2. SQL View UI_ deliverable

**Review by takahser — CHANGES_REQUESTED** [review]
@fidiroman feel free to update the doc to incoorperate answers to my [questions](https://github.com/w3f/Grants-Program/pull/1748#issuecomment-1571910338).

**Comment by fidiroman** [comment]
Thanks for your feedback @takahser, great callouts!
* Regarding the authentication, we'll implement wallet-signed authentication initially - it balances the privacy/security concerns with the user experience best right now. FiDi won't store any authentication data on its end, and the contributions will be wallet-signed at the commit time. See more in the [User authentication/authorization](https://github.com/w3f/Grants-Program/blob/a52f7471307f5d5e3ec0f0d02591c588bf4ef7b1/applications/fidi-dotsight-analytics.md#user-authenticationauthorization) section.
* Indeed! We'll support forking and reusing user dashboards and encourage community-driven development. The data inheritance will also be supported, i.e., augmenting existing dashboards with new data effortlessly.
* Yes, this will be shaped as a SQL editor with a simplified SQL and support for embedded GraphQL. We've added a quick wireframe to the proposal to illustrate the engineering direction there.

Take a look at the [follow-up commit](https://github.com/w3f/Grants-Program/blob/a52f7471307f5d5e3ec0f0d02591c588bf4ef7b1/applications/fidi-dotsight-analytics.md), and we look forward to any further comments; thanks!

**Review by Noc2 — APPROVED** [review]

**Review by takahser — APPROVED** [review]
@fidiroman thanks for answering the questions and updating the doc. Looks good to me now! Happy to approve here.

**Review by takahser — APPROVED** [review]

**Review by keeganquigley — APPROVED** [review]

**Comment by keeganquigley** [comment]
Hi @fidiroman how is M4 coming along?

**Comment by fidiroman** [comment]
Hi @keeganquigley! This grant was successfully completed on Mar 21st ([last delivery](https://github.com/w3f/Grant-Milestone-Delivery/pull/1157)), and M4 was [adjusted](https://github.com/w3f/Grants-Program/pull/2258#issuecomment-2016886259) prior to that. 

In relevant news, we'll be submitting our code-free intelligence proposal to OpenGov next week when the on-chain identity is brought back to the users in v1.2.7 and lets us verify.

**Pull request merged**
