### PR TITLE
DistributedKeyManagement.md

### PR DESCRIPTION
**Pull request by jettblu**
#### Project Abstract

This grant is focused on using distributed secret sharing to simplify key management. Development is split into two parts: a research paper that analyzes the distributed key management model and a public, reference implementation. When combined, the research paper and accompanying software will provide an alternative model to key management, which is typically done through a complex hardware wallet, single chain smart contracts, or insecure hot wallets. 

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Prxogram/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for your interest in our grants program and sorry for the late reply. My only comment/request would be: could you make it more specific with the deliveries that this is also beneficial for the Polkadot/Kusama/Substrate ecosystem.

**Comment by jettblu** [comment]
> Thanks for your interest in our grants program and sorry for the late reply. My only comment/request would be: could you make it more specific with the deliveries that this is also beneficial for the Polkadot/Kusama/Substrate ecosystem.

Hi there, thanks for taking a look! I have updated the grant application with additional information pertaining to Polkadot/Kusama/Substrate specific benefits. Please let me know if any further clarifications need to be made.

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I’m happy to go ahead with it and share it with the rest of the team.

**Review by gautamdhameja — APPROVED** [review]

**Comment by jettblu** [comment]
Hi there, I see the application has been merged. Are there any next steps I need to complete? I reviewed the guidelines, but I am still unsure of what the next steps in the application process are.

**Comment by semuelle** [comment]
> Hi there, I see the application has been merged! I reviewed the guidelines, but I am still unsure of what the next steps in the application process are.

An application being merged means it is accepted. We have a bot that usually posts a comment describing the next steps, but since your document is in the wrong folder, it did not trigger. The next step would be for you to conduct the work described in the application and then submit the first milestone as described in our [milestone delivery repo](https://github.com/w3f/Grant-Milestone-Delivery).

> In addition, I notice I added my application to the wrong directory (docs instead of applications). Should I create a PR that moves my app to the correct directory? Thanks for your help!

Good catch. I already went ahead and did that.

**Comment by semuelle** [comment]
For completeness sake, here is the text:

Congratulations and welcome to the Web3 Foundation Grants Program! Please refer to our [Milestone Delivery repository](https://github.com/w3f/Grant-Milestone-Delivery/) for instructions on how to submit milestones and invoices, our [FAQ](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md) for frequently asked questions and the [support section of our README](https://github.com/w3f/Grants-Program/blob/master/README.md#support) for more ways to find answers to your questions.

Before you start, take a moment to read through our [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md) for all communications related to the grant or make them known to the right person in your organisation. In particular, please <b>don't announce the grant publicly before at least the first milestone of your project has been approved.</b> At that point or shortly before, you can get in touch with us at grantsPR@web3.foundation and we'll be happy to collaborate on an announcement about the work you’re doing.

Lastly, please remember to let us know in case you run into any delays or deviate from the deliverables in your application. You can either leave a comment here or directly request to amend your application via PR. We wish you luck with your project! :rocket:

**Comment by jettblu** [comment]
Gotcha'! Thank you for the quick and thorough response. Looking forward to research and completing the milestones!

**Pull request merged**
