### PR TITLE
Update CosmWasmVM-CoreProduct.md

### PR DESCRIPTION
**Pull request by JafarAz**
Amending timelines as requested due to the delay in the grant submission.

@keeganquigley @semuelle sirs, what would be the correct way to amend the timeline? The current estimated duration of the milestones is not that far off from what it would take. One reason for the delay is that we had to pause the development for a period in Q2 however, we're actively working on getting this ready by end of this month.

### CODE REVIEW

**Comment by JafarAz** [comment]
@Noc2 unfortunately the original contributors to the application are no longer members of Composable. https://docs.composable.finance/ecosystem/the-composable-team our docs verify that I am part of the Composable team however, happy to verify via an alternate method

**Comment by semuelle** [comment]
> Please verify via alternative method then.

I have confirmed that Jafar works for Composable. 

@JafarAz, is the timeline until August still up to date?

**Comment by semuelle** [comment]
pinging @JafarAz

**Comment by JafarAz** [comment]
Hi, apologies for the delayed response. I will update the file to show it as September. I'm currently working on the submission as we speak.

**Comment by JafarAz** [comment]
I have read and hereby sign the Contributor License Agreement.

**Review by semuelle — APPROVED** [review]
Thanks. LGTM.

**Review by nikw3f — APPROVED** [review]

**Pull request merged**
