### PR TITLE
MINE Network Grants Application

### PR DESCRIPTION
**Pull request by polkamine**
# Grant Application Checklist

- [x] The [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application and sorry for the late response. I have a few questions: 

- What are potential attack vectors of your solution and how do you prevent them? The tokenization of centralized assets (hash rate) seems difficult to me. Are you using some form of collateral? 
- It seems you need to store a lot of data on-chain. Have you considered using off-chain storage?   
- How exactly does the Oracle work? This seems to be the most important part of the project. 
- Do you already have some code, which you could share? 
- Could you integrate unit tests into the deliverables?

**Comment by polkamine** [comment]
> * What are potential attack vectors of your solution and how do you prevent them? The tokenization of centralized assets (hash rate) seems difficult to me. Are you using some form of collateral?

Potential risks may be the attack to our rewards oracles, we will work with Substrate’s Off-chain Worker and Chainlink to make the oracle safe. And also if their price is below or equal to zero or fallback, it will call the Polkamine backup price oracle, which will be maintained by the randomly selected validators from our validators group.

The tokenization of centralized assets(hash rate) is just selling the ownership of hashrate power in the mining pool, which is a very mature industry now. You could see the success of BTCST and lots of cloud mining platforms like Bitdeer of Bitmain.
 
Also the mining pool standardization of Polkamine will be audited by the renowned third-party audit agencies and supervised by PolkaDAO with third-party experts, KOLs, founders from mining pools and DeFi protocols.

> * It seems you need to store a lot of data on-chain. Have you considered using off-chain storage?

Yes, we have to use off-chain storage, which could be untrusted clouds with IPFS included to make it safe.

> * How exactly does the Oracle work? This seems to be the most important part of the project.

As mentioned before, we will work with Substrate’s Off-chain Worker and Chainlink or Band protocol to build the oracle. And also Polkamine will leverage the validators group to run the oracles as the backups at the same time.

If their price is below or equal to zero or fallback, it will call the Polkamine backup price oracle, which will be maintained by the randomly selected validators.

> * Do you already have some code, which you could share?

We finished the tests for issuance and staking contracts on Ethereum before and gonna work on DAO contract. Once we have the grants, we will start the development on Substrate pallets. We can add you into our GitHub to check those private repos.

> * Could you integrate unit tests into the deliverables?

Sure, we will modify the PR soon and we will change our project name from Polkamine to MINE Network in this PR.

**Comment by Noc2** [comment]
Thanks for the reply. Could you integrate the additional information into the specification of the deliverables, for example regarding the oracle solution? Also how is your oracle solution different from the [ORML-Oracle](https://github.com/open-web3-stack/open-runtime-module-library/tree/master/oracle)? Regarding offchain storage, you might want to take a look at https://rs-ipfs.github.io/offchain-ipfs-manual/. And just a reminder to add unit tests to the deliverables. Also feel free to add me to your github organisation.

**Comment by polkamine** [comment]
> Thanks for the reply. Could you integrate the additional information into the specification of the deliverables, for example regarding the oracle solution? Also how is your oracle solution different from the [ORML-Oracle](https://github.com/open-web3-stack/open-runtime-module-library/tree/master/oracle)? Regarding offchain storage, you might want to take a look at https://rs-ipfs.github.io/offchain-ipfs-manual/. And just a reminder to add unit tests to the deliverables. Also feel free to add me to your github organisation.

Just added unit test as deliverable and added your into our repo

**Comment by Noc2** [comment]
Thanks. Could you still provide more information about the oracles? As far as I can see, your current solidity oracle solution is simply setRewardStats and therefore as centralized as it gets or am I missing something. Also why are you only integrating unit tests into the Mining Pool Standardization Pallet and not into the oracle part? Furthermore, your website (https://mine.network/) currently returns an error (404) and doesn’t load for me.

**Comment by mmagician** [comment]
I don't think this project makes sense. I've also checked a few of the projects you listed in your comparison table and none of them look credible to me.
Here are the main flaws I see:
- You say that mining pools are not open about their costs & profits. Well, this is for a reason and I find it hard to believe they will suddenly be open to an external auditor.
- The very presence of the external auditor that is supposed to **physically** go on-site and inspect the mining machines is a huge attack vector. Unless the auditor is on-site constantly, how can you ensure that the machines are still online? There is no way to monitor the hash-rate on-chain.
- How are users going to claim the underlying asset based on the wrapped asset? You need a bridge for each of the assets separately, right? I'm assuming that you won't be creating all the (decentralised) bridges yourself, so going over a centralised channel creates another point for the attack.
- Who is supposed to perform the maintenance of the machines if the mining farm is owned by a DAO?

**Comment by polkamine** [comment]
> Thanks for the reply. Could you integrate the additional information into the specification of the deliverables, for example regarding the oracle solution? Also how is your oracle solution different from the [ORML-Oracle](https://github.com/open-web3-stack/open-runtime-module-library/tree/master/oracle)? Regarding offchain storage, you might want to take a look at https://rs-ipfs.github.io/offchain-ipfs-manual/. And just a reminder to add unit tests to the deliverables. Also feel free to add me to your github organisation.

Yes, we could integrate the ORML-Oracle into Polkamine’s Oracle solutions and open the Oracle data-feeding services to the network’s validator group. But in order to make Oracle decentralized and safe enough, we will also cooperate with third-party Oracle services providers like Chianlink and Band Protocol to back our Oracle solution. As for the off-chain storage, we will take a look into the IPFS, and also some untrusted cloud services providers to make the storage fully decentralized and safe.

**Comment by Noc2** [comment]
Thanks for the reply. Acala’s solution also works together with chainlink as far as I know. It would be nice if you could provide more (technical) information about how exactly you want to create a decentralized oracle solution. This seems to me the most important part of your project and something that we would be willing to support in case it’s unique for our ecosystem and potentially also useful for others. Also maybe you could address some of @mmagician's  concerns.

**Comment by polkamine** [comment]
> I don't think this project makes sense. I've also checked a few of the projects you listed in your comparison table and none of them look credible to me.
> Here are the main flaws I see:
> 
> * You say that mining pools are not open about their costs & profits. Well, this is for a reason and I find it hard to believe they will suddenly be open to an external auditor.

In MINE Network, the mining pools are either self-built or purchased (through the standardization) by DAO, so in order to make the operations totally transparent, we will give all the information to the third-party auditor to publish the audit report to the pToken holders.

> * The very presence of the external auditor that is supposed to **physically** go on-site and inspect the mining machines is a huge attack vector. Unless the auditor is on-site constantly, how can you ensure that the machines are still online? There is no way to monitor the hash-rate on-chain.

The mining industry is quite mature, so the online monitoring software could help the mining operators and managers, which is also the important part of the DAO,  to know well the daily performance of the mining pool. 
The DAO will disclose the mining pool addresses to the community, and they could observe the online activity and mining power on-chain.
The DAO will invite accomplished third-party auditors to join in the DAO, and they will keep a close eye on the mining pool performances.
The DAO will distribute the rewards everyday based on the mining power which is very easy to see whether the rewards are matching the real power, since this is a mature industry with about 10 years.

> * How are users going to claim the underlying asset based on the wrapped asset? You need a bridge for each of the assets separately, right? I'm assuming that you won't be creating all the (decentralised) bridges yourself, so going over a centralised channel creates another point for the attack.

We will build the cross-chain bridges mainly focused on Bitcoin and Ethereum, and the bridges will use the MPC and TSS algorithms to make them fully decentralized and safe. Also, the relay services of the cross-chain bridges will open to our Validator group to improve the robustness.

> * Who is supposed to perform the maintenance of the machines if the mining farm is owned by a DAO?

Part of The DAO members will be mining pool operators, who will perform the maintenance of the machines,  just like the ETH2.0 validators of Lido DAO.

**Comment by mmagician** [comment]
Closing due to inactivity, it seems that your application hasn't convinced enough committee members to support it. Feel free to apply in the future with a new or updated proposal.

**Pull request closed without merging**
