### PR TITLE
Decentralized invoice system

### PR DESCRIPTION
**Pull request by herou**
### Project Abstract

We aim to build an Escrow pallet that will help communities to release funds easier to devs/teams
and the web3 community would have a simple escrow system implemented in web3.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying?

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] I have read and understood the [FAQs](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md), [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md) and [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).
- [x] I prefer the discussion of this application to be in a private Element/Matrix channel. My username is: ``@_______``

### How Did You Hear About our grants program?

- [x] Social Media
- [ ] Hackathon
- [x] Personal Recommendation
- [ ] Substrate Builders Program
- [ ] Investor/VC
- [x] Online Search
- [ ] Other: _______

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. I have two initial questions/comments: 

- First, how do you deal/plan to deal with privacy issues? I mean most companies probably don’t want to put their invoices or any information regarding this on-chain. Also, things like GDPR might be problematic here. Do you plan on using IPFS? 
- Second, I think the price is relatively high at the moment. Given that you want to basically implement a single pallet with three functions if I understand the application correctly.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the quick reply. I will mark the application as ready for review since it’s in a status in which others should take a look at it as well. However, regarding privacy, I was mostly referring to the technology itself, once it’s deployed as a parachain or independent blockchain. My assumption is that companies won’t be able to use this without any additional privacy layer, etc. Regarding the price, I still think it would be nice if you could reduce it a little bit, but others might have a different opinion regarding this.

**Comment by herou** [comment]
> Thanks for the application. I have two initial questions/comments:
> 
> * First, how do you deal/plan to deal with privacy issues? I mean most companies probably don’t want to put their invoices or any information regarding this on-chain. Also, things like GDPR might be problematic here. Do you plan on using IPFS?
> * Second, I think the price is relatively high at the moment. Given that you want to basically implement a single pallet with three functions if I understand the application correctly.

@Noc2 Thank you for your reply. I am thinking to make the amount to 15-16k. Is it okay for you?

**Review by Noc2 — CHANGES_REQUESTED** [review]
How about 10k? In this case, it would be a level 1 grant and only needs one additional approval. It would also still be nice if you could comment on my privacy concerns.

**Review by semuelle — COMMENTED** [review]
Like @Noc2, I am also skeptical that anyone would be willing to put their invoice data on a public ledger. Also, at least in Germany, an invoice is not valid unless it also contains
- an invoice number,
- the issuer's tax ID,
- recipient's address,
- what was delivered and when.

That being said, I could see this being used by individuals or sporadically. I think the 10k David proposed would be fair, also considering that the escrow pallet was 9k. Are you planning to use this yourself? Perhaps host a frontend for it? Or do you just want to "put it out there"?

**Comment by herou** [comment]
> Like @Noc2, I am also skeptical that anyone would be willing to put their invoice data on a public ledger. Also, at least in Germany, an invoice is not valid unless it also contains
> 
> * an invoice number,
> * the issuer's tax ID,
> * recipient's address,
> * what was delivered and when.
> 
> That being said, I could see this being used by individuals or sporadically. I think the 10k David proposed would be fair, also considering that the escrow pallet was 9k. Are you planning to use this yourself? Perhaps host a frontend for it? Or do you just want to "put it out there"?

In Germany and many more countries, there is no specific regulation for crypto.
I am planning to use it.
I will build a front end as well.

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I’m happy to go ahead with it. It might be useful for permissioned/private chains.

**Comment by herou** [comment]
Hi @Noc2 ,
Because of end of year vacation we are going to postpone a bit our first deliver. We are planning to deliver all 3 milestones at once. Is it okay? Please let me know. Thank you!

**Comment by Noc2** [comment]
Hi @herou, late delivery is usually not an issue. But if it's delayed for a more extended period, I suggest creating an amendment (via a PR) so that the contract is updated.  You can also deliver all milestones simultaneously, but this comes with additional risk (e.g., disagreement regarding the scope of the first milestone), and it might take a little bit longer to get paid.

**Pull request merged**
