### PR TITLE
WIP : Substrate enterprise based on Hyperledger Fabric

### PR DESCRIPTION
**Pull request by muddlebee**
#### Substrate enterprise based on Hyperledger Fabric

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [ ] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [ ] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) address in the application).
- [ ] The software delivered for this grant will be released under an open-source license specified in the application.
- [ ] The initial PR contains only one commit (squash and force-push if needed).
- [ ] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by muddlebee** [comment]
I have read and hereby sign the Contributor License Agreement.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for your interest in our grants program. This sounds like an interesting initiative. I just want to point out that if you combine the enterprise focus with a long-term plan and potentially additional services in the future, it could be a great fit for our new program: https://futures.web3.foundation/

**Comment by keeganquigley** [comment]
Hi @muddlebee I see that this application is still a draft. Do you intend to make changes or should we review it as is?

**Comment by muddlebee** [comment]
thank you @Noc2 @keeganquigley for the reply. 

We are still figuring out things and planning a long term roadmap for this. 

I'm talking with other developers who know about Hyperledger and Substrate. We're discussing how easy or hard it is to build on it and what they think about it. I'm especially interested in what parts of Hyperledger Fabric they would like to see in Substrate. This is important to make sure that if we start building something, there will be people interested in using it, so we can keep making it better.

I hope its okay if we keep in draft state, till the time we figure out a concrete roadmap.

**Comment by muddlebee** [comment]
thank you @Noc2 @keeganquigley for the reply. 

We are still figuring out things and planning a long term roadmap for this. 

I'm talking with other developers who know about Hyperledger and Substrate. We're discussing how easy or hard it is to build on it and what they think about it. I'm especially interested in what parts of Hyperledger Fabric they would like to see in Substrate. This is important to make sure that if we start building something, there will be people interested in using it, so we can keep making it better.

I hope its okay if we keep in draft state, till the time we figure out a concrete roadmap. 

Also if you have some ideas on how we can make the proposal better? Please feel free to add or share. I have put a rough outline of our proposal in the PR draft.

**Pull request closed without merging**
