### PR TITLE
RFPs readme

### PR DESCRIPTION
**Pull request by semuelle**

### CODE REVIEW

**Comment by mmagician** [comment]
I feel like that's going to be hard to maintain

**Comment by semuelle** [comment]
The list of RFPs comes from a script.

**Comment by mmagician** [comment]
Ah fair! Can we run that script on changes to the RFP folder? Or probably easier: add some instructions on how to run it?

**Comment by semuelle** [comment]
I'll create a shared doc.

**Review by Noc2 — APPROVED** [review]

**Pull request merged**
