### PR TITLE
Create sandox.md

### PR DESCRIPTION
**Pull request by TradeLinkEstonia**
#### Project Abstract

SanDOx is an IDE built as a browser app that consist of tool panels.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks for the application @TradeLinkEstonia although, I think wouldn't this application be more in response to the [Browser IDE](https://github.com/w3f/Grants-Program/blob/master/docs/RFPs/Open/IDE_for_ink_Smart_Contracts.md) RFP? Considering the Javascript console is really the only focus that would replace the one in Polkadot-JS, but doesn't aim to replace the entire dev console (extrinsics, chain state, RPC calls,etc) is that correct?

We are also looking for a new maintainer of the [ink! Playground](https://ink-playground.substrate.io/) previously maintained by Parity. Is this something that you'd be interested in, or was your initial goal to build one from scratch?

**Comment by TradeLinkEstonia** [comment]
@keeganquigley hello, Keegan!
In this application we propose to develop an in-browser IDE basically for JS. For now, on this first stage we begin with development of the app shell and lately we will be able to add new panels and features. The functionality mentioned by you like extrinsics, chain state, RPC calls should be completed on later stages. I can add these entire features to the future plans section if it is critical. And Ink! support would be also a great feature in future, so I'd propose to add multi stack support lately. This will be a very powerful tool then.

**Comment by keeganquigley** [comment]
Thanks @TradeLinkEstonia that would be great if you could add it into future plans. With a project like this, my main concern would be whether or not the project would continue to be maintained. I am also not saying I don't think it's needed, I just meant that it might fall more in line with the ink! RFP. Regardless, I will mark your application as ready for review so the rest of the committee can comment.

**Comment by TradeLinkEstonia** [comment]
@keeganquigley I've added a few more points to the `future plans` section of the application. Right now we are impressed by the seen opportunities and for sure - if this tool will be in demand by the DOT developers community, we will be happy to support and develop it further.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Looks interesting. Would you also be willing to integrate some of the requested features here: https://github.com/w3f/Grants-Program/blob/master/docs/RFPs/Open/alternative-polkadot-js-api-console.md#deliverables-nut_and_bolt Specifically the option to save your code.

**Comment by TradeLinkEstonia** [comment]
Hello, @Noc2 
There's a deliverable in our last milestone called 'Settings and projects storage' which includes local storage of projects. I've just added dowloading a ZIP archived project to it's description.
For now we plan to realize only one session, so you couldn't open two different projects in parallel sessions, but if there's a need for such a feature, we can add it on later stages of the project.

**Review by Noc2 — APPROVED** [review]
Thanks for the quick reply. I'm happy to go ahead with it.

**Review by keeganquigley — APPROVED** [review]
Thanks for the changes @TradeLinkEstonia I think this is very needed in the ecosystem with the current status of the ink! playground so I'm happy to approve it as well.

**Review by takahser — APPROVED** [review]
Happy to approve as well here.

**Comment by TradeLinkEstonia** [comment]
WoW! Many thaks for this opportunity. We are looking forward to deliver!

**Comment by semuelle** [comment]
> So I suggest to slightly move the delivery date to the end of next week (6-7th of July).

Thanks for the update, @TradeLinkEstonia. Delays of a few weeks are generally not an issue. Please proceed as usual. Let us know if you foresee any further delays, we might want to sign an amendment to the original roadmap then.

**Pull request merged**
