### PR TITLE
Orand Pull Request

### PR DESCRIPTION
**Pull request by hubertnguyen88**
#### Project Abstract

Orand is an Elliptic Curve Verifiable Random Function (ECVRF: https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-vrf-05) as a service that offers high performance, zero latency and 30 times lower cost than current providers. Orand offers on-chain verification and pseudorandom for projects that seek integrity and transparency in their features with a wide variety of case studies from card games, MMORPG to NFT collectibles

**Verifiable randomness**: We’re using Verifiable Random Function (VRF) to generate randomness the process described here https://www.rfc-editor.org/rfc/rfc6979 . Curve secp256k1 was used to minimizing verification cost for smart contract on Ethereum.

**Dispersity**: A distributed system with many participants/nodes will join to generate randomness by using Multi Party Computation (MPC).

**Unpredictability**: A VRF will perform with the input is previous randomness and it’s also require half of participants to participate in MPC.

**High throughput**: Game/application server could request randomness from the Orochi đRNG system. The result will be provided as soon as half of participants participate in the MPC.

**Fault Proof**: If the game/application server tries to delay the feeding process to manipulate the result, a fault proof will be committed so sue the game server.

**Multi-chain**: All EVM compatible blockchains can be supported.
#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [x] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@hubertnguyen:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. One quick initial feedback: Please only add one file to our repo as part of the PR. So only the one that you add to the application folder.

**Comment by hubertnguyen88** [comment]
> Thanks for the application. One quick initial feedback: Please only add one file to our repo as part of the PR. So only the one that you add to the application folder.

Got it, could you please help proceed further, are you still reviewing it?

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. But you are still adding two files for the repo. Could you change this?

**Comment by hubertnguyen88** [comment]
> Thanks for the update. But you are still adding two files for the repo (RFP and application). Could you change this?
Hi, i have deleted in RFP folder. I intend to fork application to Orochi's report and make a pull request for application from there, instead from my personal git account. Is it ok?

**Comment by hubertnguyen88** [comment]
> Thanks for the update. But you are still adding two files for the repo (RFP and application). Could you change this?

Hi, i have deleted in RFP folder. I intend to fork application to Orochi's report and make a pull request for application from there, instead from my personal git account. Is it ok?

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks. The application now contains only one file. So this is correct. Regarding the application itself, could you add more technical details, like the programming language to the milestones as well as the default deliverables of the template: https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#milestone-1-example--basic-functionality See:

>  “❗ The default deliverables 0a-0d below are mandatory for all milestones, and deliverable 0e at least for the last one.”

**Comment by hubertnguyen88** [comment]
> Thanks. The application now contains only one file. So this is correct. Regarding the application itself, could you add more technical details, like the programming language to the milestones as well as the default deliverables of the template: https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#milestone-1-example--basic-functionality See:
> 
> > “❗ The default deliverables 0a-0d below are mandatory for all milestones, and deliverable 0e at least for the last one.”

Thank you, we will update the milestone information. And will make a pull request from Orochi's repo instead my personal account.

**Pull request closed without merging**
