### PR TITLE
Create ParaSpell_Maintenance.md

### PR DESCRIPTION
**Pull request by dudo50**
#### Project Abstract

This proposal is for ParaSpell XCM SDK, Docs & UI maintenance.
We previously successfully completed two applications:
[Phase 1](https://github.com/w3f/Grants-Program/pull/1118)
[Phase 2](https://github.com/w3f/Grants-Program/pull/1245)

Reasons for opting for a maintenance grant are mentioned in our application doc.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Ethereum USDC address for the payment of the milestones is provided in the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the application. Signing maintenance grants is for us a little bit more difficult at the moment since it’s not fully covered by our terms and conditions, and we also need to sign a regular contract via docusign. Did you already consider to apply for treasury funding for this project? This seems to be a perfect fit for the treasury, and the treasury should probably also finance these tools in the long run.  We would be happy to help you with the application. See also this maintenance bounty: https://kusama.polkassembly.io/post/1545

**Comment by dudo50** [comment]
@Noc2 thank you for your advice. Our team will soon look into it.
With kind regards,
team ParaSpell

**Comment by Noc2** [comment]
The maintenance bounty is only for teams that previously received treasury funding from Kusama. But I still think it makes sense to start applying for treasuring funding in general with this project. 
Feel free to take a look at the [guide](https://docs.google.com/document/d/1p3UQUjph5t8TVaWnTkfrI5mE-BABnM9Xvtuhdlhl6JE/edit) and [template](https://docs.google.com/document/d/14E019tobfgoQTGgX4LRnbh7grOlD8yQsfqWuAgrsJMw/edit) and let me know if you have any questions or reach out to grants@web3.foundation. In the meantime, I’m closing the PR for now.

**Comment by dudo50** [comment]
Thank you @Noc2. We have moved our proposal to Kusama Treasury based on your suggestion.
[link](https://kusama.polkassembly.io/post/2474)

**Pull request closed without merging**
