### PR TITLE
Application :Dfinnwallet

### PR DESCRIPTION
**Pull request by Bharathcoorg**
#### Project Abstract

DFINN Wallet is a comprehensive non-custodial solution for Substrate and EVM Blockchains, leveraging Polkadot.js capabilities. With a focus on enhancing user experience and refining the interface, our wallet serves as a gateway to the Web3 multiverse, providing easy access to multi-chain services while prioritizing security and user convenience. Our purpose-built Mobile App, available on Android and iOS, facilitates seamless interaction with blockchain applications, offering users a frictionless journey into the world of decentralized finance.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (Polkadot AssetHub (DOT, USDC & USDT) address in the application and bank details via email, if applicable).
- [x] I understand that 30% of each milestone will be paid in vested DOT, to the Polkadot AssetHub address listed in the application.
- [x] I am aware that, in order to receive a grant, I (and the entity I represent) have to successfully complete a KYC/KYB check.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@bharathcoorg:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by Bharathcoorg** [comment]
> I have read and hereby sign the Contributor License Agreement.

**Comment by Bharathcoorg** [comment]
I have read and hereby sign the Contributor License Agreement.

**Review by keeganquigley — CHANGES_REQUESTED** [review]
Hi @Bharathcoorg thanks for the application. 

- You mention "Substrate & EVM chains" I'm not sure if this means you intend to have compatibility for both WASM & EVM (similar to Talisman), or do you only intend to support the EVM chains built with substrate, such as Moonbeam and Astar?
- What advantages would this wallet have over the existing ones you mentioned (SubWallet, Nova, etc.) and why do you want to build one from the ground up?
- The grants program doesn't cover 3rd party audits, therefore could you remove milestone 2 and adjust the cost accordingly? That should drop you down to a level 1 grant which only needs two approvals.

**Comment by Bharathcoorg** [comment]
> Hi @Bharathcoorg thanks for the application.
> 
> * You mention "Substrate & EVM chains" I'm not sure if this means you intend to have compatibility for both WASM & EVM (similar to Talisman), or do you only intend to support the EVM chains built with substrate, such as Moonbeam and Astar?
> * What advantages would this wallet have over the existing ones you mentioned (SubWallet, Nova, etc.) and why do you want to build one from the ground up?
> * The grants program doesn't cover 3rd party audits, therefore could you remove milestone 2 and adjust the cost accordingly? That should drop you down to a level 1 grant which only needs two approvals.


> * Dfinn wallet supports all substrate and all EVM blockchains. Not only Substrate EVM chains. 

>* At dfinnwallet, we're dedicated to creating new and innovative features that make our wallet stand out from the rest. Our aim is to introduce functionalities that are unique and not commonly found in other wallet solutions. In the current milestone, we've included at least 3–6 features that you won't find in other wallets. The live version of our app is already available on the App Store and Play Store.
I didn't mention some features I have in mind, such as the interact and earn platform and the AI dapp security scanner. I'll need to conduct thorough research on these features. I'll provide more details about these features in future milestones if needed.

>*Removed milestone 2 and downgraded to Level 1.

**Comment by keeganquigley** [comment]
Thanks for explaining @Bharathcoorg a couple more questions:

- Is the wallet still fully open-source?
- What parachains would you aim to support right out of the gate?
- Also, looking at your wallet now on iOS I see it already has support for Polkadot & Kusama. So just to make sure I understand correctly, this grant is for the extra features which haven't been implemented yet?

**Comment by Bharathcoorg** [comment]
> * Is the wallet still fully open-source?
> * What parachains would you aim to support right out of the gate?
> * Also, looking at your wallet now on iOS I see it already has support for Polkadot & Kusama. So just to make sure I understand correctly, this grant is for the extra features which haven't been implemented yet?

I can make it open-source with a new repo, but without cloud wallet features (I want to add this in the next 4-5 months). Currently, our repository is not properly maintained; we started it using Subwallet's code, and we use most of their packages for the basic functions. For the dapps list, we are using[ Nova Wallet's list.](https://github.com/novasamatech/nova-utils) 

We are using [Subwallet's chain list](https://github.com/Koniverse/SubWallet-ChainList) and our own list; it supports all parachains, and new parachains can be added easily. You can check the settings for supported networks in iOS. The Android version has more networks right now. 

Yes, this grant is only for implementing new features and starting dfinnwallet as a new project.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the application and all the effort that you put into this. However, the committee decided that we won't support additional wallets at this stage. There are already a lot of open-source alternatives and if you want to create a new solution you should try to find other funding sources (e.g. VCs) and create a long business model around it.

**Comment by Noc2** [comment]
(see above)

**Pull request closed without merging**
