### PR TITLE
Create: Kusama <> Polkadot Bridge 

### PR DESCRIPTION
**Pull request by Martin-Kiss**
#### Project Abstract

We are actively developing trustless bridging solutions for cross-ecosystem unification and working towards successfully bringing IBC to the Polkadot ecosystem.
Once this milestone has been realized, we will successfully establish the first trustless bridge between Kusama and Polkadot utilizing the IBC protocol.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`kusama<>polkadot-bridge.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by Martin-Kiss** [comment]
@JafarAz @Wehbix

**Comment by takahser** [comment]
@Martin-Kiss thanks for the submission of your grant application! We currently have a rather large backlog to tackle, so it might take a bit longer than usual until we can give you feedback. Nevertheless, we're going to take a look at it as soon as we can.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the application. But I would actually have the same concern about this, as I had about your previous application: https://github.com/w3f/Grants-Program/pull/1011#pullrequestreview-1078529503 
Specifically: `“Also our guidelines say the following: “We do not award grants for projects that have been the object of a successful token sale”. Looking at your website and your vision, it seems to me that the main goal of your project is to bridge between different ecosystems. So isn’t this project already funded via your private sales?”` Could you comment on this? 

Apart from this, did you already take a look at: https://github.com/paritytech/parity-bridges-common As far as I know parity always had plans for a Kusama <> Polkadot bridge.

**Comment by JafarAz** [comment]
Hey @Noc2, thanks for the response! Regarding your first concern, I believe my colleague has answered you here https://github.com/w3f/Grants-Program/pull/1011#issuecomment-1220826020, but I am happy to provide any more clarifications. I am not exactly sure how our website depicts bridging as the main goal for our project, but I appreciate the feedback, and we will consider it as we revamp the design. Furthermore, previous grants have been provided for teams building bridges as their main project and also held private rounds. Is this a recent addition to the guidelines for W3F grants?

Regarding your second question, we know Parity has plans for a KSM <> DOT bridge, but we are not sure when that will be delivered. We can switch to using Parity's bridge when it goes live, depending on the efficiency of both bridges. If we were to switch to using Parity's bridge, this does not mean that this grant and the components in this grant would be redundant, and developments would go to waste. As mentioned in the grant application, the components used within the KSM <> DOT bridge, in specific: the initial development of the hyperspace relayer, ibc-rs, Pallet IBC, GRANDPA and BEEFY light client, will be shared and utilised for our Polkadot/Kusama <> Cosmos bridge and our Polkadot/Kusama <> NEAR bridge. Therefore, this grant partially covers the cost and development of those bridges too.

**Comment by JafarAz** [comment]
@takahser hey, could you please change the label on this PR as we are currently "ready for review" following our edits after @Noc2's request.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Sorry for the delay here. Regarding your first comment, I’m not sure to which team you are referring, but in general, the guideline is not fully objective. It’s up to the grants committee members to decide if they think this is covered by previous token sales or if it’s not. Therefore, I will mark the application as ready for review and ask others to provide feedback. 

To be fully transparent, I personally have still some concerns here. On the one hand, it seems like you [raised quite a lot of money](https://www.crunchbase.com/organization/composable-finance/company_financials), which raises generally some questions regarding this 30k grant for this project. On the other hand, I personally found it strange that you initially applied for something [previously funded by ICF](https://github.com/w3f/Grants-Program/pull/1011#pullrequestreview-1078529503). And finally, I think you can definitely argue that this work is funded via your initial sales given that you mention it even in your whitepaper: https://paper.composable.finance/

**Comment by JafarAz** [comment]
Hey @Noc2, thanks for the response and update! To clarify the concerns regarding our funding rounds, we have not fundraised through bridge tokens or even plan to launch a token for this bridge; we have fundraised through two Layer 1 native tokens with unique functionality – PICA, the native token of our Picasso parachain and LAYR, the native token of our Composable parachain. The specific use cases for these tokens are detailed in the 2 links below,  you’ll see that bridging is not part of these use cases. (https://docs.composable.finance/parachains/picasso/picasso-tokenomics.html) and (https://docs.composable.finance/parachains/composable/LAYR-tokenomics.html), 

With respect to your comment regarding the ICF grant: essentially, there is no overlap.  This grant is for the KSM <> DOT bridge. For this grant, we are applying for ibc-rs, Pallet IBC and the GRANDPA/BEEFY light clients; however, in regards to the funding by the ICF, that grant was to build the necessary infrastructure on Cosmos chains to support a bridge between Polkadot <> Cosmos. Specifically, it was to support the development of an ICS-8 WASM Client. Overall, the cost of putting this all together is beyond what this grant or any grant could cover; we’re happy to provide evidence to substantiate this privately if you require. Our team is devoted to building trustless bridges for the advancement of the entire ecosystem. 

Finally, it is undeniable that we have raised funding rounds; however, this grant is still valuable to us too. It would be great to receive recognition and support from the Web3 foundation with some of the development efforts going into this.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. I’m going to ping the rest of the committee again. I personally still think that the token sale is never only for the use case of the token, but for the implementation of the whitepaper. But as I said, this is a personal opinion and therefore I will ping everyone else again.

**Review by takahser — CHANGES_REQUESTED** [review]
Thanks for the update also from my side.
Personally I won't approve this application, mainly because

1. I think it overlaps with what you promised in your whitepaper which violates with our [Guidelines](https://github.com/w3f/Grants-Program#guidelines):

    > We do not award grants for projects that have been the object of a successful token sale.

2. You already applied for a grant that seems to have been [at least partially funded by another grant program](https://github.com/w3f/Grants-Program/pull/1011#pullrequestreview-1078529503) in a previous grant application.

**Comment by JafarAz** [comment]
Hey @Noc2, thanks for the response. 

We believe the support of the W3F is instrumental to our role in the Polkadot ecosystem.  Connecting the Dotsama ecosystems to other ecosystems is a cumbersome task that benefits the entire DeFi space. Our trustless bridges consist of various development efforts. We have received support from the Interchain Foundation for building infrastructure on Cosmos and most recently, the NEAR foundation for building the infrastructure on NEAR protocol. The reason why we applied for this grant from the W3F was to support the necessary infrastructure we are building on Polkadot that enables parachains to establish IBC connections.

Moving on, in this same spirit of seeking W3F support for our work, we would like to inquire about further grants we could apply for and ask which ones you will be interested in. Given the effort entailed in preparing and reviewing applications, it might be best to get some clarity ahead of applying. Would it be possible to set up a call and go through the various projects we plan to apply for? If that’s not possible, here’s a brief list of some of the projects we are exploring, please let us know if you’re interested in sponsoring any of them:

- [CosmWasm](https://cosmwasm.com/) VM implemented on Substrate, a widely adopted smart contract framework.
- Key Management Service (AWS) for PolkadotJS
- Key Management Service (GCP) Integration for PolkadotJS
- Cubic - Substrate vaults to support projects utilizing vault strategies such as AMMs, lending protocols and other money legos in DeFi.
- Financial NFT protocol (fNFTs) - As an alternative to the ve token model, we are designing a substrate standard for financial NFTs. 
- Apollo (Substrate oracle) - a permissionless, decentralized oracle.
- Pablo, our Substrate native cross-chain DEX
- Trustless bridges to Aptos, Polygon, BNB chain, Starknet, zkSync

**Comment by Noc2** [comment]
@JafarAz Thanks for reaching out. I would be happy to jump on a call and discuss these. Feel free to reach out to david@web3.foundation. But I think the integration of cosmwasm would be interesting for us and isn't mentioned anywhere in your whitepaper.

**Pull request closed without merging**
