### PR TITLE
Corego Proposal

### PR DESCRIPTION
**Pull request by Szegoo**
#### Project Abstract

Corego is a marketplace and a set of tools for Coretime manipulation and data tracking, with the goal of making development on Polkadot faster, easier, more flexible, and, as an end result, cheaper.

The project essentially consists of four parts that will create a cohesive application. For practical purposes, we have chosen to include only the initial two components in this grant proposal. However, the complete proposal can be viewed [here](https://github.com/CoregoLabs/Proposal).

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [X] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [X] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [X] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) or BTC address in the application).
- [X] The software delivered for this grant will be released under an open-source license specified in the application.
- [X] The initial PR contains only one commit (squash and force-push if needed).
- [X] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [X] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@snk2:matrix.org`, `@kingjulio:matrix.org`

### CODE REVIEW

**Comment by Szegoo** [comment]
I have read and hereby sign the Contributor License Agreement.

**Review by takahser — CHANGES_REQUESTED** [review]
See comments in the private element channel.

**Review by Noc2 — CHANGES_REQUESTED** [review]
(gave some feedback in the private group)

**Review by takahser — CHANGES_REQUESTED** [review]
@Szegoo I added another comment in the private channel.

**Comment by takahser** [comment]
Just for context, the new, related PR can be found [here](https://github.com/w3f/Grants-Program/pull/2080).

**Pull request closed without merging**
