### PR TITLE
Decentralized Private Computation

### PR DESCRIPTION
**Pull request by aric0x02**
#### Project Abstract

This Project based in [ZEXE](https://github.com/AleoHQ/zexe/tree/master) and [ZEXE paper](https://eprint.iacr.org/2018/962).
In order to  implement ideal_ledger,plain_dpc,delegable_dpc Pallet.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) or BTC address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [x] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@aric0x02:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by aric0x02** [comment]
recheck

**Comment by aric0x02** [comment]
I have read and hereby sign the Contributor License Agreement.

**Comment by aric0x02** [comment]
recheck

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. I would be interested in learning more about your long-term goals with this project as well as your background regarding zero-knowledge applications and cryptography. And in general, the details of the integration into Polkadot/Substrate. Finally, why did you decide to focus now on ZEXE now, while you previously focused on MoveVM, see https://github.com/w3f/Grants-Program/pull/1789

**Comment by aric0x02** [comment]
our goal:
phase 1'goal :We will implement DPC prototype  substate local devement node.It includes `ideal_ledger` ,`plain_dpc`,`delegable_dpc` pallets.
phase 2 (2024 Q2)'goal :We will implement DPC privacy-preserving application parachain/chain testnet.
It includes `private user-defined asset` ,`private DEXs`,`private stablecoins` pallets.
phase 3(2025 Q2)'goal :We will implement DPC general-purpose privacy-preserving smart contract application parachain/chain.
It include private smart contract application examples.

We are new learner regarding zero-knowledge applications and cryptography.

the integration into Polkadot/Substrate:
phase 1 prototype stage:
The merkle tree of transactions and commitments will store on the storage of substrate pallet`ideal_ledger`.
plain_dpc  transaction proof verify will implement in on-chain function `verify ` in substate pallet`plain_dpc pallet`.
delegable_dpc  transaction proof verify  will implement in on-chain function `verify `  in substate pallet `delegable_dpc pallet`.

phase 2 :
We will support polkadot address.
We will implement private user-defined asset substrate pallet.
We will implement private DEX substrate pallet.
We will implement private stablecoin substrate pallet.

phase 3 :
The another version of the offline proof computation `execute' part of `plain_dpc` and `delegable_dpc` will be using off-chain worker.


Due to the needs of the collaborative team, we are now focusing on ZEXE. We are also very interested in zero-knowledge. We will also continue to implement the Move language ecological tools including the Move virtual machine, which is also an area of great interest to us.

**Review by keeganquigley — CHANGES_REQUESTED** [review]
Thanks for the application @aric0x02 

- Please also note that we don't offer BTC payments. Please change to one of the accepted [payment methods](https://github.com/w3f/Grants-Program#pencil-process).
- ZEXE and DPC are certainly interesting technologies, but I agree that the application is sparse and could use more details regarding the context. Such as what/who these pallets are useful for, and use cases for the tech.
- From what I understand, Zexe allows private computation to be executed using zkSNARKs, to verify code executions on an external CPU. Does this imply that it would essentially be an alternative to TEE (trusted execution env)?

**Comment by aric0x02** [comment]
Thanks for your review.
ZEXE 's  verify code  like smart contract executed on  chain or node validator(any machine and any one ).
ZEXE is more like privacy BTC blockchain  that support rich privacy-preserving applications ,without compromising privacy (of data or functions)  or relying on unnecessary re-executions.It is very different from TEE.
We will update the application with more details and use cases  ASAP.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. I will mark the application as ready for review and share it with the rest of the team. However, I personally won't approve it. My two big concerns are that this project won't be maintained and used, given that roadmap, etc are very minimalistic in the application. My other concern is that you are just getting started regarding zero-knowledge applications and Zexe is certainly one of the more complex implementations that require a lot of knowledge.

**Pull request closed without merging**
