### PR TITLE
Sator x Polkadot Grant Proposal

### PR DESCRIPTION
**Pull request by islaperfito**
#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [ x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [ x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [ x] The software delivered for this grant will be released under an open-source license specified in the application.
- [ x] The initial PR contains only one commit (squash and force-push if needed).
- [x ] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ x] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Here is a reference to your previous grant application: https://github.com/w3f/Grants-Program/pull/449  However, we don’t have level 2.5 grants. Given the amount you are requesting this would be a level 3 grant. Could you update this? Also, could you remove the text from the template that isn’t bold? This way it’s easier to read. Regarding the deliveries, what kind of license do you actually want to use, and is the entire application currently open source? I’m also not sure what you mean by Parity signer integration. Do you want to use parity signer to sign transactions on your existing mobile wallet? So basically using two phones.

**Comment by Noc2** [comment]
I’m closing this application for now due to inactivity. Let me know if you want to continue to work on it and I can reopen it.

**Comment by islaperfito** [comment]
Can you please reopen this?

**Comment by islaperfito** [comment]
Have made updates to the grant in response to the previous comments. Changed grant to Level 2 status.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. It would still be helpful if you remove the text of the original template that isn’t bold, like for example: “This section should break the development roadmap down into milestones and deliverables. To assist you in defining it, we have created a document with examples for some grant categories here. Since these will be part of the agreement, it helps to describe the functionality we should expect in as much detail as possible, plus how we can verify and test that functionality. Whenever milestones are delivered, we refer to this document to ensure that everything has been delivered as expected.”. 

Regarding the deliveries, could you provide more technical details, like for example what kind of smart contract are you going to develop as part of “Smart contract”? Also some of the deliveries are not very specific and hard for us to evaluate. For example “explore working with Efinity ” could mean you simply take a look at their code and decided not to use. Apart from this, we usually try to be as objective as possible and not to support a specific parachain via our grants program.

**Comment by Noc2** [comment]
I’m closing this due to inactivity. Let me know if you want to re-open it.

**Comment by islaperfito** [comment]
Yes, I can change these items and make the milestones more specific for your team to better evaluate
please re-open this thank you

**Comment by Noc2** [comment]
I'm closing this again due to inactivity. Let me know if you actually want to work on it. We usually close PRs after two weeks without any comment.

**Comment by islaperfito** [comment]
yes, would like to push updates. Can provide updates inline until this is reopened, lmk

**Comment by Noc2** [comment]
Okay, I will reopen it again, but please update it during the next two weeks.

**Comment by islaperfito** [comment]
Thank you

**Comment by islaperfito** [comment]
pushed updates regarding smart contract specification and removed the original template text that isn't bolded

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the updates. Could you also sign the latest version of our Terms & Conditions? (see [CLAassistant](https://github.com/CLAassistant)). Apart from this, I have a couple of follow-up questions/comments:

- Regarding the “Smart contract for NFT Marketplace,” where do you actually plan to deploy this, and in which programming language? On your independent chain? Don’t you need to implement this in ink!? 
- Regarding the UI-related work, do you have mock-ups or designs that you can share already?
- Regarding the Polkawallet SDK-related deliverables, it looks like you simply want to follow [this tutorial](https://github.com/polkawallet-io/sdk#building-a-polkawallet_plugin-dart-package) for your own wallet. This doesn’t seem useful for others, and it also doesn’t sound like it takes three months to implement. Could you comment on this? 
- I think the end-to-end test shouldn’t be a separate milestone. Ideally, they are part of the previous milestone.

**Comment by islaperfito** [comment]
Regarding the “Smart contract for NFT Marketplace,” where do you actually plan to deploy this, and in which programming language? On your independent chain? Don’t you need to implement this in ink!?

The Marketplace currently operates with a Golang back end and React Native front end. Currently the marketplace supports Solana NFTs, and we want to add Polkadot. We do not have an independent chain. Are you recommending that we should explore parachain development? From what I can see, we would implement this in ink. 

Regarding the UI-related work, do you have mock-ups or designs that you can share already?

Sure, here is an example of mockups from the iOS/Android application. Here you can see where we would add Polkadot wallet compatibility to the existing application, as well as Polkadot NFTs to the marketplace, available from the iOS / Android application as well as directly from nft.sator.io. This would be mobile + desktop combined development 

Screen Shot 2023-01-05 at 5 54 14 PM
Screen Shot 2023-01-05 at 5 54 51 PM
Screen Shot 2023-01-05 at 5 55 10 PM
Screen Shot 2023-01-05 at 5 55 25 PM
Screen Shot 2023-01-05 at 5 55 35 PM

Regarding the Polkawallet SDK-related deliverables, it looks like you simply want to follow [this tutorial](https://github.com/polkawallet-io/sdk#building-a-polkawallet_plugin-dart-package) for your own wallet. This doesn’t seem useful for others, and it also doesn’t sound like it takes three months to implement. Could you comment on this?

It requires more time as we are live in the iOS Apple store and Android stores and have to comply by their guidelines. The Flutter application has a Go backend as well, and there are no official Go SDK or API docs for this specific integration. 

I think the end-to-end test shouldn’t be a separate milestone. Ideally, they are part of the previous milestone.
I've removed the end-to-end tests milestone and have updated the milestone deliverables accordingly. Will now go ahead and sign the T&C

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. However, you changed the level of the grant to level 2, but the application is still [above 30k](https://github.com/w3f/Grants-Program#baby_chick-level-2). Could you update this? Also, as part of the application, you say that you 

> "deploy custonm NFT marketplace smart contract"

, but when I asked you about this delivery you replied that you don't use any smart contracts: 

> "The Marketplace currently operates with a Golang back end and React Native front end."

So what exactly do you plan to deploy as part of this milestone?

**Comment by islaperfito** [comment]
The most likely scenario is to link the marketplace via Substrate. We'll design smart contract logic using the module library and RUST; test locally with the SDK. We'll then create a Substrate runtime and integrate with SNI; test with the SDK.

We do use Rust contracts and will use them in this milestone.

**Comment by Noc2** [comment]
I'm closing the application again due to inactivity.

**Comment by islaperfito** [comment]
I was simply referring to writing smart contracts in ink! for Substrate, the purpose of using Polkadot would be to multi-chain the NFT marketplace.
In regards to RUST, we are building smart contracts for the Sator marketplace using RUST to onboard Solana users.

**Comment by Noc2** [comment]
K, I will reopen the PR. Could you update this? In general, we need as many technical details as possible here since these are the requirements of our contracts. Otherwise, you could, for example, deliver any rust smart contract, and we would need to accept it.

**Comment by Noc2** [comment]
I'm closing the PR again due to inactivity.

**Comment by Noc2** [comment]
Closing due to inactivity

**Pull request closed without merging**
