### PR TITLE
Application: e-Passport ZK validation

### PR DESCRIPTION
**Pull request by dobschal**
### Project Abstract

The issue of verifying identities on-chain and providing proof-of-personhood is a challenging one.
The goal of the e-Passport Zero-Knowledge (ZK) Validator is to combine both technologies and enable zero-knowledge identity validation on-chain. E-Passport information can be retreived via a NFC reader app, uploaded to the blockchain thru a Web3 client and anonymised and validated by an on-chain validator. 

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying?

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] I have read and understood the [FAQs](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md), [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md) and [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).
- [ ] I prefer the discussion of this application to be in a private Element/Matrix channel. My username is: ``@_______``

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] Hackathon
- [ ] Personal Recommendation
- [ ] Substrate Builders Program
- [ ] Investor/VC
- [x] Online Search
- [x] Other: DECODED Conference

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the application. I just pinged @burdges and @FlorianFranzen who created the RFP: https://github.com/w3f/Grants-Program/blob/master/rfps/open/epassport-zk-validation.md

**Comment by burdges** [comment]
Yo, there is an academic team who implemented this, but their code is not yet out, so we should see what they've done.  I've emailed them to ask

**Comment by Solha99** [comment]
Hi @burdges and @Noc2, could you provide us with an update regarding this grant pls? 
Thank you 
Olga

**Comment by burdges** [comment]
We do not know what work needs to be done to do this on polkadot, because we do not yet see the source code from the academic team who did the crypto part already, and they have not yet written me back.

**Comment by Noc2** [comment]
@Solha99 Sorry for the late reply here. Maybe we should jump on a call to discuss this grant. Could you reach out to me via email: david@web3.foundation?

**Comment by Noc2** [comment]
I’m closing this application for now. On the one hand, we are still waiting for the other team to release the code. On the other hand, it seems the committee is not willing to support this project with this kind of money. I will open the application again, in case I hear anything else. Feel free to ping me in case you have any questions.

**Comment by burdges** [comment]
I've an answer saying they were cleaning up the code for release, so more waiting for us.  I've confidence in the guy who did this for his PhD, so a release should happen, and then we can focus on supporting and integrating that effort.

There is likely to be a bunch of different work here, even once the SNARK itself and basic tooling lands, so if likely some space for ecosystem teams doing android apps for it or whatever.

**Pull request closed without merging**
