### PR TITLE
Ink Playground IDE Improvements

### PR DESCRIPTION
**Pull request by radhe-zeeve**
**Project Abstract**

Zeeve will improve Ink! Playground capabilities to keep the Playground environment to be up to date with the Ink advancements and also improve the Ink Crate docs.

We understand the on-paper maximum for a Level 2 grant is for $25,000, but the scope of this project requires 3 FTE-months and we were told earlier in the process that we can make a case to go beyond that limit.

Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] Level 1: Up to $10,000, 2 approvals
- [X] Level 2: Up to $30,000, 3 approvals
- [ ] Level 3: Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

Application Checklist

- [X] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (ink-playground-ide-improvements.md).
- [X] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [X] A BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (aUSD/USDT) address for the payment of the milestones is provided in the application.
- [X] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [X] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [X] I prefer the discussion of this application to take place in a private Element/Matrix channel. Our team username's are: @ghanzeeve:matrix.org & @radhezeeve::matrix.org

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
One minor thing: Could @arjunzeeve still sign the terms and conditions?

**Comment by gnv-zeeve** [comment]
> One minor thing: Could @arjunzeeve still sign the terms and conditions?

Seems like this isn't working, details shared on private chat.

**Comment by gnv-zeeve** [comment]
> One minor thing: Could @arjunzeeve still sign the terms and conditions?

It seems to have stuck, we did try it multiple times as well as using different browsers. Shared screenshots on private chat. Please suggest a way out.

**Comment by Noc2** [comment]
I looked into it, and I believe it's okay. We had this issue before, and it happened because of a spelling issue that does seem to cause problems with the bot.`arjun-zeeve` has successfully signed the terms. See below:

Screenshot 2023-05-17 at 07 58 30

**Review by Noc2 — CHANGES_REQUESTED** [review]
(one additional minor comment in the private chat, but I'm generally happy to go ahead with it)

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I'm happy to go ahead with it.

**Review by BenWhiteJam — APPROVED** [review]

**Review by keeganquigley — APPROVED** [review]

**Comment by radhe-zeeve** [comment]
@JoshOrndorff we are aware ink-playgroud.substrate.io is down. As mentioned in the issue Polkadot team is trying to migrate to pure k8 based deployment, as for the current development we are using docker, if anything changes in deployment process we would pivot and make adjustments to our development to accommodate the new deployment process.

**Comment by keeganquigley** [comment]
Hi @radhe-zeeve just left a comment in the private channel, FYI.

**Comment by keeganquigley** [comment]
Hi @radhe-zeeve how is the milestone coming along?

**Comment by radhe-zeeve** [comment]
@keeganquigley We have already created PR for one of the issue and marked it ready for review recently [Add new Ink Version update support by radhe-zeeve · Pull Request #815 · paritytech/ink-playground](https://github.com/paritytech/ink-playground/pull/815), resolution for other two issue required for the first milestone is being worked on and will be presented in few days.

**Comment by keeganquigley** [comment]
Thanks @radhe-zeeve feel free to provide an update in the private Element chat.

**Comment by radhe-zeeve** [comment]
I will be delivering an final updated code within the next couple of days.

**Comment by keeganquigley** [comment]
Hi @radhe-zeeve still planning on delivering this?

**Comment by radhe-zeeve** [comment]
@keeganquigley  already opened the PR last week and pinged `cmichi` on the PR, no response yet

PR's: https://github.com/paritytech/ink-playground/pull/817, https://github.com/paritytech/ink-playground/pull/815

**Comment by keeganquigley** [comment]
Thanks for the update @radhe-zeeve yes unfortunately it will probably be a while since they are swamped. In the meantime, in order to get paid for this milestone we would need you to submit a delivery PR in the repo: https://github.com/w3f/Grant-Milestone-Delivery

Its okay if the PRs are still open, but that way you can document what work was done. Are you able to complete this? Thanks!

**Comment by radhe-zeeve** [comment]
@keeganquigley  Sure, will open a PR with documentation on https://github.com/w3f/Grant-Milestone-Delivery.

**Comment by semuelle** [comment]
pinging @radhe-zeeve

**Comment by gnv-zeeve** [comment]
Hey @semuelle let us know in case you still have some open items on this and we can quickly close them.

cc: @radhe-zeeve

**Comment by semuelle** [comment]
Thanks, @gnv-zeeve. We have a bit of a backlog at the moment, so it will probably take a few more days. I'll share feedback on the pull requests.

**Pull request merged**
