### PR TITLE
Web3 Association - Open source contributor funding experiment setup

### PR DESCRIPTION
**Pull request by lovegrovegeorge**
#### Project Abstract

This is a research proposal to experiment with an open source contributor funding process. Developers in the ecosystem would be funded to help with developing the most impactful open source initiatives in the ecosystem. Contributors could work on new initiatives or improvements to existing open source solutions.

This funding process will trial a number of approaches from our funding analysis (https://funding.treasuries.co). This funding process and the approaches being trialled could become long term funding solutions for Polkadot if this experiment proves to be successful.

This proposal is for the setup of this experiment. A future proposal will be submitted that requests approval for the actual funding process once the experiment has been setup.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (Polkadot AssetHub (DOT, USDC & USDT) address in the application and bank details via email, if applicable).
- [x] I understand that an agreed upon percentage of each milestone will be paid in vested DOT, to the Polkadot address listed in the application.
- [x] I am aware that, in order to receive a grant, I (and the entity I represent) have to successfully complete a KYC/KYB check.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@lovegrovegeorge:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by keeganquigley** [comment]
Hi @lovegrovegeorge thanks for your comments. Happy to give my opinions below:

> Unknown funding amount until after voting stage is completed - The actual funding amount required cannot be stated until further into the setup of the experiment. Therefore this proposal could either stay in a draft state until that can be determined or it could be approved and merged and then updated in the future. The value used in the proposal so far is the maximum amount we could suggest for the experiment, however the actual value could be much lower depending on the final agreed experiment parameters.

The committee most likely won't vote to approve a grant with an unknown funding amount, especially for this amount. I would recommend reducing the scope/cost to include only what you need to get started, and then you can always apply for subsequent follow-up grants. For example, the committee might be more inclined to approve just the first milestone of $3k to help you bootstrap the experiment setup. Then you might be able to better determine how much more you need.

Additionally, any ask greater than $100k needs to be put up for discussion by the W3F council, in addition to the 5 approvals required to sign the grant. This could take a while, and might prove hard to get. Any changes down the line would need an amendment with the same amount of approvals. Whereas if you lowered it to a level 1 grant to get started, only 2 approvals would be needed to hit the ground running.

> Vested DOT concern - The experiment would pay developers monthly once their contribution logs are approved. The main concern i'd have is around how long the vested delay of funding is as this could make it difficult for the participating developers that would have rent and bills to pay.

The DOT is vested linearly, on-chain over a two year period. Therefore a bit will unlock with each block, but yes the majority of it would be locked to start with. 

> Full-Time Equivalent on milestones query - The experiment would select developers to work full time for a set duration of time such as 4 or 6 months. I’m unsure whether the milestones FTE value should include these participating contributors in the number or if this value should only focus on the efforts required to operate the funding process experiment itself.

Yes I would recommend including these contributors in the FTE value, since they would be working full-time. Especially if their payment would be part of the total costs.

I hope these answers help.

**Review by Noc2 — APPROVED** [review]
Sorry for the delay here. I'm happy to go ahead with it and share it with the rest of the team.

**Review by keeganquigley — CHANGES_REQUESTED** [review]
Thanks for the changes @lovegrovegeorge much appreciated. To answer your question, I can only speak for myself, as I'm not sure what the interest level would be like for other W3F & Parity colleagues, but personally I'd have no problem participating in a survey or something similar. But I'm assuming you'd want to get input from technical fellowship members and community voters as well, since members of both W3F & Parity will have varying levels of participation in OpenGov.

I'm happy to approve it and see how it goes, but one minor comment about the milestone tables. The formatting is a bit funky here, for numbers 1 - 4, could you move these descriptions to the Specification column instead? Then you can give them a quick title on the left side. That way it will adhere better to our [template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) and be uniform with other applications. Thanks!

**Review by keeganquigley — CHANGES_REQUESTED** [review]
Thanks @lovegrovegeorge I have one more comment:

Could you please define what "collaboration with Web3 Foundation" would mean in this case? Does this essentially mean you would send us surveys to fill out? As we don't typically provide any kind of technical support or partnership collaboration for the grants program.

In other words what would "finalizing the expirement parameters" consist of?

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/bounty-proposal-open-source-developer-grants-program/9445/4

**Review by keeganquigley — APPROVED** [review]
Hi @lovegrovegeorge great, thanks for the changes and happy to see the forum post too. I'm willing to go ahead and approve it as well. 

Before merging, we ask all grantees to complete [KYC/KYB](https://in.sumsub.com/idensic/l/#/uni_iW29BlDPIhrrmtck). Please submit for verification there before we can fully accept the grant. Thanks!

**Review by Noc2 — APPROVED** [review]

**Comment by keeganquigley** [comment]
Thanks @lovegrovegeorge for the update. Understandable; have you set up a priority suggestions board and invited the community to post their suggestions per the deliverable? If not, have you tried doing any other temp checks with the community, such as on the Polkadot forums? 

That might help to get the community motivated. But let us know should you wish to not continue working on it and we can potentially close it for now until you want to pick it back up.

**Comment by keeganquigley** [comment]
Hi @lovegrovegeorge since it has now been several months are you able to provide an update?

**Comment by keeganquigley** [comment]
Thanks for the update @lovegrovegeorge sounds good, lets go ahead and close it for now, and we can always potentially pick it back up in the future if you want to work on it again, by simply commenting on the PR. Cheers and best of luck with the rest of your work!

**Pull request merged**
