### PR TITLE
Xcavate Blockchain & realXchange dApp

### PR DESCRIPTION
**Pull request by meanking**
#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for your interest in our grants program. Is there a reason why you opened the same application twice, see https://github.com/w3f/Grants-Program/pull/2109?

**Comment by meanking** [comment]
Hi @Noc2 , thank you for your kind reply.
We will fix it as soon as possible. The former would be closed.

Best regards,
Alan

**Comment by meanking** [comment]
I have read and hereby sign the Contributor License Agreement.

**Comment by meanking** [comment]
Hi, David(@Noc2 )

Hope you are well. Could you give me any update for this PR?

Best,

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update and sorry for the late reply here. Could you provide more information about the Community Projects Pallet? For example, where can I find the code, and why do you want to create nft minting into this pallet, rather than reusing another NFT pallet? Also, I saw that there were a lot of [issues with your previous delivery](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/xcavate_1_dsm-w3f.md). Could you comment on this and how do you plan to change this? In the meantime, I will share the application with the rest of the team to speed up the evaluation process.

**Review by takahser — CHANGES_REQUESTED** [review]
@meanking I think [my points made](https://github.com/w3f/Grants-Program/pull/2054#pullrequestreview-1696796042) in the previous PR still mostly hold true for the new proposal on why I have concerns here. Could you comment on that?

**Comment by xcavate2022** [comment]
Hi, Many thanks for your comments. I think this draft whitepaper https://xcavate.io/whitepaper might help to understand why we want to keep the Community Project Pallet separate. The issues surrounding the previous PR were driven by a lack of skills... we have plugged that knowledge gap with new team members. I hope this clarifies our position and answers your questions. Best Regards, Richard

**Comment by xcavate2022** [comment]
We have entered our project in the Polkadot Winter Hackathon so pallet code can be found here... https://github.com/XcavateBlockchain/Xcavate_Node/tree/f4b0eec4305b963d119dba411199786e477d2ae1

**Comment by xcavate2022** [comment]
If your concerns are purely around appropriateness of a W3F grant… are you suggesting we would be better suited to applying for this new fund? https://futures.web3.foundation/ <https://futures.web3.foundation/>

**Comment by takahser** [comment]
@xcavate2022 

>  I thought the W3F grants were there to support projects, which either support the Dotsama ecosystem, or the wider global community (which I believe our pallet and dApp does)… Is that not correct?

Your assumption is correct. However, as you know we can not support every project, hence we decide based on different aspects, such as value the project brings to the community, viability, cost, reusability, previous work, technical aspects and other factors. As I already mentioned [previously](https://github.com/w3f/Grants-Program/pull/2054#pullrequestreview-1696796042), I personally have concerns regarding resusability, viability (i.e. mechanism of securing the ownership of the real-world asset through an NFT), performance in the previous delivery, and I'm not convinced that blockchain is the best solution for this project. You haven't given me reasons to convince me otherwise, hence I've came to the conclusion to not add my approval to the project.

**Pull request closed without merging**
