### PR TITLE
Tux0 application

### PR DESCRIPTION
**Pull request by muraca**
#### Project Abstract

Tux0 will be a [Tuxedo](https://github.com/Off-Narrative-Labs/Tuxedo) piece that leverages zero-knowledge proofs to manage a private token.  
To develop it, we will first conduct research to identify a zero-knowledge protocol that is suitable for use in Substrate runtimes.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) or BTC address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel.

cc @Gorzorg @JoshOrndorff

### CODE REVIEW

**Comment by muraca** [comment]
I have read and hereby sign the Contributor License Agreement.

**Comment by muraca** [comment]
recheck

**Review by keeganquigley — CHANGES_REQUESTED** [review]
Thanks for the application @muraca just a couple of initial comments:

- You mentioned that you are confident that phase 1 will succeed. I take this to mean that you would want to go forward with M2 regardless of the results of the M1 research?
- Can you integrate more technical details into the application such as the tech stack? Especially the milestone deliverables themselves. For example what will you use to build the data visualization tool? What will the benchmarking program be written in?

**Comment by muraca** [comment]
> - You mentioned that you are confident that phase 1 will succeed. I take this to mean that you would want to go forward with M2 regardless of the results of the M1 research?

From the proposal document:
> We are aware that the results might not be as good as expected. If we fail to identify a protocol that can be used in a Substrate runtime, then we would still proceed with developing the final product, using custom host functions.  
However, since some of these protocols are already used in other blockchains, we're confident this phase will be a success.

We think we must be conservative, but truth is we don't think this research will fail to identify a usable protocol.
However, to answer your question: yes, we would eventually determine what's the best protocol to use natively, integrate it in Substrate with host functions, and use that to develop Tux0, with the hope that in the future said host functions would be replaced by either the ones that the Polkadot Relay Chain will offer, or by another protocol that can work in the runtime.

---

> - Can you integrate more technical details into the application such as the tech stack? Especially the milestone deliverables themselves. For example what will you use to build the data visualization tool? What will the benchmarking program be written in?


We've been deliberately vague with the first milestone, as we didn't want to set in stone things that are subject to change:
- For the data visualization tool, we want something web-ready, to easily embed the results in our article hosted on GitHub pages.
We used [ZingChart](https://www.zingchart.com/) in previous works, but we don't want to use it in this project since it's not open source. We saw that [C3.js](https://c3js.org/) might be a good fit, but we we postponed the research and decision.
- For the benchmarking tool, we're oriented towards Rust as it might be easier to integrate with the proving systems. 


Regarding the second milestone, we have taken it for granted that the Tuxedo piece and the wallet extension will be written in Rust.

I agree that we might have been more clear on those things, but I was unsure on how to proceed. If you think we should clarify and write down these possibilities, I'll be happy to do so.

**Comment by JoshOrndorff** [comment]
Hey there :wave:

I want to share a few things that may be relevant to the review of this grant.

First, @muraca has been contributing to Tuxedo as an open source volunteer pretty often the past several weeks. He started with small chores ([Tuxedo#91](https://github.com/Off-Narrative-Labs/Tuxedo/pull/91)), then moved on to overhauling ci ([Tuxedo#93](https://github.com/Off-Narrative-Labs/Tuxedo/pull/93), [Tuxedo#112](https://github.com/Off-Narrative-Labs/Tuxedo/pull/112), [Tuxedo#113](https://github.com/Off-Narrative-Labs/Tuxedo/pull/113)), and eventually started making significant design contributions ([Tuxedo#127](https://github.com/Off-Narrative-Labs/Tuxedo/pull/127)). He understands the design of Tuxedo and the UTXO system.

And second, I'm willing to mentor/advise a few hours a week on this grant. I could help with Rust, Tuxedo, and Substrate, but not with ZK aspects. I would not be an official part of the grant, as I'm currently busy working on [another grant](https://github.com/w3f/Grants-Program/blob/master/applications/tuxedo_parachain.md).

**Comment by Gorzorg** [comment]
Hi, I am the other guy who should be a developer in this project. I am by no means an expert in cryptography, but i could be the math guy of reference if you want to make quantitative questions.

**Comment by keeganquigley** [comment]
Thanks @muraca for your explanations, they are much appreciated. Thanks also @JoshOrndorff for the introduction, and nice to see you again. I apologize for the delay, we have a bit of a backlog atm with the recent changes. 

- For the research phase, are you planning to research only the three zk protocols listed? I was just reading about [Nova folding](https://medium.com/veridise/introduction-to-nova-and-zk-folding-schemes-4ef717574484), which is a new high-speed recursive SNARK that also doesn't require a trusted setup. 
- To make sure I understand correctly, will the research results be beneficial for using zk proofs in all substrate runtimes, and not just UTXO-based runtimes?

**Comment by muraca** [comment]
@keeganquigley no worries, thank you for your attention and take your time.

> For the research phase, are you planning to research only the three zk protocols listed?

No, it's very likely that the list will be extended, but I think at one point we will have to choose which ones to compare and why. We can't test all the protocols we can find with a Google search.

> I was just reading about [Nova folding](https://medium.com/veridise/introduction-to-nova-and-zk-folding-schemes-4ef717574484), which is a new high-speed recursive SNARK that also doesn't require a trusted setup.

Thanks for mentioning this, it might be very interesting for Tux0, we'll look into it.

> To make sure I understand correctly, will the research results be beneficial for using zk proofs in all substrate runtimes, and not just UTXO-based runtimes?

The protocol we hope to identify is ideally good enough to be used in a Substrate Runtime in WASM without using host functions, so it must have small proofs and short execution time.  
It doesn't have much to do with Tuxedo or UTXOs, and it will be usable on FRAME runtimes as well.

**Review by keeganquigley — APPROVED** [review]
Thanks for your answers @muraca it looks good to me and I'm happy to approve it. I will mark it as ready for review and ping the rest of the committee to take a look.

**Review by takahser — CHANGES_REQUESTED** [review]
@muraca thanks, that sounds interesting. I have a few questions:

1. could you provide more details on the ZK protocols being considered in M1? In particular, which protocols are you going to compare and what will be the evaluation criteria? Please integrate this directly into the deliverables, as they act as a contraction that the evaluator will review your future delivery against.
2. do you have any code samples that you can provide? Or could you direct us to the nft chain materials that were presented at sub0 2022 that you mentioned in the proposal?
3. could you clarify the limitations of the prototype implementation in terms of production-readiness? What will be required to make it production-ready after this grant and what are the long-term plans for the project (if any)?

**Comment by muraca** [comment]
@keeganquigley we appreciate your support and thank you for your approval. 

@takahser nice to talk again. 

### About NFT Chain

> 2. could you direct us to the nft chain materials that were presented at sub0 2022 that you mentioned in the proposal?

https://github.com/w3f/Grants-Program/blob/0512ee1372ba30935991c8dfdd5e9b2e210ecdbe/applications/tux0.md?plain=1#L99 We are legally obliged to not share anything.

https://github.com/w3f/Grants-Program/blob/0512ee1372ba30935991c8dfdd5e9b2e210ecdbe/applications/tux0.md?plain=1#L100 In that regard, the most I can do is reminding you that you were one of the approvers of NFT Chain's application to Substrate Builder Program. In that occasion, I personally had a call with you and another developer of the company.  

### The Tux0 questions

We think some of the answers are already extensively answered in the document, I'll embed the content in this comment.
Your questions were all helpful nonetheless, because they made us reason on some things we overlooked, and we think we should clarify or extend.
Nonetheless, if among the things we don't explicitly state we will write more about there's anything you think should be written more extensively in the application doc, please point it out, as some things might be obvious for us and not for you, or vice versa. 

> 1. could you provide more details on the ZK protocols being considered in M1? In particular, which protocols are you going to compare

https://github.com/w3f/Grants-Program/blob/0512ee1372ba30935991c8dfdd5e9b2e210ecdbe/applications/tux0.md?plain=1#L30-L33 We didn't want to set in stone the protocols, as we could find other more suitable ones during the research phase, or even drop some for valid reasons. We'll try to do as much as we can.  

We want to write the program in a way that it can be extended in the future with other protocols. We will write a few words on how we plan to do this, integrating some Rust code sketches.

> what will be the evaluation criteria? 

They are defined in the Project Details section: https://github.com/w3f/Grants-Program/blob/0512ee1372ba30935991c8dfdd5e9b2e210ecdbe/applications/tux0.md?plain=1#L35-L39

I think we should specify that we intend to compare those results with execution time and size of extrinsics in Substrate runtimes as well.

> 3. could you clarify the limitations of the prototype implementation in terms of production-readiness? What will be required to make it production-ready after this grant 

1. Tuxedo should be considered production-ready; this is in Joshy's hands.
2. The zero knowledge protocol we use and its library should be subject to security audits. This is part of the evaluation criteria: https://github.com/w3f/Grants-Program/blob/0512ee1372ba30935991c8dfdd5e9b2e210ecdbe/applications/tux0.md?plain=1#L38
3. The Tux0 protocol should be reviewed by experts, I think cryptographers, and the Tux0 code should be subject to security audits. This can be done in the future by any entity who's interested in using Tux0 for their blockchain. https://github.com/w3f/Grants-Program/blob/0512ee1372ba30935991c8dfdd5e9b2e210ecdbe/applications/tux0.md?plain=1#L60

> what are the long-term plans for the project (if any)?

https://github.com/w3f/Grants-Program/blob/0512ee1372ba30935991c8dfdd5e9b2e210ecdbe/applications/tux0.md?plain=1#L169-L170

@CrackTheCode016 recently suggested a Tux0 parathread on Rococo, which would be a huge step forward for Tuxedo as well.

**Review by takahser — CHANGES_REQUESTED** [review]
@muraca thanks for the detailed replies and thanks for refreshing my memory :)

> We didn't want to set in stone the protocols, as we could find other more suitable ones during the research phase, or even drop some for valid reasons. We'll try to do as much as we can.

I understand that you want to have some flexibility, but I'd still prefer to have them in the deliverables. If you want to drop or change one (or more) of the protocols, an amendment would be possible and in this case I wouldn't expect any problems with approving it, as long as you can justify the change. Another option would be to commit to a number of protocols in the deliverables without explicitly setting for the candidates yet, something along the line of "we're going to evaluate 3 or more protocols, such as x, y and z, but the choice of protocols will be made at a later stage".

Regarding the other 2 points, thanks for clarifying, sounds good to me.

**Review by keeganquigley — APPROVED** [review]

**Review by takahser — APPROVED** [review]
@muraca thanks for the adjustments, happy to approve as well.

**Comment by muraca** [comment]
@takahser thank you again for your time and for supporting the project. 
We look forward to receiving other reviews from the committee.

**Review by Noc2 — APPROVED** [review]

**Comment by muraca** [comment]
Thanks for giving us the opportunity to work on this project.
We are kickstarting the development of the first milestone, and we hope to be able to deliver it before Christmas.

**Comment by muraca** [comment]
Dear committee, I'm writing this comment to update you on the current situation of the project.  

We started going through OpenZL, which could have been a great candidate to write circuits using a high-level language. However, looks like Manta Network got 400k USD from the Polkadot Treasury to build a tool that was left unfinished.  

We spent some time on Nova, a SNARK library developed by Microsoft, failing to find any tutorials or appropriate documentation. Because of that, we tried building some understanding of how it works by code digging. We have some trouble understanding the implications of how many of the objects used or defined in that library, which in turn makes it difficult for us to form opinions on its usability.

We also tried contacting the developers by [opening a discussion](https://github.com/microsoft/Nova/discussions/260) that didn't receive any answers. We don't exclude coming back to Nova later on.

We have currently spent 2 weeks on Halo2. Even if we didn't consider the first week we basically wasted, it's clear to us that 6 weeks are not enough to produce what we intended to do in the first milestone. 3 weeks per protocol are the bare minimum, but I'm afraid it could take longer.

We'd like to know if you would be willing to consider an amendment, with a more proper time and cost estimation. We are also thinking of splitting the first milestone in two parts, as receiving some funding earlier would be beneficial for us. 
In the meantime, we're still working hard on Halo2, and we hope to be able to finish a few working test circuits by the end of this week.

Thanks for your attention.

cc @keeganquigley @Noc2 @takahser @semuelle

**Comment by keeganquigley** [comment]
Thanks for the update @muraca yes feel free to amend the original application to update the changes and submit an amendment PR. If the updated costs aren't significantly higher, it should get approved and merged fairly quickly.

On the other hand if the cost changes would be significant, I would recommend reducing the scope in this grant (such as removing the last milestone) rather than increasing the price, and then you can always apply for a follow-up grant if it still makes sense to fund the remaining work.

I hope this helps!

**Comment by muraca** [comment]
@keeganquigley thanks for the info.
I opened an Amendment PR #2137

**Comment by keeganquigley** [comment]
Hi @muraca just checking in on progress for milestone 1. Can you provide an update?

**Comment by Gorzorg** [comment]
So, I needed to do some soul searching. I could expand on the causes, but i feel i could only continue working on the grant slowly, without being able to fix deadlines. The short version is, i had a minor burnout, and i am also starting a new job soon.

Realistically i could close milestone 1, but i would not be able to guarantee a timeline for the subsequent ones.

**Comment by semuelle** [comment]
Hi @muraca & @Gorzorg, thanks for the insights. There is currently no urgency with delivering this grant, so we have no desire to force the matter. However, at times grants become obsolete, which is why we keep tabs on all of them. My suggestion would be to set a target date of the first milestone for six months from now. We can still decide to cancel the grant then. What do you think?

**Comment by Gorzorg** [comment]
I will try putting effort into it

**Comment by keeganquigley** [comment]
thanks @Gorzorg does that mean your answer to @semuelle question about the timeline is yes?

**Comment by Gorzorg** [comment]
After assessing my new work situation, i have to abandon the project. I apologize.

**Comment by keeganquigley** [comment]
Thanks @Gorzorg we appreciate the update. Understood, we will go ahead and close it for now.

**Pull request merged**
