### PR TITLE
Security of EIP-6963 proposal

### PR DESCRIPTION
**Pull request by ThierrySans**
#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [ ] Payment details have been provided (Polkadot AssetHub (DOT, USDC & USDT) address in the application and bank details via email, if applicable).
- [x] I am aware that, in order to receive a grant, I (and the entity I represent) have to successfully complete a KYC/KYB check.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [x] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@thierrysans:matrix.org`

### CODE REVIEW

**Review by semuelle — CHANGES_REQUESTED** [review]
Thanks for the application. Could you elaborate on what you have found or are expecting to find that hasn't already been listed in the EIP? Also, have you tried applying with more EVM-focused grants programs with this? This is only a topic for Polkadot as we have wallets that support both EVM and Polkadot.

@ThierrySans & @lakhwani, could you sign the CLA, please?

**Comment by lakhwani** [comment]
I have read and hereby sign the Contributor License Agreement.

**Comment by ThierrySans** [comment]
I have read and hereby sign the Contributor License Agreement.

**Comment by takahser** [comment]
Closed, see comment in the corresponding, private Element channel.

**Pull request closed without merging**
