### PR TITLE
RFP: implementation-benchmarking Milestone 3

### PR DESCRIPTION
**Pull request by Nikhil-Desai-Talentica**
#### Project Abstract

A continuation to [pallet-benchmarking](https://github.com/w3f/Grants-Program/blob/master/docs/RFPs/Under%20Development/implementation-benchmarking.md)
There are multiple ways to implement the logic in substrate i.e. using pallets or ink smart contracts, or even writing solidity code and compiling it to WASM with the help of a Solang compiler. We have to benchmark the performance metrics of the logic implemented using each of the above methods. This will help new developers to decide the best tool to implement the logic.
[Milestones 1 and 2 delivered](https://github.com/w3f/Grants-Program/pull/1457)

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by keeganquigley — CHANGES_REQUESTED** [review]
Thanks for the follow-up application @Nikhil-Desai-Talentica in general I'm happy to support it, but have a couple questions:

- After this grant, how do you plan to maintain the project? Will you go for other sources of funding?
- Your application doesn't contain any new info other than the new deliverables. Could you perhaps add a paragraph or so to the overview that describes what you will accomplish with this milestone?
- Will it only focus on cross-contract calls/benchmarking? What about emitting events?

**Comment by Nikhil-Desai-Talentica** [comment]
Hi @keeganquigley,
1. I will discuss this with my team and reply.
2. I will add a few lines on what we are trying to accomplish in this milestone and how it might benefit developers.
3. I can include the events part in the list of deliverables.

**Review by keeganquigley — APPROVED** [review]
Thanks for making the changes @Nikhil-Desai-Talentica I'm happy to go forward with it. I will mark the application as ready for review and share internally with the rest of the committee.

**Review by Noc2 — APPROVED** [review]
I'm happy to go ahead with it.

**Pull request merged**
