### PR TITLE
Subsembly - Support for GRANDPA

### PR DESCRIPTION
**Pull request by Daniel-K-Ivanov**
### Project Abstract

This grant is a continuation of the original [Subsembly - Framework for building AssemblyScript Runtimes](https://github.com/w3f/General-Grants-Program/blob/master/grants/rfp-responses/subsembly-assemblyscript_runtime_framework.md). Developers can already checkout/install the [Subsembly CLI](https://github.com/LimeChain/subsembly) and implement Substrate Runtimes using the framework.

Other Grants:
- https://github.com/w3f/Grants-Program/blob/master/applications/assemblyscript-scale-codec.md
- https://github.com/w3f/General-Grants-Program/blob/master/grants/rfp-responses/assemblyscript-runtime.md

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [X] The total funding amount of the project is below USD $30k for first-time grant applications and $100k for follow-up ones.
- [X] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [X] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [X] The software delivered for this grant will be released under an open-source license specified in the application.
- [X] The initial PR contains only one commit (squash and force-push if needed).
- [X] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
@Daniel-K-Ivanov  Thanks for the application. Could you update the milestone deliverables? See https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md Specificly “Deliverables 0a-0d are mandatory for all milestones, and deliverable 0e at least for the last one. If you do not intend to deliver one of these, please state a reason in its specification (e.g. Milestone X is research oriented and as such there is no code to test).”

**Review by Noc2 — APPROVED** [review]
Looks good to me. I will share it with the rest of the team.

**Review by alxs — APPROVED** [review]

**Review by BenWhiteJam — APPROVED** [review]
Great to read that you continue! Ty!

**Comment by semuelle** [comment]
Hey @Daniel-K-Ivanov, I just noticed that the grant application suggested delivery of the first milestone in September. Could you give a brief update? Are there technical issues preventing you from completing it?

**Comment by Daniel-K-Ivanov** [comment]
> Hey @Daniel-K-Ivanov, I just noticed that the grant application suggested delivery of the first milestone in September. Could you give a brief update? Are there technical issues preventing you from completing it?

Hi @semuelle 
We've communicated with the Web3 Foundation a couple of months ago about the difficulties of implementing this grant. Our contact person then was @Noc2 and later after that Marcin. Since the email thread was a long one, can you sync with them? We've concluded that the grant should be suspended.

**Comment by semuelle** [comment]
Sorry for the confusion. I'll get back to you.

**Comment by alxs** [comment]
@Daniel-K-Ivanov what's the future of Subsembly, do you intend to pick this up again at some point?

**Comment by Noc2** [comment]
@Daniel-K-Ivanov I think we can terminate this agreement at this stage. I will open a PR to update the contract. If you ever want to continue to work on this, just let us know or feel free to apply for a new grant.

**Pull request merged**
