### PR TITLE
Grant application: WasmEdge for Substrate

### PR DESCRIPTION
**Pull request by juntao**
### Project Abstract

Supporting [WasmEdge](https://github.com/WasmEdge/WasmEdge) as an alternative Substrate WebAssembly runtime. The project increases the Substrate ecosystem's node software diversity by supporting an alternative high-performance WebAssembly Runtime implementation. The project team are the maintainers of the WasmEdge WebAssembly Runtime project, and had successfully completed W3F projects in the past.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [X] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the application. This looks really interesting and definitely seems to be a project, which we want to support. Could you add the “default” deliverables 0a-0d of the template to each milestone? https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md And in general, feel free to add additional details to the deliverables (= requirements of the contract).

**Comment by juntao** [comment]
> Thanks a lot for the application. This looks really interesting and definitely seems to be a project, which we want to support. Could you add the “default” deliverables 0a-0d of the template to each milestone? https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md And in general, feel free to add additional details to the deliverables (= requirements of the contract).

Thanks! Fixed and added a little more details. I also squashed the new commit.

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I’m happy to support the project and I will share it with the rest of the team.

**Comment by Noc2** [comment]
And just to clarify: We can obviously not ensure that this gets actually merged by parity, but it won’t be necessary for the approval of the milestone itself.

**Comment by juntao** [comment]
> And just to clarify: We can obviously not ensure that this gets actually merged by parity, but it won’t be necessary for the approval of the milestone itself. 

Understood. We will make a best effort to be part of the standard substrate distro. :) Thanks.

**Review by alxs — APPROVED** [review]
Interesting! Happy to see where this goes.

**Review by takahser — APPROVED** [review]
@juntao thanks for submitting this grant application. It sounds very interesting to me, I'm more than happy to approve. Looking forward to your delivery! 👍

**Review by Noc2 — APPROVED** [review]

**Comment by alxs** [comment]
Hey @juntao, any updates on the third milestone? The performance benchmarks and analysis would probably be a big help in showcasing WasmEdge's potential for Substrate, are they still in your roadmap?

**Comment by keeganquigley** [comment]
Hi @juntao just bumping a friendly reminder, see Alxs comment above.

**Comment by juntao** [comment]
Hi @alxs and @keeganquigley 

Thank you for following up. Happy new year.

We have been preparing a PR to support WasmEdge as an alternative and configurable runtime for Substrate. However, it is coming along slowly since we need to bring our working branch of Substrate up to date first (we demoed on a Substrate version from a few months ago). There apparently have been a lot of changes.

The performance WasmEdge is largely on par with wasmtime in Substrate -- WasmEdge is faster in some cases, but slower in others. We can continue to tweak the performance over time. Besides that, I think there are compelling reasons to support WasmEdge in Substrate. Specifically,

* The software supply chain security factor discussed in the original grant proposal. WasmEdge is implemented entirely differently from wasmtime.
* WasmEdge has better developer tooling support now. It is bundled in Docker Desktop since Dec 2022. 10 million Docker users automatically have access to WasmEdge and its application APIs -- e.g., the WasmEdge socket API could be useful for Substrate -- to bring the networking code into Wasm instead of in host functions.
* Fedora Linux and Red Hat Enterprise Linux now officially has WasmEdge as packages. So, it greatly simplifies WasmEdge application deployment and management on those Linux OSes and in OpenShift. 

In any case, my apologies for the delay. But we are still working on the compatibility issues to bring it up to date with the latest and greatest Substrate! Stay tuned.

cheers
Michael

**Comment by Noc2** [comment]
@juntao Thanks a lot for the update. If you need longer to finish this grant, please update the original application via a PR as well as the estimated duration. This way, your contract is officially updated, and you could integrate additional changes/work, etc.

**Comment by keeganquigley** [comment]
thanks @juntao friendly reminder regarding @Noc2 comments above.

Please submit an [amendment](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval) to extend the timeline, and that will help put the pressure off as well. Thanks!

**Comment by keeganquigley** [comment]
Hi @juntao any updates you can provide? Please note that if we don't hear from you after a few weeks, the grant could be subject to termination due to inactivity.

**Comment by keeganquigley** [comment]
Hi @juntao are you able to provide an update?

**Comment by keeganquigley** [comment]
Hi @juntao unless you are planning to deliver soon, I think it's best to close this grant for now and it can always potentially be re-opened in the future should you wish to continue working on it. Please let me know otherwise I'll go ahead and file the PR to be reviewed by the committee.

**Comment by juntao** [comment]
Hi @keeganquigley 

Yes, I think it is perhaps best to close it for now. The substrate main code branch has advanced over time, and it becomes harder and harder to merge over time.

We now know that it is viable to swap out wasmtime for WasmEdge in substrate. When there is concrete demand for this from the community, we can revisit this again. Thank you.

**Comment by keeganquigley** [comment]
Thanks for the update @juntao much obliged. I will go ahead and file it now.

**Pull request merged**
