### PR TITLE
Decentralized pallet-staking audit tool

### PR DESCRIPTION
**Pull request by taqtiqa-mark**
#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x] **Level 2**:  Up to $30,000, 3 approvals

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. In general, we are interested in a better overview when it comes to staking (and slashing) and also in regard to historical data. So you can add more details to the milestones and make this application more than a draft. I have one initial question: What do you mean by workbook? Do you plan to create a shared Google sheet or something similar?

**Comment by taqtiqa-mark** [comment]
> I have one initial question: What do you mean by workbook? Do you plan to create a shared Google sheet or something similar?

The intention is to have a decentralized tool, apart from trying to escape the surveillance business models. So, I'll make sure to provide an OpenOffice/LibreOffice Calc workbook. The idea is that a relay chain distributes it as part of its toolchain.

I'll add the milestone details.

**Review by Noc2 — APPROVED** [review]
I just changed the level: https://github.com/w3f/Grants-Program/pull/1854/commits/c0ac4461cbcd91f7a870b9b66541cf49ed56ee83 Otherwise, it looks good to me, and I'm happy to go ahead with it.

**Comment by takahser** [comment]
@taqtiqa-mark just a question here - are you planning to complete your [active grant](https://github.com/w3f/Grants-Program/pull/1348) before potentially starting this one (given, it'll get accepted)? I'm asking because usually we ask grantees to finish any active grant before starting a new one. That being said, I saw your note that this proposal is still considered to be a draft, so if you're just looking for feedback on this while finishing your previous grant, I'm fine with the approach.

**Comment by taqtiqa-mark** [comment]
> @taqtiqa-mark just a question here - are you planning to complete your [active grant](https://github.com/w3f/Grants-Program/pull/1348) before potentially starting this one

Yes. I believe that grant is [effectively complete](https://github.com/w3f/Grant-Milestone-Delivery/pull/925), subject to reviewer feedback.

**Comment by taqtiqa-mark** [comment]
> so if you're just looking for feedback on this while finishing your previous grant, I'm fine with the approach.

FYI, @Noc2 has advised that only one application is considered at a time. I've indicated that in my view [this application](https://github.com/w3f/Grants-Program/pull/1848) is the higher priority.

**Review by dsm-w3f — COMMENTED** [review]
@taqtiqa-mark thank you for the application. Could you provide more details on how do you plan to integrate the workbook with the pallets? Furthermore, how do plan to assure the quality of the software developed? Can you provide an overview of your experience with software development?

**Comment by taqtiqa-mark** [comment]
> @taqtiqa-mark thank you for the application.

FYI, @Noc2 has advised that only one application is considered at a time. I've indicated that in my view application https://github.com/w3f/Grants-Program/pull/1848 is the higher priority.  If that application is rejected I'll update with the details requested.

**Comment by dsm-w3f** [comment]
@taqtiqa-mark I reviewed this one and not the other since this is the only one marked as ready to review. The other application still needs some clarification to go for committee review. I'll comment there about it.

**Comment by taqtiqa-mark** [comment]
In light of the experience with the grant [Token economics survey (2022)](https://github.com/w3f/Grants-Program/blob/master/applications/tokenomics-survey-2022.md). Specifically, the attempt, on the brink of accepting Milestone 3, to bring within scope material that was clearly defined as out of scope, and the attempt to have guidance provided to block chain teams. Details here:

https://github.com/taqtiqa-mark/tokenomics-survey-2022/issues/4

And given the complexity and subtlety of the analysis that is the subject of this application, prior experience dictates it is prudent to:

1. Suspend this application
2. Revise the application to reflect the risks noted above

I'll reopen in due course.

**Pull request closed without merging**
