### PR TITLE
Dao-entrance Grant Application: online collaboration tool for web3

### PR DESCRIPTION
**Pull request by bai-3**
#### Project Abstract

**DAO-entrance** is trying to create a safe, efficient, powerful and Web3-based instant collaboration tool, which is a breakthrough. It establishes solid trust relationship among organization members through open and transparent smart contract; it maintain end-to-end encrypted communication, to ensure efficient and confidentiallity; it improves work efficiency with thousands of open-source collaborative tool libraries; it keeps data in safe hands through distributed and decentralized storage. 

**DAO-entrance** focuses on providing DAO with a comprehensive collaborative tool. The tool will help DAO to set up a core team. After the core team authorized by the community, they can make decisions on the daily affairs of DAO, in order to avoiding endless voting. 

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (aUSD/USDT) address for the payment of the milestones is provided in the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application and your interest in our grants program. It looks like you are applying for a level 1 grant (below 10k) and not a level 2 grant. Could you update this? Also, I have one initial question: Doesn't it make more sense first to implement the backend before you develop the UI? So I would start with the substrate module as milestone 1.

**Comment by bai-3** [comment]
> Thanks for the application and your interest in our grants program. It looks like you are applying for a level 1 grant (below 10k) and not a level 2 grant. Could you update this? Also, I have one initial question: Doesn't it make more sense first to implement the backend before you develop the UI? So I would start with the substrate module as milestone 1.

Hey @Noc2 ,

Thanks for your experienced suggestions.
we have update level and  milestone.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the updates. I have two additional follow-up questions:
- Have you already looked at other DAO-focused projects in our ecosystem, such as https://github.com/sctllabs? You can also find some of them here: https://wiki.polkadot.network/docs/build-open-source 
- Do you already have some mock-ups or UI that you can share at this stage? Usually, we ask teams to provide this upfront, but in your case, it might not be necessary, given that you are only requesting a level 1 grant. 

Independent of it, I will mark your application already as ready for review.

**Comment by bai-3** [comment]
Hey @Noc2 ,
Thank you for reminding，we carefully checked the ecological projects.
Our core goal is to provide web3 collaborative clients. We will make our clients (app/desktop) adapt to them in the next time. Although we also provide palet, we prefer to be compatible with DAO projects in the ecosystem.
At present, our UI design drawing has not been completely completed. Here are some simulated interfaces. Thank you for reminding us that we will provide UI preparation before submitting. This is the address of the simulation interface:
https://github.com/dao-entrance/design/blob/main/README.md

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for sharing the link, but I can not open it at the moment. Potentially it's a private repo: https://github.com/dao-entrance/design/blob/main/README.md

**Comment by bai-3** [comment]
@Noc2 ,I'm particularly sorry, I didn't notice this. I have set it to public.
Now you can click directly to see.

**Comment by bai-3** [comment]
@Noc2 
I'm particularly sorry, I didn't notice this. I have set it to public.
Now you can click the following link to view directly：https://github.com/dao-entrance/design/blob/main/README.md

**Comment by keeganquigley** [comment]
Hi @bai-3 thanks for the application. I like that it is based on the Matrix protocol. Just a couple questions:

- I'm assuming you aren't planning to write 4 articles? If that's the case, this is really only mandatory for the last milestone, so you can remove it from the others.
- How exactly do you plan to develop the end-to-end encryption mentioned [here](https://github.com/w3f/Grants-Program/pull/1445/files#diff-c1704076f0eeb84a05ff168ed158a14a41763bc187d6ccdd059bb6198c015542R15)?
- In M4, [this statement](https://github.com/w3f/Grants-Program/pull/1445/files#diff-c1704076f0eeb84a05ff168ed158a14a41763bc187d6ccdd059bb6198c015542R200) doesn't make much sense grammatically. Can you explain what you mean by "creating a running container" and how this is different from the Docker deliverable?

Thanks!

**Comment by bai-3** [comment]
@Noc2
Thank you for reminding，We have deleted the other 3 articles.
Due to the shortage of developers, we use matrix's official E2E scheme in the early stage, and we will focus more on its security and privacy in the later stage.
Because my English is not good, the correct description of Flutter DAPP rendering is "we create a engine run DAPP on Flutter natively,it is Compatible with Polkadot {. js} extension api " , The core rendering engine is webf （https://github.com/openwebf/webf）

**Comment by bai-3** [comment]
@keeganquigley
Thank you for reminding，We have deleted the other 3 articles.
Due to the shortage of developers, we use matrix's official E2E scheme in the early stage, and we will focus more on its security and privacy in the later stage.
Because my English is not good, the correct description of Flutter DAPP rendering is "we create a engine run DAPP on Flutter natively,it is Compatible with Polkadot {. js} extension api " , The core rendering engine is webf （[https://github.com/openwebf/webf）](https://github.com/openwebf/webf%EF%BC%89)

**Review by keeganquigley — APPROVED** [review]
@bai-3 cool! Thanks for your explanations and the changes. No worries on your English, I just wanted to make sure that it was a separate deliverable and wasn't referring to a Docker container. It makes more sense now. I'm happy to go ahead with it and looking forward to seeing what you come up with!

**Comment by keeganquigley** [comment]
@bai-3 sorry I meant to mention that your application still needs one more approval from the committee to be accepted, according to the levels.

**Comment by bai-3** [comment]
@keeganquigley Thank you very much for agreeing with me. This is what makes me most happy.

**Review by randombishop — APPROVED** [review]

**Review by Noc2 — APPROVED** [review]

**Pull request merged**
