### PR TITLE
Interstellar- New Recovery options

### PR DESCRIPTION
**Pull request by nashjl**
#### Project Abstract

We aim at leveraging the current Substrate Frame Recovery Pallet to introduce both an original NFC Recovery based on day-to-day NFC devices (payment/access/transportation cards, smartwatches, car keys, headphones, speakers, or any other NFC tags) and a specific Recovery File Token based on a one-time visual cryptographic code. A new recovery setup will allow for only a single or a combination of multiple recovery options (devices/files/social recovery).

Amendment P2: [w3f/Grants-Program#2028]( https://github.com/w3f/Grants-Program/pull/2028)

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ Polkadot (USDC & USDT) or BTC address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by keeganquigley — CHANGES_REQUESTED** [review]
Thanks for the application @nashjl this looks really cool. 

- Could you perhaps integrate more technical details into the deliverables themselves, such as what main `structs` will be built for the pallet?
- I see from your last grant that the garbled circuit initially had some problems, are these resolved in order to build the recovery file token?

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the new application. However, at this point, I recommend getting funding via other programs or VC investments. As pointed out before, the grants program should not be the main funding tool for any project for a longer period of time. See my comments on your previous grant application https://github.com/w3f/Grants-Program/pull/1543#pullrequestreview-1328015438

**Comment by nashjl** [comment]
Thanks for your feedback @keeganquigley! 

* Sure, we updated the milestones - does this work for you? 

*  Yes. The M1 garbled circuits evaluation performance enables reaching more than 60 fps now while the M2 works as expected, making the overall screen even more comfortable to read. 

 Hi @noc2, thanks for reaching out! Your previous feedback is one of the reasons we designed the `extended_recovery` pallet to be generic and totally independent of the specific Interstellar architecture. 

We see this pallet as a common good that can be used by any substrate chain. 

At the same time, we leveraged our previous work with the W3F within this newly proposed grant - demonstrating to other teams that our deliverables and this technology can be used independently of our project for other use cases including recovery and much more.

**Review by keeganquigley — CHANGES_REQUESTED** [review]
Thanks for the changes @nashjl I do like the application and think the pallet has a good common-good use case. But I agree that we've funded a lot for your team already. Would you be willing to remove the third deliverable from both milestones (updating the app) and fund this part yourself? I'd be more apt to fund just the build of the pallet itself for a reduced scope/cost.

**Comment by nashjl** [comment]
Hi @keeganquigley, thanks for your support. We’re happy that you like it.

We could indeed remove the third deliverable from both milestones. However, note that the app plays an important role for the NFC Recovery and makes more sense for evaluating the milestones. Additionally, removing this part won’t really reduce the costs of this grant as it is not the most complex part of our deliverables.

After speaking internally, we could propose the following:
-	Keep the app update for this grant | Thus providing a more interactive and complete evaluation process
-	Remove the app update from this grant | Thus providing only script for the evaluation; NFC tag reading will be faked

To address your budget concerns and considering our commitment to the Web3 Foundation, we’re willing to reduce the costs of the overall grant to 25k (with or without including the app)

**Comment by keeganquigley** [comment]
Thanks @nashjl I agree it probably doesn't make sense to remove M3 if it won't have any effect on the price, so you could keep that in since you it will be helpful for an evaluation. Thanks for the explanations. Feel free to ping me once you make the changes.

**Comment by nashjl** [comment]
Thanks @keeganquigley , costs are updated

**Review by keeganquigley — APPROVED** [review]
Thanks @nashjl I appreciate the changes. I'm personally willing to go ahead with it. I will mark the application as ready for review and ping the rest of the committee.

**Comment by nashjl** [comment]
Thanks @keeganquigley, we really appreciate your support !

**Review by takahser — CHANGES_REQUESTED** [review]
@nashjl hi again, and thanks for submitting this. I agree with @Noc2 that after extended funding through the grants program, at this point you should look into alternative funding sources, such as the treasury, our newly launched [decentralized futures](https://futures.web3.foundation/) program or VC funding. Therefore I'm not going to approve it.

**Comment by semuelle** [comment]
Hi @andredif, sorry for the inconvenience, but we [just started requiring KYC/KYB checks](https://grants.web3.foundation/docs/faq#what-is-kyckyb-and-why-do-i-have-to-provide-this-data) for all potential grantees. Could you please provide the information outlined under [this link](https://in.sumsub.com/idensic/l/#/uni_JRqwo72Y5AjXaRDO)? Let me know if you have any questions or issues!

**Comment by andredif** [comment]
Hi @keeganquigley , there should be a mistake because I'm an applicant into another Grant, #2113, and I've successfully completed KYC for that.

**Comment by keeganquigley** [comment]
Thanks @andredif usually we ask teams to go for one grant at a time. Which grant would you like to work on first? Perhaps it's better to close the other one in the meantime.

**Comment by andredif** [comment]
@keeganquigley , probably there's a misunderstanding. I am NOT an applicant into this Grant application for Interstellar. I am ONLY an applicant at #2113,QuantumGuard, which has already been approved. I'm writing here to please remove me from this conversation, because I've nothing to do with this Grant application. Somehow, I was tagged here, but I do not belong to it.

**Comment by keeganquigley** [comment]
Ah thanks for clarifying @andredif yes looks like you were incorrectly tagged, sorry about that. @nashjl would need to do the KYC check for this application.

**Comment by semuelle** [comment]
@nashjl, friendly reminder that we still need company information from you to proceed with the application: https://in.sumsub.com/idensic/l/#/uni_JRqwo72Y5AjXaRDO

**Comment by nashjl** [comment]
Happy New Year to you @keeganquigley @Noc2 @semuelle @takahser and the entire Web3 Foundation team! We appreciate your ongoing support, valuable feedback, and passion for Web3.

Apologies for the delay, @semuelle and @kegan. We have just completed the upload of all the required information for the KYC process but will shift our focus to the Decentralized Futures Program. Our goal is to incorporate the recovery and its components into a larger-scale project application.

It would be great to schedule a small meeting to discuss the scope and vision of our project for the DFP. Let us know if that works for you?

**Comment by semuelle** [comment]
Hi @nashjl, thanks for the update! Regarding DF, feel free to book a slot here: https://calendar.app.google/A3suDaSfuqjHchmv8

**Comment by semuelle** [comment]
I am going to close this application in the meantime. We can reopen it when necessary.

**Pull request closed without merging**
