### PR TITLE
Spheroid Earth project application

### PR DESCRIPTION
**Pull request by rudyryk**
#### Project Abstract

Spheroid Earth is an open visual positioning platform for AR/XR applications and metaverses.

Our initial toolset aims to simplify the work of researchers in the fields of computer vision, photogrammetry, and structure from motion (SfM). Our long-term goal is to build a Kusama/Polkadot parachain that serves as a global-scale visual search engine.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the application. But I have one initial question: How do you exactly leverage and integrate Polkadot or Substrate here?

**Comment by rudyryk** [comment]
@Noc2 David, thank you for the question.

The exact architecture of the decentralized visual positioning platform is beyond the scope of this application. However, we have initial considerations and foundational ideas on the matter.

We can decompose the platform into three blocks:

- Data collection and computational pipeline to generate a search index and other valuable artifacts, such as location 3D models.
- Storage of the search index and artifacts.
- Querying the search index, which may also involve a computational pipeline for localization.

Let's take a closer look at each block.

The process of **Data collection and computational pipeline** involves off-chain interactions that require human resources. For example, an individual may need to use a smartphone to record footage of a local public park. Afterwards, the footage is processed using a powerful machine that runs a computer vision pipeline. However, the number of tasks and footage required is enormous, as entire living areas ultimately need to be covered.

To address this challenge, we'd propose creating a decentralized marketplace for such gigs. This would involve individuals like Mira placing gigs for capturing footage of Central Park for X coins, and others like Alex completing the task. Mira would then approve the quality of the footage, and some automated consensus voting would be implemented to ensure fairness.

The **Storage of the search index and artifacts** is well-suited for a decentralized architecture, such as IPFS-like storage. Several existing solutions can address this issue. It is worth noting that storing the search index and artifacts does not violate privacy because the data is abstract at this point, whether it is point clouds or keypoint descriptors.

The community will benefit from having such an index because it can be used by anyone to perform visual positioning, considering that it is a fully open search database covering the entire planet. Additionally, it has the potential for a very resource-wise storage strategy. For example, some parts of the search index can simply be deprecated and then deleted when no one is willing to allocate coins to store that data, while useful parts remain.

Finally, **Querying the search index** can also benefit from a decentralized approach. For instance, if the organizer of the "Icing Lady" festival aims to deliver a seamless AR and Metaverse experience, it is essential to allocate computational resources for computing search query results. Decentralized protocols make it easy to allocate compute nodes by charging an account a certain amount and specifying the location area from which queries should be processed.

This is our current general vision for a decentralized approach, which may be refined and changed in the future. When designing our initial local-first computational pipeline, data formats, and tools, we consider their compatibility with future decentralized development.

**Comment by keeganquigley** [comment]
Thanks for making the changes @rudyryk however I have to agree with my colleague that I'm still not seeing how this grant relates to the Polkadot/Substrate ecosystem, besides the fact that you eventually want to build a parachain, which is not typically something we fund.

The current deliverables aren't coupled with substrate tech at all, and therefore I don't think this project is the best fit for the W3F grants program. Therefore I won't approve the application at this time, but it sounds like an interesting project in the VR world and I wish you the best of luck with it.

**Review by takahser — CHANGES_REQUESTED** [review]
@rudyryk I share the general sentiment of other reviewers here - IMHO it's an interesting AR project, but unfortunately none of the deliveries are a good fit for your program. You mention in your proposal that

> The exact architecture of the decentralized visual positioning platform is beyond the scope of this application.

However, we'd expect you to share the exact architecture of the application to be able to make a well-based decision on whether we'd want to fund the project. Hence, I believe that in the current state it's very far from being a good fit for our program.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the detailed reply. Given the feedback of the rest of the committee, we decided to close the application for now since it's not (yet) a fit for our grants program. Feel free to apply again in the future, and let me know if you have any questions in the meantime.

**Comment by rudyryk** [comment]
@Noc2 @keeganquigley @takahser Hello everyone, and thank you for the clear feedback! We will revise our roadmap and come back with an updated application.

**Pull request closed without merging**
