### PR TITLE
Add SubRelay application

### PR DESCRIPTION
**Pull request by budtr**
#### Project Abstract
SubRelay is a no-code solution to build automation workflows on any Substrate-based chain. The application helps users to create their off-chain automated workflows by subscribing to on-chain events through the interface. We aimed to make the app easy for average users but remain a powerful tool for advanced users.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application and sorry for the delay. This sounds like an interesting project. Is there a specific reason why you didn't integrate any tests in your first milestone? Could you also specify if the features in the milestones are implemented as part of the interface and the API? Currently, some of the deliveries, e.g. feature list of workflows, sound like they are only implemented as part of the UI. Also, your first milestone has twice the number 3.

**Comment by budtr** [comment]
Hi @Noc2, thanks for the response. I changed the application to add detail about API and API integration in sections 5 and 6 for both milestones. For your consideration about testing in milestone 1, our team wants to release a usable version and getting users feedback before settle down with unit tests and integration tests. And, we think the workload of milestone 1 is heavy enough cause of hidden tasks such as set up back-end infrastructure, source code skeleton.

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I'm happy to mark it as ready for review and go ahead with it.

**Review by alxs — APPROVED** [review]
Looks good to me @budtr. Thanks for the detailed application.

**Review by keeganquigley — APPROVED** [review]

**Comment by keeganquigley** [comment]
Hi @budtr how is milestone 2 coming along?

**Comment by budtr** [comment]
Hi @keeganquigley,
We are setting up the unit tests and e2e tests, and fixing mirror bugs. After that,  we will proceed with the final review and schedule the delivery for milestone 2, expected to be completed within next month.

**Comment by keeganquigley** [comment]
Thanks @budtr if you find that it will take longer than that, please consider submitting an amendment to extend the timeline, which will take the pressure off.

**Comment by keeganquigley** [comment]
Hi @budtr are you able to give us an update on M2?

**Comment by budtr** [comment]
Hi @keeganquigley, apologies for the delay. Milestone 2 had a heavy workload due to unforeseen issues. We've completed the delivery submission and created a pull request. Please take some time to evaluate our submission and provide feedback. Thank you.

**Pull request merged**
