### PR TITLE
Add Asylum grant proposal

### PR DESCRIPTION
**Pull request by YaremenkoM**
### Project Abstract

Asylum is a platform for blockchain-based games.
We are creating an infrastructure that will simplify the integration of the blockchain, unite the community and give a possibility to create a new generation of games.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Comment by YaremenkoM** [comment]
> Thank you for submitting a grant application. We've assessed your submission and have found that it requires a higher level of technical detail in order to be considered for review. We encourage you to expand on it by providing a more precise specification/technical details. The [section on project details](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#project-details) in the application template is a good reference as to what type of information we expect applicants to provide, and these [category-specific requirements](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md) contain more precise guidelines depending on what type of software you're building. An area of the application that we often find to be insufficiently elaborated are the milestone deliverables. At a minimum, please indicate what languages/technologies you will be using to implement each deliverable, and provide a technical summary of its expected functionality. Note that deliverables should be tangible, reusable by other teams and in most cases not already present in the ecosystem. If they are, you will need to provide a comparison to existing implementations and explain why it makes sense to fund your approach. Also see our [FAQ](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md#-general) for a breakdown of what we fund and what we don't. Let us know as soon as you're done with your changes, and we'll give your application another look!

Thank you for the feedback.
We will elaborate on technical details and will consider all mentioned points.

Will update the application as soon as possible.

**Comment by YaremenkoM** [comment]
@Noc2 
Thanks for waiting for our updates!
We updated the application due to mentioned points and added more detailed specifications as long as provided UI wireframes.
Looking forward to another review!

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. The application looks interesting. My recommendation would be to remove milestone 2 for now, since you probably can define the second milestone much better at a later stage (e.g. which new options, etc) and it will be easier to approve on our side. Potentially it makes even sense to split milestone 1 into two different milestones, but this is up to you. Are you aware of https://github.com/ajuna-network/? They also combine unity with substrate.

**Comment by 0xMarkian** [comment]
Good stuff !

**Comment by LastSymbol0** [comment]
Hey @Noc2 , thanks for the suggestion!
We removed 2nd milestone for this application and split 1st into two parts.

Yes, we are aware of the Ajuna network, but I believe we have different approaches to building similar things. Our main focus is to build possibilities for new gaming/metaverse experiences and make them convenient to use. And from what I see, Ajuna is more focused to create a framework for convenient usage of the substrate in games.
We are really located close to each other, but from my perspective, there is a place for such different solutions.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the update. I have one more question, before I share it with the rest of the committee. Would you be willing to reduce the price to 50k and a level 2 grant? This would make it a lot easier to get the necessary approval.

**Comment by LastSymbol0** [comment]
Yeah, that makes sense.
I removed the second game from the second milestone and decrease its cost to 20k, so we can downgrade this application to level 2

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. Sounds good to me. I’m happy to already share it with the rest of the team. Could you also integrate the unity integration, which you develop as part of milestone 2? And just to double check the game will actually interact with the substrate Asylum Core pallet, correct? Could you clarify as part of the specification of milestone 2?

**Comment by LastSymbol0** [comment]
Thanks!

Yeah, I've added a unity integration for the second milestone and specified that game will use our pallet

Waiting for other guys to review 🙂

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I’m happy to go ahead with it and to support the project.

**Comment by takahser** [comment]
Thanks for your application and interest in the Web3 Foundation Grants Program. 👍
I just finished reading it and have a few questions.

> The part of the Asylum project is an on-chain code (on layer 1, or layer 3)

What exactly do you mean with layer 1 and layer 3? Could you elaborate on that?

> 1.1 | 2D visualization | NFT item created with the proposed standard will have the ability to have a visual interpretation in form of a 2D image.
> -- | -- | --
> 1.2 | 3D visualization | NFT item created with the proposed standard will have the ability to have a visual interpretation in form of a 3D model.

- Will these be saved on-chain or off-chain?
- Which file type do you intend to support for 2D/3D objects?

> 1.3 | Multiple visual interpretations | NFT item created with the proposed standard will have the ability to have multiple visual interpretations, both for 2D or 3D visualization types. Interpretations will be stored under the different tags, for example, "2d-pixeled-inventory-view" or "3d-realistic-equipped".
> -- | -- | --

Are multiple visual interpretations of the same object going to build on top of the same corresponding model? For example, if you have an instance of a `greyDog` 3D visualization and you'll support 2 visual interpretations `-pixeled` and `-realistic`, will `greyDog-pixeled` and `greyDog-realistic` both point to the same `greyDog` instance? Or will both interpretations be self-sufficient new instances without having any reference to the original `greyDog` instance?

**Comment by LastSymbol0** [comment]
Hi @takahser , sorry for a long response 

> 1. What exactly do you mean with layer 1 and layer 3? Could you elaborate on that?

Under layer 1 is meant blockachain runtime code (like Substrate pallets) with described features. Under layer 3 is meant smart-contracts on other chains.
As it was mentioned, Asylum is seeking to be the chain-agnostic solution, so now we are targeting all options.

However, for this grant application, we will build all on-chain features in our pallets.

> 2. Will these be saved on-chain or off-chain? (2D/3D interpretation)

For now, we are in process of defining what data will be stored on-chain/off-chain. But speaking about all media sources (like pictures or 3D models) - they will be stored off-chain.

> 3. Which file type do you intend to support for 2D/3D objects?

Currently, we are in process of defining file types, but I believe it will not have a big impact on the architecture. We will find the most convenient formats that can be used for games

> 4. Are multiple visual interpretations of the same object going to build on top of the same corresponding model?

Every interpretation for an item will be a self-sufficient instance.

**Review by takahser — APPROVED** [review]
@LastSymbol0 thanks for clarifying. 👍
I'm happy to go along with your application as well.

**Review by gautamdhameja — APPROVED** [review]

**Comment by LastSymbol0** [comment]
Hey guys!

Thank you a lot for approving our application!

Sorry for the long response, the reason is that our team is mostly located in Ukraine and we needed time to dealt will all circumstances. Now we are continuing our work in the regular schedule, but due to this gap (last 15 days), we will shift our deadlines forward.

Hope this will not become a problem 🙂

Thanks!

**Comment by semuelle** [comment]
No rush with this, @LastSymbol0. We are generally not very strict with delivery dates, and under these extraordinary circumstances, you should have all the time you need. 

I hope you are all safe and healthy. When you have a clearer view of what's ahead, you can submit an amendment to the contract with an updated timeline.

**Comment by LastSymbol0** [comment]
Hey guys!

Just want to update you regarding the process of delivering milestones within our application. We started active development of 1st milestone at the beginning of April, so now we are on the way to its completion, approximately next week. The week after will be ready to open a PR regarding the milestone delivery process. You can check our development progress by the links to our gitlab, if needed.

Thanks!

**Comment by semuelle** [comment]
Thanks for the delivery, @LastSymbol0. Please do update your company address in the application. Just make sure the PR is made from the same account as the original application. Thanks!

**Pull request merged**
