### PR TITLE
Women in Blockchain & Sydtek Grant Proposal

### PR DESCRIPTION
**Pull request by womeninblockchaincad**
Grant proposal

### Project Abstract

Women in Blockchain Canada will collaborate with Sydtek to deliver high-quality Substrate training globally as well as enable the general public to see the unprecedented benefit of using the Polkadot ecosystem to allow for greater community impact. Many projects thus far have addressed nearly every facet of need within the blockchain and crypto industry, from lending, borrowing, yield aggregation, fast-settling and low-cost infrastructure, payment rails, collectibles, blockchain ecosystems, gaming, security, automation, decentralization - and yet few attempt to address the core issue of the space: how to attract a new generation of developers to build novel blockchain applications for a more ethical and sustainable future. In this proposal, therefore, we will address the need for building a new generation of developers within the Polkadot ecosystem. 

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x ] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [ x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [ x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [ x] The software delivered for this grant will be released under an open-source license specified in the application.
- [ x] The initial PR contains only one commit (squash and force-push if needed).
- [ x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the application and the interest in our grants program. However, our current grants program focuses on open source software development and research and doesn’t support education focused applications. I’m therefore closing the PR. 

That said the on-chain [treasury](https://github.com/w3f/Grants-Program#treasury) might be interested in supporting your project. I will share the application with Raul, who helps the on-chain council with the treasury spending. Also let me know, if I should put you in contact with him via email.

**Comment by rrtti** [comment]
Hi @womeninblockchaincad: feel free to email me to raul@justopensource.io if you want to discuss treasury funding opportunities, happy to help!

**Comment by womeninblockchaincad** [comment]
Hello,

Thank you - yes please connect us.

**Comment by womeninblockchaincad** [comment]
Hello,

Grateful if we can connect us to Raul.

Best,

Justyna

**Comment by Noc2** [comment]
Hi Justyna, Raul already replied here, see his comment above. Feel free to contact him at raul@justopensource.io

**Pull request closed without merging**
