### PR TITLE
Grant request: Polkadot-js extension account visibility management enhancement - authorization per account and per website

### PR DESCRIPTION
**Pull request by Tbaut**
### Project Abstract

In response to the RFP: https://github.com/w3f/Grants-Program/blob/master/rfps/privacy-enhancement-polkadot-extension.md This is a grant request to enhance Polkadot-js extension's user privacy by letting them select what account should be shared with what website, instead of granting access to any visible account.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] Hackathon
- [x] Personal Recommendation
- [ ] Substrate Builders Program
- [ ] Investor/VC
- [ ] Online Search 
- [x] Other: this Github repo

### CODE REVIEW

**Comment by takahser** [comment]
@Tbaut thanks for applying for this grant. Just for reference: https://github.com/polkadot-js/extension/issues/1037#issuecomment-1084283229

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Could you add the deliverables 0a-0d of the [template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) to the milestones? These are usually mandatory and partly necessary because of our terms and conditions.

**Comment by Tbaut** [comment]
Oops, sorry I missed the fact that it was a mandatory. I will just follow what is the standard here in terms of licence, testing, and will make sure to write an article about my work.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. However, there seems to be an issue with the formatting. Could you fix this?

**Comment by Tbaut** [comment]
Sorry again for not checking this. Should be good now.

**Review by Noc2 — COMMENTED** [review]
Perfect. I will label it as ready for review and we will make a decision shortly.

**Review by takahser — APPROVED** [review]

**Review by Noc2 — APPROVED** [review]
We decided to go ahead with your application. So, I’m happy to approve it.

**Pull request merged**
