### PR TITLE
Create Comingchat-wallet-SDK.md

### PR DESCRIPTION
**Pull request by 0xkyle37**
### Project Abstract

Comingchat-wallet-SDK is a full-environment(Android & IOS) and multi-chain wallet SDK. Comingchat-wallet-SDK aims to become a common component of the substrate ecological mobile APP, and minimize the threshold for developing the substrate ecological mobile APP.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] Hackathon
- [ ] Personal Recommendation
- [x] Substrate Builders Program
- [ ] Investor/VC
- [ ] Online Search 
- [ ] Other: _______

### CODE REVIEW

**Comment by 0xkyle37** [comment]
If there is anything that needs to be changed or added, please feel free to let me know~ 
@Noc2 @semuelle

**Comment by 0xkyle37** [comment]
If there is anything that needs to be changed or added, please feel free to let me know~ 
@Noc2 @semuelle

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Your website https://www.comingchat.com/ doesn’t seem to load for me. Could you specify the programming language of your deliveries? And have you looked at potential similar solutions in our ecosystem? For example why are you not using https://github.com/polkadot-js

**Review by semuelle — CHANGES_REQUESTED** [review]
Thanks again for the application, @0xkyle37. Some notes & questions:

- Could you add the tech stack you are using
- Why are your deliverables called "Node: ..."? Neither "Node" as in "NodeJS" nor "Substrate Node" seem to make sense here.
- Can you also add a "Development Status" section? Looking at your repositories, it looks like most of what you are proposing here is already implemented.
- The specification of deliverable 3 is unclear to me. It doesn't sound like a specification.

**Comment by Noc2** [comment]
I’m closing the application due to inactivity. Let me know if I should reopen it.

**Pull request closed without merging**
