### PR TITLE
Add Pass3 application

### PR DESCRIPTION
**Pull request by andrwlt**
#### Pass3
Pass3 is a crypto wallet, engineered for simplicity without compromising security. It leverages Passkeys for effortless wallet setup and employs a social guard system for account recovery in case of device loss. Built as a mobile-first web application, Pass3 ensures seamless functionality across both mobile and desktop platforms.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the application. Looks like an interesting project. Could you add more technical details to the specification of the milestone tables? For example, how exactly do you combine passkey with the private key of the Polkadot account? What does asset management mean (e.g., listing pallets that you will support)?

**Comment by semuelle** [comment]
pinging @andrwlt

**Comment by andrwlt** [comment]
Hi @Noc2 and @semuelle,
Sorry for the late response. I have updated the application by adding more technical details. Can you please take a look and let me know if I am missing something? Thank you.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update, and sorry for the late reply. I will mark it as ready for review. But could you potentially reduce the price? The application seems rather expensive to me compared to your previous project: https://github.com/w3f/Grants-Program/pull/776

**Comment by andrwlt** [comment]
Hi @Noc2,
Thank you for your response.
Regarding your question, I don't believe we can reduce the cost. In the previous application, a portion of the cost was covered by our team. However, after 1.5 years of self-funding, we genuinely need support from W3F to continue building products in the ecosystem.

**Comment by keeganquigley** [comment]
Hi @andrwlt thanks for the application. One question I have off the bat: is the Apple Passkey system open-source?

**Comment by andrwlt** [comment]
Hi @keeganquigley
Thank you for your question. I recognize your concerns regarding our reliance on Apple Passkeys due to its closed-source nature. However, I'd like to clarify that Pass3 is designed to utilize Passkeys in general and is not exclusively tied to Apple Passkeys, though it is compatible with Apple devices. These Passkeys are founded on the WebAuthentication (often referred to as "WebAuthn") standard, leveraging public key cryptography. This ensures that Pass3 is compatible with any device that has implemented the WebAuthentication standard. For more information on this standard, please refer to:
- https://www.w3.org/TR/webauthn-2/
- https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API
- https://support.apple.com/en-vn/HT213305

**Comment by keeganquigley** [comment]
Hi @andrwlt sorry for the late reply:

- Thanks for clarifying, yes I think that's fine as long as your app will be compatible with other systems based on the WebAuthn standards. I think it's great to be able to implement features like login in via Apple TouchID.
- Will the registered email address be encrypted?
- What type of encryption will be used for the cloud backup? For [example](https://www.coinbase.com/blog/backup-your-encrypted-private-keys-on-google-drive-and-icloud-with-coinbase), Coinbase uses AES-256 GCM
- I agree that the price seems high compared to similar proofs-of-concept. Would you be willing to remove some of the optional features such as the cloud backup and the custom wallet profile? Perhaps that could allow for a smaller scope focusing mainly on the passkey system.
- We don't usually care too much about the GH actions since we don't fund getting code production ready. So it's probably safe to remove this or add it to the 0c. testing and guide deliverable.

**Comment by keeganquigley** [comment]
Thanks @andrwlt for the thorough answers. Yes, I think I'd personally be more apt to approve it if milestone 3 was omitted and moved to a follow-up grant. That way we can see the core implementation in action first, before all the additional features are implemented. Let me know if this works for you.

**Review by semuelle — APPROVED** [review]
Thanks for the update, @andrwlt. Happy to support your proposal.

**Review by keeganquigley — APPROVED** [review]
Thanks for the updates @andrwlt much appreciated. LGTM.

**Comment by andrwlt** [comment]
@semuelle @keeganquigley Thank for your supports.

**Review by takahser — CHANGES_REQUESTED** [review]
@andrwlt, apologies for the delay on my end.

A few points and questions for clarity:

- I've noticed that this proposal bears resemblance to the [hashed-wallet](https://github.com/hypha-dao/hashed-wallet) mobile app which also received a [grant](https://github.com/w3f/Grants-Program/pull/1001) and has been delivered. It might be beneficial to address this in the [Ecosystem Fit](https://github.com/w3f/Grants-Program/pull/1001) section, highlighting the differences in your solution.
- Considering the similarities with the hashed wallet, perhaps it's worth looking into reusing their implementation? You could explore forking or even collaborating with the grantee, given that their repo hasn't had recent activity since March.
- Could you share the long-term vision for this project? Do you see the team maintaining it post-grant? If so, what drives that intention?
- In a previous [comment](https://github.com/w3f/Grants-Program/pull/1886#issuecomment-1687614005), you referenced a "month-long user research". Is it possible to share some insights from that study? A private share would work if public disclosure isn't feasible.
- Regarding your team's proficiency: What experience do you hold in web UIs or, more pertinently, mobile apps? The lo-fi wireframes are a good start, but any validation of your capability would be appreciated.

**Comment by andrwlt** [comment]
hi @takahser, thank you for your inquiry. To address your questions:
- While some teams have received grants for the social recovery wallet, and the hash wallet may resemble ours, our objectives differ. Our focus is on addressing the complexities crypto wallets pose for average users by introducing a keyless wallet, as detailed in our application. Although the hash-wallet team utilizes Flutter, we intend to develop ours as a Progressive Web Application. This approach ensures that users aren't required to install anything while still enjoying a seamless experience. While we can gain insights from the hash-wallet's approach, forking the project doesn't align with our vision.
- Our journey has been marked by trials, errors, and lessons. After our previous grant, we directed our efforts towards [Libra](https://golibra.xyz), an off-chain payment infrastructure for the Polkadot System. Upon market introduction, we identified the challenges everyday users face with cryptocurrencies, especially those unfamiliar with Web3. This led to our renewed mission: **simplifying Web3 for everyone**. Pass3 is our initial effort towards this, aiming to streamline user onboarding to Web3. Following its beta release, we aim to gather user feedback to further refine Pass3. Our vision includes exploring gas-less transfers and wallet linking, but future developments will be heavily influenced by user feedback.
- You can find preliminary details of our project research [here](https://www.figma.com/file/wOIf8C9YQzy6vWQd7Q8MTE/Pass3?type=whiteboard&node-id=1-167). However, please note that it might be disorganized and may not encompass all our offline discussions.
- To validate our team's expertise, kindly check out our latest product at: https://golibra.xyz/. I also provided the team experience information in the application.

Please let me know if I am missing anything else.

**Review by takahser — CHANGES_REQUESTED** [review]
@andrwlt honestly for a wallet application with passkey integration that would only work on mobile anyway I see more value in a native mobile application, due to several advantages such as native push notifications, biometric authentication access (fingerprint/face id), enhanced offline usage, app store visibility and general device integration, also potentially with other wallet applications.

I reached out to the maintainers of hashed wallet and they'd be very happy to collab with you guys. I think there is much more value in streamlining the development efforts and building on the existing code base to enhance this native app, rather than rewriting everything. Personally, I'd be very interested to support a joint-effort like that, but I'm not really keen on supporting the current proposal.

**Review by Noc2 — CHANGES_REQUESTED** [review]
I think @takahser proposal makes a lot of sense. Have you considered working together with another wallet provider in the ecosystem?

**Comment by takahser** [comment]
@andrwlt

> However, at this time, our team is hesitant to partner with others due to potential challenges arising from our team culture and workflow. 

Just to be clear, your team would most likely be the main contributor to that project for the scope of the passkey feature. So I don't think there should be any challenges of that nature. If you're interested I can make an Element group and discuss with the other team there to clear up any questions.

**Comment by andrwlt** [comment]
hi @takahser, thank for clarifying. I've sent you a message on Matrix.

**Comment by takahser** [comment]
Closing this, as demanded by @andrwlt on Element.
For transparency: They decided to pivot and will be back with a new proposal soon.
@andrwlt feel free to link this PR in the new proposal, once you open the PR 👍

**Comment by andrwlt** [comment]
Thank you @takahser. We greatly value the council's evaluation, feedback, and support 🙏

**Pull request closed without merging**
