### PR TITLE
Xcmsend Application

### PR DESCRIPTION
**Pull request by flipchan**
#### Project Abstract

> XCMSend aims to be the seamless way to interface with chains via XCM, designed to provide an unbiased platform, and user-friendly cross-chain message transfers within the Polkadot ecosystem. Think of a no-code layer to compose transactions.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by flipchan** [comment]
I have read and hereby sign the Contributor License Agreement.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Some quick initial feedback. We don't pay teams in DOT. Could you update the application accordingly, see https://github.com/w3f/Grants-Program#pencil-process?

**Comment by flipchan** [comment]
@Noc2 ty for the fast response, the application has now been updated to use USDT on polkadot, after the guidelines found here:
https://github.com/w3f/Grants-Program#pencil-process

**Review by semuelle — CHANGES_REQUESTED** [review]
Thanks for the application, @flipchan. 

- I think it makes a lot of sense to have a basic, standalone XCM transfer UI, but , are you familiar with [Talisman's "transport" functionality](https://app.talisman.xyz/transfer/transport)? It seems to be doing most of what you are planning. 
- Would you consider adding more wallets to M1? The polkadot.js extension is not beginner friendly, which I believe you are trying to be, so I think it would make sense to consider enabling other wallets as well. 

In any case, I will share the application with the rest of the committee.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update here. I personally have one big concern here: I don't think it makes sense to have a separate UI for cross-chain transfers. This is, in my opinion, something that should be supported by the different wallets. (Somers) Users are ideally not even aware in the future that they have to interact with different chains. Therefore, I won't support the application, but the rest of the committee might have a different opinion.

**Comment by decentration** [comment]
Thanks @semuelle, we will add Talisman as well as Subconnect in M1.

@Noc2 Hi David, it's true (we agree) xcm should be abstracted away for consumers, perhaps we can be better in our communication of the vision. 

We are not trying to build a wallet, instead we are aiming toward building a low-code drag and drop canvass UI that gives non-technical designers, as well as technical developers, a birds-eye-view interface to design workflows that xcm enables, i.e. teleport, swap and all the novel features from chains, such as: governance, time/price scheduling, DAOs, and all the pallets and primitives connections with workflows that are yet to be realised. "Like a Zapier for Substrate".   

Users can design transaction flows and use them in their own DApps.

Eventually the name might change but for simplicity, we are naming it with what it will do in the short term, because we don't want to spend any time right now on naming. 

Here is a near term vision mockup for how the drag and drop UI will look. 

XSDnD
It's a nodal canvass so the user can build diagrams, putting together workflow scenarios made up of pallets from different chains. Anything that is connected by hrmp/xcmp. Users can come up with useful permutations that might be harder to see without this kind of interface.  

XS-StatusUpdated
And when you pair that with real-time updates all in one place, the user will enjoy testing transactions, and become more effective at building the next generation of DApps. And this vision is aligned to the concept  of Cores, an application layer on top of Relay/Parachains, where apps will be leveraging parts of different chains. 

so just to clarify we aren't trying to push XCM onto consumers.

**Comment by flipchan** [comment]
Thanks for the comments!

I have updated the application to explain our vision better, which is to be a easy to use gateway for XCM transactions. 


@semuelle I agree with you, the average let's say defi users is probably most likely using subwallet, talisman or even metamask for evm compatible chains. We have changed M1 to support the most used browser wallets in the dotsama ecosystem, including Talisman and Subwallet. 


@Noc2 Their are several wallets/parachain projects that provide a basic xcm cross chain transfer functionality, but only in a limited way. With XCMSend we want to auto index and support all open channels, letting the network decide what routes are open for the end user. Instead of Cherry-picking 1-6 chains and supporting that. A focus on the Non-bias XCM transactions. As mentioned in the updated application, we want to provide a easy to use gateway into XCM for everyone, web2 companies and client libraries, dapp developers, parachain teams that want to test that their XCM send token functionality is working on Rococo. The vision is to allow a broad usergroup to interact with the dotsama ecosystem using XCM in a hassle-free way.

If I can answer any more questions, don't hesitate to poke me.  Also, we have a presentation of XCMSend, if anyone is interested I can send over the link to it, lmk.

Thanks!

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. I have a few follow-up questions: Which XCM version(s) are you planning to support? And is there a reason why you only want to support Rococo as part of this grant?

**Comment by flipchan** [comment]
@Noc2 certainly, 

The reason behind launching on Rococo is to:
1: Provide a sandbox/playground enviroment where connected connected parachains and users can test XCM functionality. 

2: Our goal and roadmap is currently to first launch on Rococo, make sure XCMSend is stable, later launch on Kusama and then finally go to Polkadot. Allowing us to gain feedback from the community during each step of the way, so we can shape XCMSend to as useful as possible. Taking in user feedback on the way.     
Roadmap WIP

**Review by semuelle — APPROVED** [review]

**Review by BenWhiteJam — APPROVED** [review]

**Review by Noc2 — APPROVED** [review]

**Pull request merged**
