### PR TITLE
Root

### PR DESCRIPTION
**Pull request by stated-tech**
#### Project Abstract

Root is a common good initiative that aims to improve on-chain governance by addressing issues such as low voter participation, lack of oversight, and siloed knowledge. It is built around a collective creation and decision-making system and aims to standardize proposal-making processes for the Substrate ecosystem.

With a composable voting system inspired by Borda's Count, it allows contributors to create proposals (preferendums) and to facilitate low-level consensuses from initiating teams.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`root.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. One quick initial feedback: could you please not delete the application template as part of the PR? Apart from this, please keep in mind that each contributor needs to sign the terms and conditions, and sometimes it takes a little longer for the bot to update the message here.

**Comment by keeganquigley** [comment]
Thanks for the application @stated-tech in addition to the comments above:

- We typically ask for mockups/wireframes for front-end focused milestones. Do you have any you can provide in the application?
- We only fund work that doesn't exist yet, so you can go ahead and remove the [0f. Research](https://github.com/w3f/Grants-Program/pull/1626/files#diff-9a36de09faa28e0f32a4c88570ff250b3d19a6e93b82fed8a8f7589657051848R318) deliverable since it is marked as completed.
- We don't fund marketing costs, so for example we can't pay for the logo creation/design. Could you remove [this deliverable](https://github.com/w3f/Grants-Program/pull/1626/files#diff-9a36de09faa28e0f32a4c88570ff250b3d19a6e93b82fed8a8f7589657051848R339) from milestone 2 and reduce the costs/scope accordingly? 
- Could you add the front-end framework you plan to use in the root.js module? (React, Vue, etc.)
- The planned [custom quorum](https://github.com/w3f/Grants-Program/pull/1626/files#diff-9a36de09faa28e0f32a4c88570ff250b3d19a6e93b82fed8a8f7589657051848R320) has an interesting design. Could you briefly describe the benefits to using it over the [adaptive quorum biasing](https://polkassembly.medium.com/adaptive-quorum-biasing-9b7e6d2a2261) model that Polkadot uses?

Thanks!

**Comment by stated-tech** [comment]
Hello everyone and many thanks for your feedback.

1) We have not made any mockup/wireframe yet because it's meant to be part of milestone 2 and we're first focusing on the Substrate pallets. Yet, we'll use Polkassembly's components for our Design System and discussed the User Flow & User Experience with Polkassembly many times.

2) We can delete the Research part, yet it has been a huge part of our R&D job and took us several months of work so we thought adding it was worth it (as discussed during a preliminary call between @monsieurbulb and @laboon).

3) No problem, marketing will be removed, but we'll keep roadmap updates and educational articles as part of our deliverables.

4) @product-polk should add this info very soon.

5) This quorum is specially custom-made for preferendums and our user flow. Our approach is an optimistic one when it comes to the writing phase: anyone can write subjects and alternatives to any proposal, except if enough people put their veto. When the voting phase comes, a quorum is then pessimistic: there it looks like the usual Quorums used in Polkadot, basically meaning a threshold to reach. Overall, this quorum is installed via the preferendum pallet and can only interact in the context of preferendums and has nothing to do with a multi-sig, proxy, or treasury proposal.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. But you are still changing our template with this PR. Could you update this? Also, we don’t fund the deployment or hosting of software, since it’s not useful for others. I would also remove the “Roadmap updates.” for the same reason.

**Pull request closed without merging**
