### PR TITLE
Refresh open-node grant

### PR DESCRIPTION
**Pull request by h4x3rotab**
This PR aims to give a refresh of the open-node-framework grant.

### CODE REVIEW

**Comment by alxs** [comment]
Thanks @h4x3rotab. A few comments:

- Are all of the features you want to implement not present in `polkadot-deployer`, and otherwise could you specify which are and which aren't (especially the list under "Open Node Framework wants to feature"?
- Is the grant still related in any way to your Open Node MVP? You say you want to work on a fork of `polkadot-deployer` but the document still mentions the former in multiple places (e.g. "we are going to expand Open Node Framework in aspects...").
- The link on line 49 is broken. Where is that repository?
- Looping in @ironoa who is maintaining `polkadot-deployer` in case he wants to add anything, in particular on contributing to upstream.

**Comment by h4x3rotab** [comment]
Oops, made a mistake. Now reopening

**Comment by alxs** [comment]
Thanks. Could you avoid force-pushing, so we can more easily see changes, from now on?

**Comment by h4x3rotab** [comment]
Replied in-line:

> Thanks @h4x3rotab. A few comments:
> 
> * Are all of the features you want to implement not present in `polkadot-deployer`, and otherwise could you specify which are and which aren't (especially the list under "Open Node Framework wants to feature"?

Slightly adjusted the deliverables table, and marked the features with "addition" or "integration" to address the relationship with the upstream.

> * Is the grant still related in any way to your Open Node MVP? You say you want to work on a fork of `polkadot-deployer` but the document still mentions the former in multiple places (e.g. "we are going to expand Open Node Framework in aspects...").

We have decided to not continue to work on the MVP repo. Instead, we have forked polkadot-depoyer here (https://github.com/Phala-Network/open-node-deployer) and will cherry-pick some of the existing code when necessary.

> * The link on line 49 is broken. Where is that repository?

It's a private repo, shared with the reviewers in the past. I can add you to the viewer if required.

**Comment by alxs** [comment]
Thanks, looks good! As far as I understand you have one person mainly working on this - could you adjust the FTEs (should be 1)?

And yes please, I would be happy to have a look at the MVP.

**Comment by h4x3rotab** [comment]
> Thanks, looks good! As far as I understand you have one person mainly working on this - could you adjust the FTEs (should be 1)?
> 
> And yes please, I would be happy to have a look at the MVP.

The staffing is rather flexible. We have one FET who leads a team of 4. Do you intend to change the amount of the grant? I think the work loads match the proposed amount, and actually the proposed budget is already very tight from our end. We just want to be more focus. So we don't want to re-negotiate the amount.

**Review by alxs — APPROVED** [review]
Sounds good and no, the amount seems fine. Thanks for sharing the repo. I'll share the amendment with the rest of the team.

**Review by Noc2 — APPROVED** [review]

**Review by semuelle — APPROVED** [review]
Sounds good!

**Pull request merged**
