### PR TITLE
Amendment to initial contract

### PR DESCRIPTION
**Pull request by lumena-tech**
Amendment to initial contract to change the payment address for milestone 3.

### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying?

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] I have read and understood the [FAQs](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md), [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md) and [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md).
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).
- [ ] I prefer the discussion of this application to be in a private Element/Matrix channel. My username is: ``@_______``

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] Hackathon
- [ ] Personal Recommendation
- [x] Substrate Builders Program
- [ ] Investor/VC
- [ ] Online Search
- [ ] Other: _______

### CODE REVIEW

**Comment by semuelle** [comment]
Thanks. That is the same address as previously, though? It should match the one in the invoice. Or the other way around.

**Comment by lumena-tech** [comment]
I let the initial address because the first payments have been made ont it. I've added the new address just after : 
**Payment Address:** DAI(ERC20) 0x8cbc9b6191c1bba1652d51ae73f7c15f485a1c72. Payment address for Milestone 3 : DAI(ERC20) 0x8cbc9b6191c1bba1652d51ae73f7c15f485a1c72

**Review by Noc2 — APPROVED** [review]

**Review by Noc2 — CHANGES_REQUESTED** [review]
Oh, I just noticed that you have the same address twice. It’s always 0x8cbc9b6191c1bba1652d51ae73f7c15f485a1c72 Could you change this?

**Comment by Noc2** [comment]
You probably wanted to add 0x8c810c87124c836802412dbbc42c5d6a8027dffc instead

**Comment by hakan-w3f** [comment]
Hi @lumena-tech , would you kindly update the invoice for W3F to proceed with the payment? Thanks.

**Comment by lumena-tech** [comment]
Hi,

The  address in the invoice is the right one. We have updated the contract.

Best regards,



-------------------------

Fabrice Croiseaux

Président

Lumena

2 rue Maurice Barrès

57000 METZ FRANCE

Mobile : +33 6 42 06 23 43

***@***.******@***.***>

https://www.linkedin.com/in/fcroiseaux/

http://www.lumena.tech


Les informations contenues dans cet email peuvent être confidentielles ou protégées par des lois en vigueur. Elles sont à l'attention des destinataires uniquement. Les données nominatives éventuelles ne peuvent être communiquées à des tiers par le récepteur de cet email.

Si vous n'êtes pas le destinataire principal, ni un des destinataires placés en copie, la divulgation, la copie, la diffusion ou toute autre utilisation de cet email est prohibée et peut être illégale. Dans ce cas, merci d'avertir l'émetteur immédiatement et de détruire cet email.

P Please consider the environment before Printing this email


Le 16 mai 2022 à 10:16:47, hakan-w3f ***@***.******@***.***>) a écrit:

Hi @lumena-tech<https://github.com/lumena-tech> , would you kindly update the invoice for W3F to proceed with the payment? Thanks.

**Review by Noc2 — CHANGES_REQUESTED** [review]
@lumena-tech  But neither the contract nor this amendment contains this address **0x8c810c87124c836802412dbbc42c5d6a8027dffc** (= address in the latest invoice). Could you please update this amendment?

**Comment by semuelle** [comment]
ping @lumena-tech.

**Comment by adetante** [comment]
Hi @Noc2, thanks for your comment.
We have fixed the PR with the right address in the contract (`0x8c810c87124c836802412dbbc42c5d6a8027dffc`)

Looks good now 👍

**Review by Noc2 — APPROVED** [review]
Perfect. Thanks!

**Review by alxs — APPROVED** [review]

**Pull request merged**
