### PR TITLE
Koi Metaverse

### PR DESCRIPTION
**Pull request by li-yuan**
### Project Abstract

> Koi Metaverse aims to unlock the next-gen GameFi metaverse economies and it is building the digital collectibles platform for virtual GameFi NFTs. It is a fish collection blockchain game that combines token economy and NFT assets. It consists of a series of smart contracts, and all of the in-game assets belong to its players. Players can play to earn by collecting high mining power fish and growing them, creating a positive self-circulation.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Comment by semuelle** [comment]
Hi @li-yuan, thank you for your application! We will look into it as soon as possible.

Could you clarify the specifications of deliverables 5a and 5b? There is currently only a link to existing assets. Also, have you considered implementing some of this functionality in ink? At first glance, it looks like all your deliverables could be done as smart contracts.

**Comment by li-yuan** [comment]
> Hi @li-yuan, thank you for your application! We will look into it as soon as possible.
> 
> Could you clarify the specifications of deliverables 5a and 5b? There is currently only a link to existing assets. Also, have you considered implementing some of this functionality in ink? At first glance, it looks like all your deliverables could be done as smart contracts.

5a, 5b We have completed part of it, and we will continue to complete the rest. They game and front-end design of the project.

In terms of the gaming NFT protocols (Lottery Draw, Auction, Minting), we may develop them as substrate modules and pallets.

The game and Dapp functions will be definitely implemented in ink! smart contract platform.

**Comment by semuelle** [comment]
Thanks for the update. Could you still add a description/specification for those deliverables (5a & b) to the document, so we know what to expect? You can leave the link.

**Comment by li-yuan** [comment]
> Thanks for the update. Could you still add a description/specification for those deliverables (5a & b) to the document, so we know what to expect? You can leave the link.

We have updated the desciption of 5a & 5b. Our previous work and progress is added into the main contents of our proposal.

**Review by semuelle — COMMENTED** [review]
- Does (anyone on) your team have any public code repositories that show experience in open source development and maintenance?
- The game is just breeding fish, correct? There is no competition or multiplayer aspect?
- What does `mining power` refer to in the case of `high mining power fish`?
- `you can lock [...] mine the governance token, and use it to participate in the other DeFi activities` - what activities does this refer to?

**Comment by li-yuan** [comment]
> Regarding the nft module, did you take a look at other existing nft implementations: https://github.com/w3f/Grants-Program/blob/master/docs/polkadot_stack.md#link-chains-and-pallets Maybe you can potentially use them for your project. See for example https://github.com/danforbes/pallet-nft. How do you plan to implement randomness for your lottery module?

Koi's nft conforms to the Ethereum erc721 protocol. If the community already has a similar implementation of erc721, we will refer to or do secondary development on the basis of it, and add the interfaces required by the koi game.
We will carefully evaluate the workload and risks of completely implementing it ourselves and secondary development on the basis of other open source projects in the community. In addition, we will directly use Randomness for random numbers.

**Comment by li-yuan** [comment]
> * Does (anyone on) your team have any public code repositories that show experience in open source development and maintenance?
> * The game is just breeding fish, correct? There is no competition or multiplayer aspect?
> * What does `mining power` refer to in the case of `high mining power fish`?
> * `you can lock [...] mine the governance token, and use it to participate in the other DeFi activities` - what activities does this refer to?

Our team has been developing commercial games for a long time, and we have a strong interest in open source projects, but there are currently no public repositories.

The first stage of the game is mainly to develop gameplay. This is mainly considering that there are still many technical problems to be solved in the realization of massively multiplayer online games on the blockchain. We will continue to explore the technology and will design subsequent versions of the game. Provide more possibilities.

Power is the attribute of fish. It determines the mining ability of fish. The larger the value of power, the stronger the mining ability of fish. The value of power is determined by fish's genes.

The token obtained from the game can be used in koi's defi project.

**Comment by li-yuan** [comment]
> 



> > we will directly use Randomness for random numbers.
> 
> Does this refer to Substrate's `Randomness` trait?

Yes.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Sorry for the late reply here. I really think it’s not mandatory to develop a new implementation of erc721 and it would be nice if you could remove this from the deliveries. There are already existing implementations, see above. Additionally you could potentially use https://github.com/paritytech/substrate/tree/master/frame/uniques, which is already deployed on kusama. Furthermore, your application still mentions substrate modules and no ink! smart contracts. Where can I find out more about your DeFi project? Also, in general I would be more willing to accept this application, if you combine it with a tutorial that shows others how to develop their own (similar) games with substrate or ink!.

**Comment by li-yuan** [comment]
> Sorry for the late reply here. I really think it’s not mandatory to develop a new implementation of erc721 and it would be nice if you could remove this from the deliveries. There are already existing implementations, see above. Additionally you could potentially use https://github.com/paritytech/substrate/tree/master/frame/uniques, which is already deployed on kusama. Furthermore, your application still mentions substrate modules and no ink! smart contracts. Where can I find out more about your DeFi project? Also, in general I would be more willing to accept this application, if you combine it with a tutorial that shows others how to develop their own (similar) games with substrate or ink!.

thank you very much! I spent a week researching your suggestions and testing the https://github.com/paritytech/substrate/tree/master/frame/uniques project. I think I should do what you said.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update and integrating ink! smart contract. Could you maybe also integrate some tutorials? Independent of it, I suggest removing milestone 2 for now. I think it will be fairly easy to get the necessary approval for milestone 1 at this stage and we can always sign a follow-up grant for milestone 2, once you successfully complete milestone 1.

**Comment by li-yuan** [comment]
> Thanks for the update and integrating ink! smart contract. Could you maybe also integrate some tutorials? Independent of it, I suggest removing milestone 2 for now. I think it will be fairly easy to get the necessary approval for milestone 1 at this stage and we can always sign a follow-up grant for milestone 2, once you successfully complete milestone 1.

I revised the plan. I would love to share our project with the community. I will write a tutorial to share our development results.

**Review by Noc2 — APPROVED** [review]
Thanks for the update. It looks good to me. I will share it with the rest of the team.

**Review by semuelle — APPROVED** [review]

**Review by mmagician — APPROVED** [review]
Sure, why not, I like fish :)
Just one comment after entering your "dapp": before I was able to do anything, it asks me to unlock my wallet. In my opinion it's really bad practice to require users to unlock/reveal their accounts, unless they are actually performing meaningful actions (e.g. viewing their balances or signing transactions). Please try to avoid it for the Polkadot version.

**Comment by semuelle** [comment]
Hey @li-yuan & @koinft. Are you still working on this grant? I don't see any activity on Github and your milestone was planned for March, if my calculations are correct. Would you mind providing an update? You are free to amend your grant contract with an updated timeline if you need more time.

**Comment by alxs** [comment]
@li-yuan @koinft any updates? Please note that if we don't hear from you within the next two weeks, we'll assume you're no longer interested and go ahead and terminate the grant.

**Pull request merged**
