### PR TITLE
propose pallet-ordinals

### PR DESCRIPTION
**Pull request by aa3ron**
#### Project Abstract

This project builds a utility substrate pallet to index RUNE UTXOs of bitcoin. It allows any parachains or substrate solochains to index RUNE UTXOs in their runtime using offchain worker.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`pallet-ordinals.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (Polkadot AssetHub (DOT, USDC & USDT) address in the application and bank details via email, if applicable).
- [x] I understand that an agreed upon percentage of each milestone will be paid in vested DOT, to the Polkadot address listed in the application.
- [x] I am aware that, in order to receive a grant, I (and the entity I represent) have to successfully complete a KYC/KYB check.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@build_at_night:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by Arraon-rgb** [comment]
> I have read and hereby sign the Contributor License Agreement.

I have read and hereby sign the Contributor License Agreement.

**Comment by Arraon-rgb** [comment]
I have read and hereby sign the Contributor License Agreement.

**Review by semuelle — COMMENTED** [review]
Hi @aa3ron, thank you for the application and sorry for the late reply. I appreciate that you are upfront about the lack of previous open source work. I also see that you have already done quite a bit of work on the pallet already and you are willing to take 100% vested DOT payment. 

Can you explain the background of this project? What is your motivation to implement this? Are you planning to use it in future projects?

**Comment by aa3ron** [comment]
> Hi @aa3ron, thank you for the application and sorry for the late reply. I appreciate that you are upfront about the lack of previous open source work. I also see that you have already done quite a bit of work on the pallet already and you are willing to take 100% vested DOT payment.
> 
> Can you explain the background of this project? What is your motivation to implement this? Are you planning to use it in future projects?

Thanks for feedback. Maybe I didn't describe this project very clear. I'll add some explain here then update the markdown.

The Rune protocol is popular in BTC ecosystem but it relies on the centrailized indexer to track all UTXOs, i.e. people or some services couldn't just use the BTC RPC node to comfirm the Rune transactions but require an extra component, that is the Rune indexer. But how to make the indexer trustless? no way but make it decentrailized. We believe that substrate is the best choice to implement this. 

About the future plan, it could be used as a reliable indexer for any BTC bridge projects or parachains that want to bring Rune into their ecosystem. Maybe we will develop a BTC layer2 based on substrate supporting BTC & Rune natively but I can't make a guarantee right now since it is a huge project :)

**Comment by PieWol** [comment]
Hey @aa3ron ,
thanks for elaborating further. Have you identified a need for this project that isn't based on your own views? Are there people that would enjoy this kind of decentralized indexer? Do you have a model in mind that would make it economically attractive to run this service as a node provider? Are there any commitments by relevant players in the rune / ordinals community that would enjoy following this web3 vision of decentralized infrastructure?

**Comment by aa3ron** [comment]
> Have you identified a need for this project that isn't based on your own views? Are there people that would enjoy this kind of decentralized indexer? 
Not yet. 

> Do you have a model in mind that would make it economically attractive to run this service as a node provider? 
We'd like to just provide such a tool/component rather than an online service. That's why this proposal is`pallet-ordinals`. But if someone developments a BTC <> substrate bridge or BTC layer2 supporting RUNE, it makes sense to charge a bridge fee for each transaction. 

> Are there any commitments by relevant players in the rune / ordinals community that would enjoy following this web3 vision of decentralized infrastructure?
Honestly, I have no an idea about what does the rune/ordinals community think about the decentralized indexer because we don't know so much friends in this field. But I am pretty sure that decentralization does matters. If we could receive this grant, we'd love to demonstrate the indexer to rune communities. In my memory, there was a issue about the data-inconsistence between a CEX and the brc20 explorer. The decentralized indexer is the best solution.

**Comment by PieWol** [comment]
Thank you for elaborating. Given that we only recently funded a [bitcoin related grant](https://github.com/w3f/Grants-Program/pull/2304) that serves as a substrate showcase I would prefer grants that try to build on Polkadot and for the Polkadot ecosystem. So sadly I don't think this is a good fit for our grants program. The idea is really nice though and I think it's a great usecase for a substrate project. I hope you can get your project funded by the ordinals community.

**Comment by aa3ron** [comment]
> Thank you for elaborating. Given that we only recently funded a [bitcoin related grant](https://github.com/w3f/Grants-Program/pull/2304) that serves as a substrate showcase I would prefer grants that try to build on Polkadot and for the Polkadot ecosystem. So sadly I don't think this is a good fit for our grants program. The idea is really nice though and I think it's a great usecase for a substrate project. I hope you can get your project funded by the ordinals community.

Maybe this tool is suit for some other projects built on Polkadot, a BTC layer2 parachain of Polkadot - -
Thanks anyway :)

**Comment by PieWol** [comment]
Thats true, for any chains in the Polkadot ecosystem, that would like this kind of service, this would be a great piece of work. Let's see what my colleagues say. Maybe they have a different opinion and are convinced by your application.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the application and all the effort you put into it. However, the grants committee decided not to proceed with it since it's not a good fit for the current grants program that focuses on Polkadot and Kusama. Independent of this, we wish you all the best for your project. Let us know if you have any questions.

**Pull request closed without merging**
