### PR TITLE
Myriad Social Submission

### PR DESCRIPTION
**Pull request by gilangbh**
#### Project Abstract

Myriad Social is a decentralized, censorship-resistant social network that enables users to host their own social network without centralized control. Our application is built on top of the Myriad blockchain (currently as **[an appchain running on Octopus Network](https://oct.network/appchains)**), which gives it a number of advantages. Firstly, it is censorship-resistant, as there is no central point of control. Secondly, it allows sovereign control, as all data is stored within user-hosted instances with freedom to host.

The product proposition of myriad is as follows:
- Federated Free Speech: Myriad allows users to host their own social network and be part of the Federation. With self-hosting, users can set up their own server and invite others to join. This makes it possible for anyone to create their own social network, without having to rely on a central service.

- Decentralize Other Social Networks: Myriad Social's crowdsourced mechanism of importing social media posts means that Myriad Social users can follow people on centralized social networks without having an account there.

- Crypto Value Layer: Myriad  gives users the ability to aggregate posts from other social networks like Twitter (for now) and import them into the blockchain. This effectively turns each post into a tipping wallet, allowing mainstream social media users to receive cryptocurrency for their content.

- Own the platform: Myriad Social is a self-governing social media platform that is powered by $MYRIA token holders and users. This decentralized structure allows for a more democratic and fair governance system that is not centrally controlled.

Myriad is built to be interoperable. Our blockchain uses Substrate, a blockchain framework behind Polkadot made by Parity Technologies. Using Substrate allows Myriad to be more flexible, because it’s compatible with a multitude of other blockchains such as Octopus, Kusama, and Polkadot. On top of that, Myriad uses a federated architecture that was built with modularity in mind, meaning that all of the components of Myriad are extensible and treated like a bunch of building blocks that can be assembled any way you’d like.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [x] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@gilangbh:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the application. But aren't the [server](https://github.com/myriadsocial/myriad-node-parachain/tree/main/pallets/server) and [tipping] pallets already fully developed? Keep in mind we usually don't support the deployment as a parachain or getting a parachain slot in any way but rather focus on the development of new open-source software for our ecosystem.  So we would be much interested in supporting tools that you want to develop in the future and that are ideally also useful for others in our ecosystem.

**Comment by gilangbh** [comment]
> I'm closing the PR for now. Let me know if I should reopen it.

Hi Sir, thank you for your feedback earlier and apologies for not responding promptly as we had to discuss internally. I would like to ask that this PR be reopened, and with this message I also want to add a clarification for our submission.

For this particular grant request, we're focusing the activity to be more about explaining and documenting the migration experience from Octopus Appchain to become a parachain. As for the target deployment we are thinking of deploying it to Rococo.

I would understand if w3f is focused especially now on software and less on market impacts, so the migration of Myriad could be misconstrued as an effort to effect the MYRIA token. However, we are only targeting the initial deployment to Rococo, to allow Polkadot developers to get introduced and understand how the concept of decentralized+federated social network works, so that they can start building on top of our APIs. As such, the idea of pursuing a parachain slot is way beyond our scope.

In terms of pending work, we are mostly going to be working on the federation part after the migration. At first I was thinking of submitting the grant request fully until our targeted completion based on our full roadmap, but considering that it is going to need a considerable amount of funding, we decided to downscope and lower our target grant request.

I understand that there might be some confusion about which features are completed and to be developed, because by the time of writing our submission, our team was also experimenting with the code in parallel, my apologies. We plan to adjust our scope to fully focus on the migration process and UI/UX updates, if that is okay with you.

Thanks!

**Comment by Noc2** [comment]
Thanks for the quick reply here. I'm happy to reopen it, and feel free to update the PR. As I pointed out before, ideally, you try to focus on open-source software development that doesn't already exist in our ecosystem and that is potentially somehow useful for others (e.g., they can reuse it for a different project). These are usually the easiest grants to approve.

**Comment by gilangbh** [comment]
Thank you for reopening. I was wondering, most of the scope of the grant submission is about migrating from Octopus Appchain into Polkadot based; I am 100% sure that we are the first one to do that and this is going to benefit other appchains coming from Octopus to Polkadot/Kusama/Rococo.

At the same time, we are bringing the concept of decentralization+federation with the actual product being migrated. I believe this is something that developers can learn and build upon.

With that in mind, does this submission qualify as useful and reusable?

**Comment by Noc2** [comment]
Yes. For example if you need to develop something for the migration/make certain changes to the code and document this in a proper way, it is helpful for others. The same is true for most newly developed other tools.

**Comment by gilangbh** [comment]
Thanks. My last question, since we are going to undergo the actual migration process, and not just the documentation, I want to structure our grant request as follows:
1. Migration process: infra, code changes
2. Documentation
3. Native polkadot currency integration
4. UI/UX updates to properly reflect the post migration product presentation

Is it advisable to structure the grant request this way? Thank you for your time replying here, I appreciate it.

**Comment by Noc2** [comment]
In general, yes. But regarding tokens, please only focus on the technical details and ideally don't mention any specific tokens as part of the application. Also, each milestone (in case you plan to deliver this as multiple milestones) should contain the [default deliverables](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#milestone-1-example--basic-functionality). So that we have some documentation to actually evaluate the deliveries, etc. And finally, the more specific the deliveries are, the better (e.g., programming language, etc.) ;-)

**Comment by gilangbh** [comment]
Thanks, we'll update and let you know if we have further question!

**Comment by keeganquigley** [comment]
pinging @gilangbh are you still planning to submit updates? Thanks!

**Review by Noc2 — CHANGES_REQUESTED** [review]
(some additional comments in the shared channel)

**Review by Noc2 — CHANGES_REQUESTED** [review]
(requested additional changes, in shared channel)

**Comment by keeganquigley** [comment]
@gilangbh see my comment in private channel.

**Review by Noc2 — CHANGES_REQUESTED** [review]
(Additional comment in the private channel)

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I'm happy to go ahead with it and mark it as ready for review.

**Comment by dsm-w3f** [comment]
I commented in the private channel.

**Review by semuelle — CHANGES_REQUESTED** [review]
See comments on Matrix.

**Comment by dsm-w3f** [comment]
I commented on the private channel.

**Review by nikw3f — APPROVED** [review]

**Review by semuelle — APPROVED** [review]

**Comment by gilangbh** [comment]
Hi everyone, here is our progress as of today:

We built and deployed the Myriad Social blockchain that uses Polkadot v1.0.0

We followed the steps to build a chain spec, WASM, and genesis file from: https://docs.substrate.io/tutorials/build-a-parachain/acquire-a-testnet-slot/#export-required-files

All the files can be found here: https://github.com/myriadsocial/myriad-node-parachain/tree/main/node/res

After modifying the chain spec and re-triggering the build to include it inside the Docker image here are our last results:

https://hub.docker.com/r/myriadsocial/myriad-node-parachain
https://hub.docker.com/r/dexamethazon/myriad-node-parachain
We got the collator running following this: https://docs.substrate.io/tutorials/build-a-parachain/acquire-a-testnet-slot/#start-the-collator-node

But we didn't manage to create a connection to it via RPC. We already opened the [ws-rpc.rococo.myriad.social](http://ws-rpc.rococo.myriad.social/). I'm still unsure if it's a Kubernetes problem or a Substrate problem...

From the Substrate side, we added the WS/RPC flags found in this document: https://docs.substrate.io/deploy/prepare-to-deploy/

We tried using telnet, it connected just fine. But when we tried to use polkadot.js.apps it failed to connect properly.

Also, the Parathread collator never really showed inside the polkadot.js.apps. If you go to the Rococo Parathread you can't see Myriad Social there after going down to ParaId 4242: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-rpc.polkadot.io#/parachains/parathreads

We would like to ask for some technical help, if we still are unable to solve this situation by today, we will submit the delivery documents by Tuesday, 3rd of October.

--

For our next updates, https://github.com/decentricity (our founder) will assist with providing updates to our PR

**Comment by Decentricity** [comment]
Hi all, Decentricity here the founder of Myriad. As mentioned by @gilangbh in his last message I will be providing updates on our progress here as well. I have good news and bad news.

**Good News: Infrastructure Setup complete and connection is secure**
image

Visible here: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fws-rpc-1.rococo.myriad.social%2Fwebsocket%2F#/explorer

**Bad News: Block Production Has Not Started (>12 hours)**

Command used to sync:
```
 /home/ubuntu/myriad-node-parachain/target/release/myriad --collator --chain /home/ubuntu/myriad-node-parachain/raw-parachain-chainspec.json --base-path /var/lib/myriad/ --port 50333 --rpc-port 9944 --unsafe-rpc-external   --rpc-cors all -- --execution wasm --chain rococo --port 50343 --rpc-port 9988
```

Results:
image

Based on our StackExchange searching, we found that this might be a common problem:

https://substrate.stackexchange.com/questions/4301/collator-nodes-are-not-working/4302#comment9580_4302

image



**Help Needed**

- We would like to reconfirm if this is a normal / common problem, or if we missed anything in our deployment. Our WASM build and chainspec can be found here: https://github.com/myriadsocial/myriad-node-parachain/tree/main/node/res
- We would like to note that the production of blocks is our only dependency in finishing Milestone 1 (we can't do the data migration without this last step) and we would only be able to submit our final delivery document when that is completed. (refer to #https://github.com/w3f/Grant-Milestone-Delivery/pull/1019 )

**Comment by Decentricity** [comment]
Updating the prior comment  #(https://github.com/w3f/Grants-Program/pull/1795#issuecomment-1744142204)
--> we have finished the Sync (after 5 days of syncing!) but the blocks are not being produced still.

We did go through the documents including https://substrate.stackexchange.com/questions/1394/our-parachain-doesnt-produce-blocks-checklist -- this has alerted us that the problem might be due to our current deployment only having one collator node.

so we updated the chainspec and we are currently deploying two collator nodes: https://github.com/myriadsocial/myriad-node-parachain/tree/main/node/res

As per informed by Santi Balaguer (onboarding team), we are just setting up a new head and wasm (without re-onboarding) as the Parachain is already unlocked, and then deploying the two collator nodes above.

**Comment by semuelle** [comment]
Thanks for the update, @gilangbh. I hope everything works out this time!

**Comment by Decentricity** [comment]
Hi everyone,

just wanted to give you an update on the progress on grant delivery. I'm glad to say that we have actually finished all items under Milestone 1 and Milestone 2, **except for items related to the block production issue**. Here's our internal Trello as an overview of finished tasks, with red and blue tasks being M1 & M2, and pink tasks being Milestone 3:

image

In the last few weeks we've been in contact with Santi Balaguer from the SquareOne team trying to get our chain to start producing blocks. Here's a chronology of events:

- Week 2 Oct: after the last update here -- https://github.com/w3f/Grants-Program/pull/1795#issuecomment-1752580885 -- we discovered that the blocks are still not being produced, with **both** peers online and syncing.
- Week 3 Oct: Santi highlighted to us that we do need to be a parachain to produce blocks, not a parathread. Additionally there was an issue with Rococo that required a fix -- which meant we needed to update from our v1.0.0 to v1.2.0. (This fix existed but needed to be deployed so before then v1.0.0 is nonworking: https://github.com/paritytech/polkadot-sdk/pull/1920 )
- Week 4 Oct: We have redeployed the chain in v1.2.0 and submitted PR to request for short-term parachain slot, and finally onboarded: https://github.com/paritytech/subport/issues/604#issuecomment-1779453938 ~ we then bought coretime based on ```onDemandBaseFee: 10,000,000``` which equates to 0.0001 ROC. Unfortunately our chain is still failing to produce blocks. Here are the logs from back then: 
image
image

- Week 1 Nov: We retried with ```1_000_000_000``` instead of ```10_000_000```. Santi confirmed that we have onboarded but still not producing blocks. Santi requested us to try running the collators locally and we complied. (We have previously tested locally but not with the newest version.)
- Present: Local chain is producing blocks in the local relaychain:

Collator RPC: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fws-rpc-1.parachain.myriad.social%2Fwebsocket%2F#/explorer

Relay Chain RPC: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fws-rpc-2.rococo.myriad.social%2Fwebsocket%2F#/explorer

Transactions also work:
image

We are attaching the logs here for your convenience:

[myriad-local-parachain.logs (2).txt](https://github.com/w3f/Grants-Program/files/13330000/myriad-local-parachain.logs.2.txt)

[myriad-local-validator-alice.logs (2).txt](https://github.com/w3f/Grants-Program/files/13329999/myriad-local-validator-alice.logs.2.txt)

[myriad-local-validator-bob.logs (2).txt](https://github.com/w3f/Grants-Program/files/13329998/myriad-local-validator-bob.logs.2.txt)

We would love to hear your thoughts on how to fix this issue so our Myriad.Social project can immediately deliver Milestone 1 and Milestone 2 to W3F and add value to the ecosystem.

**Comment by TheMayorOf9ja** [comment]
This is impressive 👏

**Comment by semuelle** [comment]
> Collator RPC: [polkadot.js.org/apps/?rpc=wss%3A%2F%2Fws-rpc-1.parachain.myriad.social%2Fwebsocket%2F#/explorer](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fws-rpc-1.parachain.myriad.social%2Fwebsocket%2F#/explorer)
> 
> Relay Chain RPC: [polkadot.js.org/apps/?rpc=wss%3A%2F%2Fws-rpc-2.rococo.myriad.social%2Fwebsocket%2F#/explorer](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fws-rpc-2.rococo.myriad.social%2Fwebsocket%2F#/explorer)

It seems these are currently down, @Decentricity?

**Comment by keeganquigley** [comment]
Hi @gilangbh how is milestone 3 coming along?

**Comment by semuelle** [comment]
Hi @agustinustheo, have you checked the "Technical" links in the wiki? There are some chatrooms for Substrate/Polkadot SDK, though the best place to ask questions mights still be the StackExchange.

I will reach out to some people to see if there is someone who could look into the Rococo issue.

**Comment by agustinustheo** [comment]
> Hi @agustinustheo, have you checked the "Technical" links in the wiki? There are some chatrooms for Substrate/Polkadot SDK, though the best place to ask questions mights still be the StackExchange.
> 
> I will reach out to some people to see if there is someone who could look into the Rococo issue.

Hi @keeganquigley @semuelle,

Just an update, we just finished moving our servers off Google Cloud and into our own self-hosted onpremise servers.

I have made an ParaId within the new Paseo Testnet and I'm looking into the docs to try to manage deploying a runtime there.

@gilangbh has also invited me into the group chat in Element.

**Comment by semuelle** [comment]
Thanks for the update, @agustinustheo. I also spoke with @SBalaguer yesterday, who promised to reach out again in case you still need help.

**Comment by keeganquigley** [comment]
Hi @agustinustheo just checking in since its been a month or so now :)

**Comment by agustinustheo** [comment]
> Hi @agustinustheo just checking in since its been a month or so now :)

Thanks for checking in we are trying still with Paseo, we already have `PAS` tokens but because they don't have a guide it is taking longer than expected.

**Comment by keeganquigley** [comment]
Hi @agustinustheo any updates?

**Comment by gilangbh** [comment]
> Hi @agustinustheo any updates?

Theo is still struggling with Paseo deployment, can we ask for some technical guidance, maybe on Element chat?

**Comment by agustinustheo** [comment]
FYI, @gilangbh @keeganquigley 

I got in contact with Hector from Paseo.

He gave me a link to the following support docs: https://github.com/paseo-network/support/blob/main/docs/rococo_migration.md

They just released this a month ago, on the 4th of June.

I will talk with him and try to finish this ASAP!

**Comment by agustinustheo** [comment]
Hi @keeganquigley, we finally figured out how to deploy on Paseo, and Myriad Social is now a Paseo Network Parachain!

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fws-rpc.paseo.myriad.social#/explorer

We're ParaID 4005.
image

**Comment by keeganquigley** [comment]
Awesome, congrats @gilangbh glad to hear it! As a reminder, when the delivery is ready it can be submitted here: https://github.com/w3f/Grant-Milestone-Delivery/pulls

**Comment by keeganquigley** [comment]
Hi @gilangbh just a reminder that if you want to get paid out for the delivery you will need to submit the delivery at the above repo. Thanks!

**Comment by semuelle** [comment]
pinging @gilangbh, @Decentricity & @agustinustheo

**Comment by agustinustheo** [comment]
Hi @semuelle and @keeganquigley 

Apologies for not responding, the team has been busy with projects other than Myriad Social at the moment.

We currently have finished most of the deliverables for Milestone 3 and we're going to submit an update to you guys soon.

Right now we're having an issue because our Paseo Parachain stopped running on our servers. We resolved it on our end and now we're going to work with the Paseo Network team in order to finish the grant program!

https://github.com/paseo-network/support/issues/74#issuecomment-2365843087

**Comment by semuelle** [comment]
Thanks for the update, @agustinustheo. Looking forward to it.

**Comment by agustinustheo** [comment]
> Thanks for the update, @agustinustheo. Looking forward to it.

Our Paseo Parachain is running.

I'm working on the documentation now, @gilangbh should be able to submit the recent Milestone either tomorrow or Friday.

**Comment by keeganquigley** [comment]
Thanks for the updates @agustinustheo still planning to submit this soon? :)

**Comment by keeganquigley** [comment]
pinging @gilangbh

**Comment by keeganquigley** [comment]
Hi @gilangbh reaching out again. Please note if we don't receive a delivery in the next few weeks we will terminate the grant due to inactivity. Thanks!

**Comment by gilangbh** [comment]
Hi Keegan. Thank you for the notice. We're wrapping up the documentations and will finish as soon as possible!
<https://aka.ms/AAb9ysg>
________________________________

**Comment by agustinustheo** [comment]
Hi @gilangbh @keeganquigley 

We have finished Milestone 3 and have the documentation ready. @gilangbh will submit the deliverables officially soon but the documents can be seen here:
- Documentation Milestone 3: https://github.com/myriadsocial/myriad-web/blob/main/docs/milestone-3-documentation.md
- Testing Guide Milestone 3: https://github.com/myriadsocial/myriad-web/blob/main/docs/milestone-3-testing-guide.md
- Dockerfile Milestone 3: https://github.com/myriadsocial/myriad-infrastructure/blob/main/linux/Dockerfile

Have a good weekend!

**Pull request merged**
