### PR TITLE
openPayroll proposal (#1592

### PR DESCRIPTION
**Pull request by rtomas**
#### Project Abstract

The objective of Open Payroll is to meet the needs of organizations that wish to make transparent payments during a given period.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by semuelle — CHANGES_REQUESTED** [review]
Thanks for the application, @rtomas. 

- The idea of putting payroll on-chain has come up in our program a few times. I can't remember any of them using ink! to implement it, but certainly pallets. Ventur and Societal come to mind. Perhaps you could look into some other projects that include payroll and point out how your approach is different.
- Companies usually don't like to publish any information on their spending, so putting it on-chain puts them at risk of someone deconstructing the data. Have you talked to any potential users about this?
- What are your long-term goals with this? Your `Future Plans` don't indicate that you are planning to make a business out of it, so how are you planning to support future development and maintenance?

**Comment by rtomas** [comment]
Hi @semuelle, thanks for your questions.

1- About the first question, Societal seems to be an amazing project that's covering different aspects of community management. In our case we are tackling the payment issue only. In one hand, our payroll contract is highly configurable, allowing users to set their own base amounts and multipliers, whereas some existing solutions may have fixed payment structures. In the other hand, we prioritize transparency and display all participants' addresses and multipliers, promoting trust and accountability within the organization. But that's only a single use case, our project could be able to cover DCA, payments for rents, etc.  

2- Yes, we understand that some companies may be hesitant to put financial information on-chain. However, we believe that the benefits of transparency and accountability outweigh the risks. We plan to work closely with potential users to address any concerns they may have. We put some examples (lines 15, 17 and 19 of the proposal) of different companies/collectives that are proud of being "open numbers" organizations. In cases similar to our model of devs that work together receiving some funds, it'll be great to have this tool to split the payment between them ;)

3- Our long-term goal with Open Payroll is to promote transparency and accountability in organizations of all types, from cooperatives to private companies, making it easy to use. While we are not planning to make a business out of it at first, we do plan to continue to develop and maintain the project. We are thinking of an Open Source model, that's why the license we choose it's GPLv3. So the tool will be available for all the community members to use freely, even if they want to make profit with it. Some ways we could move forward with Open Payroll are: 

*Open-source community*: One possibility is that the project could rely on the support of an open-source community of developers who are interested in the project's goals and are willing to contribute to its ongoing development and maintenance.

*Grants and funding*: Another option is that the project could seek out grants or funding from organizations that are aligned with its mission and values, such as those focused on promoting transparency and accountability in organizations. This could provide the resources needed to continue developing and maintaining the project over the long term.

*Monetization*: While the project's current plans are not intended to be a business, it is possible that the team could explore ways to monetize the project in the future, such as by offering paid support services or consulting services related to implementing the project in specific contexts.

If you have any other questions, don't hesitate to ask.

**Review by keeganquigley — CHANGES_REQUESTED** [review]
Thanks for the application @rtomas 

- How would the process work for DAOs that already have a treasury which they are paying people out of? Would they have to say, transfer funds once a month out of the main treasury into this one for payroll purposes?
- Are you aware of [token streaming](https://docs.sablier.finance/protocol/faq/token-streaming) projects like [Sablier](https://sablier.finance/) on Polygon? As it seems that real-time payments may be the future of on-chain payroll.
- Will there be functionality to accommodate DAOs that want to use multi-sig setups? Is it as simple as setting the multi-sig address as the owner?
- If the only way to spend the funds is by paying the beneficiaries, how would it work if something goes wrong? Say the contract owner accidentally transfers too many funds into the contract treasury. Or do you essentially allocate the payments to beneficiaries at the time of deposit, and then it is just a matter of them manually claiming?
- Are you planning on testing more than just happy paths? What kind of code coverage percentage will you aim to achieve?
- If you are using a test suite like Jest, can you add it somewhere in the application, preferably in the deliverables?
- Can you please add the tech stack (React, Next.js, ink!, etc.) into the delivery tables themselves, since these are the requirements for the contract.
- I agree that the price for M1 is a bit high considering the contract will be rather simple to start out with.

Thanks!

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. I have two additional questions: 
- What do you mean exactly by quality assurance or automatic testing in milestone 2? I assume that this will be something other than the unit tests. 
- Also, the delivery "containerized implementation" of milestone 2 seems to be the same as the docker delivery.

It may make sense to combine both milestones into a single milestone for 18k.

**Comment by rtomas** [comment]
@semuelle

1. We agree with you that the "open numbers" enterprises we're discussing may be just one small niche that could benefit from openPayroll but they are definitely not the only ones that will be able to take advantage of it.
We believe it's worth exploring these potential niches and considering how the project could be adapted to appeal to a broader audience.

2. We think that a pallet could be a great implementation for this problem, but on this stage we firmly believe that being a smart contract is the best way to test the concept, to get more adoption and to get feedback from the community to iterate and improve the project. On the other hand, to be a pallet would require that the entire chain gets updated to include it, which is not the case for smart contracts that can be deployed permisionless on any chain that supports them.

3. Regarding your other comments we have updated the application to clarify and meet the expectations.

@keeganquigley

1. DAOs that already have a treasury will need to transfer funds to the payroll contract. They can choose to send only the required funds to cover the specific payroll period or they can send more funds to cover future payroll periods. The contract will keep track of the funds that have been sent to it and will only allow the payees to claim the funds that have been allocated to the payroll period.

2. We are aware of the existance of token streaming projects. We don't know Sablier specifically, but we have researched other projects like [Superfluid](https://www.superfluid.finance/). We think that this is a great idea and we would love to explore how we could integrate it into openPayroll. We think that it could be a great way to allow the payees to claim their funds in real time. We have added this to our list of potential future improvements.

3. The functionality to allow multi-sig setups is already included by default. The contract could be owned by a native multi-sig or by a smart contract multisig.

4. We have added in the application an explanation that the owner can withdraw funds from the contract at any time. This is based on the assumption that the owner is a trusted entity such as a multi-sig, a DAO or a company.

5. The quality assurance process will definitely not only cover happy paths and expected use cases. We will test all critical functionality and scenarios that could arise potential issues or bugs.
We aim to achieve a level of testing that ensures the project is reliable and meets the desired quality standards.

6. 7. We have added the tech stack to the delivery tables.

@Noc2

1. We have improved the explanation on step 5 of the Project Details section. But to summarize, we will not only perform unit tests, but also automated end-to-end tests.
2. You are right, we have fixed that in the delivery tables.
3. We have combined both milestones into a single milestone for 20k.

Thanks @semuelle, @keeganquigley and @Noc2 for your feedback. We have updated the application to address your comments. Let us know if you have any other questions or concerns. We will be happy to answer them and improve the application to meet the expectations of the grants program.

**Review by keeganquigley — APPROVED** [review]
Thanks for the answers and the changes @rtomas I think this is a good use case for ink! contracts, happy to go forward with it, and looking forward to the delivery.

**Review by Noc2 — APPROVED** [review]

**Review by semuelle — APPROVED** [review]
> we firmly believe that being a smart contract is the best way to [...]

Completely agree. Much more versatile and too few teams take advantage of it.

**Pull request merged**
