### PR TITLE
Aryaverse - Decentralised Freelance Platform | Grant Application

### PR DESCRIPTION
**Pull request by Polkaverse**
#### Project Abstract

> Aryaverse is a decentralized freelancer platform that allows clients to find and hire freelancers for their projects. It supports smart agreement features b/w clients and freelancers, offers a self-governance system for dispute resolution, supports Stripe payments, and provides a portal to manage freelancers.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [ ] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for your application. However, we usually don't support writing a white paper as part of the deliveries since it's not helpful for others, and ideally, you already know the structure of the smart-agreement pallet when you apply for the implementation. Regarding the escrow pallet could you take a look at existing solutions, like https://github.com/herou/EscrowPallet/tree/eljo-prifti/escrow, and see if you can reuse them?

**Comment by Polkaverse** [comment]
Thanks @Noc2 for quick review. Yeah we know the flow of smart-agreement pallets when we apply for the implementation, But here in the milestone we are trying to structure the technical entities of the pallet like what all extrinsics, intrinsics we will use and what are the custom data types(struct, enums etc.) we need to define in-order to implement all the functionalities likewise we’ll define other things also. 
Thank you for sharing this code of escrow, this should help us in some ways to speed up the implementation part but we need to implement some functionalities on our own pallet like we’ll do all the contract part in smart-agreement pallet. Our escrow pallet can’t be fully similar to this. And for milestones I have updated that please take a look.

**Comment by keeganquigley** [comment]
Thanks for the application @Polkaverse a couple of additional comments:

- What kind of logic will the smart agreement pallet contain?
- Do you plan to partially re-use the escrow pallet while adding additional functionalities? In this case is it possible to reduce the scope/cost of milestone 2 down to what functions you will implement yourselves?
- We typically ask for mockups for the front-end designs. Are you able to provide some?
- What other payment mechanisms would be in place other than Stripe? For example could someone pay with crypto or stablecoins into the escrow account? Would you build integrations for popular wallet extensions? (Polkadot-JS, Talisman, Sub Wallet, etc.)
- I remember a few freelancer platforms that launched on Ethereum such as [Ethlancer](https://twitter.com/ethlancer) and [Blocklancer](https://twitter.com/blocklancer?lang=en), but these never took off and both appear to be inactive. So I worry about user adoption. What benefits would users have in using your platform over a Web 2 freelance platform?

**Comment by Polkaverse** [comment]
Thanks @keeganquigley for the review.

- The Smart- agreement pallet works closely with escrow pallet. The Smart- agreement pallet contains several functions like: 

  1. **Propose_agreement:** Propose an agreement to be signed and agreed upon.
  Checks:
        - If proposer is either the seller or buyer.
        - Place in ServiceAgreementProposals.
       
  2. **Approve_agreement:** Signs the corresponding Agreement proposal.
  Checks:

        - Check number of votes for agreement is below the threshold for approval.
        - If num of votes for agreement is met then enact escrow.
        
  3. **Complete_agreement:** Signs the corresponding Agreement as complete or finish.
    **Check:**
        - Can only approve if origin is one of the agreement participants.
**Action:**
        - If agreement is successfully completed then release the escrow amount.
        
  4. **Start_escrow_on_approved_agreement:** Pushes approved agreement through to escrow.
  **Checks:**

        -   Agreement is approved.
  **Action:**
      - Remove Agreement from Proposed Agreements and Cleanup Storage.
 
                          
  5. **Check_vote_info(Intrinsic):** Check the current vote info to take action and approve proposed agreement or update.
  **Checks:**

        - If agreement proposal already has votes necessary to pass.
        - If agreement proposal has enough votes to be approved.
      
  6. **Check_finished_agreement_info(Intrinsic):** Check the current vote info to take action and approve agreement as complete or update.
  Checks:
        - If agreement has enough approval to declare as complete.

According to the requirement checks, actions inside every function and some new functions may be increased.

- We can use very less code from the escrow repo which Noc2 has shared but we need to make the escrow pallet fully aligned with smart-agreement pallet. But yeah I have made some changes in milestone2 from the first release pls take a look.

- For now we are planning to use polkadot UI. In milestone 3 we’ll build the end-to-end frontend of our project. In that milestone if you want we can provide you mockup before starting the development.

- If we talk about the payment mechanism. Yeah, we will use crypto and stable coin payment along with the stripe payment. Stripe payment is basically for the users who are not much familiar with the coins so that our platform can give the smooth transition to the web2 users in the Web3 ecosystem. In coins, Initially we will start with the chain coin and a few other coins from our ecosystem like Dot. Moving forward we will scale it to multiple other coins to give payment flexibility to the user. And we will start with the polkadot JS  wallet later we will integrate the Talisman with our product.

- Advantages of using Aryaverse over other freelancer platforms

     1. We accept multiple payment mechanisms to give a smooth experience to the users as discussed above.
     7. We offer all types of jobs listed on our platform as Ethlancer and Blocklancer don't provide this feature.
     8. Our governance mechanism would be more accurate and efficient to resolve the disputes.
     9. Web2 platforms have control of most of the freelancing market, so individual freelancers stand little chance unless they have some highly unique skill that’s not available on any of these platforms.

**Comment by keeganquigley** [comment]
Thanks for your answers @Polkaverse I will go ahead and mark your application as ready for review and share it with the rest of the committee. In the mean time, a couple of additional comments:

- Can you add the above smart-agreement functions into the application? Preferably as part of the delivery table.
- We do usually ask for mock ups or wireframes to be provided up front, even if very basic. This shows good planning and in my opinion the front-end shouldn't be an afterthought. But we'll see what the rest of the committee thinks, since you are using Polkadot-JS until the last milestone perhaps we can make an exception.
- Web2 platforms have control of most of the market, as you mentioned. How will you ensure the quality of jobs posted and prevent spam?
- For a freelancer platform to be successful it will need to build a community. Do you plan to build forums or host a Discord server or something similar?
- Will you have a ranking system for freelancers who consistently do a great job vs those that don't?
- What might the dispute system look like?

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the updates. Since you simply want to use Polkadot-JS, I think you can remove it from the application and instead focus on the three pallets that you want to develop. For these, I recommend providing as many technical details as possible as part of the application. Also so it's clear what the difference between your solution and already existing solutions is.

**Comment by Polkaverse** [comment]
Thank you for questions @keeganquigley 
Let me give you my overall thought process. This will cover most of the questions. If you need any more clarification please let me know.
Ensuring the quality of jobs is an essential aspect of Aryaverse's platform. While Web2 freelancer platforms may have a significant market share, Aryaverse distinguishes itself through its decentralized nature and community-driven mechanisms. Here's how Aryaverse ensures job quality:

**1. Reputation and Feedback System:** Aryaverse implements a reputation and feedback system that allows both employers and freelancers to rate and review each other based on their experience. This system helps build trust and encourages high-quality work. Users with consistently positive feedback and higher ratings will establish a reputable profile, increasing their chances of securing quality jobs.

**2. Verified Profiles:** Aryaverse offers a verification process for freelancers to establish their credentials and skills. Verified profiles enhance trust and confidence among employers, ensuring they are hiring qualified professionals for their projects.

**3. Skills and Portfolio Showcase:** Aryaverse provides freelancers with the ability to showcase their skills, expertise, and previous work through a portfolio. This allows employers to assess the quality of a freelancer's work and make informed decisions when selecting a candidate.

**4. Dispute Resolution Mechanisms:** In the event of a dispute or disagreement between employers and freelancers, Aryaverse's self-governance system comes into play. The community of users can participate in the resolution process, ensuring a fair and impartial outcome. This mechanism promotes accountability and encourages both parties to maintain a high standard of work.

**5. User Ratings and Reviews:** Aryaverse encourages employers to provide detailed ratings and reviews for completed projects. These reviews serve as valuable feedback for freelancers and enable potential employers to assess their capabilities. User ratings and reviews contribute to the overall quality assessment of freelancers and assist in maintaining a high standard of work within the platform.

**6. Quality Assurance Guidelines:** Aryaverse establishes clear guidelines and standards for job postings, project requirements, and expected deliverables. By setting quality benchmarks, Aryaverse helps employers articulate their needs effectively and assists freelancers in meeting those expectations. Adhering to these guidelines ensures consistent quality across the platform.

By combining these strategies, Aryaverse aims to create a platform that upholds job quality standards, promotes accountability, and fosters a community of skilled professionals. The decentralized nature of Aryaverse empowers the community to actively participate in maintaining the platform's quality, setting it apart from traditional Web2 freelancer platforms.

We have our [discord server](https://discord.io/Aryaverse) but we haven't started campaign to build community yet. But we’ll do this as we move forward.

**Comment by Polkaverse** [comment]
Thanks @Noc2 for requesting changes. 
I have added some technical details in the application. Please take a look. 
Also for UI we are thinking that we’ll use polkadot UI until we release our testnet(this will be done in milestone 2). After that we’ll build our frontend that’s why we place frontend part in milestone 3.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. In this case, could you also add more details regarding the UI to the last milestone or maybe remove it for now and potentially apply for a follow-up grant later once you have these details? Milestone 2 also currently seems relatively expensive to me, compared to milestone 3 which contains a UI plus an additional pallet. Regarding the dispute pallet, how are the arbiters selected?

**Comment by Noc2** [comment]
I put the application on hold since we just received some information regarding it and that it might be based on somebody else's intellectual property, and we need to look into it.

**Comment by Polkaverse** [comment]
Thanks @Nco2 for the comments. I have updated the application because I see that some common names are present in another project. Also I have deleted the frontend part from the milestone 3 and added some more functionalities of conflict pallet.

Some changes which occurs: 
dispute -> conflict 
Smart-agreement -> work-contract

**Comment by MaxMasterVentures** [comment]
The design, description and business logic used for this application, as well as the code used to support this application, is proprietary code and information owned by- and created for Master Ventures. Pankaj Chaudhary (Polkaverse), who is a former contractor of Master Ventures was not authorized to use it for any purpose other than for his work at Master Ventures and is not the author or creator of the code.

Master Ventures already sent Pankaj Chaudhary a cease and desist notification in this regard. 

We also request that the Web3 Foundation does not consider and reject the application presented by Pankaj Chaudhary for the grant since the ownership of the code and IP does not lie with him. Furthermore we hope future applications of Pankaj (Polkaverse) do not include any code not written or ideated by himself and that the Web3 Foundation looks at future applications with a certain level of scrutiny.

**Review by semuelle — COMMENTED** [review]
> I have already forwarded the changes to the other project. Will let you know as I get confirmation.

I don't understand, can you clarify what you mean by this?

> I see that some common names and approach are present in another project.

What project is this? Can you share a link to it?

What is the status of Aryaverse, @Polkaverse? Do you have any public code yet?

**Comment by Polkaverse** [comment]
Hey @MaxMasterVentures, Yeah I agree that in our first release there are some similar documentation but now I have updated the whole application.Now I don't think there is something which is related to your project. And if you still think that this project is related to yours so you can share code with web3 foundation and let them decide. Also I haven't shared any code yet.

**Comment by Polkaverse** [comment]
@MaxMasterVentures Yeah i agree that in our initial release there is some documentation similarities. But now I have changed the whole application. Now i don't think there is any similarities left. If you still think there is any similarities then let web3 foundation decide that. Also I haven't shared any code for this application.

**Comment by Polkaverse** [comment]
@semuelle 
`I have already forwarded the changes to the other project. Will let you know as I get confirmation.
` mean i shared the updated application with Master ventures. The other project is master ventures with whom i worked in past. At that time the Project was in private repo. @MaxMasterVentures can you provide the details.

Currently Aryaverse is in ideation phase. We have not yet started the development of Aryaverse.

**Comment by semuelle** [comment]
> We understand that the non-sharing agreement prevents us from disclosing the details of Master Ventures' project. However, we strongly encourage Master Ventures to share the necessary information with the Web3 Foundation, enabling them to assess any potential similarities between our project and their proprietary code.

@MaxMasterVentures, could you get in touch with me via email (sebastian at web3 dot foundation) or Matrix (@sebastian:web3.foundation) to clarify this?

**Comment by MaxMasterVentures** [comment]
Not only the names were similar, but also the entire protocol logic was taken from the work we did at Master Ventures and in addition to that, the code that was used in a previous comment (since been removed) by @Polkaverse was copied 1:1 from our private repository, even leaving the same comments in the code, only removing a comment in the top that documented the original author of the code, who's one of our team members. 
As stated before, we do not tolerate this kind of behavior,  as @Polkaverse is in violation of Master Ventures IP rights and confidentiality rights under his previous employment agreement. Also considering that we are currently in the Substrate Builder’s Program, we thought it was only right to intercept this.
We see this as an attempt from @Polkaverse to defraud not only us, but also the Web3 Foundation, since the application is based on stolen IP. We will take all type of legal actions required against @Polkaverse if this continues.
We will be reaching out to you @semuelle to provide you with the information and evidence needed to properly understand and assess the situation.

**Pull request closed without merging**
