### PR TITLE
Amend Gafi Milestone 3

### PR DESCRIPTION
**Pull request by mutobui**
#### Project Abstract

> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant_guidelines_per_category.md).
- [x] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md)).
- [x] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@stefan_muto:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Comment by mutobui** [comment]
Hey W3F team,
We would like to amend milestone 3 by removing pallet_dao from delivery and lowering the cost by one-third 💪

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I’m happy to mark it as ready for review.

**Review by semuelle — APPROVED** [review]

**Review by keeganquigley — COMMENTED** [review]
thanks @mutobui, are you removing this deliverable because you plan to implement a DAO pallet that already exists?

**Comment by mutobui** [comment]
Hi @keeganquigley,
Thanks for the question
pallet_dao in the first place is designed for the game projects can create their own DAO, and in the development process, we find out this feature is better to implement at the DApps level (Solidity smart-contract). Thus, we want to remove it from the deliverable.

**Review by keeganquigley — APPROVED** [review]
thanks for the explanation!

**Review by takahser — APPROVED** [review]

**Review by dsm-w3f — APPROVED** [review]

**Comment by semuelle** [comment]
For reference, discussion here: https://github.com/w3f/Grant-Milestone-Delivery/pull/616

**Pull request merged**
