### PR TITLE
OpenSquare paid QA protocol

### PR DESCRIPTION
**Pull request by wliyongfeng**
### Project Abstract

OpenSquare Paid QA protocol is substrate `system#remark` extrinsic based, and it helps users share their knowledge in a way with bounties. A knowledge seeker can create a topic and promise a fund of tokens to useful answers. Any users can support a topic with a promise to fund tokens. Topic/question answers can just provide knowledge without worry about submission to a blockchain, while any others can do it. A topic author/supporter can resolve a topic at any time after the
creation/support action. Check the spec [here](https://github.com/opensquare-network/qa-spec).

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. I have a few initial questions: 

- Do you already have some mockups or initial designs, which you could share? 
- Could you add the IPFS script and interaction to the deliverables? 
- What are potential attack vectors and do you plan to integrate some kind of conflict resolutions (e.g. Alice doesn’t pay)?

**Comment by 9ightmare** [comment]
In fact I have this idea only  and I need builders programmers so i can develop it

**Comment by 9ightmare** [comment]
How can I open a pull request?

**Comment by Noc2** [comment]
@9ightmare could you please stop commenting on this PR, unless it’s relevant to the application itself. Regarding opening a pull request, I suggest you search for “pull request github” and in general to make yourself familiar with the process.

**Comment by wliyongfeng** [comment]
Hi @Noc2 , thanks for the feedback.

> Do you already have some mockups or initial designs, which you could share?

We have started the design job, and will post here several key pages in 1 or 2 days.

> Could you add the IPFS script and interaction to the deliverables?

I have added more deliverables to make it more clear. Plz tell me if they are still not enough.

> What are potential attack vectors and do you plan to integrate some kind of conflict resolutions (e.g. Alice doesn’t pay)?

Technically speaking, either the author or answerer may attack, and the situations maybe:
1. The author may create many topics without real future fund
2. The answerer may create many uninformative answers

For the 1st situation, we have following thinkings:
1. Every `NEW` interaction need a on-chain extrinsic which means the author has to pay gas for it. So attacks with huge topics have costs.
2. Centralized ways can be applied to arrange how to show the topics. For example, show at most 5 topics at time for one author, pin some more high quality topics, etc, different implementers may apply different strategies. Sure it sounds not so cool because it's not so decentralized, but we'd prefer to keep the 1.0 spec as lightweight as possible.
3. There are possibilities that Alice may just forgot the topic and will never fund it. We think these kinds of exceptions are acceptable, since QA bounties are usually small sized and it usually won't cost answers too much efforts.
4. One author may create several topics without any pay in a long time even got valuable answers. Here blockchain works, we tracked the author's history behaviors and any user can see this dishonesty, then few future answerers will reply to the author's topic.
5. One attacker may create many accounts and create many topics for an attack purpose. If the topics are meaningless, then No.2 centralized ways maybe applied to handle them. If some topics are useful and got valuable answers, but the topic author won't pay any fund, other supporters can still fund the valuable answers. If dapp implementer has token issued, then dapp may award the valuable answer providers. For example, OpenSquare may award this kinds of valuable answers if we issue tokens.

For the 2nd situation:

Sure the attacker can achieve this with low cost. It will mainly rely on the dapp implementer to handle it in centralization way similar with No.2 thinking for the 1st situation.
- Dapp implementers may not submit the uninformative answers to blockchain.
- Dapp implementers may just hide the obviously useless answers.
- Dapp implementers may provide features to let users to hide some answers.

There indeed have solutions to make it more decentralized, like introducing admin assignment interaction to elect council member roles and the admins can vote to close topics/answers, but for the 1st version I'd prefer to make it lightweight.

**Comment by wliyongfeng** [comment]
@Noc2 Please check part of our designs. Not all settled, but you can see an initial design of the topic list/detail and user profile pages. Thanks.

https://www.figma.com/proto/vqpglMGW8psHKB00eIVDUV/OpenSquare?page-id=3655%3A16149&node-id=3659%3A30988&scaling=min-zoom&hide-ui=1

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the quick and detailed reply. I agree that a first prototype doesn’t need to be fully decentralised, but it’s good to know that you are already thinking about some kind of on-chain admins/council system. Also a transparent rating system that shows historical behaviour is probably important here. I currently can not open your link. It’s probably private. Could you update this and also add the link to the application?

**Comment by wliyongfeng** [comment]
Sorry for the miss. Plz try this [link](https://www.figma.com/proto/vqpglMGW8psHKB00eIVDUV/OpenSquare?page-id=3655%3A16149&node-id=3659%3A30988&viewport=322%2C48%2C0.08&scaling=min-zoom).

> Also a transparent rating system that shows historical behaviour is probably important here.

Yes, OpenSquare's longterm goal is to build users' reputation/credit model based on on-chain collaboration behaviours. We have investigated some mechanisms to promote user levels, like that of StackOverflow. They are definitely in plan.

**Comment by wliyongfeng** [comment]
Thank you. Updated with 22d100303723d7a2d9244b6bd2d5dfde014dc3d1.

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I’m happy to go ahead with it and I will share it with the rest of the team.

**Comment by laboon** [comment]
Looks interesting! Couple of questions though...

1. What happens if Alice is adversarial? For example, somebody answers her question, she could just refuse to pay. Can she take her money back, or is "stuck"?
2. Since this is all happening with remarks, how are any funds actually locked? Or this is only based on promises? If this is so, couldn't you use something like Subsocial (or a centralized site)?
3. What happens if nobody does / can answer, or gives very bad answers?

**Comment by wliyongfeng** [comment]
@laboon Hi Bill, thanks for your question.

> What happens if Alice is adversarial? For example, somebody answers her question, she could just refuse to pay. Can she take her money back, or is "stuck"?

I answered similar question from Daivd [here](https://github.com/w3f/Grants-Program/pull/786#issuecomment-1015498628). Generally speaking, 

- It cost gas for Alice to attack by sending many topics.
- Corresponding reputation can be build and shown to answerers which may prevent users from answer topics from Alice.
- QA bounties are usually small sized. It's fine for good answers not awarded in some cases.
- We can apply centralized solutions by dapp implementers though.

No money locked. Creating a topic means a promise/claim/broadcast.

> Since this is all happening with remarks, how are any funds actually locked? Or this is only based on promises? If this is so, couldn't you use something like Subsocial (or a centralized site)?

We have some partnerships with Subsocial and we once discussed about the possible integration for our product like [dotreasury](https://www.dotreasury.com/ksm) or [off-chain voting](https://voting.opensquare.io/). The SUB token gas is my main worry even I know there is a faucet.

To this QA product, we have to take trade off between following items:
- Scalability. Using `remark` will make it very easy to be applied to other chains which means users can choose to fund various tokens. We have to rely on some kind of bridge/HRMP? to achieve this.
- Lightweight. It’s either on the technical side and business side. Currently we don’t have to use a pallet to implement the business.
- User experience. I want users to get the same experience as web2 in a web3 app. At least for the answerers, they don’t have to wait blocks while any others can submit their answers afterward, and don't have to pay gas for giving an answer.

> What happens if nobody does / can answer, or only gives very bad answers?

For example, if Alice asks a very difficult question, no one gives any answers or only bad answers are given in 3 months. Then there may be branches:
- Alice just `RESOLVE`s the question. Dapp implementer will decide how to handle this behavior. OpenSquare will not treat this dishonest behavior. It means if we have a credit score, this behavior won’t cause score loss.
- Alice does nothing. This topic will go down and down in the topic queue as that in any other forum like products.
 
The most tricky part here is how to decide whether an answer is valuable to a topic and how to handle it if Alice refuses to pay while she even gets an mostly accepted answer. I’d say currently there are no technical solutions that can handle it, and we have to apply governance mechanisms to for example promote user levels.

**Review by gautamdhameja — APPROVED** [review]
LGTM!

**Comment by laboon** [comment]
I apologize for the delay in responding here. I appreciate the candor that there are some issues that will be hard to solve. I will approve this.

**Review by laboon — APPROVED** [review]

**Pull request merged**
