### PR TITLE
Edubuk's Grant application Level 1

### PR DESCRIPTION
**Pull request by edubuk**
### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Comment by edubuk** [comment]
Pull request for Edubuk's grant application.

**Review by edubuk — COMMENTED** [review]
final

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. As part of your application, you are currently deleting the application template. Could you please update this? Also our grants program focuses on Polkadot, Kusama, Substrate and ink! projects. We don’t support Polygon projects, also simply because we don’t know much about it. Would you be willing to leverage our tech stack for your project?

**Comment by edubuk** [comment]
> Thanks for the application. As part of your application, you are currently deleting the application template. Could you please update this? Also our grants program focuses on Polkadot, Kusama, Substrate and ink! projects. We don’t support Polygon projects, also simply because we don’t know much about it. Would you be willing to leverage our tech stack for your project?

Sure, yes we are open to use and leverage your tech stack and have our project hosted on the Polkadot blockchain.

**Comment by edubuk** [comment]
> Thanks for the application. As part of your application, you are currently deleting the application template. Could you please update this? Also our grants program focuses on Polkadot, Kusama, Substrate and ink! projects. We don’t support Polygon projects, also simply because we don’t know much about it. Would you be willing to leverage our tech stack for your project?

Our application is saved here: https://github.com/edubuk/Grants-Program/blob/master/applications/edubuk.md

I dont think, we deleted it (may be by mistake: but here it is saved at the above link).

**Comment by edubuk** [comment]
Hi @Noc2:
Can you please help me with the commands, how to undelete it so that it
does not deletes your original application, please? I will do exactly as
you say, but please guide on this one. Sorry for the inconvenience.

**Review by edubuk — COMMENTED** [review]
ok final updated file.

**Comment by edubuk** [comment]
Hi David,

Any next steps on our application, please let us know?

Thanks,
Apoorva

**Review by Noc2 — CHANGES_REQUESTED** [review]
Hi. You are still deleting the template as part of the PR. If it’s easier, feel free to close this PR and open a new one. Also please take a look at our template https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md and the milestone there. For example, deliverables 0a-0d of the template are usually mandatory for all milestones

**Comment by edubuk** [comment]
Sure, thanks for the clarity, we will resubmit the application and include
0a to 0d also.

**Pull request closed without merging**
