### PR TITLE
Add FanChain proposal

### PR DESCRIPTION
**Pull request by jamesnguyentech**
#### Project Abstract

FanChain is a decentralized platform aiming to empower content creators, particularly streamers and influencers, by providing them with tools for creating and trading NFTs and managing their communities. The platform is designed to leverage the Polkadot ecosystem, providing a seamless and secure experience for both creators and fans. 

#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $30,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [x] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [x] Payment details have been provided (bank details via email _or_ BTC, Ethereum (USDC/DAI) or Polkadot/Kusama (USDT) address in the application).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. But could you add more technical details to the specification of the deliverables? For example, the programming/smart contract language, or are you going to use the unique pallet for this, or what kind of NFT standard in general? And just to double-check: Are you aware that the delivery needs to be open source and publicly shared for this grants program? Regarding: 

> " strict security and confidentiality policies, and we cannot publicly share our source code on GitHub"

**Comment by jamesnguyentech** [comment]
Thank you for your feedback. 

We confirm that the developed product for the Grant Program will be open-sourced.

Regarding the technical details:

- Our primary smart contract language will be Solidity, given its compatibility with EVM-supporting parachains.
- For NFT standards, we plan to use ERC721 and ERC1155 (future plan).

We hope this provides the necessary clarity. We are happy to provide further details if required.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. However, we usually don't support the development of solidity smart contracts. We instead support the development of technology that is native to our ecosystem, like ink!. Also, ERC721 is a standard that is already implemented, and my assumption would be that there is also already a fair amount of basic open-source UI for it. So, to be honest, I don't see the value of this project. But I will share it with the rest of the team. Maybe they have a different opinion about it.

**Comment by jamesnguyentech** [comment]
The difference between our platform and others is that users can customize NFT during the minting process, community management, and stream donating. We really want to create a platform that can reach as many users as possible, want it to be able to create a phenomenon so we are choosing Solidity. Although we can do ink! would like to receive your recommends.

**Comment by Noc2** [comment]
The users don't necessarily care about the smart contract language. But we do since we want to kickstart different tech stacks in our ecosystem.

**Comment by jamesnguyentech** [comment]
Thanks for your recommendations. 
In order to be more suitable for the grant program, we decided to switch the tech stack to use ink! smart contract as our original plan. 
Hopefully, it will make more sense to you.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. In this case, I have a couple of follow-up questions:
- Regarding the delivery "Smart Contract" of your first milestone, what are you going to implement here? Also, take a look at https://github.com/paritytech/ink-examples
- Could you, in general, add more details to the specification of the milestone deliveries? For example, regarding "Provide tools for creating algorithmically generated NFTs", what kind of tools are you going to provide? 
- Are you going to implement smart contracts for the Marketplace?

**Review by semuelle — COMMENTED** [review]
Thanks for the application, @jamesnguyentech. 

Based on the features, architecture and mockups, it's clear that you have put a lot of thought into this project. However, in its current form, the application is not a good fit for the grants program. We are looking for deliverables that constitute technical novelties, and most of what you are proposing already exists in one way or another. The other deliverables are centralised components that are too specific to your platform to be useful for others. 

If you can show how your smart contracts differ from or improve upon existing implementations, I'd be happy to support those. Otherwise, feel free to wait for other committee members to chime in.

**Comment by jamesnguyentech** [comment]
Hi @Noc2,
I'd be happy to provide answers to your follow-up questions:

1. Smart Contract Implementation in First Milestone:
- NFT contract: based on erc721 contract, allowing customizable attributes on minting.
- Collection Controller contract: NFT factory, ensures proper minting process, handles fees.
- NFT Marketplace contract: enables buying/selling NFTs with ownership transfer, payments, and potential fees.


2. I have updated more details of the milestone deliveries.
Additionally, The tool that I mentioned is a feature located in the creator's dashboard, that allows creating an NFT collection, creating each layer for the NFT, inputting each image for each layer, and then combining it into a complete NFT. 

3. Of course, we'll implement smart contracts for the Marketplace. I'll finish it on the first milestone.

**Comment by jamesnguyentech** [comment]
Hi @semuelle 
Thanks for your feedback.

I believe the biggest improvement in our first two milestones is the ability to select the components that make up an NFT. For example, you can choose a blue shirt, a smiling face, and a black hat, then mint them into the NFT you've chosen. 

Another aspect I've noticed is that currently, NFTs use ink! haven't been widely utilized. I have searched for some NFT marketplaces that support ink!, but it seems quite difficult to find, with no good performance. I trust that our team can address this challenge and deliver a better solution.

We are really looking forward to completing the platform, in order to move towards larger goals regarding community management and streaming donations. We would love to hear more suggestions from you.

**Review by semuelle — COMMENTED** [review]
Thanks for the updates, @jamesnguyentech. 

> 3. Of course, we'll implement smart contracts for the Marketplace. I'll finish it on the first milestone.

This is not listed as a deliverable.

> The difference between our platform and others is that users can customize NFT during the minting process, community management, and stream donating.

Some of the features you have planned sound interesting, but I still think that the deliverables you are proposing are not a good fit for the grants program, so I won't approve the application. I don't know if composable NFTs exist in ink!, so this might be worth pursuing, but this would be doable with a Level 1 grant.

**Comment by keeganquigley** [comment]
Thanks for your efforts @jamesnguyentech in putting together this proposal. I will also pass on the application, as in my opinion, many of the deliverables are beneficial only to you, but also for the reasons listed above. I would also be game for approving just the composable NFT ink! contracts at first, so that would give you two approvals right there if you were to drop it to a level 1. Perhaps the [treasury](https://wiki.polkadot.network/docs/learn-polkadot-opengov-treasury) would be more interested in funding the platform.

**Review by takahser — CHANGES_REQUESTED** [review]
@jamesnguyentech I won't approve it either for the reasons already expressed by other members of the committee - I don't think it's a good fit with our program. Nevertheless, I wish you good luck and success with your project and welcome you to submit another proposal in the future!

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the application and all the effort you put into this. However, the grants committee decided today that we won't support the project. Let me know if you have any questions and feel free to apply with another project.

**Pull request closed without merging**
