### PR TITLE
STYLE Protocol grant Application 

### PR DESCRIPTION
**Pull request by enghamzasalem**
#### Project Abstract

STYLE Protocol brings true monetization and utilization to any Virtual Asset in any game, metaverse or virtual world – based on NFT-sublicensing mechanisms, the protocol enables true interoperability of Virtual Assets and NFTs across such multiverses. STYLE Protocol aims to be the hub that bridges the current gap between web 3.0 and, e.g. gaming companies (and others) to create interoperability and cross-multiverse utilization while being embedded in play/rent/…-to-earn principles and guilds, always assuring decentralized frameworks. The goal is to further enhance users (e.g. players/customers) to utilize assets they create, own, or repeatedly use across metaverses, games and virtual worlds.

The decentralized interoperability protocol we build has the same structure as the Polkadot Ecosystem. It has its main pillar which is a DAO and around that we have Owners (Owners are people bringing Assets into the protocol to be used within the ecosystem. These can be existing NFTs or off-chain 3D files), Tailors (Tailors are manipulating Digital and Virtual Assets to enable them to be used across multiverses, e.g., creating a 3D image from a 2D asset or fitting a 3D asset for an environment) and Environments (Environments are virtual worlds, metaverses or any ecosystem within the multiverse utilizing the protocol’s supply chain to bring Assets into their world for their players and customers to use). These three “Para-ecosystems” fuel the decentralized protocol to get work all together.
#### Grant [level](https://github.com/w3f/Grants-Program#level_slider-levels)

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [X] **Level 2**:  Up to $30,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for >$100k: Web3 Foundation Council approval)

#### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied and aptly renamed (`project_name.md`).
- [ ] I have read the [application guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant_guidelines_per_category.md).
- [ ] A BTC, Ethereum (USDT/USDC/DAI) or Polkadot/Kusama (aUSD) address for the payment of the milestones is provided inside the application.
- [X] The software delivered for this grant will be released under an open-source license specified in the application.
- [ ] The initial PR contains only one commit (squash and force-push if needed).
- [ ] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process) (see the [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md)).
- [ ] I prefer the discussion of this application to take place in a private Element/Matrix channel. My username is: `@_______:matrix.org` (change the homeserver if you use a different one)

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. I have a couple of questions/comments regarding your deliveries: 

- Regarding the “wallet connect” delivery of your first milestone, what exactly does it mean that you integrate STYLE protocol with polkadot.JS? Is this only the UI integration, or do you also use some kind of bridge for it? Or do you even deploy your style smart contracts on polkadot? 
- How do you ensure the security of your staking mechanism? 
- Besides rmrk, it might make sense to support another alternative in our ecosystem like the uniques module (https://github.com/paritytech/substrate/tree/master/frame/uniques). We generally don’t want to support one specific parachain and need to be as objective as possible. Did you already reach out to rmrk directly? 
- In general, feel free to add as many technical details to the specification of the deliverables as possible (programming language, etc.). This makes it also easier to understand the details of it.

**Comment by enghamzasalem** [comment]
@Noc2 thank for your questions/feedback 
Q1- Regarding the “wallet connect” delivery of your first milestone, what exactly does it mean that you integrate STYLE protocol with polkadot.JS? Is this only the UI integration, or do you also use some kind of bridge for it? Or do you even deploy your style smart contracts on polkadot?

- It is UI integration and bridging NFTs from Polkadot parachain/RMRK standard.

Q2- How do you ensure the security of your staking mechanism?

- We will use relayer to read both chains and check staking status(if you mean staking between chains).

Q3- Besides rmrk, it might make sense to support another alternative in our ecosystem like the uniques module (https://github.com/paritytech/substrate/tree/master/frame/uniques). We generally don’t want to support one specific parachain and need to be as objective as possible. Did you already reach out to rmrk directly? 

- I totally agree with you; mostly RMRK is the most requested standard from our users to support in STYLE protocol, so our plan is to integrate fully with them and after that support all other parachains.


In general, feel free to add as many technical details to the specification of the deliverables as possible (programming language, etc.). This makes it also easier to understand the details of it.

**Review by Noc2 — CHANGES_REQUESTED** [review]
@enghamzasalem  Could you update the application accordingly? What exactly do you mean by “bridging”? It currently sounds relatively centralized to me and extremely dependent on the UI itself.

**Comment by enghamzasalem** [comment]
Hi @Noc2 !
I have pushed the changes to MileStone 1; when we say "bridging" we mean the whole process of moving assets from RMRK to STYLE <>.
BR.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the quick reply/update. Could you still sign the terms and conditions (see CLA bot above)? How exactly are you moving assets from RMRK to STYLE?

**Comment by enghamzasalem** [comment]
Done.

- Users will stake RMRK NFTs to STYLE using relayer/bridge(it will be smart contract from our side and RMRK SDK integration or it can be another smart contract on moonriver)

- Users who owned STYLE NFTs or any EVM NFTs can mint it based on RMRK standard and use there by using the bridge to stake and mint in RMRK.

In all cases, the main idea is giving the ability to bridge NFTs between STYLE standard and RMRK standard in easy way as our users want.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the quick reply.  I’m happy to mark the application as ready for review. However, I personally won’t approve it yet, because it’s not fully clear to me how exactly the connection to the STYLE protocol and the relayer is working. Is this a centralized relayer or a multsig or even a decentralized solution, etc.? Given that your token seems to be an ERC20 on ethereum and you focus on interoperability, this is probably the most important part of it.

**Comment by enghamzasalem** [comment]
Thank you @Noc2 for you comments

What do you recommend to make it clear? i was writing the application in the simplest way for technicals and non technicals  stakeholder and focus on the output functionality. 
As i mentioned before, relayer can be smart contract on both chains moonriver and ethereum to validate transactions for staking NFTs on both chains.

**Comment by Noc2** [comment]
But how exactly is this implemented? Do you have a whitepaper or something similar that describes the technical details of it or open-source code that you could share?

**Comment by enghamzasalem** [comment]
It is smilier to bridging between layers here https://ethresear.ch/t/bridging-nfts-across-layers/10799
but mainly the smart contract will be on Ethereum and moonriver and the logic that will be written smilier to these functions
`
 // swapin `tokenId` of `token` in `fromChainID` to recipient `to` on this chainID
    function nft721SwapIn(
        bytes32 txHash,
        address to,
        address sourceTokenAddress,
        uint256 sourceTokenId,
        string calldata tokenURI,
        uint256 fromChainID,
        bool isDerivative,
        string memory name,
        string memory symbol
    ) external override {
        if (isDerivative) {
            _protocol.mint(
                sourceTokenAddress,
                sourceTokenId,
                to,
                tokenURI,
                name,
                symbol
            );
            emit LogNFT721SwapIn(txHash, to, fromChainID);
        } 
    }

    // swapout `tokenId` of `token` from this chain to `toChainID` chain with recipient `to`
    function nft721SwapOut(
        address to,
        address tokenAddress,
        uint256 tokenId,
        uint256 toChainID
    ) external payable override nonReentrant {
        if (_protocol.isDerivative(tokenAddress)) {
            _transferFee();
            string memory tokenURI = IBase(tokenAddress).tokenURI(tokenId);
            IBase(tokenAddress).burn(tokenId);
            emit LogNFT721SwapOut(
                msg.sender,
                to,
                toChainID,
                true,
                tokenURI,
                tokenAddress
            );
        }
    }

`

**Comment by keeganquigley** [comment]
Thanks for the additional info @enghamzasalem, however, we don't generally support Solidity/EVM development. Would you be willing to implement these as ink! smart contracts instead?

In addition, I agree with David that we would need more technical information about how the bridge works exactly. Your [whitepaper](https://www.protocol.style/_files/ugd/87669b_a007378b197e419eb5ffb5a9d25c625c.pdf?index=true) gives a high-level overview of the architecture but doesn't really explain in detail how the non-EVM bridging would work. 

Also, I noticed in your whitepaper that you are planning to conduct a token LBP sale. Has this happened yet? Please note our [FAQ](https://github.com/w3f/Grants-Program/blob/master/docs/faq.md#can-anyone-apply) page when it comes to token sales.

**Comment by enghamzasalem** [comment]
Hello @keeganquigley ! thank you for your reply.
Indeed we are issuing a utility-token as backbone for the ecosystem infrastructure and to reward participants of the protocol and enable further utility for these holders. We were hoping to participate in the grant program as we are integrating to some of the Polkadot's ecosystems para-chains and NFTs project Such as RMRK and other standard.

**Comment by Noc2** [comment]
Thanks again for your interest in the grants program and your application. However, the grants committee decided to not support this project, mostly because of the concerns regarding your bridge. Therefore, I’m closing the application. Feel free to apply for another grant and independent of the grant application, we wish you all the best for your project.

**Pull request closed without merging**
