### PR TITLE
Integrating Polkadot.js with Blackprint

### PR DESCRIPTION
**Pull request by StefansArya**
### Project Abstract

Blackprint is a visual programming tool that can help developers interact with libraries by simply connecting nodes in realtime without the need to code. Developers themselves will need to use Blackprint Engine and load required modules to execute exported JSON of node, cable connections, and embedded data.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Just one quick initial feedback. The deliverable and specifications currently don’t mention polkadot, kusama or substrate. Could you try to integrate this? And in general feel free to add additional technical details, like for example programming language, etc. The deliverables are basically the requirements of our contracts.

**Comment by StefansArya** [comment]
Hi! Thanks for the feedback.

I have updated the specification and mention "parachain" instead, where parachain is referring to Polkadot/Kusama or Westend testnet. By the way, thanks for remind me about the deliverables. I got realized I incorrectly wrote WebSocket into WebRTC, I was a bit sleepy that night 😅.

About additional technical details, I'm still unsure what to add because it may get changed in the future (especially when I want to improve it). I think I will put video instead and add some explanation to make it easier to understand about this proposal.

This proposal is supposed to be a Development Tools (IDE / IDE plugin) specific for the client side (Browser/Node.js), and the programming language that I will use is JavaScript like I mentioned in the "Technology stack" section.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the quick reply and adding the videos. 
> 'Where parachain is referring to Polkadot/Kusama or Westend testnet. 

Just for clarification: Polkadot, Kusama and Westend are [relay chains](https://wiki.polkadot.network/docs/learn-architecture#relay-chain). Do you mean the relay chains or do you mean (all) parachains of these relay chains?

**Comment by StefansArya** [comment]
Hi, Thanks for the clarification.

I mean all of parachain on these relay chain including the relay chain itself if [Polkadot.js library](https://github.com/polkadot-js/api) could connect into it via RPC, but does the scope was too large for this proposal? 🤔 -- maybe I was missing something

If [Polkadot.js library](https://github.com/polkadot-js/api) does work for them, then my Blackprint module will also work.
I also have tried to transfer WND balance between account on Westend network, and it's does work.

It's also can connect for this network via RPC with help of [Polkadot.js library](https://github.com/polkadot-js/api):
 - Aleph Zero: wss://ws.test.azero.dev/
 - Shibuya: wss://rpc.shibuya.astar.network/
 - Polkadot: wss://rpc.polkadot.io/
 - Westend: wss://westend-rpc.polkadot.io/

But because Aleph Zero also claim itself as a public blockchain, actually I think it's more suitable if I refer them as test/mainnet. Now I become confused what I should write on the proposal 😅.

**Review by Noc2 — APPROVED** [review]
Okay, thanks for the response. So your tool will probably work with all chains that support polkadot.js. I’m happy to go ahead with the application and will share it with the rest of the team.

**Review by mmagician — COMMENTED** [review]
I don't have the best experience supporting drag-and-drop tools for blockchain.  They are very difficult to maintain due to fast-moving API, features being constantly added and so the tools simply were left to "die". Also, I personally prefer seeing the code as-is, and I might be wrong but I feel like most developers will be more comfortable coding rather than using visual features.
It's nothing against your project - and it's great to see that you have an existing prototype already. I still wish you best of luck and hopefully someone else from the Grants Committee can support the application! I'd be gladly proven wrong :)

**Comment by StefansArya** [comment]
Hi @mmagician! Thanks for your comment.

Maybe you have tried something like [EtherScripter](https://etherscripter.com/) or other tools that using UI like jigsaw puzzle. I have tried EtherScripter but it feels like visual scripting (writing code but by drag and drop the code), and yes.. I feel like writing text code seems more straight forward and comfortable for me. I think you're not wrong. But it's also just my opinion, maybe someone out there actually finds it useful.

If I compare with them I think Blackprint design is more different, each input/output port has its own data type and it will reject any cable connection that doesn't meet some criteria (like `input` port being connected to `input` port, or port with `Number` data type being connected to port for `String`).

To bring the UX to the next level, I also added a feature to suggest nodes that can be connected by using `CTRL + Right click` on the input or the output port. So without reading the documentation the user can find out which nodes he can connect to that port.
<details>
  <summary>Click here to see the picture</summary>

PDQ0Lt4dS5
</details>

Without that feature, user may think:
For the **input** port: `how or where I can get value for this port?`
For the **output** port: `what is this value/output for and to which node can I connect this?`

The same issue may happen for traditional programming with script:
```js
let audio = new Audio();
// What I should do next with this object, how can I play my .mp3 files?
```
But usually having documentation, example, and intellisense does solved this issue.

---

Because Blackprint is designed to use nodes that was imported from a module (just like a plugin/addons), Blackprint can be a general purpose visual programming tool that can be used for both frontend and backend. If you have seen the picture above, you may noticed that I already [have nodes](https://github.com/Blackprint/nodes-arweave) for [Arweave](https://docs.arweave.org/developers/). Because Arweave also has libraries for PHP and Golang, the exported JSON from Blackprint may also work for the target environment if the modules have been developed for the target language. Blackprint Engine currently [supports](https://github.com/Blackprint/Blackprint#blackprint-roadmap) JS/PHP/Golang, and the most updated engine is currently for JavaScript.

But yes.. because Blackprint is depends on its modules, the current consequences is Blackprint can't generate code by itself. I want to support code generation for Blackprint, but thinking the best design/technique for it is not easy -- especially if the target language is not just JavaScript or Golang.

But apart from the drawbacks, we can attach an event listener into Blackprint nodes to listen if the value was changed and we can programmatically change the port value with code after we add an ID to the target nodes. Blackprint can also be integrated with some frontend frameworks like Vue and React, and I have created [some examples](https://github.com/Blackprint/Blackprint#example) of it today for proof of working concept. But when I created that, I was thinking to change some API from Blackprint Engine to make it more perfect 😅 

---

Well, it is just for additional information. I was pretty happy to read your comment @mmagician :)
I think I will also discuss about UX with my friend while waiting for other committee, he seems to have great interest for Blackprint and want to offer help about the documentation even though I haven't asked him.

Btw sorry if my comment was too long 🤣.
<details>
  <summary>If you're going to try current Blackprint Editor</summary>

[Blackprint Editor](https://blackprint.github.io/) doesn't automatically load all available modules from NPM repository, and you will need to select which module you want to use. But if you're importing JSON or using the example, it may load the modules for you. The loaded modules can be found on either from the menu or with button on the right top.

loaded-module

</details>

**Comment by alxs** [comment]
Hi @StefansArya, thank you for your application. I'm afraid I agree with Marcin here and also won't support your application. Besides, I feel like this is a very niche use case - it's a cool project, but I'm not sure it would benefit other teams in the ecosystem. Best of luck.

**Comment by StefansArya** [comment]
Well, it's okay.
Thanks for taking time for reading my application @alxs.

Maybe I will look for grants on metaverse project as some developer may want to develop a game without coding. And also, I think I will still publish the [module](https://github.com/Blackprint/nodes-polkadot.js) to the NPM registry because I may need it for interacting with blockchain's RPC from the metaverse that using Blackprint, maybe like for creating MVP/prototype/experiment.

By the way, is it okay if I reopen this application after Blackprint has been adopted by many developers/projects? Maybe on end of the year if I still actively working on open source and not delay/ended up because working somewhere 🤔 

Actually I will be happy if you guys want to negotiate the milestone/costs so I can still have hope on here 😅

**Comment by Noc2** [comment]
@StefansArya Thanks for the quick reply. I will share the application again with the rest of the team and let you know in case someone else would be interested in it. The fact that two people didn’t approve it, doesn’t mean it’s rejected.

**Comment by StefansArya** [comment]
Ahh sorry.
Thank you for keeping this application alive @Noc2

**Comment by laboon** [comment]
I actually think this could be very useful for quick scripting, and hopefully guide more people into interacting with the chain at the Polkadot API level.

I share Marcin's and Alex's concern about keeping it up to date, but I think a properly modularized software architecture would make this feasible (although not easy!) to maintain.

**Review by laboon — APPROVED** [review]

**Pull request merged**
