### PR TITLE
application-BikaToken.md

### PR DESCRIPTION
**Pull request by JohnRodriguez23**
### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Comment by JohnRodriguez23** [comment]
Dear, I am the CEO of the Bika Token project, I need funds for project development, Level 1 grants and I want to immediately get information from Polkadot regarding the request for grants immediately, I will carry out project development in the next month after receiving funding from Polkadot , thank you for polkadot web3, i will make changes and will introduce the project from polkadot it's really great.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the interest in our grants program. However your application is currently missing a lot of details. For example your milestone is a simple copy of the template. Let us know once you filled out all the details and removed the text from the template.

**Comment by JohnRodriguez23** [comment]
Hi, I'm Arif from the Bika Token project, my project wants to migrate to
the Polkadot network and use the polkadot ecosystem to create DAPPs with
the polkadot network, I need level 1 funding for initial development so I
can't provide details of the project while it's still a work in progress.
When will my project receive a grant from the web3 foundation?  I want to
immediately start the early stages of development, level 1 funds are
initial funds for the Bika Token project.

Regards
Bika Token

Pada tanggal Sen, 27 Des 2021 13.57, github-actions[bot] <
***@***.***> menulis:

**Comment by JohnRodriguez23** [comment]
I will provide project details according to the wishes of the web3
Foundation as best we can, I need help and support the project with funding.

Regards
Bika Token

Pada tanggal Sen, 27 Des 2021 15.30, Arif Rahman <
***@***.***> menulis:

**Comment by semuelle** [comment]
> I can't provide details of the project while it's still a work in progress. 

@JohnRodriguez23, without project details, we don't sign grants. Fill in the details outlined in the application template. You can refer to [previously accepted applications](https://github.com/w3f/Grants-Program/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed) to get an idea of what kind of information we are looking for.

> When will my project receive a grant from the web3 foundation?

Grants are paid out after milestone delivery, so you would have to have a signed grant agreement, submit the (first) milestone and have it approved by us before receiving any compensation.

**Comment by JohnRodriguez23** [comment]
Hi W3F, I have filled out the Grant application form and have filled in the project history and filled it completely, I want to get this grant fund for the development of the Bika project, I want to get it immediately, so that I can immediately do in-depth development and research on this big project, I  predicting the Bika project could match the metaverse project, this was one of the first projects I wanted to develop.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. However, the application still doesn’t specify unique technical deliveries that are potentially useful for others in our ecosystem as part of the deliveries of the milestones. Also you mention “A grand total of 50k USD.” (as well as Costs: 0,1 BTC?), but the only thing we would potentially fund as part of the grant is “project development, and more:15k USD.” and only in case it’s very specific and useful for the entire ecosystem. We don’t fund “promotion and purchase of 5K USD” or computer equipment, etc. Furthermore, you shouldn’t delete the application_template with your PR. In general, my recommendation is to look at our readme again (https://github.com/w3f/Grants-Program) as well as potentially look at merged grant applications (https://github.com/w3f/Grants-Program/tree/master/applications) to see what kind of information we usually expect.

**Comment by JohnRodriguez23** [comment]
Hi sir, I need funds from W3F level 1 and the remaining 50 thousand will be
obtained from Launchpad or other investors.  so that's a detail for the
future, so for starters I need a level 1 grant.

Regards
Bika Token

Pada tanggal Sel, 28 Des 2021 03.05, David Hawig ***@***.***>
menulis:

**Comment by JohnRodriguez23** [comment]
when can i get a grant i want to work on a development project.

Regards
Bika Token

Pada tanggal Sel, 28 Des 2021 07.13, Arif Rahman <
***@***.***> menulis:

**Comment by JohnRodriguez23** [comment]
So sir, I'll give you the details that you asked for, so that's just for Perongres in the future, now I need Grants level 1 funds or a total fund of around 10000 USD, as agreed by W3F in the grant program, I want to immediately get funds so I can develop  project please sir i need this fund.

**Comment by JohnRodriguez23** [comment]
So when do I get a development grant? are Grants level 1 funds very Hard to come by? I need grant funds urgently, thank you for the response.

**Review by Noc2 — CHANGES_REQUESTED** [review]
We don’t give away money for free. You need to fulfill the requirements of the grants program and provide the necessary information as part of the grant application. If you are seriously interested in receiving a grant please update the application and provide the necessary details, **otherwise I will close the application in the coming days**. Keep in mind that you receive only money for the successful delivery based on clear requirements.

**Comment by JohnRodriguez23** [comment]
Okay thanks for the response, I will improve the quality and improve the
details.

Regards
Bika Token

Pada tanggal Sel, 28 Des 2021 14.22, David Hawig ***@***.***>
menulis:

**Comment by JohnRodriguez23** [comment]
Hi sir, I have updated detailed information, so please agree and set grant
date soon, I want to do development soon so I don't have much time, my
project is a unique project which only Bika has, this project is also the
first project to issue an online novel based on  Defi and Games for user
entertainment is a very good combination so please accept our grant
application soon. So if you are confused, I have explained some of the
requested funds, namely 10000 USDT for Level 1 funds, I request funds
through USDT so that there are no misunderstandings. I hope W3F can provide
financial assistance to Bika, thank you for your attention.

Regards
Bika Token

Pada tanggal Sel, 28 Des 2021 15.02, Arif Rahman <
***@***.***> menulis:

**Comment by Noc2** [comment]
The application still contains the example milestones, and things like “Substrate module: X” also you are still deleting the template. Therefore, I’m closing the PR. Again, if you are really interested in a grant, you need to put a lot more effort into the application, before you submit another PR.

**Comment by JohnRodriguez23** [comment]
Okay, I am very interested in grant funds because I really need grant funds
and I will provide good details, thanks for the advice and support.

Regards
Bika Token


Pada tanggal Rab, 29 Des 2021 15.16, David Hawig ***@***.***>
menulis:

**Pull request closed without merging**
