### PR TITLE
Apsis

### PR DESCRIPTION
**Pull request by shengda**
### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

### For which grant [level](https://github.com/w3f/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [x] **Level 3**:  Unlimited, 5 approvals (for > $100k Web3 Foundation Council approval)

### Application Checklist

- [x] The [application template](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI/USDT) address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### CODE REVIEW

**Comment by mmagician** [comment]
Sounds interesting. Before our call tomorrow, perhaps you could shed some light on the following points please:
1. If I understand correctly, you are shifting the security assumption down the line, from trusting the oracle operator to trusting the data provider itself? The data provider (e.g. price supplied) can still submit arbitrary and malicious data. Do you have plans for aggregating responses from various data providers, detecting outliers etc.?
2. What exactly does a "proof for an HTTP API invocation" consist of? I've never heard of the ability to prove that you made a request. Do you mean verification of the authenticity of the response received from the server?

**Comment by shengda** [comment]
Thank you for the prompt feedback!

For the first question, yes, it removes the trust requirement for oracle operators. This can be better seen from the image below. Data aggregation for data points from multiple data sources can be done by smart contracts in Apsis EVM, so that we could validate the both the data points and the aggregation process. Data aggregation is one of the primary use case of Apsis EVM.

For the second question, you are right, it is used to prove an HTTP response is received from the server at the specific timestamp. What we try to phrase is more from a miner or DApp point of view, which means proof that the data is received by one that makes the HTTP API, but who makes the request is not important. We could definitely phrase it to make it more clear.

On-chain vs Off-chain Oracles

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks again for the very nice call. Just to follow-up here, regarding the potential next steps:

- Provide more information about the session keys
- Remove milestone 3 for now

**Comment by shengda** [comment]
Hi, thank you for your feedback on our application. Unfortunately, after further study we find that our previous solutions can't completely solve the shared key problem with the existing network protocols. Therefore, we've decided to suspend our application until we find a workable solution.

Thank you again for reviewing our application. We have strong belief in the web3 community and we will keep building on the Polkadot ecosystem.

**Comment by mmagician** [comment]
@shengda Thank you for the update, I appreciate the honesty and openness about your project. Please let us know if you have found a workaround, and also in case you have another project you want to work on in the meantime. You might get inspired by our open RFPs: https://github.com/w3f/Grants-Program/tree/master/rfps.

**Pull request closed without merging**
